<form id="frmManageSkillProfile"  method="post" action="<?=admin_base_url()?>members/member_details/modify_my_profile_skill_info_ajax/<?=$result['id']?>" onsubmit="return modify_my_skill_profile_ajax()" enctype="multipart/form-data">
<?php
	$count= count($result['skill_arr']);
	if($count==0)
		$count=2;
		
	$skill_no=0;
	for($i=0;$i<$count;$i++)    :
		
		$db_id= isset($result['skill_arr'][$i]['id'])? $result['skill_arr'][$i]['id']:'';
		$skill_no++;
?>

<table id="<?php echo "skill_".$skill_no;?>" width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table skill_info">

    <tr>
      <td align="left" valign="top" height="30" width="180" class="label skill"  >Skill <?php echo $skill_no;?></td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
        <input type="text" name="txt_skill[]" value="<?php echo isset($result['skill_arr'][$i]['s_name'])? $result['skill_arr'][$i]['s_name']:'';?>"/>
<?php
    if($i>1)
    echo '<td valign="top" align="left" style=" float: right;  margin-right: 170px;"><a class="close" href="javascript:void(0);" style="margin-left:5px;" onclick="admin_closeExtraSkillDiv('.$skill_no.')" ><img src="'.base_url().'images/icons/close.png" alt=""></a></td>';    

?>
      </td>
    </tr>
    <input type="hidden" name="skill_db_id[]" id="dbId"  value="<?php echo $db_id;?>"> 
</table>
    <?php 
        endfor;
    ?>
    
<table id="add_more_skill" width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
    
</table>


    
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
    <tr>
      <td align="left" valign="top" height="30" width="180" colspan="3">
        <a href="javascript:void(0);" class="add-one" onClick="return admin_add_extra_skill_div();">Add One</a>
      </td>
    </tr>
    <tr>
    
      <td align="left" valign="bottom" height="30" width="75" colspan="2">&nbsp;</td>
      <td align="left" valign="bottom">
      <input name="" type="submit" class="btn"  value="Update" />
      <input name="" type="reset" class="btn"  value="Cancel" onclick="cancel_edit_part_AJAX('skills')" />
      </td>
    </tr>
</table>        
<input type="hidden" name="total_skill_divs" id="h_skill" value="<?php echo $skill_no;?>"/>
 
 <?php /*?> //////////// NEW FIELD(S) [BEGIN] //////////// <?php */?>
     <input type="hidden" name="actual_skill_divs" id="actual_skill_divs" value="<?= count($result['skill_arr']) ?>" />
     <input type="hidden" name="deleted_skill_ids" id="deleted_skill_divs" value="" />
 <?php /*?> //////////// NEW FIELD(S) [END] //////////// <?php */?>
</form>