<form id="frmManageBasicProfile"  method="post" action="<?=admin_base_url()?>members/member_details/modify_my_profile_basic_info_ajax/<?=$result['id']?>" onsubmit="return modify_my_basic_profile_ajax()" enctype="multipart/form-data">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Languages I Speak</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" name="txt_lang" id="txt_lang" value="<?php echo $result['s_languages'];?>"/></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="70" width="180" class="label">About Me</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><textarea name="txt_about" id="txt_about" cols="" rows=""><?php echo $result['s_about_me'];?></textarea></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">My Church Name</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input name="txt_cname" id="txt_cname" type="text" value="<?php echo $result['s_church_name'];?>"/></td>
    </tr>
    
     <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church Address</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" name="txt_caddress" id="txt_caddress" value="<?php echo $result['s_church_address'];?>"></td>
    </tr>
    
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church City</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" name="txt_ccity" id="txt_ccity" value="<?php echo $result['s_church_city'];?>"></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church State</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" id="txt_cstate" name="txt_cstate" value="<?php echo $result['s_church_state'];?>"></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church Country</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
      <select name="txt_ccountry" class="txt_basic_country" style="width:238px; margin-bottom:6px;">
         <option value="">Select</option>
         <?= makeOptionCountry('', encrypt($result['i_church_country_id'])) ?>
      </select>
      
      </td>
    </tr>
    
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church Postcode</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" name="txt_cpostcode" id="txt_cpostcode" value="<?php echo $result['s_church_postcode'];?>"></td>
    </tr>
    
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Church Phone</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><input type="text" id="txt_cphone" name="txt_cphone" value="<?php echo $result['s_church_phone'];?>" /></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Denomination</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
      <select name="txt_denomination" id="txt_denomination" style="width:260px;">
         <option value="">Select</option>
           <?=makeOptionDenomination(encrypt($result['i_id_denomination']));?>
      </select>
      </td>
    </tr>
    
    
    <tr>
      <td align="left" valign="bottom" height="30" colspan="2">&nbsp;</td>
      <td align="left" valign="bottom">
      <input type="hidden" name="is_basic_submitted" id="is_basic_submitted" value="Y" />
      <input name="" type="submit" class="btn"  value="Update"/>
      <input name="" type="reset" class="btn cancel_btn"  value="Cancel" onclick="cancel_edit_part_AJAX('basic')" />
      </td>
    </tr>
</table>
</form>