<table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table text-table" id="member_basic_info_details">
<?php
	$church_add = $result['s_church_address'];
	$postcode   = $result['s_church_postcode'];
	$city     = $result["s_church_city"];
	$state    = $result["s_church_state"];
	$country  = get_country_name_by_id($result["i_church_country_id"]);  
	
	$basic_address=array();
	if(!empty($church_add))    
		$basic_address['church_add']=$church_add;
	if(!empty($postcode))    
		$basic_address['postcode']=$postcode;
	if(!empty($city))
		$basic_address['city']=$city;
	if(!empty($state))
		$basic_address['state']=$state;
	if(!empty($country))    
		$basic_address['country']=$country;
	
	
	$address= implode(', ',$basic_address);
?>
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">Languages I Speak</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $result['s_languages'];?></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">About Me</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $result['s_about_me'];?></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">My Church Name</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $result['s_church_name'];?></td>
    </tr>                            
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">Church Location</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $address;?></td>      
    </tr>
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">Church Phone</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $result['s_church_phone'];?></td>
    </tr>
    <tr>
      <td align="left" valign="top" height="25" width="180" class="label">Denomination</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" ><?php echo $result['s_name'];?></td>    
    </tr>
    
    
    <tr>
      <td align="left" valign="bottom" height="40" colspan="2">&nbsp;</td>
      <td align="left" valign="bottom"><a href="javascript:void(0);" class="edit-btn" onclick="show_edit_part_AJAX('basic')">Edit</a></td>
    </tr>
</table>