<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table02">
                               
                               
                                <tr class="blue_td">
                                      <th align="center" style="width:80px;">Hour</th>
                                      <th align="left">Reminder</th>
                                      <th align="left" class="last_td" style="width:140px;">&nbsp;</th>
                                </tr>
                                
                                <?php 
								
									$day = $selected_date;

									$startTime = date(strtotime($day." 00:00"));
									$endTime = date(strtotime($day." 23:45"));
									
									$timeDiff = round(($endTime - $startTime)/60/60);
									
									$startHour = date("G", $startTime);
									$endHour = $startHour + $timeDiff; 
									
									for ($i=$startHour; $i < $endHour; $i++)
									{
										for ($j = 0; $j <= 45; $j+=15)
										{
												
										  $time = str_pad($i, 2, '0', STR_PAD_LEFT).":".str_pad($j, 2, '0', STR_PAD_LEFT)."<br/>";
										  $com_time = str_pad($i, 2, '0', STR_PAD_LEFT).":".str_pad($j, 2, '0', STR_PAD_LEFT).":00";
										 
									?>			
									  <tr class="blue_td">
                                      <td align="center" valign="top"><?=$time?></td>
                                      <td align="left" valign="top" class="alarm">
                                    <?php if(count($note_list)){
								   		 	foreach($note_list as $key=> $not_val){
								   			
												if($not_val['t_time'] == $com_time){
								     ?>
                                      <p>Note: <a href="javascript:void(0);" class="blue_link"  onclick="return edit_note(<?=$not_val['id']?>);"><?=my_substr($not_val['s_description'],20)?></a></p>
                                  <?php 		}
											}
										 }
								   ?>  
								   <?php 
								   		if(count($todo_list)){
                                       		foreach($todo_list as $key=> $list_val){
                                        
                                        		if($list_val['t_start_time'] == $com_time ){
                                   ?>
                                      <p>To-Do-List: <a href="javascript:void(0);" class="blue_link"  onclick="return edit_list(<?=$list_val['id']?>);"><?=my_substr($list_val['s_description'],20)?></a></p>
                                  <?php 		}
											}
										 }
								   ?>  
                                        
                                        <!--<p>Event: <a href="javascript:void(0);" class="blue_link"  onclick="return show_dialog('edit_event')">Event Title Goes Here</a></p>-->
                                        </td>
                                      <td align="left" valign="top" class="last_td">
                                      	<p><img src="images/icons/add_note.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return add_note('<?=$com_time?>')">Add Note</a></p>
                                        <p><img src="images/icons/add_list.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return add_list('<?=$com_time?>')">Add To-Do-List</a></p>
                                        <!--<p><img src="images/icons/add_event.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return show_dialog('add_event')">Add Event</a></p>-->
                                      </td>
                                </tr>				
								 <?php
											}
									}
								
								 ?>
                                 
                                 
                                  <tr class="blue_td">
                                      <td align="center" valign="top">24:00</td>
                                      <td align="left" valign="top" class="alarm">
                                    <?php if(count($note_list)){
								   		 	foreach($note_list as $key=> $not_val){
								   			
												if($not_val['t_time'] == '24:00:00'){
								     ?>
                                       <p>Note: <a href="javascript:void(0);" class="blue_link"  onclick="return edit_note(<?=$not_val['id']?>);"><?=my_substr($not_val['s_description'],20)?></a></p>
                                     <?php 		}
											}
										 }
								   ?> 
                                    <?php 
								   		if(count($todo_list)){
                                       		foreach($todo_list as $key=> $list_val){
                                        
                                        		if($list_val['t_start_time'] == '24:00:00' ){
                                   ?> 
                                       <p>To-Do-List: <a href="javascript:void(0);" class="blue_link"  onclick="return edit_list(<?=$list_val['id']?>);"><?=my_substr($list_val['s_description'],20)?></a></p>
                                        
                                    <?php 		}
											}
										 }
								   ?> 
                                        <!--<p>Event: <a href="javascript:void(0);" class="blue_link"  onclick="return show_dialog('edit_event')">Event Title Goes Here</a></p>-->
                                        </td>
                                      <td align="left" valign="top" class="last_td">
                                      	<p><img src="images/icons/add_note.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return add_note('24:00:00')">Add Note</a></p>
                                        <p><img src="images/icons/add_list.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return add_list('24:00:00')">Add To-Do-List</a></p>
                                        <!--<p><img src="images/icons/add_event.png" alt="" /> <a href="javascript:void(0);" class="blue_link"  onclick="return show_dialog('add_event')">Add Event</a></p>-->
                                      </td>
                                </tr>		
                                 
                                
                                <?php  ?>
                                
                               
                          </table>