<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                          <tr>
                            <th align="left" valign="middle" height="30" width="70">Ad Image</th>
                            <th align="left" valign="middle" height="30" width="120">Title</th>
                            <th align="left" valign="middle" height="30" width="180">URL</th>
                            <th align="left" valign="middle" height="30" width="150">Posted By</th>
                            <th align="left" valign="middle" height="30" width="150">Post type</th>
                            <th align="left" valign="middle" height="30" width="80">Posting Date</th>
                            <th align="left" valign="middle" height="30" width="80">Publication<br />Start Date</th>
                            <th align="left" valign="middle" height="30" width="80">Publication<br />End Date</th>
                            <th align="center" valign="middle" height="30" width="88">Payment Status</th>
                            <th align="center" valign="middle" height="30" class="last"  width="88">Actions</th>
                          </tr>
                          <?php 
						  
						  	 if( count($info_arr) ) :
				   
							 foreach($info_arr as $info) : 
							  
							   $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
							   $name=getThumbName($info['s_image'],'thumb');
							  //echo $name;
								$IMG_THUMB = $IMG_THUMB_PATH . $name;
								 $id = $info['id'];
								$title = $info['s_title'];
								//$desc =  html_entity_decode(htmlspecialchars_decode($info['s_desc']),ENT_QUOTES,'utf-8');
								$image_rank= $info['image_rank'];
								$url = $info['s_url'];
								$i_user_id = $info['i_user_id'];
								$s_status = ($info['i_status'] == 1)?'HIDE':'SHOW';	   
						  
						  ?>
                          
                          <tr>
                            <td align="center" valign="top" class="banner-img"><a href="javascript:void(0);"><img src="<?=$IMG_THUMB?>" width="60" height="60" alt="image" /></a></td>
                            <td align="left" valign="top"><?=$title ?></td>
                            <td align="left" valign="top"><a href="<?=$url?>" target="_blank"><?=$url ?></a></td>
                            <td align="left" valign="top"><?php if($info['s_name']== 'Administrator'){ echo 'Administrator'; }else { echo $info['u_name'];  }?></td>
                            <td align="left" valign="top"><?=$info['p_loc']?></td>
                            <td align="left" valign="top"><?=getShortDate($info['dt_created_on'],5)?></td>
                            <td align="left" valign="top"><?=getShortDate($info['dt_start_date'],5)?></td>
                            <td align="left" valign="top"><?=getShortDate($info['dt_end_date'],5)?></td>
                            <td align="left" valign="top"><?php if($info['a_pay_status'] == 1){ echo '<font color=green>Payed</font>';}else if($info['a_pay_status'] == 0){ echo '<font color=red>Not Payed</font>';} ?></td>
                            
                            <td align="center" valign="middle" class="last">
                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='<?= admin_base_url() ?>site_settings/media_center_advertisement/edit-advertisement/<?= $id;?>'"/>
                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="delete_confirm(<?= $id ?>);"/>
                            <?php if($info['i_status'] == 1){ ?>
                            		<span id="<?=$info['id']?>_status"><input  title="Show" type="button" class="btn-01" onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 2 , <?php echo $info['i_status'] ?>)"  value="<?=$s_status?>"/></span>
                            <?php 
							    } 
								else if($info['i_status'] == 2){?>
                                	<span id="<?=$info['id']?>_status"><input title="Show" type="button" class="btn-01" onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 1 , <?php echo $info['i_status'] ?>)"  value="<?=$s_status?>"/></span>
                            
                            <?php }?>
                            
                            </td>
                          </tr>
                          
                          
                                   
					  <?php
                             endforeach;
                             
                           else :	// i.e. no records exists...
                      ?>
                          <tr>
                              <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                          </tr>
                      <?php
                           endif;
                      ?>
                              </table>
	
 <div class="paging"><ul><?= $page_links?></ul></div>