<!--POST COMMENT LIGHTBOX -->
<div class="lightbox comment_div" style="width:540px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
     
            <div class="heading">
                  <div class="left">
                        <h4><img src="images/icons/coment.png" alt="" /> Post Comment </h4>
                  </div>
            </div>
            <div class="frm_box">
                  <p>
                    <textarea  class="feed_comment_box" cols="" rows="" style="width:486px; height:100px; margin-bottom:10px;"></textarea>
                  </p>
                  	<input type="hidden" name="i_photo_id" id="i_photo_id" value=""/>
                  <p>
                    <input class="submit-green" id="post_comment_button" type="button"  style="margin-top:15px;" value="Post" name="" onclick="post_comment();">
                  </p>
                  
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div> 
<!--POST COMMENT LIGHTBOX -->