<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php
include(APPPATH . "views/layouts/nav.phtml");
$total_frnds = $qualification_params['total_frnds'];
$total_commitmnts = $qualification_params['total_commitments'];
$total_rings = $qualification_params['total_rings'];
$total_prayer_grps = $qualification_params['total_prayer_grps'];
$six_months_later = $qualification_params['sixMonthsLater'];
$join_date = $qualification_params['join_date'];
//echo $sixMonthsLater_date = date('d-m-Y', $six_months_later);
$current_time = time();
$admin_set_q_params_arr = get_prayer_parameters_set_by_admin();
$min_frnds = $admin_set_q_params_arr['min_friends'];
$min_months = $admin_set_q_params_arr['min_months'];
$min_rings = $admin_set_q_params_arr['min_rings'];
$min_prayer_grps = $admin_set_q_params_arr['min_prayer_grps'];
$min_pr_commtmnts = $admin_set_q_params_arr['min_pr_comttmnts'];
//$diff = abs($current_time - $join_date);
//
//define('DAY', 60 * 60 * 24, true);
//define('MONTH', DAY * 30, true);
//define('YEAR', DAY * 365, true);
//
//echo $years = floor($diff / (YEAR)).'<br>';
//echo $months = floor(($diff - $years * YEAR) / (MONTH)).'<br>';
//echo $days = floor(($diff - $years * YEAR - $months * MONTH ) / (DAY));

$time_start = $join_date;
$time_end = $current_time;
$years = 0;
$months = 0;
while ($time_start < $time_end) {
    $tmp_time = strtotime('+ 1 year', $time_start);
    if ($tmp_time < $time_end) {
        $years++;
        $time_start = $tmp_time;
    } else {
        $tmp_time = strtotime('+ 1 month', $time_start);
        if ($tmp_time < $time_end) {
            $months++;
            $time_start = $tmp_time;
        } else {
            $time_start = $time_end;
        }
    }
}
if ($years > 0) {
    // $age = $years . ' years &amp; ' . $months . ' months';
    $age = (($years * 12) + $months) . ' months';
    $active_months = (($years * 12) + $months);
} else if ($months >= 1) {
    $age = $months . ' months';
    $active_months = $months;
} else if ($months < 1) {
    $months = 0;
    $active_months = 0;
    $age = $months . ' months';
}
?>
<!-- /NAVIGATION SECTION -->
</div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
    .nw-chat-lnk{ color:#014882 !important; font-size:13px !important;
                  cursor:pointer; }
    </style>
    <!-- CONTENT SECTION -->
    <div id="content_section">
    <div id="container">
        <!--<div id="mid_content"> -->
        <!-- latest news -->
        <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
        <!-- /latest news -->
        <div class="clr"></div>
        <!-- main container -->
        <div id="main_container">
            <!-- left container -->
            <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
            <!-- /left container -->
            <!-- mid container -->
            <div id="mid_container">

                <?php
                /* $a=check_prayer_partner(decrypt($_SESSION['user_id']));
                  echo $a; */
                ?>

                <?php if ($is_want_prayer_partner == 'Y') { ?>  

                    <!--sub page links -->
                    <div class="link-div">
                        <ul>

                            <li><a href="my-prayer-partners.html" class="<?php echo ($page_name == 'my-prayer-partners') ? 'current' : ''; ?>"><span>My Prayer Partners</span></a></li>

                            <li><a href="prayer-partner-request.html" class="<?php echo ($page_name == 'prayer-partner-request') ? 'current' : ''; ?>"><span>Prayer Partner Requests</span></a></li>

                            <li><a href="search-invite-prayer-partner.html" class="<?php echo ($page_name == 'search-invite-prayer-partner') ? 'current' : ''; ?>"><span>Search  &amp;  Invite Prayer Partners</span></a></li>
                        </ul>
                        <div class="clr"></div>
                    </div>
                    <!--/sub page links -->

                    <!--You are not yet enlisted to Prayer Partner Zone section start -->
                    <div class="shade_box_blue" style="padding-top:5px;"> 
                        <div class="txt_content">
                           Opt out of Prayer Partner Zone 
                            <a href="javascript:void(0);" onclick="return show_dialog('optout-as-prayer-partner')" class="enlist-prayer-partner">Opt Out</a>
                        </div>
                    </div>
                    <!--You are not yet enlisted to Prayer Partner Zone section end -->


                    <?php /* ?> <?php if(count($result_arr_pp)):?>




                      <div style="padding-top:20px;">
                      <div class="page_heading">
                      <div class="left"><img src="images/icons/icon23.png" alt="" /> Prayer Partner Request Received</div>
                      </div>
                      <DIV id="request_recieved_content"><?=$content2?></DIV>
                      </div>
                      <?php endif;?><?php */ ?>

                    <div class="page_heading">
                        <div class="left"><img src="images/icons/flower.png" alt="" width="29" height="41"/> My Prayer Partners </div>
                        <div class="right"></div>
                    </div>


                    <!--< <div class="arrow_btm"></div>
                     div class="section01" style="margin-bottom:1px;">
                         <div class="txt_content" style="padding:10px 0px;">
                               <div class="heading02"><img src="images/icons/search.png" alt="" style="margin-right:3px;" /> 
                               <a  href="search-invite-prayer-partner.html" class="blue_link">Search New Prayer Partner</a> </div>
                               <div class="clr"></div>
                         </div>
                   </div>-->

                    <div class="section01" style="margin-bottom:1px;">
                        <div class="txt_content" style="padding:5px 0px;">
                            <div class="heading02" style="margin-bottom:10px;">
                                <img src="images/icons/search.png" alt=""  />Search My Prayer Partners </div>
                            <div class="clr"></div>

                            <form name="filter_friends" id="filter_friends" method="post"  onsubmit="return false;" >  
                                <input name="txt_name" id="txt_name" type="text" style="width:223px; height:16px;  margin-right:5px;" class="left"/>
                                <select name="show" id="show" style="width:160px;height:26px;line-height:21px;">
                                    <option value="-1">Show All</option>   
                                    <option value="1">Show Online</option>
                                    <option value="4">Show Offline</option>
                                </select>
                                <?php /* ?> <script type="text/javascript">
                                  $(document).ready(function(arg) {
                                  $("#show").msDropDown();
                                  $("#show").hide();
                                  })
                                  </script><?php */ ?>
                                <input type="hidden" name="search_basic" id="search_basic" value="Y" />
                                <input name="btn_submit" id="btn_submit" type="submit" value="Search" class="yellow-btn my-frd-search <?php /* ?>left<?php */ ?>" />
                            </form>
                            <div class="clr"></div>
                        </div>
                    </div>



                    <DIV id="my_friends">
                        <?= $friends_result_content ?>
                    </DIV>




                <?php } else {
                    ?>  
                    <div class="page_heading">
                        <div class="left"><img src="images/icons/flower.png" alt="" width="29" height="41" /> My Prayer Partners </div>
                        <div class="right"></div>
                    </div>

                    <div class="div_content" style=" margin-top:0px;">



                        <!--You are not yet enlisted to Prayer Partner Zone section start -->
                        <div class="shade_box_blue" style="padding-top:5px;"> 
                            <div class="txt_content">
                                You are not yet enlisted to Prayer Partner Zone. To enlist yourself please click on the button below <br/>
                                <!--<a href="javascript:void(0);" onclick="return show_dialog('enlist-as-prayer-partner')" class="enlist-prayer-partner">Enlist as Prayer Partner</a>-->
                                <a style="float:left" href="javascript:void(0);" onclick="show_msg('#confirm')" class="enlist-prayer-partner">Enlist as Prayer Partner</a>
                                <a style="float:left; margin: 23px 0 0 6px;" href="javascript:void(0);" class="view-criteria"><img src="<?= base_url(); ?>images/sign-icon.png" height="18" width="17"></a>
                                <div class="clr"></div>
                            </div>
                        </div>
                        <div class="shade_box_blue" style="padding-top:5px;display:none" id="confirm"> 
                            <div class="txt_content" >
                                <p class="bold-text">Are you sure you want to enlist yourself as Prayer Partner?</p>

                                <form enctype="multipart/form-data" method="post" action="" >
                                    <input class="btn" type="button" style="" value="Yes" name="" onclick="enlist_()" />
                                    <input class="btn" type="button" onclick="hide_msg('#confirm')" value="No" name="" />
                                </form>
                            </div>
                        </div>
                        <!--You are not yet enlisted to Prayer Partner Zone section end -->


                    </div>

                <?php } ?>
            </div>                   
            <!-- /mid container -->
            <!-- right container -->
            <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
            <!-- /right container -->
        </div>
        <!-- /main container -->
        <div class="clr"></div>
        <!--</div> -->
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>




<!-- /lightbox SECTION -->
<div class="lightbox enlist-as-prayer-partner" style="width:500px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top">
        <div>&nbsp;</div>
    </div>
    <div class="mid">
        <div class="heading">
            <div class="left">
                <h4>Confirmation Message</h4>
            </div>
        </div>
        <p class="bold-text">Are you sure you want to enlist yourself as Prayer Partner?</p>

        <form enctype="multipart/form-data" method="post" action="" >
            <input class="btn" type="button" style="" value="Yes" name="" onclick="enlist_()" />
            <input class="btn" type="button" onclick="hide_dialog()" value="No" name="" />
        </form>
    </div>
    <div class="bot">
        <div>&nbsp;</div>
    </div>
</div>


<div class="lightbox optout-as-prayer-partner" style="width:480px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top">
        <div>&nbsp;</div>
    </div>
    <div class="mid">
        <div class="heading">
            <div class="left">
                <h4>Confirmation Message</h4>
            </div>
        </div>
        <p class="bold-text">Are you sure you want to quit yourself from Prayer Partner Zone?</p>

        <form enctype="multipart/form-data" method="post" action="" >
            <input class="btn" type="button" style="margin-left:146px;" value="Yes" name="" onclick="optout_()" />
            <input class="btn" type="button" onclick="hide_dialog()" value="No" name="" />
        </form>
    </div>
    <div class="bot">
        <div>&nbsp;</div>
    </div>
</div>
<div class="lightbox enlist_pr_prtnr" style="width:415px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <strong>You are not eligible yet to enlist yourself as a prayer partner.</strong><br><br>
        <label class="<?php
        if ($current_time < $six_months_later) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Member For : <?= $age ?> <?php if ($current_time < $six_months_later) echo "(min.req $min_months months)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_frnds < $min_frnds) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total friends : <?= $total_frnds ?> <?php if ($total_frnds < $min_frnds) echo "(min.req $min_frnds)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_rings < $min_rings) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total rings : <?= $total_rings ?><?php if ($total_rings < $min_rings) echo "(min.req $min_rings)" ?> 
        </label><br><br>
        <label class="<?php
        if ($total_prayer_grps < $min_prayer_grps) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total prayer groups : <?= $total_prayer_grps ?> <?php if ($total_prayer_grps < $min_prayer_grps) echo "(min.req $min_prayer_grps)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_commitmnts < $min_pr_commtmnts) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total prayer commitments : <?= $total_commitmnts ?>&nbsp;<?php if ($total_commitmnts < $min_pr_commtmnts) echo "(min.req $min_pr_commtmnts)" ?>
        </label><br><br>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<!--<div class="lightbox write_prayer_point" style="width:480px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
   
            <div class="heading">
                  <div class="left">
                        <h4>Write Prayer Points</h4>
                  </div>
            </div>
           <p> <textarea id="text_area_prayer_point" name="textarea_prayer_pt" cols="" rows="" style="width:440px; height:100px;"></textarea></p>
           <p style="padding-bottom:8px;" class="blue12">You Should write date along with prayer points</p>
           <input type="hidden" id="dbId" value="0">
           <p><input id="save_points" name="" type="button" value="Save" class="btn" onclick="write_prayer_partner_()" /></p>
          
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<div class="lightbox read_prayer_pt" style="width:480px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading">
                  <div class="left">
                        <h4>Read Prayer Points</h4>
                  </div>
            </div>
            <div id="prayer_points" style="height: 130px; overflow-y: auto;overflow-x:hidden ;">
          
           </div>
           <p>&nbsp;</p>

           <p><input name="" type="button" value="Close" onclick="hide_dialog()" class="btn" /></p>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>-->




<div class="lightbox remove_div" style="width:245px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4> Reason for Removal </h4></div></div>
        <div class="frm_box">

            <div class="lable01" style="width:100px;">Reason :</div> 
            <div class="field01"> <textarea name="" cols="" rows="" style="width:320px; height:100px;"></textarea></div>
            <div class="clr"></div>

            <div class="lable01" style="width:100px;">&nbsp;</div> 
            <div class="field01"><input name="" type="button" value="Remove" class="btn" /></div>
            <div class="clr"></div>
        </div>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
<div class="lightbox view_q_criteria" style="width:415px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <label class="">Minimum membership time :&nbsp; <?php echo $min_months .' '. 'months'; ?></label><br><br>
        <label class="">Minimum friends :&nbsp; <?php echo $min_frnds; ?></label><br><br>
        <label class="">Minimum rings :&nbsp; <?php echo $min_rings; ?></label><br><br>
        <label class="">Minimum prayer groups :&nbsp; <?php echo $min_prayer_grps; ?></label><br><br>
        <label class="">Minimum prayer commitments :&nbsp; <?php echo $min_pr_commtmnts; ?></label><br><br>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<!-- confirm delete points-->
<div class="lightbox delete-page-popup" style="width:245px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?= base_url() ?>images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading" style="margin-bottom:0px;">
            <div class="left">
                <h4>Delete Prayer Points</h4>
            </div>
        </div>
        <div class="shade_box_white" style="padding:8px 0px;">
            <div style="padding-bottom:10px;">
                <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete prayer points?</p>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                <input name="" type="button" value="Yes" class="popup-yes" onClick="delete_prayer_points()"/>
                <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
            </form>   
            <div class="clr"></div>
        </div>

    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<?php /* ?>CONFIRM DELETE PRAYER PARTNERS<?php */ ?>

<div class="lightbox delete-prayer-partner" style="width:245px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?= base_url() ?>images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading" style="margin-bottom:0px;">
            <div class="left">
                <h4>Delete Prayer Partner</h4>
            </div>
        </div>
        <div class="shade_box_white" style="padding:8px 0px;">
            <div style="padding-bottom:10px;">
                <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete this prayer partner?</p>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                <input type="hidden" name="i_del_partner_id" id="i_del_partner_id" value="" />
                <input name="" type="button" value="Yes" class="popup-yes" onClick="delete_prayer_partners_()"/>
                <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
            </form>   
            <div class="clr"></div>
        </div>

    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<script type="text/javascript">
    /*read prayer points section script start*/
    $(document).ready(function() {
        $('.read-prayer-points').click(function() {
            $(this).parent('.light_heading').find('.prayer-points').slideToggle();
        });
    })
    /*read prayer points section script end*/
</script>

<script type="text/javascript">
    $(document).ready(function(arg) {

        $('#filter_friends').submit(function() {

            var datatosend = $("#filter_friends").serialize();

            showBusyScreen();
            //alert(datatosend);
            $.ajax({
                type: "POST",
                url: base_url + "logged/my_prayer_partners/friends_ajax_pagination",
                data: datatosend,
                success: function(data) {
                    $('#my_friends').html(data);
                    hideBusyScreen();
                }
            });


        });
        $('.view-criteria').click(function() {
            show_dialog('view_q_criteria');
        });
    });

//    function show_msg(divid)
//    {
//        $(divid).slideDown();
//    }

    function show_msg(divid)
    {
        // $(divid).slideDown();
        //var count = 0;
        var total_frnds = <?= $total_frnds ?>;
        var total_rings = <?= $total_rings ?>;
        var total_prayer_grps = <?= $total_prayer_grps ?>;
        var total_commitmnts = <?= $total_commitmnts ?>;
        var six_month_later = <?= $six_months_later ?>;
        var current_time = <?= $current_time ?>;
        var min_frnds = <?= $min_frnds ?>;
        var min_rings = <?= $min_rings ?>;
        var min_prayer_grps = <?= $min_prayer_grps ?>;
        var min_commitmnts = <?= $min_pr_commtmnts ?>;
        var min_months = <?= $min_months ?>;
        var active_duration = <?= $active_months ?>;
//        alert(total_rings);
//        if (total_frnds >= min_frnds) {
//            count++;
//        }
//        if (total_rings >= min_rings) {
//            count++;
//        }
        // alert(count);
        if ((total_frnds >= min_frnds) && (total_rings >= min_rings) && (total_prayer_grps >= min_prayer_grps) && (total_commitmnts >= min_commitmnts) && (active_duration >= min_months))
        {
            $(divid).slideDown();
        } else {
            show_dialog('enlist_pr_prtnr');
        }
    }
    function hide_msg(divid)
    {
        $(divid).slideUp();
    }
</script>
<style type="text/css">
    .color-red{ background-color: #ff3333; color: #fff; padding: 2px 4px;}
    .color-green{ background-color: green; color: #fff; padding: 2px 4px;}
    .color-blue{ background-color: burlywood; color: #fff; padding: 2px 4px;}
</style>