<div class="arrow_btm"></div>
     <div class="div_content" style=" margin-top:0px;">
      <?php  #pr($result_arr);
	         if(count($result_arr) >0):
					foreach($result_arr as $key=>$val):	
						
						$name = $val['s_displayname'];
						
						/*$add = array();
						$country_name = get_country_name_by_id($val['i_country_id']);
						if(!empty($val['s_city']))
							$add['city']=$val['s_city'];
						if(!empty($val['s_state']))
							$add['state']=$val['s_state'];
						if(!empty($country_name))    
							$add['country']=$country_name;
						
						
						$address = implode(', ',$add);*/
						$address = get_user_address_info($val['i_requester_id']);
						$img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);	
						$user_id =$val['i_requester_id'];
						$available_status = ($val['is_available'] == 'true')?'Available':'Max limit reached';
			  			$css =($val['is_available'] == 'true')?'class = "available"':'class = "not-available" ';
			  			$status_img =($val['is_available'] == 'true')?'online.png':'not-available.png ';
						
						if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
						  $profile_link = get_profile_url($val['i_requester_id'],$val['s_displayname']);
						}else
						{
							$profile_link = get_profile_url_prayer_partner($val['i_requester_id'],$val['s_displayname']);
						}		
		?>                                   
                                        
                                        
                    <div class="shade_box_blue" style="padding-top:5px;" id="rec_request_<?=$user_id?>"> 
                                             <div class="txt_content">
                                                 <a href="<?= $profile_link;?>"><div class="pro_photo2" style="background:url(<?=$img?>) no-repeat center;width:60px; height:60px;" ></div><!--<img src="images/alex.jpg" alt="" class="pro_photo2" />--></a>
                                                  <div class="left_div01">
                                                       <p <?=$css?>><a class="left" href="<?= $profile_link;?>" ><?=$name?> </a> [ <img alt="" src="images/icons/<?=$status_img?>"> <span class="nogrey_link"><?=$available_status?></span> ]</p>
                                                       <?php /*?> <p class="blue_bold12"><a href="javascript:void(0);"><?=$name?></a></p><?php */?>
                                                        <p class="location"><?=$address?></p>
                                                        <!--<p class="light-grey">10 Mutual Friends</p>-->
                                                        <p class="date-time">Connected Since : <?=getShortDateWithTime($val['dt_created_on'],6)?> </p>
                                                  </div>
                                                   <div class="right_div02">
                                                        <?php if($val['is_available']=='false') : ?>
                                                        <p class="add-remove-friend"><img src="images/icons/not-available.png" alt="" /> Not Available.</p>
                                                      <?php else: ?> 
                                                       <p class="add-remove-friend"><img src="images/icons/accept.png" alt="" /> <a  href="javascript:void(0);" id="invite_prayer_partner_<?=($user_id)?>" onclick="invitation_accept_('<?=($user_id)?>')" >Accept</a></p> 
                                                       <?php endif; ?>  
                                                      
                                                      <!--  <p class="add-remove-friend"><img src="images/icons/view.png" alt="" /> <a  href="javascript:void(0);">View</a></p>    -->
                                                        <p class="add-remove-friend"><img src="images/icons/decline.png" alt="" /> <a  href="javascript:void(0);" id="decline_prayer_partner_<?=($user_id)?>" onclick="decline_prayer_partner_('<?=$user_id?>')">Decline</a></p>
                                                    </div>
                                                  <div class="clr"></div>
                                               </div>
                                       </div>
  		<?php 
	    		endforeach;
				
		?>                                     
                                       
		<?php if($page_links){ ?>
        <div class="pagination">
        
        <div class="left">Viewing Page <?=$current_loaded_page_no?> of <?=$total_pages?> </div>
        
        <div class="right">
               <ul class="small-paging">
                <?=$page_links?> 
                </ul>
        </div>
        </div>
		<?php  }?>
        <?php
				else:
					echo '<div class="shade_box_blue" style="padding-top:5px;"><div  class="shade_norecords" style="width:325px"><p class="blue_bold12">No Prayer Partner Request Recieved.</p></div></div>';
				endif;
	   ?>
       
      </div>
