<?php //pr($result_arr)?>
<script type="text/javascript">
<!--
function pausePlayers(playing_id) { 
  
   <?php
	foreach($result_arr as $val):
	?>
		
		   if(<?=$val['id']?> != playing_id) { jwplayer("myElement_"+<?=$val['id']?>).pause(true); }
	<?php
 		endforeach;
	?>
};


$(function(){
<?php
	foreach($result_arr as $val):
		$ID = 'm1'. $val['id'];
		$audio_filename = base_url()."uploads/user_audio_files/".$val['s_audio_file_name'];
?>
	<?php /*?>$("#<?= $ID ?>").mb_miniPlayer({
		width:295,
		inLine:false
	});<?php */?>
	 jwplayer("myElement_<?=$val['id']?>").setup({
        file: "<?=$audio_filename?>",
        image: "<?=$audio_filename?>",
		title: "<?=$val['s_title']?>",
		
		height: 30,
        width: 472,
        events:{
		  onPlay: function() {
		    	pausePlayers(<?=$val['id']?>);
			 //jwplayer('container3').stop();
		  }
		}
    });
	
<?php
	endforeach;
?>
});
//-->
</script>
<?php

	if(count($result_arr)>0){
		foreach($result_arr as $val):
				
		 $audio_filename = base_url()."uploads/user_audio_files/".$val['s_audio_file_name'];
?> 
		<div class="new-album-testing">
        <div class="new-albumtxt-testing">
             <p class="blue_bold12"><img alt="" src="images/icons/audio_icon.png" /><a href="javascript:void(0);"><?=my_substr($val['s_title'], 35);?></a></p>
             <p class="light_blue12"><?=$val['s_artist']?> , <?=$val['s_genre']?></p>
             <p class="date-time"><?=getShortDate($albm_val['dt_created_on'], 5)?></p>
             <p><?=$val['s_desc']?></p>
             <div class="audio-player audio-player-div">
                      <div id="myElement_<?=$val['id']?>">Loading the player...</div>
             </div>
        </div>
         <div class="light_heading"> 
             <div class="left"><a href="javascript:void(0);" class="comments_div<?=$val['id']?>"  onclick="return show_comments(<?=$val['id']?>)<?php /*?>show_dialog('view_comments_div')<?php */?>">Comments (<?=$val['total_comments']?>)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);"   onclick="return show_people_liked(<?=$val['id']?>); " class="liked_by_<?=$val['id']?>">Liked by (<?=count_photo_like_link($val['id'],'audio')?>)</a></div>
        <?php if((show_photo_like_link($val['id'],'audio') == TRUE) ) { ?>
		
                <div class="right"><a href="javascript:void(0);"  >Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$val['id']?>" onClick="windowLike(<?=$val['id']?>,'Like')">Like</a>  </div>                
       <?php } 
	    	else{ 
	      ?>
         		<div class="right"><a href="javascript:void(0);">Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$val['id']?>" >Like</a> </div>
       <?php }?>
             
              
         </div>
         
         	<!-- slide section start -->
            <div class="new-wl">
            <!--comment section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid">
                      <div class="heading">
                            <div class="left">
                                  <h4><img class="cmnt" src="images/icons/cmnt2.png" height="20px" width="20px"  alt="" /> <span class="comments_div<?=$val['id']?>">Comments (<?=$val['total_comments']?>)</span> </h4>
                                  <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                            </div>
                       </div>
                       <DIV id="audio_comment_div<?=$val['id']?>"></DIV>
                    </div>
                </div>
            <!--comment section end-->	
            <!--like by section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid">
                      <div class="heading">
                            <div class="left">
                                  <h4><img alt="heart2" src="images/heart2.png" height="19" width="20" class="cmnt" /> <span class="liked_by_<?=$val['id']?>">Liked by (<?=count_photo_like_link($val['id'],'audio')?>)</span> </h4>
                                   <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                            </div>
                      </div>
                      
                        <div class="shade_box_white" id="audio_like_div<?=$val['id']?>">
                        </div>
                   </div>
            	</div>
            <!--like by section end-->
                
            </div>
            <div class="new-wl-right">
                <!--comment section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid">
                      <div class="heading">
                            <div class="left">
                                  <h4><img alt="" src="images/no.png" class="cmnt" width="21" height="19"/>  Comment  </h4>
                                  <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                            </div>
                      </div>
                      
                      <div class="txt_content01 comments-number-content"> 
                      <textarea class="wal-comment-textarea" id="feed_comment_box_<?=$val['id']?>"></textarea>
                      <input type="button" value="Post" class="yellow-btn" id="post_comment_button" onclick="post_comment(<?=$val['id']?>)" />
                      <br class="clr" />
                      </div>
                </div>
                </div>
                <!--comment section end-->	
            </div>
            <!-- slide section end --> 
		 
       </div>
         <script type="text/javascript">
			$(function(){
				$('.left a').click(function(){
				var index=$(this).index();
				
				$('.new-wl > .comments-number').css('display','none');
				$('.new-wl-right > .comments-number').css('display','none');
				$(this).parent().parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
				})
				
				$('.right a').click(function(){
				var index=$(this).index();
				$('.new-wl > .comments-number').css('display','none');
				$('.new-wl-right > .comments-number').css('display','none');
				$(this).parent().parent().next().next('.new-wl-right').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
				})
				
				$('.wal-minus').click(function(){
					$(this).parents('.comments-number').slideUp('fast');
				})
			})
		</script>
  <?php                                
		endforeach;?>
		        
<?php	}
	
?>

<input type="hidden" id="current_page" name="current_page" value="<?=$current_page?>"  />

  