<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Gospel Magazine</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                            <!--filter section start -->
                            <div class="filter" >
                                <span class="filter-by">Filter By &raquo;</span>
                                <form id="search_frm" action="" method="post" enctype="multipart/form-data" class="filter-search" onsubmit="return search_()" style="width:700px;">
                                    <label>Article Title :</label><input name="txt_title" id="txt_title" type="text" style="width:158px;" />

                                   <?php /*?> <label>Admin ID :</label><input type="text" style="width:100px;" />
                                   <?php */?>
                                    <label>Published By :</label><input name="txt_published_by" id="txt_published_by" type="text" style="width:143px;" />
                                    <div class="clr"></div>
                                    <label>Date of posting From :</label>
                                    <input type="text"  value="" name="date_to1" id="date_to1"  readonly="readonly" class="date-field"/>
                                          <img src="../images/icons/cal.png" alt="" onclick="$(this).prev().focus()" class="calender" style="margin-right:21px;" />
                                          <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $.datepicker.setDefaults($.datepicker.regional['']);
                                                    $("#date_to1").datepicker($.datepicker.regional['en']);
                        
                                                });
                                           </script>
                                            
                                    <label>To :</label>        
                                    <input type="text"  value="" name="date_to2" id="date_to2"  readonly="readonly" class="date-field"/>
                                          <img src="../images/icons/cal.png" alt="" onclick="$(this).prev().focus()" class="calender" />
                                          <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $.datepicker.setDefaults($.datepicker.regional['']);
                                                    $("#date_to2").datepicker($.datepicker.regional['en']);
                                                });
                                          </script>
                                    
                                    <input type="hidden" id="hd_val" value="Y" />
                                    
                                    <input name="" type="submit" value="GO" class="go" />
                                    &nbsp;&nbsp;<a href="javascript:void(0)" onclick="return show_all_();" >Show all</a>
                                </form>
                                
                                  
                                <div class="clr"></div>
                            </div>
                            <!--filter section end -->
                        
                            <h4>Gospel Magazine</h4>
                            <div class="right" style="margin-bottom:14px;"><input name="" type="button" value="Add New Article"  class="evnt_btn1" 
onclick="window.location=admin_base_url+'add-new-article.html'"/></div>
                            
                            <!--tab section start -->
                            <div class="tab-box">
                               <?php /*?> <div class="tab_content title-div">
                                    <ul>
                                        <li class="first select"><a href="javascript:void(0);">Articles Online</a></li>
                                        <li class="noBg"><a href="javascript:void(0);">Awaiting Approval</a></li>
                                    </ul>
                                </div>
                               <?php */?>
                                <div class="clr"></div>
                                <div class="tab_details detail-div">
                                    
                                    
                                    <!--Articles Online box -->
                                    
                                    <div class="show lavel-01" id="table_contents">
                                    <?=$content;?>
                                    </div>
                                    <!--/Articles Online box -->
                                    
                                    
                                    
                                    <!--Awaiting Approval box -->
                                    <div class="lavel-01">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                                          <tr>
                                            <th align="left" valign="middle" height="30" width="60">Posted On</th>
                                            <th align="left" valign="middle" height="30" width="130">Posted By</th>
                                            <th align="left" valign="middle" height="30" width="180">Article Title</th>
                                            <th align="left" valign="middle" height="30" width="150">Publisher</th>
                                            <th align="left" valign="middle" height="30" width="300">Description</th>
                                            <th align="center" valign="middle" height="30" class="last">Actions</th>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">Lorem Ipsum</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">In aliquet enim non metus tempus elementum. Faucibus nisl vehicula tempor quis at lorem. </td>
                                            <td align="center" valign="middle" class="last">
                                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-awaiting-approval.html'"/>
                                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-awaiting-approval')"/>
                                            <input name="" title="Approve" type="button" class="btn-06"  value="Approve"/>
                                            </td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">Lorem Ipsum</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">In aliquet enim non metus tempus elementum. Faucibus nisl vehicula tempor quis at lorem. </td>
                                            <td align="center" valign="middle" class="last">
                                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-awaiting-approval.html'"/>
                                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-awaiting-approval')"/>
                                            <input name="" title="Approve" type="button" class="btn-06"  value="Approve"/>
                                            </td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">Lorem Ipsum</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">In aliquet enim non metus tempus elementum. Faucibus nisl vehicula tempor quis at lorem. </td>
                                            <td align="center" valign="middle" class="last">
                                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-awaiting-approval.html'"/>
                                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-awaiting-approval')"/>
                                            <input name="" title="Approve" type="button" class="btn-06"  value="Approve"/>
                                            </td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">Lorem Ipsum</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">In aliquet enim non metus tempus elementum. Faucibus nisl vehicula tempor quis at lorem. </td>
                                            <td align="center" valign="middle" class="last">
                                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-awaiting-approval.html'"/>
                                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-awaiting-approval')"/>
                                            <input name="" title="Approve" type="button" class="btn-06"  value="Approve"/>
                                            </td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">Lorem Ipsum</td>
                                            <td align="left" valign="top">Nunc adipiscing</td>
                                            <td align="left" valign="top">In aliquet enim non metus tempus elementum. Faucibus nisl vehicula tempor quis at lorem. </td>
                                            <td align="center" valign="middle" class="last">
                                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-awaiting-approval.html'"/>
                                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-awaiting-approval')"/>
                                            <input name="" title="Approve" type="button" class="btn-06"  value="Approve"/>
                                            </td>
                                          </tr>
                                        </table>
                                    </div>
                                    <!--/Awaiting Approval box -->
                                    
                                    
                                </div>
                            </div>
                            <!--tab section end -->
                            
                            <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div><!--/mid_content-->
            
            <div class="clr"></div>
</div>
<input type="hidden" id="article_id" value="">
<input type="hidden" id="comment_article_id" value="">
</div>


<!-- /CONTENT SECTION -->



<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Christian News</h4>
                  </div>
            </div>
               <div class="shade_box_white">
               <p class="center-text">Do you really want to delete this news?</p>
               <form method="post" enctype="multipart/form-data">
               <input type="hidden" id="i_del_id" value="">
                       <input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onclick="return delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->
<!--popup delete awaiting approval start-->
<div class="lightbox delete-awaiting-approval" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Awaiting Approval</h4>
                  </div>
            </div>
               <div class="shade_box_white">
               <p class="center-text">Do you really want to delete this approval?</p>
               <form method="post" enctype="multipart/form-data">
                       <input name="" type="button" value="Yes" class="btn" style="margin-left:146px;"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup delete awaiting approval end-->

<!--popup view comment start-->
<div class="lightbox comments-popup" style="width:600px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>View Comments</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="height:400px; overflow:auto">
               <DIV id="comment_html">
               <?=$result?>
               </DIV>

               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup view comment end-->

<!--popup liked by start-->
<div class="lightbox liked-by" style="width:750px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Liked By</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="height:400px; overflow:auto">
               <DIV id="liked_html">
               <?=$result?>
               </DIV>
                     
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup liked by end-->











<script type="text/javascript">


function search_()
  {
      showBusyScreen();
      var title = $('#txt_title').val();
      var published_by = $('#txt_published_by').val();

      //var uploaded_by = $('#txt_admin_id').val();
      var date_from = $('#date_to1').val();
      var date_to = $('#date_to2').val();
	  
	  
      $.ajax({
          url : admin_base_url+'media_center/gospel_magazine/gospel_magazine/magazine_listing_ajax',
          type : 'post',
          data : ({'title' : title,
                   
                    'published_by' : published_by,
                    'date_from':date_from,
                    'date_to':date_to,
					'hd_val':$('#hd_val').val()
          }),
          success : function(data)
          {
              hideBusyScreen();
              $('#table_contents').html(data);
          }
      });
      return false;
  }
  

function confirm_delete_(id)
{
  $('#i_del_id').val(id);
  show_dialog('delete-page-popup');
}

function delete_()
{
    var id = $('#i_del_id').val();
    var current_page = $('#current_page').val();
    showBusyScreen();
    $.ajax({
          url : admin_base_url+'media_center/gospel_magazine/gospel_magazine/delete_article/'+ current_page,
          type : 'post',
          data : ({'id' : id,'current_page':current_page}),
          dataType : 'json',
          success : function(data)
          {

              showUIMsg(data.msg);
              hideBusyScreen();
              hide_dialog();
              $('#table_contents').html(data.html);
          }
      });
    
}

function show_all_()
  {
      $('#search_frm')[0].reset();
      showBusyScreen();
      $.ajax({
          url : admin_base_url+'media_center/gospel_magazine/gospel_magazine/magazine_listing_ajax/0',
          type : 'post',
          data : ({'hd_val':'Y'}),
          success : function(data)
          {
              hideBusyScreen();
              $('#table_contents').html(data);
          }
      });
  }
  
  
  
  function show_people_like(article_id)
  {
      
      $('#article_id').val(article_id);
         
     showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
        $.ajax({
            
            url: admin_base_url +'media_center/gospel_magazine/gospel_magazine/fetch_likes_on_magazine/'+article_id,
            dataType: 'json',
            type: 'post',
            data : ({'article_id':article_id}),
    
            success: function (data, status) {
                //hideUILoader();
                $('#liked_html').html(data.html_data);
                hideUILoader('liked-by');
                
                //hideBusyScreen();
                showUIMsg(data.msg);
            },
            error: function(data, status, e) {
                hideUILoader('liked-by');
                //show_dialog('view_comments_div');
                showUIMsg("Error!");
                
            }
        });
                 
         
  }
  
  
  function show_comments(article_id)
  {
        
      $('#comment_article_id').val(article_id);
      
     showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
        $.ajax({
            
            url: admin_base_url +'media_center/gospel_magazine/gospel_magazine/fetch_comment_on_gospel_magazine/'+article_id,
            dataType: 'json',
            type: 'post',
            data : ({'article_id':article_id}),
    
            success: function (data, status) {
              
                $('#comment_html').html(data.html_data);
                hideUILoader('comments-popup');
                
                //hideBusyScreen();
                showUIMsg(data.msg);
            },
            error: function(data, status, e) {
                hideUILoader('comments-popup');
                //show_dialog('view_comments_div');
                showUIMsg("Error!");
                
            }
        });
                 
  }
  
function remove_like_(id)
{
    var article_id = $('#article_id').val();
    $.ajax({
        url : admin_base_url+'media_center/christian_news/remove_like',
        type : 'post',
        data : ({'comment_record_id':id,'article_id':article_id}),
        dataType : 'json',
        success : function(data)
        {
            $('#like_'+article_id).html(data.total_likes);
                showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
                $.ajax({
                    
                    url: admin_base_url +'media_center/christian_news/fetch_people_liked_post/',
                    dataType: 'json',
                    type: 'post',
                    data : ({'article_id':article_id}),
            
                    success: function (data, status) {
                        //hideUILoader();
                        $('#liked_html').html(data.html_data);
                        hideUILoader('liked-by');
                        
                        //hideBusyScreen();
                        showUIMsg(data.msg);
                    },
                    error: function(data, status, e) {
                        hideUILoader('liked-by');
                        //show_dialog('view_comments_div');
                        showUIMsg("Error!");
                        
                    }
                });
        }
    });
}


function remove_comment_(id)
{
    var article_id = $('#comment_article_id').val();
    
        $.ajax({
        url : admin_base_url+'media_center/christian_news/remove_comment',
        type : 'post',
        data : ({'comment_record_id':id,'article_id':article_id}),
        dataType : 'json',
        success : function(data)
        {
            $('#comment_'+article_id).html(data.total_comments);
            
                showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
                $.ajax({
                    
                    url: admin_base_url +'media_center/christian_news/fetch_comment_on_news/',
                    dataType: 'json',
                    type: 'post',
                    data : ({'article_id':article_id}),
            
                    success: function (data, status) {
                      
                        $('#comment_html').html(data.html_data);
                        hideUILoader('comments-popup');
                        
                        //hideBusyScreen();
                        showUIMsg(data.msg);
                    },
                    error: function(data, status, e) {
                        hideUILoader('comments-popup');
                        //show_dialog('view_comments_div');
                        showUIMsg("Error!");
                        
                    }
                });
        }
    });
}

</script>