<table width="70%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="600">Book Name</th>
                                <th align="center" valign="middle" height="30" class="last">Actions</th>
                              </tr>
                              <tr>
                                <td align="left" valign="top"><a href="chapter-from-book.html">Lorem Ipsum</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-book')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
         <?/*                     <tr>
                                <td align="left" valign="top"><a href="chapter-from-book.html">Lorem Ipsum</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-book')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top"><a href="chapter-from-book.html">Lorem Ipsum</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-book')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top"><a href="chapter-from-book.html">Lorem Ipsum</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-book')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top"><a href="chapter-from-book.html">Lorem Ipsum</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-book')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
         */?>
                            </table>