<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
    <tr>
        <th align="left" valign="middle" height="30" width="72">Joining Date</th>
        <th align="left" valign="middle" height="30" width="100">Name</th>
        <th align="left" valign="middle" height="30" width="45">Gender</th>
        <th align="left" valign="middle" height="30" width="150">Country, State &amp; City</th>
        <th align="left" valign="middle" height="30" width="180">Email</th>
        <th align="left" valign="middle" height="30" width="100">Mobile</th>
        <th align="center" valign="middle" height="30" width="410" class="last">Actions</th>
    </tr>
    <?php
    //echo "current page : ".$current_page." ";
    $now_page = round(($current_page / $pagination_per_page) + 1);
    // echo "in admin_members_ajax.phtml : now_page = ".$now_page;
    // pr($info_arr);

    foreach ($info_arr as $info) :
        $id = $info['id'];
        $date_joined = getShortDate($info['dt_created_on'], 3);
        $name = $info['s_first_name'] . ' ' . $info['s_last_name'];
        $gender_db = $info['e_gender'];

        /* $address        = (isset($info['s_country']))? $info['s_country']: '';
          $address       .= (isset($info['s_state']))? ', '.$info['s_state']: '';
          $address       .= (isset($info['s_city']))? ', '.$info['s_city']: '';
         */

        $add = array();
        if (!empty($info['s_country']))
            $add['country'] = $info['s_country'];
        if (!empty($info['s_state']))
            $add['state'] = $info['s_state'];
        if (!empty($info['s_city']))
            $add['city'] = $info['s_city'];

        $address = implode(', ', $add);

        $email = $info['s_email'];
        $mobile = $info['s_mobile'];
        $status = ($info['i_status'] == 1) ? 'Disable' : 'Enable';
        $gender = ($gender_db == 'M' || $gender_db == 'm') ? 'Male' : 'Female';
        $is_minister = ($info['is_minister'] == 0) ? 'SET AS MINISTER' : 'UNSET MINISTER';
        ?>
        <tr>
            <td align="left" valign="top"><?php echo $date_joined; ?></td>
            <td align="left" valign="top"><?php echo $name; ?></td>
            <td align="left" valign="top"><?php echo $gender; ?></td>
            <td align="left" valign="top"><?php echo $address; ?></td>
            <td align="left" valign="top"><?php echo $email; ?></td>
            <td align="left" valign="top"><?php echo $mobile; ?></td>
            <td align="center" valign="middle" class="last">
                <input name="" title="View Details" type="button" class="view-button"  value="" onclick="window.location = '<?= admin_base_url() ?>members/member_details/index/<?php echo $id; ?>/<?php echo $now_page; ?>'"/>
                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return delete_confirm_(<?php echo $info['id']; ?>, 1);"/>
                <input name="" title="Enable" type="button" class="btn-03" id="status<?php echo $id; ?>"  value="<?php echo $status; ?>" onclick="return status_change(<?php echo $id; ?>)"/>
                <input name="" title="Set As Minister" type="button" class="btn-04" id="is_minister<?php echo $id; ?>" value="<?php echo $is_minister; ?>" onclick="return change_is_minister(<?php echo $id; ?>)" />

                <input  title="Reset Password" type="button" class="btn-04" onclick="show_dialog('send-new-pwd');
                        $('#user_id').val('<?= $info['id'];  ?>');
                        "  value="Reset Password"/>
                <input  title="View Posts" type="button" class="btn-04" onclick="window.location = '<?= admin_base_url() ?>members/members_post/index/<?= $info['id'] ?>'"  value="View Posts"/>
            </td>
        </tr>
        <?php
    endforeach;
    ?>
  <!--  <tr>
      <td align="left" valign="top">20/12/2012</td>
      <td align="left" valign="top">Andrew Maxcell</td>
      <td align="left" valign="top">Male</td>
      <td align="left" valign="top">USA,<br />New York,<br />7/A Garden City</td>
      <td align="left" valign="top">andrew.maxcell@gmail.com</td>
      <td align="left" valign="top">+91 990 000 0000</td>
      <td align="center" valign="middle" class="last">
      <input name="" title="View Details" type="button" class="view-button"  value="" onclick="window.location='member-details.html'"/>
      <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
      <input name="" title="Enable" type="button" class="btn-03"  value="Enable"/>
      <input name="" title="Set As Minister" type="button" class="btn-04"  value="Set As Minister" />
      </td>
    </tr>
    <tr>
      <td align="left" valign="top">20/12/2012</td>
      <td align="left" valign="top">Andrew Maxcell</td>
      <td align="left" valign="top">Male</td>
      <td align="left" valign="top">USA,<br />New York,<br />7/A Garden City</td>
      <td align="left" valign="top">andrew.maxcell@gmail.com</td>
      <td align="left" valign="top">+91 990 000 0000</td>
      <td align="center" valign="middle" class="last">
      <input name="" title="View Details" type="button" class="view-button"  value="" onclick="window.location='member-details.html'"/>
      <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
      <input name="" title="Enable" type="button" class="btn-03"  value="Enable"/>
      <input name="" title="Set As Minister" type="button" class="btn-04"  value="Set As Minister" />
      </td>
    </tr>
    <tr>
      <td align="left" valign="top">20/12/2012</td>
      <td align="left" valign="top">Alanee Maxcell</td>
      <td align="left" valign="top">Female</td>
      <td align="left" valign="top">USA,<br />New York,<br />7/A Garden City</td>
      <td align="left" valign="top">andrew.maxcell@gmail.com</td>
      <td align="left" valign="top">+91 990 000 0000</td>
      <td align="center" valign="middle" class="last">
      <input name="" title="View Details" type="button" class="view-button"  value="" onclick="window.location='member-details.html'"/>
      <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
      <input name="" title="Enable" type="button" class="btn-03"  value="Disable"/>
      <input name="" title="Set As Minister" type="button" class="btn-04"  value="Set As Minister" />
      </td>
    </tr>
    -->
</table>
<div class="paging"><ul><?= $page_links ?></ul></div>

