<script type="text/javascript">
<!--
	function showSkillEdit(obj) {
		$(obj).parents('.text-table').hide();
		if($(obj).parents('.sec-detail').find('.form-table').css('display')=='none'){
			$(obj).parents('.sec-detail').find('.form-table').show();
			$(obj).parents('.sec-detail').find('.dd').show();
		}
	}
	
	
	// when "cancel" button clicked...
	function hideSkillEdit(obj) {
		
		//// remove those extra "add-more" divs...
		var actual_skill_rec_count = parseInt( $('#actual_skill_divs').val() );
		var max_no_of_tbls = 5;
		var start_loop = actual_skill_rec_count+1;
		for(i=start_loop; i<=max_no_of_tbls; i++) {
			tblID = "#skill_"+ i;
			$(obj).parents('.sec-detail').find(tblID).remove();
		}
		$('#h_skill').val( actual_skill_rec_count );	// resetting edu-count...
		$('#deleted_skill_divs').val('');		// resetting deleted record-count to 0 again...
		
		
		$(obj).parents('.sec-detail').find('.form-table').hide(); 
        if($(obj).parents('.sec-detail').find('.text-table').css('display')=='none'){
            $(obj).parents('.sec-detail').find('.text-table').show();
            $(obj).parents('.sec-detail').find('.dd').hide();
            
        }
		
	}
//-->
</script>
<div class="lavel-01">  
    <!--title section -->
    <div class="sec-title">
        <span class="title-left"></span>
        <div class="title-body"><h2>Skill</h2></div>
        <span class="title-right"></span>
    </div>
    <!--/title section -->
    <!--detail section -->
    <div class="sec-detail">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table text-table" id="member_skill_details">
        
            <?php 
            $count= count($result['skill_arr']);
           
            $skill_no=0; 
            if($count==0)
                $count=2;
                
                for($i=0;$i<$count;$i++)    :
                
                
                $skill_no++;
            ?>
            
            <tr>
              <td align="left" valign="top" height="25" width="180" class="label">Skill <?php echo $skill_no;?></td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" ><?php echo $result['skill_arr'][$i]['s_name'];?></td>
            </tr>
            
            <?php
            endfor;
            ?>
            
            <tr>
              <td align="left" valign="bottom" height="40" colspan="2">&nbsp;</td>
              <td align="left" valign="bottom"><a href="javascript:void(0);" class="edit-btn-other" onclick="showSkillEdit(this)">Edit</a></td>
            </tr>
        </table>
        
        <form id="frmManageSkillProfile"  method="post" action="<?=admin_base_url()?>members/member_details/modify_my_profile_skill_info_ajax/<?=$result['id']?>" onsubmit="return modify_my_skill_profile_ajax()" enctype="multipart/form-data">
            <?php
             
            $skill_no=0;
            for($i=0;$i<$count;$i++)    :
                
                $db_id= isset($result['skill_arr'][$i]['id'])? $result['skill_arr'][$i]['id']:'';
                $skill_no++;
            ?>
        
        <table id="<?php echo "skill_".$skill_no;?>" width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table skill_info">
      
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label skill"  >Skill <?php echo $skill_no;?></td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                <input type="text" name="txt_skill[]" value="<?php echo isset($result['skill_arr'][$i]['s_name'])? $result['skill_arr'][$i]['s_name']:'';?>"/>
                     <?php
            if($i>1)
            echo '<td valign="top" align="left" style=" float: right;  margin-right: 170px;"><a class="close" href="javascript:void(0);" style="margin-left:5px;" onclick="admin_closeExtraSkillDiv('.$skill_no.')" ><img src="'.base_url().'images/icons/close.png" alt=""></a></td>';    
               /* echo '<tr><td class="label" width="180" valign="top" height="30" align="left"></td><td class="label" width="20" valign="top" align="left"></td><td valign="top" align="left" style=" float: right;"><a class="close" href="javascript:void(0);" style="margin-left:5px; margin-right: 170px;" onclick="admin_closeExtraSkillDiv('.$skill_no.')" ><img src="'.base_url().'images/icons/close.png" alt="" ></a></td></tr>';*/
        
        ?>
              </td>
           
              <?php 
              /*
                if($i>=2) :
              ?>
              <td>
                <a class="close" href="javascript:void(0);" style="margin:5px 5px;" onclick="admin_closeExtraSkillDiv('<?php echo $db_id;?>')" ><img src="<?php echo base_url();?>images/icons/close.png" alt=""></a>
              </td>
              <?php
              endif; */
              ?>
            </tr>
            <input type="hidden" name="skill_db_id[]" id="dbId"  value="<?php echo $db_id;?>"> 
        </table>
            <?php 
                endfor;
            ?>
            
        <table id="add_more_skill" width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
            
        </table>
        
        
            
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
            <tr>
              <td align="left" valign="top" height="30" width="180" colspan="3">
                <a href="javascript:void(0);" class="add-one" onClick="return admin_add_extra_skill_div();">Add One</a>
              </td>
            </tr>
            <tr>
            
              <td align="left" valign="bottom" height="30" width="75" colspan="2">&nbsp;</td>
              <td align="left" valign="bottom">
              <input name="" type="submit" class="btn"  value="Update" />
              <input name="" type="reset" class="btn"  value="Cancel" onclick="hideSkillEdit(this)" />
              </td>
            </tr>
        </table>        
        <input type="hidden" name="total_skill_divs" id="h_skill" value="<?php echo $skill_no;?>"/>
         
         <?php /*?> //////////// NEW FIELD(S) [BEGIN] //////////// <?php */?>
             <input type="hidden" name="actual_skill_divs" id="actual_skill_divs" value="<?= count($result['skill_arr']) ?>" />
             <input type="hidden" name="deleted_skill_ids" id="deleted_skill_divs" value="" />
         <?php /*?> //////////// NEW FIELD(S) [END] //////////// <?php */?>
        </form>
        
    </div>
    <!--/detail section -->
</div>