<div class="lavel-01">
                                	<!--title section -->
                                	<div class="sec-title">
                                    	<span class="title-left"></span>
                                        <div class="title-body"><h2>Subscriptions</h2></div>
                                        <span class="title-right"></span>
                                    </div>
                                    <!--/title section -->
                                    <div class="show-by">
                                    <label>Show :</label>
                                        <select name="type" id="type" style="width:120px; float:right;">
                                              <option>All</option> <option>SMS Credit</option> <option>Trade Credit</option>
                                        </select>
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#type").msDropDown();
                                                $("#type").hide();
                                            })
                                        </script>
                                    </div>
                                    <div class="clr"></div>
                                    <!--detail section -->
                                    <div class="sec-detail">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                                          <tr>
                                            <th align="left" valign="middle" height="30" width="100">Purchase Date</th>
                                            <th align="left" valign="middle" height="30" width="160" >Purchase Type</th>
                                            <th align="left" valign="middle" height="30" width="80" >Amount</th>
                                            <th align="left" valign="middle" height="30" class="last">Paid By</th>
                                          </tr>
                                           <tr>
                                              <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                                          </tr>
                                        <?php /*?>  <tr>
                                            <td align="left" valign="top" >01/01/2013</td>
                                            <td align="left" valign="top">Personal</td>
                                            <td align="left" valign="top">$20.00</td>
                                            <td align="left" valign="top" class="last">Andrew Black</td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" >01/01/2013</td>
                                            <td align="left" valign="top">Personal</td>
                                            <td align="left" valign="top">$20.00</td>
                                            <td align="left" valign="top" class="last">Andrew Black</td>
                                          </tr><?php */?>
                                          
                                        </table>

                                    </div>
                                    <!--/detail section -->
                                </div>