<script type="text/javascript">
<!--
	function showEduEdit(obj) {
		$(obj).parents('.text-table').hide();
		if($(obj).parents('.sec-detail').find('.form-table').css('display')=='none'){
			$(obj).parents('.sec-detail').find('.form-table').show();
		}
	}
	
	
	// when "cancel" button clicked...
	function hideEduEdit(obj) {
		
		//// remove those extra "add-more" divs...
		var actual_edu_rec_count = parseInt( $('#actual_edu_divs').val() );
		var max_no_of_tbls = 5;
		var start_loop = actual_edu_rec_count+1;
		for(i=start_loop; i<=max_no_of_tbls; i++) {
			tblID = "#edu_"+ i;
			$(obj).parents('.sec-detail').find(tblID).remove();
		}
		$('#h_edu').val( actual_edu_rec_count );	// resetting edu-count...
		$('#deleted_edu_divs').val('');		// resetting deleted record-count to 0 again...
		
		
		$(obj).parents('.sec-detail').find('.form-table').hide(); 
        if($(obj).parents('.sec-detail').find('.text-table').css('display')=='none'){
            $(obj).parents('.sec-detail').find('.text-table').show();
            $(obj).parents('.sec-detail').find('.dd').hide();
            
        }
		
	}
//-->
</script>
<div class="lavel-01">
    <!--title section -->
    <div class="sec-title">
        <span class="title-left"></span>
        <div class="title-body"><h2>Education</h2></div>
        <span class="title-right"></span>
    </div>
    <!--/title section -->
    <!--detail section -->
    <div class="sec-detail">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table text-table" id="member_edu_details">
        
        <?php 
        $count= count($result['education_arr']);
            
            if($count==0)
                $count=1;
            for($i=0;$i<$count;$i++)    :
            
                $country  = get_country_name_by_id($result["education_arr"][$i]["s_school_country"]);
                $state    = $result["education_arr"][$i]["s_school_state"];
                $city     = $result["education_arr"][$i]["s_school_city"];
                
                $edu_address=array();
                if(!empty($country))    
                    $edu_address['country']=$country;
                if(!empty($state))
                    $edu_address['state']=$state;
                if(!empty($city))
                    $edu_address['city']=$city;
                
                $school_location = implode(', ',$edu_address);
                

        ?>
        
            <tr>
              <td align="left" valign="top" height="25" width="180" class="label">School/College</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" ><?php echo $result['education_arr'][$i]['s_school_name'];?></td>
            </tr>
            <tr>
              <td align="left" valign="top" height="25" width="180" class="label">School Location</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" ><?php echo $school_location;?></td>      
            </tr>
            <tr>
              <td align="left" valign="top" height="25" width="180" class="label">Class Year</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" ><?php echo $result['education_arr'][$i]['i_class_year'];?></td>
            </tr>
            <tr>
              <td align="left" valign="top" height="25" width="180" class="label">Degree</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" ><?php echo $result['education_arr'][$i]['s_degree'];?></td>
            </tr>
            <tr><td>&nbsp;</td>
                
            </tr>
            <?php 
            //echo "<br><br>";
            
            endfor;
            ?>
            
            <tr>
              <td align="left" valign="bottom" height="40" colspan="2">&nbsp;</td>
              <td align="left" valign="bottom"><a href="javascript:void(0);" class="edit-btn-other" onclick="showEduEdit(this)">Edit</a></td>
            </tr>
        </table>
        
        <form id="frmManageEduProfile"  method="post" action="<?=admin_base_url()?>members/member_details/modify_my_profile_edu_info_ajax/<?=$result['id']?>" onsubmit="return modify_my_edu_profile_ajax()" enctype="multipart/form-data">   
        <?php 
       
            $edu_no=0;
            $count= count($result['education_arr']);
            
            if($count==0)
                $count=1;
            //echo $count;
            for($i=0;$i<$count;$i++)   :   
            //foreach($result['education_arr'] as $edu) :
            $edu_no++;
            $db_id=isset($result['education_arr'][$i]['id'])? $result['education_arr'][$i]['id']:'' ;
            
        ?>
        <table id="<?php echo "edu_".$edu_no;?>"  width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table edu_info">
        <?php
            if($i>0)    
                echo '<tr><td class="label" width="180" valign="top" height="30" align="left"></td><td class="label" width="20" valign="top" align="left"></td><td valign="top" align="left" style=" float: right;  width:193px;"><a class="close" href="javascript:void(0);" onclick="admin_closeExtraEduDiv(this)" ><img src="'.base_url().'images/icons/close.png" alt="" ></a></td></tr>';
        
        ?>
       
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">School/College</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <input type="text" name="txt_school_name[]" value="<?php echo isset($result['education_arr'][$i]['s_school_name'])? $result['education_arr'][$i]['s_school_name']:'';?>"/>
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">School/College city</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <input type="text" name="txt_school_city[]" value="<?php echo isset($result['education_arr'][$i]['s_school_city'])? $result['education_arr'][$i]['s_school_city']:'';?>"/>
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">School/College state</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <input type="text" name="txt_school_state[]" value="<?php echo isset($result['education_arr'][$i]['s_school_state'])? $result['education_arr'][$i]['s_school_state']:'';?>"/>
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">School/College country</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <select name="txt_school_country[]" class="txt_edu_country" style="width:238px; margin-bottom:6px;">
                        <option value="">---</option>
						<?=makeOptionCountry('',encrypt($result['education_arr'][$i]['s_school_country']));?>

                    </select>
              </td>
            </tr>
            
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">Class Year</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <input type="text" name="txt_school_year[]" value="<?php echo isset($result['education_arr'][$i]['i_class_year'])? $result['education_arr'][$i]['i_class_year']:'';?>"/>
              </td>
            </tr>
            <tr>
              <td align="left" valign="top" height="30" width="180" class="label">Degree</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                    <input type="text" name="txt_school_degree[]" value="<?php echo isset($result['education_arr'][$i]['s_degree'])? $result['education_arr'][$i]['s_degree']:'';?>"/>
              </td>
            </tr>
            <tr><td>&nbsp;</td></tr>
             <input type="hidden" name="db_id[]" id="dbId" value="<?php echo $db_id;?>"  />          
        </table>
        <?php
            endfor;
        ?>
        <table id="add_more_edu" width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
        <tr><td align="left" valign="bottom" height="30" colspan="2">&nbsp;</td></tr>
        </table>
        
         
         <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">  
           <tr>
              <td align="left" valign="top" height="30" width="180" colspan="3"><a href="javascript:void(0);" class="add-one" onClick="return admin_add_extra_edu_div()">Add One</a></td>
            </tr>
         </table>
         
         
         <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
         <tr>
         
              <td align="left" valign="top" height="30" width="180" class="label"></td>
              <td align="left" valign="top" width="20" class="label"></td>
              <td align="left" valign="top" ></td>
            
              <td align="left" valign="bottom" height="30" colspan="2">&nbsp;</td>
              <td align="left" valign="bottom">
              
              <input name="" type="submit" class="btn"  value="Update"/>
              <input name="" type="reset" class="btn"  value="Cancel" onclick="hideEduEdit(this)" />
              </td>
            </tr>
         </table>
         <input type="hidden" name="total_edu_divs" id="h_edu" value="<?php echo $edu_no;?>" />
         
         <?php /*?> //////////// NEW FIELD(S) [BEGIN] //////////// <?php */?>
             <input type="hidden" name="actual_edu_divs" id="actual_edu_divs" value="<?= count($result['education_arr']) ?>" />
             <input type="hidden" name="deleted_edu_ids" id="deleted_edu_divs" value="" />
         <?php /*?> //////////// NEW FIELD(S) [END] //////////// <?php */?>
        </form>
        
         
    </div>
    <!--/detail section -->
</div>



<!-- ################### HTML TO COPY FOR "ADD MORE" [BEGIN] ################### -->

<span id="div_edu_copy" style="display:none;">
<table  width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table edu_info">
<?php
    if($i>0)    
        echo '<tr><td class="label" width="180" valign="top" height="30" align="left"></td><td class="label" width="20" valign="top" align="left"></td><td valign="top" align="left" style=" float: right;  width:193px;"><a class="close" href="javascript:void(0);" onclick="admin_closeExtraEduDiv(this)" ><img src="'.base_url().'images/icons/close.png" alt="" ></a></td></tr>';

?>

    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">School/College</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <input type="text" name="txt_school_name[]" value=""/>
      </td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">School/College city</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <input type="text" name="txt_school_city[]" value=""/>
      </td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">School/College state</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <input type="text" name="txt_school_state[]" value=""/>
      </td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">School/College country</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <select name="txt_school_country[]" class="txt_edu_country1" style="width:238px; margin-bottom:6px;">
                <option value="">---</option>
                <?= makeOptionCountry('') ?>
            </select>
      </td>
    </tr>
    
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Class Year</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <input type="text" name="txt_school_year[]" value=""/>
      </td>
    </tr>
    <tr>
      <td align="left" valign="top" height="30" width="180" class="label">Degree</td>
      <td align="left" valign="top" width="20" class="label">:</td>
      <td align="left" valign="top" >
            <input type="text" name="txt_school_degree[]" value=""/>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
     <input type="hidden" name="db_id[]" id="dbId" value=""  />          
</table>
</span>
<!-- ################### HTML TO COPY FOR "ADD MORE" [END] ################### -->