<div class="lavel-01">
                                	<!--title section -->
                                	<div class="sec-title">
                                    	<span class="title-left"></span>
                                        <div class="title-body"><h2>Balance in Account</h2></div>
                                        <span class="title-right"></span>
                                    </div>
                                    <!--/title section -->
                                    <!--detail section -->
                                    <div class="sec-detail">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table">
                                            <tr>
                                              <td align="left" valign="top" height="25" width="180" class="label">SMS Amount</td>
                                              <td align="left" valign="top" width="20" class="label">:</td>
                                              <td align="left" valign="top" >$ 00.00</td>
                                            </tr>
                                            <tr>
                                              <td align="left" valign="top" height="25" width="180" class="label">Trade Amount</td>
                                              <td align="left" valign="top" width="20" class="label">:</td>
                                              <td align="left" valign="top" >$ 00.00</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!--/detail section -->
                                </div>