<?php
//pr($info_arr);
//die();
if(count($info_arr)!=0)
{
    $counter = 0;
    foreach($info_arr as $info)   
    {
        $counter++;

?>             
                <div class="pop-content <?php echo ($counter==1)?'first':''?>" id="del_commitmen<?= $info['id'] ?>"> <div class="ring_del"> <a href="javascript:void(0)" onclick="return del_commitment('<?= $info['id'] ?>')"><img src="<?=base_url() ?>images/fe/cross-icon.gif"></a></div>       
                       <img src="<?php echo get_profile_image($info['i_user_id'],'thumb')?>" alt="posteb by" width="73" height="73" class="posted-by" />
                       <div class="right-panel">
                            <h5><?php echo $info->s_profile_name?></h5>
                            <h6>Updated on: <span><?php echo getShortDate($info['dt_created_on'],5)?></span> </h6>
                            <h6>Started on: <span><?php echo getShortDate($info['dt_start_time'],5)?></span> </h6>
                            <h6>Ended on: <span><?php echo getShortDate($info['dt_end_time'],5)?></span> </h6>
                            <p><?php echo $info['s_contents']?></p>
                       </div>
                    </div>

<?php
    }
}
else
{
?>
<div class="shade_box_blue" style="padding-top:5px; width: 578px; height: 280px;">
<div class="shade_norecords" style="width:325px;">
<p class="blue_bold12" style="font-weight: bold; margin-top: 100px;">No comments.</p>
</div>
</div>
<?php
}

?>                    
<div class="clr"></div>
<style>
    .ring_del{ position: absolute; right: 10px; top: 10px;}
</style>