<?php include(APPPATH."views/layouts/logged_header.phtml");?>
<!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
<!-- /NAVIGATION SECTION -->

</div>
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                      
                        <!-- left container -->
                        <div id="left_container01">
                        	<div class="page_heading">
                            	<div class="left"><img src="images/icons/msg.png" alt="" width="48" height="32"/> Compose Message</div>
                            </div>
                           
                        	<div class="arrow_btm"></div>
                            <div class="frm_box inbox_div_blue" >
                            
                            	
                                <div id="contact_list" >
                                    <div class="lable01" style="width:180px;">To :</div>
                                      <div class="selectRecipients">
                                       <?php 
										  if(count($contacts)):
											 $count_total = 1;
											  foreach($contacts as $key=>$val){
												  
												  $img = get_profile_image($val['user_id'], 'thumb');
												  
												  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
												   		$profile_link = get_profile_url($val['user_id'],$val['user_profile_name']);
												  }
												  else{
													   $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
												  }
												  
												  $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
														
										 ?>
                                         <div class="image-block <?=$CSS?>">
                                              <input  type="checkbox"  value="<?=encrypt($val['user_id'])?>" id="chkmember<?=$val['user_id']?>" name="chkmember<?=$val['user_id']?>" />
                                              <div class="inside">
                                                  <?php /*?><div style="background:url('<?=$img?>') no-repeat center;width:60px; height:60px;" class="pro_photo2"></div><?php */?>
                                                  <img alt="Friend" src="<?=$img?>" /><br/><br/><br/>
                                                  <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>
                                              </div>
                                          </div>
                                        
                                       	 
										 <?php	$count_total++;	
										 			}
										 		endif; 
										 ?>
                                       	   
                                	  </div> 
                                      <div style="margin-left: 195px;" class="error_msg" id="err_send_recepients"></div>
								</div>
                            
                           
                                
                              <?php /*?>  <div class="field03">
                                       <input type="text" id="invite-frnd"  />
										<script type="text/javascript">
                                            $(document).ready(function() {
                                                $("#invite-frnd").tokenInput("http://shell.loopj.com/tokeninput/tvshows.php", {
                                                    prePopulate: [
                                                        { name: "Name 1"} , 
														
                                                    ]
                                                })
                                                .blur();
                                            });
                                        </script>
                                </div><?php */?>
                                
                                <div class="clr"></div>
                                
                                 <div class="lable01" style="width:180px;">Subject :</div>
                                <div class="field03">
                                      <input name="subject" id="subject" type="text" />
                                </div>
                                
                                <div class="clr"></div>
                                <div class="lable01" style="width:180px;">Body  :</div>
                                <div class="field03">
                                      <textarea id="message" name="message" style="width:400px; height:90px;"></textarea>
                                
                                <div class="error_msg" id="err_send_message" style=" margin-top: -5px;"></div>
                                </div>
                                <div class="clr"></div>
                             
                                
                                <div class="lable01" style="width:180px;">&nbsp;</div>
                                <div class="field03">

                                      <input name="btn_submit" id="btn_submit" type="button" value="Send"  onclick="send_message();" class="btn"/>
                                </div>
                                <div class="clr"></div>
                            </div>                            
                              
                        </div>
                          
                        <!-- /left container -->
                        <!-- right container -->
                         <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>

<!-- /FOOTER SECTION -->




<div class="lightbox change_contact_address" style="width:550px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4> Change Contact Info before You Proceed </h4></div></div>
           <div class="frm_box">
             <div class="lable01">Your Contact Email:</div> 
             <div class="field01"><input name="" type="text" value="lorem@abc.com" /> </div>
             <div class="clr"></div>
             <div class="lable01">Your Contact No.:</div> 
             <div class="field01"><input name="" type="text"  value="123456"/> </div>
            
             <div class="clr"></div>
             <div class="lable01">&nbsp;</div> 
             <div class="field01"><input name="" type="button" value="Proceed" class="btn" /></div>
             <div class="clr"></div>
           </div>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<script type="text/javascript">
<!--	
	var ticker_holder = $('.bargaining').get(0);
	var ticker_text = $('.ticker').get(0);
	var ticker_pos = ticker_text.parentNode.offsetWidth;
	
	var ticker_data = $(ticker_holder).html();
	$(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');
	
	$('#sub-nav').hover
	(
	function() { $('marquee', this).get(0).stop();  },
	function() { $('marquee', this).get(0).start(); }
	); 
//-->
</script>
