<div class="lightbox message_div" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="images/icons/msg.png" alt="" width="30"  /> Message Detail </h4>
                  </div>
            </div>
            <div class="txt_content01" id="mail_content" style="padding:5px;">
            	
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>