<?php include(APPPATH."views/layouts/logged_header.phtml");?>
<!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
<!-- /NAVIGATION SECTION -->

</div>
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                      
                        <!-- left container -->
                        <div id="left_container01">
                        	<div class="page_heading">
                            	<div class="left"><img src="images/icons/msg.png" alt="" width="48" height="32"/> Reply Message</div>
                            </div>
                           
                        	<div class="arrow_btm"></div>
                            <div class="frm_box inbox_div_blue" >
                            
							 <?php 
                                    //pr($contacts); 
                                    $img = get_profile_image($contacts['id'], 'thumb');
                                    if($contacts['if_already_friend'] == 'true' || $contacts['already_added_netpal'] == 'true'){
                                          $profile_link = get_profile_url($contacts['id'],$contacts['user_profile_name']);
                                    }
                                    else{
                                         $profile_link = get_public_profile_url($contacts['id'],$contacts['user_profile_name']);
                                    }
                                    
                             ?>
                                <div id="contact_list" >
                                    <div class="lable01" style="width:180px;">To :</div>
                                     <div class="field03">
                                     <a href="<?=$profile_link?>" target="_blank" ><span style="color:#004084; font-size:14px;"><?=$contacts['s_first_name']?></span></a>
                                	 </div>
                                     
                                     <input  type="hidden"  value="<?=encrypt($contacts['id'])?>" id="reply_user" name="reply_user" />
                                      <div style="margin-left: 195px;" class="error_msg" id="err_send_recepients"></div>
								</div>
                            
                           
                                
                              <?php /*?>  <div class="field03">
                                       <input type="text" id="invite-frnd"  />
										<script type="text/javascript">
                                            $(document).ready(function() {
                                                $("#invite-frnd").tokenInput("http://shell.loopj.com/tokeninput/tvshows.php", {
                                                    prePopulate: [
                                                        { name: "Name 1"} , 
														
                                                    ]
                                                })
                                                .blur();
                                            });
                                        </script>
                                </div><?php */?>
                                
                                <div class="clr"></div>
                                
                                 <div class="lable01" style="width:180px;">Subject :</div>
                                <div class="field03">
                                      <input name="subject" id="subject" type="text" value="RE: <?=$message_detail['s_subject']?>" />
                                </div>
                                
                                <div class="clr"></div>
                                <div class="lable01" style="width:180px;">Body  :</div>
                                <div class="field03">
                                      <textarea id="message" name="message" style="width:400px; height:140px;">
                                      



                                      <?= '.........................................................'; ?>
                                      <?=br2nl($message_detail['s_message'])?>
                                      </textarea>
                                
                                <div class="error_msg" id="err_send_message" style=" margin-top: -5px;"></div>
                                </div>
                                <div class="clr"></div>
                             
                                
                                <div class="lable01" style="width:180px;">&nbsp;</div>
                                <div class="field03">

                                      <input name="btn_submit" id="btn_submit" type="button" value="Send"  onclick="reply_message();" class="btn"/>
                                </div>
                                <div class="clr"></div>
                            </div>                            
                              
                        </div>
                          
                        <!-- /left container -->
                        <!-- right container -->
                         <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>

<!-- /FOOTER SECTION -->




<div class="lightbox change_contact_address" style="width:550px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4> Change Contact Info before You Proceed </h4></div></div>
           <div class="frm_box">
             <div class="lable01">Your Contact Email:</div> 
             <div class="field01"><input name="" type="text" contactsue="lorem@abc.com" /> </div>
             <div class="clr"></div>
             <div class="lable01">Your Contact No.:</div> 
             <div class="field01"><input name="" type="text"  contactsue="123456"/> </div>
            
             <div class="clr"></div>
             <div class="lable01">&nbsp;</div> 
             <div class="field01"><input name="" type="button" contactsue="Proceed" class="btn" /></div>
             <div class="clr"></div>
           </div>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<script type="text/javascript">
<!--	
	var ticker_holder = $('.bargaining').get(0);
	var ticker_text = $('.ticker').get(0);
	var ticker_pos = ticker_text.parentNode.offsetWidth;
	
	var ticker_data = $(ticker_holder).html();
	$(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');
	
	$('#sub-nav').hover
	(
	function() { $('marquee', this).get(0).stop();  },
	function() { $('marquee', this).get(0).start(); }
	); 
//-->
</script>
