<?php #pr($result_arr);
	if(count($result_arr)){
		foreach($result_arr as $key=> $val){
			
			$profile_image = get_profile_image($val['post_owner_user_id'],'thumb');
			$s_profile_name = $val['s_first_name'] .' ' .$val['s_last_name'] ;
											
			if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
				  $profile_link = get_profile_url($val['post_owner_user_id'],$s_profile_name);
			}else
			{
			   $profile_link = get_public_profile_url($val['post_owner_user_id'],$s_profile_name); 
			}
			
			
?>

            <li>
                <span class="payer-member-name">
                <div class="pro_photo3" style="background:url(<?php echo $profile_image;?>) no-repeat center;width:30px; height:30px;" ></div>
                    <div class="pra-member-content-friend">
                        <a href="<?=$profile_link?>"><?=$s_profile_name?></a>
                        <span class="pra-invite-link" id="invite_text_<?=$val['post_owner_user_id']?>">
                        <?php if($val['member_group_status'] == 'accepted'){ ?>
                        <a href="javascript:void(0);" >Already Member</a>
                        <?php }
						else if($val['member_group_status'] == 'not available'){
						?>
							<a href="javascript:void(0);" onclick="invite_prayer_group(<?=$val['post_owner_user_id']?>)">Invite To Group</a>  
						<?php }
							else if($val['member_group_status'] == 'pending'){
						?>
							<a href="javascript:void(0);" onclick="invite_prayer_group(<?=$val['post_owner_user_id']?>)">Re-send Invitation</a>  
						<?php }
						?>
                        </span>
                        <ul class="prayer-option">
                   			 <li>Location- <?=get_countryname($val['i_country_id'])?></li>
                    		 <li>I</li>
                   			 <li>No.of friends - <?=$val['total_friend']?> </li>
                    
                   		</ul>
                        <!--<p style="color:#2B629C;">Relationship: <?=$val['relationship']?></p>-->
                    </div>
                
                </span>
                
            </li>                                                                                        
        

<?php 
		}
	}
?>
