<table width="100%" border="0" cellspacing="0" cellpadding="0">

         <?php

            if($info_arr)

            {

             ?>

  <thead>

    <tr>

      <th>S no.</th>

      <th align="left">Name</th>

      <!--<th>Joined on</th>-->

      <th align="left">Email</th>

      <th align="left">Status</th>

    </tr>

   </thead>

    <tbody>

    <?php

                $i = 1;
				$status_label = '';
                foreach ($info_arr as $member) {
					if ($member->status == 0) {
						$status_label = 'Invited, Not joined';
					} else { 
						$status_label = 'Invited, Joined';	
					}
                    ?>

    <tr>

    

      <td width="6%"><?php echo $i++; ?></td>

      <td width="27%" class="textleft"><?php echo $member->name; ?></td>

      <!--<td width="5%"><?php //echo getShortDate($member->joined_on_date,3); ?></td>-->

      <td width="25%" class="textleft"><?php echo $member->email; ?></td>

      <td width="20%"><?php echo $status_label; ?></td>
    </tr>
	
	

    <?php } ?>

  </tbody>

  <?php }

else

{

  echo '<tr><td colspan="5">No Records</td></tr>';

}  ?>

</table>
<div class="paging"><ul><?= $page_links ?></ul></div>