
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<?php 
 $now_page = round(($current_page/$pagination_per_page)+1);
  
?>
         <?php

            if($info_arr)

            {
                $j= $now_page - 1;
                if($now_page > 1){  $i = $now_page+(24*$j); } else {$i=1;}

             ?>

  <thead>

    <tr>
	  <th></th>	
      <th>S no.</th>

      <th align="left">Name</th>
      <th align="left">Email</th>

    </tr>

   </thead>

    <tbody>
<form style="width:412px;" name="sent_invitation_user_frm" id="sent_invitation_user_frm" method="post" action="<?=base_url().'logged/church/cogtime_user_sent_invitation'?>">
    <?php

                //$i = 1;
//pr($info_arr);
                foreach ($info_arr as $member) {
                                   
                    ?>

    <tr>

    
        <td width="6%"><input type="checkbox" name="cogtime_user_id[]" id="cogtime_user_id<?php echo $member->id?>" class="cogtime_user_id" value="<?php echo $member->id?>" <?php if (in_array($member->id, $_SESSION['check_member'])){ echo'checked=""'; }  ?> >
            <input type="hidden" value="<?php $arr = $_SESSION['check_member'];
 foreach ($arr as $val){
    echo $id = $val.'/';
 }
                
             ?>" name="member_id_arr">
        </td>
	 
      <td width="6%"><?php echo $i++; ?></td>

      <td width="27%" class="textleft"><?php echo $member->user_name; ?></td>

      <td width="25%" class="textleft"><?php echo $member->s_email?></td>

    </tr>
	
	

    <?php
    
                                     
    
                                     } ?>
	<input type="submit" id="sent_invitation_user_btn" value="submit" class="post-btn" style="display:none;"> 
</form>
  </tbody>

  <?php }

else

{

  echo '<tr><td colspan="5">No Records</td></tr>';

}  ?>

</table>
<div class="paging"><ul><?= $page_links ?></ul></div>
<script type="text/javascript">

$(document).ready(function(){
    $('.cogtime_user_id').click(function(){
         var id = $(this).val();
         var type = 'docheck';
         if($('#cogtime_user_id'+id).is(':checked')){
            var type = 'docheck';
            $.ajax({
        type: 'post',
        url: base_url+'logged/church/store_in_session',
       // dataType: 'json',
        data: {'id' : id ,'type': type},
        success: function (data, status) {
  
     location.reload();

            }   // end of success function...


    });
         }
          if(!$('#cogtime_user_id'+id).is(':checked')){
            var type = 'uncheck';
            $.ajax({
        type: 'post',
        url: base_url+'logged/church/store_in_session',
       // dataType: 'json',
        data: {'id' : id ,'type': type},
        success: function (data, status) {
  
     location.reload();

            }   // end of success function...


    });
        }
            
//          
           
        
        });
         
    });

</script>