<div class="place-time" >
            	<!--washington time box -->
            	<div class="time-box washington">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Washington</p>
                    <span><?=$time_val['washington']?></span>
                </div>
				
                <!--washington time box end-->
                <!--london time box -->
            	<div class="time-box london">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>London</p>
                    <span><?=$time_val['london']?></span>
                </div>
                <!--london time box end-->
                <!--russia time box -->
            	<div class="time-box russia">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Moscow</p>
                    <span><?=$time_val['moscow']?></span>
                </div>
                <!--russia time box end-->
                <!--beijing time box -->
            	<div class="time-box beijing">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Beijing</p>
                    <span><?=$time_val['beijing']?></span>
                </div>
                <!--beijing time box end-->
                <!--brasilia time box -->
            	<div class="time-box brasilia">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Brasilia</p>
                    <span><?=$time_val['brasilia']?></span>
                </div>
                <!--brasilia time box end-->
                <!--capetown time box -->
            	<div class="time-box capetown">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Capetown</p>
                    <span><?=$time_val['capetown']?></span>
                </div>
                <!--capetown time box end-->
                <!--delhi time box -->
            	<div class="time-box delhi">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>New Delhi</p>
                    <span><?=$time_val['delhi']?></span>
                </div>
                <!--delhi time box end-->
                <!--tokyo time box -->
            	<div class="time-box tokyo">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Tokyo</p>
                    <span><?=$time_val['tokyo']?></span>
                </div>
                <!--tokyo time box end-->
                <!--sydney time box -->
            	<div class="time-box sydney">
                	<img src="images/white-dot.png" alt="white dot" />
                    <p>Sydney</p>
                    <span><?=$time_val['sydney']?></span>
                </div>
                <!--sydney time box end-->
</div>