<!-- FOOTER SECTION -->
<div id="footer_section">
    <div id="footer">
        <p>
            <?php
            if (count($footer_cms_menu) > 0) {
                $i = 1;
                $count = count($footer_cms_menu);
                foreach ($footer_cms_menu as $key => $val) {
                    $CSS = (($count - 1) != $key) ? '|' : '';
                    $link = get_cms_url($val['id'], $val['s_title']);
                    ?>
                    <a href="<?= $link ?>"><?= $val['s_title'] ?></a><?= $CSS ?>
                    <?php
                    $i++;
                }
            }
            $sess_id = $this->session->userdata('user_id');
            ?>
                    <font style="color: #013759;">|</font><a href="<?php  if(!empty($sess_id)){ echo base_url().'advertisement_request';}else{ echo base_url().'register.html';} ?>" >Advertisement</a> 
        </p>
        <p class="copyright">&copy; All Rights Reserved COGTIME 2014</p>
    </div>
</div>
<!-- /FOOTER SECTION -->
<!-- ############ Need to login dialog box [Start] ########### -->
<div id="need_to_login" style="display:none;cursor: default"> 
    <div style="float:right;cursor:pointer;font-size:14px;padding-left:5px;padding-bottom:5px" onclick="$.unblockUI()">X</div>
    You need to login first.<br />
    <a href="<?= base_url() ?>" style="color:inherit">Login here</a>
</div>
<!-- ############ Need to login dialog box [End] ########### -->


<!-- ############ Loading Section [Start] ########### -->
<!--<div id="loading_dialog" class="modal_dialog" style="width:auto; padding:20px; background:transparent;border:none"> <img src="images/loading_big.gif" width="50"/> </div>-->
<div id="loading_dialog" class="modal_dialog" style="width:auto; padding:20px; background:transparent;border:none;font-weight:bold;color:#FFFFFF; display:none;"><?= ('Loading...') ?><span id="loading_dot"></span></div>
<!-- ############ Loading Section [End] ########### -->












<!--login popup start -->
<?php
if (!@$session_data['loggedin']) {

    $RemberEmail = '';
    $RemberPwd = '';
    $Rember = '';
    if (isset($_COOKIE['CG_FO']['email']) && isset($_COOKIE['CG_FO']['password'])) {
        $RemberEmail = $_COOKIE['CG_FO']['email'];
        $RemberPwd = $_COOKIE['CG_FO']['password'];
        $Rember = $_COOKIE['CG_FO']['remember'];
    }

    //echo $this->router->class; echo '<br/>';
//echo $this->router->method ; 
    ?>		


    <?php /* ?> start open login popup<?php */ ?>

    <script language="javascript" type="text/javascript">
        $(document).ready(function() {


            var is_login_referrer = '<?= @$session_data['login_referrer'] ?>';
            var is_loginPopUpShown = '<?= @$this->session->userdata('loginPopUp') ?>';
            var current_controller = '<?= $this->router->class ?>';
            var current_method = '<?= @$this->router->method ?>';

            ///alert(current_controller+' ==lg-ref: '+is_login_referrer+' login popp : '+is_loginPopUpShown+' cur mehod: '+current_method)


        });
    </script>


    <?php /* ?> end open login popup<?php */ ?>


    <div  class="lightbox login-box" style="width:500px;">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>

        <div class="mid">
            <div class="heading">
                <div class="left">
                    <h4>User Login</h4>
                </div>
            </div>
            <div class="frm_box login">
                <form onsubmit="return userAjaxLogin(this.email_login.value, this.password_login.value);" action="" method="post" name="frmLogin" id="frmLogin"> 
                    <input name="login_referrer" id="login_referrer" type="hidden" value="<?= @$session_data['login_referrer'] ?>"/>
                    <input name="current_referrer" id="current_referrer" type="hidden" value=""/>
                    <input type="hidden" name="is_submitted" id="is_submitted" value="Y"  />


                    <div class="lable01">Email :</div>
                    <div class="field01">
                        <input name="email_login" id="email_login" type="text" value="<?= ($RemberEmail == '') ? "Email" : $RemberEmail; ?>" />
                    </div> 
                    <div id="error_msg_email_login" class="error-message"></div> 


                    <div class="clr"></div>

                    <div class="lable01">Password:</div>
                    <div class="field01">
                        <input name="password_login" id="password_login" type="password" value="<?= ($RemberPwd == '') ? "Password" : $RemberPwd; ?>" />
                    </div>
                    <div id="error_msg_password_login" class="error_msg"></div>

                    <div class="clr"></div>
                    <div class="lable01">&nbsp;</div>
                    <label class="remember-pass"><input type="checkbox" id="chkRem" value="1" name="chkRem" <?= ($Rember == 'checked' ? 'checked="checked"' : '') ?> class="sigin_chk" />Remember me</label>

                    <a class="forget-password" href="<?= base_url() ?>forgot-password.html">Forgot password</a>
                    <div class="clr"></div>
                    <div class="lable01">&nbsp;</div>
                    <div class="field01">
                        <input name="" type="submit" value="Login" class="btn" />
                    </div>
                    <div class="clr"></div>
                    <a href="<?= base_url() . 'register.html' ?>" class="register-link">If you are not a register user, then please register now.</a>
                </form>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>
    <?php
}
?>  
<?php /* ?>  ############ LOGINBOX Section [End] ########### <?php */ ?>


<!--login popup end -->



<a href="javascript:void(0);" class="control" id="control"><!--<img src="images/online.png" alt="bullet" width="12" height="12">--></a>
<!--notification start -->
<div id="BeeperBox" class="UIBeeper">
    <div class="UIBeeper_Full">
        <div class="Beeps">
            <div class="UIBeep UIBeep_Top UIBeep_Bottom UIBeep_Selected">
                <!-- Below Is The Link To Which Bepper Will Point To (replace # with the required link) -->
                <a class="UIBeep_NonIntentional" href="javascript:void(0);">
                    <span class="beeper_x">&nbsp;</span>
                    <div class="UIBeep_Title" id="cogtime_notification_div">

   <!--<span class="blueName">Praveen Gowda</span> likes your comment on <span class="blueName">Hitherto Web Labs</span>.-->
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!--notification end -->

<?php /* ?> SYSTEM REMINDER POP UP  <?php */ ?>












<!--reminder popup start -->
<div class="lightbox reminder" style="width:500px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/clock1.png" alt="" /> Reminder Notification</h4></div></div>
        <DIV id="reminder_html"></DIV>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
<!--reminder popup end -->




<?php /* ?>NOTIFICATION BLOCK <?php */ ?>
<?php if (@$session_data['loggedin'] && $this->session->userdata('user_type') == 1) { ?>
<!--    <script type="text/javascript">
    // to show clock
        $(document).ready(function(arg) {
           get_new_request_notification();
           setInterval(function() {
                get_new_request_notification()
            }, 59000);

        });
        $(document).ready(function() {
            $('.ui-datepicker').hide();
        });

        function get_new_request_notification() {
            //alert(1)
            $.ajax({
                type: "post",
                url: base_url + 'base_controller/get_new_request_',
                dataType: "json",
                success: function(json_response) {

                    if (json_response.result == 'success') {
                        //alert(json_response.friend_count);
                        if (json_response.friend_count > 0)
                        {
                            $('#frnd_notification').attr('style', 'display:inline-block;');
                            $("#frnd_notification").addClass('notification');
                            $('#frnd_notification').html(json_response.friend_count);

                        }

                        if (json_response.friend_count == 0) {
                            $('#frnd_notification').hide();
                        }

                        if (json_response.netpal_count > 0) {
                            $('#netpal_notification').attr('style', 'display:inline-block;');
                            $("#netpal_notification").addClass('notification');
                            $('#netpal_notification').html(json_response.netpal_count);
                        }
                        else if (json_response.netpal_count == 0) {
                            $('#netpal_notification').hide();
                        }


                        if (json_response.prayer_count > 0) {
                            $('#prayer_notification').attr('style', 'display:inline-block;');
                            $("#prayer_notification").addClass('notification');
                            $('#prayer_notification').html(json_response.prayer_count);
                        }
                        else if (json_response.prayer_count == 0) {
                            $('#prayer_notification').hide();
                        }

                        if (json_response.prayergrp_notification_count > 0) {
                            $('#pryergrp_not').attr('style', 'display:inline-block;');
                            $("#pryergrp_not").addClass('notification');
                            $('#pryergrp_not').html(json_response.prayergrp_notification_count);
                        }
                        else if (json_response.prayergrp_notification_count == 0) {
                            $('#pryergrp_not').hide();
                        }
						
						if (json_response.prayer_room_notification_count > 0) {
                            $('#prayerRoom_not').attr('style', 'display:inline-block;');
                            $("#prayerRoom_not").addClass('notification');
                            $('#prayerRoom_not').html(json_response.prayer_room_notification_count);
                        }
                        else if (json_response.prayer_room_notification_count == 0) {
                            $('#prayerRoom_not').hide();
                        }
						
						if (json_response.ring_notification_count > 0) {
                            //$('#ring_not').attr('style', 'display:inline-block;');
                            $("#ring_not").addClass('notification');
                            $('#ring_not').html(json_response.ring_notification_count);
                        }
                        else if (json_response.ring_notification_count == 0) {
                            $('#ring_not').hide();
                        }
						
                    }

                },
                error: function() {
                    //showUIMsg('Some error occurred. Please try again.');
                }
            });
        }


    </script>-->

<!--    <script type="text/javascript">
    // to show clock
        $(document).ready(function(arg) {
           get_system_notifications();
           get_system_reminders_at_remind_me_time();
            get_system_reminders();

    //setInterval(function(){get_system_notifications()},59000);
        });

        function playSound(soundfile) {

            $('#control').html("<embed src=\"" + soundfile + "\" hidden=\"true\" autostart=\"true\" loop=\"false\" />");
        }

        function get_system_notifications() {

            //alert(1)
            var sound_file = base_url + "uploads/alert/56895^DING.mp3"
            $.ajax({
                type: "post",
                url: '<?= base_url() ?>base_controller/get_new_notifications',
                dataType: "json",
                success: function(json_response) {
                    //alert(11);
                    if (json_response.result === 'success') {
                        //alert(json_response.notification_msg);
                        $('#cogtime_notification_div').html(json_response.notification_msg);
                        $('.control').trigger('click');
                        get_new_request_notification();
                        playSound(sound_file);
                    }
                    setTimeout(function() {
                        get_system_notifications()
                    }, 10000);
                },
                error: function() {
                    //showUIMsg('Some error occurred. Please try again.');
                }
            });
        }

    //////// get system reminders ?//////////////////////////

        function get_system_reminders() {

            //alert(1)
			var sound_file = base_url + "uploads/alert/56895^DING.mp3"
            $.ajax({
                type: "post",
                url: '<?= base_url() ?>base_controller/is_active_reminder_popup',
                dataType: "json",
                success: function(json_response) {
                    //alert(11);
                    if (json_response.result === 'success') {
                        // alert(json_response.reminder_html);
                        $('#cogtime_notification_div').html(json_response.reminder_html);
						//$('#reminder_html').html(json_response.reminder_html);
                      //  show_dialog('reminder');
						 $('.control').trigger('click');
                        playSound(sound_file);
                    }
                    setTimeout(function() {
                        get_system_reminders()
                    }, 10000);
                },
                error: function() {
                    //showUIMsg('Some error occurred. Please try again.');
                }
            });
        }

    ///////////end //////////////////////////////////////////


    //////// get system reminders at remind me time of user//////////////////////////

//        function get_system_reminders_at_remind_me_time() {
//
//            //alert(1)
//			var sound_file = base_url + "uploads/alert/56895^DING.mp3"
//            $.ajax({
//                type: "post",
//                url: '<?= base_url() ?>base_controller/show_system_reminder_popup_at_remind_me_time',
//                dataType: "json",
//                success: function(json_response) {
//                    ///alert(11);
//                    if (json_response.result === 'success') {
//                        ///alert(json_response.notification_msg);
//                        $('#cogtime_notification_div').html(json_response.reminder_html);
//						//$('#reminder').html(json_response.reminder_html);
//                       // show_dialog('reminder');
//						 $('.control').trigger('click');
//                        get_new_request_notification();
//                        playSound(sound_file);
//                    }
//                    setTimeout(function() {
//                        get_system_reminders_at_remind_me_time()
//                    }, 10000);
//                },
//                error: function() {
//                    //showUIMsg('Some error occurred. Please try again.');
//                }
//            });
//        }

    ///////////end //////////////////////////////////////////

    </script>-->
    
    
<div class="lightbox optout-as-prayer-partner2" style="width:480px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4>Confirmation Message</h4>
                  </div>
            </div>
           <p class="bold-text">Are you sure you want to quit yourself from Prayer Partner Zone?</p>
           
           <form enctype="multipart/form-data" method="post" action="" >
            <input class="btn" type="button" style="margin-left:146px;" value="Yes" name="" onclick="chnge_pp_status('Y')" />
            <input class="btn" type="button" onclick="hide_dialog()" value="No" name="" />
           </form>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<div class="lightbox enlist-as-prayer-partner2" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4>Confirmation Message</h4>
                  </div>
            </div>
           <p class="bold-text">Are you sure you want to enlist yourself as Prayer Partner?</p>
           
           <form enctype="multipart/form-data" method="post" action="" >
            <input class="btn" type="button" style="margin-left:146px;" value="Yes" name="" onclick="chnge_pp_status('N')" />
            <input class="btn" type="button" onclick="hide_dialog()" value="No" name="" />
           </form>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>   
<script type="text/javascript">

//show current time

var currenttime = '<? print $user_local_time_to_display ?>' //PHP method of getting server date

///////////Stop editting here/////////////////////////////////

var montharray=new Array("January","February","March","April","May","June","July","August","September","October","November","December")
var serverdate=new Date(currenttime)

function padlength(what){
var output=(what.toString().length==1)? "0"+what : what
return output
}

function displaytime(){
serverdate.setSeconds(serverdate.getSeconds()+1)
//var datestring=montharray[serverdate.getMonth()]+" "+padlength(serverdate.getDate())+", "+serverdate.getFullYear()
var timestring=padlength(serverdate.getHours())+":"+padlength(serverdate.getMinutes())+":"+padlength(serverdate.getSeconds())
$('#user_local_time').html(timestring);     
}

window.onload=function(){
setInterval("displaytime()", 1000)
}


$(document).ready(function(arg) {
//get_user_clock();
//setInterval(function(){get_user_clock()},1000);

});
 
/*function get_user_clock() {//return false;
	$.ajax({
	   type: "post",
	   url: '<?=base_url()?>base_controller/getUserClock',
	   data: {zone_val:'<?=$arr_profile_info['s_time']?>'},
	   dataType:"json",
	   success: function(json_response){

			if(json_response.result = 'success') {
				$('#user_local_time').html(json_response.time);		
			}
			
		},
		error: function(){
			//showUIMsg('Some error occurred. Please try again.');
		}
	});
}*/

</script>
    
<?php } ?>
<?php /* ?>NOTIFICATION BLOCK <?php */ ?>


<?php /* ?>Salvation prayer popups<?php */ ?>

<?php if ($page_name != '') { ?>
    <div class="lightbox welcome">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div>
                    <h4>Welcome </h4>                
            </div>
            <div >
                <h5> Welcome to CoGTime where everybody is somebody.</h5> 
                <p class="blue_bold12"><?= $this->session->userdata('username') ?> <span>YOU'VE MADE IT!!</span></p>
                <p class="light_blue_bold12"> <?= $salvation_prayer['result']['s_welcome_msg'] ?></p>
                <br />
                <input name="" type="button" value="About This Site" class="popup-yes"  onclick="hide_dialog();window.location.href='<?=base_url()?>cms/2/about-us.html'"   />
                &nbsp;
                <input name="" type="button" value="What it means to be a Christian" class="popup-no"   onclick="show_another_dialog('being_christian')"  />
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>
    <div class="lightbox being_christian">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div class="heading-cap">
                    <h4>Being a Christian </h4>
            </div>
            <script type="text/javascript">
                stepcarousel.setup({
                    galleryid: 'bandContainer1', //id of carousel DIV
                    beltclass: 'belt', //class of inner "belt" DIV containing all the panel DIVs
                    panelclass: 'thumbnails', //class of panel DIVs each holding content
                    autostep: {enable: true, moveby: 1, pause: 3000},
                    panelbehavior: {speed: 500, wraparound: true, persist: false},
                    defaultbuttons: {enable: false, moveby: 1, leftnav: ['http://i34.tinypic.com/317e0s5.gif', -5, 80], rightnav: ['http://i38.tinypic.com/33o7di8.gif', -20, 80]},
                    statusvars: ['statusA', 'statusB', 'statusC'], //register 3 variables that contain current panel (start), current panel (last), and total panels
                    contenttype: ['inline'] //content setting ['inline'] or ['external', 'path_to_external_file']
                })
            </script>
            <img src="images/arr_l.png" alt=""  class="scroller_arrow01"  onclick="javascript:stepcarousel.stepBy('bandContainer1', -1)"/>
            <div id="bandContainer1" class="bandContainer_slideshow">
                <div class="belt">
    <?php
    if (count($salvation_prayer['photo_arr'])) {
        foreach ($salvation_prayer['photo_arr'] as $sal_key => $val) {

            $salvation_img = base_url() . 'uploads/salvation_prayer_photos/' . getThumbName($val['s_photo_name'], 'main');
            ?>
                            <div class="thumbnails">
                                <div style=" background:URL('<?= $salvation_img ?>') no-repeat center;border:1px solid #62c3bc; width: 385px; padding-top:130px;	height:173px; ">
                                    <h4><strong>who we are ?</strong> </h4>
                                    <!--<p class="blue_bold12">Image Will Come Here</p>-->
                                </div>
                            </div>
        <?php
        }
    }
    ?>

                </div>
            </div>
            <img src="images/arr_r.png" alt=""  class="scroller_arrow01" onclick="javascript:stepcarousel.stepBy('bandContainer1', 1)" style="float:right;" />
            <div class="clr"></div>
            <div class="">
                <input name="" type="button" value="Next" class="popup-yes"  onclick="show_another_dialog('mean_to_be_member')"  />
            </div>
            <br class="clear"/>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>


    <div class="lightbox mean_to_be_member">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div> <h4>What does it mean to be a member? </h4></div>
            <div class="">
                <h5> What does it mean to be a member, what could my function?</h5>
                <div class="light_blue_bold12"> <?= htmlspecialchars_decode($salvation_prayer['result']['s_mean_of_member']) ?></div>
                <br />
                <input name="" type="button" value="Next" class="popup-yes"   onclick="show_another_dialog('become_member_of_body')"  />
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>

    <div class="lightbox become_member_of_body">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div><h4>How do I become a member of the body ?</h4></div>
            <div class="">
                <h5>How do I become a member of the body ?</h5>
                <div class="light_blue_bold12"> <?= htmlspecialchars_decode($salvation_prayer['result']['s_to_become_member']) ?> </div>
                <br />
                <input name="" type="button" value="Next" class="popup-yes"   onclick="show_another_dialog('salvation_prayer')"  />
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>

    <div class="lightbox salvation_prayer ">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div>                
                    <h4>Salvation Prayer </h4>
            </div>
            <div class="">
                <h5>Forgive me Father...Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius
                    tempor Lorem ipsum dolor sit amet, consectetur adipisicing elit... </h5>
                <div class="light_blue_bold12"> <?=htmlspecialchars_decode( $salvation_prayer['result']['s_salvation_prayer']) ?></div> 

                <br />
                <input name="" type="button" value="Yes" class="popup-yes"   onclick="show_another_dialog('congratulation')"   /> 
                <input name="" type="button" value="No" class="popup-no"   onclick="show_another_dialog('remind_me')"   /> 
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>

    <div class="lightbox congratulation">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div><h4>Congratulation </h4></div>
            <div class="">
                <h5>Congratulations</h5> <p class="blue_bold12">You are now a born again Christian.</p>
                <p class="light_blue_bold12">Welcome to the Family of God.</p> 

                <br />
               <div align="center"> <input name="" type="button" value="What Next " class="popup-yes"   onclick="show_another_dialog('what_next')"   /> 
                <input name="" type="button" value="Finish" class="popup-no"   onclick="hide_dialog()"   /></div> 
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>


    <div class="lightbox what_next">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div>             
                    <h4>What Next (Help Me Grow) </h4>
            </div>
            <div class="">
                       <?php 
                    //echo $about = preg_replace('#<p>(.*?)</p>#', ' ', nl2br($salvation_prayer['result']['s_what_next']));
                       ?>
                <h5> Here provide counselling information.</h5> 
                <p id="whatnext"><?= nl2br($salvation_prayer['result']['s_what_next']) ?></p>
                <script type="text/javascript">
                    jQuery(document).ready(function(){
                       jQuery('#whatnext > p > *').unwrap();
                    });
                </script>

                <br />
                <input name="" type="button" value="Close" class="popup-yes"   onclick="hide_dialog()"   /> 
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>

    <div class="lightbox remind_me">
        <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
        <div class="top">
            <div>&nbsp;</div>
        </div>
        <div class="mid">
            <div>
                <h4>Remind Me </h4>
            </div>
            <div class="welcome_div">

                <input name="" type="button" value="Remind Me Later" class="popup-yes"   onclick="hide_dialog()"   /> 
                <input name="" type="button" value="No Thanks" class="popup-no"   onclick="hide_dialog()"   /> 
                <br class="clear"/>
            </div>
        </div>
        <div class="bot">
            <div>&nbsp;</div>
        </div>
    </div>

<div class="lightbox frnd-pop">
      <div class="close"><a onclick="hide_dialog()" href="javascript:void(0)"><img alt="" src="http://cogtime.com/images/close.png"></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            
           <p style="font-size:18px; color:#ff0000; padding:20px;">You must have a friend list to create a chat room.</p>
           
           
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>








<div class="lightbox ring-pop">
      <div class="close"><a onclick="hide_dialog()" href="javascript:void(0)"><img alt="" src="http://cogtime.com/images/close.png"></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            
           <p style="font-size:18px; color:#ff0000; padding:20px;">You must have a friend list to create a ring.</p>
           
           
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<?php } ?>
<!--<script type="text/javascript">
$.noConflict();


</script>-->

<?php /* ?>Salvation prayer popups<?php */ ?>









