<script type="text/javascript">
<!--
$(document).ready(function() {
//auto fill start
var isemailcookie = "<?php  echo $_COOKIE['CG_FO']['email'];?>";
var ispwdcookie = "<?php  echo $_COOKIE['CG_FO']['password'];?>";

if(isemailcookie == "" || ispwdcookie == ""){
	   $('#email').autofill({'value':'Email'});
	   $('#password').autofill({'value':'Password'});
	}
	//auto fill end	;
});
function after_submit() {
	if(window.location.hash!='') {
		$('#frm_login').append('<input type="hidden" name="hash" value="'+window.location.hash + '" />');
	}
}

//-->
</script>

<!-- HEADER SECTION -->
<div id="header_section_home">
    <div id="header_home">
    	<div id="logo"><a href="<?=base_url().'index.html'?>"><img src="<?=base_url()?>images/logo.png" width="230px" height="57px" alt="COGTIME Xtian network" title="Cogtime" /></a></div>

                  <div id="login_box">
                  
                  
					   <?php 
                          
                           if(!@$session_data['loggedin'])
                           {
                           // pr($_COOKIE['CG_FO']);
                            
                           $RemberEmail ='';
                           $RemberPwd ='';
                           $Rember = '';
                                if(isset($_COOKIE['CG_FO']['email']) && isset($_COOKIE['CG_FO']['password'])) 
                                    {
                                        $RemberEmail  = $_COOKIE['CG_FO']['email']; 
                                        $RemberPwd 	  = $_COOKIE['CG_FO']['password']; 
                                        $Rember 	  = $_COOKIE['CG_FO']['remember']; 
                                        
                                    }
                           }
                      
                      ?>
                  
                  
                  
                  
                  
                  
                          <form onsubmit="return userLogin(this.email_login.value, this.password_login.value);" method="post" name="frmLogin" id="frmLogin">
                          
                          <input name="login_referrer" id="login_referrer" type="hidden" value="<?=@$session_data['login_referrer']?>"/>
                          <input name="current_referrer" id="current_referrer" type="hidden" value=""/>
                          <input type="hidden" name="is_submitted" id="is_submitted" value="Y"  /> 
                         
                          <input style=" " name="email_login" type="text" id="email" value="<?=($RemberEmail=='')?$posted['email']:$RemberEmail;?>"  autocomplete ="off"/>
                          
                          
                          <input name="password_login" type="password" id="password" value="<?=($RemberPwd=='')?$posted['password']:$RemberPwd;?>"  autocomplete ="off"/>
                          <div id="error_msg_password_login" class="error_msg"></div>
                          
                          <input name="" type="submit" value="Login" />
                          <div id="error_msg_email_login" class="error_msg" style="margin-left:20px;"></div> 
                          <div class="clr"></div>
                           <label class="remember-pass"><input name="chkRem" id="chkRem" type="checkbox" value="1" <?=($Rember=='checked'?'checked="checked"':'')?>/>Remember me.</label>  Not a registered user? <a href="<?=base_url().'register.html'?>" class="signup">Sign Up here</a>
                          <a href="<?=base_url()?>forgot-password.html">Forgot Password?</a>
                          </form>
                      </div>
    </div>
</div>
<!-- /HEADER SECTION -->



<?php /*?> ############ Login Status Check [Start] ########### <?php */?>
<input type="hidden" id="logged_status" value="<?= @$logged_in_state ?>" />
<?php /*?> ############ Login Status Check [End] ########### <?php */?>




<!--ip block pop up-->
<?php
//echo 'nabin';
 $blockStatus = $_REQUEST['blockStatus'];
 if($blockStatus == 1){
     
 
?>
<link type="text/css" rel='stylesheet' href="<?= base_url() ?>css/myPopup.css">
<script type="text/javascript" src="<?= base_url() ?>js/myPopup.js"></script>
<div class="overlay-bg">
</div>
<div class="overlay-content popup1">
    <p>Your IP is blocked by Admin . Please contact admin</p>
    <img src="<?= base_url() ?>images/close.png" alt="close" height="24" width="24" class="close-btn">
</div>
<script type="text/javascript">
$(document).ready(function(){
   // alert('blocked')
   
   $('.close-btn, .overlay-bg').click(function(){
		//alert('dd')
        $('.overlay-bg, .overlay-content').hide(); // hide the overlay
    });
  // $('#s--modalbox-overlay').css('display','block');
});


</script>

 <?php } 
 
 $member_status = $_REQUEST['mSt'];
 if($member_status == 1){
 ?>
<script type="text/javascript">

$(document).ready(function(){
    ShowUIMSg('You are already used this link');
});

</script>
 <?php } ?>