<script type="text/javascript">
var globaVariableForGetunreadmsg = 1;
</script>
<div id="left_container">
		 
		  <?php include(APPPATH ."views/layouts/blocks/left_user_profile_block.phtml");?>
          <div class="menu-box">
      <div class="nw-heading gap10">
             
             <div class="topminus exp-col027" style="display:none; cursor:pointer; text-align:right;"><strong>Collapse</strong></div>
             <div class="topplus exp-col027" style="cursor:pointer; text-align:right;"><strong>Expand All</strong></div>
      </div>
      
      </div>
      <div class="nw-contenttop" id="switchdiv027">
          <?php include(APPPATH ."views/layouts/blocks/left_personal_block.phtml");?> 
          <?php include(APPPATH ."views/layouts/blocks/left_user_connection.phtml");?> 
          <?php include(APPPATH ."views/layouts/blocks/left_media_lib.phtml");?> 
          <?php include(APPPATH ."views/layouts/blocks/left_social_activity.phtml");?> 
          </div>

 </div>