<!--[if lte IE 7]>
<style type="text/css">
html .jquerycssmenu{height: 1%;} /*Holly Hack for IE7 and below*/
</style>
<![endif]-->
<!--[if IE 7]>
	<body class="ie7">
<![endif]-->
<!--[if IE 8]>
	<body class="ie8">
<![endif]-->
<!--[if IE 9]>
	<body class="ie9">
<![endif]-->
<!--[if lt IE 9]><script  type="text/javascript" src="js/html5.js"></script><![endif]-->

<script language="javascript">
<!--

function after_submit() {
	if(window.location.hash!='') {
		//alert(window.location.hash);
		$('#frm_login').append('<input type="hidden" name="hash" value="'+window.location.hash + '" />');
	}
}

//-->
</script>
<!-- HEADER SECTION -->
<div id="header_section">
    <div id="header">
    	<div id="logo"><a href="<?=base_url().'index'?>"><img src="<?=base_url()?>images/logo.png" alt="COGTIME Xtian network" title="Cogtime" /></a></div>
            <?php if( ($this->session->userdata('loggedin')!='' || $this->session->userdata('loggedin')!=false) && $this->session->userdata('is_admin') != 1)
          {?>
          	 <div id="header_right"> Welcome <a href="<?=base_url();?>my-wall.html"><?=$this->session->userdata('username').' '.$this->session->userdata('user_lastname')?></a> | <a href="<?=base_url().'logout'?>">Logout</a><br />
                  <ul>
                        <li><a href="javascript:void(0);"  onclick="window.open('speak-to-net-coach.php',   'windowname2',   'resizable=0, location=1, width=385, height=500');    return false;">Speak to a Net Coach</a></li>
                        <li>|</li>
                        <li><a href="">Help</a></li>
                  </ul>
            </div>
             <br class="clr" />
            
       <?php }?>
            

<?php /*?> ############ Login Status Check [Start] ########### <?php */?>
<input type="hidden" id="logged_status" value="<?= @$logged_in_state ?>" />
<?php /*?> ############ Login Status Check [End] ########### <?php */?>