<script language="javascript">
<!--
function after_submit() {
	if(window.location.hash!='') {
		//alert(window.location.hash);
		$('#frm_login').append('<input type="hidden" name="hash" value="'+window.location.hash + '" />');
	}
}

//-->
</script>
<!-- HEADER SECTION -->
<div id="header_section">
    <div id="header">
    	<div id="logo"><a href="<?=base_url().'index'?>"><img src="<?=base_url()?>images/logo.png" width="230" height="57" alt="COGTIME Xtian network" title="Cogtime" /></a></div>
            <?php if( ($this->session->userdata('loggedin')!='' || $this->session->userdata('loggedin')!=false) && $this->session->userdata('is_admin') != 1)
          {?>
          	 <div id="header_right"> Welcome <a href="<?=base_url();?>my-wall.html"><?=$this->session->userdata('username').' '.$this->session->userdata('user_lastname')?></a> | 
                <span id="user_local_time">
                 Time: 
                 <? 
                    $UserLocalTime = explode(' ',getUserLocalTime($arr_profile_info['s_time']));
                    echo $UserLocalTime[3];
                 ?>
                </span> | <a href="<?=base_url().'logout'?>">Logout</a><br />
                  <ul>
                      <li><a href="javascript:void(0);"  id="online-chat">Speak to a Net Coach</a></li>
                        <li>|</li>
                        <li><a href="<?= base_url() ?>help_center">Help</a></li>
                  </ul>
                     <script>
            $(document).ready(function(){
                $('#online-chat').click(function(){
                    var address = "<?= base_url() ?>livehelperchatmaster/livehelperchat-master/lhc_web?name=<?=$this->session->userdata('username').' '.$this->session->userdata('user_lastname') ?>";
                    var con = "width=500,height=500";
                    window.open (address,'livehelperchatmaster', config = con);
                });
            });
        </script>
            </div>
             <br class="clr" />
             <!----------arif-------------->
             <div class="lightbox session-popup">
      
      
      <div class="mid">
          <div><a href="<?=base_url().'index'?>"><img src="<?=base_url()?>images/logo.png" alt="COGTIME Xtian network" title="Cogtime" width="230" height="57" /></a></div>
      <h4>Your session has expired. Please login again </h4>
      <input type="submit" value="Login" name="" id="lgout"> 
    </div>          
            </div>
<!--  <script>
                        var idleTime = 0; //here we define idle time
                        $(document).ready(function() {
                            /* here we can call function timercount() own desire time */
                            var idleInterval = setInterval("timercount()", 60000);
                            // define time 1 second = 1000, for 1 min 60x1000=60000
                            /* this function check the mouse event if mouse move or 
                             click then it set idleTime the value 0 */
                            $(this).mousemove(function(e) {
                                idleTime = 0;
                            });
                            /* this function check the keyboard event
                             if any key press by key board then it set idleTime the value 0 */
                            $(this).keypress(function(e) {
                                idleTime = 0;
                            });
                        })
                        function timercount() {
                            idleTime = idleTime + 1;
                            if (idleTime > 40) {
                                
                              
                               // var type = 'logout'; 
                                $.ajax({
            url : base_url+'base_controller/session_des',
            type : 'post',
            dataType : 'json',
            data : ({type:'logout'}),
            success : function (data)
            {
                 hideUILoader('session-popup')
// hideUILoader('comments-popup');
                //$('#del_commitmen'+id).hide();
                // window.location.href = '<?= base_url() ?>admin/site-settings/All_comments';
                
            }
        });
                                $('#lgout').click(function(){
                                    window.location="<?= base_url() ?>";
                                });
                                                                       
   
                            }
                        }
                    </script>-->
                    <!----------arif-------------->
            
       <?php }?>
            

<?php /*?> ############ Login Status Check [Start] ########### <?php */?>
<input type="hidden" id="logged_status" value="<?= @$logged_in_state ?>" />

<?php /*?> ############ Login Status Check [End] ########### <?php */?>


<!--<script type="text/javascript" src="--><?//= base_url() ?><!--js/jquery.cookie.js"></script>-->





<!--------------------------ip blocker login added on 18-12-2014------------------------------------------------------>
<?php
/************************check ip status & change the ip status**********************/
$ip = getenv("REMOTE_ADDR") ;
 $logged_user_id = intval(decrypt($this->session->userdata('user_id')));
 
  $query = $this->db->get('cg_user_ip');

foreach ($query->result() as $row)
{
    $block_ip = $row->u_ip;
    $block_status = $row->is_status;
    $block_id =  $row->u_id;
    if($ip == $block_ip && $block_status == 1 && $logged_user_id == $block_id){
        $data = array(
               'is_status' => 1,
               
            );

$this->db->update('cg_user_ip', $data, array('u_id' => $logged_user_id,'u_ip' =>$block_ip));
    }
}
/****************************************************/

/****************************check ip status & call ip blocker controller for logout************************************/
$query = $this->db->get_where('cg_user_ip', array('u_id' => $logged_user_id ));
foreach ($query->result() as $row)
    {
       $iplist = $row->u_ip;
            if($iplist == $ip){
       $query1 = $this->db->get_where('cg_user_ip', array('u_ip' => $iplist,'u_id' => $logged_user_id  ));
                 
            foreach ($query1->result() as $row){
                $status = $row->is_status;
                if($status == 1){
                    //die('ok');
                    ?>

                        <?php
                    header('Location:'.base_url().'base_controller/ip_block');
                    
                }
            }  
            
            
            }
       
    }

/**********************************************************************/

?>
<!--------------------------------------------------------------->