<!--navigation for public start -->
<div class="nav-public">
	<ul class="nav-container">
    	<li <?php echo($nav_slider_num == 1)?' class = "select"':'';?>><a href="index.html"><img src="images/cogtime-bullet.png" alt="bullet" width="59" height="59"><span>Cogtime</span></a></li>
        <li <?php echo($nav_slider_num == 2)?'class = "select"':'';?>><a href="social-hub-public.html"><img src="images/social-hub-bullet.png" alt="bullet" width="59" height="59"><span>Social Hub</span></a></li>
        <li <?php echo($nav_slider_num == 3)?'class = "select"':'';?>><a href="trade-center-public.html"><img src="images/trade-center-bullet.png" alt="bullet" width="59" height="59"><span>Trade Center</span></a></li>
        <li <?php echo($nav_slider_num == 4)?'class = "select"':'';?>><a href="media-center-public.html"><img src="images/media-center-bullet.png" alt="bullet" width="59" height="59"><span>Media Center</span></a></li>
        <li <?php echo($nav_slider_num == 5)?'class = "select"':'';?>><a href="build-the-kingdom-public.html"><img src="images/kingdom-bullet.png" alt="bullet" width="59" height="59"><span>Build The Kingdom</span></a></li>
        <li <?php echo($nav_slider_num == 1)?'class = "select last"':'class= "last"';?>><a href="holy-place-public.html"><img src="images/holy-place-bullet.png" alt="bullet" width="59" height="59"><span>Holy Place</span></a></li>
    </ul>
</div>
<!--navigation for public end -->