<div class="search-panel">
            <p class="title">Profile Summary</p>
            <div class="tweeter-search">
            <span>Search People:</span>
            <form name="search_twit" id="search_twit" action="" method="post" enctype="multipart/form-data" class="tweeter-search-form" onsubmit="return false;">
                <input name="searchTweeter" type="text" id="searchTweeter">
                <input type="hidden" id="search_basic" name="search_basic" value="Y" /> 
                <input name="" type="submit" value="" id="search_profile">
            </form>
           </div>
</div>


<script type="text/javascript">

$(document).ready(function(arg) {
$('#search_twit').submit(function(){ 
			
		  var datatosend=$("#search_twit").serialize();
		   showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
			  $.ajax({
					 type: "POST",
					 url: base_url+'logged/tweet_home/search_people_ajax_pagination',
					 data: datatosend,
					 //dataType : 'json',
					 success: function(data){
						 hideUILoader_nodialog();
						//window.location.href= base_url+"search-people.html";	 
					}
			   });	 
	
		});
 


});


</script>