<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <?php /*?><div id="top_corner">&nbsp;</div><?php */?>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        	<!--my tweeter profile start -->    
                            <div class="tweeter-profile">
                             	<?php include(APPPATH ."views/logged/my_tweet/search_panel.phtml");?>
                                
                                <!--tweeter header start -->  
                                <!--tweeter header start -->  
                                <?php
                                  $user_id = intval(decrypt($this->session->userdata('user_id')));
                                  $bg_img_name = $_SESSION['s_tweet_bg_img'];
                                  $bg_img_arr = explode('.', $bg_img_name);
                                  $bg_img_name = $bg_img_arr[0];
                                  $ext = $bg_img_arr[1];
                                  //print_r($bg_img_name);
                                  $img_url = base_url() . 'uploads/user_photos/' . $bg_img_name . '-big.' . $ext;
                                  if (empty($bg_img_name)) {
                                  ?>
                                  <!--tweeter header start -->  
                                  <div style="background:url(images/tweeter-profile-bg.jpg) no-repeat 0 0;" class="tweeter-profile-header">

                                  <div class="clr"></div>
                                  <div class="edit_twtr_pic" style="display: none"><a href="javascript:void(0);" onclick="show_dialog('edit-bg-image');"><h3>Edit Background Image</h3></a></div>
                                  <?php include(APPPATH . "views/logged/my_tweet/tweet_user_detail.phtml"); ?>
                                  </div> 
                                  <?php } else { ?>
                                  <div style="background:url(<?php echo $img_url; ?>) no-repeat 0 0;" class="tweeter-profile-header">

                                  <div class="clr"></div>
                                  <div class="edit_twtr_pic" style="display: none"><a href="javascript:void(0);" onclick="show_dialog('edit-bg-image');"><h3>Edit Background Image</h3></a></div>
                                  <?php include(APPPATH . "views/logged/my_tweet/tweet_user_detail.phtml"); ?>
                                  </div> 
                                <?php 
                                } 
                                ?>
                                <!--tweeter header end --> 
                                <!--tweeter header end --> 
                                <!--tweeter page nav start --> 
                                 <?php include(APPPATH ."views/logged/my_tweet/my_twitter_menu.phtml");?>
                                <!--tweeter page nav end -->  
                                <!--write tweet section start -->
                                <?php /*?><div class="write-tweet">
                                	<form action="" method="post" enctype="multipart/form-data">
                                    	<span class="tweet-top-curve"></span>
                                        <div class="tweet-mid-curve"><textarea  class="tweet-comment-box" id="ta_post_tweet" 
                                        name="ta_post_tweet" onfocus="if(this.value=='Max 140 Characters')this.value='';" 
                                            onblur="if(this.value=='')this.value='Max 140 Characters';"  >Max 140 Characters</textarea></div>
                                            
                                         <input type="hidden" id="hidden_inputbox" />
                                        <span class="tweet-bot-curve"></span>
                                        <input name="Cancel" type="button" value="Cancel" class="tweetCancel">
                                        <input name="" type="button" value="Tweet" class="tweetSubmit" onclick="post_tweet_text('all_tweet')">
                                    </form>
                     
      
                                    <div class="clr"></div>
                                </div><?php */?>
                                <!--write tweet section end -->
                            	<div id="new_tweet_contents"><?=$tweets_ajax_content?></div>  
                             </div>
                            <!--my tweeter profile end -->  
                              <?php if($no_of_result  == 0):?>
                                <div class="shade_box_01" style="padding-top:5px;" id="no_tweets"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Followers.</p></div></div>
                            <?php endif;?>	
                           
                            
                            <?php if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="<?=$current_page_1?>" onclick="show_more_tweets($(this).attr('page_value'))">[view more] </a> </div>
                            <?php endif; ?>
                            <input type="hidden" id="i_user_id" value="<?=$profile_id?>" />
                        </div>
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
      <?php include(APPPATH . "views/logged/my_tweet/edit_background.phtml"); ?>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<!-- /FOOTER SECTION -->


<!-- /lightbox SECTION -->
<script type="text/javascript">
			
$(document).ready(function(){
		$("#searchTweeter").autofill({'value':"Type Keyword"}); 

    $(".tweeter-profile-header").hover(
            function() {
                $(".edit_twtr_pic").show();
            },
            function() {
                $(".edit_twtr_pic").hide();
            }
    );
	});

</script>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_tweets(page) {
	
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/tweet_home/my_followers_ajax_pagination/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				$('#new_tweet_contents').append(data.html);
				$('#show_more_tweets_link').attr('page_value', data.cur_page);
				$('#show_more_tweets_link').attr('onclick','');
				$('#show_more_tweets_link').attr('onclick','show_more_tweets('+data.cur_page+')');
				
			}
			else {
				$('#new_tweet_contents').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Followers.</p></div>');
				$('#show_more_div').remove();
			}
			//alert(data.view_more);
            
            if(data.view_more==false)
            {
                
                $('#new_tweet_contents').append('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Followers.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}

</script>

