<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <?php /*?><div id="top_corner">&nbsp;</div><?php */?>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        	<!--my tweeter profile start -->    
                            <div class="tweeter-profile">
                             	<?php include(APPPATH ."views/logged/my_tweet/search_panel.phtml");?>
                                <!--tweeter header start -->  
                                <?php
                                $user_id = intval(decrypt($this->session->userdata('user_id')));
                                $bg_img_name = $_SESSION['s_tweet_bg_img'];
                                $bg_img_arr = explode('.', $bg_img_name);
                                $bg_img_name = $bg_img_arr[0];
                                $ext = $bg_img_arr[1];
                                //print_r($bg_img_name);
                                $img_url = base_url() . 'uploads/user_photos/' . $bg_img_name . '-big.' . $ext;
                                if (empty($bg_img_name)) {
                                    ?>
                                    <!--tweeter header start -->  
                                    <div style="background:url(images/tweeter-profile-bg.jpg) no-repeat 0 0;" class="tweeter-profile-header">
                                        
                                        <div class="clr"></div>
                                        <div class="edit_twtr_pic" style="display: none"><a href="javascript:void(0);" onclick="show_dialog('edit-bg-image');"><h3>Edit Background Image</h3></a></div>
                                        <?php include(APPPATH . "views/logged/my_tweet/tweet_user_detail.phtml"); ?>
                                    </div> 
                                <?php } else { ?>
                                    <div style="background:url(<?php echo $img_url; ?>) no-repeat 0 0;" class="tweeter-profile-header">
                                        
                                        <div class="clr"></div>
                                        <div class="edit_twtr_pic" style="display: none"><a href="javascript:void(0);" onclick="show_dialog('edit-bg-image');"><h3>Edit Background Image</h3></a></div>
                                        <?php include(APPPATH . "views/logged/my_tweet/tweet_user_detail.phtml"); ?>
                                    </div> 
                                <?php } ?>
                                <!--tweeter header end --> 
                                <!--<div style="background:url(images/tweeter-profile-bg.jpg) no-repeat 0 0;" class="tweeter-profile-header">
                                	test
                                    <div class="clr"></div>
                                   
                                </div> -->
                                <!--tweeter header end --> 
                                <!--tweeter page nav start --> 
                                 <?php include(APPPATH ."views/logged/my_tweet/my_twitter_menu.phtml");?>
                                <!--tweeter page nav end -->  
                                <!--write tweet section start -->
                                <div class="write-tweet">
                                	<form action="" method="post" enctype="multipart/form-data">
                                    	<span class="tweet-top-curve"></span>
                                        <div class="tweet-mid-curve"><textarea  class="tweet-comment-box" id="ta_post_tweet" 
                                        name="ta_post_tweet" onfocus="if(this.value=='Max 140 Characters')this.value='';" 
                                            onblur="if(this.value=='')this.value='Max 140 Characters';"  >Max 140 Characters</textarea></div>
											<input type="hidden" id="hidden_inputbox" />
                                        <span class="tweet-bot-curve"></span>
                                            <div class="tab_details comment-content nw-comment-content">
            
            <input type="hidden" id="public_wall_owner_id" name="public_wall_owner_id" value="<?=($this->session->userdata('user_id'))?>" />
            
            
            <!--  text div start -->
                <!--  <div class="write-text">
                <textarea name="wall_msg" id="wall_msg" cols="" rows="" onfocus="if(this.value=='Max 500 Characters')this.value='';" onblur="if(this.value=='')this.value='Max 500 Characters';" maxlength ="500" 
                onKeyDown="limitTextarea(this.form.wall_msg,this.form.countdown,500);" 
onKeyUp="limitTextarea(this.form.wall_msg,this.form.countdown,500);" onkeypress="return restrict_carrige(event);"  >Max 500 Characters</textarea>
 <p style=" clear:both; float:left"> <span id="text_count">0</span> Characters</p>
                </div>-->
               <!-- text div end  -->
                
               <!-- upload image div start  -->
                <div class="upload-image" >
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Upload Image :</label>
                    <input name="btn_upload" id="btn_upload" type="file" size="40" />
                    <br class="clr"/>
                    <div id="all_photos">
                  
                    </div>
            
                  <div id="hdnflds" >
                  </div>
                 
                 </div>   
                      
                <!--upload image div end -->
                
                
                
               <!-- upload video div start -->
                <div class="upload-video">
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Video Url :</label><div class="video-url"><input name="txt_video_url" id="txt_video_url" type="text" /></div>
					<ul class="video-logo" >
					<li><img src="<?=base_url()?>/images/YouTube.png"title="YouTube" alt="YouTube"></li>
					<li><img src="<?=base_url()?>/images/Vimeo.png"title="Vimeo" alt="Vimeo"></li>
					<li><img src="<?=base_url()?>/images/DailyMotion.png"title="DailyMotion" alt="DailyMotion"></li>
					<li><img src="<?=base_url()?>/images/Viadeo.png"title="Viadeo" alt="Viadeo"></li>
					</ul>
                    <br class="clr"/>
                    <div id="all_videos">
                      <?php /*?><div class="view-thumb"><img src="images/photo-img01.jpg" alt="photo" width="60" height="60" /><a href="javascript:void(0);" class="remove" title="Remove Video"></a></div>
                     <?php */?>
                    </div>
                    
                     <div id="hdnvideoflds" >
                     </div>
                  
                </div>
               <!-- upload video div end -->
               
               
            </div>

								 <div class="tab_content button-set type-text" style="display:none">
								<ul>
                  <!--  <li class="select"><a href="javascript:void(0);"><img src="images/nw-text-btn.png" alt="text" title="Write Text"  /></a></li>-->
								<li><a href="javascript:void(0);"><img src="images/nw-photo-btn.png" alt="photo" title="Upload Photo" /></a></li>
								<li><a href="javascript:void(0);"><img src="images/nw-video-btn.png" alt="video" title="Upload Video" /></a></li>
								</ul>
								</div>
                                         
                                        <input name="Cancel" type="button" value="Cancel" class="tweetCancel" />
                                        <input name="" type="button" value="Chitter" class="tweetSubmit" onclick="post_tweet_text('my_tweets')" />
                                    </form>
                     
      
                                    <div class="clr"></div>
                                </div>
                                <!--write tweet section end -->
                            	<div id="tweet_contents"><?=$tweets_ajax_content?></div>  
                             </div>
                            <!--my tweeter profile end -->  
                              <?php if($no_of_result  == 0):?>
                                <div class="shade_box_01" style="padding-top:5px;" id="no_tweets"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Chitters.</p></div></div>
                            <?php endif;?>	
                           
                            
                            <?php if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="<?=$current_page_1?>" onclick="show_more_tweets($(this).attr('page_value'))">[view more] </a> </div>
                            <?php endif; ?>
                            <input type="hidden" id="i_user_id" value="<?=$profile_id?>" />
                        </div>
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
      <form id="frmUploadTweetPhoto"  method="post" action="<?= base_url() . 'logged/my_photos/edit_twt_bg_img' ?>" onsubmit="return false;" enctype="multipart/form-data">
          <div class="lightbox edit-bg-image" style="width:480px;">
              <div class="close"><a href="javascript:void(0)" onclick="
                      hide_dialog()"><img src="<?php echo base_url() ?>images/close.png" alt="" width="24" height="24"/></a></div>
              <div class="top"><div>&nbsp;</div></div>
              <div class="mid">
                  <div class="heading"><div class="left"><h4><img src="<?php echo base_url() ?>images/icons/photo.png" alt="" /> Upload  Photo </h4></div></div>
                  <div class="frm_box">
                      <div class="lable01">Browse Photo:</div> 
                      <div class="field01">                       
                          <input type="file" name="s_photo" id="s_photo" />
                          <span id="err_photo" class="error-message"></span>  
                      </div>
                      <div class="clr"></div>
                      <center><input name="add_mphoto_btn" id="add_mphoto_btn" type="submit" value="Upload" class="btn" /></center>
                  </div>

              </div>
              <div class="bot"><div>&nbsp;</div></div>
          </div>
      </form>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<!-- /FOOTER SECTION -->
<!--popup one start-->
<div class="lightbox delete-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Chitter</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete this Chitter?</p>
               </div>
               <form action="" method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<!-- /lightbox SECTION -->
<script type="text/javascript">
			
$(document).ready(function(){
	
	
		$("#searchTweeter").autofill({'value':"Type Keyword"}); 
		//$("#ta_post_tweet").autofill({'value':"Compose New Tweet"});
		
		$('.tweet-comment-box').focus(function(){
			$(this).animate({height:'50px'},500);
			$('.tab_content').css('display','block');
			$('.tweetSubmit, .tweetCancel').fadeIn('fast',function(){
					$('.tweetCancel').click(function(){
					$('.tab_content').css('display','none');
					$('.upload-image').hide();
					$('.upload-video').hide();
						$(this).parent('form').find('.tweet-comment-box').animate({height:'18px'},500);
						$('.tweetSubmit, .tweetCancel').stop(true,true).slideUp();
					});
					
					// added to slide p after tweeting
					$('.tweetSubmit').click(function(){
					$('.tab_content').css('display','none');
					$('.upload-image').hide();
					$('.upload-video').hide();
						$(this).parent('form').find('.tweet-comment-box').animate({height:'18px'},500);
						$('.tweetSubmit, .tweetCancel').stop(true,true).slideUp();
					});
			});
		});
		
	});

</script>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_tweets(page) {
	
	var i_user_id = $('#i_user_id').val();
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/tweet_home/my_tweets_ajax_pagination/'+i_user_id+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				$('#tweet_contents').append(data.html);
				$('#show_more_tweets_link').attr('page_value', data.cur_page);
				$('#show_more_tweets_link').attr('onclick','');
				$('#show_more_tweets_link').attr('onclick','show_more_tweets('+data.cur_page+')');
				//show_video();
			}
			else {
				$('#tweet_contents').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Chitters.</p></div>');
				$('#show_more_div').remove();
			}
			//alert(data.view_more);
            
            if(data.view_more==false)
            {
               
                $('#tweet_contents').append('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Chitters.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}

$(document).ready(function(arg) {
	$(".tweeter-profile-header").hover(
          function() {
              $(".edit_twtr_pic").show();
          },
          function() {
              $(".edit_twtr_pic").hide();
          }
  );

 $('#frm_search').submit(function(){ 
			
		  var i_user_id = $('#i_user_id').val();			
		  var datatosend=$("#frm_search").serialize();
		   showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
			  $.ajax({
					 type: "POST",
					 url: base_url+'logged/tweets/my_tweets_ajax_pagination/'+i_user_id,
					 data: datatosend,
					 dataType : 'json',
					 success: function(data){
						$('#frm_search')[0].reset();
						
						if(data.html!='') {
							//alert( data.cur_page+' posting');
							$('#show_more_div').remove();
							$('#tweet_contents').html(data.html);
							$('#show_more_tweets_link').attr('page_value', data.cur_page);
							$('#show_more_tweets_link').attr('onclick','');
							$('#show_more_tweets_link').attr('onclick','show_more_tweets('+data.cur_page+')');
						}
						else {
							$('#tweet_contents').html('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No Chitters.</p></div>');
							$('#show_more_div').remove();
						}
						
						
						//alert(data.no_of_result- data.current_page);
						if(data.no_of_result == 0){
							$('#show_more_div').remove();
						}
						else if(data.view_more==false )
						{
							//alert(1);
							$('#tweet_contents').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Chitters.</p></div>');
							$('#show_more_div').remove();
						}
						else if((data.no_of_result - data.cur_page != 0)){
							//alert(2);
							
							$('#show_more_div').remove();
							$('#mid_container').append('<div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="'+data.cur_page+'" onclick="show_more_tweets('+data.cur_page+')">[view more] </a> </div>');
						}
						
						hideUILoader_nodialog();
					 }
			   });	 
	
		});
 


});


</script>
<script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#ta_post_tweet').keyup(function(){
            limitChars('ta_post_tweet', 140, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('ta_post_tweet',140, '');
    
 
});
</script>

<script type="text/javascript">
$('#ta_post_tweet').triggeredAutocomplete({
	hidden: '#hidden_inputbox',
	source: "<?php echo base_url()?>logged/tweet_home/show_connections/",
	trigger: "@" ,
	open:function() { $('.ui-menu').width(150) }  
	
});

	
</script>

