<!--connections start -->
<div class="menu-box">
      <div class="nw-heading">
             <div class="left">
                  <h4><img src="images/icons/connections.png" alt="Connections" />Connections</h4>
            </div>
             <div class="right exp-col03"><img src="images/icons/nw-minus.png" alt="" class="plus-minus2" /></div>
             <div class="right exp-col03" style="display:none;"><img src="images/icons/nw-plus.png" alt="" class="plus-minus2" width="13px" height="10px"/></div>
      </div>
      
      <div class="nw-content" id="switchdiv03">
          <ul> 
                <li><a href="my-profile.html" class="<?php echo ($page_name=='my-profile')?'select':'';?>">My Profile</a></li>
                <li><a href="my-wall.html" class="<?php echo ($page_name=='my-wall')?'select':'';?>">My Wall</a></li>
                 <li><a href="wall-privacy-settings.html" class="<?php echo ($page_name=='wall-privacy-settings')?'select':'';?>">My Wall Privacy Settings</a></li>
                <li><a href="my-friends.html" class="<?php echo ($page_name=='my-friends' || $page_name == 'search-invite-friends' || $page_name=='friend-request')?'select':'';?>">My Friends <span id="frnd_notification"><?php if($arr_profile_info['friend_count']) {?><span class="notification"><?=$arr_profile_info['friend_count']?></span><?php } ?></span></a></li>
                
                <li><a href="my-net-pals.html" class="<?php echo ($page_name=='my-net-pals' || $page_name=='net-pal-request' || $page_name=='search-invite-net-pals' )?'select':'';?>">My NetPals <span id="netpal_notification"><?php if($arr_profile_info['netpal_count']) {?><span class="notification"><?=$arr_profile_info['netpal_count']?></span><?php } ?></span></a></li>
               
                <li >
                <a href="my-prayer-partners.html" class="<?php echo ($page_name=='my-prayer-partners' ||$page_name=='prayer-partner-request' || $page_name=='search-invite-prayer-partner'|| $page_name=='prayer-partner-request' || $page_name=='search-invite-prayer-partner')?'select':'';?>">My Prayer Partners <span  id="prayer_notification" ><?php if($arr_profile_info['prayer_count']) {?><span  class="notification"><?=$arr_profile_info['prayer_count']?></span><?php } ?></span></a>
                </li>
                <li class="last"><a href="my-contacts/Yahoo" class="<?php echo ($page_name == 'my-contacts') ? 'current' : ''; ?>"><span>My Contacts</span></a> </li>
          </ul>
      </div>
      <br class="clr" />
</div>
 <!--connections end -->
 
                          