 <!--media library start -->
  <div class="menu-box">
        <div class="nw-heading">
          		<div class="left">
                      <h4><img src="images/icons/media-library.png" width="20px" height="20px" alt="Media Library"/>Media Library</h4>
                </div>
                <div class="minus right exp-col019" style="display:none;"><img src="images/icons/nw-minus.png" width="13px" height="10px" alt="" class="plus-minus2"/></div>
                <div class="plus right exp-col019"><img src="images/icons/nw-plus.png" width="13px" height="10px" alt="" class="plus-minus2"/></div>
          </div>
        <div class="nw-content" id="switchdiv019" style="display:none;">
            <ul>
                  <li><a href="my-photos.html" class="<?php echo ($page_name=='my-photos')?'select':'';?>">My Photos</a></li>
                  <li><a href="my-audios.html" class="<?php echo ($page_name=='my-audios')?'select':'';?>">My Audios</a></li>
                  <li class="last"><a href="my-videos.html" class="<?php echo ($page_name=='my-videos')?'select':'';?>">My Videos</a></li>
            </ul>
        </div>
        <br class="clr" />
  </div>
  <!--media library end -->