 <!--people you may know -->
<div class="cogtime_projects">
                                    <div class="nw-right-heading">
                                          <div class="left">
                                                <h4>People You May Know</h4>
                                          </div>
                                          <div class="right exp-col022"><img src="images/minus-white.png" alt="" class="plus-minus" /></div>
                                          <div class="right exp-col022" style="display:none;"><img src="images/plus-white.png" alt="" class="plus-minus" /></div>
                                    </div>
                                    <div class="content" id="switchdiv022">
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="images/alex.jpg" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="javascript:void(0);">John Archer</a></p>
                                                <p class="nw-date-time">10 Mutual Friends</p>
                                                <p><a href="#" class="add-as-friend">[add as friend]</a></p>
                                          </div>
                                          
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="images/alex.jpg" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="javascript:void(0);">John Archer</a></p>
                                                <p class="nw-date-time">10 Mutual Friends</p>
                                                <p><a href="#" class="add-as-friend">[add as friend]</a></p>
                                          </div>
                                          <div class="clr"></div>
                                          <div class="view_more"><a href="#">[see all]</a></div>
                                    </div>
                              </div>
<!--/ people you may know -->