 <!--people you may know -->
<div class="cogtime_projects">
                                    <div class="nw-right-heading">
                                          <div class="left">
                                                <h4>People You May Know</h4>
                                          </div>
                                          <div class="minus-right right exp-col022" style="display:none;"><img src="images/minus-white.png" width="13" height="10" alt="" class="plus-minus" /></div>
                                          <div class="plus-right right exp-col022"><img src="images/plus-white.png" alt="" class="plus-minus" width="13" height="10" /></div>
                                    </div>
                                    <div class="content" id="switchdiv022" style="display:none;">
									<?php 
 //$friends=get_friends_by_id($_SESSION['user_id']);
//pr($people_you_may_know); 

 if($people_you_may_know)
 {
 	
 ?>									<?php 
									//$vals=array_slice($val,'0','2');
									 $logged_user_id = intval(decrypt($this->session->userdata('user_id')));
									for($i=0;$i<3;$i++)
									{
										$k = $people_you_may_know[$i];
										$profile_link =get_profile_url( $k['user_id'] , my_url($k['name']) );
										$img = get_profile_image_of_user('thumb',$k['s_profile_photo'],$k['e_gender']);
										/*********************already friend***************************/
                                                           $fr = "SELECT COUNT(*) AS check_count FROM cg_user_contacts WHERE i_requester_id ='".$logged_user_id."'  AND i_accepter_id = '".$k['user_id']."' AND s_status = 'pending' ";
                                                                 $result1  = $this->db->query($fr)->result_array();
                                                                $check_count = $result1[0]['check_count'];
              
                                                                                   /****************************************************/
									?>
									    <div class="project_box">
                                                <a href="javascript:void(0);"><img src="<?=$img?>" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="<?=$profile_link?>"><?=$k['name']?></a></p>
												<p class="nw-date-time"><?=$k['mutualfrnd']?> Mutual Friend<?=($k['mutualfrnd']==1)?' ':'s '?></p>
                                                                                                <?php
                                                                                                if($check_count == 0){
                                                                                                ?>
                                                <p><a href="javascript:void(0);" id="invite_friend_<?=$k['user_id']?>" class="add-as-friend" onclick="invite_friend_('<?=encrypt($k['user_id'])?>')">[add as friend]</a></p>
                                                                                                <?php }else{ ?>	
                                                <p><a href="javascript:void(0);" id="invite_friend_<?=$k['user_id']?>" class="add-as-friend" >[Friend request sent]</a></p>
                                                                                                <?php } ?>
                                          </div>
                                          <?php 
										  
										  }?>
                                          <div class="clr"></div>
										  <?php if(count($people_you_may_know)>2){?>
                                          <div class="view_more"><a href="<?=base_url()?>mutual-friends">[see all]</a></div>
										  <?}?>
                                    </div>
									  <?php }
									  else
									  {?>
									  <?php 
									$vals=get_friend_suggestion();
									//$i=0;
									foreach($vals as $val)
									{
					
									$name=$val['s_profile_name'];
									$profile_link = get_profile_url($val['id'],$val['s_profile_name']);
									 $img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);
									// $ct=get_mutual_count($m);
									?>
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="<?=$img?>" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="<?=$profile_link?>"><?=$name?></a></p>
                                         
                                                <p><a href="javascript:void(0);" id="invite_friend_(<?=$val['id']?>)" class="add-as-friend" onclick="invite_friend_('<?=encrypt($val['id'])?>')">[add as friend]</a></p>
                                          </div>
                                          <?php 

										  }
										  ?>
                                      
                                          <div class="clr"></div>
									  <?php
									  }?>
                              </div>
                              
							
<!--/ people you may know -->
<script type="text/javascript">
function invite_friend_(id)
	{
		var URL = base_url +'logged/my_friends/invite_friend';
		showBusyScreen();
		if(ajax_req!=null) {
			ajax_req.abort();
		}
		ajax_req = $.ajax({
			type: 'POST',
			url:URL,
			dataType: 'json',
			data: ({ 'frnd_id' : id
				 }),
			success: function (data) {
							var result_obj = data;
							hideBusyScreen();
							if(result_obj.success== true ) {
								showUIMsg(result_obj.msg);
                                                              //  alert('#invite_friend_'+result_obj.u_id);
								$('#invite_friend_'+result_obj.u_id).text(result_obj.html_txt);
							}
							else if(result_obj.success==false){
							    showUIMsg(result_obj.msg);
							}
					},
			error: function (data, status, e) {
								hideBusyScreen();
								showUIMsg(data.msg);
			}
		});
	}
</script>