 <!--people you may know -->
<div class="cogtime_projects">
                                    <div class="nw-right-heading">
                                          <div class="left">
                                                <h4>People You May Know</h4>
                                          </div>
                                          <div class="minus-right right exp-col022" style="display:none;"><img src="images/minus-white.png" width="13" height="10" alt="" class="plus-minus" /></div>
                                          <div class="plus-right right exp-col022"><img src="images/plus-white.png" alt="" class="plus-minus" width="13" height="10" /></div>
                                    </div>
                                    <div class="content" id="switchdiv022" style="display:none;">
									<?php 
 $friends='';//get_friends_by_id($_SESSION['user_id']);
 if($friends != 0)
 {
 $val=get_mutual_friends($_SESSION['user_id']);
 //pr($val,1);?>
									<?php 
									//$vals=array_slice($val,'0','2');
									$i=0;
									foreach($val as $key=>$m)
									{
										 $i=$i+1;
										 $k=array();
										 $k=explode(',',$key);
										 $name=$k[1].' '.$k[2];
										 $profile_link = base_url() . "profile/" . $k[0] . "/" . my_url($name) . ".html";
										 $img = get_profile_image_of_user('thumb',$k[4],$k[3]);
										 $ct=get_mutual_count($m);
										 $address = get_user_address_info($k[0]); 
									?>
									
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="<?=$img?>" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="<?=$profile_link?>"><?=$name?></a></p>
												<p class="location"><?=$address?></p>
												
                                                <p class="nw-date-time"><?=$ct?> Mutual Friend<?=($ct==1)?' ':'s '?></p>
                                                <p><a href="javascript:void(0);" id="#invite_friend_(<?=$k?>)" class="add-as-friend" onclick="invite_friend_('<?=encrypt($k)?>')">[add as friend]</a></p>
												
                                          </div>
                                          <?php 
										  if($i>1)
										 break;
										  }?>
                                        
                                          <div class="clr"></div>
										  <?php if(count($val)>2){?>
                                          <div class="view_more"><a href="<?=base_url()?>mutual-friends">[see all]</a></div>
										  <?}?>
                                    </div>
									  <?php }
									  else
									  {?>
									  <?php 
									$vals=get_friend_suggestion();
									//$i=0;
									foreach($vals as $val)
									{
					
									$name=get_user_name_by_id($val['id']);
									$profile_link = get_profile_url($val['id'],$name);
									 $img = get_profile_image($val['id'], 'thumb');
									// $ct=get_mutual_count($m);
									?>
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="<?=$img?>" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="<?=$profile_link?>"><?=$name?></a></p>
                                         
                                                <p><a href="javascript:void(0);" id="#invite_friend_(<?=$val['id']?>)" class="add-as-friend" onclick="invite_friend_('<?=encrypt($val['id'])?>')">[add as friend]</a></p>
                                          </div>
                                          <?php 

										  }?>
                                      
                                          <div class="clr"></div>
									  <?php
									  }?>
                              </div>
							
<!--/ people you may know -->
<script type="text/javascript">
function invite_friend_(id)
	{
		var URL = base_url +'logged/my_friends/invite_friend';
		showBusyScreen();
		if(ajax_req!=null) {
			ajax_req.abort();
		}
		ajax_req = $.ajax({
			type: 'POST',
			url:URL,
			dataType: 'json',
			data: ({ 'frnd_id' : id
				 }),
			success: function (data) {
							var result_obj = data;
							hideBusyScreen();
							if(result_obj.success== true ) {
								showUIMsg(result_obj.msg);
								//$('#invite_friend_'+result_obj.u_id).html(result_obj.html_txt);
							}
							else if(result_obj.success==false){
							    showUIMsg(result_obj.msg);
							}
					},
			error: function (data, status, e) {
								hideBusyScreen();
								showUIMsg(data.msg);
			}
		});
	}
</script>