 <!-- cogtime projects -->
<div class="cogtime_projects" style="margin-bottom:10px;">
                                    <div class="nw-right-heading">
                                          <div class="left">
                                                <h4>CoGTime Events </h4>
                                          </div>
                                          <div class="minus-right right exp-col02" style="display:none;"><img src="images/minus-white.png" width="13" height="10" alt=""  class="plus-minus" /></div>
                                          <div class="plus-right right exp-col02"><img src="images/plus-white.png" alt="" class="plus-minus" width="13" height="10"/></div>
                                    </div>
                                    <div class="content" id="switchdiv02" style="display:none;">
                                    <?php 
										if(is_array($latest_admin_events))
										{
										
										foreach($latest_admin_events as $result){
										?>
                                          <div class="project_box">
                                                <p class="blue_bold12"><strong><?=$result['s_title']?></strong></p>
                                                <p><?=my_substr(html_entity_decode(htmlspecialchars_decode($result['s_desc']),ENT_QUOTES,'utf-8'), 97);?></p>
                                                <p><?=$result['s_city']?>, <?=$result['s_state']?>, <?=get_country_name_by_id($result['i_country_id'])?></p>
                                                <p>Duration: <?=getShortDateWithTime($result['dt_start_time'],7)?> to <?=getShortDateWithTime($result['dt_end_time'],7)?></p>
                                          </div>
                                          <?php }
										}										
									?>
                                          <div class="clr"></div>
                                       
                                    </div>
                              </div>
 <!-- /cogtime projects -->