 <!--people you may know -->
 <?php $val=get_mutual_friends($_SESSION['user_id']);
 //pr($val,1);?>
<div class="cogtime_projects">
                                    <div class="nw-right-heading">
                                          <div class="left">
                                                <h4>People You May Know</h4>
                                          </div>
                                          <div class="right exp-col022"><img src="images/minus-white.png" alt="" class="plus-minus" /></div>
                                          <div class="right exp-col022" style="display:none;"><img src="images/plus-white.png" alt="" class="plus-minus" /></div>
                                    </div>
                                    <div class="content" id="switchdiv022">
									<?php 
									//$vals=array_slice($val,'0','2');
									$i=0;
									foreach($val as $k=>$m)
									{
									$i=$i+1;
									$name=get_user_name_by_id($k);
									$profile_link = get_profile_url($k,$name);
									 $img = get_profile_image($k, 'thumb');
									 $ct=get_mutual_count($m);
									?>
                                          <div class="project_box">
                                                <a href="javascript:void(0);"><img src="<?=$img?>" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="<?=$profile_link?>"><?=$name?></a></p>
                                                <p class="nw-date-time"><?=get_mutual_count($m)?> Mutual Friend<?=($ct==1)?' ':'s '?></p>
                                                <p><a href="javascript:void(0);" id="#invite_friend_(<?=$k?>)" class="add-as-friend" onclick="invite_friend_('<?=encrypt($k)?>')">[add as friend]</a></p>
                                          </div>
                                          <?php 
										  if($i>1)
										 break;
										  }?>
                                        <!--  <div class="project_box">
                                                <a href="javascript:void(0);"><img src="images/alex.jpg" alt="" class="pro_photo3" /></a>
                                                <p class="grey-link"><a href="javascript:void(0);">John Archer</a></p>
                                                <p class="nw-date-time">10 Mutual Friends</p>
                                                <p><a href="#" class="add-as-friend">[add as friend]</a></p>
                                          </div>-->
                                          <div class="clr"></div>
										  <?php if(count($val)>2){?>
                                          <div class="view_more"><a href="<?=base_url()?>mutual-friends">[see all]</a></div>
										  <?}?>
                                    </div>
                              </div>
<!--/ people you may know -->
<script type="text/javascript">
function invite_friend_(id)
	{
		var URL = base_url +'logged/my_friends/invite_friend';
		showBusyScreen();
		if(ajax_req!=null) {
			ajax_req.abort();
		}
		ajax_req = $.ajax({
			type: 'POST',
			url:URL,
			dataType: 'json',
			data: ({ 'frnd_id' : id
				 }),
			success: function (data) {
							var result_obj = data;
							hideBusyScreen();
							if(result_obj.success== true ) {
								showUIMsg(result_obj.msg);
								//$('#invite_friend_'+result_obj.u_id).html(result_obj.html_txt);
							}
							else if(result_obj.success==false){
							    showUIMsg(result_obj.msg);
							}
					},
			error: function (data, status, e) {
								hideBusyScreen();
								showUIMsg(data.msg);
			}
		});
	}
</script>