<?php
	if($page_name != 'tweets' && $page_name != 'my-tweets' && $home_menu !='1'){ #pr($right_bar['tweet_arr']);
?>
 <!-- my tweet -->
<div class="my_tweet">
      <div class="nw-right-heading">
            <div class="left">
                  <h4>My Chitter Tweets</h4>
            </div>
            <div class="minus-right right exp-col01" style="display:none;"><img src="images/minus-white.png" alt="" class="plus-minus" width="13" height="10" /></div>
            <div class="plus-right right exp-col01"><img src="images/plus-white.png" alt=""  class="plus-minus" width="13" height="10"/></div>
      </div>
      <div class="content no-padding" id="switchdiv01" style="display:none;">
            <div class="dot-box" >
                  <div class="view-my">
                  <a  href="<?=base_url()?>my-followers.html" class="left">[view my followers]</a>
                  
                  </div>
                  <div class="clr"></div>
                  <form method="post" class="tweet-post">
                      <p>Tweet</p>
                          <div class="tweet-textarea">
                          <textarea id="ta_rightbar_post_tweet" name="ta_rightbar_post_tweet" onfocus="if(this.value=='Max 140 Characters')this.value='';" onblur="if(this.value=='')this.value='Max 140 Characters';" onkeypress="return restrict_carrige(event);" maxlength="140" >Max 140 Characters</textarea>
                          </div>
                          <input name="" type="button" class="wall-comment-submit" value="Post" onclick="post_rightbar_tweet_text('right_bar')" />
                  </form>
            </div>
            <div class="project_box no-brdr">
                  <p class="blue_bold12" style="padding-bottom:8px;"><a  href="javascript:void(0);">My Tweet Chain</a></p>
           
                 <div id ="new_right_tweet_contents">
                  <?php
                      if(count($right_bar['tweet_arr'])){
                      foreach($right_bar['tweet_arr'] as $key=> $val){
                          
                          $data = json_decode($val['data']);
                          
                          if($val['s_type'] == 'retweeted'){
							  // $twit_id = getTwitterUsernameById($data->tweet_owner_id);
                                                            $twit_id = $val['s_tweet_id'];
                                                           $count = strlen($twit_id);
							 // $rt_profile_link = getTwitterProfileLink($twit_id);
                                                           $rt_profile_link = base_url() . "user-twitter-profile/" . intval(decrypt($this->session->userdata('user_id'))) . '/' . substr($twit_id, 1, $count) . ".html";
						  }
						  $profile_image_filename = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);
                                                  $twit_id = $val['s_tweet_id'];
                                                           $count = strlen($twit_id);
							 // $rt_profile_link = getTwitterProfileLink($twit_id);
                                                           $profile_link = base_url() . "user-twitter-profile/" . intval(decrypt($this->session->userdata('user_id'))) . '/' . substr($twit_id, 1, $count) . ".html";
						 // $profile_link = getTwitterProfileLink($val['s_tweet_id']);
						 
                           $MARK_UNMARK_TXT = ($val['fav_tweet'] == 1)?'Unmark from your favourite tweet?':'Mark this as your favourite tweet?';

						 $tweet_text =  strip_tags(htmlspecialchars_decode($data->s_tweet_text));  
						//pr( strpos($tweet_text, ':'));
						if(strpos($tweet_text, ':')){
							 $tweet_desc_first_part = substr($tweet_text, 0, strpos($tweet_text, ':')+1);
							 $tweet_desc  = substr($tweet_text, strpos($tweet_text, ':')+1, strlen($tweet_text));
							// get_href_content(htmlspecialchars_decode($data->s_tweet_text)); 
							 $new_text = $tweet_desc_first_part.'<a href="'.get_href_content(htmlspecialchars_decode($data->s_tweet_text)).'">'.substrws($tweet_desc, 22).'</a>';
							//exit;
						}
						else{
							$new_text =  substrws(htmlspecialchars_decode($data->s_tweet_text), 60); 
						}
						
					
                  ?>
                  
                     <div style="margin-top: 10px;">
                       
                       <?php if($val['s_type'] == 'normal'){ 
                       ?>
                        <a href="<?=$profile_link?>"><div class="pro_photo3" style="background:url(<?php echo $profile_image_filename;?>) no-repeat center;width:60px; height:60px;" ></div></a>                
                        <div class="right_div01">
                              <p  style="font-size:12px; line-height:15px;"><a  href="<?=$profile_link?>" class="light_blue_link"><?=$val['s_profile_name']?> <?=$val['s_tweet_id']?> :</a> </p>
                              <p class="nw-date-time" style="font-size:12px; line-height:15px;"><?=get_time_elapsed($val['dt_created_on'])?><!--id="tweet_ryt_date"-->
                               <span id="fav_img<?=$val['id']?>">
                                <?php if($val['fav_tweet'] > 0){?>
                                 
                                 <img src="images/icons/heart.png" alt="favorite" width="14" height="14" class="favorite-icon" title="Favorite" />
                                 
                                <?php } ?>
                                </span>
                              </p>
                               <p style="font-size:12px; line-height:15px; padding-bottom:10px;"><?=(get_twitter_profile_hash_link(($new_text)))?></p>
							   <?php if(!empty($data->photo) && count($data->photo)){ 
			   			foreach($data->photo as $key=>$photo_val):
							
							$IMG = base_url()."uploads/tweet_photos/".getThumbName($photo_val,'thumb');
			   ?>
			   <div class="video-image">
                     <div class="" style="background:url('<?=$IMG?>') no-repeat center;width:60px;height:45px" ></div> 
                </div>
               <?php 	endforeach;
			   		 }
				?>
				
                        </div>
                        <?php } 
                              else if($val['s_type'] == 'retweeted'){
                        ?>
                        <a href="<?=$profile_link?>"><div class="pro_photo3" style="background:url(<?php echo $profile_image_filename;?>) no-repeat center;width:60px; height:60px;" ></div></a>               
                        <div class="right_div01">
                             <p  style="font-size:12px; line-height:15px;"><a  href="<?=$profile_link?>" class="light_blue_link"><?=$val['s_profile_name']?> <?=$val['s_tweet_id']?> :</a> </p>
                              <p class="nw-date-time"><?=get_time_elapsed($val['dt_created_on'])?><!--id="tweet_ryt_date"-->
                               <span id="fav_img<?=$val['id']?>">
                                <?php if($val['fav_tweet'] > 0){?>
                                 
                                 <img src="images/icons/heart.png" alt="favorite" width="14" height="14" class="favorite-icon" title="Favorite" />
                                 
                                <?php } ?>
                                </span>
                              </p>
                               <p> <span style=" font-size:13px;color: #ABABAB; ">RT <a href="<?=$rt_profile_link?>" style="color: #ABABAB; text-decoration:none;"><?php echo $val['s_tweet_id']; //getTwitterUsernameById($data->tweet_owner_id)?></a> :</span> <?=get_twitter_profile_hash_link($new_text)?></p>
                             
							 <?php if(!empty($data->photo) && count($data->photo)){ 
			   			foreach($data->photo as $key=>$photo_val):
							
							$IMG = base_url()."uploads/tweet_photos/".getThumbName($photo_val,'thumb');
			   ?>
			   <div class="video-image">
                     <div class="" style="background:url('<?=$IMG?>') no-repeat center;width:60px;height:45px" ></div> 
                </div>
               <?php 	endforeach;
			   		 }
				?>
				
                        </div>
                        <?php } ?>
                        
                        
                        <div class="light_heading liquid">
                            <ul>
                                <li><a  href="javascript:void(0);" class="left" onclick="view_tweet_reply(<?= $val['id']?>)">[reply]</a></li>
								
				<?php 
                                //echo $val['fav_tweet'].'/';
				// $fav=check_fav($val['id']);
                                $fav=$val['fav_tweet'];
				if($fav == 0)
					{
					?>
              <li><a  href="javascript:void(0);" class="left" style="margin-left:23px;" onclick="javascript:mark_fav_tweet(<?=$val['id']?>,1,<?=$val['fav_tweet']?>)">[Favorite]</a></li>
			  <?php
					}
					else
					{
					?>
			  <li><a  href="javascript:void(0);" class="left" style="margin-left:8px;" onclick="javascript:mark_fav_tweet(<?=$val['id']?>,0,<?=$val['fav_tweet']?>)">[Favourited]</a></li>

					<?php
					}
					?>                                 <?php   
                        //echo $data->tweet_owner_id.' -- '.intval(decrypt($this->session->userdata('user_id'))); 
                          if($val['i_owner_id'] != intval(decrypt($this->session->userdata('user_id'))) && $data->tweet_owner_id != intval(decrypt($this->session->userdata('user_id')))){ ?>
                          <li id="li_retweet_block<?=$val['id']?>"><a class="right"  href="javascript:void(0);" onclick="slideDownRetweet(<?= $val['id']?>)">[retweet]</a></li>
                         <?php  }
                         ?>
                            </ul>
                            <div class="clr"></div>
                        
                            
                            
                        <div class="tweeterBlock">
                          <!--reply block start -->
                          <div class="insideTweeterBlock" id="tweet_reply_block<?=$val['id']?>">
                           <div id="tweet_reply<?=$val['id']?>"></div>
                            <form method="post">
                                <textarea name="ta_tweet_reply<?=$val['id']?>" id="ta_tweet_reply<?=$val['id']?>" onfocus="if(this.value=='Max 140 Characters')this.value='';" onblur="if(this.value=='')this.value='Max 140 Characters';" >Max 140 Characters</textarea>
                                <input name="post" type="button" value="Post" class="small-blue-btn left" onclick="post_reply(<?=$val['id']?>)"/>
                                <div class="clr"></div>
                            </form>
                        </div>
                          <!--reply block end -->
                          <!--mark as favorite block start -->
                          <div class="insideTweeterBlock" id="tweet_fav_block<?=$val['id']?>">
                              <p id="<?='ptext'.$val['id']?>"><?=$MARK_UNMARK_TXT?></p>
                              <div class="clr"></div>
                              <?php if($val['fav_tweet'] == 1){ ?>
                                    <span id="<?=$val['id']?>_status"><input name="favorite" type="button" value="Unmark" class="small-blue-btn" onclick="javascript:mark_fav_tweet(<?=$val['id']?>,0,<?=$val['fav_tweet']?>)"/></span>
                              <?php 
                                  } 
                                  else if($val['fav_tweet'] == 0){?>
                                      <span id="<?=$val['id']?>_status"><input name="favorite" type="button" value="Mark" class="small-blue-btn" onclick="javascript:mark_fav_tweet(<?=$val['id']?>,1,<?=$val['fav_tweet']?>)"/></span>
                              
                              <?php }?>
                          </div>
                          <!--mark as favorite block end -->
                          <!--retweet block start -->
                          <div class="insideTweeterBlock" id="retweet_block<?=$val['id']?>">
                              <p>Retweet this to your followers?</p>
                              <div class="clr"></div>
                              <input name="retweet" type="button" value="Retweet" class="small-blue-btn" onclick="retweet('right_bar',<?=$val['id']?>);" />
                              <input name="cancel" type="button" value="Cancel" class="small-green-btn" />
                          </div>
                          <!--retweet block end -->
                      </div>
                            <div class="clr"></div>
                        </div>
                        </div>
                   
                  
                  <?php 
                          }?>
                          
                        <div class="view-tweets">
                            <a href="my-tweets.html">[view my tweets]</a>
                        </div>
                        <div class="clr"></div>
                  <?php        
                      }else{
                          
                          echo '<p style="font-size:12px; line-height:15px; margin-left:90px; ">No Tweets.</p>';
                      }
                  ?>
                 </div> 
                 
			</div>
            
      </div>
</div>
<!-- /my tweet -->

<script type="text/javascript">
var ajax_post = null; 
function post_rightbar_tweet_text(posted_from) 
{
  //var id=$('#i_photo_id').val();
 showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
  if(ajax_post!=null) {
   ajax_post.abort();
  }
  ajax_post = $.ajax({
   
   url: base_url+'logged/tweet_home/post_his_tweets/'+posted_from,
   dataType: 'json',
   data: {'message': $('#ta_rightbar_post_tweet').val()},
   type: 'post',
 
   success: function (data, status) {
    if(data.success == 'true'){
	  $('.no_tweets').hide();
	  $('#ta_rightbar_post_tweet').val('');
	  
	  //alert(data.html);
	  $('#new_right_tweet_contents').html(data.html);
	  //$('#tweet_ryt_date').html(data.right_tweet_date);
      
    }
   hideUILoader_nodialog();
    showUIMsg(data.msg);
   },
   error: function(data, status, e) {
  //hideUILoader_nodialog();
    showUIMsg("Error!");
    
   }
  });
}

</script>                            
 <script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#ta_rightbar_post_tweet').keyup(function(){
            limitChars('ta_rightbar_post_tweet', 140, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('ta_rightbar_post_tweet',140, '');
    
 
});

var carriage_count = 0;
function restrict_carrige(e)
{
	

	if(e.keyCode == 13){
		carriage_count++;
		console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >5){
		return false;
		//e.preventDefault();
	}
}
$(document).ready(function() {

//  $('#myvideo_big_thumb_1').click(function(){
$('[id^="myvideo_big_thumb_t_"]').click(function(){ 
//alert($(this).attr('media_id'));
  showLoading(); 
  var media_id =  $(this).attr('media_id');
  $.ajax({
		type: 'post',
		url: base_url+'logged/tweet_home/get_video/',
		data: ({'media_id' : media_id ,'width':329 ,'height':212}),

		dataType: 'json',
		success: function (data, status) {
			if(data.result=='success') {
				hideLoading();
			   $('#myvideo_first_thumb_t_'+media_id).html(data.s_image_source.html);
			   $('#myvideo_first_thumb_t_'+media_id).attr('i_media_id',data.i_media_id);
			}
		},
		error: function (data, status, e) {
			hideLoading();
			showUIMsg('Some error occurred. Please try again.');
		}
	});
});
  $('[id^="myvideo_big_thumb_t_"]').trigger('click');
});
</script>  

<?php 
	}
?>                           
                             