<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Tweets</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                            <!--filter section start -->
                            <div class="filter">
                                <span class="filter-by">Filter By &raquo;</span>
                                <form  name="frm_search" id="frm_search" action="" method="post" onsubmit="return false;" class="filter-search">
                                    <label>Posted By :</label><input type="text" name="txt_tweet" id="txt_tweet" />
                                    <label style="width:32px;" >Date :</label>
                                    <input type="text"  value="" name="date_to1" id="date_to1"   class="date-field"/>
                                          <img src="../images/icons/cal.png" alt="" onclick="$(this).prev().focus()" class="calender" style="margin-right:35px;" />
                                          <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $.datepicker.setDefaults($.datepicker.regional['']);
                                                    $("#date_to1").datepicker($.datepicker.regional['en']);
                                
                                                });
                                          </script>
                                    
                                    <input type="hidden" value="Y" name="search_basic" id="search_basic"  />
                                    <input name="" type="submit" value="GO" class="go" />
                                </form>  
                                <div class="clr"></div>
                            </div>
                            <!--filter section end -->
                            <DIV id="table_content" style="margin-top:5px;">
							  <?=$result_content?>
                            </DIV>
                        	<div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->

<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Tweet</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">Do you really want to delete this tweet?</p>
                    <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->
