<?php
#pr($result_comments_arr);

if(count($result_comments_arr))
{
    
    foreach($result_comments_arr as $res)    :
        $comment_user_img = get_profile_image($res['i_user_id'],'thumb',$res['s_profile_photo']);
?>
                                  
                      <div class="txt_content01"> 
                          <a href="javascript:void(0);"><img src="<?php echo $comment_user_img?>" height="60" width="60" alt="" class="pro_photo" /></a>
                          <div class="left_div01a">
                            <p class="blue_bold12"><a  href="javascript:void(0);"><?= $res['s_profile_name']?></a></p>
                            <p class="light-grey"><?= $res['s_contents']?></p>
                            <p class="date-time"><?php if(get_time_elapsed($res['dt_created_on'])) echo "Updated on : ".get_time_elapsed($res['dt_created_on']);?></p>
                          </div>
                          <div class="clr"></div>
                      </div>
<?php
    endforeach;
}

?>
                                  
        