
     <div class="div_content">
     <DIV id="new_comment_div"><?=$comments_list?></DIV>
      <?php  if($no_of_comments > 4): ?>
              
              <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?=$current_comments_page?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
      <?php endif; ?>
     </div>
            
      
  
<!--lightbox details for image start -->
   
   
  
