<div class="div_content" style=" margin-top:0px;">

                            <?php
                            //pr($ringdata);
                            if($ringdata)
                            {
                                foreach($ringdata as $ringval)
                                {
                                    $LOGO    = base_url().'uploads/user_ring_logos/'.getThumbName($ringval['s_logo'],'thumb');
                                    $ring_detail_link    = base_url().'rings/'.$ringval['ringid'].'/ring-home.html';
                            ?>
                            <div class="blog">
                            <h2 class="nw-blg-heading">
                            <a href="<?php echo $ring_detail_link?>" id="ring_name_<?php echo $ringval['ringid']?>"><?php echo $ringval['s_ring_name']?></a>
                            </h2>
                             <h3 class="new-cat-ring cat-name-adjust"><img src="images/category.png" class="cat_icons" width="18" height="31" alt="" /><span><?php echo $ringval['s_category_name']?></span><span><?=get_ring_category_name_by_id($ringval['i_sub_category_id'])?></span></h3>
                            <div class="clr"></div>
                            <p class="time-posted">
                            created <?php echo getShortDate($ringval['dt_created_on'],5)?> by 
                            <?php
							if($ringval['if_already_friend'] == 'true' || $ringval['already_added_netpal'] == 'true'){
							  $profile_link = get_profile_url($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }else
							 {
							  $profile_link = get_profile_url_prayer_partner($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }										
							?>
                            <a style="color: #62C3BC;" href="<?php echo $profile_link?>"><?php echo $ringval['owner_name']?></a> 
                            </p>
                            
                            <p><?php echo my_substr($ringval['s_description'],160)?></p>
                            <div class="clr"></div>
                            <ul class="article-comment-block article-comment-block2">
                            	<li class="first">Total Posts : <?php echo $ringval['post']?> </li> 
                                <li> <span>Total Comments : <?php echo $ringval['cmt']?></span></li>
                                <li> <span>Total Likes : <?php echo $ringval['lik']?></span></li>
                                <li class="right">
                                    <ul>
										<?php
                                        if(!in_array($ringval['ringid'], $arr_join_req) && $this->i_profile_id != $ringval['i_user_id'])
                                        {
                                        ?> 
                                        <li  class="first" id="join_req_p_<?php echo $ringval['ringid']?>"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  onclick="joinRequest('ring_name_<?php echo $ringval['ringid']?>','<?php echo encrypt($ringval['ringid'])?>');">Join Ring</a></li>
                                        <?php 
                                        }
                                        ?>
                                    </ul>
                                </li>
                             </ul>
                            
                                  
                            </div>
                            
                            <?php
                                }
                            }
                            ?>
</div>
                    

                            
                            

