
<div class="clr"></div>
<!-- CONTENT SECTION -->
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<div id="content_section">
      <div id="container">
            
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" />  Denomination</div>
                        <div class="right"><input name="" type="button" value="Add New"  class="evnt_btn1" onclick="return show_dialog('add-denominations')"/></div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        
                        <div class="content_area">
                                              
                        <DIV ID ="table_content" style="margin-left: 210px;" >
                        <?=$result_content?>
                        </DIV>

                              
                        <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->


<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Denomination</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">Do you really want to delete the denomination?</p>
               <form method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<!--popup add headlines start-->
<div class="lightbox add-denominations" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Add Denomination</h4>
                       
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
              		
               <div class="content_area frm_box2"  >
               <!--<span style="font-size:11px;font-style:italic;line-height:13px;display:inline-block; height:30px; padding-top: 5px;">(Note: Only for external News link.)</span>-->
                
                        	  <form id="frm_add_denomination"  method="post"  onsubmit="return post_frm_ajax();" enctype="multipart/form-data"> 
                                  <div class="lable01"><span class="red-mark">* </span> Name :</div>
                                  <div class="field01">
                                        <input name="txt_add_denomination" id="txt_add_denomination" type="text" maxlength="90"/>
                                         <div class="clr"></div>
                                  </div>
                                  <div class="error-message" id="err_denomination" style="padding: 5px 0;"></div>
                                  <div class="clr"></div>
                          
                                  <div class="lable01"> </div>
                                  <div class="field01">
                                        <input name="" type="submit" class="btn"  value="Add"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('add');hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup add headlines end-->


<!--popup edit headlines start-->
<div class="lightbox edit-denomination" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Denomination</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2" style="padding-top: 0px;" >
               <!--<span style="font-size:11px;font-style:italic;line-height:13px;display:inline-block; height:30px;padding-top: 5px;">(Note: Only for external News link.)</span>-->
                        	  <form name="frm_edit_denomination" id="frm_edit_denomination" action="" method="post" onsubmit="return post_frm_edit_ajax();">
                                  <div class="lable01"><span class="red-mark">* </span> Name :</div>
                                  <div class="field01">
                                        <input name="txt_edit_denomination" id="txt_edit_denomination" type="text" maxlength="90"/>
                                         <div class="clr"></div>
                                  		
                                  </div>
                                   <div class="error-message" id="err_denomination_edit"></div>
                                  <div class="clr"></div>
                                  
                                  
                          
                                  
                                  <div class="lable01"> </div>
                                  <div class="field01">
                                  		<input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('edit');hide_dialog()"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup edit headlines end-->