<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>


<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
           <!-- <div id="top_corner">&nbsp;</div>-->
            <div id="mid_content">
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                       <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        <div class="page_heading">
                                    <div class="left"><img src="images/icons/frnd.png" alt="" /> Friends </div>
                              </div>
                          <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                              	<ul>
									<li><a href="my-friends.html" class="<?php echo ($page_name == 'my-friends') ? 'current' : ''; ?>"><span>My Friends</span></a> </li>
									<li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe"/></span></li>
									<li><a href="friend-request.html" class="<?php echo ($page_name == 'friend-request') ? 'current' : ''; ?>"><span>My Requests</span></a> </li>
									<li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe"/></span></li>
									<li><a href="search-invite-friends.html" class="<?php echo ($page_name == 'search-invite-friends') ? 'current' : ''; ?>"><span>Add Friends</span></a> </li>
									<li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe"/></span></li>
									<li><a href="find-friends.html" class="<?php echo ($page_name == 'find-friends') ? 'current' : ''; ?>"><span>Import Contacts</span></a> </li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                        <!--/sub page links -->
                              <div class="arrow_btm"></div>
                              <div class="section01" style="margin-bottom:1px;">
                                
                                </div>
                             	<DIV id="my_mutual_friends">
									<?=$friends_result_content?>
                                </DIV>
                    </div>
                        <!-- /mid container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>

<?php /*?>POPUPS AND SCRIPTS<?php */?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<!--popup one start-->

<!--popup one end-->

<script type="text/javascript">

 

</script>
