<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->


<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <div id="top_corner">&nbsp;</div>
        <div id="mid_content">
            <!-- latest news -->
            <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div id="main_container">
                <!-- left container -->
                <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
                <!-- /left container -->
                <!-- left container -->
                <div id="mid_container">
                
                    <div class="page_heading">
                                    <div class="left"><img src="images/icons/frnd.png" alt="" /> My Contacts </div>
                                    <?php /*?><div class="right"><a  href="search-invite-friends.html" class="btn_link" style="width:141px;"><span><img src="images/icons/search.png" alt="" /> Search   &amp; Connect</span></a></div><?php */?>
                              </div>
                    <!--sub page links -->
                   <!-- <div class="link-div" style="margin-top:0px;">-->
                       <!-- <ul>
                            <li><a href="my-friends.html" class="<?php echo ($page_name == 'my-friends') ? 'current' : ''; ?>"><span>My Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="friend-request.html" class="<?php echo ($page_name == 'friend-request') ? 'current' : ''; ?>"><span>My Requests</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="search-invite-friends.html" class="<?php echo ($page_name == 'search-invite-friends') ? 'current' : ''; ?>"><span>Add Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="find-friends.html" class="<?php echo ($page_name == 'find-friends') ? 'current' : ''; ?>"><span>Import Contacts</span></a> </li>
                           <!-- <li><span><img src="images/greynew-pipe.png"/></span></li>-->
                            <!--<li><a href="my-contacts/Yahoo" class="<?php echo ($page_name == 'my-contacts') ? 'current' : ''; ?>"><span>My Contacts</span></a> </li>-->
                        <!--</ul>-->
                        <div class="clr"></div>
                    <!--</div>-->
                    <!--/sub page links -->
                    
                    
                   
                     <p class="nw-del" onclick="delete_checked()"><img src="images/icons/delete.png" width="13" height="15"/> Delete</p> <p class="select-all"> <a onclick="javascript:checkAll();" href="javascript:void(0)" style="margin-left:20px;">Select All</a></p> 
                    <div class="arrow_btm"></div>
                    <div class="frm_box shade_box_blue" style="padding-bottom:17px;">
                       <div class="email-overflow <?=(count($result) == 0)?'email-overflow-no':''?>">
                            <ul id="mailidUl" style="">
                            
                            <?php
								if(count($result))
								{ //pr($result);
								foreach($result as $contact) 
                                                                    echo $contact->id;
                                                                    {?>
                                <li>
                                    <input type="checkbox" name="contact_<?=$contact['id']?>" id="contact_<?=$contact['id']?>" value="<?=$contact['id']?>" /><?php  echo $contact->s_contact_email; ?>
                                </li>
                                <?php } 
								}
								else
								{?>
                                <h4 class="no-contacts">No Contacts Imported</h4>
                                <?php } ?>
                            </ul>
                            </div>
                        
                    </div>

					<div>
                    <?php $handler->handle_request($_POST);?>
                    </div>
                </div>
                <!-- /left container -->
                <!-- right container -->
                <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
                <!-- /right container -->
            </div>
            <!-- /main container -->
            <div class="clr"></div>
        </div>
        <div id="bot_corner">&nbsp;</div>
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
</div>
<!-- /FOOTER SECTION -->
<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:245px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Remove Contact</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to remove this contact?</p>
               </div>
               <form method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="popup-yes" onClick="delete_contacts()"/>
                    <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<script type="text/javascript">
    $(document).ready(function(arg) {

        $('#frm_Search_friends').submit(function() {

            var datatosend = $("#frm_Search_friends").serialize();

            showBusyScreen();
            //alert(datatosend);
            $.ajax({
                type: "POST",
                url: base_url + "logged/my_friends/send_invitation",
                data: datatosend,
                success: function(data) {
                    hideBusyScreen();
                    showUIMsg('Successfully send');
                }
            });


        });

    });

function addInContacts()
{
	showBusyScreen();
	$.ajax({
			type: "POST",
			url: base_url + "logged/my_friends/add_in_contacts",
			data: $('#invite_form').serialize(),
			success: function(data) {
				hideBusyScreen();
				showUIMsg('Successfully added');
			}
		});
}

function checkAll() 
{ 
	if($('#mailidUl :checkbox').attr('checked')) {
		$('#mailidUl :checkbox').attr('checked', false);
	}
	else {
		$('#mailidUl :checkbox').attr('checked', true);
	}
}


function delete_checked() {
	var j = 0;
	$('#mailidUl :checkbox:checked').each(function(i){
		if($(this).attr('id').substr(0, 8) == 'contact_') {
			j++;
		}
	});
	if(j!=0) {
		show_dialog('delete-page-popup');
	}
}


function delete_contacts() 
{
  	hide_dialog();
 	showBusyScreen();

	var csv_mail_ids = '';
	$(':checkbox:checked').each(function(i){
		if($(this).attr('id').substr(0, 8) == 'contact_') {
			csv_mail_ids += $(this).val()+',';
		}
	});
	csv_mail_ids = csv_mail_ids.substring(0, csv_mail_ids.length-1); //alert(csv_mail_ids);
	 $.ajax({
		type: 'POST',
		url:base_url+'logged/my_friends/delete_contacts/',
		dataType: 'json',
		data: ({'csv_mail_ids': csv_mail_ids ,'current_page' : $('#current_page').val()}),
		success: function (data, status) {
			 hideBusyScreen();
			 showUIMsg(data.msg);
			 $('#mailidUl').html(data.content);
			
		},
		error: function (data, status, e) {
			hideBusyScreen();
		}
	});
}

</script>
