<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
.nw-chat-lnk{ color:#014882 !important; font-size:13px !important;
	cursor:pointer; }
</style>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
           <!-- <div id="top_corner">&nbsp;</div>-->
            <div id="mid_content">
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                       <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        <div class="page_heading">
                                    <div class="left"><img src="images/icons/frnd.png" alt="" /> Friends </div>
                                    <?php /*?><div class="right"><a  href="search-invite-friends.html" class="btn_link" style="width:141px;"><span><img src="images/icons/search.png" alt="" /> Search   &amp; Connect</span></a></div><?php */?>
                              </div>
                          <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                              	<ul>
                                	<li><a href="my-friends.html" class="<?php echo ($page_name == 'my-friends') ? 'current' : ''; ?>"><span>My Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="friend-request.html" class="<?php echo ($page_name == 'friend-request') ? 'current' : ''; ?>"><span>My Requests</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="search-invite-friends.html" class="<?php echo ($page_name == 'search-invite-friends') ? 'current' : ''; ?>"><span>Add Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png"/></span></li>
                            <li><a href="find-friends.html" class="<?php echo ($page_name == 'find-friends') ? 'current' : ''; ?>"><span>Import Contacts</span></a> </li>
                           <!-- <li><span><img src="images/greynew-pipe.png"/></span></li>-->
                            <!--<li><a href="my-contacts/Yahoo" class="<?php echo ($page_name == 'my-contacts') ? 'current' : ''; ?>"><span>My Contacts</span></a> </li>-->
                                </ul>
                                <div class="clr"></div>
                              </div>
                        <!--/sub page links -->
                        	
                            
                         <?php /*?>   <?php if(count($result_arr_friend) >0): ?>
                                <div style="padding-top:20px;">
                                    <div class="page_heading">
                                        <div class="left"><img src="images/icons/friend_rcv.png" alt="" /> Friend Request Received</div>
                                     </div>
                                      <DIV id="request_recieved_content"><?=$friend_request_recived?></DIV>
                                </div>
                           <?php endif; ?> <?php */?>
                            
                            
                              
                            
                              <div class="arrow_btm"></div>
                              <div class="section01" style="margin-bottom:1px;">
                                    <div class="txt_content" style="padding:5px 0px;">
                                          <div class="heading02" style="margin-bottom:10px;">
                                          <img src="images/icons/search.png" alt=""  />Search My Friend List </div>
                                            <div class="clr"></div>
                                            
                                     <form name="filter_friends" id="filter_friends" method="post"  onsubmit="return false;" >  
                                            <input name="txt_name" id="txt_name" type="text" style="width:223px; height:16px;  margin-right:5px;" class="left"/>
                                             <select name="show" id="show" style="width:160px;height:26px;line-height:21px;">
                                                <option value="-1">Show All</option>   
                                                <option value="1">Show Online</option>
                                                <option value="4">Show Offline</option>
                                          </select>
                       					<?php /*?> <script type="text/javascript">
                                              $(document).ready(function(arg) {
                                                  $("#show").msDropDown();
                                                  $("#show").hide();
                                              })
                                          </script><?php */?>
                                          <input type="hidden" name="search_basic" id="search_basic" value="Y" />
                                            <input name="btn_submit" id="btn_submit" type="submit" value="Search" class="yellow-btn my-frd-search <?php /*?>left<?php */?>" />
                                          </form>
                                          <div class="clr"></div>
                                    </div>
                              </div>
                             
                             	<DIV id="my_friends">
									<?=$friends_result_content?>
                                </DIV>
                        </div>
                        <!-- /mid container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>

<?php /*?>POPUPS AND SCRIPTS<?php */?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:245px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Remove Friend</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to remove this friend?</p>
               </div>
               <form action="" method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="popup-yes" onClick="delete_friend_()"/>
                    <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<script type="text/javascript">
$(document).ready(function(arg) {
 
 $('#filter_friends').submit(function(){ 
						
						var datatosend=$("#filter_friends").serialize();
						
					     	showBusyScreen();
							//alert(datatosend);
							$.ajax({
							   type: "POST",
							   url: base_url+"logged/my_friends/friends_ajax_pagination",
							   data: datatosend,
							   success: function(data){
								   $('#my_friends').html(data);
							       hideBusyScreen(); 
							   }
							 });	 
					   
						
				});
 
 });
 

</script>
