<div class="div_content" style=" margin-top:0px;">
    <?php
    if (count($result_arr) > 0) {
        foreach ($result_arr as $key => $val):

            $add = array();
            $name = $val['s_displayname'];
            
            $address = get_user_address_info($val['user_id']);
            $chat_name = get_chat_name_by_id($val['user_id']);
            $img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);

            $profile_link = get_profile_url($val['user_id'], $val['s_displayname']);
            $relation_arr = CheckUserRelation($val['user_id']);

            $chat_html = '';

            if (check_Chat_link_online_hlpr($val['user_id'], 'public', $relation_arr))
                $chat_html = ' <a class="nogrey_link nw-chat-lnk" onclick="showOnlineUser(\'show\');chatWith(\'' . $val['s_first_name'] . '\',' . $val['user_id'] . ')" chatwith="' . $val['user_id'] . '"><img src="images/Chat.png" height="20px" width="20px" title="chat" alt="chat" /></a>';
            ?>   

            <div class="shade_box_blue" style="padding-top:5px;" id="friend_record_<?= $val['user_id'] ?>"> 
                <div class="txt_content">
                    <a href="<?= $profile_link; ?>"><div class="pro_photo2" style="background:url(<?= $img ?>) no-repeat center;width:60px; height:60px;" ></div></a>
                    <div class="left_div01" style="width:397px;">
                        <p class="add-remove-friend"><img alt="" src="images/icons/remove.png" width="29" height="41" /> <a href="javascript:void(0);" onclick="delete_confirm_(<?= $val['user_id'] ?>)">Remove</a></p>
                        <p class="blue_bold12"><a  href="<?= $profile_link; ?>" class="left"><?= $name ?>&nbsp;(<?= $chat_name ?>) </a>&nbsp; [ <a class="nogrey_link"><?= check_user_online_hlpr($val['user_id'], 'public', $relation_arr); ?></a> ]<?= $chat_html ?></p>

                        
                        <p class="location"><?= $address ?></p>
                        <p class="date-time">Connected Since : <?= getShortDateWithTime($val['dt_created_on'], 6) ?> </p>

                    </div>
                    <div class="clr"></div>
                </div>
            </div>



            <?php
        endforeach;
    }
    else {
        echo '<div class="shade_box_blue" style="padding-top:5px;"><div  class="shade_norecords" style="width:275px;"><p class="blue_bold12">No friends.</p></div></div>';
    }
    ?>
</div>
