<?php include(APPPATH."views/layouts/logged_header.phtml");?>
<!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
<!-- /NAVIGATION SECTION -->


<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- left container -->
                        <div id="mid_container">
                        <div class="page_heading">
                                    <div class="left"><img src="images/icons/frnd.png" alt="" />Friends </div>
                                    <?php /*?><div class="right"><a  href="search-invite-friends.html" class="btn_link" style="width:141px;"><span><img src="images/icons/search.png" alt="" /> Search   &amp; Connect</span></a></div><?php */?>
                              </div>
                         <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                              	<ul>
                                	<li><a href="my-friends.html" class="<?php echo ($page_name == 'my-friends') ? 'current' : ''; ?>"><span>My Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe" /></span></li>
                            <li><a href="friend-request.html" class="<?php echo ($page_name == 'friend-request') ? 'current' : ''; ?>"><span>My Requests</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe"/></span></li>
                            <li><a href="search-invite-friends.html" class="<?php echo ($page_name == 'search-invite-friends') ? 'current' : ''; ?>"><span>Add Friends</span></a> </li>
                            <li><span><img src="images/greynew-pipe.png" width="11" height="32" alt="greynew-pipe"/></span></li>
                            <li><a href="find-friends.html" class="<?php echo ($page_name == 'find-friends') ? 'current' : ''; ?>"><span>Import Contacts</span></a> </li>
                           <!-- <li><span><img src="images/greynew-pipe.png"/></span></li>-->
                            <!--<li><a href="my-contacts/Yahoo" class="<?php echo ($page_name == 'my-contacts') ? 'current' : ''; ?>"><span>My Contacts</span></a> </li>-->
                                </ul>
                                <div class="clr"></div>
                              </div>
                        <!--/sub page links -->
                        
                        
                              <!--<div class="page_heading">
                                    <div class="left"><img src="images/icons/search_frnd.png" alt="" /> Search &amp; Invite Friends</div>
                                
                              </div>-->
                              <div class="arrow_btm"></div>
                              <div class="frm_box shade_box_blue" style="padding-bottom:17px;">
                              <?php //base_url().'search-invite-friends.html' ?>
                              <?php 
                                     if($this->session->userdata('is_preserve_search')){
                              ?>
                                 		<form id="frm_Search_friends"  method="post" enctype="multipart/form-data" onsubmit="return false;">
                                      
                                    <div class="lable02">First Name(*):</div>
                                    <div class="field01">
                                          <input name="txt_fname" id="txt_fname" type="text" value="<?=$this->session->userdata('s_fname');?>"  style="width:258px;"/>
                                    </div>  
                                    <div class="clr"></div>
                                    <div class="lable02">Last Name(*):</div>
                                    <div class="field01">
                                          <input name="txt_lname" type="text" id="txt_lname" value="<?=$this->session->userdata('s_lname');?>"  style="width:258px;"/>
                                    </div>
                                  <div class="clr"></div>
                                    <div class="lable02">Email ID:</div>
                                    <div class="field01">
                                         <input name="txt_email" id="txt_email" type="text"  value="<?=$this->session->userdata('s_email');?>"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable02">Country:</div>
                                    <div class="field01">
                                    	<input name="txt_country" id="txt_country" type="text"  style="width:258px;"/>
                                         <select name="txt_country" id="txt_country"  style="width:212px;"/>
										<option value="-1">Select</option>-->
                     					 <?=makeOptionCountry($this->session->userdata('s_church_name'));?>
                                         </select>

                                   </div>
                                    <div class="clr"></div>
                                	
                                     <div class="lable02">State:</div>
                                    <div class="field01">
                                         <input name="txt_state" id="txt_state" type="text" value="<?=$this->session->userdata('s_state');?>"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable02">City:</div>
                                    <div class="field01">
                                         <input name="txt_city" id="txt_city" type="text" value="<?=$this->session->userdata('s_city');?>"  style="width:258px;"/>
                                    </div>
                                   <div class="clr"></div>
                                     
                                     
                                     <div class="lable02">School/College:</div>
                                    <div class="field01">
                                         <input name="txt_school_name" id="txt_school_name" type="text" value="<?=$this->session->userdata('s_school_name');?>"  style="width:258px;"/>
                                    </div> 
                                    <?php /*?><div class="lable02">School Location:</div>
                                    <div class="field01">
                                         <input name="txt_school_address" id="txt_school_address" type="text"  style="width:258px;"/>
                                    </div><?php */?>
                                    <div class="clr"></div>
                                     <div class="lable02">Class Year:</div>
                                    <div class="field01">
                                         <input name="txt_class" id="txt_class" type="text" value="<?=$this->session->userdata('s_class');?>"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    
                                     <div class="lable02">Employer:</div>
                                    <div class="field01">
                                         <input name="txt_emp" id="txt_emp" type="text" value="<?=$this->session->userdata('s_emp_name');?>"   style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable02">Time Period:</div>
                                    <div class="field01">
                                        <!-- <input name="txt_time" id="txt_time" type="text"  style="width:258px; "/>-->
                                         <select name="year_from"  style="width:117px;margin-right:5px;">
                                                   <option value="">---</option>
                                                 <?=makeOptionYear($this->session->userdata('s_church_name'))?>
                                         </select>
                                         <span class="spanned_left"> &nbsp; To  &nbsp;</span>
                                         <select name="year_to" style="width:116px;">
                                                   <option value="">---</option>
                                                 <?=makeOptionYear($this->session->userdata('s_church_name'))?>
                                         </select>
                                         
                                         
                                         
                                    </div>
                                    <div class="clr"></div>
                                     <div class="lable02">Church:</div>
                                    <div class="field01">
                                         <input name="txt_church" id="txt_church" value="<?=$this->session->userdata('s_church_name');?>" type="text"  style="width:258px;"/>
                                    </div> 
                                    <?php /*?><div class="lable02">Church Location:</div>
                                    <div class="field01">
                                         <input name="txt_church_loc" id="txt_church_loc" type="text"  style="width:258px;"/>
                                    </div>
                                    <div class="clr"></div><?php */?>
                                   <div class="clr"></div>
                                    <div class="lable02">&nbsp;</div>
                                    <div class="field01">
                                    	 <input name="search_basic" id="search_basic" type="hidden" value="Y"/>
                                          <input name="" type="submit" value="Search"  class="btn"/>
                                    </div>
                                    <div class="clr"></div>
                                    
                                   </form>
                              <?php 
									  }
									  else{
							  ?>
                              			<form id="frm_Search_friends"  method="post" enctype="multipart/form-data" onsubmit="return false;">
                                        <div class="field01" style="margin-left:52px; width:auto">
                                        <span style="margin-right:40px">
                                          <input type="radio" name="select_search" value="1" checked="checked" />Search By Chat Name</span>
                                        <span>
                                          <input type="radio" name="select_search" value="2"  /> Search By User Details
                                         </span>
                                        </div>
                                        <div class="clr"></div>
                                      <div id="search_1" style="display:none"> 
                                    <div class="lable02">* First Name:</div>
                                    <div class="field01">
                                          <input name="txt_fname" id="txt_fname" type="text"  style="width:258px;"/>
                                    </div>  
                                    <div class="clr"></div>
                                    <div class="lable02">* Last Name:</div>
                                    <div class="field01">
                                          <input name="txt_lname" type="text" id="txt_lname"  style="width:258px;"/>
                                    </div>
                                  <div class="clr"></div>
                                    <div class="lable02">Email ID:</div>
                                    <div class="field01">
                                         <input name="txt_email" id="txt_email" type="text"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                     <div class="lable02"> Age Range: </div>
                                      
                                      <div class="field01"> 
                                          <!-- <input name="txt_time" id="txt_time" type="text"  style="width:200px; "/>-->
                                           <select style="width:115px;margin-right:5px;" name="age_from" id="age_from">
                                                     <option value="-1">Min Age</option>
                                                     <?=makeOptionNumber(18,80, 1,$this->session->userdata('s_age_from'))?>
                                           </select>
                                           <span class="spanned_left"> &nbsp; To  &nbsp;</span>
                                           <select style="width:115px;" name="age_to" id="age_to">
                                                     <option value="-1">Max Age</option>
                                                     <?=makeOptionNumber(18,80, 1, $this->session->userdata('s_age_to'))?>
                                          </select>
                                           
                                           
                                           
                                      </div>
                                       <div class="lable02">Gender:</div>
                                      <div class="field01">
                                            <select name="gender" id="gender" style="width:269px;">
                                                  <option value="-1" >Select</option>
                                                  <option value="M" <?=($this->session->userdata('e_gender')== 'M')?'selected="selected"':'';?>>Male</option>
                                                  <option value="F" <?=($this->session->userdata('e_gender')== 'F')?'selected="selected"':'';?>>Female</option>
                                            </select>
                                        <?php /*?>    <script type="text/javascript">
                                          $(document).ready(function(arg) {
                                              $("#gender").msDropDown();
                                              $("#gender").hide();
                                          })
                                      </script><?php */?>
                                      </div>
                                      <div class="clr"></div>
                                    <!--<div class="lable02">Country:</div>
                                    <div class="field01">
                                         <!--<input name="txt_country" id="txt_country" type="text"  style="width:258px;"/>-->
                                        <!-- <select name="txt_country" id="txt_country"  style="width:269px;"/>
										 <option value="-1">Select</option>
                     					 <?//=makeOptionCountry();?>
                                         </select>-->

                                   <!-- </div>
                                    <div class="clr"></div>
                                
                                     <div class="lable02">State:</div>
                                    <div class="field01">
                                         <input name="txt_state" id="txt_state" type="text"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable02">City:</div>
                                    <div class="field01">
                                         <input name="txt_city" id="txt_city" type="text"  style="width:258px;"/>
                                    </div>
                                    <div class="clr"></div>-->
                                    <div class="lable02"> Location: </div>
                                      <div class="field01">
                                            <input name="txt_location" id="txt_location" type="text" value="<?=$this->session->userdata('location')?>" style="width:258px;"/>
                                      </div>
                                      <div class="clr"></div>
                                     <div class="lable02">School/College:</div>
                                    <div class="field01">
                                         <input name="txt_school_name" id="txt_school_name" type="text"  style="width:258px;"/>
                                    </div> 
                                    <?php /*?><div class="lable02">School Location:</div>
                                    <div class="field01">
                                         <input name="txt_school_address" id="txt_school_address" type="text"  style="width:258px;"/>
                                    </div><?php */?>
                                    <div class="clr"></div>
<!--                                    <div class="lable02">School/College Location: </div>
                                    <br/>
                                      <div class="field01">
                                            <input name="txt_s_location" id="txt_s_location" type="text" value="<?=$this->session->userdata('s_location')?>" style="width:258px;"/>
                                      </div>
                                      <div class="clr"></div>
                                     <div class="lable02">Class Year:</div>
                                    <div class="field01">
                                         <input name="txt_class" id="txt_class" type="text"  style="width:258px;"/>
                                    </div> -->
                                    <div class="clr"></div>
                                    
                                    <!-- <div class="lable02">Employer:</div>
                                    <div class="field01">
                                         <input name="txt_emp" id="txt_emp" type="text"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable02">Time Period:</div>
                                    <div class="field01">
                                        <!-- <input name="txt_time" id="txt_time" type="text"  style="width:258px; "/>-->
                                         <!--<select name="year_from"  style="width:117px;margin-right:5px;">
                                                   <option value="">---</option>
                                                 <?=makeOptionYear()?>
                                         </select>
                                         <span class="spanned_left"> &nbsp; To  &nbsp;</span>
                                         <select name="year_to" style="width:116px;">
                                                   <option value="">---</option>
                                                 <?=makeOptionYear()?>
                                         </select>
                                         
                                         
                                         
                                    </div>
                                    <div class="clr"></div>-->
                                     <div class="lable02">Church:</div>
                                    <div class="field01">
                                         <input name="txt_church" id="txt_church" type="text"  style="width:258px;"/>
                                    </div> 
                                    <?php /*?><div class="lable02">Church Location:</div>
                                    <div class="field01">
                                         <input name="txt_church_loc" id="txt_church_loc" type="text"  style="width:258px;"/>
                                    </div>
                                    <div class="clr"></div><?php */?>
                                   <div class="clr"></div>
                                    <div class="lable02">Church Location: </div>
                                      <div class="field01">
                                            <input name="txt_c_location" id="txt_c_location" type="text" value="<?=$this->session->userdata('c_location')?>" style="width:258px;"/>
                                      </div>
                                      <div class="clr"></div>
                                   </div>
                                   <div id="search_2" >
                                   <div class="lable02">User name:</div>
                                    <div class="field01">
                                         <input name="txt_chat" id="txt_chat" type="text"  style="width:258px;"/>
                                    </div> 
                                    <div class="clr"></div>
                                    </div>
                                    <div class="lable02">&nbsp;</div>
                                    <div class="field01">
                                    	 <input name="search_basic" id="search_basic" type="hidden" value="Y"/>
                                          <input name="" type="submit" value="Search"  class="btn"/>
                                    </div>
                                    <div class="clr"></div>
                                    
                                   </form>
                              <?php
									  }
							  ?>
                              </div>
                    
                                    
                                   
                                   <DIV id="table_content">
									<?=$result_content?>
                                  </DIV>
                                    <?php /*?><div class="pagination">
                                          <div class="left">Viewing Page 1 of 10 </div>
                                          <div class="right"><a  href="javascript:void(0);" class="blue_link">&laquo; Previous</a> <a href="javascript:void(0);">1</a> <a href="javascript:void(0);">2</a> <a href="javascript:void(0);">3</a> <a href="javascript:void(0);">4</a> <a href="javascript:void(0);">5</a> <a  href="javascript:void(0);" class="blue_link">Next &raquo;</a></div>
                                    </div><?php */?>
                                   
                              
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
</div>
<!-- /FOOTER SECTION -->
<script type="text/javascript">
<!--	
	var ticker_holder = $('.bargaining').get(0);
	var ticker_text = $('.ticker').get(0);
	var ticker_pos = ticker_text.parentNode.offsetWidth;
	
	var ticker_data = $(ticker_holder).html();
	$(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');
	
	$('#sub-nav').hover
	(
	function() { $('marquee', this).get(0).stop();  },
	function() { $('marquee', this).get(0).start(); }
	); 
//-->
</script>


<script type="text/javascript">
$(document).ready(function(arg) {
$("input[name=select_search]").click(
function()
{
	var value=$(this).val();
	if(value=='1')
	{
		$("#table_content").html('');
		$("#search_2").slideDown('3000');
		$("#search_1").slideUp('3000');
	}
	else
	{
		$("#table_content").html('');
		$("#search_2").slideUp('3000');
		$("#search_1").slideDown('3000');
		
	}
}
);
 //alert(a);
 $('#frm_Search_friends').submit(function(){ 
      
      var datatosend=$("#frm_Search_friends").serialize();
      var fname=$("#txt_fname").val();
	  var lname=$("#txt_lname").val();
	  //var location=$("#txt_location").val();
	 var radio=$('input[name=select_search]:checked').val();
	  if( (fname == "" || lname == "") && (radio == '2'))
	  {
		 	
         showUIMsgFriend("Please enter first name and last name for search");  
	  }
	  else
	  {
		  showBusyScreen();
	  
       //alert(datatosend);
       $.ajax({
          type: "POST",
          url: base_url+"logged/my_friends/ajax_pagination",
          data: datatosend,
          success: function(data){
           $('#table_content').html(data);
              hideBusyScreen(); 
          }
        });  
  }
     
    });
 
 });

$(function() {
/*var m= "2220 AUGY,2220 BAZOCHES-SUR-VESLES,2220 BRAINE,2220 BRENELLE";
alert(m.replace(/[,]/g,"<br>"));*/

$("#txt_location").autocomplete("<?php echo base_url();?>logged/prayer_wall/send_cities", {
    width: 268,
    selectFirst: true,
    minChars: 3,
    multiple: false,
	multipleSeparator: "\n",
	max: null,
    //matchContains: false,
    formatItem: formatItem
   });
   function formatItem(row) 
{//console.log(row);
 //var n=row[0].replace(/[,]/g,"\n"); console.log(n);	
 if(row[0]!="No match found")
  return  "<span style='font-size:11px; font-weight:normal; margin:0px; padding: 3px 5px ;cursor: pointer; display:block;'>" + row[0]+"</span>";
 else
  return " (<span style='font-size:11px;'>" +row[0]+"</span>)";
}
	 
   
});
$(function() {
/*var m= "2220 AUGY,2220 BAZOCHES-SUR-VESLES,2220 BRAINE,2220 BRENELLE";
alert(m.replace(/[,]/g,"<br>"));*/

$("#txt_s_location").autocomplete("<?php echo base_url();?>logged/my_friends/send_cities", {
    width: 268,
    selectFirst: true,
    minChars: 3,
    multiple: false,
	multipleSeparator: "\n",
	max: null,
    //matchContains: false,
    formatItem: formatItem
   });
   function formatItem(row) 
{//console.log(row);
 //var n=row[0].replace(/[,]/g,"\n"); console.log(n);	
 if(row[0]!="No match found")
  return  "<span style='font-size:11px; font-weight:normal; margin:0px; padding: 3px 5px ;cursor: pointer; display:block;'>" + row[0]+"</span>";
 else
  return " (<span style='font-size:11px;'>" +row[0]+"</span>)";
}
	 
   
});
$(function() {
/*var m= "2220 AUGY,2220 BAZOCHES-SUR-VESLES,2220 BRAINE,2220 BRENELLE";
alert(m.replace(/[,]/g,"<br>"));*/

$("#txt_c_location").autocomplete("<?php echo base_url();?>logged/prayer_wall/send_cities", {
    width: 268,
    selectFirst: true,
    minChars: 3,
    multiple: false,
	multipleSeparator: "\n",
	max: null,
    //matchContains: false,
    formatItem: formatItem
   });
   function formatItem(row) 
{//console.log(row);
 //var n=row[0].replace(/[,]/g,"\n"); console.log(n);	
 if(row[0]!="No match found")
  return  "<span style='font-size:11px; font-weight:normal; margin:0px; padding: 3px 5px ;cursor: pointer; display:block;'>" + row[0]+"</span>";
 else
  return " (<span style='font-size:11px;'>" +row[0]+"</span>)";
}
	 
   
});
</script>
