<script type="text/javascript">
$(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoad,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#prod_frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});

function showLoad()
{
 // $('#photo_album_btn').attr('disabled','disabled');
 	showUIMsg();
  $('#product_create_btn').val('Creating...');
  
}


// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#product_create_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#'+id) != null ) {
				$('#'+id).html(data.arr_messages[id]);
				$('#'+id).css('display', 'block');
			}
		}

		
	}
	else {
		
		showUIMsg(data.msg);		
		window.location.href= "<?php echo base_url().'etrade/manage-my-product'?>";
		//window.location.href= "<?php echo base_url().'my-ring.html'?>";
		
	}
	$('#sp_add_loading').html('');
	//hideLoading();
				
}




</script>

<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
.newwidth
{
	width:320px !important;
}
.newwidth-lable01
{
	width:108px !important;
}
.txtwidth
{
	width:314px !important;
}

</style>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                  
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        
                        <div id="mid_container">
                       	  <div class="page_heading">
                            	<div class="left"><img src="images/icons/ring.png" alt="" /> Update Product</div>
                          </div>
                             
                             <div class="frm_box blue_box" style="width: 462px; padding:20px 15px;">
                             <form name="prod_frm" id="prod_frm" action="<?=base_url().'logged/e_trade/save_etrade_product'?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">
                             <input type="hidden" value="<?php echo $info['id']?>" name="id" />
                                    <div class="frm_box inbox_div_blue" style="padding-left:0px; padding-right:0px;">
                                   <div class="lable01 newwidth-lable01" >Category :</div>
                                    <div class="field03 newwidth">
                                          <select name="category" id="category" style="width:325px;">
                                          		<option value="">Please select category</option>
                                                <?php echo $category?>
                                          </select>
                                          <span id="err_category" class="error-message"></span> 
                                          
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Name :</div>
                                    <div class="field03 newwidth">
                                          <input name="product_name" type="text" class="txtwidth" value="<?php echo $info['s_name']?>" />
                                          <span id="err_product_name" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Brand :</div>
                                    <div class="field03 newwidth">
                                          <input name="product_brand" type="text" class="txtwidth" value="<?php echo $info['s_name']?>" />
                                          <span id="err_product_brand" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    
                                    <div class="lable01 newwidth-lable01" >Attribute 1 :</div>
                                    <div class="field03 newwidth">
                                          <input name="product_attr1" type="text" class="txtwidth" value="<?php echo $info['s_attribute1']?>" />
                                          <span id="err_product_attr1" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Attribute 2 :</div>
                                    <div class="field03 newwidth">
                                          <input name="product_attr2" type="text" class="txtwidth" value="<?php echo $info['s_attribute2']?>" />
                                          <span id="err_product_attr2" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Description  :</div>
                                    <div class="field03 newwidth">
                                          <textarea name="product_desc" style="width:316px; height:90px;"><?php echo br2nl($info['s_description'])?></textarea>
                                          <span id="err_product_desc" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div><img src="<?php echo base_url()?>uploads/e_trade_product/<?php echo getThumbName($info['s_image'],'thumb')?>" style="margin-left:124px;" /></div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Image  :</div>
                                    <div class="field03 newwidth">
                                          <input name="image" type="file"  style="width:317px;"/>
                                          <span id="err_image" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Stock  :</div>
                                    <div class="field03 newwidth">
                                         <input name="stock" type="text" class="txtwidth" value="<?php echo $info['i_stock']?>" />
                                         <span id="err_stock" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Condition :</div>
                                    <div class="field03 newwidth">
                                          <select name="condition" id="condition" style="width:325px;">
                                          		<option value="1" <?php if($info['i_condition']==1){?>selected<?php }?>>New</option>
                                                <option value="2" <?php if($info['i_condition']==2){?>selected<?php }?>>Old</option>
                                          </select>
                                          <span id="err_condition" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Unit Price ($) :</div>
                                    <div class="field03 newwidth">
                                          <input name="product_price" type="text" class="txtwidth" value="<?php echo $info['f_unit_price']?>" />
                                          <span id="err_product_price" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >Open to Sale For :</div>
                                    <div class="field03 newwidth">
                                          <select name="opensale" id="sale" style="width:325px;" onchange="selectShipping(this.value)">
                                              <option value="">Select Open to Sale</option>
                                              <option value="1" <?php if($info['i_open_to_offer_for_local']==1){?>selected<?php }?>>Local</option>
                                              <option value="2" <?php if($info['i_open_to_offer_for_local']==2){?>selected<?php }?>>International </option>
                                              <option value="3" <?php if($info['i_open_to_offer_for_local']==3){?>selected<?php }?>>Local & International </option>
                                          </select>
                                          <span id="err_opensale" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                    <div id="local" <?php if($info['i_open_to_offer_for_local']==1 || $info['i_open_to_offer_for_local']==3){?>style="display:block;"<?php }else{?>style="display:none;"<?php }?>>
                                        <div class="lable01 newwidth-lable01" >Shipping Cost($) :</div>
                                        <div class="field03 newwidth">
                                              <input name="localship" type="text" style="width:200px;" value="<?php echo $info['f_local_shipping_cost']?>" />&nbsp;(Local)
                                              <span id="err_localship" class="error-message"></span> 
                                        </div>
                                    </div>
                                    
                                    <div class="clr"></div>
                                    <div id="international" <?php if($info['i_open_to_offer_for_local']==2 || $info['i_open_to_offer_for_local']==3){?>style="display:block;"<?php }else{?>style="display:none;"<?php }?>>
                                        <div class="lable01 newwidth-lable01" >Shipping Cost($) :</div>
                                        <div class="field03 newwidth">
                                              <input name="international_ship" type="text" style="width:200px;" value="<?php echo $info['f_international_shipping_cost']?>" />&nbsp;(International)
                                              <span id="err_international_ship" class="error-message"></span> 
                                        </div>
                                    </div>
                                   
                                    
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" ></div>
                                    <div class="field03 newwidth" style="color:#48535a;"> Any product listing valid for 30 days </div>
                                    <div class="clr"></div>
                                    <div class="lable01 newwidth-lable01" >&nbsp;</div>
                                    <div class="field03 newwidth">
                                          <input name="" id="product_create_btn" type="submit" value="Update"  class="btn" />
                                          <input name="" type="button" value="Cancel"  class="btn" onclick="location.href='<?php echo base_url()?>etrade/manage-my-product'" />
                                    </div>
                                    <div class="clr"></div>
                              </div>
                               </form>
                          	</div>
                            
                        </div>
                    <!-- /left container -->
                        
            <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>





<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>



<script type="text/javascript">
	function selectShipping(val)
	{
		if(val==1)
		{
			$('#local').show();
			$('#international').hide();
		}
		else if(val==2)
		{
			$('#international').show();
			$('#local').hide();
		}
		else if(val==3)
		{
			$('#local').show();
			$('#local').show();
		}
	}
</script>
<!-- /lightbox SECTION -->
<!-- confirm delete album popup-->
<!-- end of delete pop up -->
