<div class="link-div">
    <ul>
        <li><a href="<?php echo base_url()?>etrade/manage-sent-request.html" <?=($swap_menu ==  1)?'class="current"':''?>><span class="nw-etrade">Buy Request Sent</span></a></li>
        <li><a href="<?php echo base_url()?>etrade/manage-my-product.html" <?=($swap_menu == 2)?'class="current"':''?>><span class="nw-etrade">My Products Listing</span></a></li>
        <li><a href="<?php echo base_url()?>etrade/manage-buy-request-received.html" <?=($swap_menu ==  3)?'class="current"':''?>><span class="nw-etrade">Buy Request Received</span></a></li>
    </ul>
    <div class="clr"></div>
</div>