

<div class="clr"></div>
<!-- CONTENT SECTION -->
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Reset Password</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container"> <?php #pr($posted);?>
                        <div class="arrow_btm"></div>
                        <form id="frm_rset_pwd"  method="post" action="<?=admin_base_url().'site_settings/reset_password.html'?>" enctype="multipart/form-data">
                        <div class="content_area frm_box">
                        <div class="blue_div"><?=show_msg('success_msg');?></div>
                              <div class="lable01"><span class="red-mark">* </span> Password:</div>
                              <div class="field01">
                                    <input name="txt_old_pwd" id="txt_old_pwd" type="password" value="<?=$posted['txt_old_pwd']?>" autocomplete="off" />
                              </div>
                              <?php $show_old_p_err = (form_error('txt_old_pwd'))?'style="display:block;"':''; ?>
                              <div class="error-message" <?=$show_old_p_err?>><?php echo form_error('txt_old_pwd'); ?></div>
                              <div class="clr"></div>
                              
                              <div class="lable01"><span class="red-mark">* </span> New Password: </div>
                              <div class="field01">
                                    <input name="txt_new_pwd" id="txt_new_pwd" type="password" value="<?=$posted['txt_new_pwd']?>" />
                              </div>
                              <?php $show_new_p_err = (form_error('txt_new_pwd'))?'style="display:block;"':''; ?>
                              <div class="error-message " <?=$show_new_p_err?>><?php echo form_error('txt_new_pwd'); ?></div>
                              <div class="clr"></div>
                              
                              <div class="lable01"><span class="red-mark">* </span> Confirm New Password: </div>
                              <div class="field01">
                                    <input name="txt_cnew_pwd" id="txt_cnew_pwd" type="password" value="<?=$posted['txt_cnew_pwd']?>" />
                              </div>
                              <?php $show_cnf_p_err = (form_error('txt_cnew_pwd'))?'style="display:block;"':''; ?>
                              <div class="error-message" <?=$show_cnf_p_err?>><?php echo form_error('txt_cnew_pwd'); ?></div>
                              <div class="clr"></div>
                              
                              <div class="lable01"> </div>
                              <div class="field01">
                                    <input name="" type="submit" class="btn"  value="Submit" />
                              </div>
                              <div class="clr"></div>
                        </div>
                        </form>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION --