<div>
            <div class="page_heading_full">
                  Search Result
            </div>
            <div class="project_box" style="border:0px;">
              <p class="blue_bold12"> <a href="javascript:void(0);">God is Everywhere</a></p>
              <p class="date-time"> HH:MM DD/MM/YYYY</p>
              <p>&nbsp;</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do  tempor
                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                    nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do  tempor  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                    nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do  tempor
                    incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat.</p>
               
               <p class="read-more">[<a href="my-blog.php">read more</a>]</p>
             </div>   
        
  </div>