<?php
	if( $this->session->userdata('loggedin') =='' || $this->session->userdata('loggedin')==false){
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
     }
     else{
         
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
 <?php  }?>
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
<div id="container">
  <div id="top_corner">&nbsp;</div>
  <div id="mid_content"> 
    <!-- latest news -->
    <?php #include(APPPATH ."views/layouts/latest_news.phtml");?>
    <!-- /latest news -->
    <div class="clr"></div>
    <!-- main container -->
    <div id="main_container"> 
      <!-- left container -->
     <?php include(APPPATH."views/layouts/leftbar.phtml");?>
      <!-- left container -->
      <div id="mid_container">
	  
        <div class="pd-box">
          <ul class="dp-list">
            <li><a href="javascript:void(0)" class="select"><?=$public_arr_profile_info['s_profile_name']?> <?=$view_name?></a></li>
           
			<li class="li-right"> 
            <form name="frm_preserve_search" method="post" enctype="multipart/form-data" action="<?=$_SERVER['HTTP_REFERER']?>">
                <input type="hidden" name="IS_PRESERVE_SEARCH" id="IS_PRESERVE_SEARCH" value="Y" />
                <input type="submit" class="yellow-btn" style=" background:none repeat scroll 0 0 #013D62;" name="reload_search" value="Back" />
            </form>
            </li>
          
          </ul>
          <br class="clr" />
        </div>
        <div class="prfile-list-main-box"> 
			<h1><?=$public_arr_profile_info['s_profile_name']?>  </h1>
             <?php  $relation_arr = CheckUserRelation($public_arr_profile_info['id']);	?>
			<span class="pro-offline">
			<?=check_user_online_hlpr($public_arr_profile_info['id'], 'public', $relation_arr); ?>
            </span>
			<br class="clr"/>
		
              <!--Profile start-->
              <div class="prfile-sec-content-box  select-display" >
                <h2>
                Profile
                </h2>
                <div class="profile-sml-sec">
                     <?php $img = get_profile_image_of_user( 'main',$public_arr_profile_info['s_profile_photo'],$public_arr_profile_info['e_gender']);?>
                                <div  class="prfile-sec-photo" style=" background:URL('<?=$img?>')no-repeat center;width:100px; height:100px;" title="member" ></div>
                                
                                <div class="prfile-sec-content-box-right">
                                    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="pro-table">
                                     <tr>
                                        <td valign="top" align="left"><span>Date of Birth: </span></td>
                                        <td valign="top" align="left"><?=($public_arr_profile_info['dt_dob'] != '0000-00-00')?getShortDate($public_arr_profile_info['dt_dob'],5):'';?></td>
                                      </tr>
                                      <tr>
                                        <td valign="top" align="left" ><span>Website:</span></td>
                                        <td valign="top" align="left"><a href="<?=$public_arr_profile_info['s_website']?>" target="_blank"><?=$public_arr_profile_info['s_website']?></a></td>
                                      </tr>
                                      <tr>
                                        <td valign="top" align="left" ><span>Profile URL:</span></td>
                                        <td valign="top" align="left"><a href="http://www.cogtime.com/<?=$public_arr_profile_info['s_profile_url_suffix']?>" target="_blank">www.cogtime.com/<?=$public_arr_profile_info['s_profile_url_suffix']?></a></td>
                                      </tr>
                                    </table>
                                 </div>
                      <br class="clear"/>
                  </div>
              </div>
		   	  <!--Profile start--> 
		
			  <ul class="profile-msg-send">
                                        	<?php if($own_profile == 'false'):?>
                                            <li><a class="send-pro-message" href="javascript:void(0);" <?php /*?>onclick="show_dialog('send_message_div');"<?php */?>>Send A Message</a></li>
                                           
											<?php  endif;
											
											if($if_already_friend == 'false') :?>
                                            	<li><a href="javascript:void(0);" id="invite_friend_<?=($public_arr_profile_info['id'])?>" onclick="invite_friend_('<?=encrypt($public_arr_profile_info['id'])?>')">Send Friend Request</a></li>
                                            <?php elseif($display_becomefriend == 'false'):?>
                                            	<li><a href="javascript:void(0);" id="invite_friend_<?=($public_arr_profile_info['id'])?>" onclick="invite_friend_('<?=encrypt($public_arr_profile_info['id'])?>')" >Re-send Friend Request</a></li>
                                            <?php endif; ?>
                                            
                                           <?php if($if_already_netpals == 'false') :?>
                                            	<li><a id="invite_netpal_<?= $public_arr_profile_info['id']?>"  href="javascript:void(0);" onclick="invite_netpals_(<?php echo $public_arr_profile_info['id'];?>)">Invite As Netpal</a></li>
                                            <?php elseif($display_becomenetpals == 'false'):?>
                                            	<li><a d="invite_netpal_<?= $public_arr_profile_info['id']?>"  href="javascript:void(0);" onclick="invite_netpals_(<?php echo $public_arr_profile_info['id'];?>)" >Reinvite As NetPal</a></li>
                                            <?php endif; ?>
                                            
                                             <?php ## prayer partner
											 if($is_hit_frm_pp){  
												 if($prayer_partner['display_becomeprayer_partner'] == 'false'): ?>
													<li> <a  href="javascript:void(0);" id="invite_prayer_partner_<?=($public_arr_profile_info['id'])?>" onclick="invite_prayer_partner_('<?=encrypt($public_arr_profile_info['id'])?>','<?=$prayer_partner['display_becomeprayer_partner']?>')">Re-send Partner Request</a></li>
												  
																								
											  <?php elseif($prayer_partner['display_alreadyprayer_partner'] == 'true'):?>
													<li><a href="javascript:void(0);"> Already Your Partner </a></li>
											  
											 
											 <?php elseif($prayer_partner['is_available']=='false') : ?>
													<li><a href="javascript:void(0);">Not Available as Partner</a></li>
													 
											  
											  <?php else: ?>
											 <li> <a  href="javascript:void(0);" id="invite_prayer_partner_<?=($public_arr_profile_info['id'])?>" onclick="invite_prayer_partner_('<?=encrypt($public_arr_profile_info['id'])?>','<?=$prayer_partner['display_becomeprayer_partner']?>')">Invite As Partner</a></li>
											  
											  <?php endif;
											 }
											  ?>
                                             
                                            
                                        </ul>
                    
          	  <div class="new-wl">
                        <div class="comments-number">
                                                          
                             <div class="comments-number-mid">
                              <div class="heading">
                                    <div class="left">
                                          <h4><img alt="" src="images/icons/cmnt2.png" height="20px" width="20px" class="cmnt" /> Send A Message</h4>
                                          <img src="images/minus-white.png" alt="" class="wal-minus" width="13" height="10"/>
                                    </div>
                        		</div>
                              <table width="100%" cellspacing="0" cellpadding="0" border="0" class="profile-msg-table" >
                                 <tr>
                                    <td valign="middle" align="left">To: </td>
                                    <td valign="top" align="left"><?=$public_arr_profile_info['s_profile_name']?></td>
                                  </tr>
                                  <tr>
                                    <td valign="middle" align="left">Subject: </td>
                                    <td valign="top" align="left"><input type="text" class="profile-txt-width"  id="subject" name="subject" /></td>
                                  </tr>
                                  <tr>
                                    <td valign="top" align="left">body:</td>
                                    <td valign="top" align="left"><textarea class="profile-txt-width"  name="message" id="message"></textarea></td> 
                                    
                                  </tr>
                                  <tr style="">
                                  <td valign="top" align="left">&nbsp;&nbsp;</td>
                                  <td class="error_msg" id="err_send_message" style=" margin-left:138px;"></td>
                                  </tr>
                                 
                                  <tr>
                                    <td></td>
                                    <td><input type="button"  class="yellow-btn" value="Send" onclick="send_message_from_public_profile()" /></td>
                                  </tr>
                                  <input type="hidden" id="recipent_id" value="<?=encrypt($public_arr_profile_info['id'])?>" />
                                </table>
                            </div>
                                                         
                        </div>
                    </div>
            
        <!-- All Friends  start-->
        <div class="profile-frd">
			<h4>All <?=$view_name?></h4>
			
		</div>
		<div class="pro-container">
			<div class="pro-slider-section text-aling-public-profile">
                <ul class="myphotosdisplay" ID ="friend_html" >
                <?=$friend_content?>
               
                </ul>
				<br class="clr"/>
				   
                  <?php if($no_of_result > $friend_pagination_per_page): ?>
                                    
                          <div class="view_more" id="show_more_div" style="clear:both;"><a href="javascript:void(0);" id="show_more_rec_link" page_value="<?=$current_page_1?>" onclick="show_more_rec($(this).attr('page_value'))" class="more-pro-view-all">[view more] </a> </div>
                          
                  <?php endif; ?>
                 
			</div>
		</div>
        <input type="hidden" value="<?=$i_profile_id?>"  id="i_user_id" />
		<!-- All Friends  end-->
        </div>
        
      </div>
      <!-- right container -->
      <?php include(APPPATH."views/layouts/rightbar.phtml");?>
      <!-- right container --> 
      
    </div>
    <!-- main container --> 
  </div>
  <div class="clr"></div>
</div>
</div>

<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?><!-- /FOOTER SECTION --> 

<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_rec(page) {
	
	var i_user_id = $('#i_user_id').val();
	var type  = '<?=$view_name?>';
	var s_url;
	if(type  ==  'Friends')
		s_url =  base_url+'public_profile/all_friends_ajax_pagination/'+i_user_id+'/'+page;
	else
		s_url =  base_url+'public_profile/all_netpals_ajax_pagination/'+i_user_id+'/'+page;
		
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: s_url,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#friend_html').append(data.html);
				$('#show_more_rec_link').attr('page_value', data.cur_page);
				$('#show_more_rec_link').attr('onclick','');
				$('#show_more_rec_link').attr('onclick','show_more_rec('+data.cur_page+')');
			}
			else {
				$('#friend_html').append('<li style="clear:both;"><p class="blue_bold12" style="text-align: center; width: 445px;font-size:14px;">No More <?=$view_name?>.</p></li>');
				$('#show_more_div').remove();
			}
			//alert(data.view_more);
            
            if(data.view_more==false)
            {
               
                $('#friend_html').append('<li style="clear:both;"><p class="blue_bold12" style="text-align: center; width: 445px;font-size:14px;" >No More <?=$view_name?>.</p></li>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}
</script>

<script type="text/javascript" src="<?= base_url() ?>js/switch.js"></script>