<?php

	include(APPPATH ."views/layouts/church_header.phtml");

?>

<!-- CONTENT SECTION -->
</div>
<div id="content_section" style="margin-top:8px;">

      <div id="container">

            <div id="top_corner">&nbsp;</div>

            <div id="mid_content">

                  <!-- left container -->

                  <div id="register_l">

                        <div class="frm_box" style="color: #26ae52;font-size: 17px">

                        	You have successfully registered. Please check your mail and activate your account.

                        	

                        </div>

                  </div>

                  <!-- /left container -->

                  <!-- right container -->
<!--
                  <div id="register_r">

                        <h1>Lorem ipsum dolor sit amet</h1>

                        <p>CoGTime Xtian Network aims to network Christians around the world.</p>

                        <p>As a centre point it is envisaged the site will help unite global communities and meet the needs of the less privileged by channeling provision from other societies around the world. </p>

                        <p>What you get from this site is:</p>

                        <ul class="list01 list04">

                              <li>Lorem ipsum dolor sit amet.</li>

                              <li>Consectetur adipisicing elit.</li>

                              <li>Sed do  tempor incididunt.</li>

                              <li>Ut labore et dolore magna aliqua.</li>

                        </ul>

                  </div>
-->
                  <!-- /right container -->

            </div>

            <div id="bot_corner">&nbsp;</div>

      </div>

      <div class="clr"></div>

</div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>

<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/church_footer.phtml");?>

<!-- /FOOTER SECTION -->







