<?php
	include(APPPATH ."views/layouts/church_header.phtml");
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); 
$open_time = json_decode($church_arr[0]->ch_open_time);
$close_time = json_decode($church_arr[0]->ch_close_time);
$special_note = json_decode($church_arr[0]->ch_special_note);
//pr($open_time);
//pr($close_time);exit;
//pr($ser_arr);
?>
</div>
<div class="container">
  <div class="church-left">
    <div class="church-service">
      <h3>Service Times</h3>
      <ul>
          <?php 
          if(!empty($ser_arr)){
              foreach ($ser_arr as $val){
			  $time_interval = '';
			  if($val->ch_service_week_day == 'Mon') { 
                                 $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_mon .=$stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Tue') { 
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_tue .=$stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Wed') {
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_wed .=$stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Thurs') { 
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_thurs .= $stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Fri') { 
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_fri .= $stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Sat') { 
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_sat .= $stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
			  if($val->ch_service_week_day == 'Sun') {
                               $stat_time = explode(':',$val->c_start_time);
                                
                                 $end_time = explode(':',$val->c_end_time);
				$time_interval_sun .=$stat_time[0].':'.$stat_time[1].' - '. $end_time[0].':'.$end_time[1].' , ';
			  }
		}
          ?>
       <?php if($time_interval_mon) { ?> <li> <?php  echo '<span class="time-label">'.'Mon : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_mon ,' , ').'</span>'; ?></li><?php } ?>
	<?php if($time_interval_tue) { ?>	<li> <?php echo '<span class="time-label">'.'Tue : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_tue ,' , ').'</span>'; ?></li><?php } ?>
		<?php if ($time_interval_wed) { ?><li> <?php echo '<span class="time-label">'.'Wed : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_wed ,' , ').'</span>'; ?></li><?php } ?>
		<?php if ($time_interval_thurs) { ?><li> <?php  echo '<span class="time-label">'.'Thurs : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_thurs ,' , ').'</span>'; ?></li><?php } ?>
		<?php if ($time_interval_fri) { ?><li> <?php echo '<span class="time-label">'.'Fri : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_fri ,' , ').'</span>'; ?></li><?php } ?>
        <?php if ($time_interval_sat) { ?>	<li> <?php echo '<span class="time-label">'.'Sat : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_sat ,' , ').'</span>'; ?></li><?php } ?>
	<?php if ($time_interval_sun) { ?>	<li> <?php echo '<span class="time-label">'.'Sun : '.'</span>'. '<span class="time-text">'.rtrim($time_interval_sun ,' , ').'</span>'; ?></li><?php } ?>
          <?php 
              }
               else{?> 
               <li>no service found</li>             
              <?php } ?>
       
      </ul>
    </div>
    <div class="church-time">
        <h3>Office Hours </h3>
<ul class="ch-notification">
	<?php foreach ($open_time As $openkey => $openval) { ?>
    <li><span class="office-hours-label"><?= $openkey; ?> :</span> <span class="office-hours-text"><?php if($openval == 'Closed') { ?> <?= $openval; ?> <? } else { ?> <?= $openval; ?> - <?= $close_time->$openkey;  } ?> <?php if($special_note->$openkey != '') { ?> (lunch <?=$special_note->$openkey;?> ) <?php } ?></span></li>
	<?php } ?>
    </ul>
	</div>
      
      <!--Church Address-->
      <div class="church-service">
      <h3><?= $church_arr[0]->s_name; ?></h3>
        <ul>
            <li> <span class="church-address-text">
                    <?= $church_arr[0] ->s_address ?><br>
           <?= get_city_name_by_id($church_arr[0] ->i_city_id).', '.get_state_name_by_id($church_arr[0] ->i_state_id) ?><br>
         
          <?= get_country_name_by_id($church_arr[0]->i_country_id) ?></span></li>	
            <li> <span class="time-label">Tel : </span><span class="time-text"><?= $church_arr[0]->s_phone ?></span></li>				
            <li> <span class="time-label">Email : </span><span class="time-text"><a href="mailto:<?= $church_arr[0]->ch_email ?>"><?= $church_arr[0]->ch_email ?></a> </span></li>        
            <li> <span class="time-label">Web: </span><span class="time-text"><a href="<?= $church_arr[0]->ch_url ?>" target="_blank"><?= $church_arr[0]->ch_url ?></a></span></li>	                 
      </ul>
    </div>
      <!--Church Address end-->

  </div>
  <div class="church-right">
    <h3><?= $church_arr[0]->w_heading; ?> <?= $church_arr[0]->s_name; ?> 
         <?php
          
        if($this->session->userdata('loggedin')!= '1'){ 
        ?>
        <a href="<?php echo base_url().'church_registration/'.$church_arr[0]->id?>">Join Now</a>
    
        <?php }else{
            if(!empty($_GET['member_id'])){
            ?>

 <a href="javascript:void(0)" onclick="send_inv(<?=$_GET['member_id'] ?>,<?= $church_arr[0]->id ?>);">Join Now</a>
    
          <?php
            }
          
            } ?>
    </h3>
      <p class="church-address-text02">
10 Johnson Way
London, England
United Kingdom
  <br>
Tel : +442086582213<br>
Email : <a href="mailto:robaghadiuno@hotmail.com ">robaghadiuno@hotmail.com </a>
</p>
    <p><?= $church_arr[0]->w_des; ?> </p>
     <ul class="church-gallery">
        <?php
                 $img1 = get_church_land_image1($church_arr[0]->id, 'main', $church_arr[0]->img1);
                 $img2 = get_church_land_image2($church_arr[0]->id, 'main', $church_arr[0]->img2);
                 $img3 = get_church_land_image3($church_arr[0]->id, 'main', $church_arr[0]->img3);
                 $img4 = get_church_land_image4($church_arr[0]->id, 'main', $church_arr[0]->img4)
                 ?>
              <?php 
              if(!empty($church_arr[0]->img1)){
              
              ?>
        <li style="background:url(<?= $img1 ?>) top center no-repeat;"><?php if(!empty($church_arr[0]->img1_des)) { ?><span><?php  echo $church_arr[0]->img1_des;  ?></span><?php } ?></li>
         <?php
              }
              if(!empty($church_arr[0]->img2)){
         ?>
      <li style="background:url(<?= $img2 ?>) top center no-repeat;" class="noRightMargin"><?php  if(!empty($church_arr[0]->img2_des)){ ?><span> <?php  echo $church_arr[0]->img2_des;  ?></span><?php } ?></li>
      <?php
              }
              if(!empty($church_arr[0]->img3)){
              
      ?>
      <li style="background:url(<?= $img3 ?>) top center no-repeat;"><?php if(!empty($church_arr[0]->img3_des)){ ?><span><?php echo $church_arr[0]->img3_des;  ?></span><?php } ?></li>
      <?php
              }if(!empty($church_arr[0]->img4)){
      ?>
      <li style="background:url(<?= $img4 ?>) top center no-repeat;" class="noRightMargin"><?php if(!empty($church_arr[0]->img4_des)){ ?><span> <?php echo $church_arr[0]->img4_des;  ?></span><?php } ?></li>
      <?php 
              }
      ?>
    </ul>
  </div>
  <div class="clear"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


  <script type="text/javascript">
        function send_inv(member_id,church_id){
     showBusyScreen();
    // var base_url = ;
        $.ajax({
                    type: "POST",
                    url: base_url + "base_controller/send_member_inv/",
                    data: { 'member_id':member_id ,'church_id':church_id },
                    dataType: 'json',
                    success: function(data,msg) {
                         //alert(JSON.stringify(data));
                         //alert(data.msg)
                        if(data.msg == 'error'){
                            showUIMsg("You already send join request , waiting for church admin approval");
                            window.location.href='<?= base_url().'find-church.html'  ?>';
//                            $('#err_email').css('display','block').html('Email id already exists.')
//                            $('#success_ch_req').css('display','none');
                        }else if(data.msg == 'ok'){
                            //showUIMsg("Send join request successfully...");
							showUIMsg("Join request sent successfully...");
                            $('#send_inv_mem').css('display','none');
                               window.location.href='<?= base_url().'find-church.html'  ?>';
//                             $('#church_reg_new').slideUp();
//                             $('#success_ch_req').slideDown();
                        }
                        hideBusyScreen();
                        

                        

                    }
                });
}
        
        </script>