<?php
	include(APPPATH ."views/layouts/header.phtml");
?>
<!-- CONTENT SECTION -->
<div id="content_section" style="margin-top:8px;">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- left container -->
                  <div id="register_l">
                        <h1> Forget Password</h1>
                        
                        <?php if($success_msg  != '') { ?>
                        <h1 style=" margin-top:35px; font-size:16px;"><?=$success_msg?></h1>
                        <?php } else{ ?>
                        
                        <div class="frm_box">
                        <form name="frm" id="frm"  method="post" action="<?=base_url()?>forgot-password.html" enctype="multipart/form-data">
                              <div class="lable01">Email:</div>
                              <div class="field01">
                                    <input name="txt_email" id="txt_email" type="text" value="<?=$posted['txt_email']?>"  />
                                    <?php if(form_error('txt_email') != ''){ echo form_error('txt_email');} ?>
                                    <?php if($email_err_msg != '') { echo '<div class="error_massage" style="display:block;">'.$email_err_msg.'</div>'; }?>
                              </div>
                              <div class="clr"></div>
             
                              <div class="lable01">Captcha:</div>
                              <div class="field01" style="padding-top:3px;">
                                    <p> Type the characters you see in the picture below:</p>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">&nbsp;</div>
                              <div class="field01">
                               <p><!--<img src="images/captcha.png" alt="" />-->
                                    <?php
									echo $captcha["image"];
								?>	</p>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">&nbsp;</div>
                              <?php /*?><div class="field01">
                                    <input name="txt_" type="text"  />
                              </div><?php */?>
                              <div class="field01"> 	
							   <input type="hidden" id="ssc" name="ssc" value="<?=encrypt($captcha["word"]);?>" />
                               <input type="text" id="security_code" name="security_code" />
                               <?php if($captcha_err != ''){ ?>
									 <div class="error_massage" ><?php echo $captcha_err; ?></div> <?php } ?>
                           	  </div>
                              <div class="clr"></div>
                             
                                                        
                              <div class="lable01">&nbsp;</div>
                              <div class="field01">
                                    <input name="" type="submit" value="Submit"  class="btn"/>
                              </div>
                              <div class="clr"></div>
                              
                              </form>
                        </div>
                        <?php }?>
                  </div>
                  <!-- /left container -->
                  <!-- right container -->
                  <div id="register_r">
                        <h1>Lorem ipsum dolor sit amet</h1>
                        <p>CoGTime Xtian Network aims to network Christians around the world.</p>
                        <p>As a centre point it is envisaged the site will help unite global communities and meet the needs of the less privileged by channeling provision from other societies around the world. </p>
                        <p>What you get from this site is:</p>
                        <ul class="list01 list04">
                              <li>Lorem ipsum dolor sit amet.</li>
                              <li>Consectetur adipisicing elit.</li>
                              <li>Sed do  tempor incididunt.</li>
                              <li>Ut labore et dolore magna aliqua.</li>
                        </ul>
                  </div>
                  <!-- /right container -->
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->

<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->