<?php
 	include(APPPATH ."views/layouts/header.phtml");
	
	# include banner file...
	include(APPPATH ."views/layouts/banner.phtml");
?>

<!-- CONTENT SECTION  A-->
<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
    	<!--know about cogtime start -->
    	<div class="know-about">
        	<h2>Know About Cogtime</h2>
            <!--container -->
            <div class="know-about-container">
            
            <?php  $VID_IMG = base_url()."uploads/hp_cms_video/".getThumbName($hp_cms_content['s_video_image_2'],'bigthumb'); ?>
                  
                  <div class="cogtime-video" id="myvideo_first_thumb" style="background:url() no-repeat center;" i_media_id="<?=$i_media_id?>"></div>
                <div  id="myvideo_big_thumb_1" media_id="<?=$hp_cms_content['id']?>">
                	 <?php /*?><img src="images/play-icon.png" id="play_video" alt="Play" class="play-icon" /><?php */?>
               </div> 
            
            
            <p><?php echo nl2br($hp_cms_content['s_content_1']);?></p>
            </div>
            <!--container end -->
        </div>
    	<!--know about cogtime end -->
        
        <!--upcoming events -->
        <div class="upcoming-events">
        <h2>Upcoming Events</h2>
        <!--container -->
        <div class="upcoming-events-container">
        	<ul>
            	<?php
						if(count($hp_events) > 0)
						{
							foreach($hp_events as $val){
								$title = my_substr(html_entity_decode(htmlspecialchars_decode($val['s_title']),ENT_QUOTES,'utf-8'), 68);
								$desc = my_substr(html_entity_decode(htmlspecialchars_decode($val['s_desc']),ENT_QUOTES,'utf-8'), 74);
								$detail_url = get_events_detail_url($val['id']);
								
								$IMG_THUMB_PATH = base_url() ."uploads/events_photo/";
								$name=getThumbName($val['s_image_1'],'thumb'); 
								$IMG_THUMB = $IMG_THUMB_PATH . $name;
				?>
            
            					<li><img src="<?=$IMG_THUMB?>" alt="prayer meeting" />
                    <div class="events-container-inside">
                        <p class="title"><a href="javascript:void(0);" onclick="show_dialog('event<?= $val['id']?>')"><?=$title?></a></p>
                        <p class="date" style="color:#000 !important; font-size:13px;"><?=getShortDate($val['dt_start_time'], 9)?></p>
                        <p><?=$desc?></p>
                    </div>
                </li>
                <!---------------------------------event pop up----------------------------------->
                 <div class="lightbox event<?= $val['id']?>" style="width: 400px; left: 100px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><?=$title?></h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949; font-size:16px; text-align:center;">
                  <!-----contain start---->
                  <span><img src="<?=$IMG_THUMB?>" alt="event" /></span>
               <h1><?=$title?></h1>
               <span>Created On: <?=$val['dt_created_on'] ?></span>
               <span>Venue: <?= $val['s_address']. ', ' . $val['s_city'] . ', ' . $val['s_state'] . ', ' . get_country_name_by_id($val['i_country_id']); ?></span>
               <span>Details :<?= $desc; ?></span>
               
               

               <span>Time: <?=$val['dt_start_time'] ?></span>
                 <!--right part -->
                        <div class="pre-time-map">                               


                            

                                    <?php 
                                    //$add =  $address = str_replace(" ", "+", $val['s_address']);
                                    $address =  $val['s_city'] . '+' . $val['s_state'] . '+' . get_country_name_by_id($val['i_country_id']).'+'.$val['s_postcode'];
                                    $reg = get_country_name_by_id($val['i_country_id']);
$url = "http://maps.google.com/maps/api/geocode/json?address=$address&sensor=false&region=$reg";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_PROXYPORT, 3128);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
$response = curl_exec($ch);
curl_close($ch);
$response_a = json_decode($response);
 $lat = $response_a->results[0]->geometry->location->lat;

 $long = $response_a->results[0]->geometry->location->lng;
                                     // echo $mapshow->printGMapsJS();
                                     // echo $mapshow->showMap(false); 
                                    ?>
                            <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
                            <script type="text/javascript">
                            var map;
function initialize() {
  var mapOptions = {
    zoom: 16, 
    center: new google.maps.LatLng(<?= $lat ?>, <?= $long ?>)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
}

google.maps.event.addDomListener(window, 'load', initialize);
                            
                            </script>
                            <div id="map-canvas">
                                
  
                            </div>
                                </div>
                               <?php// } ?>
                        </div>
                        <!--/right part -->
               </p>
               </div>
               <form action="" method="post" id="delfrm">
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
<!--                 <input name="" type="button" value="Yes" class="post-btn" style="margin-left:105px;" onClick="delete_service(<?= $val->id ?>)"/>
                 <input name="" type="button" value="No" class="cancel-btn" onclick="hide_dialog()"/>-->
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
                <!-------------------------------------------------------------------------------------->
                <?php 
						 }
					  }
					  else{
						  
						  echo '<div style="margin-top:125px; margin-left:95px;"><p>No Upcoming Events.</p></div>';
					  }
				
				?>
            </ul>
           <?php 
		   if(count($hp_events) > 0){
		   ?> 
            <a href="<?=base_url().'upcoming-events.html'?>" class="view-all" style="color:#000;">view all..</a>
            <?php }?>
        </div>
        <!--container end -->
        </div>
        <!--upcoming events end -->
        
        <!--what people say start-->
        <div class="people-say">
        	<h2>What People Say!</h2>
            <div class="people-say-container">
                  <?php  $VID_IMG = base_url()."uploads/hp_cms_video/".getThumbName($hp_cms_content['s_video_image'],'bigthumb'); ?>
                  
                  <div class="cogtime-video" id="myvideo_thumb" style="background:url() no-repeat center;" i_media_id="<?=$i_media_id?>"></div>
                <div  id="myvideo_big_thumb" media_id="<?=$hp_cms_content['id']?>">
                	 <?php /*?><img src="images/play-icon.png" id="play_video" alt="Play" class="play-icon" /><?php */?>
               </div> 
             
               <?php /*?> <iframe frameborder="0" width="338" height="190" src="<?= $hp_cms_content['s_video_url'] ?>"></iframe><?php */?>
               <p> <?php echo  nl2br($hp_cms_content['s_content_2']);?></p>
            </div>
        </div>
        <!--what people say end -->
    </div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>

<!-- /CONTENT SECTION -->
  
  
<?php
	include(APPPATH ."views/layouts/footer.phtml");
?>

<!--videos posts  -->      
<script language="javascript">
  $(document).ready(function() {

  $('#myvideo_big_thumb').click(function(){
	showLoading();
	var media_id = $('#myvideo_big_thumb').attr('media_id');
	//alert(media_id);
	$.ajax({
		  type: 'post',
		  url:base_url+'index/get_media/',
		  data: ({'media_id' : media_id ,'width':329 ,'height':190}),
  
		  dataType: 'json',
		  success: function (data, status) {
			  if(data.result=='success') {
				  hideLoading();
				  //alert(data.i_media_id);
				  //alert(data.s_image_source.html);
				 $('#myvideo_thumb').html(data.s_image_source.html);
				 $('#myvideo_thumb').attr('i_media_id',data.i_media_id);
			  }
			  
			  
		  },
		  error: function (data, status, e) {
			  hideLoading();
			  showUIMsg('Some error occurred. Please try again.');
			  
		  }
	  });
	
  
  });
  
  $('#myvideo_big_thumb_1').click(function(){
	showLoading();
	var media_id = $('#myvideo_big_thumb_1').attr('media_id');
	//alert(media_id);
	$.ajax({
		  type: 'post',
		  url:base_url+'index/know_about_cogtime_video/',
		  data: ({'media_id' : media_id ,'width':310 ,'height':190}),
  
		  dataType: 'json',
		  success: function (data, status) {
			  if(data.result=='success') {
				  hideLoading();
				  //alert(data.i_media_id);
				  //alert(data.s_image_source.html);
				 $('#myvideo_first_thumb').html(data.s_image_source.html);
				 $('#myvideo_first_thumb').attr('i_media_id',data.i_media_id);
			  }
			  
			  
		  },
		  error: function (data, status, e) {
			  hideLoading();
			  showUIMsg('Some error occurred. Please try again.');
			  
		  }
	  });
	
  
  });
  
 $('#myvideo_big_thumb').trigger('click');
 $('#myvideo_big_thumb_1').trigger('click');
  
  });
</script>
<script type="text/javascript" src="<?= base_url() ?>js/lightbox.js"></script>
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />

<!--videos posts  -->	