<?php
	include(APPPATH ."views/layouts/header.phtml");
?>
<!-- CONTENT SECTION -->
<div id="content_section" style="margin-top:8px;">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- left container -->
                  <div id="register_l">
                      <?php if($_GET['findch'] != 1) { ?>
                        <h1> Register Now - It’s  FREE </h1>
                      <?php } if($_GET['findch'] == 1) { ?>
                        <h1> Register your Church </h1>
                      <?php } ?>
                        <!--14-01-2015 church registration-->
                        <!--today-->
                      
                        <span class="church-register-main"  <?php
                      if($_GET['findch'] == 1) { 
                          ?> style="display: none" <?php } ?>>
                           
                            
                            <input type="radio" name="reg" value="cogtime" checked="" class="chk" style="display: none;"> Register as a member  &nbsp;
                            <input type="radio" id="chrch_reg" name="reg" value="church" class="chk" style="display: none;" <?php if($_GET['findch'] == 1) { ?> checked=""  <?php } ?> >  
                                
                       
                        </span>
                       
                        
                        <script type="text/javascript">
                        $(document).ready(function(){
                            $('.chk').click(function(){
                                var chkVal = $(this).val();
                                if(chkVal == 'cogtime'){
                                 $('#cogtime_registration').css('display','block');
                                 $('#church_reg').css('display','none');
                                }
                                if(chkVal == 'church'){
                                    $('#church_reg').css('display','block');
                                     $('#cogtime_registration').css('display','none');
                                     if($('.advance-search-panel').is(':visible')){
                                         $('.advance-search-panel').css('display','none');
                                     }
                                }
                                //alert(chkVal);
                                
                            });
                            
                            
                        });
                        </script>
                        
                        <div class="frm_box" id="cogtime_registration">
                        
                        
                        	<form name="frm_registration" id="frm_registration"  method="post" action="<?=base_url()?>register.html" enctype="multipart/form-data">
                        
                              <div class="lable01">Title:</div>
                              <div class="field01">
                                    <select name="title" id="title" style="width:100px;">
                                          <option value="-1" >Select</option> 
                                          <option value="Mr" <?php echo $selected =($posted["title"]=='Mr')?'selected':''?>>Mr.</option>
                                          <option value="Mrs" <?php echo $selected =($posted["title"]=='Mrs')?'selected':''?>>Mrs.</option>
                                          <option value="Ms" <?php echo $selected =($posted["title"]=='Ms')?'selected':''?>>Ms.</option>
                                    </select>
                                    <script type="text/javascript">
                                    $(document).ready(function(arg) {
                                        $("#title").msDropDown();
                                        $("#title").hide();
                                    })
                                </script>
                                <?php if($error_title != '') {?>
                                <div class="error_massage" style="display:block;clear:both;"><?php echo $error_title; ?></div>
                                <?php }?>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">First Name:</div>
                              <div class="field01">
                                    <input name="txt_first_name" id="txt_first_name" type="text" value="<?=$posted['txt_first_name']?>"/>
                                    <?php if(form_error('txt_first_name') != ''){ ?><?php echo form_error('txt_first_name'); }?>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">Last Name:</div>
                              <div class="field01">
                                    <input name="txt_last_name" id="txt_last_name" type="text" value="<?=$posted['txt_last_name']?>"/>
                                    <?php if(form_error('txt_last_name') != ''){ echo form_error('txt_last_name'); } ?>
                              </div>
                              <div class="clr"></div>
                              
                               <div class="lable01">Chat/Chitter Name:</div>
                              <div class="field01">
                                    <input name="txt_chat_display_name" id="txt_chat_display_name" type="text" value="<?=$posted['txt_chat_display_name']?>" maxlength="10"/>
                                    <?php if(form_error('txt_chat_display_name') != ''){ echo form_error('txt_chat_display_name'); }
									if($error_chatname != '' && form_error('txt_chat_display_name') == '')
									{
										echo '<div class="error_massage" style="clear:both;">'.$error_chatname.'</div>';
									}
									?>
									<p>Your chat name must contain atleast 1 digit and 1 letter.</p>
                              </div>
                              <div class="clr"></div>
                              
                              <div class="lable01">Gender:</div>
                              <div class="field01">
                                    <select name="gender" id="gender" style="width:100px;">
                                          <option value="-1">Select</option>  
                                          <option value="M" <?php echo $selected =($posted["gender"]=='M')?'selected':''?>>Male</option>  
                                          <option value="F" <?php echo $selected =($posted["gender"]=='F')?'selected':''?>>Female</option>
                                    </select>
                                    <script type="text/javascript">
                                    $(document).ready(function(arg) {
                                        $("#gender").msDropDown();
                                        $("#gender").hide();
                                    })
                                </script>
                                 <?php if($error_gender != ''){  echo '<div class="error_massage" style="clear:both;">'.$error_gender.'</div>'; }?>
                              </div>
                             
                              <div class="clr"></div>
                              <div class="lable01">Email:</div>
                              <div class="field01">
                                    <input name="txt_email"  id="txt_email" type="text" value="<?=$posted['txt_email']?>"   />
                                    <?php if(form_error('txt_email') != ''){  echo form_error('txt_email');} ?>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">Password:</div>
                              <div class="field01">
                                    <input name="txt_password" id="txt_password" type="password" value="<?=$posted['txt_password']?>" autocomplete ="off" />
                                    <?php // if(form_error('txt_password') != ''){ echo form_error('txt_password'); }?>
                                    <?php  if($error_password != ''){  ?>
                                       <div class="error_massage"><?php echo $error_password; ?></div><?php } ?>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">Confirm Password:</div>
                              <div class="field01">
                                    <input name="txt_cpassword" id="txt_cpassword" type="password" value="<?=$posted['txt_cpassword']?>"/>
                                    <?php //if(form_error('txt_cpassword') != ''){ echo form_error('txt_cpassword');} ?>
                                       <?php  if($error_cpassword != ''){  ?>
                                       <div class="error_massage"><?php echo $error_cpassword; ?></div><?php } ?>
                                    
                              </div>
                              
                              <div class="clr"></div>
                              <div class="lable01">Date of Birth:</div>  
                               <div class="field01">
                                       
                                           <?php
                                          # getting day-month-yr extracted from db DOB...
										// if($arr_profile_info['dt_dob'] != '0000-00-00'){
                                          $DOB_TSTAMP = time();
                                          $DOB_DAY = date( "j", $DOB_TSTAMP );
                                          $DOB_MONTH = date( "n", $DOB_TSTAMP );
                                          $DOB_YR = date( "Y", $DOB_TSTAMP );
										  
                                      ?>
                                      
                                          <select name="day" id="day"  style="width:50px; margin-right:2px;" autocomplete="off">
                                              <option   value="-1">---</option>
											  
                                            <?= makeOptionDay($posted['day']) ?>
                                             
                                          </select>
                                          
                                          <select name="month" id="month"  style="width:90px; margin-right:2px;">
                                                <option value="-1">---</option>
                                                <?= makeOptionMonth($posted['month']) ?>
                                          </select>
                                          
                                          <select name="year" id="year"  style="width:70px;">
                                                <option value="-1">---</option>
                                                <?= makeOptionDobYear($posted['year']) ?>
                                          </select> 
                                             <?php// echo form_error('dob'); ?>
                                         <?php  if($dob != ''){  ?>
                                       <div class="error_massage"><?php echo $dob; ?></div><?php } ?>
                                        
                                        </div> 
                              
                             
                              <div class="clr"></div>
							  <div class="lable01">Languages I Speak:</div>  
							<div class="field01">
							<select name="txt_lang" id="txt_lang" style="width:212px;">
								<option value="-1">---</option>
								<?php echo makeNetpalLanguage($posted['s_language']);?>
							  </select>
							  <?php if($txt_lang != ''){?>
							<div class="error_massage"><?php echo $txt_lang; ?></div>
							<?php }?>
							</div> 
							<div class="clr"></div>
                              <div class="lable01">Time Zone:</div>
                              <div class="field01">
                                    <select name="time_zone" id="time_zone" style="width:312px;" onchange="get_time_text()">
                                          <option value="-1">Select</option>
                                          <?= makeOptionTimezones($posted['time_zone']) ?>
                                          
                                    </select>
                                   
                                    <script type="text/javascript">
                                    $(document).ready(function(arg) {
                                        $("#time_zone").msDropDown();
                                        $("#time_zone").hide();
                                    });
									function  get_time_text()
										{
										var text=$('#time_zone option:selected').text();
										$('#time_text').val(text);
										}
                                </script>
                                <input type="hidden" value="" id="time_text" name="time_text">
                           <?php  if($error_zone != ''){  ?>
						   <div class="clr"></div>
                           <div class="error_massage"><?php echo $error_zone; ?></div><?php } ?>
                              </div>
                              <div class="clr"></div>
                             
                              <div class="lable01">Captcha:</div>
                              <div class="field01" style="padding-top:3px;">
                                    <p> Type the characters you see in the picture below:</p>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">&nbsp;</div>
                              <div class="field01">
                               <p><!--<img src="images/captcha.png" alt="" />-->
                                    <?php
									echo $captcha["image"];
								?>	</p>
                              </div>
                              <div class="clr"></div>
                              <div class="lable01">&nbsp;</div>
                              <?php /*?><div class="field01">
                                    <input name="txt_" type="text"  />
                              </div><?php */?>
                              <div class="field01"> 	
							   <input type="hidden" id="ssc" name="ssc" value="<?=encrypt($captcha["word"]);?>" />
                               <input type="text" id="security_code" name="security_code" />
									 <?php //if(form_error('security_code') != '') { echo form_error('security_code');} ?>
									<div class="error_massage"><?php echo $error_ssc; ?></div>
                           	  </div>
                              <div class="clr"></div>
                          
                                                         
                              
                              <div class="lable01">&nbsp;</div>
                              <div class="field01">
                                 <input name="txt_terms_cond"  id="txt_terms_cond" type="checkbox"  value="1" <?=($posted["txt_terms_cond"]== 1)?'checked="checked"':''?>/>
                                    Accept <a href="javascript:void();" class="blue_link"  onclick="return show_dialog('terms_condition')">Terms & Conditions</a> & <a href="javascript:void();" class="blue_link"  onclick="return show_dialog('privacy_policy')">Privacy Policy </a>
                                  <?php  if($error_terms_cond != ''){  ?>
                           <div class="error_massage"><?php echo $error_terms_cond; ?></div><?php } ?>  
                                  </div>
                              <div class="clr"></div>
                              <div class="lable01">&nbsp;</div>
                              <div class="field01">
                               		<input type="hidden" name="is_submitted" id="is_submitted" value="Y"  />
                                    <input name="btn_submit" type="submit" value="Sign Up!"  class="btn"/>
                              </div>
                              <div class="clr"></div>
                            </form>
                        </div>
                        <!-- church req 14-01-2015-->
                         <!-- church registration- today-->
                        <div class="frm_box" style="display: none;" id="church_reg">
                            <span>

                                   

                                Find Your church<span><img src="images/church-info.png" alt="Church" style="display: none"></span>

                                </h1>
                                <input type="text" name="ch_email" id="ch_email" placeholder="Enter church email id" >
                               
                              <input type="button" name="find" value="Find church" onclick="church_find();"   class="sml_btn" style="line-height: 23px; height: 23px;"><!--<input type="button" class="advc-search" value="Advance" onclick="advance_search()">-->
                                <br> <a class="tooltip3 adv-ch-srch" href="javascript:void(0)"  onclick="advance_search()">Advanced Search
                                <span>
                                   Please enter a church email address or click Advanced to enter the church name and location
                            </span>
                                </a>
                                <div class="error_txt" id="mail_error">
                                    
                                </div>
                            </span>
                            <script type="text/javascript" >
                                function church_find(){
                                   
                                var email_id = $('#ch_email').val();  
                                 var chkeml=email_id.match(/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/);
                                     if(email_id == ''){
                                         $('#mail_error').css('display','block').html('Please enter church email id');
                                         
                                     }else if(chkeml==null){
                                          $('#mail_error').css('display','block').html('Please enter valid church email id');
                                     }
                                //alert(email_id);
                                else {
                                    showBusyScreen();
                                    $('#mail_error').css('display','none');
                                    $.ajax({
          url : base_url+'base_controller/find_church_by_email',
          type : 'post',
          data : ({'email_id' : email_id,}),
          success : function(data)
          {
              hideBusyScreen();
              //alert(data)
              $('#table_contents').html(data);
          //window.location.href="<?= admin_base_url() ?>help_center/help_center";
          }
      }); 
                                }
                                }
                                function advance_search(){
                                $('#church_reg').slideUp();
                                $('.advance-search-panel').slideDown();
                                }
                            </script>
                            <div id="table_contents"></div>
                        </div>
                         <div class="advance-search-panel" style="display: none">
                             <!--<span><a href="javascript:void(0)" onclick="normal_search()" class="normal_srch">Normal Search</a></span>-->
                             <div class="frm_box adv-new">
                                 <h1 style="font-size: 15px; padding-bottom: 42px; font-weight: bold;"><span class="find-txt">Find a church</span>
                             </h1>
							 <span>
                                   Please enter a church email address or click Advanced to enter the church name and location
                            </span>
							
                                 <div class="clr"></div>
                                 <div class="pull-right-close"><a style="right: -4px;top: -46px;" href="javascript:void(0);" onclick="normal_search()"><img src="images/close.png" alt="Church"></a></div>
                           <span>Church Name:</span>
                                <input type="text"  name="txt_name_church" id="txt_name_church" />
                                <span class="error_massage" id="churherror1"></span>
                                <div class="clr"></div>
                                <!--new added-->
                                

                                <span>Address:</span>
                                <input type="text"  name="txt_address_church" id="txt_address_church" />
                                <span class="error_massage" id="churherror2"></span>
                                <div class="clr"></div>

                                <span> Postcode:</span>
                                <input type="text" name="txt_postcode_church" id="txt_postcode_church" />
                                <span class="error_massage" id="churherror3"></span>
                                <div class="clr"></div>

                              
                               

                                <div class="lable-form-nw"> 
                                    <input style="margin-left: 101px;" type="button" class="yellow-btn register-your-float-right click-church" value="Search"  onclick="search_advance_church()" />

                                </div>
                               
                                <div class="clr"></div>
                           
                        </div>
                         </div>
                         <script type="text/javascript">
                         function normal_search(){
                               $('#church_reg').slideDown();
                                $('.advance-search-panel').slideUp();
                                 $('#table_contents_adv').slideUp(); 
                         }
                         function search_advance_church(){
                             
                             var txt_name_church = $('#txt_name_church').val();
                             var txt_address_church = $('#txt_address_church').val();
                             var txt_postcode_church = $('#txt_postcode_church').val();
                             if(txt_name_church.trim() == ''){
                                 $('#churherror1').css('display','block').html('Enter church name');
                                 var flag1 = 1;
                             }else{
                                 $('#churherror1').css('display','none');
                                 var flag1 = 0;
                             }
                             if(txt_address_church.trim() == ''){
                                  $('#churherror2').css('display','block').html('Enter church address');
                                 var flag2 = 1; 
                             }
                             else{
                                  $('#churherror2').css('display','none');
                                 var flag2 = 0; 
                             }
                             if(txt_postcode_church.trim() == ''){
                               $('#churherror3').css('display','block').html('Enter church postal code');
                                 var flag3 = 1;    
                             }
                             else{
                                 $('#churherror3').css('display','none');
                                 var flag3 = 0;   
                             }
                             if(flag1 == 0 && flag2 == 0 && flag3 == 0){
                                 showBusyScreen(); 
                                 $.ajax({
          url : base_url+'base_controller/church_advace_search',
          type : 'post',
          data : ({'txt_name_church' : txt_name_church, 'txt_address_church': txt_address_church ,'txt_postcode_church':txt_postcode_church }),
          success : function(data)
          {
              hideBusyScreen();
              //alert(data)
               $('#table_contents_adv').slideDown(); 
              $('#table_contents_adv').html(data);
          //window.location.href="<?= admin_base_url() ?>help_center/help_center";
          }
      }); 
                             }
                         }
                         
                         </script>
                          <div id="table_contents_adv"></div>
                  </div>
                  <!-- /left container -->
                  <!-- right container -->
                  <div id="register_r">
                        <h1>Lorem ipsum dolor sit amet</h1>
                        <p>CoGTime Xtian Network aims to network Christians around the world.</p>
                        <p>As a centre point it is envisaged the site will help unite global communities and meet the needs of the less privileged by channeling provision from other societies around the world. </p>
                        <p>What you get from this site is:</p>
                        <ul class="list01 list04">
                              <li>Lorem ipsum dolor sit amet.</li>
                              <li>Consectetur adipisicing elit.</li>
                              <li>Sed do  tempor incididunt.</li>
                              <li>Ut labore et dolore magna aliqua.</li>
                        </ul>
                  </div>
                  <!-- /right container -->
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->

<div class="lightbox terms_condition" style="width:700px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" height="24" width="24" alt="close" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><h4>Terms & Conditions</h4></div>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit odio, pulvinar eu tincidunt id, tincidunt eu mauris. Aliquam ac tortor massa, sit amet interdum libero. Pellentesque arcu est, venenatis ut convallis nec, sollicitudin eget nisl. Suspendisse hendrerit luctus nibh, quis faucibus arcu pretium sit amet. Pellentesque dui enim, imperdiet in accumsan eu, interdum sed neque. Quisque vitae magna eget metus ultricies facilisis. Donec malesuada sagittis fringilla. Phasellus blandit nisi congue urna vestibulum adipiscing.</p>
<p>&nbsp;</p>
<p>Suspendisse sit amet eleifend urna. Vivamus accumsan suscipit mauris, et molestie nisi lobortis sed. Donec fringilla blandit nunc eu euismod. Mauris leo arcu, suscipit nec vulputate pretium, feugiat id mauris. Duis quis ante eget metus blandit cursus. Morbi cursus euismod facilisis. Pellentesque semper accumsan mi a pretium. Nunc a dolor erat, eu tristique ipsum. Suspendisse potenti. Vestibulum condimentum, est non condimentum interdum, nisi lorem tempus lorem, eget posuere sapien arcu sit amet ligula. Nulla neque enim, egestas id lacinia nec, rutrum id lorem.</p>
<p>&nbsp;</p>
<p>Morbi eu neque in arcu aliquet dapibus. Pellentesque quis dignissim risus. Quisque posuere consectetur mi, ullamcorper faucibus justo iaculis et. Integer aliquet placerat porta. Morbi vitae leo augue, lacinia iaculis leo. Donec varius bibendum bibendum. Quisque nibh velit, sagittis laoreet congue quis, rhoncus a metus. Proin vel risus purus. Pellentesque posuere aliquet lectus nec adipiscing. Aenean eget iaculis sem. Nulla id blandit ligula.</p>
<p>&nbsp;</p>
<p>Integer auctor purus at arcu convallis feugiat. Nullam a est a ante adipiscing pretium nec nec quam. Etiam sed orci vitae neque adipiscing pellentesque et non sem. Vestibulum pellentesque tellus vel magna tempus vel adipiscing turpis mollis. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean in mauris et arcu vestibulum eleifend. Integer ante elit, fermentum ac lacinia fermentum, sollicitudin eu massa. Cras ultricies sapien sed mauris feugiat imperdiet sed in mauris. Sed felis nulla, sollicitudin sed facilisis a, mollis sed diam. Sed eu condimentum ipsum.</p>

    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>


<div class="lightbox privacy_policy" style="width:700px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" height="24" width="24" alt="close" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><h4>Privacy policy</h4></div>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit odio, pulvinar eu tincidunt id, tincidunt eu mauris. Aliquam ac tortor massa, sit amet interdum libero. Pellentesque arcu est, venenatis ut convallis nec, sollicitudin eget nisl. Suspendisse hendrerit luctus nibh, quis faucibus arcu pretium sit amet. Pellentesque dui enim, imperdiet in accumsan eu, interdum sed neque. Quisque vitae magna eget metus ultricies facilisis. Donec malesuada sagittis fringilla. Phasellus blandit nisi congue urna vestibulum adipiscing.</p>
<p>&nbsp;</p>
<p>Suspendisse sit amet eleifend urna. Vivamus accumsan suscipit mauris, et molestie nisi lobortis sed. Donec fringilla blandit nunc eu euismod. Mauris leo arcu, suscipit nec vulputate pretium, feugiat id mauris. Duis quis ante eget metus blandit cursus. Morbi cursus euismod facilisis. Pellentesque semper accumsan mi a pretium. Nunc a dolor erat, eu tristique ipsum. Suspendisse potenti. Vestibulum condimentum, est non condimentum interdum, nisi lorem tempus lorem, eget posuere sapien arcu sit amet ligula. Nulla neque enim, egestas id lacinia nec, rutrum id lorem.</p>
<p>&nbsp;</p>
<p>Morbi eu neque in arcu aliquet dapibus. Pellentesque quis dignissim risus. Quisque posuere consectetur mi, ullamcorper faucibus justo iaculis et. Integer aliquet placerat porta. Morbi vitae leo augue, lacinia iaculis leo. Donec varius bibendum bibendum. Quisque nibh velit, sagittis laoreet congue quis, rhoncus a metus. Proin vel risus purus. Pellentesque posuere aliquet lectus nec adipiscing. Aenean eget iaculis sem. Nulla id blandit ligula.</p>
<p>&nbsp;</p>
<p>Integer auctor purus at arcu convallis feugiat. Nullam a est a ante adipiscing pretium nec nec quam. Etiam sed orci vitae neque adipiscing pellentesque et non sem. Vestibulum pellentesque tellus vel magna tempus vel adipiscing turpis mollis. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean in mauris et arcu vestibulum eleifend. Integer ante elit, fermentum ac lacinia fermentum, sollicitudin eu massa. Cras ultricies sapien sed mauris feugiat imperdiet sed in mauris. Sed felis nulla, sollicitudin sed facilisis a, mollis sed diam. Sed eu condimentum ipsum.</p>

    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>

<script type="text/javascript">

$(document).ready(function(){
    var checked = $("#chrch_reg:checked").length;
   if(checked == 1){
       $('#church_reg').css('display','block');
                                     $('#cogtime_registration').css('display','none');
                                     if($('.advance-search-panel').is(':visible')){
                                         $('.advance-search-panel').css('display','none')
   }
   }
});

</script>