<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Social Hub &raquo; Landing page contents</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area frm_box frm_box2">
                        
                        <?php if(count($res))
                        {
                            foreach($res as $r)
                            {
                                if($r['s_keyword']=='sh_main')
                                {
                                    $content['main_title']=$r['s_title'];
                                    $content['main_desc']=$r['s_desc'];
                                }
                                if($r['s_keyword']=='sh_tweet')
                                {
                                    $content['tweet_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='sh_blog')
                                {
                                    $content['blog_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='sh_rings')
                                {
                                    $content['rings_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='sh_events')
                                {
                                    $content['events_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='sh_chatRoom')
                                {
                                    $content['chatRoom_desc'] = $r['s_desc'];
                                }
                        
                            }
                        }
                        
                        ?> 
                        
                        <form id="social_hub_landing_frm" action="" method="post" enctype="multipart/form-data" onsubmit="return form_post()">
                                  <!--<h2>Introduction Section</h2> -->
                                  <div class="lable02">Title :</div>
                                  <div class="field02">
                                        <input name="txt_sh_title" type="text" value="<?=$content['main_title']?>"/>
                                  </div>
                                  <div id="err_sh_title" class="error-message"></div>
                                  <div class="clr"></div>
                                  <div class="lable02">Introduction : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_desc" style="height: 144px;"><?=$content['main_desc']?></textarea>
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                  <h2>Tweet</h2>
                                  <div class="lable02">Content : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_tweet" class="small" style="height: 88px;"><?=$content['tweet_desc']?></textarea>
                                  </div>
                                  <div class="clr"></div>
                                  
                                  <h2>Blog</h2>
                                  <div class="lable02">Content : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_blog" class="small" style="height: 88px;"><?=$content['blog_desc']?></textarea>
                                  </div>
                                  <div class="clr"></div>
                                  <h2>Rings</h2>
                                  <div class="lable02">Content : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_rings" class="small" style="height: 88px;"><?=$content['rings_desc']?></textarea>
                                  </div>
                                  <div class="clr"></div>
                                  <h2>Events</h2>
                                  <div class="lable02">Content : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_events" class="small" style="height: 88px;"><?=$content['events_desc']?></textarea>
                                  </div>
                                  <div class="clr"></div>
                                  <h2>Chat Room</h2>
                                  <div class="lable02">Content : </div>
                                  <div class="field02">
                                        <textarea name="txtarea_sh_chatRoom" class="small" style="height: 88px;"><?=$content['chatRoom_desc']?></textarea>
                                  </div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable02"> </div>
                                  <div class="field02">
                                        <input name="" type="submit" class="btn"  value="Update" />
                                        <input name="" type="reset" class="btn"  value="Reset" onclick="return clear_box();"/>
                                  </div>
                              </form>
                        
                             
                              
                              <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->


<script type="text/javascript">
$(document).ready(function(arg) {
    
    // for AJAX page-submission...
    optionsArr = {
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateFrm, // post-submit callback 
        url:        admin_base_url + "social_hub/social_hub_landing_page/post_data"
    }; 
});
function form_post()
{
    
    $('#social_hub_landing_frm').ajaxSubmit(optionsArr);
    
    return false;
    
    //var values = $('#social_hub_landing_frm').serialize();
    
}
// validate ajax-submission...
function validateFrm(data)
{
    
    var data = JSON.parse(data);
hideBusyScreen();
showUIMsg(data.msg); 

        $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });   
    if(data.result=='failure') 
    {
        
        
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');

                //$('#err_'+id).attr('style','margin-left: 12px;');
            }
        }
        
    }
    else {
        
        
           
        
    }

}

function clear_box(){
      
          $('#social_hub_landing_frm')[0].reset();
          $('.error-message').hide();
      
  }


</script>