<script type="text/javascript">
$(document).ready(function(arg) {
 $('#frm_search').submit(function(){ 
						
						var datatosend=$("#frm_search").serialize();
						
					     	showBusyScreen();
							//alert(datatosend);
							
							$.ajax({
							   type: "POST",
							   url: admin_base_url+"site_settings/inbox/inbox/ajax_pagination/",
							   data: datatosend,
							   success: function(data){
								  
								  hideBusyScreen(); 
                                                                  
                                                                  $('#table_content').html('');
								   $('#table_content').html(data);
							       
								
								 
							   }
							 });	 
					   
						
				});
 
 });
 </script>


<div class="filter">
                             <span class="filter-by">Filter By &raquo;</span>
                            <form id="frm_search" onsubmit="return false;" method="post" enctype="multipart/form-data" class="filter-search">
<!--                            	<label>User Reporting :</label>
                                <input type="text" name="txt_name" id="txt_name" />
								<label>Abuser :</label>
                                <input type="text" name="txt_abuser_name" id="txt_abuser_name" />-->
								<label>Type :</label>
                                <select name="category" style="width:100px">
								<option value='-1' selected>----</option>
								<option value="report">Report abuse Request</option>
								<option value="project">project Information Request</option>
								<option value="church">church Request</option>
								<option value="ring">Ring Request</option>
<!--								<option value="photo">Photo</option>
								<option value="prayer_wall">Prayer wall post</option>
								<option value="ring">Ring Post</option>
								<option value="user">User</option>
								<option value="video">Video</option>
								<option value="wall">Wall Post</option>-->
								</select>
								<div class="clr"></div>
                                                                <div class="clr"></div>
								<label>Date Between :</label>
                                <input type="text" name="from_date" id="from_date" class="date-field"/>
								 <img src="../images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" class="calender" style="margin-right:35px;" />
								<script type="text/javascript">
									$(document).ready(function(arg) {
										$.datepicker.setDefaults($.datepicker.regional['']);
										$("#from_date").datepicker($.datepicker.regional['en']);

									});
							  </script>
								<label>To :</label>
                                <input type="text" name="end_date" id="end_date" class="date-field"/>
								 <img src="../images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" class="calender" style="margin-right:35px;" />
								<script type="text/javascript">
									$(document).ready(function(arg) {
										$.datepicker.setDefaults($.datepicker.regional['']);
										$("#end_date").datepicker($.datepicker.regional['en']);

									});
							  </script>
                                <input name="" type="submit" value="GO" class="go" />
                                <input type="hidden" id="search_basic" name="search_basic" value="Y" />
                            </form>  
                            <div class="clr"></div>
                          </div>