<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />
<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>
<script type="text/javascript">
$(function(){
		$("#friendSlct").multiselect().multiselectfilter();	
		$("#ringselect").multiselect().multiselectfilter();
		$("#netpalselect").multiselect().multiselectfilter();
		$("#ppselect").multiselect().multiselectfilter();	
		$("#pgselect").multiselect().multiselectfilter();
		$("#frndinv").multiselect().multiselectfilter();	
		$("#netpalinv").multiselect().multiselectfilter();
		$("#ppinv").multiselect().multiselectfilter();
		$("#pginv").multiselect().multiselectfilter();
		
	
	});
	
</script>
<script language="javascript">

var g_controller_url = base_url+"my-ring.html";

var photo_id = null;
$(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoad,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#ring_frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});

function showLoad()
{
 // $('#photo_album_btn').attr('disabled','disabled');
 	showUIMsg();
  $('#photo_album_btn').val('Creating...');
  
}


// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		showUIMsg(data.msg);	
	}
	else {
		
		showUIMsg(data.msg);		
		//window.location.href= "<?$_SERVER['HTTP_REFERER']?>";///document.URL;
		window.location.href= "<?php echo base_url().'my-ring.html'?>";
		
	}
	$('#sp_add_loading').html('');
	//hideLoading();
				
}





$(function(){
	$('#ring_desc_span').textCounter({
		target: '#ring_desc', // required: string
		count: 500, // optional: integer [defaults 140]
		alertAt: 20, // optional: integer [defaults 20]
		warnAt: 10, // optional: integer [defaults 0]
		stopAtLimit: true // optional: defaults to false
	});
	
});


</script>
<script type="text/javascript">
$(document).ready(function() {

	$('.send-pro-message').click(function(){
		var index=$(this).index();
		$('.new-wl > .comments-number ').css('display','none');
		$(this).next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	});
	
	 $('.wal-minus').click(function(){
			$(this).parents('.comments-number').slideUp('fast');
	 });
});
</script>
<style>
.sml_btn{ background:none repeat scroll 0 0 #013D62;}
</style>

<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                  
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        
                        <div id="mid_container">
                        <div class="page_heading">
                                <div class="left"><img src="images/icons/ring.png" alt="" onClick="location.href='<?=base_url()?>my-ring.html'" /> Rings </div>
								<!--<p class="rings-joined">Rings I have Joined / Created</p>-->
                                <?php /*?><div class="right"><input name="" type="button" value="Create Ring"  class="evnt_btn"  onclick="window.location='create-my-ring.html'"/></div><?php */?>
                            </div>
                            <!--sub page links -->
                              <div class="link-div" style="margin-top:-2px;">
                                  <ul>
                                    <li><a href="my-ring.html" class="<?php echo ($page_name=='my-ring')? 'current':'';?>"><span>My Ring</span> </a> </li>
                                    <li><a href="search-ring.html" class="<?php echo ($page_name=='search-ring')? 'current':'';?>"><span>Browse  &amp;  Search Ring</span> </a> </li>
                                    
                                       <?php 
                                 $logged_user_id = intval(decrypt($this->session->userdata('user_id')));
                                 $frnd_number = get_friend_number_by_id($logged_user_id);
                                 if($frnd_number <= 0){
                                 
                                ?>
                                          <li><a href="javascript:void(0)" onclick="show_dialog('ring-pop')" class="<?php echo ($page_name=='create-my-ring')? 'current':'';?>"><span>Create Ring</span> </a> </li>
                                          <?php
                                 }else if($frnd_number > 0){
                                          ?>
                                          <li><a href="create-my-ring.html" class="<?php echo ($page_name=='create-my-ring')? 'current':'';?>"><span>Create Ring</span> </a> </li>
                                 <?php } ?>
                                    
                                     <li><a href="approve-join-request.html" class="<?php echo ($page_name=='approve-join-request')?'current':'';?>"><span>Ring Requests</span></a> </li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                            <!--/sub page links -->
                            
                       	 <!-- <div class="page_heading">
                            	<div class="left"><img src="images/icons/ring.png" alt="" /> Create Ring</div>
                          </div>-->
                             
                             
                             <form name="ring_frm" id="ring_frm" action="<?=base_url().'logged/my_ring/add_ring'?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">
                             <div class="frm_box blue_box" style="width: 500px;">
                                    <div class="lable01" style="width:100px;">Name: </div> 
                                    <div class="field03" style="width: 350px;">
                                    <input name="ring_name" id="ring_name" type="text" style="width: 300px;" />
                                    <span id="err_name" class="error-message"></span> 
                                    </div>  
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">Description: </div>  
                                    <div class="field03" style="width: 350px;">
                                    <!--<textarea name="ring_desc" id="ring_desc" cols="" rows="" style="width:300px; height:170px;"></textarea>-->
                                    <textarea name="ring_desc"  id="ring_desc" style="width:300px; height:170px" onFocus="if(this.value=='Max 500 Char allowed') this.value='';" onBlur="if(this.value=='')this.value='Max 500 Char allowed'; " onkeypress="return restrict_carrige(event);"  >Max 500 Char allowed</textarea>
                                    <div class="clr"></div>
                                     <span id="ring_desc_span" class="pad-80 tcWarn" style="display:none;">0</span>
                                     
                                     <!--<span>500 characters</span>-->
                                    <span id="err_desc" class="error-message"></span> 
                                      <p style="float:left"><span id="text_count">0</span> Characters</p>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">Category:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <select name="category" id="category" style="width:300px;" onchange="javascript:generateSubcat($(this).val())">
                                          <option value="">Please Select Category</option>
                                          <?php echo $category?>
                                    </select>
                 					<span id="err_category" class="error-message"></span> 
                                 <?php /*?>   <script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#category").msDropDown();
                                            $("#category").hide();
                                        })
                                    </script><?php */?></div> 
                                    <div class="clr"></div>
                                    
                                    
                                    <DIV id="sub_cat" style="display:none;"></DIV>
                                    
                                    <div style="font-style:italic; font-size:11px; margin-left:115px;">Cant find your category. Request additional category  <a href="javascript:void(0);" class="link-reuqset">Click Here</a></div>  
                                    <div class="clr"></div>
                                    
                                    <DIV style="display:none;">
                                    <div class="lable01" style="width:100px;">&nbsp;</div>  
                                    <div class="field03" style="width:350px;">
                                    	<input type="text" value="" name="requestcategory" id="requestcategory" style="width:100px;" />
                                        
                                        <input type="button" class="sml_btn" value="Sent request" onclick="sentRequestForCategory()" />
                                    </div> 
                                    </DIV>
                                    
                                    
                                    <div class="clr"></div>
                                    
                                    <div class="lable01" style="width:100px;">Logo:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <input name="ring_logo" type="file"  size="39" style="width:300px"/>
                                    <span id="err_logo" class="error-message"></span> 
                                    </div> 
                                    
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">Privacy Settings:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <select name="privacy_settings" id="privacy_settings" style="width:300px;">
                                          
                                          <option value="2">All User</option>
                                          <option value="1">Only user invited by you can join  </option>
                                    </select>
                 					<span id="err_privacy_settings" class="error-message"></span> 
                                    <script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#privacy_settings").msDropDown();
                                            $("#privacy_settings").hide();
                                        })
                                    </script></div> 
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">	Invite Friends :</div>  
                                    <div class="field03" style="width: 350px;">
                                    
                                   	  
                                      <?php echo get_invitation('ring');?>
                                         <span id="err_invite_frnd" class="error-message"></span> 
										
                                    </div>
                                        <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">&nbsp;</div>  
                                    <div class="field03" style="width: 350px;">
                                      
                                      <input name="photo_album_btn"  id="photo_album_btn" type="submit" value="Create"  class="btn"/> 
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="location.href='<?php base_url()?>my-ring.html'" />
                                                                  
                          </div>
                          <div class="clr"></div>
                            <strong>A user can create maximum <?=$MAX_GRP?> Rings.</strong>
                            
                             </form>
                             <div class='clr'></div>
                            	</div>
                      
                    <!-- /left container -->
                        
                  </div>
                    <!-- right container -->
                    <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                    <!-- /right container -->
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>





<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<div class="lightbox contact_div" style="width:500px; ">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Select from Contacts </h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
                 
                  <?php /*?> <div class="user_div"> 
                        <input name="" type="checkbox" value="" />  <a href="javascript:void(0);"><img src="images/man1.png" alt=""/></a>
                      <a href="javascript:void(0);" class="blue_link">George Swift</a>
                        
                  </div><?php */?>
                  <div id="contact_list" >
                                   
                                      <div class="selectRecipients" style="background-color: #FFF; width:457px; border:none;">
                                       <?php 
										  if(count($contact_arr)):
											 $count_total = 1;
											 //pr($contact_arr);
											  foreach($contact_arr as $key=>$val){
												  
												  $img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);
												  
												  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
												   		$profile_link = get_profile_url($val['user_id'],$val['s_displayname']);
												  }
												  else{
													   $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
												  }
												  
												  $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
														
										 ?>
                                         <div class="image-block <?=$CSS?>">
                                             
                                              <input type="checkbox"  value="<?=$val['user_id']?>_<?=$val['s_displayname']?>" name="<?=intval(decrypt($this->session->userdata('user_id')))?>" id="<?=$key+1?>" />
                                              <div class="inside">
                                                  <?php /*?><div style="background:url('<?=$img?>') no-repeat center;width:60px; height:60px;" class="pro_photo2"></div><?php */?>
                                                  <img alt="Friend" src="<?=$img?>" /><br/><br/><br/>
                                                  <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>
                                              </div>
                                          </div>
                                        
                                       	 
										 <?php	$count_total++;	
										 			}
										 		endif; 
										 ?>
                                       	   
                                	  </div> 
								</div>
                    <div class="clr"></div>
                    <br />
                    <div style="text-align:right;"><input name="" type="button" value="Done" onclick="javascript:get_selected_contacts();" class="btn"/></div>
            </div>
            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

 <!--//lightbox SECTION 
 confirm delete album popup
 end of delete pop up -->
<script type="text/javascript">
function sentRequestForCategory()
{
	showLoading();
	$.ajax({
        url : base_url+"logged/my_ring/send_cat_req",
        type : "post",
        data : ({'category':$('#requestcategory').val()}),
        dataType : 'json',
        success : function(data)
        {
			$('#requestcategory').val('');
            hideLoading();
            showUIMsg(data.msg);
        }
    });
}
var carriage_count = 0;
$(document).ready(function() {

  $('.link-reuqset').click(function(){
	  $(this).parent().next().next().slideToggle('slow');
  });
  var count=0;
//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
	
  var text = $('#'+textid).val(); 
  
  if(text == ''){
	  count = 0;
  }
 


if( count == 0)
{
	//alert (carriage_count)
  var textlength = 0;
}
else
{
 var textlength = text.length;
}
  $('#text_count').html(textlength);
  if(textlength > limit)
  {
  $('#'+textid).val(text.substr(0,limit));
  return false;
  }
  else
  {
  return true;
  }
  
}


$(function(){
  $('#ring_desc').keyup(function(){
	  count=1;
  limitChars('ring_desc', 500, '');
  });
  $('#ring_desc').keydown(function(){
	  count=1;
  limitChars('ring_desc', 500, '');
  });
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('ring_desc',500, '');
});

function restrict_carrige(e)
{
	/*//if(e.keyCode == 13)
	{
		$.ajax({
			type: 'post',
			url: base_url+'logged/prayer_wall/getCarriageCount',
			data: {'str':$('#ta_desc').val()},
			dataType: 'json',
	
			success: function (data, status) {
				
					if(data.count > 1){
						return false;
					}
				
				}	// end of success function...
		});
	}*/
	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));

	if(e.keyCode == 13){
		carriage_count++;
		console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >10){
		return false;
		//e.preventDefault();
	}
}
 function generateSubcat(id) { 
        showUILoader_nodialog();
        $.ajax({
            type: 'get',
            url: '<?= base_url() ?>logged/my_ring/generateSubCat_II' + '/' + id,
            dataType: 'json',
            success: function(data, status) {
                hideUILoader_nodialog();
                $('#sub_cat').html(base64_decode(data.html));
                $('#sub_cat').attr('style', 'display:block;');
            }	// end of success function...
        });
    }
</script>