<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Add New Listen</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area frm_box ">
                              <form id="add_video_frm" action="" method="post" enctype="multipart/form-data" onsubmit="return add_video_()">
                                  <div class="lable01">Title :</div>
                                  <div class="field01">
                                        <input name="txt_title" type="text" />
                                  </div>
                                  <div id="err_title" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Category :</div>
                                  <div class="field01" style="margin-bottom:8px;">
                                          <select name="category" id="category" style="width:412px;">
                                          
                                          <?php
                                            foreach($all_cat as $cat)
                                            {
                                          ?>
                                          
                                                <option value="<?=$cat['id']?>"><?=$cat['s_name']?></option>
                                          <?php
                                            }
                                          ?>
                                                
                                          </select>
                                          
                                  </div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Description : </div>
                                  <div class="field01">
                                        <textarea id="elm1" name="txtarea_desc" class="elm1" rows="" cols="" ></textarea>
                                        <br class="clr" />
                                        <label class="left">(Maximum characters: 1000) </label>
                                  </div>
                                  <div id="err_desc" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Sound cloud embed code :</div>
                                  <div class="field01">
                                        <input name="txt_url" type="text" />
                                  </div>
                                  <div id="err_url" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Tags :</div>
                                  <div class="field01">
                                        <input name="tags" type="text" />
                                  </div>
                                  <!--<div id="err_url" class="error-message"></div>-->
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Is Feature:</div>
        						  <div class="field01" style="margin-bottom:8px;">
                                          <select name="is_featured" id="is_featured" style="width:412px;" onchange="showUploadFiled($(this))">
                                                <option value="1">Yes</option>
                                                <option value="0" selected="selected">No</option>
                                          </select>
                                         
                                  </div>
                                  <div class="clr"></div>
                                  
                                  <div style="display:none;" id="uploadDiv">
                                  	<div class="lable01">Upload Image :</div>
                                  	<div class="field01">
                                       <input type="file" name="adv_image">                                  </div>
                                  	<div id="err_adv_image" class="error-message"></div>
                                  	<div class="clr"></div>
                                  </div>
                                  
								  <div class="clr"></div>
								  
								  
								  <div class="lable01">In home:</div>
                                  		<div class="field01" style="margin-bottom:8px;">
                                          <select name="is_feature_home" id="is_feature_home" style="width:412px;">
                                                <option value="1" <?=($news_info['i_is_feature_home']==1)? 'selected="selected"':''?>>Yes</option>
                                                <option value="0" <?=($news_info['i_is_feature_home']==0)? 'selected="selected"':''?>>No</option>
                                          </select>
                                          <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                //$("#topStory").msDropDown();
                                                //$("#topStory").hide();
                                                //$('#topStory').css("width", "412px"); 
                                            })
                                          </script>
										  </div>
										  <div class="error-message"></div>
										  <div class="clr"></div>
										
										  
										  
										  <div id="div_adv_image_featured" style="display:none;">
										  <div class="lable01">Upload Image :</div>
										  <div class="field01">
											   <input type="file" name="adv_image_featured">
											   <div>[resolution: 1000 X 500 ]</div>
										  </div>
										  <div id="err_adv_image_featured" class="error-message"></div>
										  <div class="clr"></div>
										  </div>
								  
								  <div class="lable01">&nbsp;</div>
								  
								  
								  
                                  <div class="field01">
                                        <input name="" type="submit" class="btn"  value="Add"/><input name="" type="reset" class="btn"  value="Cancel" onclick="window.location='<?=admin_base_url()?>0/media-center-landing-videos.html'"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>         
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->












<script type="text/javascript">

function showUploadFiled(obj)
{alert($(obj).val());
	if($(obj).val()==1)
		$('#uploadDiv').show();
	else	
		$('#uploadDiv').hide();
}
$(document).ready(function(arg) {
    
    // for AJAX page-submission...
   
    
    
    optionsArrAdd = {
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateAddFrm, // post-submit callback 
        url:        admin_base_url + "media_center/add_new_audio/post_add_data"
    }; 
	
	
	$("#is_feature_home").change(function(){
		if ($(this).val() == 1)
		{
			$("#div_adv_image_featured").css("display","block");
		}
		else
		{
			$("#div_adv_image_featured").css("display","none");
		}
	});
    
    
});
//---------------------------------- add ----------------------------------------

function add_video_()
{
	tinyMCE.triggerSave(false,true);
    $('#add_video_frm').ajaxSubmit(optionsArrAdd);
    return false;
}
function validateAddFrm(data)
{
    
    var data = JSON.parse(data);

    showUIMsg(data.msg);
    hideBusyScreen();

     $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
        
    if(data.result=='failure') 
    {
       
        
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');

            }
        }
        
    }
    else {  //success
        
         //hideBusyScreen();

         $('#add_video_frm')[0].reset();
         window.location.href = admin_base_url+'0/'+'audio.html';
         
       
    }

}

//---------------------------------- end add ----------------------------------------


  
  
  $(document).ready(function () {

 //counting the left characters in comment
    
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    
    $(function(){
        $('#txtarea_desc').keyup(function(){
            //limitChars('txtarea_desc', 1000, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    
    //limitChars('txtarea_desc',1000, '');

    
 
});
  
function tinyMCE_call()
{

tinyMCE.init({
        // General options
        mode : "exact",
        elements:"elm1",
        theme : "advanced",
        width : "350px",
        height : "300px",
       plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
       
       entity_encoding : "raw",

       // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,formatselect,fontsizeselect,forecolor,separator,media,image,link,unlink",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,
        file_browser_callback : "tinyBrowser",

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : base_url+"css/tinymce/cms_pages.css",

        // Drop lists for link/image/media/template dialogs
        //template_external_list_url : "<?php echo base_url()?>js/template_list.js",
       // external_link_list_url : "<?php echo base_url()?>js/link_list.js",
        //external_image_list_url : "<?php echo base_url()?>js/image_list.js",
        //media_external_list_url : "<?php echo base_url()?>js/media_list.js",
        convert_urls : false,

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        },
        oninit: pastePlainText
});
}
//// for tinyMCE configurations [End]

$(document).ready(function(){
    tinyMCE_call();
});
var pastePlainText = function() {
    // No need to pass in an ID, instead fetch the first tinyMCE instance
    var ed = tinyMCE.get(0); 
    ed.pasteAsPlainText = true;  

    //adding handlers crossbrowser
    if (tinymce.isOpera || /Firefox\/2/.test(navigator.userAgent)) {
        ed.onKeyDown.add(function (ed, e) {
            if (((tinymce.isMac ? e.metaKey : e.ctrlKey) && e.keyCode == 86) || (e.shiftKey && e.keyCode == 45))
                ed.pasteAsPlainText = true;
        });
    } else {            
        ed.onPaste.addToTop(function (ed, e) {
            ed.pasteAsPlainText = true;
        });
    }
};
  
</script>