<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Minister Shouts &raquo; Add Your Shout</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area frm_box frm_box2">
                        	  <form action="" method="post" enctype="multipart/form-data">
                                  <div class="lable01">Title :</div>
                                  <div class="field02">
                                        <input name="" type="text" />
                                  </div>
                                  <div class="error-message">* Required Field</div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable02">Description :</div>
                                  <div class="field02" style="width:820px; margin-bottom:6px;">
                                       <textarea id="elm1" name="elm1" rows="" cols="" style="width:820px; min-height:400px;">
                                        &lt;p&gt;
                                            This is some example text that you can edit inside the &lt;strong&gt;TinyMCE editor&lt;/strong&gt;.
                                        &lt;/p&gt;
                                        &lt;p&gt;
                                        Nam nisi elit, cursus in rhoncus sit amet, pulvinar laoreet leo. Nam sed lectus quam, ut sagittis tellus. Quisque dignissim mauris a augue rutrum tempor. Donec vitae purus nec massa vestibulum ornare sit amet id tellus. Nunc quam mauris, fermentum nec lacinia eget, sollicitudin nec ante. Aliquam molestie volutpat dapibus. Nunc interdum viverra sodales. Morbi laoreet pulvinar gravida. Quisque ut turpis sagittis nunc accumsan vehicula. Duis elementum congue ultrices. Cras faucibus feugiat arcu quis lacinia. In hac habitasse platea dictumst. Pellentesque fermentum magna sit amet tellus varius ullamcorper. Vestibulum at urna augue, eget varius neque. Fusce facilisis venenatis dapibus. Integer non sem at arcu euismod tempor nec sed nisl. Morbi ultricies, mauris ut ultricies adipiscing, felis odio condimentum massa, et luctus est nunc nec eros.
                                        &lt;/p&gt;
                                    </textarea>
                                  </div>
                                  <div class="error-message">* Required Field</div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01">
                                        <input name="" type="button" class="btn"  value="Add"/><input name="" type="reset" class="btn"  value="Cancel" onclick="window.location=''"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
