<input type="hidden" id="current_page" value="<?=$current_page?>">

<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="80">Posted On</th>
                            <!--    <th align="left" valign="middle" height="30" width="65">By Admin ID</th>
                            -->
                                <th align="left" valign="middle" height="30" width="160">Title</th>
                                <th align="left" valign="middle" height="30" width="110">Category</th>
                                <th align="left" valign="middle" height="30" width="260">Description</th>
                                <th align="center" valign="middle" height="30" width="100">Featured</th>
                                <th align="center" valign="middle" height="30" width="30">Likes</th>
                                <th align="center" valign="middle" height="30" width="40">Comments</th>
								<th align="center" valign="middle" height="30" width="90">Posted by</th>
                                <th align="center" valign="middle" height="30" class="last" style="width: 42px;">Actions</th>
                              </tr>
                              
<?php
//pr($result_arr);
if(count($result_arr)) {
    foreach($result_arr as $news)
    {
?>
                              <tr>
                                <td align="left" valign="top"><?= getShortDateWithTime($news['dt_posted_on'],7)?></td>
                            <!--    <td align="left" valign="top">MB475821</td>
                            -->
                                <td align="left" valign="top"><?=my_substr($news['s_title'],50)?></td>
                                <td align="left" valign="top"><?=$news['cat_name']?></td>
                                <td align="left" valign="top"><?=my_substr(strip_tags(get_unformatted_string_edit($news['s_desc'])),80)?></td>
                                <td align="center" valign="top"><?=($news['i_is_top_story']==1)? 'Yes':'---'?></td>
                                
                                <td align="center" valign="top"><a id="like_<?=$news['id']?>" href="javascript:void(0);" onclick="return show_people_like(<?=$news['id']?>);"><?=$news['total_likes']?></a></td>
                                
                                <td align="center" valign="top"><a id="comment_<?=$news['id']?>" href="javascript:void(0);" onclick="return show_comments(<?=$news['id']?>);"><?=$news['total_comments']?></a></td>
                                <td align="left" valign="top"><?=get_admin_username_by_id($news['i_posted_by'])?></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='<?=admin_base_url()?><?=$current_page?>/<?=$news['id']?>/edit-christian-news.html'"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return confirm_delete_(<?=$news['id']?>)"/>
                                </td>
                              </tr>
<?php
    }
}
else
{
?>
                            <tr>
                                <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                             </tr>
<?php
}
?>
                       
                            
                            </table>

<?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>                              