<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Media Center &raquo; Landing page contents</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area frm_box frm_box2">
                        
                        
                        <?php if(count($res))
                        {
                            foreach($res as $r)
                            {
                                if($r['s_keyword']=='mc_main')
                                {
                                    $content['main_title']=$r['s_title'];
                                    $content['main_desc']=$r['s_desc'];
                                }
                            }
                        }
                        
                        ?> 
                        
                        
                        
                        
                              <form id="media_center_landing_frm" action="" method="post" enctype="multipart/form-data" onsubmit="return form_post()">
                                  <!--<h2>Introduction Section</h2> -->
                                  <div class="lable02">Title :</div>
                                  <div class="field02">
                                        <input name="txt_title" type="text" value="<?=$content['main_title']?>"/>
                                  </div>
                                  <div id="err_title" class="error-message"></div>
                                  <div class="clr"></div>
                                  <div class="lable02">Introduction : </div>
                                  <div class="field02">
                                        <textarea id="txtarea_desc" name="txtarea_desc" cols="" rows="" style="height: 144px;"><?=$content['main_desc']?></textarea>
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                  <div class="lable02"> </div>
                                  <div class="field02">
                                        <input name="" type="submit" class="btn"  value="Update"/><input name="" type="reset" class="btn"  value="Reset" onclick="clear_box();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>             <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->


<script type="text/javascript">
$(document).ready(function(arg) {
    
    // for AJAX page-submission...
    optionsArr = {
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateFrm, // post-submit callback 
        url:        admin_base_url + "media_center/media_center_landing_page/post_data"
    }; 
});
function form_post()
{
    
    $('#media_center_landing_frm').ajaxSubmit(optionsArr);
    
    return false;
    
    //var values = $('#trade_center_landing_frm').serialize();
    
}
// validate ajax-submission...
function validateFrm(data)
{
    
    var data = JSON.parse(data);
hideBusyScreen();
showUIMsg(data.msg);

     $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
        
    if(data.result=='failure') 
    {
       
        
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');

                //$('#err_'+id).attr('style','margin-left: 12px;');
            }
        }
        
    }
    else {
        
         
       
    }

}

function clear_box(){
      
          $('#media_center_landing_frm')[0].reset();
          $('.error-message').hide();
      
  }


</script>