<?php
    //pr($result_arr);
?>
<input type="hidden" id="current_page" value="<?=$current_page?>">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="70">Posted On</th>
                              <?/*?>  <th align="left" valign="middle" height="30" width="140">Posted By</th>
                              <?*/?>
                                <th align="left" valign="middle" height="30" width="300">Title</th>
                                <th align="left" valign="middle" height="30" width="370">Description</th>
                               <?/* <th align="center" valign="middle" height="30" width="60">Liked By</th>
                                <th align="left" valign="middle" height="30" width="40">Comments</th>
                               */?>
                                <th align="center" valign="middle" height="30" width="42" class="last">Actions</th>
                              </tr>
                              
              <?php
                    if(count($result_arr))  
                    {
                        foreach($result_arr as $res)
                        {
                            
                        
                    
              ?>
                              
                              
                              <tr>
                                <td align="left" valign="top"><?=getShortDateWithTime($res['dt_posted_on'],7)?></td>
                               <?/*?> <td align="left" valign="top"><?=$res['admin_name']?></td>
                               <?*/?>
                                <td id="title_<?=$res['id']?>" align="left" valign="top"><?=$res['s_title']?></td>
                                <td id="desc_<?=$res['id']?>" align="left" valign="top"><?=my_substr($res['s_desc'],100)?></td>
                              <?/*  <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                */?>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return fetch_word_info_(<?=$res['id']?>);" />
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return confirm_delete_word_(<?=$res['id']?>);"/>
                                </td>
                              </tr>
                              
                              
                              
              <?php
                        }
                    }
                    else
                    {
              ?>
                             <tr>
                                <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                             </tr>
              <?php
                    }
                    
              ?>
                              
                              <?/*
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              <tr>
                                <td align="left" valign="top">20/12/2012</td>
                                <td align="left" valign="top">Alex</td>
                                <td align="left" valign="top">Contemporary</td>
                                <td align="left" valign="top">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</td>
                                <td align="center" valign="top" onclick="return show_dialog('liked-by')"><a href="javascript:void(0);">20</a></td>
                                <td align="center" valign="top" onclick="return show_dialog('comments-popup')"><a href="javascript:void(0);">17</a></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('edit-new-word')"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                </td>
                              </tr>
                              */?>
                            </table>
                            
                            
<?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>  
