                            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="70">Date Posted</th>
                                <th align="left" valign="middle" height="30" width="70">Posted By</th>
                                <th align="left" valign="middle" height="30" width="550">Testimony</th>

                                <th width="103" height="30" align="center" valign="middle" class="last">Actions</th>
  </tr>
                              
                              
                         <?php
                         //pr($info_arr);
                            if(count($info_arr)){
                            foreach($info_arr as $key=> $info){
                        ?>
                              <tr>
                                <td align="left" valign="top"><?=getShortDate($info['dt_insert_date'],5)?></td>
                                <td align="left" valign="top"><a href="javascript:void(0);" onclick="return show_dialog('detailed-descriptions')"><?= my_substr($info['s_description'],120)?></a></td>
                                
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='edit-prayer-wall.html'"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-page-popup')"/>
                                <input name="" title="Disable" type="button" class="btn-06"  value="Disable"/>
                                </td>
                              </tr>

                <?php    }
                    }
                    else{
                ?>
                     <tr>
                          <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                     </tr>
                
                <?php
                    }
                ?>
                              
                       
                            </table>
<?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>  