
<input type="hidden" id="current_page" value="<?=$current_page?>">
                            
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                          <tr>
                            <th align="left" valign="middle" height="30" width="77">Date Posted</th>
                            <th align="left" valign="middle" height="30" width="200">Posted By</th>
                            <th align="left" valign="middle" height="30" width="500">Testimony</th>
                            <th align="center" valign="middle" height="30" class="last">Actions</th>
                          </tr>
                              
                              
                         <?php
                         //pr($info_arr);
                            if(count($info_arr)){
                            foreach($info_arr as $key=> $info){
                        ?>
                                <tr>
                              <td align="left" valign="top"><?=getShortDate($info['dt_insert_date'],9)?></td>
                            <td align="left" valign="top"><?=$info['posted_by']?></td>
                            <td align="left" valign="top"><?=my_substr(html_entity_decode($info['s_description']),150)?></td>
                            <td align="center" valign="middle" class="last">
                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return fetch_edit_(<?=$info['id']?>);" style="margin-left: 34px;"/>
                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return delete_confirm_(<?=$info['id']?>)"/>
                            <input name="" title="View Post" type="button" class="btn-03"  value="View Post" onclick="return view_post_(<?=$info['id']?>)"/>
                            </td>
                          </tr>       
                <?php    }
                    }
                    else{
                ?>
                     <tr>
                          <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                     </tr>
                
                <?php
                    }
                ?>
                              
                       
                            </table>
<?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>  