<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> <?=$category_name?> <?=htmlentities(»)?> List of Sub-Category(s)</div>
                        
                        
                        <div class="right">
                            <a class="back-page" href="ring-categories.html">Back to Category List</a>
                        </div>
                        
                  </div>
                  
                  <input type="hidden" id="product_category_id" value="<?= $product_category_id?>" />
                  
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                            <h4>Sub-Category(s) of <?=$category_name?></h4>
                            <div class="right"><input name="" type="button" value="Add a Sub Category"  class="evnt_btn1" onclick="return show_dialog('add-product-category')"/></div>
                            <div class="clr"></div>
                        
                        
                         <DIV id="table_content">
							  <?=$result_content?>
                            </DIV>
                        <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->

<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Ring Sub-Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">If you delete this sub-category all Ring  under this sub-category will be deleted from the system. Are you sure you want to delete this sub-category anyway?</p>
                    <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_sub_cat_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->


<!--popup add category start-->
<div class="lightbox add-product-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="sub_cat_clear_box('add');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Add a Sub-Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_add_product_sub_category" action="" method="post" onsubmit="return post_sub_cat_frm_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 130px;"><span class="red-mark">* </span> Sub Category Name :</div>
                                  <div class="field01" style="width: 330px;">
                                        <input name="txt_cat_name" id="txt_cat_name" type="text" style="width: 320px;"/>
                                  </div>
                                  <div id="err_cat_name" class="error-message" style="margin-left: 12px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01" style="width: 130px;">&nbsp;</div>
                                  <div class="field01" style="margin-left: 0px; width: 300px;">
                                  <input type="hidden" id="add_parent_prod_id" name="add_parent_prod_id" value="<?=$product_category_id?>" />
                                        <input name="" type="submit" class="btn"  value="Add"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="sub_cat_clear_box('add');hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup add category end-->



<!--popup edit product category start-->
<div class="lightbox edit-product-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="sub_cat_clear_box('edit');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Ring Sub-Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_edit_product_sub_category" action="" method="post" onsubmit="return post_sub_cat_frm_edit_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 130px;"><span class="red-mark">* </span> Sub Category Name :</div>
                                  <div class="field01" style="width: 330px;">
                                        <input name="txt_edit_cat_name" id="txt_edit_cat_name" type="text" style="width: 320px;"/>
                                  </div>
                                  <div id="err_dit_cat_name" class="error-message" style="margin-left: 12px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01" style="width: 130px;">&nbsp;</div>
                                  <div class="field01" style="margin-left: 0px; width: 300px;">
                                  <input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
                                  <input type="hidden" id="edit_parent_prod_id" name="edit_parent_prod_id" value="<?=$product_category_id?>" />
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="sub_cat_clear_box('edit'); hide_dialog()"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup edit product category end-->

<script>
//========================== end of delete =======================================
//============================== ajax form submit for edit =================================
$(document).ready(function(arg) {
    
   
 
    // for AJAX page-submission... add ------------- sub cat-----------------------------
     subCat_optionsArr = { 
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateSubCatFrm, // post-submit callback 
        url:        admin_base_url + "social_hub/ring_categories/add_sub_cat_info"
    }; 
    
     // for AJAX page-submission... edit
    subCat_optionsArr_edit = { 
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateEditSubCatFrm, // post-submit callback 
        url:        admin_base_url + "social_hub/ring_categories/edit_sub_cat_info"
    }; 
 //------------------------------------- sub cat end -----------------------------
 
})

function post_frm_ajax()
{
    
    $('#frm_add_product_category').ajaxSubmit(optionsArr);
    
    return false;
}




function post_frm_edit_ajax()
{
    $('#frm_edit_product_category').ajaxSubmit(optionsArr_edit);
    
    return false;
}

// validate ajax-submission...
function validateEditFrm(data)
{
    var data = JSON.parse(data);
    if(data.result=='failure') 
    {
        clear_all_err();

        for ( var id in data.arr_messages ){
    
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');
                $('#err_'+id).attr('style','margin-left: 12px;');
            }
        }
        
    }
    else {
        clear_all_err();
        showUIMsg(data.msg);        
        hide_dialog();
        //$('#td_name_'+data.id).html(data.updated_d_name);
        $('#product_'+data.id).html(data.updated_d_name);
    }

}

function clear_all_err()
{
    $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
}

//============================== sub cat =================================

function post_sub_cat_frm_ajax()
{
    
    $('#frm_add_product_sub_category').ajaxSubmit(subCat_optionsArr);
    
    return false;
}

// validate ajax-submission...
function validateSubCatFrm(data)
{
    
    var data = JSON.parse(data);

    if(data.result=='failure') 
    {
        $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
        
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');
                $('#err_'+id).attr('style','margin-left: 12px;');
            }
        }
        
    }
    else {
        showUIMsg(data.msg);    
        hide_dialog();    
        $('#table_content').html(base64_decode(data.response));
        sub_cat_clear_box('add');
    }

}



function post_sub_cat_frm_edit_ajax()
{
    
    $('#frm_edit_product_sub_category').ajaxSubmit(subCat_optionsArr_edit);
    
    return false;
}

// validate ajax-submission...
function validateEditSubCatFrm(data)
{
    
    var data = JSON.parse(data);

    if(data.result=='failure') 
    {
        $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
        
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');
                $('#err_'+id).attr('style','margin-left: 12px;');
            }
        }
        
    }
    else {
        showUIMsg(data.msg);    
        hide_dialog();    
        $('#td_name_'+data.id+' a').html(data.updated_d_name);
        sub_cat_clear_box('edit');
    }

}


 function edit_cat(id)
    { 
        $('#i_edit_id').val(id );
         showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
      
             $.ajax({
                 type: "post",
                 url: base_url+'admin/social_hub/ring_categories/edit_info/'+id,
                 dataType:"json",
                 
                 success: function(json_response){
                
                      if(json_response.result = 'success') {
                          
                          $('#txt_edit_cat_name').val('');
                          $('#txt_edit_cat_name').val(json_response.s_category_name);
                         
                             hideUILoader('edit-product-category');
                          
                      }
                      else {
                           hideUILoader('edit-product-category');
                          showUIMsg('Some error occurred. Please try again.');
                      }
                  },
                  error: function(){
                     hideUILoader('edit-product-category');
                      showUIMsg('Some error occurred. Please try again.');
                  }
              });     
    
    }
	
	
function delete_confirm_(record_id)
{
 
        $('#i_del_id').val( record_id );
        //$('.no_of_rings').html(total_rings);
        show_dialog('delete-page-popup');
        
}
    
function delete_()
  {

      var selected_id = parseInt( $('#i_del_id').val() );
      //alert(selected_id );

  if( selected_id!=0 )
  {
       $.ajax({
                 type: "post",
                 url:base_url + 'admin/social_hub/ring_categories/delete_information',
                 dataType:"json",
                data: ({'id':selected_id}),
                 success: function(json_response){
                     hide_dialog();
                      if(json_response.result = 'success') {
                        //$('#row_'+selected_id).hide();
                        $('#table_content').html(base64_decode(json_response.response));
                        showUIMsg("Ring Category has been deleted successfully.");
                             
                      }
                      else {
                     
                           
                          showUIMsg('Some error occurred. Please try again.');
                      }
                  },
                  error: function(){
                      showUIMsg('Some error occurred. Please try again.');
                  }
              });
              
              
    }          
              
 
}


function delete_sub_cat_()
  {

      var selected_id = parseInt( $('#i_del_id').val() );
      //alert(selected_id );

  if( selected_id!=0 )
  {
       $.ajax({
                 type: "post",
                 url:base_url + 'admin/social_hub/ring_categories/delete_sub_information',
                 dataType:"json",
                data: ({'id':selected_id}),
                 success: function(json_response){
                     hide_dialog();
                      if(json_response.result = 'success') {
                        //$('#row_'+selected_id).hide();
                        $('#table_content').html(base64_decode(json_response.response));
                        showUIMsg("Ring Sub-Category has been deleted successfully.");
                             
                      }
                      else {
                     
                           
                          showUIMsg('Some error occurred. Please try again.');
                      }
                  },
                  error: function(){
                      showUIMsg('Some error occurred. Please try again.');
                  }
              });
              
              
    }          
              
 
}
</script>