<?php
pr($info_arr);
if (count($info_arr) != 0) {
    $counter = 0;
    
    foreach ($info_arr as $info) {
        $counter++;
        ?>             
        <div class="pop-content <?php echo ($counter == 1) ? 'first' : '' ?>">        
            <img src="<?php echo get_profile_image_of_user('thumb',$info['s_profile_photo'],$info['e_gender']) ?>" alt="posted by" width="73" height="73" class="posted-by" />
            <div class="right-panel">
<!--                <h5><?php echo $info->s_profile_name ?></h5>-->
                
                <p><h5>Sender Name :&nbsp;<?php echo get_username_by_id($info['i_invited_id']); ?></h5></p>
                <br>
                <h6>Request sent on: <span><?php echo $info['dt_request_date']; ?></span> </h6>
            </div>
        </div>

        <?php
    }
} else {
    ?>
    <div class="shade_box_blue" style="padding-top:5px; width: 578px; height: 280px;">
        <div class="shade_norecords" style="width:325px;">
            <p class="blue_bold12" style="font-weight: bold; margin-top: 100px;">No Pending Requests</p>
        </div>
    </div>
    <?php
}
?>                    

<div class="clr"></div>                  
