<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Ring</div>
                        <div class="right"><a class="back-page" href="rings.html">Back to Ring List</a></div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                            <!--blog brief start -->
                            <div class="blog-brief">
                            <input type="hidden" id="ring_id" value="<?=$ring_detail_arr[0]['id']?>">
                          <?php 
                         
							$RING_IMG = base_url() ."uploads/user_ring_logos/".getThumbName($ring_detail_arr[0]['s_logo'],'thumb');
						   ?>
                            <img src="<?=$RING_IMG?>" alt="Ring Logo" width="73" height="73" class="blog-posted-by" />
                            	<div class="right-panel">
                                    <h2><?=$ring_detail_arr[0]['s_ring_name']?></h2>
                                    <h3>Created by <strong><a href="javascript:void(0);"><?=$ring_detail_arr[0]['s_owner_name']?></a></strong> on <span><?php echo getShortDate($ring_detail_arr[0]['dt_created_on'],5)?></span></h3>
                                    
                                    
                                    <p id="first_part"><?php echo my_substr($ring_detail_arr[0]['s_description'],293)?> </p>
                                    <?php if(strlen($ring_detail_arr[0]['s_description'])>293)
                                    {
                                    ?>
                                    <div class="hidden-content">
                                    <p><?php echo substr($ring_detail_arr[0]['s_description'],0,strlen($ring_detail_arr[0]['s_description']))?></p>
                                    </div>
                                    <span  class="more-content"><a href="javascript:void(0);">View More</a></span>
                                    <?php
                                    }
                                    ?>
                                    </div>
                                 
                                
                            </div>
                            <div class="clr"></div>
                            <!--blog brief end -->
                            <!--members of the ring start -->
                            <h4>Members in the Ring</h4>
                            <div class="members-in-ring">
                               <?php
                               pr($ring_user_arr);
							       if(count($ring_user_arr)){
									  
									 foreach( array_slice($ring_user_arr,0,8) as $key => $val){
										
										 $img = get_profile_image($val['user_joined_id'], 'thumb'); 
										 
							   ?>
                                    <div class="member-block">
                                     <!-- <div class="member-pic" style="background:url(<?=$img?>) no-repeat center;width:73px; height:73px; margin-left: 9px;" ></div>-->
                                        <?php /*?><img src="../images/man1.png" alt="pic" width="73" height="73" class="member-pic" /><?php */?>
                                        <h3><?=$val['s_profile_name']?></h3>
                                        <h4><?=$val['s_country_name']?></h4>
                                        <a href="javascript:void(0);" class="remove" onclick="remove_member_confirm(<?php echo $val['table_id']?>,'<?=$val['s_profile_name']?>','<?=$img?>','no_popup')">Remove from Ring</a>
                                    </div>
                               <?php 
									 }
								   }
							   ?>
                               
                                <div class="clr"></div>
                                <a href="javascript:void(0);" onclick="return show_all_members_popup_();" class="show-all">Show All</a>
                            </div>
                            <!--members of the ring end -->
                            
                            <h4>List of Post(s)</h4>
                            <div class="clr"></div>
                            <DIV id="table_content">
							  <?=$result_content?>
                            </DIV>
                            
                        	<div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->


<?//----------------------------------------- if popup ------------------------------------------------?>
<input id="if_popup" type="hidden" value="">
<?//----------------------------------------- if popup ------------------------------------------------?>


<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Post</h4>
                  </div>
            </div>
            <div class="shade_box_white">
               <p class="center-text">Do you really want to delete this post?</p>
               <form action="" method="post" enctype="multipart/form-data">
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onclick="delete_()"/>
                    <input type="hidden" id="i_del_id" />
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->


<!--popup delete member start-->
<div class="lightbox delete-member-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="check_if_popup()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Member</h4>
                  </div>
            </div>
            <div class="shade_box_white">
            <img id="deleted_user_img" src="" alt="" style="height: 73px; width: 73px; margin-left: 200px;">
            <!--<div id="deleted_user_img" class="member-pic" style="background:url() no-repeat center;width:73px; height:73px; margin-left: 9px;"></div>
            -->
               <p class="center-text">Do you really want to remove <span id="deleted_user_name"></span>?</p>
               <form action="" method="post" enctype="multipart/form-data">
                       <input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onclick="remove_member_()"/>
                    <input type="hidden" id="i_member_del_table_id" value=""/>
                    <input name="" type="button" value="No" class="btn" onclick="check_if_popup()"/>
               </form>   
               <div class="clr"></div>
            </div>
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup delete member end-->

<!--popup view article start-->
<div class="lightbox post-popup" style="width:600px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>View Post</h4>
                  </div>
            </div>
               <div class="shade_box_white">
               	<DIV id="post_detail"><?=$post_detail_content?></DIV>	
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup view article end-->

<!--popup all member start-->
<div id="all_member_popup" class="lightbox all-member-popup" style="width:750px;">

</div>
<!--popup all member end-->

<!--edit post popup -->
<div class="lightbox post-edit-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="clrErrorMsgs();hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Post</h4>
                  </div>
            </div>
            <div class="shade_box_white">
           		<div class="content_area frm_box2">
                        	  <form action="" method="post" enctype="multipart/form-data">
                                  <div class="lable01">Title :</div>
                                  <div class="field01">
                                        <input name="txt_edit_title" id="txt_edit_title" type="text" />
                                  </div>
                                  <div id="err_edit_title" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Description : </div>
                                  <div class="field01">
                                        <textarea class="lightbox-textarea" name="limitedtextarea" onKeyDown="limitText(this.form.limitedtextarea,this.form.countdown,500);" 
onKeyUp="limitText(this.form.limitedtextarea,this.form.countdown,500);" id="txt_edit_post" style="height:155px;" ></textarea>
										<br class="clr" />
										<label class="left" style="font-style:italic; font-size:11px;">(Maximum characters: 500)</label>
                                  </div>
                                  <div id="err_edit_post" class="error-message"></div>
                                  <input type="hidden" id="i_post_edit_id" value="" />
                                  
                                  <div class="clr"></div>
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01">
                                        <input name="" type="button" class="btn"  value="Update" onclick="update_post()"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clrErrorMsgs();hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
           
           
           
           
            </div>
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--edit post popup end -->

<div class="lightbox comments-popup" style="width:600px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>View Comments</h4>
                  </div>
            </div>
               <div id="comment_div" class="shade_box_white" style="height:280px; overflow:auto">
              
               
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('.more-content a').click(function(){
			$('#first_part').hide();
			$('.hidden-content').slideDown();
			$(this).hide();
		});
	});
	
function limitText(limitField, limitCount, limitNum) {
	if (limitField.value.length > limitNum) {
		limitField.value = limitField.value.substring(0, limitNum);
	} 
}
	
function show_post_dialog(i_ring_id)
{
	showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
		$.ajax({
			
			url: admin_base_url +'social_hub/rings/show_post_detail/'+i_ring_id,
			dataType: 'json',
			type: 'post',
	
			success: function (data, status) {
				$('#post_detail').html(data.html);
				hideUILoader('post-popup');
				
			},
			error: function(data, status, e) {
				hideUILoader('post-popup');
				showUIMsg("Error!");
				
			}
		});
}




function show_all_members_popup_()
{
    var ring_id = $('#ring_id').val();
    
    $.ajax({
        url : admin_base_url+'social_hub/rings/ajax_show_all_members',
        type : 'post',
        dataType : 'json',
        data : ({'ring_id':ring_id}),
        success : function (data)
        {
           
            $('#all_member_popup').html(data.response);
            
            
        }
    });
    
        
    show_dialog('all-member-popup');
}

function show_eight_members_popup_()
{
    var ring_id = $('#ring_id').val();
    
    $.ajax({
        url : admin_base_url+'social_hub/rings/ajax_show_eight_members',
        type : 'post',
        dataType : 'json',
        data : ({'ring_id':ring_id}),
        success : function (data)
        {
            $('.members-in-ring').html(data.response);
        }
    });
    
        
    //show_dialog('all-member-popup');
}






function remove_member_confirm(table_id,user_name,user_img,if_popup)
{
    $('#i_member_del_table_id').val(table_id);
    //$('#deleted_user_img').attr('style','background:url('+user_img+')no-repeat center;width:73px; height:73px; margin-left: 203px;');
    $('#deleted_user_img').attr('src',user_img);
    $('#deleted_user_name').html(user_name);
    
    
    $('#if_popup').attr('value','');
    if(if_popup=='popup')
    {
        hide_dialog();
        $('#if_popup').val('popup');
    }
    show_dialog('delete-member-popup');

}

function remove_member_()
{
    var id = $('#i_member_del_table_id').val();
    
    $.ajax({
        url : admin_base_url+'social_hub/rings/delete_member',
        type : 'post',
        dataType : 'json',
        data : ({'table_id':id}),
        success : function(data)
        {
            showUIMsg(data.msg);
            hide_dialog();
            var if_popup = $('#if_popup').val();
    
            var ring_id = $('#ring_id').val();
            if(if_popup=='popup')
            {
                show_all_members_popup_(ring_id);
            }
            
            show_eight_members_popup_();
            
            
        }
    });
}


/* called from delete popup no button*/
function check_if_popup()
{
    hide_dialog();
    var if_popup = $('#if_popup').val();
    if(if_popup=='popup')
    {
        //var ring_id = $('#ring_id').val();
        //show_all_members_popup_(ring_id);
        show_dialog('all-member-popup');
        
    }
}
 function show_all_comments(id)
    {
        //alert(id);
        showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
        
        $.ajax({
            url : admin_base_url+'social_hub/rings/all_comments_ajax_pagination',
            type : 'post',
            dataType : 'json',
            data : ({'id':id}),
            success : function (data)
            {
                hideUILoader('comments-popup');
                $('#comment_div').html(data.html);
                
            }
        });
        
        
        
    }

</script>