<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Ring Categories</div>
                        <div class="right"><input name="" type="button" value="Add a Ring Category"  class="evnt_btn1" onclick="return show_dialog('add-ring-category')"/></div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                        
                         <DIV id="table_content">
							  <?=$result_content?>
                            </DIV>
                        <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->

<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Ring Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">Do you really want to delete this Ring Category ?</p>
                    <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>


<!--popup one end-->


<!--popup two start-->
<div class="lightbox delete-move-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Ring Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text" style="text-align:left;">This category contains <span class="no_of_rings"></span> rings.Please move these rings to another category before deleting.click yes to move the rings.</p>
			
                    <input type="hidden" name="i_del_id" id="i_del_id" value="" />
				
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="hide_dialog();show_move_page();"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup two end-->


<!--popup two start-->
<div class="lightbox move-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Move Rings</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text" style="text-align:left;">please select the category and subcategory to move the ring.</p>
			    <div class="content_area frm_box2">
			  <div class="lable01">    
			   <label>Category:</label>
			   </div>
			   <div class="field01">
			   <select id="cat-list" onchange="get_subcat_list($(this).val())">
			   </select>
			   </div>
			   <div class="clr"></div>
			  <div class="lable01">
			    <label>Sub-Category:</label>
				</div>
				 <div class="field01">
			   <select id="sub-cat-list">
			   </select>
			   </div>
			   <div class="clr"></div>
			   <div class="error-message" id="err-sub-cat" style="display:none">* Required Field</div>
			   	<div class="clr"></div>
				<input type="hidden" name="i_cat_id" id="i_cat_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="move_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
				 </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup two end-->

<!--popup add ring category start-->
<div class="lightbox add-ring-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="clear_box('add');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Add a Ring Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_add_ring_category" action="" method="post" onsubmit="return post_frm_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 105px;"><span class="red-mark">* </span> Category Name :</div>
                                  <div class="field01">
                                        <input name="txt_cat_name" id="txt_cat_name" type="text" />
                                  </div>
                                  <div id="err_cat_name" class="error-message" style="margin-left: 12px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01" style="margin-left: 10px;">
                                        <input name="" type="submit" class="btn"  value="Add"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('add');hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup add ring category end-->

<!--popup edit ring category start-->
<div class="lightbox edit-ring-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="clear_box('edit');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Ring Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_edit_ring_category" action="" method="post" onsubmit="return post_frm_edit_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 105px;"><span class="red-mark">* </span> Category Name :</div>
                                  <div class="field01">
                                        <input name="txt_edit_cat_name" id="txt_edit_cat_name" type="text" />
                                  </div>
                                  <div id="err_dit_cat_name" class="error-message" style="margin-left: 12px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01" style="margin-left: 10px;">
                                  <input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('edit'); hide_dialog()"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup edit ring category end-->

