<?php
$logged_id=intval(decrypt($this->session->userdata('user_id')));
		if(count($result_arr)):
			foreach($result_arr as $k=> $val){	
			
				 $name = $val['s_profile_name'];
				 $IMG = get_profile_image($val['i_user_id'],'thumb',$val['s_profile_photo']);
				 $comment_txt = $val['s_contents'];
				 $profile_link = get_profile_url($val['i_user_id'],$val['s_profile_name']);	
				 $url=CheckUserRelation($val['i_user_id']);
				  if($url['i_isfriend'] == true || $url['i_isnetpal'] == true)
				{
				$profile_link = get_profile_url($val['i_user_id'],$val['s_profile_name']);	
				}
				else if($val['i_user_id'] == $logged_id)
				{
				$profile_link = base_url().'my-wall.html';
				}
				else{
				$profile_link = get_public_profile_url($val['i_user_id'],$val['s_profile_name']);
				}
				 
?>
<div class="txt_content01 track-comment-border"> 
            <a href="<?=$profile_link?>"><div class="pro_photo" style="background:url(<?php echo $IMG;?>) no-repeat center;width:60px; height:60px;" ></div></a>
             <div class="left_div01a">
                      <p class="blue_bold12"><a  href="<?=$profile_link?>"><?=$name?></a></p>
                      <p class="light-grey"><?=$val['s_contents']?></p>
                       <?php if(get_time_elapsed($val['dt_created_on']) != '') {?>
                        <p class="date-time">Updated on: <?=get_time_elapsed($val['dt_created_on'])?></p>
                       <?php } ?>
                    </div>
            <div class="clr"></div>
</div>

<?php
			}
		endif;
?>