<script type="text/javascript">
 function edit_audio(id)
	{
		$('#i_edit_id').val(id);
		//$('#i_album_id').val(album_id);
		 showUILoader('<img src="<?= base_url() ?>images/loading_big.gif" width="50"/> ');
	  
			 $.ajax({
				 type: "get",
				 url: '<?=base_url()?>logged/organize_audio/edit_audio_ajax/'+id,
				 dataType:"json",
				 success: function(json_response){
					 
					  if(json_response.result = 'success') {
						 //  alert(json_response.audio_arr);
						   
						   for ( var id in json_response.audio_arr ){
							  // alert(json_response.audio_arr[id])
								  $('#'+id).val(json_response.audio_arr[id]);
						    }
							// puting audio file name ///
							//var audio_PATH = base_url+ "uploads/user_audio_files/";
						   // $('#track_music_file').val(json_response.audio_arr.s_audio_file_name);
							
						 	hideUILoader('edit_photo');
					  }
					  else {
						   hideUILoader('edit_photo');
						  showUIMsg('Some error occurred. Please try again.');
					  }
				  },
				  error: function(){
					 hideUILoader('edit_photo');
					  showUIMsg('Some error occurred. Please try again.');
				  }
			  });	 
		//show_dialog('edit-scrolling-headlines');
		//return false;
	}



$(document).ready(function() {
	
	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoadEdit,  // pre-submit callback 
        success:       validateEditFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#frmEditAudio').submit(function() {
	
        $(this).ajaxSubmit(options);
		
        return false;
		
    });

});
function showLoadEdit()
{
 // $('#edit_photo_btn').attr('disabled','disabled');
  $('#edit_photo_btn').val('Updating...');
  $('#edit_photo_loading').html('<img id="img_holder" src="<?=base_url()?>images/loading_small.gif" align="absmiddle" />');
  
}


// validate ajax-submission...
function validateEditFrm(data)
{
	
	var data = JSON.parse(data);//alert(data.arr_messages);
	if(data.success==false) 
	{ //alert(1111);
		
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#edit_photo_btn').attr('disabled','');
		$('#edit_photo_btn').val('Update');
		$('#edit_photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert('#err_edit_'+id);
			
			if( $('#err_edit_'+id) != null ) {
				$('#err_edit_'+id).html(data.arr_messages[id]);
				$('#err_edit_'+id).attr('style','display:block;');
			}
		}

		
	}
	else {
		  // clearing form
		  $('#frmEditAudio')[0].reset();
		  $('.error-message').hide();
		  $('#edit_photo_btn').val('Update');
		  hide_dialog();
		  $('#album_div').html(base64_decode(data.html));
		  showUIMsg(data.msg);
		  //window.location.href=document.URL;
	}
	$('#edit_photo_loading').html('');
	//hideLoading();
				
}
function clear_box(){
		  $('#frmEditAudio')[0].reset();
		  $('.error-message').hide();
}
</script>
<script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#s_desc').keyup(function(){
            limitChars('s_desc', 250, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('s_desc',250, '');
    
 
});
</script>

<form id="frmEditAudio"  method="post" action="<?=base_url().'logged/organize_audio/edit_audio_ajax'?>" onsubmit="return false;" enctype="multipart/form-data">
<div class="lightbox edit_photo" style="width:550px;">
    <div class="close"><a href="javascript:void(0)" onclick="clear_box();hide_dialog()"><img src="images/close.png" alt="" height="24px" width="24px" /></a></div>
    
    <div class="top"><div>&nbsp;</div></div>
       <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/photo.png" alt="" /> Edit Audio </h4></div></div>
               <div class="frm_box">
           
             <div class="lable01">Title:</div> 
             <div class="field01"><input name="s_title" id="s_title"  type="text"  /> 
             <span id="err_edit_title" class="error-message"></span> 
             </div>
             <div class="clr"></div>
             
             
             <div class="lable01">Artist:</div> 
             <div class="field01"><input name="s_artist" id="s_artist" type="text"  />
             <span id="err_edit_artist" class="error-message"></span> 
             </div>
             <div class="clr"></div>
             
             
             <div class="lable01">Genre:</div> 
             <div class="field01"><!--<input name="s_genre" id="s_genre" type="text"/>-->
             <select name='txt_genre' style='width:260px' id="s_genre_id">
             	<option value="-1">Select</option>
                <?=makeOptionGenre();?>
             </select> 
             <span id="err_edit_genre" class="error-message"></span> 
             </div>
             <div class="clr"></div> 
             
                         
             <?php /*?><div class="lable01">Sound Track Album:</div> 
             <div class="field01"><input name="s_sound_track_album" id="s_sound_track_album" type="text" /> 
              <span id="err_edit_track_album" class="error-message"></span> 
             </div>
             <div class="clr"></div><?php */?>
             
             
             <div class="lable01">Description:</div> 
             <div class="field01"><textarea name="s_desc" id="s_desc" style="height:80px;"></textarea> 
             </div>
             <div class="clr"></div>
             
             
             <div class="lable01">Browse Audio:</div> 
             <div class="field01 error_txt" style="width:320px;">
             <input name="track_music_file" id="track_music_file" type="file" style="width:217px;" /> (.mp3 only) 
             <input type="hidden" id="s_audio_file_name" name="s_audio_file_name" value=""/>
              <span id="err_edit_track_music_file" class="error-message"></span> 
             </div>
             <div class="clr"></div>
             
            <div class="lable01">Select Album:</div> 
             <div class="field01"> 
             <select name="select_album1" id="select_album1" style="width:260px;">
                 <?php if(count($all_audio_albums)>0):
					 		echo '<option value="-1">Select</option>';
					 		foreach($all_audio_albums as $album):
							
								$sel = ($current_album_id == $album['id'])?'selected ="selected"':'';
					  ?>
                            
                     		<!--<option>[New Album]</option>-->
                            <option value="<?=$album['id']?>" <?=$sel?>><?=$album['s_name']?></option>
                     <?php 	endforeach;
						  	else:
							echo '<option value="0">No Albums available, Please create.</option>';
						   endif;
					 ?>
            </select>
           <?php /*?> <script type="text/javascript">
                $(document).ready(function(arg) {
                    $("#select_album1").msDropDown();
                    $("#select_album1").hide();
                })
            </script> <?php */?>
             <span id="err_edit_album1" class="error-message"></span> 
            </div>
             <div class="clr"></div>
             
              <div class="field01" style="width:517px; font-style:italic; color:#494949; line-height:15px;">Disclaimer: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit odio, pulvinar eu tincidunt id, tincidunt eu mauris.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec velit odio, pulvinar eu tincidunt id, tincidunt eu mauris.</div>
             <div class="clr"></div>
             
           <?php /*?>   <div class="lable01">New Album Name:</div> 
             <div class="field01"><input name="" type="text" /> </div>
             <div class="clr"></div><?php */?>
             <div class="lable01">&nbsp;</div> 
              <input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
             <div class="field01">
             <?php if(count($all_audio_albums)>0):?>
                <input name="edit_photo_btn" id="edit_photo_btn" type="submit" value="Update" class="btn" />
             <?php else:?>
                <input name="cancel" type="button" value="Cancel" class="btn" onclick="clear_box();hide_dialog();" />
             <?php endif;?>
             </div>
             <div class="clr"></div>
           </div>
          
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
</form>