<script type="text/javascript">
    function clear_form() {
        $('#frm_search')[0].reset();
    }

    $(document).ready(function(arg) {

        $('#frm_search').submit(function() {

            var datatosend = $("#frm_search").serialize();

            showUILoader_nodialog('<img src="' + base_url + 'images/loading_big.gif" width="50"/> ');
            $.ajax({
                type: "POST",
                url: base_url + 'logged/my_photo_album_details/photos_ajax_pagination/<?= $profile_id ?>',
                data: datatosend,
                dataType: 'json',
                success: function(data) {
                    $('#frm_search')[0].reset();
                    if (data.html != '') {
                        $('#result_photo_section').html(data.html);
                        $('#show_more_feeds_link').attr('page_value', data.current_page);
                    }
                    else {
                        $('#result_photo_section').html('<div class="view_more" style="text-align: center; height:25px;"><p class="blue_bold12" style="font-size:16px;">No More Photo.</p></div>');
                        $('#show_more_feeds_div').hide();
                    }

                    hide_dialog('search_audio');
                    hideUILoader_nodialog();
                }
            });
        });

    });
	
$(document).ready(function() {    
	$(".lightbox-2").lightbox({
		fitToScreen: true,
		scaleImages: true,
		xScale: 1.2,
		yScale: 1.2,
		displayDownloadLink: true
	});
});
</script>


<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <div id="top_corner">&nbsp;</div>
        <div id="mid_content">
            <!-- latest news -->
            <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div id="main_container">
                <!-- left container -->
                <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
                <!-- /left container -->
                <!-- mid container -->
                <div id="mid_container">

                    <!--sub page links -->
                    <div class="link-div" style="margin-top:0px;">
                        <ul>
                            <li><a href="manage-my-photo.html"><span>Manage My Photo Albums</span> </a> </li>
                            <li><a href="create-photo-album.html"><span>Create Photo Album</span></a></li>
                            <li><a href="javascript:void(0);" onclick="return show_dialog('upload_photo')"><span>Upload Photo</span></a></li>
                        </ul>
                        <div class="clr"></div>
                    </div>
                    <!--/sub page links -->

                    <div class="page_heading">
                        <div class="left"><img src="images/icons/photo.png" alt="" /> <?= $arr_albums['s_name'] ?></div>
                        <?php /* ?><div class="right"><input name="" type="button" value="Upload Photo"  class="upload_btn"  onclick="return show_dialog('upload_photo')"/></div><?php */ ?>
                    </div>


                    <div class="arrow_btm"></div>
                    <div class="section01">


                        <div class="audio_div">
                            <?php $IMG = base_url() . "uploads/user_album_photos/" . getThumbName($arr_albums['s_photo'], 'thumb'); ?>
                            <div class="photo-div left">
                                <a href="javascript:void(0);"><div style="background:url(<?= $IMG ?>) no-repeat center;width:122px; height:82px; cursor:pointer; "  title="Album" ></div></a>
                            </div>
                            <p class="date-time">Created on : <?= getShortDate($arr_albums['dt_created_on'], 5) ?></p>
                            <p><?= $arr_albums['s_desc'] ?></p>
                                <!--<p class="blue_bold12"><a href="javascript:void(0);">Album Name</a></p>
                                                                10 Photos -->
                        </div>




                        <div class="clr"></div>
                    </div>
                    <div class="page_heading">
                        <div class="left"><img src="images/icons/photo1.png" alt="" /> Photos (<?= $total ?>)</div>
                        <div class="right">
                            <? /* <img src="images/icons/search.png" alt="" /> <a href="javascript:void(0);"  onclick="return show_dialog('search_audio')" class="blue_link"><strong>Search</strong></a>
                             */ ?>
                            <input type="button" class="upload_btn"  value="Upload Photo" onclick="return show_dialog('upload_photo')" style="line-height:normal;"/>

                        </div>
                        <div class="clr"></div>
                    </div>
                    <div class="arrow_btm"></div>
                    <div class="div_content" style=" margin-top:0px;">

                        <div class="shade_box_01">
                            <DIV id="result_photo_section"><?= $photo_content ?></DIV>  
                            <?php
                            if ($total == 0) {
                                ?>

                                <div class="view_more" style="text-align: center; height:25px;"><p class="blue_bold12" style="font-size:16px;">No photos.</p></div>
                                <?php
                            }
                            ?>
                        </div>  

                            <?php if ($total_no_of_photos > $pagination_per_page): ?>

                            <div class="view_more" id="show_more_feeds_div">
                                <a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?= $current_page ?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> 
                            </div>
                        <?php endif; ?>

                    </div>

                </div>
                <!-- /mid container -->
                <!-- right container -->
<?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
                <!-- /right container -->
            </div>
            <!-- /main container -->
            <div class="clr"></div>
        </div>
        <div id="bot_corner">&nbsp;</div>
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH . "views/logged/photos/blocks/upload_multi_photo_popup.phtml"); ?>

<?php include(APPPATH . "views/logged/photos/blocks/upload_photo_popup_photo_album_details.phtml"); ?>
<?php include(APPPATH . "views/logged/photos/load_photo_details.phtml"); ?>


<!-- /lightbox SECTION -->
<!--light box for image details start-->
<div class="lightbox image-details" style="width:850px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top">
        <div>&nbsp;</div>
    </div>
    <div class="mid">
        <div id="photo_html"></div>
    </div>
    <div class="bot">
        <div>&nbsp;</div>
    </div>
</div>
<!--light box for image details end-->

<div class="lightbox search_audio" style="width:480px;">
    <div class="close"><a href="javascript:void(0)" onclick="clear_form();
            hide_dialog();"><img src="images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/search1.png" alt="" /> Search</h4></div></div>
        <form name="frm_search" id="frm_search" class="filter-search" onsubmit="return false;" method="post" >
            <div class="frm_box">
                <div class="lable01" style="width:100px;">Title:</div> 
                <div class="field01"><input name="txt_title" id="txt_title" type="text" /></div>
                <div class="clr"></div>
                <input type="hidden" id="search_basic" name="search_basic" value="Y" />
                <div class="lable01" style="width:100px;">&nbsp;</div> 
                <div class="field01"><input name="" type="submit" value="Search" class="btn" /></div>
                <div class="clr"></div>
            </div>
        </form>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>



<script type="text/javascript">
<!--	
    var ticker_holder = $('.bargaining').get(0);
    var ticker_text = $('.ticker').get(0);
    var ticker_pos = ticker_text.parentNode.offsetWidth;

    var ticker_data = $(ticker_holder).html();
    $(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');

    $('#sub-nav').hover
            (
                    function() {
                        $('marquee', this).get(0).stop();
                    },
                    function() {
                        $('marquee', this).get(0).start();
                    }
            );
//-->
</script>


<script type="text/javascript">

    var ajax_req_feeds = null;
    function show_more_feeds(page) {
        if (ajax_req_feeds != null) {
            ajax_req_feeds.abort();
        }
        showUILoader_nodialog();
        ajax_req_feeds = $.ajax({
            type: 'get',
            url: base_url + 'logged/my_photo_album_details/photos_ajax_pagination/<?= $profile_id ?>/<?= $album_id ?>/' + page,
            dataType: 'json',
            success: function(data, status) {

                hideUILoader_nodialog();
                if (data.html != '') {
                    $('#result_photo_section').append(data.html);
                    $('#show_more_feeds_link').attr('page_value', data.current_page);
                }
                else {
                    $('#result_photo_section').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Photo.</p></div>');
                    $('#show_more_feeds_div').hide();
                }

                if (data.view_more == false)
                {
                    //alert("offf");
                    $('#result_photo_section').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Photo.</p></div>');
                    $('#show_more_feeds_div').hide();
                }

            }    // end of success function...
        });
    }
</script>
