<script type="text/javascript">
function get_photo_album_info(album_id) {
    showLoading();
  
      $.ajax({
       type: "get",
       url: '<?=base_url()?>logged/my_photos/get_photo_album_info/'+album_id,
       dataType:"json",
       success: function(json_response){
            hideLoading();
            if(json_response.result = 'success') {
                $('#albums_section').attr('style','display:none;');
                $('#single_photo_album_section').attr('style','display:block;');
                $('#single_photo_album_section').html(json_response.album_html);        
            }
            else {
                showUIMsg('Some error occurred. Please try again.');
            }
        },
        error: function(){
            hideLoading();
            showUIMsg('Some error occurred. Please try again.');
        }
    });
}

function back_photo_albums() {
    showLoading();
    $('#single_photo_album_section').attr('style','display:none;');
    $('#albums_section').attr('style','display:block;');
    hideLoading();
}

</script>
<script type="text/javascript">
  function show_photo_slideshow()
  {
         
      showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
        $.ajax({
            
            url: base_url +'logged/my_photos/fetch_all_photos/',
            dataType: 'json',
            type: 'post',
    
            success: function (data, status) {
                $('#photo_html').html(data.html_data);
                hideUILoader('view_slideshow');
                showUIMsg(data.msg);
            },
            error: function(data, status, e) {
                hideUILoader('view_slideshow');
                showUIMsg("Error!");
                
            }
        });
                 
         
  }
function clear_form(){
      $('#frm_search')[0].reset();
} 

$(document).ready(function(arg) {
    


 $('#frm_search').submit(function(){ 
                        
          var datatosend=$("#frm_search").serialize();
           showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
              $.ajax({
                 type: "POST",
                 url: base_url+'logged/my_photos/photos_ajax_pagination/<?=$profile_id?>',
                 data: datatosend,
                 dataType : 'json',
                 success: function(data){
                    $('#frm_search')[0].reset();
                    if(data.html!='') {
                        $('#result_div').html(data.html);
                        $('#show_more_feeds_link').attr('page_value', data.current_page);
                    }
                    else {
                        $('#result_div').html('<div class="view_more" style="text-align: center; height:25px;"><p class="blue_bold12" style="font-size:14px;">No photos.</p></div>');
                        $('#show_more_feeds_div').hide();
                    }
                    hide_dialog('search_audio');
                    hideUILoader_nodialog();
                 }
               });     
    });
 
 });
</script>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_feeds(page) {
    if(ajax_req_feeds!=null) {
        ajax_req_feeds.abort();
    }
    showUILoader_nodialog();
    ajax_req_feeds = $.ajax({
        type: 'get',
        url: base_url+'logged/my_photos/photos_ajax_pagination/<?=$profile_id?>'+'/'+page,
        dataType: 'json',

        success: function (data, status) {

            hideUILoader_nodialog();
            if(data.html!='') {
                $('#result_div').append(data.html);
                $('#show_more_feeds_link').attr('page_value', data.current_page);
            }
            else {
                $('#result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more photos.</p></div>');
                $('#show_more_feeds_div').hide();
            }
            
          
        }    // end of success function...
    });
}
</script>

<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        	 <div class="page_heading">
                                <div class="left"><img src="images/icons/photo.png" alt="" /> Photos</div>
                            </div>
                             <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                                  <ul>
                                    <li><a href="my-photos.html"><span>My Photos</span> </a> </li>
                                    <li><a href="manage-my-photo.html"><span>Manage My Photo Albums</span> </a> </li>
                                    <li><a href="create-photo-album.html"><span>Create Photo Album</span></a></li>
                                    <li><a href="javascript:void(0);" onclick="return show_dialog('upload_photo')"><span>Upload Photo</span></a></li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                             <!--/sub page links -->
                              
                            <div class="page_heading_01">
                                <div class="left"><img src="images/icons/photo.png" alt="" /> All  Albums</div>
                            </div>
                            
                            <div class="arrow_btm"></div>
                               <DIV id="result_albums_section">
                                  <?=$result_arr?>
                                </DIV>
                               
                            
                            <div id="single_photo_album_section">
                            </div>
                                              
                        </div>                 
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /lightbox SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<?php include(APPPATH."views/logged/photos/blocks/upload_photo_popup.phtml");?>
<?php include(APPPATH."views/logged/photos/blocks/upload_multi_photo_popup.phtml");?>


<?php include(APPPATH."views/logged/photos/comments/my_photo_post_comment_lightbox.phtml");?>




