<script type="text/javascript">
    function get_photo_album_info(album_id) {
        showLoading();
        $.ajax({
            type: "get",
            url: '<?= base_url() ?>logged/my_photos/get_photo_album_info/' + album_id,
            dataType: "json",
            success: function(json_response) {
                hideLoading();
                if (json_response.result = 'success') {
                    $('#albums_section').attr('style', 'display:none;');
                    $('#single_photo_album_section').attr('style', 'display:block;');
                    $('#single_photo_album_section').html(json_response.album_html);
                }
                else {
                    showUIMsg('Some error occurred. Please try again.');
                }
            },
            error: function() {
                hideLoading();
                showUIMsg('Some error occurred. Please try again.');
            }
        });
    }

    function back_photo_albums() {
        showLoading();
        $('#single_photo_album_section').attr('style', 'display:none;');
        $('#albums_section').attr('style', 'display:block;');
        hideLoading();
    }


    function show_photo_slideshow()
    {

        showUILoader('<img src="' + base_url + 'images/loading_big.gif" width="50"/> ');
        $.ajax({
            url: base_url + 'logged/my_photos/fetch_all_photos/',
            dataType: 'json',
            type: 'post',
            success: function(data, status) {
                //hideUILoader();
                $('#photo_html').html(data.html_data);
                hideUILoader('view_slideshow');
                //hideBusyScreen();
                showUIMsg(data.msg);
            },
            error: function(data, status, e) {
                hideUILoader('view_slideshow');
                //show_dialog('view_comments_div');
                showUIMsg("Error!");

            }
        });


    }
    function clear_form() {
        $('#frm_search')[0].reset();
    }

    $(document).ready(function(arg) {



        $('#frm_search').submit(function() {

            var datatosend = $("#frm_search").serialize();
            showUILoader_nodialog('<img src="' + base_url + 'images/loading_big.gif" width="50"/> ');
            $.ajax({
                type: "POST",
                url: base_url + 'logged/my_photos/photos_ajax_pagination/<?= intval(decrypt($this->session->userdata('user_id'))) ?>',
                data: datatosend,
                dataType: 'json',
                success: function(data) {

                    $('#result_div').html('');
                    $('#show_more_feeds_div').hide();

                    if (data.html != '') {
                        $('#no_tweets').hide();
                        $('#result_div').html(data.html);
                    }
                    else {
                        $('#no_tweets').remove();
                        $('#result_div').append('<div id="no_tweets" style="padding-top:5px;" class="section01"><div style="width:260px;" class="shade_norecords"><p class="blue_bold12">No Photos.</p></div></div>')
                    }
                    if (data.view_more == true)
                    {
                        $('#result_div').append('<div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);"id="show_more_feeds_link" page_value="' + data.current_page + '" onclick="show_more_feeds(' + data.current_page + ')">[view more] </a></div>');
                    }

                    if (data.html != '' && data.view_more == false)
                    {

                        $('#result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Photo.</p></div>');
                        $('#show_more_feeds_div').hide();
                    }
                    hideUILoader_nodialog();
                }
            });
        });

    });

    var ajax_req_feeds = null;
    function show_more_feeds(page) {
        if (ajax_req_feeds != null) {
            ajax_req_feeds.abort();
        }
        showUILoader_nodialog();
        ajax_req_feeds = $.ajax({
            type: 'get',
            url: base_url + 'logged/my_photos/photos_ajax_pagination/<?= $profile_id ?>' + '/' + page,
            dataType: 'json',
            success: function(data, status) {

                hideUILoader_nodialog();
                if (data.html != '') {
                    $('#result_div').append(data.html);
                    $('#show_more_feeds_link').attr('page_value', data.current_page);
                }
                else {
                    $('#result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Photo.</p></div>');
                    $('#show_more_feeds_div').hide();
                }

                if (data.view_more == false)
                {

                    $('#result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Photo.</p></div>');
                    $('#show_more_feeds_div').hide();
                }

            }	// end of success function...
        });
    }
</script>

<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->
</div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <!--<div id="mid_content"> -->
        <!-- latest news -->
        <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
        <!-- /latest news -->
        <div class="clr"></div>
        <!-- main container -->
        <div id="main_container">
            <!-- left container -->
            <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
            <!-- /left container -->
            <!-- mid container -->
<!--            <form id="hhj"  method="post" action="<?= base_url() . 'logged/my-photos/index' ?>"  enctype="multipart/form-data">
                <div class="lable01">Browse Photo:</div> 
                <div class="field01">
                    <input name="s_photo" id="s_photo" type="file" />
                    <span id="err_photo" class="error-message"></span>  
                </div>
                <input type="submit" value="upload">
            </form>-->
            <div id="mid_container">
                <div class="page_heading">
                    <div class="left"><img src="images/icons/photo.png" alt="" /> Photos</div>
                </div>
                <!--sub page links -->
                <div class="link-div" style="margin-top:0px;">
                    <ul>
                        <li><a href="manage-my-photo.html"><span>Manage My Photo Albums</span> </a> </li>
                        <li><a href="create-photo-album.html"><span>Create Photo Album</span></a></li>
                        <li><a href="javascript:void(0);" onclick="return show_dialog('upload_photo')"><span>Upload Photo</span></a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <!--/sub page links -->

                <div class="page_heading">
                    <div class="left"><img src="images/icons/photo.png" alt="" /> My  Albums (<?= $total_albums ?>)</div>
                </div>



                <div class="arrow_btm"></div>
                <DIV id="result_albums_section">
                    <?= $album_result_content ?>
                </DIV>




                <div id="single_photo_album_section">
                </div>


                <div class="page_heading">

                    <div class="left"><img src="images/icons/photo1.png" alt="" /> My Photos (<?= $total_photos ?>)</div>
                    <div class="right">
                        <img alt="" src="images/icons/search.png" /> <a class="blue_link art-search" href="javascript:void(0);"><strong>Search</strong></a>
                    </div>
                    <div class="clr"></div>
                </div>


                <div class="section01 art-search-section">
                    <form id="frm_search" onsubmit="return false;" method="post" >
                        <label class="lable-txt-nw">Name</label>
                        <input type="text" class="Card-Holder-Name" name="txt_title" />
                        <br class="clear"/>
                        <div class="lable-txt-input"> 
                            <input type="submit" class="yellow-btn float-right" value="Search" name="" />
                        </div>
                        <br class="clear"/>
                        <input type="hidden" value="Y" name="search_basic" />
                    </form>
                </div>


                <div class="arrow_btm"></div>
                <div class="div_content" style=" margin-top:0px;">

                    <DIV id="result_div" >
                        <?= $result_content ?>
                    </DIV>
                    <?php if ($no_of_result == 0): ?>
                        <div class="shade_box_01" style="padding-top:5px;" id="no_tweets"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Photo.</p></div></div>
                    <?php endif; ?>	
                    <?php if ($no_of_result > $pagination_per_page): ?>

                        <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?= $current_page_1 ?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
                    <?php endif; ?>

                </div>

            </div>                 
            <!-- /mid container -->
            <!-- right container -->
            <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
            <!-- /right container -->
        </div>
        <!-- /main container -->
        <div class="clr"></div>
        <!--</div> -->
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<!-- /lightbox SECTION -->
<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>
<?php include(APPPATH . "views/logged/photos/blocks/upload_photo_popup_homepage.phtml"); ?>
<?php include(APPPATH . "views/logged/photos/blocks/upload_multi_photo_popup_homepage.phtml"); ?>



<!--popup one start-->
<div class="lightbox delete-msg-popup" style="width:245px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?= base_url() ?>images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading" style="margin-bottom:0px;">
            <div class="left">
                <h4>Delete Selected Photos</h4>
            </div>
        </div>
        <div class="shade_box_white" style="padding:8px 0px;">
            <div style="padding-bottom:10px;">
                <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete these photos?</p>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                <input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_messages()"/>
                <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
            </form>   
            <div class="clr"></div>
        </div>

    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->


<script type="text/javascript">
    $(function() {
        $('.art-search').click(function() {

            $('.art-search-section').stop(true, true).slideToggle('slow');
        });

    })



</script>

