<form id="frmUploadPhoto"  method="post" action="<?=base_url().'logged/my_photos/add_photo'?>" onsubmit="return false;" enctype="multipart/form-data">
<div class="lightbox upload_multi_photo" style="width:480px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/photo.png" alt="" /> Upload Multiple Photo </h4></div></div>
               <div class="frm_box">
                
                 <div class="lable01">Browse Photo:</div> 
                 <div class="field01">
                 <input name="s_photo" id="s_photo" type="file" />
                 <span id="err_photo" class="error_msg"></span>  
                 </div>
                 <div class="clr"></div>
                 
                 <div class="lable01">Select Album:</div> 
                 <div class="field01"> 
                 <select name="select_album1" id="select_album1" style="width:260px;">
                 		<option value="-1">Select</option>
                        <option value="new_album">[New Album]</option>
                     <?php if(count($arr_albums)>0):
					 		foreach($arr_albums as $photo_album):?>
                     		<!--<option>[New Album]</option>-->
                            <option value="<?=$photo_album['id']?>"><?=$photo_album['s_name']?></option>
                     <?php 	endforeach;
					 		endif;?>
                </select>
                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        $("#select_album1").msDropDown();
                        $("#select_album1").hide();
                    })
                </script> 
                <span id="err_album1" class="error_msg"></span> 
                </div>
                 <div class="clr"></div>
                 
                 <div class="lable01">New Album Name:</div> 
                 <div class="field01">
                 <input name="txt_album_name" id="txt_album_name" type="text" /> 
                 <span id="err_album_name" class="error_msg"></span> 
                 </div>
                 <div class="clr"></div>
                 
                 <div class="lable01">&nbsp;</div> 
                 <div class="field01">
                 <input name="add_photo_btn" id="add_photo_btn" type="submit" value="Upload" class="btn" />
                 <span id="photo_loading"></span>
                 </div>
                 <div class="clr"></div>
               </div>
          
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
</form>