<div>
                                   <div id="4">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/job.png" alt=" " />  Work</h4> </div>
                                        <div class="right"><img src="images/icons/edit.png" alt=" " />  <a onclick="showDiv('4')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                     <?php
                                        
                                     
                                        $count=count($arr_profile_info['work_arr']);
                                        if ($count==0)
                                            $count=1;
                                      
                                        for($i=0;$i<$count;$i++)    :
                                            $country  = $arr_profile_info["work_arr"][$i]["s_employer_country"];
                                            $state    = $arr_profile_info["work_arr"][$i]["s_employer_state"];
                                            $city     = $arr_profile_info["work_arr"][$i]["s_employer_city"];
                                            
                                            /*$address  = (!empty($country))? $country:'';
                                            $address .= (!empty($state))? ', '.$state: '';
                                            $address .= (!empty($city))? ', '.$city: '';
                                            */                                           
                                            
                                            $work_address=array();
                                            if(!empty($country))    
                                                $work_address['country']=$country;
                                            if(!empty($state))
                                                $work_address['state']=$state;
                                            if(!empty($city))
                                                $work_address['city']=$city;
                                            
                                            $address = implode(', ',$work_address);
                                            
                                            $work_experience_year_from = $arr_profile_info['work_arr'][$i]['s_experience_year_from'];
                                            $work_experience_month_from = $arr_profile_info['work_arr'][$i]['i_experience_month_from'];
                                            $work_experience_year_to = $arr_profile_info['work_arr'][$i]['s_experience_year_to'];
                                            $work_experience_month_to = $arr_profile_info['work_arr'][$i]['i_experience_month_to'];
                                            
                                            if($work_experience_year_from=='-1')
                                            {
                                                $work_experience_month_from=-1;
                                                $experience_from = "";
                                            }
                                                
                                            else
                                                $experience_from = $work_experience_year_from;
                                                
                                            $experience_to= " to ";
                                            if($arr_profile_info['work_arr'][$i]['e_is_current_employer']=='yes')
                                                $experience_to .= "till now";
                                            else
                                                $experience_to .= $work_experience_year_to;
                                                
                                            
                                            
                                            
                                     ?>
                                      
                                         <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                            <div class="lable01">Employer:</div>  
                                            <div class="field01"><?=$arr_profile_info["work_arr"][$i]["s_employer_name"]?></div> 
                                            <div class="clr"></div>
                                            <div class="lable01">Work Place:</div>  
                                            <div class="field01"><?=$address;?></div> 
                                            <div class="clr"></div>
                                            <div class="lable01">Position:</div>  
                                            <div class="field01"><?=$arr_profile_info["work_arr"][$i]["s_position"];?></div> 
                                            <div class="clr"></div>
                                            <div class="lable01">Period:</div>  
                                            <div class="field01"><?php echo $experience_from.$experience_to;?></div> 
                                            <div class="clr"></div>
                                         </div>
                                      <?php
                                         endfor;
                                      ?>
                                   </div>
                                   <div id="jason4" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/job.png" alt=" " />  Work</h4> </div>
                                     </div>
                                     <form id="frmManageWorkProfile"  method="post" action="modify-my-profile-work-info-ajax" onsubmit="return modify_my_work_profile_ajax()" enctype="multipart/form-data">
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                    
                                    <?php
                                        
                                        for($i=0;$i<$count;$i++)   :
                                                   
                                    ?>
                                   
                                    <!------------------------work div----------------------------->
                                    <div id="<?php echo (($i>0)? 'work_div_'.($i+1):'work_div_1')?>"> 
                                    <?php 
                                        if($i>0 && $i<$count)
                                        {
                                            $j= $i+1;

                                            echo "<h4 class='sepration'></h4><a class='close' href='javascript:void(0);' style='margin:5px;' onclick=\"closeExtraWorkDiv('work_div', $j)\" ><img src='images/icons/close.png' alt=''></a>";
                                        }
                                    ?>
                                      <div class="lable01">Employer:</div>  
                                        <div class="field01"><input name="txt_work_company[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_name"])? $arr_profile_info["work_arr"][$i]["s_employer_name"]: '' ?>" style="width:230px;" /> </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work City:</div>  
                                        <div class="field01"><input name="txt_work_city[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_city"])? $arr_profile_info["work_arr"][$i]["s_employer_city"]: '' ?>" style="width:230px;" /></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work State:</div>  
                                        <div class="field01"><input name="txt_work_state[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_state"])? $arr_profile_info["work_arr"][$i]["s_employer_state"]: '' ?>"  style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work Country:</div>  
                                        <div class="field01"><input name="txt_work_country[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_country"])? $arr_profile_info["work_arr"][$i]["s_employer_country"]: '' ?>" style="width:230px;" /></div> 
                                        <div class="clr"></div> 
                                        <div class="lable01">Position:</div>  
                                        <div class="field01"><input name="txt_work_position[]" type="text"  value="<?=isset($arr_profile_info["work_arr"][$i]["s_position"])? $arr_profile_info["work_arr"][$i]["s_position"]: '' ?>" style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Period:</div>  
                                         <div class="field01" >
                                          
                                          <select name="mnth_from[]" class="profile_combo mnth_from" style="width:60px;">
                                             <option value="-1">Select</option>
                                             <?php echo makeOptionMonth(isset($arr_profile_info["work_arr"][$i]["i_experience_month_from"])? $arr_profile_info["work_arr"][$i]["i_experience_month_from"]:'')?> 
                                            </select>
                                               <script type="text/javascript">
                                                    $(document).ready(function(arg) {
                                                        $(".profile_combo").msDropDown();
                                                        $(".profile_combo").hide();         
                                                    })
                                                </script>
                                          
                                        <select name="year_from[]" class="profile_combo year_from" style="width:60px;">
                                       			<option value="-1">Select</option>
                                            	 <?=makeOptionYear(isset($arr_profile_info["work_arr"][$i]["s_experience_year_from"])? $arr_profile_info["work_arr"][$i]["s_experience_year_from"]:'')?>
                                         </select>
                                         
                                         
                                         <span class="left"> &nbsp; To  &nbsp;</span>
                                         <select name="mnth_to[]" class="profile_combo mnth_to" style="width:60px;" <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo "disabled='disabled'";?>>
                                             <option value="-1">Select</option>
                                             <?php echo makeOptionMonth(isset($arr_profile_info["work_arr"][$i]["i_experience_month_to"])? $arr_profile_info["work_arr"][$i]["i_experience_month_to"]:'');?> 
                                            </select>
                         
                                           
                                          
                                         <select name="year_to[]" class="profile_combo year_to" style="width:60px;" <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo "disabled='disabled'";?>>
                                       			<option value="-1">Select</option>
                                            	 <?=makeOptionYear(isset($arr_profile_info["work_arr"][$i]["s_experience_year_to"])? $arr_profile_info["work_arr"][$i]["s_experience_year_to"]:'')?>
                                         </select>
                                   

                                         </div>
                                      
                                         
                                        <div class="clr"></div>
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01">
                                            <input name="is_current_employer" type="radio" class="radio_cur_emp"  onclick="return current_emp(<?php echo ($i+1)?>);"  <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo "checked";?> value="<?= $arr_profile_info["work_arr"][$i]["id"]; ?>"  /> Current Employer
                                        </div>
                                        
                                       
                                        
                                        <input type="hidden" name="db_id[]" id="dbId" value="<?php echo isset($arr_profile_info["work_arr"][$i]["id"])? $arr_profile_info["work_arr"][$i]['id']: '0'?>">
                                        </div>  <!------------------------/work div----------------------------->
                                        <?php
                                            endfor;
                                        ?>
                                        <script type="text/javascript">
                                         /*   $(document).ready(function(arg) {
                                                $.datepicker.setDefaults($.datepicker.regional['']);
                                                $(".date_work_from").datepicker($.datepicker.regional['en']);
                                                $(".date_work_to").datepicker($.datepicker.regional['en']);
                                          
                                            });    */ 
                                        </script>
                                        <div id="add_more_work_div">    </div>
                                        
                                         <input type="hidden" name= "total_work_divs" id="work_div_h" value="<?php echo $count;?>" />
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01" style="text-align:right;width:250px;"> 
                                             <a href="javascript:void(0);" id="add_extra_work"   class="blue_link" onClick="add_extra_work_div()"><strong>Add More..</strong></a>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                        <input type="hidden" name="is_work_submitted" id="is_work_submitted" value="Y" />
                                        <input name="" type="submit" value="Save"  class="btn" />
                                        <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('4')"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                     </form>
                                  </div>
                              </div>