<?php /*?><div class="lightbox view_slideshow" style="width:470px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/slideshow.png" alt="" /> Slideshow </h4></div></div>
        
              <script type="text/javascript">
                    stepcarousel.setup({
                        galleryid: 'bandContainer1', //id of carousel DIV
                        beltclass: 'belt', //class of inner "belt" DIV containing all the panel DIVs
                        panelclass: 'thumbnails', //class of panel DIVs each holding content
                        autostep: {enable:false, moveby:1, pause:3000},
                        panelbehavior: {speed:500, wraparound:true, persist:false},
                        defaultbuttons: {enable: false, moveby: 1, leftnav: ['http://i34.tinypic.com/317e0s5.gif', -5, 80], rightnav: ['http://i38.tinypic.com/33o7di8.gif', -20, 80]},
                        statusvars: ['statusA', 'statusB', 'statusC'], //register 3 variables that contain current panel (start), current panel (last), and total panels
                        contenttype: ['inline'] //content setting ['inline'] or ['external', 'path_to_external_file']
                    })
                </script>
              <img src="images/arr_l.png" alt=""  class="scroller_arrow01"  onclick="javascript:stepcarousel.stepBy('bandContainer1', -1)"/>
              <div id="bandContainer1" class="bandContainer_slideshow">
                    <div class="belt">
                   		  <div class="thumbnails"><img src="images/house.jpg" alt="" /></div>
						  <div class="thumbnails"><img src="images/lcd.jpg" alt="" /></div>
                    </div>
              </div>
              <img src="images/arr_r.png" alt=""  class="scroller_arrow01" onclick="javascript:stepcarousel.stepBy('bandContainer1', 1)" style="float:right;" /> 
        <div class="clr"></div>
        
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div><?php */?>
