<script type="text/javascript">
$(document).ready(function() {
	
	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  show_No_red_Add_Load,  // pre-submit callback 
        success:       validateAddNoredirectFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#frmNUploadPhoto').submit(function() {
	
        $(this).ajaxSubmit(options);
		
        return false;
		
    });

});

function show_No_red_Add_Load()
{
  $('#add_Nphoto_btn').val('Uploading...');
  $('#photo_Nloading').html('<img id="img_holder" src="<?=base_url()?>images/loading_small.gif" align="absmiddle" />');
  
}


// validate ajax-submission...
function validateAddNoredirectFrm(data)
{
	
   var data = JSON.parse(data);//alert(data.html);
	
	if(data.success==false) 
	{
		
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#add_Nphoto_btn').attr('disabled','');
		$('#add_Nphoto_btn').val('Upload');
		$('#photo_Nloading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		
	}
	else {
		  // clearing form
		  $('#frmNUploadPhoto')[0].reset();
		  $('#add_Nphoto_btn').val('Upload');
		  hide_dialog();
		  $('#album_div').html(base64_decode(data.html));
		  showUIMsg(data.msg);
		  //window.location.href=document.URL;
	}
	$('#frmNUploadPhoto')[0].reset();
	$('#photo_Nloading').html('');
	//hideLoading();
				
}
function clear_box(){
		$('#frmNUploadPhoto')[0].reset();
		  $('.error-message').hide();
}
</script>
<script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#txt_desc').keyup(function(){
            limitChars('txt_desc', 250, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('txt_desc',250, '');
    
 
});
</script>

<form id="frmNUploadPhoto"  method="post" action="<?=base_url().'logged/organize_photo/add_photo_ajax'?>" onsubmit="return false;" enctype="multipart/form-data">
<div class="lightbox upload_photo" style="width:480px;">
    <div class="close"><a href="javascript:void(0)" onclick="clear_box();hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    
    <div class="top"><div>&nbsp;</div></div>
       <div class="mid">
        <div class="heading"><div class="left"><h4><img src="images/icons/photo.png" alt="" /> Upload Photo </h4></div></div>
               <div class="frm_box">
               
              <?php /*?> <div style="color:#004084; font-weight:bold; font-size:12px;"><a href="javascript:void(0);" onclick="hide_dialog('upload_photo'); show_dialog('multiple_album'); " >Upload Multiple Photo</a></div><?php */?>
               
               
                 <div class="lable01">Title:</div> 
                 <div class="field01">
                 <input name="txt_title" id="txt_title" type="text" />
                 <span id="err_title" class="error-message"></span> 
                 </div>
                 <div class="clr"></div>
               
                 <div class="lable01">Description:</div> 
                 <div class="field01">
                 <textarea name="txt_desc"  id="txt_desc" cols="" rows="" style="height:80px;" maxlength="250"></textarea>
                 <span style="font-size: 11px;font-style: italic;line-height: 13px;">(Max 250 characters.)</span>
                  </div>
                 <div class="clr"></div>
                 
                 <div class="lable01">Browse Photo:</div> 
                 <div class="field01">
                 <input name="s_photo" id="s_photo" type="file" />
                 <span id="err_photo" class="error-message"></span>  
                 </div>
                 <div class="clr"></div>
                 
                 <div class="lable01">Select Album:</div> 
                 <div class="field01"> 
                 <select name="select_album1" id="select_album1" style="width:260px;">
                       <?php /*?> <option value="new_album">[New Album]</option><?php */?>
                     <?php if(count($all_photo_albums)>0):
					 		echo '<option value="-1">Select</option>';
					 		foreach($all_photo_albums as $photo_album):
							
								$sel = ($current_album_id == $photo_album['id'])?'selected ="selected"':'';
					  ?>
                            
                     		<!--<option>[New Album]</option>-->
                            <option value="<?=$photo_album['id']?>" <?=$sel?>><?=$photo_album['s_name']?></option>
                     <?php 	endforeach;
						  	else:
							echo '<option value="0">No Albums available, Please create.</option>';
						   endif;
					 ?>
                </select>
               <?php /*?> <script type="text/javascript">
                    $(document).ready(function(arg) {
                        $("#select_album1").msDropDown();
                        $("#select_album1").hide();
                    })
                </script> <?php */?>
                <span id="err_album1" class="error-message"></span> 
                </div>
                 <div class="clr"></div>
                 
                 <?php /*?><div class="lable01">New Album Name:</div> 
                 <div class="field01">
                 <input name="txt_album_name" id="txt_album_name" type="text" /> 
                 <span id="err_album_name" class="error-message"></span> 
                 </div>
                 <div class="clr"></div><?php */?>
                 
                 <div class="lable01">&nbsp;</div> 
                 <div class="field01">
                 <?php if(count($all_photo_albums)>0):?>
                 	<input name="add_Nphoto_btn" id="add_Nphoto_btn" type="submit" value="Upload" class="btn" />
                 <?php else:?>
                 	<input name="cancel" type="button" value="Cancel" class="btn" onclick="clear_box();hide_dialog();" />
                 <?php endif;?>
                 <span id="photo_Nloading"></span>
                 </div>
                 <div class="clr"></div>
               </div>
          
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
</form>