<?php
$max_iamge_size = $max_file_upload_size;
?>
<script type="text/javascript">
    var g_controller_url = base_url + "logged/my_photos/";
    var iamge_size;
    var photo_id = null;
    $(document).ready(function() {

        // for AJAX page-submission...
        var options = {
            beforeSubmit: showLoadPhoto, // pre-submit callback 
            success: validateFrmPhoto // post-submit callback 
        };
        $('#s_photo').change(function() {
            var f = this.files[0];
            iamge_size = f.size || f.fileSize;
            //alert(iamge_size);
        })
        // bind to the form's submit event 
        $('#frmUploadPhoto').submit(function() {
            var max_file_size = '<?php echo $max_iamge_size; ?>';
            //alert(max_file_size);
            if (iamge_size > max_file_size) {
                $('#err_photo').html("Maximum file upload size is 2 MB");
            } else
            {
                $(this).ajaxSubmit(options);
                return false;
            }

        });

    });

    function showLoadPhoto()
    {
        // $('#add_photo_btn').attr('disabled','disabled');
        $('#add_photo_btn').val('Uploading...');
        $('#photo_loading').html('<img id="img_holder" src="<?= base_url() ?>images/loading_small.gif" align="absmiddle" />');

    }


// validate ajax-submission...
    function validateFrmPhoto(data)
    {
        //alert( data);
        var data = JSON.parse(data);
        if (data.success == false)
        {

            $('.error-message').each(function(i) {
                $(this).attr('style', 'display:none');
            });

            //$('#add_photo_btn').attr('disabled','');
            $('#add_photo_btn').val('Upload');
            $('#photo_loading').html('');

            for (var id in data.arr_messages) {
                //alert(data.arr_messages[id]);
                if ($('#err_' + id) != null) {
                    $('#err_' + id).html(data.arr_messages[id]);
                    $('#err_' + id).css('display', 'block');
                }
            }


        }
        else {
            // clearing form
            $('#frmUploadPhoto')[0].reset();
            //$('#select_album1').val($('options:first', '#select_album1').val());
            // $('#add_photo_btn').attr('disabled','');
            $('#add_photo_btn').val('Upload');
            hide_dialog();
            showUIMsg(data.msg);
            window.location.href = document.URL;// "<?= $_SERVER['HTTP_REFERER'] ?>";//document.URL;
        }
        $('#photo_loading').html('');
        //hideLoading();

    }
    function clear_box(mode) {
        $('#frmUploadPhoto')[0].reset();
        $('.error-message').hide();
    }
</script>
<script type="text/javascript">
    $(document).ready(function() {

        //counting the left characters in comment
        function limitChars(textid, limit, infodiv)
        {
            var text = $('#' + textid).val();
            var textlength = text.length;
            if (textlength > limit)
            {
                $('#' + textid).val(text.substr(0, limit));
                return false;
            }
            else
            {

                return true;
            }
        }


        $(function() {
            $('#txt_add_desc').keyup(function() {
                limitChars('txt_add_desc', 250, '');
            });
        });


        //// just to show correct no. of chracters left while the page is loaded...
        limitChars('txt_add_desc', 250, '');


    });
</script>

<form id="frmUploadPhoto"  method="post" action="<?= base_url() . 'index.php/logged/my_photos/add_photo' ?>" onsubmit="return false;" enctype="multipart/form-data">
    <div class="lightbox upload_photo" style="width:480px;">
        <div class="close"><a href="javascript:void(0)" onclick="clear_box();
                hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>

        <div class="top"><div>&nbsp;</div></div>
        <div class="mid">
            <div class="heading"><div class="left"><h4><img src="images/icons/photo.png" alt="" /> Upload Photo </h4></div></div>
            <div class="frm_box">

                <?php /* ?> <div style="color:#004084; font-weight:bold; font-size:12px;"><a href="javascript:void(0);" onclick="hide_dialog('upload_photo'); show_dialog('multiple_album'); " >Upload Multiple Photo</a></div><?php */ ?>


                <div class="lable01">Title:</div> 
                <div class="field01">
                    <input name="txt_title" id="txt_title" type="text" />
                    <span id="err_title" class="error-message"></span> 
                </div>
                <div class="clr"></div>

                <div class="lable01">Description:</div> 
                <div class="field01">
                    <textarea name="txt_add_desc"  id="txt_add_desc" style="height:80px;" maxlength="250"></textarea>
                    <span style="font-size: 11px;font-style: italic;line-height: 13px;">(Max 250 characters.)</span>
                </div>
                <div class="clr"></div>

                <div class="lable01">Browse Photo:</div> 
                <div class="field01">
                    <input name="s_photo" id="s_photo" type="file" />
                    <span id="err_photo" class="error-message"></span>  
                </div>
                <div class="clr"></div>

                <div class="lable01">Select Album:</div> 
                <div class="field01"> 
                    <select name="select_album1" id="select_album1" style="width:260px;">
                        <?php /* ?> <option value="new_album">[New Album]</option><?php */ ?>
                        <?php
                        if (count($all_photo_albums) > 0):
                            echo '<option value="-1">Select</option>';
                            foreach ($all_photo_albums as $photo_album):

                                $sel = ($current_album_id == $photo_album['id']) ? 'selected ="selected"' : '';
                                ?>

                                <!--<option>[New Album]</option>-->
                                <option value="<?= $photo_album['id'] ?>" <?= $sel ?>><?= $photo_album['s_name'] ?></option>
                                <?php
                            endforeach;
                        else:
                            echo '<option value="0">No Albums available, Please create.</option>';
                        endif;
                        ?>
                    </select>
                    <?php /* ?> <script type="text/javascript">
                      $(document).ready(function(arg) {
                      $("#select_album1").msDropDown();
                      $("#select_album1").hide();
                      })
                      </script> <?php */ ?>
                    <span id="err_album1" class="error-message"></span> 
                </div>
                <div class="clr"></div>

                <?php /* ?><div class="lable01">New Album Name:</div> 
                  <div class="field01">
                  <input name="txt_album_name" id="txt_album_name" type="text" />
                  <span id="err_album_name" class="error-message"></span>
                  </div>
                  <div class="clr"></div><?php */ ?>

                <div class="lable01">&nbsp;</div> 
                <div class="field01">
                    <?php if (count($all_photo_albums) > 0): ?>
                        <input name="add_photo_btn" id="add_photo_btn" type="submit" value="Upload" class="btn" />
                    <?php else: ?>
                        <input name="cancel" type="button" value="Cancel" class="btn" onclick="clear_box();
                                    hide_dialog();" />
                           <?php endif; ?>
                    <span id="photo_loading"></span>
                </div>
                <div class="clr"></div>
            </div>

        </div>
        <div class="bot"><div>&nbsp;</div></div>
    </div>
</form>