<!-- header -->
<?php
	include(APPPATH ."views/layouts/church_logged_header.phtml");
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>
<div class="container timeline-overflow">
<?php if(decrypt($this->session->userdata('user_id')) == $church_admin->ch_admin_id) { ?>
  <div class="post-section">
  	<div class="post-block">
	 <form name="public_wall_post_form" id="public_wall_post_form"  method="post" class="wall-comment-form" enctype="multipart/form-data" action="<?=base_url().'logged/church_wall/post_his_church_wall'?>" onsubmit="return false;">
    	<div class="profile-pic"><img src="images/profile-pic.png" alt="Profile Pic" width="82" height="77"></div>
		<!-- wall message -->
        <textarea placeholder="Post In Wall..." name="church_post_message" ></textarea>
		<!-- wall message -->
		 <!-- upload image div start  -->
                <div class="upload-image" >
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide(); $('.camera-ico').children('span').removeClass('active');" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Upload Image :</label>
                    <input name="btn_upload" id="btn_upload" type="file" size="40" />
                    <br class="clr"/>
                    <div id="all_photos">
                  
                    </div>
            
                  <div id="hdnflds" >
                  </div>
                 
                 </div>   
                      
                <!--upload image div end -->
                
                
                
               <!-- upload video div start -->
                <div class="upload-video">
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();$('.video-ico').children('span').removeClass('active');" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Video Url :</label><div class="video-url"><input name="txt_video_url" id="txt_video_url" type="text" /></div>
					<ul class="video-logo" >
					<li><img src="<?=base_url()?>/images/YouTube.png"title="YouTube" alt="YouTube"></li>
					<li><img src="<?=base_url()?>/images/Vimeo.png"title="Vimeo" alt="Vimeo"></li>
					<li><img src="<?=base_url()?>/images/DailyMotion.png"title="DailyMotion" alt="DailyMotion"></li>
					<li><img src="<?=base_url()?>/images/Viadeo.png"title="Viadeo" alt="Viadeo"></li>
					</ul>
                    <br class="clr"/>
                    <div id="all_videos">
                      <?php /*?><div class="view-thumb"><img src="images/photo-img01.jpg" alt="photo" width="60" height="60" /><a href="javascript:void(0);" class="remove" title="Remove Video"></a></div>
                     <?php */?>
                    </div>
                    
                     <div id="hdnvideoflds" >
                     </div>
                  
                </div>
               <!-- upload video div end -->
			   
			   <!-- upload video div start -->
                <div class="upload-audio">
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();$('.audio-ico').children('span').removeClass('active');" style="float:right;color:#013d62">Hide[-]</a>
                    <p style="font-size:13px;padding-bottom:12px;color:'#333'">Audio Url(Put Soundcloud embeded code here) :</p><div class="video-url"><input name="txt_audio_url" id="txt_audio_url" type="text" /></div>
                    <div id="all_videos">
                      <?php /*?><div class="view-thumb"><img src="images/photo-img01.jpg" alt="photo" width="60" height="60" /><a href="javascript:void(0);" class="remove" title="Remove Video"></a></div>
                     <?php */?>
                    </div>
                    
                     <div id="hdnvideoflds" >
                     </div>
                  
                </div>
               <!-- upload video div end -->
        <div class="attch-part"><label>Attach:</label><span>
        <a href="javascript:void(0);" title="Upload Image" onclick="$('.upload-video').hide();$('.upload-audio').hide();$('.upload-image').show();$('.camera-ico').children('span').addClass('active');$('.video-ico,.audio-ico').children('span').removeClass('active');" class="camera-ico"><span>&nbsp;</span></a>
        <a href="javascript:void(0);" title="Share Video" onclick="$('.upload-video').show();$('.upload-audio').hide();$('.upload-image').hide();$('.video-ico').children('span').addClass('active');$('.camera-ico,.audio-ico').children('span').removeClass('active');" class="video-ico"><span>&nbsp;</span></a>
        <a href="javascript:void(0);" title="Share Audio" onclick="$('.upload-video').hide();$('.upload-audio').show();$('.upload-image').hide();$('.audio-ico').children('span').addClass('active');$('.video-ico,.camera-ico').children('span').removeClass('active');" class="audio-ico" ><span>&nbsp;</span></a>        
        </span></div>
        
        <div class="post-update"><input type="submit" class="post-btn" value="Post"></div>
		</form>
    </div>	
  </div>
<?php } ?>
<div class="timeline-main">
  <?php if(!empty($result_newsfeed_content)){ ?>
  <?= $result_newsfeed_content ?>
  <?php } ?>
  <div class="clear"></div>
</div>

</div>

<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->

<script type="text/javascript">
$(document).ready(function() {
	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoading,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
    // bind to the form's submit event 
    $('#public_wall_post_form').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });
});

function validateFrm(jsondata)
{
	//alert(jsondata.feed);
	var data = JSON.parse(jsondata);
	//alert(data.msg); alert(data.vid_msg);
	if(data.success==false) 
	{
		hideLoading(); 
		if(data.vid_msg == ''){
			showUIMsg(data.msg);
		}else{
			showUIMsg(data.vid_msg);
		}
	}
	else {
		hideLoading(); 
		
	
		showUIMsg(data.msg);		
		location.reload();
		//window.location.href=g_controller_url;
	}
}
</script>
