<?php
	include(APPPATH ."views/layouts/church_logged_header.phtml");
	//pr($church_activity_feed_comments);
?>

<!-- CONTENT SECTION -->
<div class="container">
  
  <div class="main-page">
  	<h3 class="page-heading">Activity</h3>
    <div class="activity-left">
    	<ul class="left-list">
        <li><a href="activity-comments.html" class="active">Manage Comments</a></li>        
        <li><a href="activity-request.html">Requests</a></li>
        <li><a href="activity-invitations.html">Invitations</a></li>
        <li><a href="activity-members.html">Community Members</a></li>
        </ul>
    </div>
    <div class="activity-right">
	<?php 
	
	if($church_activity_feed_comments) { 
	foreach($church_activity_feed_comments As $church_activity_feed_comment) { 
			$data_arr = json_decode($church_activity_feed_comment->feedtitle);
			//pr($data_arr);
	//pr($data_arr->photo);
	if ( $church_activity_feed_comment->post_type == 1 ) {
	?>
    	<div class="activity-comment-box" id="wall_activity-comment-box<?php echo $church_activity_feed_comment->id; ?>">
        	<h4><a href="javascript:void(0);"><?php echo $church_activity_feed_comment->member_name; ?></a> Posted a Comment on a wall post.</h4>
            <div class="timeline-part">
        	<p><?php echo $data_arr->message; ?></p>
			<?php if(!empty($data_arr->photo) && count($data_arr->photo) < 2){
			//echo 'I'.count($data_arr->photo);
			//pr($data_arr->photo);
			foreach($data_arr->photo as $key=>$photo_val){
			$IMG = base_url()."uploads/church_wall/".getThumbName($photo_val,'big');
			?>
            <figure><img src="<?=$IMG?>" alt="Prayer" width="477" height="244"></figure>
			<?php }
			} else if(!empty($data_arr->photo) && count($data_arr->photo) > 2){?>
			<ul class="bxslider">
				<?php
			foreach($data_arr->photo as $key=>$photo_val){
			$IMG = base_url()."uploads/church_wall/".getThumbName($photo_val,'big');
			?>
			<li><img src="<?=$IMG?>" alt="Prayer" ></li>
			<?php 
			}
			?>
			</ul>
			<?php }?>
			<div class="comment-text">
            	<textarea name="wall_comment_txt" id="wall_comment_txt_<?php echo $church_activity_feed_comment->id; ?>" class="comment_message" height="20" width="40"><?php echo $church_activity_feed_comment->s_contents; ?></textarea> 
				<input type="button" name="save_comment" id="save_comment_<?php echo $church_activity_feed_comment->id; ?>" value="SAVE" onclick="javascript:save_comments('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');" style="display:none;"/>
           
			</div>
            <div class="edit-review"> <a href="javascript:comments_edit('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');">Edit</a> |  <a href="javascript:remove_comments('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');">Remove</a></div>
        </div>
		</div>
		<?php } 
		else if ( $church_activity_feed_comment->post_type == 2 ) { ?>
        <div class="activity-comment-box" id="ring_activity-comment-box<?php echo $church_activity_feed_comment->id; ?>">
        	<h4><a href="javascript:void(0);"><?php echo $church_activity_feed_comment->member_name; ?></a> Posted a Comment on a Ring.</h4>
            <h5>Ring Name: <span><?php echo $church_activity_feed_comment->feedtitle; ?></span></h5>
             <div class="comment-text">
            	<textarea name="ring_comment_txt" id="ring_comment_txt<?php echo $church_activity_feed_comment->id; ?>" class="comment_message" height="20" width="40"><?php echo $church_activity_feed_comment->s_contents; ?></textarea> 
				<input type="button" name="ring_save_comment" id="ring_save_comment_<?php echo $church_activity_feed_comment->id; ?>" value="SAVE" onclick="javascript:save_comments('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');" style="display:none;"/> 
            </div>
            
            <div class="edit-review"> <a href="javascript:comments_edit('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');">Edit</a> |  <a href="javascript:remove_comments('<?php echo $church_activity_feed_comment->id; ?>','<?php echo $church_activity_feed_comment->post_type; ?>');">Remove</a></div>
        </div>
        <?php } 
		} } else { 
		echo '<div class="activity-comment-box"><h4> No records found. </h4></div>';
		}
		?>
		
        
        <!--<div class="activity-comment-box">
        	<h4><a href="javascript:void(0);">John Smith</a> Posted a Comment on a Prayer Group.</h4>
            <h5>Prayer Group Name: <span>Prayer for Jesus</span></h5>
             <div class="comment-text">
            	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley book. 
            </div>
            
            <div class="edit-review"> <a href="javascript:void(0);">Edit</a> |  <a href="javascript:void(0);">Remove</a></div>
        </div>-->
        
        
        
        

    </div>
    <div class="clear"></div>
    
    
  </div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->
<script type="text/javascript">
$(document).ready(function(){
  $('.bxslider').bxSlider();
  
});
function comments_edit(id,post_type) {
	//$('#comment_text_'+user_id).attr("readonly",false,"important");
	showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
	if (post_type == 1) { 
		$('#wall_comment_txt_'+id).focus();
		$('#save_comment_'+id).show();
	} else { 
		$('#ring_comment_txt'+id).focus();
		$('#ring_save_comment_'+id).show();
	}
	hideUILoader_nodialog();
}
function save_comments(id,post_type) {
var base_url = '<?php echo base_url(); ?>';
showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
var wall_comment = '';
var ring_comment = '';
if (post_type == 1) {
var wall_comment = $('#wall_comment_txt_'+id).val();
} else { 
var ring_comment = $('#ring_comment_txt'+id).val();
}
$.ajax({
  url: base_url+'logged/church_activity_management/save_comment/',
  type: 'POST',
  data : {id:id,wall_comment:wall_comment,ring_comment:ring_comment,post_type:post_type},
  success: function(data) {
	if (post_type == 1) { 
		$('#save_comment_'+id).hide();
	} else {
		$('#ring_save_comment_'+id).hide();
	}
	hideUILoader_nodialog();
	//showUIMsg(data.msg);
  }
});

}

function remove_comments(id,post_type) {
var base_url = '<?php echo base_url(); ?>';
if(confirm('Are you sure to delete this comment?')){
$.ajax({
  url: base_url+'logged/church_activity_management/remove_comments/',
  type: 'POST',
  data : {id:id,post_type:post_type},
  success: function(response) {
	if (post_type == 1) {
		$('#wall_activity-comment-box'+id).remove();
	} else {
		$('#ring_activity-comment-box'+id).remove();
	}
  }
});
}
else {
	return false;
}

}
</script>


