<?php
	include(APPPATH ."views/layouts/church_admin_header.phtml");
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>

<div class="container-body">
    <div class="round-con">
        <?php
         
         $church_number =  get_church_ring_number_by_id($_SESSION['logged_church_id']);
        // echo $church_number;
        ?>
        <div class="right-round right-gray"><p><a href="<?= base_url() ?>church_member" style="text-decoration: none; color: #ffffff;">Community members</a> <br /><span><?=get_member_count_by_church_id($church_arr[0]->id)?></span></p></div>
        <div class="right-round right-gray"><p><a href="<?= base_url() ?>church-ring-list" style="text-decoration: none; color: #ffffff;">Rings </a><br /><span><?= $church_number ?></span></p></div>
        <div class="right-round right-gray"><p><a href="<?= base_url()."".$church_arr[0]->id ?>/church-prayer-group.html" style="text-decoration: none; color: #ffffff;">Prayer Groups</a>  <br /><span><?=get_prayer_group_count_by_church($church_arr[0]->id)?></span></p></div>
    </div>
    </div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


