<?php
	include(APPPATH ."views/layouts/church_admin_header.phtml");
?>
<script language="javascript">

</script>
<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>

<div class="container-body">
   <?php
	include(APPPATH ."views/layouts/church_admin_left.phtml");
?>
    <div class="right-panel">
    <h2>Sub Admin</h2>
   
    <div class="spacer"></div>
    <div><a title="Add New" class="add-button" href="<?php echo base_url().'church-addsubadmin'?>">Add New</a></div>
    <div class="spacer"></div>
    <div class="right-box">

            <?php
            if($member_arr)
            {
             ?>
             <ul>
                <li class="head">
                <span class="sl">S no.</span>
                <span class="name">Name</span>
                 <span class="joind-on">Joined on</span>
                <span class="email">Email</span>
                <span class="action">Action</span>
                <!--<span class="fileapprove">File approved/<br>Not Approved</span>-->
               
                </li>
                <?php
                $i = 1;
                foreach ($member_arr as $member) {
                    ?>
                     <li class="">
                    <span class="sl"><?php echo $i++; ?></span>
                    <span class="name"><?php echo $member->s_first_name.' '.$member->s_last_name?></span>
                    <span class="joind-on"><?php echo getShortDate($member->created_date,3)?></span>
                    <span class="email"><?php echo $member->s_email?></span>
                    <span class="action"><a href="<?php echo base_url().'church-editsubadmin/'.$member->mid?>">Edit</a></span>
                    
                    </li>
                    <?php
                }
               ?>
            </ul>

             <?php   
            }
             else
            {
                ?><li class="">No Records</li><?php
            }
            ?>
           
            
        <div class="spacer"></div>
        
     

    </div>
    
     
    
    </div>
    
    </div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


