<!-- header -->
<?php
  include(APPPATH ."views/layouts/church_logged_header.phtml");
  
?>


<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />
<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>
<script type="text/javascript">
$(function(){
		$("#friendSlct").multiselect().multiselectfilter();	
		$("#ringselect").multiselect().multiselectfilter();
		$("#netpalselect").multiselect().multiselectfilter();
		$("#ppselect").multiselect().multiselectfilter();	
		$("#pgselect").multiselect().multiselectfilter();
		$("#frndinv").multiselect().multiselectfilter();	
		$("#netpalinv").multiselect().multiselectfilter();
		$("#ppinv").multiselect().multiselectfilter();
		$("#pginv").multiselect().multiselectfilter();
		
	
	});
	
</script>
<script language="javascript">

var g_controller_url = base_url+"church-ring-list";

var photo_id = null;
$(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoad,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#ring_frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});

function showLoad()
{
 // $('#photo_album_btn').attr('disabled','disabled');
 	showUIMsg();
  $('#photo_album_btn').val('Creating...');
  
}


// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		showUIMsg(data.msg);	
	}
	else {
		
		showUIMsg(data.msg);		
		//window.location.href= "<?$_SERVER['HTTP_REFERER']?>";///document.URL;
		window.location.href= "<?php echo base_url().'church-ring-list'?>";
		
	}
	$('#sp_add_loading').html('');
	//hideLoading();
				
}





$(function(){
	$('#ring_desc_span').textCounter({
		target: '#ring_desc', // required: string
		count: 500, // optional: integer [defaults 140]
		alertAt: 20, // optional: integer [defaults 20]
		warnAt: 10, // optional: integer [defaults 0]
		stopAtLimit: true // optional: defaults to false
	});
	
});


</script>
<script type="text/javascript">
$(document).ready(function() {

	$('.send-pro-message').click(function(){
		var index=$(this).index();
		$('.new-wl > .comments-number ').css('display','none');
		$(this).next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	});
	
	 $('.wal-minus').click(function(){
			$(this).parents('.comments-number').slideUp('fast');
	 });
});
</script>

<!-- CONTENT SECTION -->

      <div class="container">
      <div class="main-page">
       <h3 class="page-heading">Rings</h3>
      <?php include(APPPATH . "views/layouts/church_admin_left_ring.phtml"); ?>
       <div class="activity-right">
           <form name="ring_frm" id="ring_frm" action="<?=base_url().'logged/church_ring/add_ring'?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">
                                <div  class="create-ring">
                                    <div class="lable01">Name: </div> 
                                    <div class="field03">
                                    <input name="ring_name" id="ring_name" type="text" />
                                    <span id="err_name" class="error-message"></span> 
                                    </div>  
                                    <div class="clr"></div>
                                    <div class="lable01">Description: </div>  
                                    <div class="field03">
                                    <!--<textarea name="ring_desc" id="ring_desc" cols="" rows="" style="width:300px; height:170px;"></textarea>-->
                                    <textarea name="ring_desc"  id="ring_desc" style="height:170px" onFocus="if(this.value=='Max 500 Char allowed') this.value='';" onBlur="if(this.value=='')this.value='Max 500 Char allowed'; " onkeypress="return restrict_carrige(event);"  >Max 500 Char allowed</textarea>
                                    <div class="clr"></div>
                                     <span id="ring_desc_span" class="pad-80 tcWarn" style="display:none;">0</span>
                                     
                                     <!--<span>500 characters</span>-->
                                    <span id="err_desc" class="error-message"></span> 
                                      <p style="float:left"><span id="text_count">0</span> Characters</p>
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable01">Category:</div>  
                                    <div class="field03">
                                    <select name="category" id="category" style="width:300px;" onchange="javascript:generateSubcat($(this).val())">
                                          <option value="">Please Select Category</option>
                                          <?php echo $category?>
                                    </select>
                                <span id="err_category" class="error-message"></span> 
                                       <?php /*?>   <script type="text/javascript">
                                              $(document).ready(function(arg) {
                                                  $("#category").msDropDown();
                                                  $("#category").hide();
                                              })
                                          </script><?php */?></div> 
                                          <div class="clr"></div>
                                          
                                          
                                          <DIV id="sub_cat" style="display:none;"></DIV>
                                          
                                            
                                          <div class="clr"></div>
                                          
                                          <DIV style="display:none;">
                                          <div class="lable01">&nbsp;</div>  
                                          <div class="field03" style="width:350px;">
                                            <input type="text" value="" name="requestcategory" id="requestcategory" />
                                              
                                              <input type="button" class="sml_btn" value="Sent request" onclick="sentRequestForCategory()" />
                                          </div> 
                                          </DIV>
                                          
                                          
                                          <div class="clr"></div>
                                          
                                          <div class="lable01">Logo:</div>  
                                          <div class="field03">
                                          <input name="ring_logo" type="file"  size="39" style="width:300px"/>
                                          <span id="err_logo" class="error-message"></span> 
                                          </div> 
                                          
                                          <!--<div class="clr"></div>
                                           <div class="lable01">Privacy Settings:</div>  
                                          <div class="field03">
                                          <select name="privacy_settings" id="privacy_settings" style="width:300px;">
                                                
                                                <option value="2">All User</option>
                                                <option value="1">Only user invited by you can join  </option>
                                          </select>
                                <span id="err_privacy_settings" class="error-message"></span> 
                                    <script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#privacy_settings").msDropDown();
                                            $("#privacy_settings").hide();
                                        })
                                    </script></div> -->
                                    <div class="clr"></div>
                                     <div class="lable01"> Invite Members :</div>  
                                    <div class="field03">
                                    
                                      <!--<input type="text" id="invite_frnd" name="invite_frnd" autocomplete="off" style="width:300px;" />
                                      <input type="hidden" id="h_friend_id"  name="h_friend_id" />-->
                                      <?php echo get_churchinvitation('ring');?>
                                         <span id="err_invite_frnd" class="error-message"></span> 
                    
                                    </div>
                                   
                                      
                                    
                                        <div class="clr"></div>
                                     <div class="lable01">&nbsp;</div>  
                                    <div class="field03">
                                      
                                      <input name="photo_album_btn"  id="photo_album_btn" type="submit" value="Create"  class="btn"/> 
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="location.href='<?php base_url()?>my-ring.html'" />
                                                                  
                                </div>
                                <div class="clr"></div>
                                <!--<strong>A user can create maximum <?=$MAX_GRP?> Rings.</strong>-->
                            
                             </form>
      </div>

</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
</div>

<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


<script type="text/javascript">
function sentRequestForCategory()
{
	showLoading();
	$.ajax({
        url : base_url+"logged/church_ring/send_cat_req",
        type : "post",
        data : ({'category':$('#requestcategory').val()}),
        dataType : 'json',
        success : function(data)
        {
			$('#requestcategory').val('');
            hideLoading();
            showUIMsg(data.msg);
        }
    });
}
var carriage_count = 0;
$(document).ready(function() {

  $('.link-reuqset').click(function(){
	  $(this).parent().next().next().slideToggle('slow');
  });
  var count=0;
//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
	
  var text = $('#'+textid).val(); 
  
  if(text == ''){
	  count = 0;
  }
 


if( count == 0)
{
	//alert (carriage_count)
  var textlength = 0;
}
else
{
 var textlength = text.length;
}
  $('#text_count').html(textlength);
  if(textlength > limit)
  {
  $('#'+textid).val(text.substr(0,limit));
  return false;
  }
  else
  {
  return true;
  }
  
}


$(function(){
  $('#ring_desc').keyup(function(){
	  count=1;
  limitChars('ring_desc', 500, '');
  });
  $('#ring_desc').keydown(function(){
	  count=1;
  limitChars('ring_desc', 500, '');
  });
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('ring_desc',500, '');
});

function restrict_carrige(e)
{
	/*//if(e.keyCode == 13)
	{
		$.ajax({
			type: 'post',
			url: base_url+'logged/prayer_wall/getCarriageCount',
			data: {'str':$('#ta_desc').val()},
			dataType: 'json',
	
			success: function (data, status) {
				
					if(data.count > 1){
						return false;
					}
				
				}	// end of success function...
		});
	}*/
	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));

	if(e.keyCode == 13){
		carriage_count++;
		console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >10){
		return false;
		//e.preventDefault();
	}
}
 function generateSubcat(id) { 
        showUILoader_nodialog();
        $.ajax({
            type: 'get',
            url: '<?= base_url() ?>logged/church_ring/generateSubCat_II' + '/' + id,
            dataType: 'json',
            success: function(data, status) {
                hideUILoader_nodialog();
                $('#sub_cat').html(base64_decode(data.html));
                $('#sub_cat').attr('style', 'display:block;');
            }	// end of success function...
        });
    }
</script>