<!-- header -->
<?php
	include(APPPATH ."views/layouts/church_logged_header.phtml");
	//pr($posted);
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>

<div class="container">
    <div class="main-page">
	<div class="content_area frm_box frm_box2" id="edit_church_about_info_frm">
                        	  <form name="frm_about_info" id="frm_about_info" action="" method="post" onsubmit="return post_frm_ajax_add(); return false;">
                                  <div class="lable02"><span class="red-mark">* </span>Title :</div>
                                  <div class="field02">
                                        <input name="txt_title" id="txt_title" type="text" value="<?= $posted['s_title']; ?>" maxlength="20" style="margin:0px;" />
                                   <div class="clr"></div>
                                  <span>(Max 20 characters.)</span>
                                  </div>
                                  <div class="error-message" id="err_title"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable02"><span class="red-mark">* </span> Content :</div>
                                  <div class="field02" style="width:820px; margin-bottom:6px;">
                                       <textarea id="elm1" name="elm1" class="elm1" rows="" cols="" style="width:820px; min-height:400px;"><?=$posted['s_contents']; ?></textarea>
                                  </div>
                                  <div class="error-message" id="err_elm1"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01"> </div>
                                  <div class="field01">
                                  		<input name="c_id" id="c_id" type="hidden"   value="<?=$posted['id']?>"/>
                                  		<input name="is_submitted" id="is_submitted" type="hidden" value="Y"/>
                                        <input name="update_btn" id="update_btn" type="submit" class="btn"  value="Update" />
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="window.location='<?=base_url().$posted['id'].'/church_wall_about'?>'"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
	</div>
</div>

<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->
<script language="javascript" type="text/javascript">
function tinyMCE_call()
{
	
/*tinyMCE.init({
	
		// General options
		mode : "exact",
		elements:"elm1",
        theme : "advanced",
		//width : "750px",
		//height : "600px",
		plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,formatselect,fontsizeselect,forecolor,separator,media,image,link,unlink",
		theme_advanced_buttons2 : "",
		theme_advanced_buttons3 : "",
		
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		file_browser_callback : "tinyBrowser",
		
		skin : "o2k7",
        skin_variant : "silver",
		content_css : base_url+"css/tinymce/cms_pages.css",
		
		// Style formats
		/*style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],*/

		// Replace values for the template plugin
		/*template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	
	
});*/

tinyMCE.init({
        // General options
        mode : "exact",
	    elements:"elm1",
        theme : "advanced",
		width : "750px",
		height : "600px",
       plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	   
	   entity_encoding : "raw",

       // Theme options
		theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,formatselect,fontsizeselect,forecolor,separator,media,image,link,unlink",
		theme_advanced_buttons2 : "",
		theme_advanced_buttons3 : "",
		
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		file_browser_callback : "tinyBrowser",

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : base_url+"css/tinymce/cms_pages.css",

        // Drop lists for link/image/media/template dialogs
        //template_external_list_url : "<?php echo base_url()?>js/template_list.js",
       // external_link_list_url : "<?php echo base_url()?>js/link_list.js",
        //external_image_list_url : "<?php echo base_url()?>js/image_list.js",
        //media_external_list_url : "<?php echo base_url()?>js/media_list.js",
		convert_urls : false,

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
}
$(document).ready(function(arg) {
	//tinyMCE init call
	tinyMCE_call();
	var base_url = '<?=base_url()?>';
	var id = $('#c_id').val();
	// for AJAX page-submission...
    optionsArr = { 
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateFrm, // post-submit callback 
		url: base_url + "logged/church_wall_about/save_church_about_info"
    }; 
 
});



function post_frm_ajax_add()
{
	 tinyMCE.triggerSave(false,true);
	//alert($('#ta_desc').val());
	$('#frm_about_info').ajaxSubmit(optionsArr);
	
	return false;
}

function validateFrm(jsondata)
{
	//alert(jsondata.feed);
	var data = JSON.parse(jsondata);
	//alert(data.msg); alert(data.vid_msg);
	if(data.success==false) 
	{
		hideLoading(); 
		if(data.vid_msg == ''){
			showUIMsg(data.msg);
		}else{
			showUIMsg(data.vid_msg);
		}
	}
	else {
		hideLoading();
	
		showUIMsg(data.msg);		
		//location.reload();
		window.location.href=data.redirect;
	}
}


</script>


