<!-- header -->
<?php
	include(APPPATH ."views/layouts/church_logged_header.phtml");
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>
<div class="container">
  
  <div class="main-page">
  	<h3 class="page-heading">Prayer Group</h3>
    <div class="activity-left">
    	<ul class="left-list">
        <?php if(subadmin_access('prayer_group')): ?>
        <li><a href="<?=base_url()?>church-prayer-group-invite/<?=$prayer_group_id?>">Search and Invite</a></li>
		<?php endif;?>     
		<li><a href="<?=base_url()?>church-prayer-group-member/<?=$prayer_group_id?>">Members</a></li>   	
		<li><a href="<?=base_url().''.$_SESSION['logged_church_id']?>/church-prayer-group">Prayer Groups</a></li>		
        </ul>
    </div>
    <div class="activity-right">
        <div class="activity-comment-box">
       	  
            <!--payer notification start-->
                <div class="main-payer-section">
                    <div class="payer-notification">
                        <div class="nw-right-heading">
                            <h4 class="message-board-title">Message Board</h4>

                            <span  class="prayer-link">Post New Message</span>

                            <!-- <a href="javascript:void(0);"  class="prayer-link">Create Prayer Group </a>-->

                        </div>
                        <div class="form-prayer-box">
                            <div class="Create-list-box">
                                <textarea  rows="" cols="" name="ta_post_prayer_grp" id="ta_post_prayer_grp"></textarea>
                                <input type="button" class="yellow-btn" value="Post" name="" onclick="post_prayer_grp_post(<?= $praye_group_id ?>)" />
                            </div>
                           

                        </div>
                        <div class="notification-list-box">
                            <ul class="notification-ul" id="grp_post_list">
                                <?= $postlists ?>
                                <?php if (count($group_posts) == 0) { ?>
                                    <li id="no_prayer_grp_post"><span style="margin-left: 290px;">No Posts.</span></li>
                                <?php } else
								{
								foreach($group_posts as $k=>$v): ?>
									<li>
                  <span>
              		<strong><?=get_username_by_id($v->i_user_id)?>:</strong> 
                   <span class="text-small-3"> <?=$v->s_post_desc?> </span>          </span><br />
					<span class="text-small-4">Posted on: <?=getShortDateWithTime($v->dt_created_on,6)?></span>
					</li>
                 
                  
                  
                                    	<!--<li class="Message-option-li-float"><a onclick="show_confirm_popup(0)" href="javascript:void(0)">Remove Post</a></li>
                  	<li class="Message-option-li-float">I</li>
                  	<li class="Message-option-li-float"><a onclick="edit_prayer_grp_post(0)" class="editprayerpost" href="javascript:void(0)">Edit Post</a></li>
                                 </ul>
               
               <div id="message_edit_0" class="Message-edit-textarea">
               <textarea id="ta_edit_post_0" cols="" rows="">test message</textarea>
               <input type="button" onclick="save_post(0,50,  'N', 171)" name="" value="Save" class="yellow-btn">
               </div>
              </li>-->
								<?
endforeach;								}?>

                            </ul>
                        </div>

                    </div>



                    <!--prayer wall eight start -->
                   
                    <!--prayer wall eight end  -->
                </div>
            
        </div>

    </div>
    <div class="clear"></div>
    
    
  </div>
</div>

<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->

<script type="text/javascript">
 function post_prayer_grp_post()
 {
	var data="";
	data=$('#ta_post_prayer_grp').val();
	if(data == '')
	{
		showUIMsg('Please enter Some message');
	}
	else
	{
		showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');  
			$.ajax({
				type: 'post',
			   // url: base_url+'logged/prayer_group/generate_friend_search_listing_AJAX/'+group_id,
				url: base_url+'logged/church_prayer_group/post_message/<?=$prayer_group_id?>',
				dataType: 'json',
				data: {'inv':data
					   },
			   success: function (json_response) {
				  
						hideUILoader_nodialog();
						   showUIMsg(json_response.msg);
						//window.location.href = base_url+ '<?=$_SESSION['logged_church_id']?>/church-prayer-group';
							window.location.reload();	
					  
					  }
					  });
				  }
	}
 
</script>
