<?php
$data_arr = json_decode($feed['data']);
//pr($data_arr);
#echo count($data_arr->video); 
# dump( $session_data );
 $data_arr->wall_owner_id;
$msg_id = $feed['id'];	
 $data_arr->wall_owner_id;	 	 
#echo ' ==> '.show_delete_link($msg_id);	
if( $feed['s_type'] == 'wall_post' ){
	$user_primary_info = get_primary_user_info($data_arr->user_id);
	$profile_image_filename = get_profile_image($data_arr->user_id,'thumb');
	//$user_primary_info['s_picture'];
	$profile_displayname = $user_primary_info['s_profile_name'];
	$profile_url = $user_primary_info['s_profile_url'];
	if($data_arr->wall_owner_id > 0  && $data_arr->wall_owner_id != ''){
		  $wall_owner_name = get_username_by_id($data_arr->wall_owner_id);
	}
	$posting_user_name = get_username_by_id($data_arr->user_id);
	$logged_user_id = intval(decrypt($this->session->userdata('user_id')));
	
?>

<div class="txt_content01"> <a href="<?=$profile_url?>"><div class="pro_photo" style="background:url(<?php echo $profile_image_filename;?>) no-repeat center;width:60px; height:60px;" ></div><?php /*?><img src="images/alex.jpg" alt="" class="pro_photo" /><?php */?></a>
          <div class="left_div01a">
                <p class="blue_bold12"><a  href="<?=$profile_url?>"><?=$profile_displayname?></a></p>
                
                <?php if(($data_arr->wall_owner_id == $logged_user_id || $data_arr->user_id == $logged_user_id) && $data_arr->wall_owner_id != '' ){
				 ?>
                 	 <p class="blue_bold12" style="font-size:13px;"><?=$posting_user_name?> has posted on <?=($wall_owner_name)."'s wall."?></p>
				 <?php    }
				 ?>
                <p><?=$data_arr->message?></p>
               
              <!-- image --> 
               <?php if(!empty($data_arr->photo) && count($data_arr->photo)){ 
			   			foreach($data_arr->photo as $key=>$photo_val):
							
							$IMG = base_url()."uploads/wall_photos/".getThumbName($photo_val,'mid');
			   ?>
                <div class="video-image">
                     <div class="" style="background:url('<?=$IMG?>') no-repeat center;width:329px; height:212px;" ></div> 
                </div>
               <?php 	endforeach;
			   		 }
				?>
              <!-- image -->
               
               <!--video play-->
 			   <?php if(!empty($data_arr->video) && count($data_arr->video)){ 
			   ?>
                <div class="video-image">
                    <div  class="cogtime-video" id="myvideo_first_thumb_<?=$feed['id']?>" style="background:url('') no-repeat center;;width:329px; height:212px;" ></div>
                    <div id="myvideo_big_thumb_1_<?=$feed['id']?>" media_id="<?=$feed['id']?>"></div> 
                </div>
                
                
               <?php 	
			   		 }
				?>
               <!--video play--> 
                
                <?php if(get_time_elapsed($feed['dt_created_on']) != '') {?>
                 <p class="date-time">Updated : <?=get_time_elapsed($feed['dt_created_on'])?></p>
                <?php } ?>
                
          </div>
          <input type="hidden" name="i_del_post_id" id="i_del_post_id" value="" />
          <div class="clr"></div>
          <div class="light_heading">
                <div class="left"><a href="javascript:void(0);" class="comments_div<?=$feed['id']?>"  onclick="return show_comments(<?=$feed['id']?>)<?php /*?>show_dialog('view_comments_div')<?php */?>">Comments (<?=$feed['total_comments']?>)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);"   onclick="return show_people_liked(<?=$feed['id']?>); " class="liked_by_<?=$feed['id']?>">Liked by (<?=count_like_link($feed['id'])?>)</a></div>
       
       <?php if((show_like_link($msg_id) == TRUE) ) { 
		?>
                <div class="right"><a href="javascript:void(0);"  >Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$feed['id']?>" onClick="windowLike(<?=$feed['id']?>,'Like')">Like</a> &nbsp;   <?php if(show_delete_link($msg_id) == 'yes'){ ?> |  &nbsp; <a href="javascript:void(0);" onclick="delete_(<?=$feed['id']?>)">Delete</a><?php } ?> </div>                
       <?php } 
	   		else{ 
	   ?>
         <div class="right"><a href="javascript:void(0);"  >Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$feed['id']?>" >Like</a> &nbsp;  <?php if(show_delete_link($msg_id) == 'yes'){ ?> |  &nbsp; <a href="javascript:void(0);" onclick="delete_(<?=$feed['id']?>)">Delete</a><?php } ?> </div>
          
       <?php }?>
       </div>
       
       		<!-- slide section start -->
              <div class="new-wl">
                  <!--comment section start-->
                  <div  class="comments-number content-width" id="post-comment-div<?=$feed['id']?>" >
                    <div class="comments-number-mid content-width">
                        <div class="heading">
                              <div class="left">
                                    <h4><img class="cmnt" src="images/icons/cmnt2.png" alt="" /> <span class="comments_div<?=$feed['id']?>">Comments (<?=$feed['total_comments']?>)</span> </h4>
                                    <img class="wal-minus" alt="" src="images/minus-white.png" />
                              </div>
                            </div>
                            <DIV id="comment_content_div<?=$feed['id']?>"></DIV>
                      </div>
                  </div>
              	  <!--comment section end-->	
                  <!--like by section start-->
                  <div  class="comments-number content-width" id="post-like-div<?=$feed['id']?>">
                    <div class="comments-number-mid">
                        <div class="heading">
                              <div class="left">
                                    <h4><img alt="" src="images/heart2.png" class="cmnt" /> <span class="liked_by_<?=$feed['id']?>">Liked by (<?=count_like_link($feed['id'])?>) </span></h4>
                                     <img class="wal-minus" alt="" src="images/minus-white.png" />
                              </div>
                        </div>
                              <div class="shade_box_white" id="like_content_div<?=$feed['id']?>"></div>
                      </div>
                  </div>
              	  <!--like by section end-->
              </div>
              
                  <div class="new-wl-right">
                      <!--comment section start-->
                      <div  class="comments-number content-width" id="post-comment-box<?=$feed['id']?>">
                        <div class="comments-number-mid content-width comment-box-manage-profile">
                            <div class="heading">
                                  <div class="left">
                                        <h4><img alt="" src="images/no.png" class="cmnt" />  Comment  </h4>
                                        <img class="wal-minus" alt="" src="images/minus-white.png" />
                                  </div>
                            </div>
                              <div class="txt_content01 comments-number-content content-width"> 
                              <textarea  id="feed_comment_box_<?=$feed['id']?>" cols="" rows="" style="width:461px; height:100px; margin-bottom:10px;"></textarea>
                              <input type="hidden" name="i_newsfeed_id" id="i_newsfeed_id" value=""/>
                              <input class="yellow-btn" id="post_comment_button" type="button"  value="Post" name="" onclick="post_comment(<?=$feed['id']?>);" />
                              
                              <br class="clr" />
                              </div>
                      </div>
                  </div>
                  <!--comment section end-->	
                  </div>
            <!-- slide section end -->
		</div>
         <script type="text/javascript">
					$('.left a').click(function(){
						var index=$(this).index();
						$('.new-wl > .comments-number').css('display','none');
						$('.new-wl-right > .comments-number').css('display','none');
						$(this).parent().parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
					})
						
					$('.right a').click(function(){
						var index=$(this).index();
						$('.new-wl > .comments-number').css('display','none');
						$('.new-wl-right > .comments-number').css('display','none');
						$(this).parent().parent().next().next('.new-wl-right').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
					})
						
						
					$('.wal-minus').click(function(){
						$(this).parents('.comments-number').slideUp('fast');
					})
					</script>
        
<?php } ?>

<script type="text/javascript">
//Fetching the followings.........
  function show_comments(i_newsfeed_id)
  {
	  
	$('.new-wl > .comments-number').css('display','none');
	$('.new-wl-right > .comments-number').css('display','none');
	$('#post-comment-div'+i_newsfeed_id).slideDown('slow');
		 
	 showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
		$.ajax({
			
			url: base_url +'logged/my_wall/NEW_fetch_comment_wallpost/'+i_newsfeed_id,
			dataType: 'json',
			type: 'post',
	
			success: function (data, status) {
				//hideUILoader();
				$('#comment_content_div'+i_newsfeed_id).html(data.html_data);
				hideUILoader_nodialog();
				showUIMsg(data.msg);
			},
			error: function(data, status, e) {
				hideUILoader('view_comments_div');
				showUIMsg("Error!");
				
			}
		});
				 
		 
  }
  
  function show_people_liked(i_newsfeed_id)
  {
	   
	   $('.new-wl > .comments-number').css('display','none');
	   $('.new-wl-right > .comments-number').css('display','none');
	   $('#post-like-div'+i_newsfeed_id).slideDown('slow');
	   
	   showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
		$.ajax({
			
			url: base_url +'logged/my_wall/new_fetch_likes_on_wallpost/'+i_newsfeed_id,
			dataType: 'json',
			type: 'post',
	
			success: function (data, status) {
				$('#like_content_div'+i_newsfeed_id).html(data.html_data);
				hideUILoader_nodialog();//('liked_by_div');
				showUIMsg(data.msg);
			},
			error: function(data, status, e) {
				hideUILoader_nodialog();
				showUIMsg("Error!");
				
			}
		});
				 
		 
  }
  
</script>
