
<?php
//pr($result_arr);
if( is_array($result_arr) && count($result_arr) ) :
	foreach($result_arr as $feed) :
		include(APPPATH.'views/newsfeed/my_profile_single_feed.phtml');
	?>
		<script type="text/javascript">
		$(function(){
			
                        $('.wal-minus').click(function(){
				$(this).parents('.comments-number').slideUp('fast');
			})
		});
		</script>
	<?php	
	endforeach;
else :
?>

<?php
endif;
?>
<input type="hidden" id="current_page_1" name="current_page_1" value="<?=$current_page_1?>" />

