<div class="div_content">
      <div class="postheading">
            <div class="left">
                  <h4>Post In Wall</h4>
            </div>
      </div>
                
      <form name="public_wall_post_form" id="public_wall_post_form"  method="post" class="wall-comment-form" enctype="multipart/form-data" action="<?=base_url().'newsfeed/post_his_wall/'?>" onsubmit="return false;">
      <input type="hidden" id="wall_type" name="wall_type" value="my_wall" />
	   <!--  text div start -->
			   <div class=" comment-content nw-comment-content">
                <div class="write-text">
                <textarea name="wall_msg" id="wall_msg" cols="" rows="" onfocus="if(this.value=='Max 500 Characters')this.value='';" onblur="if(this.value=='')this.value='Max 500 Characters';" maxlength ="500" 
                onKeyDown="limitTextarea(this.form.wall_msg,this.form.countdown,500);" 
onKeyUp="limitTextarea(this.form.wall_msg,this.form.countdown,500);" onkeypress="return restrict_carrige(event);"  >Max 500 Characters</textarea>
 <p style=" clear:both; float:left"> <span id="text_count">500</span> Characters</p>
                </div>
                                <script type="text/javascript">
                                  $(document).ready(function(){
                                     // $("#text_countt").html('500')
                                  $("#wall_msg").keyup(function(){
                                      
                               $("#text_count").text("Characters left: " + (500 - $(this).val().length));
                                   });    
                                  });
                               
                               
                               </script>
               <!-- text div end  -->
			   </div>
            <div class="tab_details comment-content nw-comment-content">
            
            <input type="hidden" id="public_wall_owner_id" name="public_wall_owner_id" value="<?=($this->session->userdata('user_id'))?>" />
            
            
              <!--  text div start -->
               <!-- <div class="write-text">
                <textarea name="wall_msg" id="wall_msg" cols="" rows="" onfocus="if(this.value=='Max 500 Characters')this.value='';" onblur="if(this.value=='')this.value='Max 500 Characters';" maxlength ="500" 
                onKeyDown="limitTextarea(this.form.wall_msg,this.form.countdown,500);" 
onKeyUp="limitTextarea(this.form.wall_msg,this.form.countdown,500);" onkeypress="return restrict_carrige(event);"  >Max 500 Characters</textarea>
 <p style=" clear:both; float:left"> <span id="text_count">0</span> Characters</p>
                </div>-->
               <!-- text div end  -->
                
               <!-- upload image div start  -->
                <div class="upload-image" >
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Upload Image :</label>
                    <input name="btn_upload" id="btn_upload" type="file" size="40" />
                    <br class="clr"/>
                    <div id="all_photos">
                  
                    </div>
            
                  <div id="hdnflds" >
                  </div>
                 
                 </div>   
                      
                <!--upload image div end -->
                
                
                
               <!-- upload video div start -->
                <div class="upload-video">
				<a href="javascript:void(0);" onclick="$(this).parent('div').hide();" style="float:right;color:#013d62">Hide[-]</a>
                    <label  class="upload-img">Video Url :</label><div class="video-url"><input name="txt_video_url" id="txt_video_url" type="text" /></div>
					<ul class="video-logo" >
					<li><img src="<?=base_url()?>images/YouTube.png" title="YouTube" height="18px" width="44px" alt="YouTube"></li>
					<li><img src="<?=base_url()?>images/Vimeo.png" title="Vimeo" height="17px" width="19px" alt="Vimeo"></li>
					<li><img src="<?=base_url()?>images/DailyMotion.png" height="18px" width="18px" title="DailyMotion" alt="DailyMotion"></li>
					<li><img src="<?=base_url()?>images/Viadeo.png" height="17px" width="74px" title="Viadeo" alt="Viadeo"></li>
					</ul>
                    <br class="clr"/>
                    <div id="all_videos">
                      <?php /*?><div class="view-thumb"><img src="images/photo-img01.jpg" alt="photo" width="60" height="60" /><a href="javascript:void(0);" class="remove" title="Remove Video"></a></div>
                     <?php */?>
                    </div>
                    
                     <div id="hdnvideoflds" >
                     </div>
                  
                </div>
               <!-- upload video div end -->
               
               
            </div>
            <div class="tab_content button-set type-text">
                <ul>
                   <!-- <li class="select"><a href="javascript:void(0);"><img src="images/nw-text-btn.png" alt="text" title="Write Text"  /></a></li>-->
                    <li><a href="javascript:void(0);"><img src="images/nw-photo-btn.png" alt="photo" title="Upload Photo" /></a></li>
                    <li><a href="javascript:void(0);"><img src="images/nw-video-btn.png" alt="video" title="Upload Video" /></a></li>
                </ul>
            </div>
            
            <input name="" type="submit" class="wall-comment-submit-nw " value="Post" />
      </form>
</div>
<br class="clr" />
<script language="javascript">
<!--
var g_controller_url = base_url+"my-wall.html";
 var carriage_count = 0;
$(document).ready(function() {
	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoading,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
    // bind to the form's submit event 
    $('#public_wall_post_form').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });
	
	$(function(){
  $('#wall_msg').keyup(function(){
	  count=1;
  limitChars('wall_msg', 500, '');
  });
  $('#wall_msg').keydown(function(){
	  count=1;
  limitChars('wall_msg', 500, '');
  });
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('wall_msg',500, '');

});

var count=0;
//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
	
  var text = $('#'+textid).val(); 
  
  if(text == ''){
	  count = 0;
  }
 


if( count == 0)
{
	//alert (carriage_count)
  var textlength = 0;
}
else
{
 var textlength = text.length;
}

/**********6-12-2014*****************************/
 // $('#text_count').html(textlength);
  /***************************************/
  
        
  if(textlength > limit)
  {
  $('#'+textid).val(text.substr(0,limit));
  return false;
  }
  else
  {
  return true;
  }
  
}




function restrict_carrige(e)
{
	/*//if(e.keyCode == 13)
	{
		$.ajax({
			type: 'post',
			url: base_url+'logged/prayer_wall/getCarriageCount',
			data: {'str':$('#ta_desc').val()},
			dataType: 'json',
	
			success: function (data, status) {
				
					if(data.count > 1){
						return false;
					}
				
				}	// end of success function...
		});
	}*/
	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));

	if(e.keyCode == 13){
		carriage_count++;
		//console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >10){
		return false;
		//e.preventDefault();
	}
}

// validate ajax-submission...
function validateFrm(jsondata)
{
	//alert(jsondata.feed);
	var data = JSON.parse(jsondata);
	//alert(data.msg); alert(data.vid_msg);
	if(data.success==false) 
	{
		hideLoading(); 
		if(data.vid_msg == ''){
			showUIMsg(data.msg);
			
		}else{
			showUIMsg(data.vid_msg);
		}
	}
	else {
		hideLoading(); 
		$("#public_wall_post_form")[0].reset(); 
		$('#all_photos').html('');
		$('#hdnflds').html('');
		$('.tab_content ul li').removeClass('select');
		$('.tab_content ul li').first().addClass('select');
		var index = 0;
		
		$('.tab_details > div').hide();
		$('.tab_details > div').filter(':eq(' + index + ')').show();
		$('.tab_details .sec-title').filter(':eq(' + index + ')').show();
		$('.tab_details .sec-detail').filter(':eq(' + index + ')').show();
		$('.tab_details .title-body').filter(':eq(' + index + ')').show();
		$("#comment_result_div").html(base64_decode(data.feed)+$('#comment_result_div').html());
                
                $("#wallMsg").html('My Wall Messages &amp; Comments');
                $("#noPost").html('');
                
		//$('[id^="myvideo_big_thumb_1_"]').trigger('click');
		$('#text_count').html('');
		$('#text_count').html('0');
		showUIMsg(data.msg);		
		
		//window.location.href=g_controller_url;
	}
}
-->
</script>

<script language="javascript">
$(document).ready(function() {

//  $('#myvideo_big_thumb_1').click(function(){
$('[id^="myvideo_big_thumb_1_"]').click(function(){ 
//alert($(this).attr('media_id'));
  showLoading(); 
  var media_id =  $(this).attr('media_id');
  $.ajax({
		type: 'post',
		url: base_url+'logged/my_wall/get_video/',
		data: ({'media_id' : media_id ,'width':329 ,'height':212}),

		dataType: 'json',
		success: function (data, status) {
			if(data.result=='success') {
				hideLoading();
			   $('#myvideo_first_thumb_'+media_id).html(data.s_image_source.html);
			   $('#myvideo_first_thumb_'+media_id).attr('i_media_id',data.i_media_id);
			}
		},
		error: function (data, status, e) {
			hideLoading();
			showUIMsg('Some error occurred. Please try again.');
		}
	});
});
  $('[id^="myvideo_big_thumb_1_"]').trigger('click');
});
</script>
