<?php
//pr($result_arr);
if( is_array($result_arr) && count($result_arr) ) :
	foreach($result_arr as $feed) :
		include(APPPATH.'views/newsfeed/public_profile_single_feed.phtml');
	endforeach;
else :
?>

<?php
endif;
?>
<input type="hidden" id="current_page_1" name="current_page_1" value="<?=$current_page_1?>" />
<script language="javascript">
$(document).ready(function() {

//  $('#myvideo_big_thumb_1').click(function(){
$('[id^="myvideo_big_thumb_1_"]').click(function(){ 
//alert($(this).attr('media_id'));
  showLoading(); 
  var media_id =  $(this).attr('media_id');
  $.ajax({
		type: 'post',
		url: base_url+'public_profile/get_video/',
		data: ({'media_id' : media_id ,'width':329 ,'height':212}),

		dataType: 'json',
		success: function (data, status) {
			if(data.result=='success') {
				hideLoading();
			   $('#myvideo_first_thumb_'+media_id).html(data.s_image_source.html);
			   $('#myvideo_first_thumb_'+media_id).attr('i_media_id',data.i_media_id);
			}
		},
		error: function (data, status, e) {
			hideLoading();
			showUIMsg('Some error occurred. Please try again.');
		}
	});
});
  $('[id^="myvideo_big_thumb_1_"]').trigger('click');
});
</script>