<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <div id="mid_container">
                              <div class="page_heading">
                                    <div class="left"><img src="images/icons/msgg.png" alt="" />My Privacy Settings </div>
                              </div>
                              <div class="arrow_btm"></div>
                              <form action="<?php echo base_url().'logged/privacy_settings/update'?>" name="frm" id="frm" method="post"  onsubmit="return false;" >  
                                <div class="shade_box_01 email_settings">
                                    
                                    <h4>My Photo</h4>
                                    <div class="settings_div">
                                        		
                                                <?php
												$radio_photo_privacy	= 1;
												if($privacy_settings['photo']['friend_privacy']==0 && $privacy_settings['photo']['netpal_privacy']==0 && $privacy_settings['photo']['prayer_partner_privacy']==0 && $privacy_settings['photo']['ring_privacy']==0 && $privacy_settings['photo']['prayer_group_privacy']==0)
													$radio_photo_privacy	= 0;
												?>
                                                <input name="photoprivacy" type="radio" value="1" onclick="showOptions($(this),'public');" <?php if($radio_photo_privacy==0){?> checked="checked"<?php }?> />Public(visible to everyone)
                                                <input name="photoprivacy" type="radio" value="2" onclick="showOptions($(this),'private');" class="radio-gap" <?php if($radio_photo_privacy>0){?> checked="checked"<?php }?> />Private
                                                <span id="err_photoprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                <div <?php if($radio_photo_privacy==0 || $radio_photo_privacy==''){?> style="display:none;"<?php }?> id="testdiv">
                                                	<input name="photofrnd" type="checkbox" value="1" <?php if($privacy_settings['photo']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="photonetpal" type="checkbox" value="1" <?php if($privacy_settings['photo']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="photopp" type="checkbox" value="1" <?php if($privacy_settings['photo']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="photoring" type="checkbox" value="1" <?php if($privacy_settings['photo']['ring_privacy']!=0){?>checked="checked"<?php }?> />Rings <div class="clr"></div>
                                                    <input name="photopg" type="checkbox" value="1" <?php if($privacy_settings['photo']['prayer_group_privacy']!=0){?>checked="checked"<?php }?> />Prayer Groups<div class="clr"></div>
                                                    <?php /*?>
													| <span><img src="images/down.png" onclick="showAll($(this))" /></span>
													<div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['photo']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                    
                                                    <?php /*?>
													 | <span><img src="images/down.png" onclick="showAll($(this))" /></span><div class="clr"></div>
													<div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
														
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="prayer_group[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['photo']['prayer_group_privacy'],$pg['id']) !== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                         
                                    </div>
                                    <h4>My Audio</h4>
                                    <div class="settings_div">
                                          		<?php
												$radio_audio_privacy	= 1;
												if($privacy_settings['audio']['friend_privacy']==0 && $privacy_settings['audio']['netpal_privacy']==0 && $privacy_settings['audio']['prayer_partner_privacy']==0 && $privacy_settings['audio']['ring_privacy']==0 && $privacy_settings['audio']['prayer_group_privacy']==0)
													$radio_audio_privacy	= 0;
												?>	
                                                <input name="audioprivacy" type="radio" value="1" <?php if($radio_audio_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');" />Public(visible to everyone)
                                                <input name="audioprivacy" type="radio" value="2" <?php if($radio_audio_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');" />Private
                                                <span id="err_audioprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                <div <?php if($radio_audio_privacy==0 || $radio_audio_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="audiofrnd" type="checkbox" value="1" <?php if($privacy_settings['audio']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="audionetpal" type="checkbox" value="1" <?php if($privacy_settings['audio']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="audiopp" type="checkbox" value="1" <?php if($privacy_settings['audio']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="audioring" type="checkbox" value="1" <?php if($privacy_settings['audio']['ring_privacy']!=0){?>checked="checked"<?php }?> />Rings
                                                    <div class="clr"></div>
                                                    <input name="audiopg" type="checkbox" value="1" <?php if($privacy_settings['audio']['prayer_group_privacy']!=0){?>checked="checked"<?php }?> />Prayer Groups 
													<div class="clr"></div>
                                                    <?php /*?>| <span><img src="images/down.png" onclick="showAll($(this))" /></span><div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php 
														
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="audio_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['audio']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                    
                                                    
													<?php /*?>| <span><img src="images/down.png" onclick="showAll($(this))" /></span><?php */?>
                                                    
                                                    <?php /*?><div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="audio_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['audio']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    <h4>My Video</h4>
                                    <div class="settings_div">
                                          		<?php
												$radio_video_privacy	= 1;
												if($privacy_settings['video']['friend_privacy']==0 && $privacy_settings['video']['netpal_privacy']==0 && $privacy_settings['video']['prayer_partner_privacy']==0 && $privacy_settings['video']['ring_privacy']==0 && $privacy_settings['video']['prayer_group_privacy']==0)
													$radio_video_privacy	= 0;
												?>	
                                                <input name="videoprivacy" type="radio" value="1" <?php if($radio_video_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');"  />Public(visible to everyone)
                                                <input name="videoprivacy" type="radio" value="2" <?php if($radio_video_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');"  />Private
                                                <span id="err_videoprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                <div <?php if($radio_video_privacy==0 || $radio_video_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="videofrnd" type="checkbox" value="1" <?php if($privacy_settings['video']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="videonetpal" type="checkbox" value="1" <?php if($privacy_settings['video']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="videopp" type="checkbox" value="1" <?php if($privacy_settings['video']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="videoring" type="checkbox" value="1" <?php if($privacy_settings['video']['ring_privacy']!=0){?>checked="checked"<?php }?> />Rings <div class="clr"></div>
                                                    <input name="videopg" type="checkbox" value="1" <?php if($privacy_settings['video']['prayer_group_privacy']!=0){?>checked="checked"<?php }?> />Prayer Groups<div class="clr"></div> 
                                                    <?php /*?>
													| <span><img src="images/down.png" onclick="showAll($(this))" /></span>
													<div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="video_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['video']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div>
                                                    | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                   <div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="video_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['video']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    
                                    <h4>My Events</h4>
                                    <div class="settings_div">
                                         		<?php
												$radio_event_privacy	= 1;
												if($privacy_settings['event']['friend_privacy']==0 && $privacy_settings['event']['netpal_privacy']==0 && $privacy_settings['event']['prayer_partner_privacy']==0 && $privacy_settings['event']['ring_privacy']==0 && $privacy_settings['event']['prayer_group_privacy']==0)
													$radio_event_privacy	= 0;
												?>	
                                                <input name="eventprivacy" type="radio" value="1" <?php if($radio_event_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');" />Public(visible to everyone)
                                                <input name="eventprivacy" type="radio" value="2" <?php if($radio_event_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');" />Private
                                                <span id="err_eventprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                
                                                <div <?php if($radio_event_privacy==0 || $radio_event_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="eventfrnd" type="checkbox" value="1" <?php if($privacy_settings['event']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="eventnetpal" type="checkbox" value="1" <?php if($privacy_settings['event']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="eventpp" type="checkbox" value="1" <?php if($privacy_settings['event']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="eventring" type="checkbox" value="1" <?php if($privacy_settings['event']['ring_privacy']==1){?>checked="checked"<?php }?> />Rings<div class="clr"></div>
                                                    <input name="eventpg" type="checkbox" value="1" <?php if($privacy_settings['event']['prayer_group_privacy']==1){?>checked="checked"<?php }?> />Prayer Groups<div class="clr"></div>
                                                    <?php /*?> | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="event_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['event']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div>
                                                     | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="event_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['event']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    <div class="clr"></div>
                                    <div class="left" style="padding: 5px 0px 5px 0px; background: #ffffff; color:#206A9E ;width: 492px;  "><img alt="" src="images/icons/msgg.png">View Timeline </div>
                                    <div class="wall_pvcy" style="float: left;">
                                    <h4>Post In Wall</h4>
                                    <div class="settings_div">
                                         		<?php
												$radio_wall_privacy	= 1;
												if($privacy_settings['wall']['friend_privacy']==0 && $privacy_settings['wall']['netpal_privacy']==0 && $privacy_settings['wall']['prayer_partner_privacy']==0 && $privacy_settings['wall']['ring_privacy']==0 && $privacy_settings['wall']['prayer_group_privacy']==0)
													$radio_wall_privacy	= 0;
												?>	
                                                <input name="wallprivacy" type="radio" value="1" <?php if($radio_wall_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');" />Public(visible to everyone)
                                                <input name="wallprivacy" type="radio" value="2" <?php if($radio_wall_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');" />Private
                                                <span id="err_wallprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                
                                                <div <?php if($radio_wall_privacy==0 || $radio_wall_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="wallfrnd" type="checkbox" value="1" <?php if($privacy_settings['wall']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="wallnetpal" type="checkbox" value="1" <?php if($privacy_settings['wall']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="wallpp" type="checkbox" value="1" <?php if($privacy_settings['wall']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="wallring" type="checkbox" value="1" <?php if($privacy_settings['wall']['ring_privacy']==1){?>checked="checked"<?php }?> />Rings<div class="clr"></div>
                                                    <input name="wallpg" type="checkbox" value="1" <?php if($privacy_settings['wall']['prayer_group_privacy']==1){?>checked="checked"<?php }?> />Prayer Groups <div class="clr"></div>
                                                    <?php /*?> | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="wall_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['wall']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div>
                                                    | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="wall_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['wall']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    
                                    <h4>Comments/Likes In Wall</h4>
                                    <div class="settings_div">
                                         		<?php
												$radio_wall_comment_like_privacy	= 1;
												if($privacy_settings['wallCommentLike']['friend_privacy']==0 && $privacy_settings['wallCommentLike']['netpal_privacy']==0 && $privacy_settings['wallCommentLike']['prayer_partner_privacy']==0 && $privacy_settings['wallCommentLike']['ring_privacy']==0 && $privacy_settings['wallCommentLike']['prayer_group_privacy']==0)
													$radio_wall_comment_like_privacy	= 0;
												?>	
                                                <input name="wallCommentLikeprivacy" type="radio" value="1" <?php if($radio_wall_comment_like_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');" />Public(visible to everyone)
                                                <input name="wallCommentLikeprivacy" type="radio" value="2" <?php if($radio_wall_comment_like_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');" />Private
                                                <span id="err_wallCommentLikeprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                
                                                <div <?php if($radio_wall_comment_like_privacy==0 || $radio_wall_comment_like_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="wallCommentLikefrnd" type="checkbox" value="1" <?php if($privacy_settings['wallCommentLike']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="wallCommentLikenetpal" type="checkbox" value="1" <?php if($privacy_settings['wallCommentLike']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="wallCommentLikepp" type="checkbox" value="1" <?php if($privacy_settings['wallCommentLike']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="wallCommentLikering" type="checkbox" value="1" <?php if($privacy_settings['wallCommentLike']['ring_privacy']==1){?>checked="checked"<?php }?> />Rings<div class="clr"></div>
                                                    <input name="wallCommentLikepg" type="checkbox" value="1" <?php if($privacy_settings['wallCommentLike']['prayer_group_privacy']==1){?>checked="checked"<?php }?> />Prayer Groups <div class="clr"></div>
                                                    <?php /*?> | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="wall_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['wall']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div>
                                                    | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="wall_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['wall']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    
                                </div>
                                    <div class="clr" style="padding: 10px 195px 10px 196px; background: #ffffff; "></div>
                                     <h4>Messages</h4>
                                     <div class="settings_div">
                                         		<?php
												$radio_msg_privacy	= 1;
												if($privacy_settings['msg']['friend_privacy']==0 && $privacy_settings['msg']['netpal_privacy']==0 && $privacy_settings['msg']['prayer_partner_privacy']==0 && $privacy_settings['msg']['ring_privacy']==0 && $privacy_settings['msg']['prayer_group_privacy']==0)
													$radio_msg_privacy	= 0;
												?>	
                                                <input name="msgprivacy" type="radio" value="1" <?php if($radio_msg_privacy==0){?> checked="checked"<?php }?> onclick="showOptions($(this),'public');" />Public(visible to everyone)
                                                <input name="msgprivacy" type="radio" value="2" <?php if($radio_msg_privacy>0){?> checked="checked"<?php }?> onclick="showOptions($(this),'private');" />Private
                                                <span id="err_msgprivacy" class="error-message"></span>
                                                <div class="clr"></div>
                                                
                                                <div <?php if($radio_msg_privacy==0 || $radio_msg_privacy==''){?> style="display:none;"<?php }?>>
                                                	<input name="msgfrnd" type="checkbox" value="1" <?php if($privacy_settings['msg']['friend_privacy']==1){?>checked="checked"<?php }?> />Friends
                                                    
                                                    <div class="clr"></div>
                                                    <input name="msgnetpal" type="checkbox" value="1" <?php if($privacy_settings['msg']['netpal_privacy']==1){?>checked="checked"<?php }?> />Netpals 
                                                     <div class="clr"></div>
                                                    <input name="msgpp" type="checkbox" value="1" <?php if($privacy_settings['msg']['prayer_partner_privacy']==1){?>checked="checked"<?php }?> />Prayer Partners 
                                                    <div class="clr"></div>
                                                    
                                                    <input name="msgring" type="checkbox" value="1" <?php if($privacy_settings['msg']['ring_privacy']==1){?>checked="checked"<?php }?> />Rings<div class="clr"></div>
                                                    <input name="msgpg" type="checkbox" value="1" <?php if($privacy_settings['msg']['prayer_group_privacy']==1){?>checked="checked"<?php }?> />Prayer Groups <div class="clr"></div>
                                                    <?php /*?> | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="ring">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_ring as $ring)
														{
															?>
                                                            <li><?php echo $ring->s_ring_name?>&nbsp;<input type="checkbox" name="wall_arr_ring[]" value="<?php echo $ring->id?>" <?php if(strpos($privacy_settings['wall']['ring_privacy'],$ring->id)!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div>
                                                    | <span><img src="images/down.png" onclick="showAll($(this))" /></span>
                                                    <div style="display:none;" id="pg">
                                                    	<ul class="my-audio-list-pad">
                                                    	<?php
                                                        foreach($arr_prayer_grp as $pg)
														{
															?>
                                                            <li><?php echo $pg['s_group_name']?>&nbsp;<input type="checkbox" name="wall_arr_pg[]" value="<?php echo $pg['id']?>" <?php if(strpos($privacy_settings['wall']['prayer_group_privacy'],$pg['id'])!== false){?>checked="checked"<?php }?> /></li>
															<?php 
														}
														?>
                                                       </ul>
                                                    </div><?php */?>
                                                </div>
                                          
                                    </div>
                                    
                                    <p>&nbsp;</p>
                                    <input name="" type="button" value="Update" class="btn bottom-button" onclick="$('#frm').submit();" />
                              </div>
                              </form>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script type="text/javascript">

 function showOptions(obj,flag)
 {
	 if(flag=='public')
	 {
	 	$(obj).next().next().next().next().hide();
	 }
	 else if(flag=='private')
	 {
	 	$(obj).next().next().next().show();
	 }
 }
 
 function showAll(obj)
 {//console.log(obj);
	$(obj).parent().next().next().slideToggle();
 }
 
 $(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoading,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});
// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		showUIMsg(data.msg);	
	}
	else {
		
		showUIMsg(data.msg);		
		window.location.href= "<?php echo base_url().'privacy-settings.html'?>";
		
	}
	$('#sp_add_loading').html('');
	hideLoading();
				
}
</script>
