<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>

<!-- CONTENT SECTION -->

<div id="content_section">
      <div id="container">
      <!-- main container -->
	  <div id="mid_content">
		<!-- latest news -->
	   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
        <!-- /latest news -->
        <div class="clr"></div>
	 <div id="main_container"> 
      <!-- left container -->
	  <?php include(APPPATH."views/layouts/leftbar.phtml");?>
      <!-- left container -->
      <div id="mid_container">
      	<!--gospel magazine top banner start -->
       <div class="gospel-magazine-banner2">
        	<div class="gospel-magazine-banner-content2">
                <h2>gospel-magazine</h2>
                <p>magazines for music, records, artists and news</p>
            </div>
        </div>
        <!--gospel magazine top banner end -->  
      	<!--link to page section start --> 
        <div class="link-to-page">
        	<ul>
            	<li class="last"><a href="media-center.html" class="back-media">Back to Media Center</a></li>
            </ul>
        </div> 
        <!--link to page section end -->  
        <!--article container start --> 
        <div id="table_content" class="article-container">
         <?php echo $listingContent?>
         </div>
        <!--article container end -->   
 		</div>
          
			<?php include(APPPATH."views/layouts/rightbar.phtml");?>
          
          
          <!--video gallery start -->
          <!--video gallery end -->	
          </div>

	  </div>
		  
	  <div class="clr"></div>
      <!-- main container end-->       
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<input type="hidden" id="h_news_id" value="">
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>





<div class="lightbox liked_by_div" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/thumb_up.png" alt="" /> Liked by </h4>
                  </div>
            </div>
            <div id="liked_html"></div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>


<!--view comment div-->
<div class="lightbox view_comments_div " style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/cmnt.png" alt="" width="30" height="30"/> View Comments </h4>
                  </div>
            </div>
            <div id="comment_html"></div>

            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>


