 								<?php 
								//pr($result_arr);
									if(count($result_arr)){
										foreach($result_arr as $key=> $val){
											
											$comment_arr = $val['comment_arr'];
											$is_follow = get_tweet_follow_status_by_userid($val['i_user_id']);
								?>
                                 
                                         <div class="shade_box_shade-inner">
                                           
                                            <?php 
											     if($is_follow == false && intval(decrypt($this->session->userdata('user_id'))) != $val['i_user_id']){
    										?>
                                             	 <p class="right follow_a<?=$val['i_user_id']?>"><img src="images/icons/bird2.png" alt="" /><a href="javascript:void(0);" class="blue_link" onclick="javascript:followUser(<?=$val['i_user_id']?> , 'follow' )" ><strong>Follow Ministers Tweet</strong></a></p>
                                            <?php
												}
												else if($is_follow == true && intval(decrypt($this->session->userdata('user_id'))) != $val['i_user_id'] ){
											?> 
                                            	<p class="right follow_a<?=$val['i_user_id']?>"><img src="images/icons/bird2.png" alt="" /><a href="javascript:void(0);" class="blue_link" onclick="javascript:followUser(<?=$val['i_user_id']?> , 'Unfollow' )" ><strong>Unfollow Ministers Tweet</strong></a></p>
   
                                            <?php
												}
                                            ?>
                                               
                                            <p class="blue_bold12"> <a href="javascript:void(0);"><?=$val['s_post_title']?></a></p>
                                            <p class="light_blue_bold12" style="padding-bottom:10px;">By: <?=$val['s_profile_name']?></p>
                                            <div class="clr"></div>
                                             <p>&nbsp; </p>
                                             <p><?=nl2br($val['s_post_description'])?></p>
                                             <p>&nbsp; </p>
                                             <p class="date-time"><?=get_time_elapsed_blog($val['dt_created_date'])?></p>
                                          </div>
                                          
                                         <div class="light_heading">
                                             <div class="left">
                                                <a href="javascript:void(0);" class="minister-shout-comment" onclick="view_article_comments(<?=$val['id']?>)"  >Comments (<span id="tot_comment<?=$val['id']?>"><?=$val['total_comments']?></span>)</a>
                                                &nbsp; |   &nbsp; 
                                                <a href="javascript:void(0);" class="minister-shout-comment" onclick="show_post_comment(<?=$val['id']?>)" >Comment</a> </div>
                                          </div>
                                          
                                         <div class="nw-mid-comments" >
                                            <div class="mid-comments" id="ms_comments<?=$val['id']?>">
                                                <div style="margin-bottom:0px;" class="heading">
                                                      <div class="left">
                                                            <h4><img alt="" class="cmnt" src="images/icons/cmnt2.png" height="20px" width="20px"/> View Comments </h4>
                                                      </div>
                                                </div>
                                                	<DIV id="comment_content<?=$val['id']?>"></DIV>
                                            </div>
                                            
                                            <div class="mid-comments" id="ms_write_comment<?=$val['id']?>">
                                                <div  class="heading">
                                                      <div class="left">
                                                            <h4><img alt="" class="cmnt" src="images/no.png" /> Comments </h4>
                                                      </div>
                                                </div>
                                                   <div style="padding:8px 0px;" class="shade_box_white">
                                                            <div> 
                                                            <form  method="post" >
                                                            <textarea name="txt_comment<?=$val['id']?>" id="txt_comment<?=$val['id']?>" class="post-by" cols="" rows=""></textarea>
                                                            <input type="button" name="" value="Post" class="yellow-btn" onclick="postArticleComment(<?=$val['id']?>, <?=$val['i_blog_id']?>)" /> 
                                                            </form>
                                                            <br class="clr" />
															</div>
                                                            <div class="clr"></div>
                                                      </div>
                                                </div>
                                               
                                                
                                         	
                                          
                                          </div>
                                <?php
										}
									}
								?>