<!--POST COMMENT LIGHTBOX -->
<div class="lightbox comment_div" style="width:540px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" height="24" width="24" alt="close" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
     
            <div class="heading">
                  <div class="left">
                        <h4><img src="images/icons/coment.png" height="20" width="20" alt="coment" /> Post Comment </h4>
                  </div>
            </div>
            <div class="frm_box">
                  <p>
                    <textarea id="comment"  class="feed_comment_box" style="width:486px; height:100px; margin-bottom:10px;"></textarea>
                  </p>
                  <p><span id="text_count">0</span> Characters</p> 
                  	<input type="hidden" name="i_newsfeed_id" id="i_newsfeed_id" value=""/>
                  <p>
                    <input class="submit-green" id="post_comment_button" type="button"  style="margin-top:15px;" value="Post" name="" onclick="post_comment();">
                  </p>
                  
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div> 
<!--POST COMMENT LIGHTBOX -->