<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container"> 
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container"> <?php //pr($latest_intercession);?>
                              <div class="my-wall-section">
                                    <p class="green-title">Bible Verse : [ <a  href="read-bible-chapter-view.php"><?=$rand_bible_verse[0]['s_book_name']?> <?=$rand_bible_verse[0]['s_chapter'].':'.$rand_bible_verse[0]['i_verses']?></a> ]</p>
                                    <p><?=$rand_bible_verse[0]['s_text']?></p>
                              </div>
                              <div class="my-wall-section">
                                    <p><span class="green-title">E-Intercession :</span> </p><!--Pray for earthquake and tsunami victims of Japan. City, State, Country-->
                             <div class="right-panel">
                            	<p class="quoted-text" style="padding:0px; background:none; margin-bottom:5px;">
                                 <a href="<?=base_url()?>e-intercession/<?=$latest_intercession[0]['id']?>/e-intercession-request-detail.html">  <?=my_substr(html_entity_decode(htmlspecialchars_decode($latest_intercession[0]['s_description']),ENT_QUOTES,'utf-8'),291);?></a>
                                    <span>Updated on: <?=get_time_elapsed($latest_intercession[0]['dt_insert_date'])?></span>  
    						   </p>
                              
                               <p class="intercession-home" style="color: #013D62;font-size: 12px;line-height: 16px;"><strong><?=get_country_name_by_id($latest_intercession[0]['i_country_id'])?></strong></p>
                               <p> <span class="intercession-home" style="color: #011F31;font-size: 12px;line-height: 16px;">From:  <?=getShortDateWithTime($latest_intercession[0]['dt_start_date'], 6)?></span></p>
                               <p> <span class="intercession-home" style="color: #011F31;font-size: 12px;line-height: 16px;">To:  <?=getShortDateWithTime($latest_intercession[0]['dt_end_date'], 6)?></span></p>
                             </div>
                                    
                              </div>
                              
                              <div class="my-wall-section">
                                    <?php
											$IMG = base_url().'uploads/prayer_wall_photos/'.getThumbName($latest_emergency_intercession[0]['s_image_name'],'mid_thumb');
											$DESC = html_entity_decode(htmlspecialchars_decode($latest_emergency_intercession[0]['s_description']),ENT_QUOTES,'utf-8'); 
									?>
									<div class="left">
                                                <span class="green-title">Prayer Click :</span>
												<br class="clr" style="margin-bottom: 10px;"/>
                                                <a href="javascript:void(0);"><div  title="prayer" style="background:url(<?=$IMG?>) no-repeat center;width:150px; height:74px;" class="pro_photo3"></div></a>
                                                <div>
                                                      <p style="margin-bottom:10px;" class="prayr_click"><?=$DESC?></p>
                                                      
                                                      <p class="blue_bold12 name-heading prayr_click">Updated on: <?=get_time_elapsed($latest_emergency_intercession[0]['dt_insert_date'])?></p>
                                                	  
                                                </div>
                                                <div class="light_heading liquid">
                                                    <ul>
                                                        <li class="left">No. of commitments (<span id="total_commitments"><?=$total_commits?></span>)</li>
                                                      
                                                      <?php if(!$isCommitExists){ ?>
                                                        <li><a class="right" href="javascript:void(0);" onclick="prayerClickCommit(<?=$latest_emergency_intercession[0]['id']?>)" id="prayerClickCommit">Commit</a></li>
                                                       <?php } ?>
                                                    </ul>
                                                	<div class="clr"></div>
                                                
                                                   
                                                	<div class="clr"></div>
                                                </div>
                                                <div class="clr"></div>
                                     </div>
                              </div>
                              
                              <div class="section01"> <img src="images/food.png" alt="" /> <a href="five-a-day.html"  <?php /*?>onclick="return show_dialog('five_a_day')"<?php */?>  class="big-grey-text"><strong>Have you had your "FIVE" a day ?</strong></a>
                                    <div class="clr"></div>
                              </div>
                              
                              
                              
                              <?php
								include(APPPATH ."views/newsfeed/newsfeed_post_.phtml");
					    	  ?>

                              <div class="div_content">
                                    <div class="nwheading">
                                          <div class="left">
                                                <h4>My Wall Messages &amp; Comments</h4>
                                          </div>
                                    </div>
                                   <div id="comment_result_div"><?=$result_newsfeed_content?></div>
                                    <?php if($no_of_result > 4): ?>
                                    
                                    <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?=$current_page_1?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
                                    <?php endif; ?>
                              </div>
                              <div class="div_content">
                                    <div class="nwheading">
                                          <div class="left">
                                                <h4>My Prayer Requests &amp; Commitments</h4>
                                          </div>
                                    </div>
                                    <div id="prayer_result_div"><?=$prayer_req_ajax_content?></div>
                                    <?php 
										if($prayer_no_of_result > 4): ?>
                                    
                                    <div class="view_more" id="show_more_prayer_div"><a href="javascript:void(0);" id="show_more_prayer_link" page_value="<?=$prayer_current_page?>" onclick="show_more_prayer($(this).attr('page_value'))">[view more] </a> </div>
                                    <?php endif; ?>
                                    
                              </div>
                              <div class="div_content">
                                    <div class="nwheading">
                                          <div class="left">
                                                <h4>My CoGTime Project Contributions</h4>
                                          </div>
                                          <!--<div class="right exp-col04"><img src="images/plus-white.png" alt=""  class="plus-minus"/></div>
                                          <div class="right exp-col04" style="display:none;"><img src="images/minus-white.png" alt=""  class="plus-minus"/></div> display:none;-->
                                    </div>
                                    <div class="div_content" id="switchdiv04" style=" margin-top:0;">
                                          <div class="project_box">
                                                <p class="blue_bold12"><a href="javascript:void(0);">Halloween Project</a></p>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do  tempor 
                                                      ut labore et dolore magna aliqua. ... <a  href="charity-project-home.php" class="blue_link">[read more]</a></p>
                                          </div>
                                          <div class="project_box">
                                                <p class="blue_bold12"><a href="javascript:void(0);">Good Friday Project</a></p>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do  tempor 
                                                      ut labore et dolore magna aliqua. ... <a  href="charity-project-home.php" class="blue_link">[read more]</a></p>
                                          </div>
                                          <div class="view_more"><a  href="javascript:void(0);" class="blue_link">[view more] </a> </div>
                                    </div>
                              </div>
                              <input type="hidden" value="<?=$first_login?>" name="is_first_login" id="is_first_login" />

                        </div>
                        
                        
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>

<?php /*?>POPUPS AND SCRIPTS<?php */?>

<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<?php include(APPPATH."views/logged/wall/my_wall_post_comment_lightbox.phtml");?>

<?php /*?>VIEW COMMENTS<?php */?>

<div class="lightbox view_comments_div " style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/cmnt.png" alt="" /> View Comments </h4>
                  </div>
            </div>
            <div id="comment_html"></div>

            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<?php /*?>VIEW COMMENTS<?php */?>

<?php /*?>LIKED LIGHT BOX <?php */?>
<div class="lightbox liked_by_div" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" style="height:299px;">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/thumb_up.png" alt="" /> Liked by </h4>
                  </div>
            </div>
            <div id="liked_html"></div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<?php /*?>LIKED LIGHT BOX <?php */?>

<?php /*?>delete confirm box for wall post <?php */?>
<div class="lightbox delete-post" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Prayer Points</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete this post?</p>
               </div>
               <form action="" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="i_del_partner_id" id="i_del_partner_id" value="" />
                 <input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_post()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>

<div class="lightbox five_a_day" style="width:530px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4>5 a Day </h4>
                  </div>
            </div>
            <div>
                 <?php if(count($five_fruits_arr)){
							foreach($five_fruits_arr as $key=> $val){
								
								$s_image_name = base_url() ."uploads/nine_bible_fruits/".$val['s_image_name'];
									 
				 ?>
                 
                  <div class="day_div"><img src="<?=$s_image_name?>" alt="" />
                        <p class="blue_bold12"> <?=$val['s_book_name']?> <?=$val['bible_chapter_no']?>:<?=$val['bible_verse_no']?></p>
                        <p><?=nl2br($val['s_verse'])?> </p>
                        <div class="clr"></div>
                  </div>
                  <?php 	
				  			}
				  		}
				  ?>
                                  
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<div class="lightbox commitments_div" style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="images/icons/hand.png" alt="" /> View Commitments </h4>
                  </div>
            </div>
            <div id="commitment_html"></div>
           
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<div class="lightbox commit_div" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4><img src="images/icons/hand.png" alt="" /> Commit to E-Intercession </h4>
                  </div>
            </div>
            <div class="frm_box">
                  <div class="lable05" style="padding-left:5px;">Commitment:</div>
                  <div class="clr"></div>
                  <div class="field03" style="width:442px;">
                        <textarea name="" cols="" rows="" style="width:442px; height:70px;"></textarea>
                  </div>
                  <div class="clr"></div>
                  <div class="lable05" style=" width:38px;"> From:</div>
                  <div class="field01" style=" width:165px;">
                        <select name="frm2" id="frm2" style="width:165px;">
                              <option>15 min</option>
                        </select>
                        <script type="text/javascript">
                                $(document).ready(function(arg) {
                                    $("#frm2").msDropDown();
                                    $("#frm2").hide();
                                })
                            </script>
                  </div>
                  <div class="lable01" style=" width:40px;">Date:</div>
                  <div class="field04" style="width:170px;">
                        <input style="width:140px;"   type="text"  value=" DD/MM/YYYY" name="date_to2" id="date_to2"  readonly="readonly"/>
                        <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                        <script type="text/javascript">
							$(document).ready(function(arg) {
								$.datepicker.setDefaults($.datepicker.regional['']);
								$("#date_to2").datepicker($.datepicker.regional['en']);

							});
						</script>
                  </div>
                  <div class="clr"></div>
                  <div class="lable05" style=" width:38px;"> To:</div>
                  <div class="field01" style=" width:165px;">
                        <select name="to8" id="to8" style="width:165px;">
                              <option>15 min</option>
                        </select>
                        <script type="text/javascript">
                                $(document).ready(function(arg) {
                                    $("#to8").msDropDown();
                                    $("#to8").hide();
                                })
                            </script>
                  </div>
                  <div class="lable01" style=" width:40px;">Date:</div>
                  <div class="field04" style="width:170px;">
                        <input style="width:140px;"   type="text"  value=" DD/MM/YYYY" name="date_to3" id="date_to3"  readonly="readonly"/>
                        <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                        <script type="text/javascript">
							$(document).ready(function(arg) {
								$.datepicker.setDefaults($.datepicker.regional['']);
								$("#date_to3").datepicker($.datepicker.regional['en']);

							});
						</script>
                  </div>
                  <div class="clr"></div>
                  <input name="" class="submit-green" type="submit" value="Post" style="margin-top:15px;" />
                  <div class="clr"></div>
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<!-- ------------------------------------------------- -->
<script type="text/javascript">
$(document).ready(function(){

//var my_location = location ; //alert(my_location);
var check_first_login = $('#is_first_login').val();
//alert(check_first_login);
if(check_first_login != '')
{
	show_dialog('welcome');
}

});
</script>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_feeds(page) {
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/my_wall/newsfeed_pagination_show_more/<?=$profile_id?>'+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#comment_result_div').append(data.html);
				$('#show_more_feeds_link').attr('page_value', data.current_page);
			}
			else {
				$('#comment_result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more posts to display.</p></div>');
				$('#show_more_feeds_div').hide();
			}
			
			/*$('.htr').css('display','none');
			$('#'+m).css('display', 'table-row'); 
			$('#'+m+' td').html(data);*/

		}	// end of success function...
	});
}



var ajax_req_prayer = null;
function show_more_prayer(page) {
	if(ajax_req_prayer!=null) {
		ajax_req_prayer.abort();
	}
	showUILoader_nodialog();
	ajax_req_prayer = $.ajax({
		type: 'get',
		url: base_url+'logged/my_wall/my_all_prayer_request_ajax_pagination/<?=$profile_id?>'+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#prayer_result_div').append(data.html);
				$('#show_more_prayer_link').attr('page_value', data.cur_page);
			}
			else {
				$('#prayer_result_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more posts to display.</p></div>');
				$('#show_more_prayer_div').hide();
			}
			
			/*$('.htr').css('display','none');
			$('#'+m).css('display', 'table-row'); 
			$('#'+m+' td').html(data);*/

		}	// end of success function...
	});
}


 function show_commits(i_prayer_id)
  {
		 
	 showUILoader('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
		$.ajax({
			
			url: base_url +'logged/my_wall/fetch_commit_on_prayer/'+i_prayer_id,
			dataType: 'json',
			type: 'post',
	
			success: function (data, status) {
				//hideUILoader();
				$('#commitment_html').html(data.html_data);
				hideUILoader('commitments_div');
				//hideBusyScreen();
				showUIMsg(data.msg);
			},
			error: function(data, status, e) {
				hideUILoader('commitments_div');
				//show_dialog('view_comments_div');
				showUIMsg("Error!");
				
			}
		});
				 
		 
  }
  
  
  function prayerClickCommit(id){
		showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
		$.ajax({
			
			url: base_url+'logged/e_intercession/commitPrayerClick/'+ id,
			dataType: 'json',
			data: '',
			type: 'post',
	
			success: function (data, status) {
				     $('#total_commitments').html('');
				     $('#total_commitments').html(data.total_commits);
					 $('#prayerClickCommit').hide();
					 showUIMsg(data.msg);
					 hideUILoader_nodialog();
			},
			error: function(data, status, e) {
				hideUILoader_nodialog();
				showUIMsg("Error!");
				
			}
		});
  }
  
  
function getPrayerClickCommit(id) {
	$.ajax({
	   type: "post",
	   url: base_url+'logged/e_intercession/getPrayerClickTotalCommit/'+id,
	   dataType:"json",
	   success: function(data){
				$('#total_commitments').html('');
				$('#total_commitments').html(data.total_commits);
		}
	});
}


$(document).ready(function(arg) {
	getPrayerClickCommit('<?=$latest_emergency_intercession[0]['id']?>');
	setInterval(function(){getPrayerClickCommit('<?=$latest_emergency_intercession[0]['id']?>')},59000);
});
</script>
