<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />
<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>


<script type="text/javascript">
$(function(){
		$("#wall_friendSlct").multiselect().multiselectfilter();	
		$("#wall_ringselect").multiselect().multiselectfilter();
		$("#wall_netpalselect").multiselect().multiselectfilter();
		$("#wall_ppselect").multiselect().multiselectfilter();
		$("#wall_pgselect").multiselect().multiselectfilter();
		
		$("#wallCommentLike_friendSlct").multiselect().multiselectfilter();	
		$("#wallCommentLike_ringselect").multiselect().multiselectfilter();
		$("#wallCommentLike_netpalselect").multiselect().multiselectfilter();
		$("#wallCommentLike_ppselect").multiselect().multiselectfilter();
		$("#wallCommentLike_pgselect").multiselect().multiselectfilter();
	});
</script>

<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
.settings_div{ width:460px !important;}
</style>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <div id="mid_container">
                              <div class="page_heading">
                                    <div class="left"><img src="images/icons/msgg.png" alt="" />View Timeline </div>
                              </div>
                              <div class="arrow_btm"></div>
                              <form action="<?=base_url().'logged/my_wall/update_wall_privacy_settings'?>" name="frm" id="frm" method="post"  onsubmit="return false;" >  
                                <div class="shade_box_01 email_settings">
                            
                                    <h4>Post In Wall</h4>
                                    <div class="settings_div" >
                                    	<div class="field01 gap-main-r ">
										
                                        <?php echo get_privacy_setting('wall',$privacy_arr_wall, 'wall_');
                                        ?>
                                       <a href="<?=base_url()?>privacy-settings.html" class="privacy-change">Change</a>
                                       <div class="clr"></div>
                                        <span id="err_privacy_arr_wall" class="error-message"></span> 
                                        </div>     		
                                     </div>
                                     
                                     <h4>Comments/Likes In Wall</h4>
                                     <div class="settings_div">
                                    	<div class="field01 gap-main-r ">
										
                                        <?php echo get_privacy_setting('wallCommentLike',$privacy_arr_wallCommentLike, 'wallCommentLike_');
                                        ?>
                                       <a href="<?=base_url()?>privacy-settings.html" class="privacy-change">Change</a>
                                       <div class="clr"></div>
                                        <span id="err_privacy_arr_wallCommentLike" class="error-message"></span> 
                                        </div>     		
                                     </div>
                                    
                                    <p>&nbsp;</p>
                                    <input name="" type="button" value="Update" class="btn bottom-button" onclick="$('#frm').submit();" />
                              </div>
                              </form>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script type="text/javascript">

 function showOptions(obj,flag)
 {
	 if(flag=='public')
	 {
	 	$(obj).next().next().next().next().hide();
	 }
	 else if(flag=='private')
	 {
	 	$(obj).next().next().next().show();
	 }
 }
 
 function showAll(obj)
 {//console.log(obj);
	$(obj).parent().next().next().slideToggle();
 }
 
 $(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoading,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});
// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		showUIMsg(data.msg);	
	}
	else {
		
		showUIMsg(data.msg);		
		window.location.href= "<?php echo base_url().'wall-privacy-settings.html'?>";
		
	}
	$('#sp_add_loading').html('');
	hideLoading();
				
}
</script>
