<div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Languages I Speak:</div>  
                                        <div class="field01">
                                        <input name="txt_lang" id="txt_lang" type="text" value="<?=isset($arr_profile_info["s_languages"])? $arr_profile_info["s_languages"]: '' ?>" />
                                        <?php echo form_error('txt_lang'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">About Me:</div>  
                                        <div class="field01">
                                        <textarea name="txt_about" id="txt_about"><?=isset($arr_profile_info["s_about_me"])? $arr_profile_info["s_about_me"]: '' ?></textarea>
                                        <?php echo form_error('txt_about'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <p class="lable01" style="font-weight: bold; font-size: 12px;">Church Details</p>
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Name:</div>  
                                        <div class="field01">
                                        <input name="txt_cname" id="txt_cname" type="text" value="<?=isset($arr_profile_info["s_church_name"])? $arr_profile_info["s_church_name"]: '' ?>" />
                                        <?php echo form_error('txt_cname'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Address:</div>  
                                        <div class="field01">
                                        <textarea rows="" cols="" name="txt_caddress" id="txt_caddress"><?=isset($arr_profile_info["s_church_address"])? $arr_profile_info["s_church_address"]: '' ?></textarea>
                                        <?php echo form_error('txt_caddress'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                       <?php /*?> <div class="lable01">City:</div>  
                                        <div class="field01">
                                        <input name="txt_ccity" id="txt_ccity" type="text" value="<?=isset($arr_profile_info["s_church_city"])? $arr_profile_info["s_church_city"]: '' ?>" />
                                        <?php echo form_error('txt_ccity'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">State:</div>  
                                        <div class="field01">
                                        <input name="txt_cstate"  id="txt_cstate" type="text" value="<?=isset($arr_profile_info["s_church_state"])? $arr_profile_info["s_church_state"]: '' ?>" />
                                        <?php echo form_error('txt_cstate'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Country:</div>  
                                        <div class="field01">
                                        
                                        <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;">
                                            <option value="-1">---</option>
                                            <?=makeOptionCountry('',encrypt($arr_profile_info["i_church_country_id"]));?>

                                        </select>
                                        <?php echo form_error('txt_ccountry'); ?>
                                        </div> 
                                        <div class="clr"></div> <?php */?>
                                        
                                        <div class="lable01">Country:</div>  
                                        <div class="field01">
                                        
                                        <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;" onchange="showChurchState(this.value);">
                                            <option value="-1">---</option>
                                            <?=makeOptionCountryNew('',encrypt($arr_profile_info["i_church_country_id"]));?>

                                        </select>
                                        <?php echo form_error('txt_ccountry'); ?>
             
                                        </div> 
                                        <div class="clr"></div> 
                                        
                                        <div class="lable01">State:</div>  
                                        <div class="field01">
                                        <select name="txt_cstate" id="txt_cstate" onchange="showChurchCity(this.value)">
                                        	<option value="-1">---</option>
											<?=$cstate;?>
                                        </select>
                                        
                                        <?php echo form_error('txt_cstate'); ?>
                                         <div class="error-message" id="err_cstate"></div>
                                        </div> 
										<div class="clr"></div> 
                                        <div class="lable01">City:</div>  
                                        <div class="field01">
                                        <select name="txt_ccity" id="txt_ccity">
                                        	<option value="-1">---</option>
											<?=$ccity;?>
                                        </select>
                                        
                                        <?php echo form_error('txt_ccity'); ?>
                                         <div class="error-message" id="err_ccity"></div>
                                         </div>
                                        
                                        <div class="lable01">Postcode:</div>  
                                        <div class="field01">
                                        <input name="txt_cpostcode" id="txt_cpostcode" type="text" value="<?=isset($arr_profile_info["s_church_postcode"])? $arr_profile_info["s_church_postcode"]: '' ?>" />
                                        <?php echo form_error('txt_cpostcode'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Phone:</div>  
                                        <div class="field01">
                                        <input name="txt_cphone" id="txt_cphone" type="text"  value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>"/>
                                        <?php echo form_error('txt_cphone'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Denomination:</div>  
                                        <div class="field01">
                                         <select name="txt_denomination" id="txt_denomination" style="width:260px;">
                                             <option value="<?=encrypt(0)?>"><?="Denomination"?></option>
                                             <?=makeOptionDenomination(encrypt($arr_profile_info['i_id_denomination']));?>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                //$("#txt_denomination").msDropDown();
                                                //$("#txt_denomination").hide();
                                            })
                                        </script>
                                        <?php echo form_error('txt_denomination'.'===='); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <!--<div class="lable01">Profile Photo:</div>  
                                        <div class="field01"><input name="" type="file" size="25" /></div> 
                                        <div class="clr"></div>-->
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                          <input type="hidden" name="is_basic_submitted" id="is_basic_submitted" value="Y" />
                                          <input name="" type="submit" value="Save"  class="btn" />
                                          <input name="" type="button" value="Cancel"  class="btn" onclick="closeBasicInfoDiv()"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>