                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                    
                                    <?php
                                    $count=count($arr_profile_info['work_arr']);
                                        if ($count==0)
                                            $count=1;
                                        for($i=0;$i<$count;$i++)   :
                                                   
                                    ?>
                                   
                                    <!--work div-->
                                    <div id="<?php echo (($i>0)? 'work_div_'.($i+1):'work_div_1')?>"> 
                                    <?php 
                                        if($i>0 && $i<$count)
                                        {
                                            $j= $i+1;

                                            echo "<h4 class='sepration'></h4><a class='close' href='javascript:void(0);' style='margin:5px;' onclick=\"closeExtraWorkDiv(this)\" ><img src='images/icons/close.png' alt='' width='24' height='24'></a>";
                                        }
                                    ?>
                                      <div class="lable01">Employer:</div>  
                                        <div class="field01"><input name="txt_work_company[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_name"])? $arr_profile_info["work_arr"][$i]["s_employer_name"]: '' ?>" style="width:230px;" /> </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work City:</div>  
                                        <div class="field01"><input name="txt_work_city[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_city"])? $arr_profile_info["work_arr"][$i]["s_employer_city"]: '' ?>" style="width:230px;" /></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work State:</div>  
                                        <div class="field01"><input name="txt_work_state[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_state"])? $arr_profile_info["work_arr"][$i]["s_employer_state"]: '' ?>"  style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work Country:</div>  
                                        <div class="field01"><? /*<input name="txt_work_country[]" type="text" value="<?=isset($arr_profile_info["work_arr"][$i]["s_employer_country"])? $arr_profile_info["work_arr"][$i]["s_employer_country"]: '' ?>" style="width:230px;" />*/?>
                                        <select name="txt_work_country[]" class="txt_country_work" style="width:238px; margin-bottom:6px;">
                                             <option value="-1">---</option>
                                             <?=makeOptionCountry('',encrypt($arr_profile_info["work_arr"][$i]["s_employer_country"]));?>
                                         
                                         </select>
                                        
                                        
                                        </div> 
                                        <div class="clr"></div> 
                                        <div class="lable01">Position:</div>  
                                        <div class="field01"><input name="txt_work_position[]" type="text"  value="<?=isset($arr_profile_info["work_arr"][$i]["s_position"])? $arr_profile_info["work_arr"][$i]["s_position"]: '' ?>" style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Period:</div>  
                                        
                                        
                                         <div class="field01" >
                                          <span class="left" style="width:40px;">From :</span>
                                          <select name="mnth_from[]" class="profile_combo mnth_from" style="width:133px; float:left;">
                                             <option value="-1">---</option>
                                             <?php echo makeOptionMonth(isset($arr_profile_info["work_arr"][$i]["i_experience_month_from"])? $arr_profile_info["work_arr"][$i]["i_experience_month_from"]:'')?> 
                                            </select>
                                               <script type="text/javascript">
                                                    $(document).ready(function(arg) {
                                                        //$(".profile_combo").msDropDown();
                                                        //$(".profile_combo").hide(); 
      
                                                    })
                                                </script>
                                                
                                         
                                          
                                        <select name="year_from[]" class="profile_combo year_from" style="width:60px; margin-bottom:10px; float:left;">
                                                   <option value="-1">---</option>
                                                 <?=makeOptionYear(isset($arr_profile_info["work_arr"][$i]["s_experience_year_from"])? $arr_profile_info["work_arr"][$i]["s_experience_year_from"]:'')?>
                                         </select>
                                               
                                         <div class="clr"></div>

                                         
                                         <span class="left" style="width:40px;">To :</span>

                                         
                                         <select name="mnth_to[]" class="profile_combo mnth_to" style="width:133px; float:left;"  <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo " disabled='disabled' id= 'disabled_mnth_to' ";?>>
                                             <option value="-1">---</option>
                                             <?php echo makeOptionMonth(isset($arr_profile_info["work_arr"][$i]["i_experience_month_to"])? $arr_profile_info["work_arr"][$i]["i_experience_month_to"]:'');?> 
                                            </select>
                                          
                                          
                                         <select name="year_to[]" class="profile_combo year_to" style="width:60px; margin-bottom:10px; float:left;" <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo "disabled='disabled' id= 'disabled_year_to'";?>>
                                                   <option value="-1">---</option>
                                                 <?=makeOptionYear(isset($arr_profile_info["work_arr"][$i]["s_experience_year_to"])? $arr_profile_info["work_arr"][$i]["s_experience_year_to"]:'')?>
                                         </select>
                                      
                                         </div>
                                      
                                         
                                        <div class="clr"></div>
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01">
                                            <input name="is_current_employer" type="radio" class="radio_cur_emp"  onclick="return current_emp(this);"  <?php if($arr_profile_info["work_arr"][$i]["e_is_current_employer"]=='yes') echo "checked";?> value="<?= $arr_profile_info["work_arr"][$i]["id"]; ?>"  /> Current Employer
                                        </div>
                                        
                                       
                                        
                                        <input type="hidden" name="db_id[]" id="dbId" value="<?php echo isset($arr_profile_info["work_arr"][$i]["id"])? $arr_profile_info["work_arr"][$i]['id']: '0'?>">
                                        </div>  <!--/work div-->
                                        <script type="text/javascript">
                                                    $(document).ready(function(arg) {
                                                       
                                                        //$(".txt_country_work").msDropDown();
                                                        //$(".txt_country_work").hide();        
                                                    })
                                                </script>
                                        <?php
                                            endfor;
                                        ?>
                                
                                
                                        <div id="add_more_work_div">  </div>
                                        
                                         <input type="hidden" name= "total_work_divs" id="work_div_h" value="<?php echo $count;?>" />
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01" style="text-align:right;width:250px;"> 
                                             <a href="javascript:void(0);" id="add_extra_work"   class="blue_link" onClick="add_extra_work_div()"><strong>Add More..</strong></a>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                        <input type="hidden" name="is_work_submitted" id="is_work_submitted" value="Y" />
                                        <input name="" type="submit" value="Save"  class="btn"  />
                                        <input name="" type="button" value="Cancel"  class="btn" onclick="closeWorkDiv();"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                     
                                     
                                        <?php /*?> //////////// NEW FIELD(S) [BEGIN] //////////// <?php */?>
                                        <input type="hidden" name="actual_work_divs" id="actual_work_divs" value="<?= count($arr_profile_info['work_arr']) ?>" />
                                        <input type="hidden" name="deleted_work_ids" id="deleted_work_divs" value="" />
                                        <input type="hidden" name="work_div_id_order" id="work_div_id_order" value="<?= count($arr_profile_info['work_arr']) ?>" />
                                        <?php /*?> //////////// NEW FIELD(S) [END] //////////// <?php */?>