<script type="text/javascript">
 function changeStatus(id,i_status ,cur_status)
	{
		var URL = '<?php echo admin_base_url()?>' +'site_settings/scrolling_headlines/change_status/';
		showBusyScreen();
		if(ajax_req!=null) {
			ajax_req.abort();
		}
		ajax_req = $.ajax({
			type: 'POST',
			url:URL,
			dataType: 'json',
			data: ({ 'record_id' : id
				   	 ,'i_status' : i_status
					 ,'cur_status' : cur_status
				 }),
			success: function (data, status) {
							var result_obj = data;
							hideBusyScreen();
							if(result_obj.result=='success' && result_obj.redirect == false ) {
								showUIMsg(result_obj.msg);
								$('#'+result_obj.u_id+'_status').html(result_obj.action_txt);
							}
							else if(result_obj.result==false && result_obj.redirect == true){
							    showUIMsg(result_obj.msg);
							}
					},
			error: function (data, status, e) {
								hideBusyScreen();
								showUIMsg(data.msg);
			}
		});
	}

  
  function clear_box(mode){
	  if(mode == 'add'){
		  $('#frm_scrolling')[0].reset();
		  $('.error-message').hide();
	  }else{
		  $('#frm_edit_headlines')[0].reset();
		   $('.error-message').hide();
		}
  }
  
  function edit_headlines(id)
	{
		$('#i_edit_id').val(id );
		 showUILoader('<img src="<?= base_url() ?>images/loading_big.gif" width="50"/> ');
	  
			 $.ajax({
				 type: "get",
				 url: '<?=admin_base_url()?>site_settings/scrolling_headlines/edit_info/'+id,
				 dataType:"json",
				 success: function(json_response){
					 
					  if(json_response.result = 'success') {
						  
						  $('#txt_edit_headline').val('');
						  $('#txt_edit_url').val('');
						  
						  $('#txt_edit_headline').val(json_response.s_headlines);
						  $('#txt_edit_url').val(json_response.s_url);	
						 	hideUILoader('edit-scrolling-headlines');
						  //setTimeout(function(){hideUILoader('edit-scrolling-headlines')},200);
					  }
					  else {
						   hideUILoader('edit-scrolling-headlines');
						  showUIMsg('Some error occurred. Please try again.');
					  }
				  },
				  error: function(){
					 hideUILoader('edit-scrolling-headlines');
					  showUIMsg('Some error occurred. Please try again.');
				  }
			  });	 
		//show_dialog('edit-scrolling-headlines');
		//return false;
	}
 </script>


<div class="clr"></div>
<!-- CONTENT SECTION -->
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<div id="content_section">
      <div id="container">
            
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" />  Scrolling Headlines</div>
                        <div class="right"><input name="" type="button" value="Add New Headline"  class="evnt_btn1" onclick="return show_dialog('add-scrolling-headlines')"/></div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        
                        <div class="content_area">
                                              
                        <DIV ID ="table_content" >
                        <?=$result_content?>
                        </DIV>

                              
                        <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->


<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Scrolling Headline</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">Do you really want to delete the scrolling headline?</p>
               <form method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<!--popup add headlines start-->
<div class="lightbox add-scrolling-headlines" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Add Scrolling Headline</h4>
                       
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
              		
               <div class="content_area frm_box2" style="padding-top: 0px;" >
               <span style="font-size:11px;font-style:italic;line-height:13px;display:inline-block; height:30px; padding-top: 5px;">(Note: Only for external News link.)</span>
                
                        	  <form id="frm_scrolling"  method="post"  onsubmit="return post_frm_ajax();" enctype="multipart/form-data"> 
                                  <div class="lable01"><span class="red-mark">* </span> Headline :</div>
                                  <div class="field01">
                                        <input name="txt_headlines" id="txt_headlines" type="text" style="margin:0px;" maxlength="90"/>
                                         <div class="clr"></div>
                                  		 <span>(Max 30 characters.)</span>
                                  </div>
                                  <div class="error-message" id="err_headlines"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01"><span class="red-mark">* </span> URL :</div>
                                  <div class="field01">
                                        <input name="txt_feed" id="txt_feed" type="text" />
                                  </div>
                                  <div class="error-message" id="err_feed"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01"> </div>
                                  <div class="field01">
                                        <input name="" type="submit" class="btn"  value="Add"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('add');hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup add headlines end-->


<!--popup edit headlines start-->
<div class="lightbox edit-scrolling-headlines" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Scrolling Headline</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2" style="padding-top: 0px;" >
               <span style="font-size:11px;font-style:italic;line-height:13px;display:inline-block; height:30px;padding-top: 5px;">(Note: Only for external News link.)</span>
                        	  <form name="frm_edit_headlines" id="frm_edit_headlines" action="" method="post" onsubmit="return post_frm_edit_ajax();">
                                  <div class="lable01"><span class="red-mark">* </span> Headline :</div>
                                  <div class="field01">
                                        <input name="txt_edit_headline" id="txt_edit_headline" type="text"  style="margin:0px;" maxlength="90"/>
                                         <div class="clr"></div>
                                  		<span>(Max 30 characters.)</span>
                                  </div>
                                  <div class="error-message" id="err_edit_headline"></div>
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01"><span class="red-mark">* </span> URL :</div>
                                  <div class="field01">
                                        <input name="txt_edit_url" id="txt_edit_url" type="text" />
                                  </div>
                                  <div class="error-message" id="err_edit_url"></div>
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01"> </div>
                                  <div class="field01">
                                  		<input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('edit');hide_dialog()"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup edit headlines end-->