<?php
#pr($arr_prayer_request); 
if (count($arr_prayer_request)) {
    foreach ($arr_prayer_request as $key => $val) {

        $IMG = base_url() . 'uploads/prayer_wall_photos/' . getThumbName($val['s_image_name'], 'mid');
        $DESC = html_entity_decode(htmlspecialchars_decode($val['s_description']), ENT_QUOTES, 'utf-8');
        $s_subject = html_entity_decode(htmlspecialchars_decode($val['s_subject']), ENT_QUOTES, 'utf-8');
       // echo $val['id'];
        ?>

        <div class="prayer-wall-dotted-box">
            <div class="prayer-wall-image">
                <div  title="prayer" style="background:url(<?= $IMG ?>) no-repeat center;width:286px; height:142px;"></div>
            </div>
            <div class="right-panel">
                <p class="quoted-text"><a href="<?= base_url() ?>e-intercession/<?= $val['id'] ?>/e-intercession-request-detail.html"><?= ($s_subject) ?></a></p> 
                <p class="quoted-text">
                    <a href="<?= base_url() ?>e-intercession/<?= $val['id'] ?>/e-intercession-request-detail.html"><?= nl2br($DESC) ?></a> 
                    <span style="color:#013D62; font-size:13px;">Location: <?= (get_city_name_by_id($val['i_city_id'])) . ', ' . (get_state_name_by_id($val['i_state_id'])) . ', ' . get_countryname($val['i_country_id']) ?></span>
                    <span>Updated on: <?= get_time_elapsed($val['dt_insert_date']) ?></span>
                </p>
                <?php /* ?><h2 class="name"><?=$val['posted_by_admin']?></h2><?php */ ?>


                <p class="date-time">From: <span><?= getShortDateWithTime($val['dt_start_date'], 9) ?></span> | To: <span><?= getShortDateWithTime($val['dt_end_date'], 9) ?></span></p>
            </div>
            <div class="clr"></div>

            <ul class="article-comment-block">
                <!--<li class="first"><span><a href="javascript:void(0);" class="commit-open-close">Commit</a></span></li> 
                <li><a href="javascript:void(0);" class="commitment-open-close">Commitments (<span>2</span>)</a></li>
                <li><a href="javascript:void(0);" class="testimony-open-close">Testimony</a></li> -->

                <?php if ($val['commit_exists'] == 0) { ?> 
                    <li class="first" id="commit_li<?= $val['id'] ?>"><span><a href="javascript:void(0);" class="commit-open-close" onclick="show_reply(<?= $val['id'] ?>)" >Commit</a></span></li> 

                    <li><a href="javascript:void(0);" class="commitment-open-close" onclick="view_commits(<?= $val['id'] ?>)" >Commitments <span id="total_commits<?= $val['id'] ?>">(<?= $val['total_commitments'] ?>)</span></a></li>

                    <li><a href="javascript:void(0);" class="testimony-open-close" onclick="view_testimony(<?= $val['id'] ?>)">Testimony (<?= get_e_intercession_testimony_count($val['id']); ?>)</a></li> 

                <?php } else { ?>
                    <li class="first"><a href="javascript:void(0);" class="commitment-open-close" onclick="view_commits(<?= $val['id'] ?>)" >Commitments <span id="total_commits<?= $val['id'] ?>">(<?= $val['total_commitments'] ?>)</span></a></li>

                    <li><a href="javascript:void(0);" class="testimony-open-close" onclick="view_testimony(<?= $val['id'] ?>)">Testimony (<?= get_e_intercession_testimony_count($val['id']); ?>)</a></li> 
                <?php } ?>

            </ul>
            <!--commit form start -->
            <div class="commit-form" id="commit_form<?= $val['id'] ?>">
                <!--minimize link start -->
                <div class="minimize" title="Minimize" onclick="show_reply(<?= $val['id'] ?>)">&nbsp;</div>
                <!--minimize link end -->
                <h2>Add Commitment</h2>
                <form  id="add_commit<?= $val['id'] ?>" action="" method="post" enctype="multipart/form-data">
                    <!--left side start  -->
                    <div class="left-side" style="width:410px;">
                        <label>Word of Encouragement:</label>
                        <textarea onblur="if (this.value == '')
                                            this.value = 'Max 140 Characters';" onfocus="if (this.value == 'Max 140 Characters')
                                                        this.value = '';" rows="" cols="" name="ta_commit_text" id="ta_commit_text_<?= $val['id'] ?>" class="big-textarea" onKeyDown="limitText(this.form.ta_commit_text, this.form.countdown, 140);" 
                                  onKeyUp="limitText(this.form.ta_commit_text, this.form.countdown, 140);" style="height: 36px;width:370px;" >Max 140 Characters</textarea>
                        <span id="err_message<?= $val['id'] ?>" class="error-message"></span> 
                    </div>
                    <!--left side end  -->

                    <!--right side start -->
                    <div class="right-side" style=" float:left; width:320px;">

                        <label class="small">From:</label>

                        <div class="field04" style="width:270px; float:left; ">
                            <input style="width:170px; float:left; margin-right:4px; "   type="text"  value="" name="commit_date_to" id="commit_date_to_<?= $val['id'] ?>"  readonly="readonly"/>
                            <img src="images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" style="cursor:pointer; float:left;" />
                            <script type="text/javascript">
                                $(document).ready(function(arg) {



                                    $(function() {
                                        var inputDate = $("#commit_date_to_<?= $val['id'] ?>");
                                        var changeYearButtons = function() {
                                            setTimeout(function() {
                                                $('.NextYrClass').remove();
                                                $('.PrevYrClass').remove();
                                                var widgetHeader = inputDate.datepicker("widget").find(".ui-datepicker-header");
                                                //you can opt to style up these simple buttons tho
                                                var prevYrBtn = $('<button title="PrevYr" class="PrevYrClass"></button>');
                                                prevYrBtn.bind("click", function() {
                                                    $.datepicker._adjustDate(inputDate, -1, 'Y');
                                                });
                                                var nextYrBtn = $('<button title="NextYr" class="NextYrClass"> </button>');
                                                nextYrBtn.bind("click", function() {
                                                    $.datepicker._adjustDate(inputDate, +1, 'Y');

                                                });
                                                prevYrBtn.appendTo(widgetHeader);
                                                nextYrBtn.appendTo(widgetHeader);

                                            }, 0);
                                        };

                                        $("#commit_date_to_<?= $val['id'] ?>").datepicker({
                                            beforeShow: changeYearButtons,
                                            onChangeMonthYear: changeYearButtons,
                                            dateFormat: 'yy-mm-dd',
                                            minDate: new Date(<?= (date('Y')) ?>, <?= (date('m') - 1) ?>, <?= (date('d')) ?>, 0, 00),
                                            //controlType: 'select',
                                            //stepMinute: 15
                                        });

                                    });


                                    $(function() {
                                        var inputDate = $("#commit_date_end_<?= $val['id'] ?>");
                                        var changeYearButtons = function() {
                                            setTimeout(function() {
                                                $('.NextYrClass').remove();
                                                $('.PrevYrClass').remove();
                                                var widgetHeader = inputDate.datepicker("widget").find(".ui-datepicker-header");
                                                //you can opt to style up these simple buttons tho
                                                var prevYrBtn = $('<button title="PrevYr" class="PrevYrClass"></button>');
                                                prevYrBtn.bind("click", function() {
                                                    $.datepicker._adjustDate(inputDate, -1, 'Y');
                                                });
                                                var nextYrBtn = $('<button title="NextYr" class="NextYrClass"></button>');
                                                nextYrBtn.bind("click", function() {
                                                    $.datepicker._adjustDate(inputDate, +1, 'Y');

                                                });
                                                prevYrBtn.appendTo(widgetHeader);
                                                nextYrBtn.appendTo(widgetHeader);

                                            }, 0);
                                        };

                                        $("#commit_date_end_<?= $val['id'] ?>").datepicker({
                                            beforeShow: changeYearButtons,
                                            onChangeMonthYear: changeYearButtons,
                                            dateFormat: 'yy-mm-dd',
                                            minDate: new Date(<?= (date('Y')) ?>, <?= (date('m') - 1) ?>, <?= (date('d')) ?>, 0, 00),
                                            //controlType: 'select',
                                            //stepMinute: 15
                                        });

                                    });
                                });
                            </script>

                            <span id="err_start_date<?= $val['id'] ?>" class="error-message"></span> 
                        </div>


                        <div class="clr"></div>
                        <label class="small">To:</label>

                        <div class="field04" style="width:270px; float:left;">
                            <input style="width:170px; float:left; margin-right:4px;"   type="text"  value="" name="commit_date_end" id="commit_date_end_<?= $val['id'] ?>"  readonly="readonly"/>
                            <img src="images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" style="cursor:pointer; float:left;" />

                            <span id="err_end_date<?= $val['id'] ?>" class="error-message"></span> 
                        </div>



                    </div>
                    <!--right side end -->

                    <div id="day_block" style="float:left; margin-top:12px;">
                        <label> Day of Week:</label>
                        <div class="secttion-padding">
                            <table class="cal_table" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <th class="nw-cal_table">S</th>
                                    <th class="nw-cal_table">M</th>
                                    <th class="nw-cal_table">T</th>
                                    <th class="nw-cal_table">W</th>
                                    <th class="nw-cal_table">T</th>
                                    <th class="nw-cal_table">F</th>
                                    <th class="nw-cal_table">S</th>
                                </tr>
                                <tr id="weekdays_tr<?= $val['id'] ?>">
                                    <td valign="middle">
                                        <input name="chk_day[]"  type="checkbox" value="Sunday" <?= (in_array('Sunday', $week_arr)) ? 'checked="checked"' : '' ?>  />
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Monday" <?= (in_array('Monday', $week_arr)) ? 'checked="checked"' : '' ?> />
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Tuesday" <?= (in_array('Tuesday', $week_arr)) ? 'checked="checked"' : '' ?>/>
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Wednesday" <?= (in_array('Wednesday', $week_arr)) ? 'checked="checked"' : '' ?>/>
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Thursday" <?= (in_array('Thursday', $week_arr)) ? 'checked="checked"' : '' ?>/>
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Friday" <?= (in_array('Friday', $week_arr)) ? 'checked="checked"' : '' ?>/>
                                    </td>
                                    <td valign="middle">
                                        <input name="chk_day[]" type="checkbox" value="Saturday" <?= (in_array('Saturday', $week_arr)) ? 'checked="checked"' : '' ?>/>
                                    </td>
                                </tr>
                            </table>

                        </div>
                        <span id="err_chk_day<?= $val['id'] ?>" class="error-message err_new"></span> 
                        <div class="clr"></div>
                    </div>


                    <div class="clr"></div>

                    <DIV class="view-pray-time">
                        <label> Prayer Time: </label>
                        <div class="prayer-time secttion-padding time-list-adjust" id="time_tr<?= $val['id'] ?>">
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="00:00:00-03:00:00" /> 0:00 – 3:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="03:00:00-06:00:00" /> 3:00 – 6:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="06:00:00-09:00:00" /> 6:00 – 9:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="09:00:00-12:00:00" /> 9:00 – 12:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="12:00:00-15:00:00" /> 12:00 – 15:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="15:00:00-18:00:00" /> 15:00 – 18:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="18:00:00-21:00:00" /> 18:00 – 21:00</div>
                            <div class="lbl02"><input name="chk_time[]" type="checkbox" value="21:00:00-23:00:00" /> 21:00 – 23:00</div>
                        </div>
                        <span id="err_chk_time<?= $val['id'] ?>" class="error-message err_new"></span> 
                    </DIV>

                    <input name="post" type="button" value="Post" class="post-btn" onclick="post_reply(<?= $val['id'] ?>)" />
                </form>
                <div class="clr"></div>
            </div>
            <!--commit form end -->

            <div class="commitment-container" id="commitment-container<?= $val['id'] ?>">
                <div title="Minimize" class="minimize" onclick="view_commits(<?= $val['id'] ?>)">&nbsp;</div>
                <h2 class="title">View Commitments</h2>
                <DIV id ="commitment_content_<?= $val['id'] ?>">
                    <!--commitment start -->

                    <!--commitment end -->
                </DIV>
            </div>

            <div class="testimony-container" id="testimony-container<?= $val['id'] ?>">
                <div class="minimize" title="Minimize" onclick="view_testimony(<?= $val['id'] ?>)"> </div>
                <h2 class="title">View Testimony</h2>
                <!--testimony start -->
                <DIV id ="testimony_content_<?= $val['id'] ?>" ></DIV>
                <!--testimony end -->
            </div>
        </div>


        <?php
    }
}
?>