<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
							<div class="page_heading">
                                    <div class="left"><img src="images/icons/box.png" alt="" /><?php echo $info['product_id']?></div>
                                      <div class="right">
                                        <input type="button" onclick="window.location='<?php echo $_SERVER['HTTP_REFERER']?>'" value="Back" style="" class="yellow-btn" />
                                    </div>
                            </div>
                            <?php include(APPPATH."views/logged/efreebie/menu.phtml");?>
							  <div class="arrow_btm"></div>
							   <div class="ne-etrade-product-category"><?php echo $info['s_name']?></div>
							   <!--product list-->
							   <div class="ne-etrade-product-category-list">
									<div class="read-thumb">
                                    <img src="<?php echo base_url().'uploads/e_trade_product/'.getThumbName($info['s_image'],'big')?>" alt=""/>
                                    </div>
									<div class="read-thumb-right">
										<!--<ul class="pro-categorylist">
											<li><a href="javascript:void(0)">Category</a></li>
											<li>I<li>
											<li><a href="javascript:void(0)">Similar Products</a></li>
										</ul>-->
										<br class="clear"/>
										<p class="readmore-attribute1">
											<?php echo $info['s_attribute1']?>
										</p>
                                        <p class="readmore-attribute1">
											<?php echo $info['s_attribute2']?>
										</p>
									</div>
									<ul class="ne-etrade-breadcrumb2">
											<li>Brand: <?php echo $info['s_brand']?></li>
											<li>Product Age: <?php echo $info['s_product_age']?></li>
											<li>Shipping Preference: <?php echo ($info['i_open_to_offer_for_local']==1)?'Local':(($info['i_open_to_offer_for_local']==2)?'International':'Local & International')?></li>
                                            <li><a class="view-shipping-free" href="javascript:void(0);" onclick="showShippingFee('<?php echo $info['id']?>')">View Shipping Fee</a>
											<!--slide view shipping free-->
												<div class="slide-view-shipping-free attribute1" id="shippingfee_<?php echo $info['id']?>">
													<p><strong> Local Shipping Fee :</strong> <?php echo get_price($info['f_local_shipping_cost'])?></p>
													<p><strong> International Shipping Fee :</strong> <?php echo get_price($info['f_international_shipping_cost'])?></p>
												</div>
											<!--slide view shipping free-->
											</li><li>Posted On: <?php echo getShortDate($info['dt_insert_time'],5)?></li>
											<li>Seller From: <?php echo get_user_address_info($info['i_user_id'])?></li>
									</ul>
							  <p class="attribute1">
								<strong> Details</strong>  
								<?php echo $info['s_description']?>
							 </p>
							 <br class="clr"/>
							
							   </div>
							    <!--product list-->
                                
                                 <?php
									if($info['i_user_id']!=intval(decrypt($this->session->userdata('user_id'))))
									{
									?>
										<div class="ne-etrade-quantity-section" id="req_buy_<?php echo $info['id']?>">
										
											  <!--Quantity Section-->
										
											  <div class="ne-etrade-product">
											  <form method="" id="frmReq<?php echo $info['id']?>">
												<input type="hidden" name="owner_user_id" value="<?php echo $info['i_user_id']?>" />
												<input type="hidden" name="rcv_prod_id" value="<?php echo $info['id']?>" />
												 <input type="button" class="swap-change-request-btn-margin yellow-btn " value="Request eFreebie" name="" onclick="sendRequest($(this),'<?php echo $info['id']?>')" style="float:right; width:220px;" />
												<a  class="change-contact-det" href="javascript:void(0);" onclick="showContactSection('<?php echo $info['id']?>');">Change contat detalis</a>
												
												 <br class="clr"/>
												 <div class="changes-contact-section" id="contact-section_<?php echo $info['id']?>">
													<div class="changes-contact-box">
													<label class="subproduct subemail-txt"> Email :</label>
													<input type="text"  value="" name="email" />
													</div>
												   
													 <div class="changes-contact-box">
													<label class="subproduct subemail-txt"> Phone :</label>
													<input type="text"  value="" name="phone" />
													 </div>
												 </div>
												 <br class="clr" />
												 </form>
										 
											 </div>
								
									<!--Quantity Section-->
										</div>
									<?php
									}
									?>
						</div>
                            <!--sub page links -->
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                        </div>
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>



<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<script type="text/javascript">
function showShippingFee(id)
{
	$('#shippingfee_'+id).slideToggle('slow');
}
function showContactSection(id)
{
	$('#contact-section_'+id).slideToggle('slow');
}

function goToSubCategoryList(id)
{
	$('#subcatid').val(id);
	$('#frmSubcat').submit();
}
var ajax_req_feeds = null;
function show_more_record(page) {
	
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/e_freebie/generate_product_listing_AJAX/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				$('#listingContent').append(data.html);
				$('#show_more_feeds_link').attr('page_value', data.cur_page);
				$('#show_more_feeds_link').attr('onclick','');
				$('#show_more_feeds_link').attr('onclick','show_more_record('+data.cur_page+')');
			}
			else {
				$('#listingContent').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Records.</p></div>');
				$('#show_more_feeds_div').remove();
			}
            
            if(data.view_more==false)
            {
                
                $('#listingContent').append('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Records.</p></div>');
                $('#show_more_feeds_div').remove();
            }
		

		}	// end of success function...
	});
}
</script>

<script type="text/javascript">

function sendRequest(obj,id)
{
  $.ajax({
		  "type":'post',
		  "data":$('#frmReq'+id).serialize(),
		  "dataType":'json',
		  "url":'<?php base_url()?>logged/e_freebie/sendrequest',
		  "success": function(data)
					  {
						  if(data.success==false)
						  {
							  showUIMsg(data.msg);
						  }
						  else
						  {
							  $('#contact-section_'+id).slideUp();
							  showUIMsg(data.msg);
						  }
					  }
	  
	  });
}

</script>