<div class="link-div">
    <ul>
        <li><a href="<?php echo base_url()?>efreebie/manage-my-product" <?=($swap_menu ==  1)?'class="current"':''?>><span class="nw-etrade">eFreebies Offered</span></a></li>
        <li><a href="<?php echo base_url()?>efreebie/request-received" <?=($swap_menu == 2)?'class="current"':''?>><span class="nw-etrade">eFreebie Request Received</span></a></li>
        <li><a href="<?php echo base_url()?>efreebie/sent-request" <?=($swap_menu == 3)?'class="current"':''?>><span class="nw-etrade">eFreebie Request Sent</span></a></li>
    </ul>
    <div class="clr"></div>
</div>
