        	<?
			$i=0;
			//pr($gospel_magazine ,1);<?php echo $nomargin
			if($gospel_magazine)
			{
				foreach($gospel_magazine as $val)
				{
					$i++;
					$nomargin	= '';
					if($i==3)
					{
						$nomargin	=	"no-mrgn";
						$i		= 0;
					}
				?>
				
                
                <div class="article-box2 " onClick="window.location.href='christan-project-detail/<?php echo $val['id']?>/<?=my_url($val['s_title'])?>.html'">
                    <h3><?php echo substrws($val['s_title'],80) ?></h3>
                    <p class="grey date"><?php echo $val['dt_posted_on'] ?></p>
                    <p><?php echo htmlspecialchars_decode(substrws($val['s_description'],230)) ?></p>
            	</div>
				<?php
				}
			}
			?>
            
            <!--pagination start -->
            <div class="clr"></div>
            <?php 
			if($page_links)
			{
			?>
            <div class="article-pagination">
            	<ul><?php echo $page_links;?></ul>
            	
            </div>
            <?php
			}
			?>
            <!--pagination end -->
