                     <!--search prayer wall, create prayer request tab start -->
                        <div class="search-create-prayer-container">
                        	
                        	
                            <div class="search-create-form-container" id="create_box">
                            	                              
                                <!--create new prayer request start -->
                                <div class="frm_box search-create-prayer-box">
                                	<!--minimize link start -->
                              		<div class="minimize" title="Minimize">&nbsp;</div>
                          			<!--minimize link end -->
                                    <form id="add_prayer_request" action="<?=base_url().'logged/prayer_wall/add_prayer_request_ajax'?>" onsubmit="return false;" method="post" enctype="multipart/form-data">
                                      <div class="lable01" style=" width:100px;">Request Type:</div>
                                      <div class="field04">
                                             <select name="request_type" id="request_type" style="width:212px;">
                                            	
                                                  <option value="-1">Select</option>
                                                  <option value="1">Emergency</option>
                                                  <option value="2">On Going</option>
                                            </select>
                                          <?php /*?>  <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $("#request_type").msDropDown();
                                                    $("#request_type").hide();
                                                })
                                            </script><?php */?>
                                           <span id="err_request_type" class="error-message"></span>  
                                      </div>
                                      <div class="clr"></div>
                                      <?php /*?><div class="lable01" style=" width:100px;">Subject:</div>
                                      <div class="field04">
                                            <input name="txt_subject" id="txt_subject" type="text" />
                                            <span id="err_subject" class="error-message"></span>  
                                      </div>
                                      <div class="clr"></div><?php */?>
                                      <div class="lable01" style=" width:100px;">Description:</div>
                                      <div class="field03">
                                            <textarea name="ta_desc"  id="ta_desc" style="width:435px; height:80px;" onFocus="if(this.value=='Max 300 Char allowed')this.value='';" onBlur="if(this.value=='')this.value='Max 300 Char allowed';" >Max 300 Char allowed</textarea>
                                            <span id="err_desc" class="error-message"></span>  
                                      </div>
                                      <div class="clr"></div>
                                      
                                      <div class="lable01" style=" width:100px;">&nbsp;</div>
                                      <div class="field03" style="width:0px;">
                                          <input name="" type="button" value="Add Photo"  class="blue-small-button" onclick="return show_dialog('contact_div')"/> <span id="err_image_msg" class="error-message"></span>
                                     
                                          <img id="uploaded_img" src="" alt="" style="display: none;">
                                   		 <p id="photo_name" style=" width:100px;"></p>
                                      </div>
                                       
                                      <div class="clr"></div>
                                      
                                      <div class="lable01" style=" width:100px;">From:</div>
                                      <div class="field03" style="width:460px;">
                                            <div class="lbl01" style=" width:38px;"> Date:</div>
                                            
                                            <div class="lbl01"  style=" width:180px;">
                                                  <input style="width:150px; float:left;"   type="text"  value="" name="date_to1" id="date_to1"  readonly="readonly"/>
                                                  <img src="images/icons/cal.png" alt="" class="right" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                                                  <script type="text/javascript">
                                                    $(document).ready(function(arg) {
                                                        //$.datepicker.setDefaults($.datepicker.regional['']);
                                                        //$("#date_to1").datepicker($.datepicker.regional['en']);
														dateToday = new Date(); 
														$("#date_to1").datepicker({minDate: dateToday});
                        								/*var d = new Date(); 
														d.setDate( d.getDate() + 1 );
														$('#date_to1').datepicker('setDate', d); 
														d = new Date(); d.setDate( d.getDate() + 4 );
														$('#date_end1').datepicker({minDate: d});*/
														
														
                                                    });
                                                </script>
                                                 <span id="err_date_to1" class="error-message"></span>  
                                            </div>
                                            
                                            <div class="lbl01" style=" width:40px;">Time:</div>
                                            <div class="lbl01" style=" width:165px;">
                                                 <input name="txt_from_time" id="txt_from_time" type="text" style="width:155px;" />
                                                 
                                                 <span id="err_from_time" class="error-message"></span>  
                                            </div>
                                           
                                      </div>
                                       <div class="field01" style="font-weight: normal;font-size: 11px;font-style: italic;">(24-hour format ex : HH:MM)</div>
                                      <div class="clr"></div>
                                      <div class="lable01" style=" width:100px;">To:</div>
                                      <div class="field03" style="width:460px;">
                                            <div class="lbl01" style=" width:38px;">Date:</div>
                                            <div class="lbl01"  style=" width:180px;">
                                                    <input style="width:150px; float:left;"  type="text"  value="" name="date_end1" id="date_end1"  readonly="readonly"/>
                                            <img src="images/icons/cal.png" class="right" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                                              <script type="text/javascript">
                                                    $(document).ready(function(arg) {
                                                       // $.datepicker.setDefaults($.datepicker.regional['']);
                                                       // $("#date_end1").datepicker($.datepicker.regional['en']);
                        								//$("#date_end1").datepicker({minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?>, 0, 00)});
														 dateToday = new Date(); 
														$("#date_end1").datepicker({minDate: dateToday});

                                                    });
                                                </script>
                                                <span id="err_date_end1" class="error-message"></span>  
                                            </div>
                                          
                                            <div class="lbl01" style=" width:40px;">Time:</div>
                                            <div class="lbl01" style=" width:165px;">
                                                   <input name="txt_to_time" id="txt_to_time" type="text" style="width:155px;" />
                                                   
                                                   <span id="err_to_time" class="error-message"></span>  
                                            </div>
                                            
                                            
                                            
                                            
                                      </div>
                                       <div class="field01" style="font-weight: normal;font-size: 11px;font-style: italic;">(24-hour format ex : HH:MM)</div>
                                       <div class="clr"></div>
                                     <div class="field01" style="margin-left:578px;">It expires on end date</div>
                          			  <input name="hd_image_name" id="hd_image_name" type="hidden"/>
                                      <input name="posted_from" id="posted_from" type="hidden" value=""/>
                                     
                                      <div class="clr"></div>
                                      <div class="lable01" style=" width:100px;">&nbsp;</div>
                                      <div class="field04">
                                            <input name="" type="submit" value="Post"  class="blue-small-button"/>
                                      </div>
                                      <div class="clr"></div>
                                   </form>
                                </div>
                                <!--create new prayer request start -->
                            </div>
                        </div>
                        <!--search prayer wall, create prayer request tab end -->
                        
<script type="text/javascript">

$(document).ready(function () {


//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
var text = $('#'+textid).val(); 
var textlength = text.length;
if(textlength > limit)
{
$('#'+textid).val(text.substr(0,limit));
return false;
}
else
{

return true;
}
}


$(function(){
$('#ta_desc').keyup(function(){
limitChars('ta_desc', 300, '');
});
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('ta_desc',300, '');


});
</script>


<div class="lightbox contact_div" style="width:500px; ">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Select from prayer wall photos </h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
                 
                  
                  <div id="contact_list" >
                                   
                                      <div class="selectRecipients" style="background-color: #FFF; width:457px; border:none;">
                                       <?php 
										  if(count($prayer_photo)):
											 $count_total = 1;
											 //pr($contact_arr);
											  foreach($prayer_photo as $key=>$val){
												  
												 
												  $IMG = base_url()."uploads/prayer_wall_photos/".getThumbName($val['s_photo_name'],'thumb'); 
												  $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
														
										 ?>
                                         <div class="image-block <?=$CSS?>">
                                             
                                              <input type="radio" name="prayer_img_name" value="<?=$val['s_photo_name']?>" thumb="<?=base_url()."uploads/prayer_wall_photos/".getThumbName($val['s_photo_name'],'mid');?>"/>
                                              <div class="inside">
                                                
                                                  <img alt="Prayer photo" src="<?=$IMG?>"><br/><br/><br/>
                                                  
                                              </div>
                                          </div>
                                        
                                       	 
										 <?php	$count_total++;	
										 			}
										 		endif; 
										 ?>
                                       	   
                                	  </div> 
								</div>
                    <div class="clr"></div>
                    <br />
                    <div style="text-align:right;"><input name="" type="button" value="Done" onclick="javascript:get_selected_photo();" class="blue-small-button blue-small-done-button"/></div>
            </div>
            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>