<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="mid_content">
                  <!-- latest news -->
                 <h2 class="main-title">My Commitments</h2>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!--buttons section start -->
                       <?php include(APPPATH ."views/logged/holy_place/prayer_wall/prayer_wall_menu.phtml");?>
                        <div class="clr"></div>
                        <!--buttons section end -->
                        
                        
                        <div class="search-create-form-container">
                          <!--search form start -->
                          <?php include(APPPATH ."views/logged/holy_place/prayer_wall/prayer_wall_search_panel.phtml");?>
                          <!--search form end -->
                          
                          <!--create new prayer request start -->
                          <?php include(APPPATH ."views/logged/holy_place/prayer_wall/create_prayer_request.phtml");?>
                          <!--create new prayer request start -->
                       
                              
                          </div>
                          
                     
                      	<div class="clr"></div>
                        
                        <!--manage my commitment box start -->
                        <DIV id="commit_content_div"><?=$commitments_ajax_content?></DIV>
                        <!--manage my commitment box end -->
                        
                       
                        
                  </div>
                  <!-- /main container -->
                  <!--pagination start -->
                    <div class="clr"></div> 
                    <?php if($no_of_result  == 0):?>
                                <div class="shade_box_01" style="padding-top:5px;" id="no_tweets"><div  class="shade_norecords" style="width:520px;;"><p class="blue_bold12">No Commitments.</p></div></div>
                            <?php endif;?>	
                           
                            
                            <?php if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="<?=$current_page_1?>" onclick="show_more_records($(this).attr('page_value'))">[view more] </a> </div>
                            <?php endif; ?>
                  <!--pagination end -->
                  
            </div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->


<div class="lightbox delete-prayer" style="width: 400px; left: 296px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Commitments</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">
               Do you really want to delete the commitments on this prayer request?
               </p>
               </div>
               <form action="" method="post" id="delfrm">
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                  <input type="hidden" name="s_type" id="s_type" value="" />
                 <input name="" type="button" value="Yes" class="btn" style="margin-left:105px;" onClick="delete_commitments()"/>
                 <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>



<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_records(page) {
	
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/prayer_wall/my_all_commitments_ajax_pagination/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				
				//alert(data.cur_page+'dfdf');
				$('#commit_content_div').append(data.html);
				$('#show_more_tweets_link').attr('page_value', data.cur_page);
				$('#show_more_tweets_link').attr('onclick','');
				$('#show_more_tweets_link').attr('onclick','show_more_records('+data.cur_page+')');
			}
			else {
				$('#commit_content_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Commitments.</p></div>');
				$('#show_more_div').remove();
			}
			//alert(data.view_more);
            
            if(data.view_more==false)
            {
               
                $('#commit_content_div').append('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Commitments.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}

 
</script>