<ul class="prayer-wall-links">
  <li <?=($page_name == 'prayer-wall-home')?'class="select"':''?>><a href="prayer-wall-home.html" class="prayer-wall">Prayer wall home</a></li>
  <li <?=($page_name == 'manage-my-prayer-request')?'class="select"':''?>><a href="manage-my-prayer-request.html" class="prayer-request">My prayer request</a></li>
  <li <?=($page_name == 'manage-my-commitments')?'class="select"':''?>><a href="manage-my-commitments.html" class="my-commitments">My Commitments</a></li>
</ul>

<ul class="search-create-btn-holder top-gap">
    <li><a href="javascript:void(0);"  onclick="open_search_prayer_wall()" >Search Prayer Wall</a></li>
    <li><a href="javascript:void(0);" onclick="open_create_prayer_wall()">Create new prayer request</a></li>
</ul>
<div class="clr"></div>
