			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="80">Date Posted</th>
                                <th align="left" valign="middle" height="30" width="100">Project Title(ID)</th>
                                <th align="left" valign="middle" height="30" width="120">Posted By</th>
                                <th align="left" valign="middle" height="30" width="200">Request Information</th>
                              </tr>
                           <?php 
						   //pr($info_arr);
						  	 if( count($info_arr) ) :
				   
							 foreach($info_arr as $info) : 
							  	
								$title = html_entity_decode(htmlspecialchars_decode($info['s_project_name']),ENT_QUOTES,'utf-8');
								$desc =  (html_entity_decode(htmlspecialchars_decode($info['s_information']),ENT_QUOTES,'utf-8'));
						  ?>
                              
                              
                              
                              <tr>
                                <td align="left" valign="top"><?=getShortDate($info['dt_created_on'],5)?></td>
                                <td align="left" valign="top"><a href="javascript:void(0);" onclick="return show_project_details(<?php echo $info['i_project_id'] ?> )"><?=$title?></a></td>
                                <td align="left" valign="top"><?=$info['i_user_id']?> < <a href="mailto:<?=get_useremail_by_id($info['i_user_id'])?>"><?=get_useremail_by_id($info['i_user_id'])?> </a>></td>
                                <td align="left" valign="top"><?=$desc?></td>
                                
                              </tr>
                            <?php
                             endforeach;
                             
								 else :	// i.e. no records exists...
							?>
								<tr>
									<td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
								</tr>
							<?php
								 endif;
							?>
 </table>


<div class="paging" >
            <ul><?= $page_links ?></ul>
</div>	
