<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php
include(APPPATH . "views/layouts/nav.phtml");
//pr($qualification_params);
$total_frnds = $qualification_params['total_frnds'];
$total_commitmnts = $qualification_params['total_commitments'];
$total_rings = $qualification_params['total_rings'];
$total_prayer_grps = $qualification_params['total_prayer_grps'];
$six_months_later = $qualification_params['sixMonthsLater'];
$join_date = $qualification_params['join_date'];
//echo $sixMonthsLater_date = date('d-m-Y', $six_months_later);
$current_time = time();
$admin_set_q_params_arr = get_netpal_parameters_set_by_admin();
$min_frnds = $admin_set_q_params_arr['min_friends'];
$min_months = $admin_set_q_params_arr['min_months'];
$min_rings = $admin_set_q_params_arr['min_rings'];
$min_prayer_grps = $admin_set_q_params_arr['min_prayer_grps'];
$min_pr_commtmnts = $admin_set_q_params_arr['min_pr_comttmnts'];
//$diff = abs($current_time - $join_date);
//
//define('DAY', 60 * 60 * 24, true);
//define('MONTH', DAY * 30, true);
//define('YEAR', DAY * 365, true);
//
//echo $years = floor($diff / (YEAR)).'<br>';
//echo $months = floor(($diff - $years * YEAR) / (MONTH)).'<br>';
//echo $days = floor(($diff - $years * YEAR - $months * MONTH ) / (DAY));

$time_start = $join_date;
$time_end = $current_time;
$years = 0;
$months = 0;
while ($time_start < $time_end) {
    $tmp_time = strtotime('+ 1 year', $time_start);
    if ($tmp_time < $time_end) {
        $years++;
        $time_start = $tmp_time;
    } else {
        $tmp_time = strtotime('+ 1 month', $time_start);
        if ($tmp_time < $time_end) {
            $months++;
            $time_start = $tmp_time;
        } else {
            $time_start = $time_end;
        }
    }
}
if ($years > 0) {
    // $age = $years . ' years &amp; ' . $months . ' months';
    $age = (($years * 12) + $months) . ' months';
    $active_months = (($years * 12) + $months);
} else if ($months >= 1) {
    $age = $months . ' months';
    $active_months = $months;
} else if ($months < 1) {
    $months = 0;
    $active_months = 0;
    $age = $months . ' months';
}
?>
<!-- /NAVIGATION SECTION -->
</div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>


<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <div id="top_corner">&nbsp;</div>
        <div id="mid_content">
            <!-- latest news -->
            <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div id="main_container">
                <!-- left container -->
                <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
                <!-- /left container -->
                <!-- mid container -->
                <div id="mid_container">
                    <div class="page_heading">
                        <div class="left"><img src="images/icons/netpal.png" alt="" /> My NetPals </div>
                        <div class="right"></div>
                    </div>

                    <!--sub page links -->
                    <!--           <div class="link-div">
                                 <ul>
                                         <li><a href="prayer-partner-request.php"><span>Prayer Partner Requests</span></a></li>
                                     <li><a href="search-invite-prayer-partner.php"><span>Search  &amp;  Invite Prayer Partners</span></a></li>
                                 </ul>
                                 <div class="clr"></div>
                               </div>
                    -->
                    <!--/sub page links -->

                    <div class="div_content" style=" margin-top:0px;">
                        <!--You are not yet enlisted to Net Pal Zone section start -->
                        <div class="shade_box_blue" style="padding-top:5px;"> 
                            <div class="txt_content">
                                You are not yet opted to NetPal Zone. To opt yourself please click on the button below 
                                <a style="float:left" href="javascript:void(0);" class="enlist-prayer-partner">Opt as NetPal</a>
                                <a  style="float:left; margin: 23px 0 0 6px;" href="javascript:void(0);" class="view-criteria" style=""><img src="<?= base_url(); ?>images/sign-icon.png" height="18" width="17"></a>
                                <div class="clr"></div>
                            </div>
                        </div>
                        <!--You are not yet enlisted to Net Pal Zone section end -->
                    </div>

                </div>
                <!-- /mid container -->
                <!-- right container -->
                <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
                <!-- /right container -->
            </div>
            <!-- /main container -->
            <div class="clr"></div>
        </div>
        <div id="bot_corner">&nbsp;</div>
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>
<!-- /FOOTER SECTION -->
<!-- /lightbox SECTION -->


<div class="lightbox enlist-as-net-pal" style="width:480px;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top">
        <div>&nbsp;</div>
    </div>
    <div class="mid">
        <div class="heading">
            <div class="left">
                <h4>Confirmation Message</h4>
            </div>
        </div>
        <p class="bold-text">Are you sure you want to opt yourself as NetPal?</p>

        <form enctype="multipart/form-data" method="post" action="">
            <input class="btn" type="button" style="margin-left:146px;" value="Yes" name="" onclick="enlist_net_pal_()">
            <input class="btn" type="button" onclick="hide_dialog()" value="No" name="">
        </form>
    </div>
    <div class="bot">
        <div>&nbsp;</div>
    </div>
</div>

<div class="lightbox enlist_pr_prtnr" style="width:415px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <strong>You are not eligible yet to enlist yourself as NetPal.</strong><br><br>
        <label class="<?php
        if ($current_time < $six_months_later) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Member For : <?= $age ?> <?php if ($current_time < $six_months_later) echo "(min.req $min_months months)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_frnds < $min_frnds) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total friends : <?= $total_frnds ?> <?php if ($total_frnds < $min_frnds) echo "(min.req $min_frnds)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_rings < $min_rings) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total rings : <?= $total_rings ?><?php if ($total_rings < $min_rings) echo "(min.req $min_rings)" ?> 
        </label><br><br>
        <label class="<?php
        if ($total_prayer_grps < $min_prayer_grps) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total prayer groups : <?= $total_prayer_grps ?> <?php if ($total_prayer_grps < $min_prayer_grps) echo "(min.req $min_prayer_grps)" ?>
        </label><br><br>
        <label class="<?php
        if ($total_commitmnts < $min_pr_commtmnts) {
            echo "color-red";
        } else {
            echo "color-green";
        }
        ?>">Your total prayer commitments : <?= $total_commitmnts ?>&nbsp;<?php if ($total_commitmnts < $min_pr_commtmnts) echo "(min.req $min_pr_commtmnts)" ?>
        </label><br><br>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>
<div class="lightbox view_q_criteria" style="width:415px;;">
    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
    <div class="top"><div>&nbsp;</div></div>
    <div class="mid">
        <label class="">Minimum membership time :&nbsp; <?php echo $min_months .' '. 'months'; ?></label><br><br>
        <label class="">Minimum friends :&nbsp; <?php echo $min_frnds; ?></label><br><br>
        <label class="">Minimum rings :&nbsp; <?php echo $min_rings; ?></label><br><br>
        <label class="">Minimum prayer groups :&nbsp; <?php echo $min_prayer_grps; ?></label><br><br>
        <label class="">Minimum prayer commitments :&nbsp; <?php echo $min_pr_commtmnts; ?></label><br><br>
    </div>
    <div class="bot"><div>&nbsp;</div></div>
</div>


<script type="text/javascript">

    var ticker_holder = $('.bargaining').get(0);
    var ticker_text = $('.ticker').get(0);
    var ticker_pos = ticker_text.parentNode.offsetWidth;

    var ticker_data = $(ticker_holder).html();
    $(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');

    $('#sub-nav').hover
            (
                    function() {
                        $('marquee', this).get(0).stop();
                    },
                    function() {
                        $('marquee', this).get(0).start();
                    }
            );
    $(function() {

        $('.enlist-prayer-partner').click(function() {
            var total_frnds = <?= $total_frnds ?>;
            var total_rings = <?= $total_rings ?>;
            var total_prayer_grps = <?= $total_prayer_grps ?>;
            var total_commitmnts = <?= $total_commitmnts ?>;
            var six_month_later = <?= $six_months_later ?>;
            var current_time = <?= $current_time ?>;
            var min_frnds = <?= $min_frnds ?>;
            var min_rings = <?= $min_rings ?>;
            var min_prayer_grps = <?= $min_prayer_grps ?>;
            var min_commitmnts = <?= $min_pr_commtmnts ?>;
            var min_months = <?= $min_months ?>;
            var active_duration = <?= $active_months ?>;
            if ((total_frnds >= min_frnds) && (total_rings >= min_rings) && (total_prayer_grps >= min_prayer_grps) && (total_commitmnts >= min_commitmnts) && (active_duration >= min_months))
            {
                return show_dialog('enlist-as-net-pal');
            } else {
                show_dialog('enlist_pr_prtnr');
            }

        });
        $('.view-criteria').click(function() {
            show_dialog('view_q_criteria');
        });
    });
</script>

<style type="text/css">
    .color-red{ background-color: #ff3333; color: #fff; padding: 2px 4px;}
    .color-green{ background-color: green; color: #fff; padding: 2px 4px;}
    .color-blue{ background-color: burlywood; color: #fff; padding: 2px 4px;}
</style>
