<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
.nw-chat-lnk{ color:#014882 !important; font-size:13px !important;
	cursor:pointer; }
</style>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->                         
                        <div id="mid_container">
                              
                              <!--sub page links -->
                              <div class="link-div">
                                  <ul>
                                     <li><a href="my-net-pals.html" class="<?php echo ($page_name=='my-net-pals')?'current':'';?>"><span>My NetPals</span></a> </li>
                                    <li><span><img src="images/greynew-pipe.png" width="11" height="32"/></span></li>
                                    <li><a href="net-pal-request.html" class="<?php echo ($page_name=='net-pal-request')?'current':'';?>"><span>NetPals Request</span></a> </li>
                                    <li><span><img src="images/greynew-pipe.png" width="11" height="32"/></span></li>
                                    <li><a href="search-invite-net-pals.html" class="<?php echo ($page_name=='search-invite-net-pals')?'current':'';?>"><span>Search  &amp;  Invite NetPals</span></a> </li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                              <!--/sub page links -->
                              
                              
                              <div class="div_content" style=" margin-top:0px;">
                              
                              
                              
                                    <!--You are not yet enlisted to Net Pal Zone section start -->
                                    <div class="shade_box_blue" style="padding-top:5px;"> 
                                         <div class="txt_content">
                                             You are opted to be in NetPal Zone. To quit yourself from netpal please click on the button below 
                                             <a href="javascript:void(0);" onclick="return show_dialog('opt-out-as-net-pal')" class="enlist-prayer-partner">Quit from NetPal</a>
                                         </div>
                                     </div>
                                     <!--You are not yet enlisted to Net Pal Zone section end -->
                                     
                                     
                              </div>
                              
                              
                              
                                    
                             <?php /*?> <DIV id="netpal_request_receive">
                                   
                                 <?= $content2;?>
                              </DIV><?php */?>
              
                              
                              
                              
                              
                              <div class="page_heading">
                                    <div class="left"><img src="images/icons/netpal.png" alt="" /> My NetPals </div>
                                    <?php /*?><div class="right"><a  href="search-invite-net-pals.html" class="btn_link" style="width:155px;"><span><img src="images/icons/search.png" alt="" /> Search New NetPal</span></a></div><?php */?>
                              </div>
                              
                              <div class="arrow_btm"></div>
                              <div class="section01" style="margin-bottom:1px;">
                                    <div class="txt_content" style="padding:5px 0px;">
                                          <div class="heading02" style="margin-bottom:10px;">
                                          <img src="images/icons/search.png" alt="" width="15" height="16" />Search My NetPal List </div>
                                            <div class="clr"></div>
                                            
                                            
                                       <form id="netpal_form" action="" method="post" onsubmit="return false;">     
                                          <input name="txt_name" type="text"  value="" style="width:223px; height:16px; margin-right:5px;" class="left"/>
                                           <select name="show" id="show" style="width:160px;">
                                              <option value="-1">Show All</option>   
                                              <option value="1">Show Online</option>
                                              <option value="4">Show Offline</option>
                                        </select>
                     
                                            <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    //$("#show").msDropDown();
                                                    //$("#show").hide();
                                                })
                                            </script>
                                           <input type="hidden" name="search_basic" id="search_basic" value="Y" />
                                          <input name="" type="submit" value="Search" class="yellow-btn my-frd-search" />
                                        </form>
                                          <div class="clr"></div>
                                    </div>
                              </div>
                              
                              <DIV id="net_pals">
                                <?php echo $result_arr;?>
                              </DIV>
                              
                             
                        </div>                     
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /lightbox SECTION -->


<div class="lightbox opt-out-as-net-pal" style="width:245px; height:200px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4>Confirmation Message</h4>
                  </div>
            </div>
           <p class="bold-text">Are you sure you want to opt out yourself from NetPal Zone?</p>
           
           <form enctype="multipart/form-data" method="post" action="" style="height:28px;">
            <input class="popup-yes" type="button"  value="Yes" name="" onclick="opt_out_net_pal()" />
            <input class="popup-no" type="button" onclick="hide_dialog()" value="No" name="" />
           </form>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<!-- confirm delete netpal popup-->
<div class="lightbox delete-page-popup" style="width: 245px;; left: 296px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete NetPal</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete NetPal?</p>
               </div>
               <form action="" method="post" enctype="multipart/form-data" >
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                 <input name="" type="button" value="Yes" class="popup-yes" onClick="remove_netpal_()"/>
                    <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!-- end of delete pop up -->




<script type="text/javascript">
   

</script>

<script type="text/javascript">
$(document).ready(function(arg) {
 
 $('#netpal_form').submit(function(){ 
      
      var datatosend=$("#netpal_form").serialize();
      
           showBusyScreen();
       //alert(datatosend);
       $.ajax({
          type: "POST",
          url: base_url+"logged/my_net_pals/netpals_ajax_pagination",
          data: datatosend,
          success: function(data){
           $('#net_pals').html(data);
              hideBusyScreen(); 
          }
        });  
        
      
    });
 
 });
 

</script>