<?php include(APPPATH."views/layouts/logged_header.phtml");?>   
<!-- NAVIGATION SECTION -->
<?php include(APPPATH."views/layouts/nav.phtml");?>    
<!-- /NAVIGATION SECTION -->

<div class="clr"></div>      

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH ."views/layouts/latest_news.phtml");?> 
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                         <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <div id="mid_container">
                        
                        	 <!--sub page links -->
                              <div class="link-div">
                                  <ul>
                                   	
                                    <li><a href="my-net-pals.html" class="<?php echo ($page_name=='my-net-pals')?'current':'';?>"><span>My NetPals</span></a> </li>
                                    <li><span><img src="images/greynew-pipe.png"/></span></li>
                                    <li><a href="net-pal-request.html" class="<?php echo ($page_name=='net-pal-request')?'current':'';?>"><span>NetPals Request</span></a> </li>
                                    <li><span><img src="images/greynew-pipe.png"/></span></li>
                                    <li><a href="search-invite-net-pals.html" class="<?php echo ($page_name=='search-invite-net-pals')?'current':'';?>"><span>Search  &amp;  Invite NetPals</span></a> </li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                              <!--/sub page links -->
                        
                              <!--<div class="page_heading">
                                    <div class="left"><img src="images/icons/netpal.png" alt="" /> NetPal Requests </div>
                                      <div class="clr"></div>
                              </div>
                              <div class="arrow_btm"></div>-->
                              
                              <div class="page_heading_01">
                                          <div class="left"><img src="images/icons/netpal_rqust.png" alt="" />  NetPal Requests Sent </div>
                                            <div class="clr"></div>
                              </div>
                                <div class="arrow_btm"></div>
                                                  
                                  <DIV id="netpal_request_sent">
                                     
                                     <?= $content1;?>
                                  </DIV>
                              
                              
                              <div style="padding-top:10px;">
                                    <div class="page_heading_01">
                                          <div class="left"><img src="images/icons/netpal_rcev.png" alt="" />  NetPal Requests Received</div>
                                            <div class="clr"></div>
                                    </div>
                                    <div class="arrow_btm"></div>
                                    
                                    
                                      <DIV id="netpal_request_receive">
                                           
                                         <?= $content2;?>
                                      </DIV>
              
              
                              </div> 
                        </div>
                        
                        <!-- /left container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>   
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div> 
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>     
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->
<script type="text/javascript">
   
  /*  var ticker_holder = $('.bargaining').get(0);
    var ticker_text = $('.ticker').get(0);
    var ticker_pos = ticker_text.parentNode.offsetWidth;
    
    var ticker_data = $(ticker_holder).html();
    $(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');
    
    $('#sub-nav').hover
    (
    function() { $('marquee', this).get(0).stop();  },
    function() { $('marquee', this).get(0).start(); }
    ); 
*/
</script>