<div class="pro-float">
                    <div class="profile-frd">
                        <h4>Videos</h4>
                        <a class="pro-view-all" href="<?=base_url()?>public-profile/<?=$profile_id?>/video-album.html">View all</a>
                    </div>
                    <div class="pro-container">
                        <div class="pro-video-section">
                        	<?php
							$arr_video_ids	= get_videoid_with_privacy(intval(decrypt($this->session->userdata('user_id'))), $i_profile_id);
							//pr($public_profile['video_res']);
							$privacy		= get_privacy('video',$profile_id);
                             if(count($public_profile['video_res']) )
                             {
                                $counter=0;
                                foreach($public_profile['video_res'] as $videos) :
                                    $counter++;
                                    $img = base_url().'uploads/user_videos/'.getThumbName($videos['s_video_image'],'bigthumb');
									$comments_array = $videos['comments_arr'];
									if($privacy == 'Private')
									{
										if(in_array($videos['id'],$arr_video_ids))
										{
											?>
											<div class="friend-pro-video-sec">
												<a href="<?=base_url()?>public-profile-video/<?=$profile_id?>/album/<?=$videos['id']?>/video-details.html">
													<img src="<?=$img?>" alt="video" width="144" height="80" class="video-thumbnail" />
													<br class="clr"/>
													<span><?php echo substr($videos['s_title'],0,18)?></span>
												</a>
											</div>
											  <?php
										}
									}
									else
									{
										?>
											<div class="friend-pro-video-sec">
												<a href="<?=base_url()?>public-profile-video/<?=$profile_id?>/album/<?=$videos['id']?>/video-details.html">
													<img src="<?=$img?>" alt="video" width="144" height="80" class="video-thumbnail" />
													<br class="clr"/>
													<span><?php echo substr($videos['s_title'],0,18)?></span>
												</a>
											</div>
										<?php
									}
                                endforeach;
                            }
							else{
								  echo '<div class="shade_box_blue no_comments" style="padding-top:5px; "><div  class="shade_norecords" style="width:235px;"><p class="blue_bold12">No Video.</p></div></div>';
							  }
                        ?>
                            
                        </div>
                    </div>
</div>

