<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="mid_content">
                   <!-- latest news -->
                  <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
						
						<!-- mid container mid_thumb-->
                        <div id="mid_container">
						<div class="page_heading">
                                    <div class="left"><img alt="" src="images/tithe-time.png" /> Tithe Your Time through Prayer </div>
                                    <div class="right"><input type="submit" style=" background:none repeat scroll 0 0 #013D62;" value="Back" class="sml_btn" onclick="window.location='giving.html'"></div>
                        </div>
                        
						<DIV id="tithe_content"><?=$search_content?></DIV>	
						
                        <?php if($no_of_result == 0): ?>
                            <div class="view_more" style="text-align:center;padding-top: 20px;height: 30px;" id="no_project" >No results. Please change time selection to view projects.</div>
                         <?php endif; ?>  
                        
                        
                        <?php if($no_of_result > $pagination_per_page): ?>
                     
                             <div class="custom_show view_more" id="show_more_div" style="width:475px;"><a href="javascript:void(0);" id="show_more_records_link" page_value="<?=$current_page_1?>" onclick="show_more_records($(this).attr('page_value'))">[view more] </a> </div>
                        <?php endif; ?>  
						 <input type="hidden" id="post_type" name="post_type" value="<?=$search_typ?>" />
						</div>
						<!-- mid container -->
						
						<!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                        
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->

<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_records(page) {
	
	var post_type = $('#post_type').val();
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/build_the_kingdom/search_all_prayer_request_ajax_pagination/'+post_type+'/'+page,
		dataType: 'json',

		success: function (data, status) {
			$('#show_more_div').remove();
			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				
				$('#tithe_content').append(data.html);
				$('#show_more_records_link').attr('page_value', data.cur_page);
				$('#show_more_records_link').attr('onclick','');
				$('#show_more_records_link').attr('onclick','show_more_records('+data.cur_page+')');
			}
			else {
				$('#mid_container').append('<div class="view_more " style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more results.</p></div>');
				$('#show_more_div').remove();
			}
			
			if(data.view_more==true)
			{
				cur_page = data.cur_page;
				$('.shade_box_shade').append('<div class="custom_show view_more" id="show_more_div" style="width:475px;"><a href="javascript:void(0);" id="show_more_records_link" page_value="'+cur_page+'" onclick="show_more_records('+cur_page+')">[view more] </a> </div>');
				
			}
            
            if(data.view_more==false)
            {
                
                $('#mid_container').append('<div class="view_more " style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No more results.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}

</script>