<?php 
//pr($ringdata);
		if ($ringdata) {
		foreach($ringdata As $church_members) { 
		//pr($church_members);
		
		?>
        	<li>
            	<figure><img src="<?= get_profile_image_of_user('thumb',$church_members->s_profile_photo,$church_members->e_gender)?>" alt="<?php echo $church_members->member_name; ?>"></figure>
                <div class="right-text"><h4><a href="<?=base_url() . "profile/" . $church_members->member_id . "/" . my_url($church_members->member_name) . ".html"?>"><?=$church_members->member_name; ?></a></h4>
                <p class="designetion"><?=my_substr($church_members->s_about_me,35); ?></p>
            </li>
			<?php }
			} else { 
			?>
			<h4 style="text-align:center;"> No records found. </h4>
			<?php } ?>
   <input type="hidden" id="current_page" name="current_page" value="<?= $current_page_1 ?>"  />  
 