<?php 
pr($ringdata);
		if ($ringdata) {
		foreach($ringdata As $church_members) { 
		//pr($church_members);
		
		?>
        	<li>
            	<figure><img src="<?= get_profile_image(($church_members->member_id), 'thumb') ?>" alt="<?php echo $church_members->member_name; ?>"></figure>
                <div class="right-text"><h4><a href="<?=get_public_profile_url($church_members->member_id, $church_members->member_name)?>"><?=$church_members->member_name; ?></a></h4>
                <p class="designetion"><?=my_substr($church_members->s_about_me,35); ?></p>
                <!--<p class="update-time">Added by Joe about 4 months ago</p>--></div>
            </li>
			<?php }
			} else { 
			?>
			<h4 style="text-align:center;"> No records found. </h4>
			<?php } ?>
   <input type="hidden" id="current_page" name="current_page" value="<?= $current_page_1 ?>"  />  
 