 <table width="100%" border="0" cellpadding="0" cellpadding="0">
 <thead>
      
</thead>
	  <?php 
 //echo 'sdfsdfssdfsdfdfs'; 
	  //pr($church_list);

		if(!empty($grpdata)){
//echo 'IFIFIIFIF';
			foreach($grpdata as $church)

			{

	  ?>

      <tr>

      <td><?php if($church_admin){?><img alt="" src="images/crown.png" style="margin-right:5px;"><?php }else {?><img alt="" src="images/man-24-16.png"><?}?><a href="<?=base_url()?>church-prayer-group/<?=$church->id?>"><?=$church->s_group_name?></a><span class="count-02"><?=$church->members?></span><?php if($church_admin){ ?><?php }else { ?><a onclick="show_dialog('Leave-group'); $('#i_lev_id').val('<?=$church->i_prayer_group_id?>');" style="float:right; display: none;" title="Leave Group" href="javascript:void(0)">Leave group</a><?php } ?>

	  <p><?//getDenominationNameById($church->i_denomination_id) ?>  <small><?php if($church_admin){?>Created on- <?php echo getShortDate($church->dt_created_on,5);}else {?>Joined on- <?php echo getShortDate($church->dt_joined_on,5);}?></small>  
      <span class="already-member"><?php if($church->is_member == 1){ ?><img alt="" src="images/icons/accept.png"><?php echo 'Already Member';  }else{?></span> 
      <a href="javascript:void(0);" class="searchjoin-btn" onClick="sendGrpJoinReq('<?=$church->id?>')" id="invite_text_<?=$church->id?>">
	  
	  <?php 
	  if($church->is_member == 'pending'){
	  ?>
      <img src="images/icons/restore.png">
      <?php } else{ ?>
      <img src="images/icons/send.png" width="16" height="13">
       <?php }?>
     
          
	  <?php echo ($church->is_member == 'pending')?'Resend Join Request':'Send Join Request';?>
      
      
      
      
      </a>
      <a href="javascript:void(0);" class="searchjoin-btn" onClick="sendGrpJoinReq('<?=$church->id?>')" id="invite_text_new<?=$church->id?>" style="display: none;">
	  
	  <?php 
	  if($church->is_member == 'pending'){
	  ?>
      <img src="images/icons/restore.png">
      <?php } else{ ?>
      <img src="images/icons/restore.png">
       <?php }?>
     
          
	  <?php echo ($church->is_member == 'pending')?'Resend Join Request':'Resend Join Request';?>
      
      
      
      
      </a>
      <? }?>
 </p>

	  

	  

</a>

	  </td>

      </tr>

	  <?php

			}

		}else
		{	
		?>

		<tr>

      <td><p>No Prayer Groups Found.</p></td>

      </tr>

		<?

		}		

	  ?>



</table>



<div class="lightbox delete-group delete-post" style="width:450px;">

    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog();

            $('#i_del_id').val('');"><img src="<?= base_url() ?>images/close.png" alt="" width="24" height="24"/></a></div>

    <div class="top"><div>&nbsp;</div></div>

    <div class="mid">

        <div class="heading" style="margin-bottom:0px;">

            <div class="left">

                <h4>Delete Prayer Group</h4>

            </div>

        </div>

        <div class="shade_box_white" style="padding:8px 0px;">

            <div style="padding-bottom:10px;">

                <p class="center-text" style="line-height:23px; color:#494949; font-size:16px;">Do you really want to delete these group?</p>

            </div>

            <form action="" method="post" enctype="multipart/form-data">

                <input type="hidden" name="i_del_id" id="i_del_id" value="" />

                <input name="" type="button" value="Yes" class="post-btn"  onClick="deleteGroup()"/>

                <input name="" type="button" value="No" class="cancel-btn" onclick="hide_dialog();

                        $('#i_del_id').val('');"/>

            </form>   

            <div class="clr"></div>

        </div>



    </div>

    <div class="bot"><div>&nbsp;</div></div>

</div>



<div class="lightbox Leave-group delete-post" style="width:245px;">

    <div class="close"><a href="javascript:void(0)" onclick="hide_dialog();

            $('#i_lev_id').val('');"><img src="<?= base_url() ?>images/close.png" alt="" width="24" height="24"/></a></div>

    <div class="top"><div>&nbsp;</div></div>

    <div class="mid">

        <div class="heading" style="margin-bottom:0px;">

            <div class="left">

                <h4>Leave Prayer Group</h4>

            </div>

        </div>

        <div class="shade_box_white" style="padding:8px 0px;">

            <div style="padding-bottom:10px;">

                <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to leave these group?</p>

            </div>

            <form action="" method="post" enctype="multipart/form-data">

                <input type="hidden" name="i_lev_id" id="i_lev_id" value="" />

                <input name="" type="button" value="Yes" class="popup-yes"  onClick="leaveGroup()"/>

                <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog();

                        $('#i_lev_id').val('');"/>

            </form>   

            <div class="clr"></div>

        </div>



    </div>

    <div class="bot"><div>&nbsp;</div></div>

</div>

