<?php
	include(APPPATH ."views/layouts/church_admin_header.phtml");
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>

<div class="container-body">
    <div class="round-con">
        <?php
         
         $church_number =  get_church_ring_number_by_id($_SESSION['logged_church_id']);
        // echo $_SESSION['logged_church_id'];
        ?>
<!--        <div class="right-round right-gray"><p><a href="<?= base_url() ?>church_member" style="text-decoration: none; color: #ffffff;">Community members</a> <br /><span><?=get_member_count_by_church_id($church_arr[0]->id)?></span></p></div>
        <div class="right-round right-gray"><p><a href="<?= base_url() ?>church-ring-list" style="text-decoration: none; color: #ffffff;">Rings </a><br /><span><?= $church_number ?></span></p></div>
        <div class="right-round right-gray"><p><a href="<?= base_url()."".$church_arr[0]->id ?>/church-prayer-group.html" style="text-decoration: none; color: #ffffff;">Prayer Groups</a>  <br /><span><?=get_prayer_group_count_by_church($church_arr[0]->id)?></span></p></div>-->
        
        <div>
  <div class="left-dashboard">
    <div class="group-block">
      <h3 class="member-heading">Community</h3>
      <ul>
        <li><a href="<?= base_url() ?>church_member">Members</a> <span>(<?=get_member_count_by_church_id($church_arr[0]->id)?>)</span></li>
<!--        <li><a href="javascript:void(0);">Online Users</a> <span>(11)</span></li>-->
      </ul>
    </div>
       <div class="group-block">
      <h3 class="ring-heading">Ring</h3>
      <ul>
        <li><a href="<?= base_url() ?>church-ring-list">Total Ring</a> <span>(<?= get_church_ring_total_by_church_ID($_SESSION['logged_church_id']) ?>)</span></li>
        <li><a href="javascript:void(0);">Total Member</a> <span>(<?= get_church_ring_member_total_by_church_ID($_SESSION['logged_church_id']) ?>)</span></li>
        <li><a href="javascript:void(0);">Total Post</a> <span>(<?= get_church_ring_post_total_by_church_ID($_SESSION['logged_church_id']) ?>)</span></li>
      </ul>
    </div>
       <div class="group-block">
      <h3 class="groups-heading">Prayer Groups</h3>
      <ul>
        <li><a href="<?= base_url().$church_arr[0]->id ?>/church-prayer-group.html">Total Prayer Groups</a> <span>(<?=get_prayer_group_count_by_church($church_arr[0]->id)?>)</span></li>
        <li><a href="javascript:void(0);">Total Member</a> <span>(<?= get_prayer_group_member_count_by_church($_SESSION['logged_church_id']) ?>)</span></li>
        <li><a href="javascript:void(0);">Total Post</a> <span>(<?=get_prayer_group_post_count_by_church($_SESSION['logged_church_id']) ?>)</span></li>
      </ul>
    </div>
  </div>
  <div class="right-dashboard">
    <div class="quick-link-panels">
      <h3>Quick Links</h3>
      <ul>
        <li><a href="<?= base_url().$_SESSION['logged_church_id'].'/church-wall' ?>">Church wall</a></li>
        <li><a href="<?= base_url().'church_setting' ?>">Manage site</a></li>
        <li><a href="<?= base_url().'church_member' ?>">Members</a></li>
        <li><a href="<?= base_url().'church-ring-list' ?>">Rings</a></li>
        <li><a href="<?= base_url().$_SESSION['logged_church_id'].'/church-prayer-group' ?>">Prayer Groups</a></li>
<!--        <li><a href="javascript:void(0);">Chat rooms</a></li>-->
      </ul>
    </div>
  </div>
  <div class="clr"></div>
</div>

    </div>
    </div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


