<!-- header -->
<?php
	include(APPPATH ."views/layouts/church_logged_header.phtml");
	//pr($church_arr[0]);
	//pr($posted);
?>

<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>

<div class="container">
    <div class="main-page about-page">
	<div class="page-heading page-heading-clr"><h3><?php echo get_unformatted_string_edit($church_arr[0]->s_title); ?></h3>	<div class="right">
	<!--a href="<?=base_url().'logged/church_wall_about/edit/'.$church_arr[0]->id?>">EDIT</a>-->
                <?php 
                if($_SESSION['charch_super_admin'] == 'yes' || $_SESSION['subadmin_role'] == 2){
                ?>
	<input type="button" class="btn" onclick="go_to_edit();" value="EDIT">
                <?php } ?>
	</div></div>
	<p><?php echo get_unformatted_string_edit($church_arr[0]->s_contents); ?></p>
	<div class="clr"></div>
	<div class="clr"></div>

	<div class="clr"></div>
	</div>
</div>

<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->
<script type="text/javascript">
function go_to_edit()
{
	window.location.href="<?=base_url().'logged/church_wall_about/edit/'.$church_arr[0]->id?>";
}
</script>