<?php

    include(APPPATH ."views/layouts/church_admin_header.phtml");

?>

<!-- CONTENT SECTION -->

<?php //pr($church_arr); ?>



<div class="container-body">

   <?php

    //include(APPPATH ."views/layouts/church_admin_left.phtml");

?>

    <div class="right-panel">
        <!--right-panel equal-height--->

    <h2>Users</h2>

    <!--<div class="vector-search">

        <label>Search :</label>

        <input type="text" >

    </div>-->

   


    <div class="right-box">

		<div align="right"><input type="button" value="Send Invitation" id="sent_invitation_user" class="btn" style="font-weight:normal;"></div><br />
        <div class="church-time-table" style="margin-right:0;" id="table_content">
                        <?= $result_content ?>

        



        </div>

        

     



    </div>

    

     

    

    </div>

    

    </div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>

<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/church_footer.phtml");?>

<!-- /FOOTER SECTION -->
<script type="text/javascript">
$(document).ready(function() {
$( "#sent_invitation_user" ).click(function() {
$( "#sent_invitation_user_btn" ).trigger( "click" );

var options = { 

        beforeSubmit:  showLoad,  // pre-submit callback 

        success:       validateFrm // post-submit callback 

    }; 

 

    // bind to the form's submit event 

    $('#sent_invitation_user_frm').submit(function() {

        $(this).ajaxSubmit(options);
		alert('Hi......');
        return false;

        

    });


});
});

function showLoad()

{

 // $('#photo_album_btn').attr('disabled','disabled');

    showUIMsg();

	}


// validate ajax-submission...

function validateFrm(data)

{

   alert( data);

    var data = JSON.parse(data);


    if(data.success==false) 

    {
	
	showUIMsg(data.msg);
	location.reload();

    }

    else {

        

        showUIMsg(data.msg);  
		location.reload();
        }

    
	
}	

</script>
