<?php

    include(APPPATH ."views/layouts/church_admin_header.phtml");

?>

<!-- CONTENT SECTION -->

<?php //pr($church_arr); ?>



<div class="container-body">

   <?php

    //include(APPPATH ."views/layouts/church_admin_left.phtml");

?>

    <div class="right-panel">
        <!--right-panel equal-height--->

    <h2>Add Members</h2>

    <!--<div class="vector-search">

        <label>Search :</label>

        <input type="text" >

    </div>-->

    <div class="right-box">
	

        <form class="add-newmember" name="importfrm" id="importfrm" method="post">
<div class="clr"></div>
        <label class="lable01">Name1 :</label>
        <div class="field03"><input type="text" name="name" id="name" value="">
		<span id="name_err" style="display:none;" class="error-message">Please enter name</span></div>
        <div class="clr"></div>
		<label class="lable01">Email1 :</label>
        <div class="field03"><input type="email" name="email" id="email" value="">
		<span id="email_err" style="display:none;" class="error-message">Please enter email</span></div>
		 <div class="clr"></div>
		
		<label class="lable01">Name2 :</label>
         <div class="field03"><input type="text" name="name1" id="name1" value="">
		<span id="name_err_1" style="display:none;" class="error-message">Please enter name</span></div>
        <div class="clr"></div>
        
		<label class="lable01">Email2 :</label>
        <div class="field03"> <input type="email" name="email1" id="email1" value="">
		<span id="email_err_1" style="display:none;" class="error-message">Please enter email</span></div>
		<div class="clr"></div>
        
		<label class="lable01">Name3 :</label>
         <div class="field03"><input type="text" name="name2" id="name2" value="">
		<span id="name_err_2" style="display:none;" class="error-message">Please enter name</span></div>
        
        <div class="clr"></div>
        
        
		<label class="lable01">Email3 :</label>
         <div class="field03"><input type="email" name="email2" id="email2" value="">
		<span id="email_err_2" style="display:none;" class="error-message">Please enter email</span></div>
        <div class="clr"></div>
		
		
		<label class="lable01">Name4 :</label>
        <div class="field03"> <input type="text" name="name3" id="name3" value="">
		<span id="name_err_3" style="display:none;" class="error-message">Please enter name</span></div>
        <div class="clr"></div>
        
		<label class="lable01"l>Email4 :</label>
        <div class="field03"> <input type="email" name="email3" id="email3" value="">
		<span id="email_err_3" style="display:none;" class="error-message">Please enter email</span></div>
		<div class="clr"></div>
		
		<label class="lable01">Name5 :</label>
         <div class="field03"><input type="text" name="name4" id="name4" value="">
		<span id="name_err_4" style="display:none;" class="error-message">Please enter name</span></div>
        <div class="clr"></div>
		<label class="lable01">Email5 :</label>
        <div class="field03"> <input type="email" name="email4" id="email4" value="">
		<span id="email_err_4" style="display:none;" class="error-message">Please enter email</span>
        </div>
        <div class="clr"></div>
		<label class="lable01">&nbsp;</label>
		
        <div class="field03"><input type="button" value="Submit" class="post-btn" onclick="member_form_validation ();" style="float:left; font-weight:normal;"></div>
<div class="clr"></div>
        </form>
		
        </div>

    </div>

    

     

    

    </div>

    

    </div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>
<script type="text/javascript">
function member_form_validation () {
var e_flag=0;
var val_arr=[];
if((jQuery('#name').val() != '' && jQuery('#email').val() == '') || (jQuery('#name').val() == '' && jQuery('#email').val() != ''))
{
    
	e_flag=1;
	$('#name_err').css("display","block");
	$('#email_err').css("display","block");
    
}
else if(jQuery('#name').val() != '' && jQuery('#email').val() != '')
{
    var email = jQuery('#email').val();
    var check_mail = email.match(/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/);
    
    //alert(email);
     if( check_mail == null ){
         e_flag=1;
         $('#email_err').css("display","block").html('Invalid email id ');
     }else if(check_mail == null && jQuery('#name').val() == '' ){
         e_flag=1;
	$('#email_err').css("display","block").html('Invalid email id ');
	$('#name_err').css("display","block");
     }else if(email.match(/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/) == null && jQuery('#name').val() != '' ){
         e_flag=1;
	$('#email_err').css("display","block").html('Invalid email id ');  
     }
     else{
    
     
	val_arr.push(jQuery('#name').val()+'_'+jQuery('#email').val());
    }
	//console.log(val_arr);
}
if((jQuery('#name1').val() != '' && jQuery('#email1').val() == '') || (jQuery('#name1').val() == '' && jQuery('#email1').val() != '')) {
	e_flag=1;
	$('#name_err_1').css("display","block");
	$('#email_err_1').css("display","block");
}
else if (jQuery('#name1').val() != '' && jQuery('#email1').val() != '')
{

	val_arr.push(jQuery('#name1').val()+'_'+jQuery('#email1').val());
	//console.log(val_arr);
}
if((jQuery('#name2').val() != '' && jQuery('#email2').val() == '') || (jQuery('#name2').val() == '' && jQuery('#email2').val() != '')) {
	e_flag=1;
	$('#name_err_2').css("display","block");
	$('#email_err_2').css("display","block");
}
else if (jQuery('#name2').val() != '' && jQuery('#email2').val() != '')
{
	val_arr.push(jQuery('#name2').val()+'_'+jQuery('#email2').val());
}
if((jQuery('#name3').val() != '' && jQuery('#email3').val() == '') || (jQuery('#name3').val() == '' && jQuery('#email3').val() != '')) {
	e_flag=1;
	$('#name_err_3').css("display","block");
	$('#email_err_3').css("display","block");
}
else if(jQuery('#name3').val() != '' && jQuery('#email3').val() != '')
{
	val_arr.push(jQuery('#name3').val()+'_'+jQuery('#email3').val());
}
if((jQuery('#name4').val() != '' && jQuery('#email4').val() == '') || (jQuery('#name4').val() == '' && jQuery('#email4').val() != '')) {
	e_flag=1;
	$('#name_err_4').css("display","block");
	$('#email_err_4').css("display","block");
}
else if(jQuery('#name4').val() != '' && jQuery('#email4').val() != '')
{
	val_arr.push(jQuery('#name4').val()+'_'+jQuery('#email4').val());
}
if(e_flag == 1)
{
	return false;
}
else
{
//alert(val_arr);
if(val_arr.length == 0) {
alert('Please enter atlease one details');
return false;
}
else{
	$.ajax({
			 type: "POST",
			 url: "<?php echo base_url(); ?>logged/church/church_add_member_form/",
			 data: {'val_arr': val_arr},
			 success: function(data){
				hideBusyScreen();
				showUIMsg('Mail sent successfully');				
				window.location.href="<?php echo base_url(); ?>logged/church/church_invited_member/";
			 }
		 });
}
}
}


</script>

<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/church_footer.phtml");?>

<!-- /FOOTER SECTION -->

