<?php
	include(APPPATH ."views/layouts/church_admin_header.phtml");
?>
<script language="javascript">
$(function()
{
    if("<?php echo $_SESSION['addsubadminmsg']?>" != '')
    {
        showUIMsg('<?php echo $_SESSION['addsubadminmsg']?>');
        <?php unset($_SESSION['addsubadminmsg'])?>
    }
});
</script>
<!-- CONTENT SECTION -->
<?php // pr($member_arr); ?>

<div class="container-body">
   <?php
	//include(APPPATH ."views/layouts/church_admin_left.phtml");
?>
    <div class="right-panel">
    <h2>Sub Admin</h2>
    
<div class="spacer"></div>
    <div class="church-setting-main">
        <h3>Add New Sub Admin</h3>
        
        <div class="form-main">
        <form action="<?php echo base_url().'church-addsubadmin'?>" method="post">
            <label>Search Members: </label>
            <input type="text" name="searchemail" value="<?php echo $searchemail?>" placeholder="Please Type Email" class="find-email">
            <input type="submit" value="Search" class="post-btn-new">
            <span class="error-msg">Required</span>
            </form>
        </div>
       
        <div class="spacer"></div>
        <?php
        if($member_arr[0] && $member_arr[0]->role != 2)
        {
            ?>
            <div class="add-member-main"><ul class="member-list">
            <li>
                
                <div class="user-pic" style="background:url(<?= get_profile_image_of_user('thumb',$member_arr[0]->s_profile_photo,$member_arr[0]->e_gender) ?>) no-repeat;" title="<?= $user_name ?>"></div>
                <div class="right-text"><h4><a href="javascript:void(0);"><?php echo  $member_arr[0]->s_first_name.' '.$member_arr[0]->s_last_name?></a></h4>
                <!--<p class="designetion">CEO &amp; Founder at The Lazeez Hotel and Restaurant</p>
                <p class="update-time">Added by Joe about 4 months ago</p></div>-->
                
                <div class="assign-main">
                    <form action="<?php echo base_url().'logged/church/church_addsubadmin'?>" method="post">
                        <input type="hidden" name="subadminaccess" value="1">
                        <input type="hidden" name="memberid" value="<?php echo $member_arr[0]->cmid?>">
                       <label><input type="checkbox" name="assign[]" value="wall"> Community</label>
                       <label><input type="checkbox" name="assign[]" value="prayergroup"> Prayer Group</label>
                       <label><input type="checkbox" name="assign[]" value="ring"> Rings</label>
                        <input type="submit" value="Assign" class="post-btn">
                    </form>    
                </div>
                
            </li></div>
            <?php
        }
        ?>
        
        <div class="spacer"></div>
    </div>
    
    </div>
    
    </div>
    <div class="clear"></div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/church_footer.phtml");?>
<!-- /FOOTER SECTION -->


