<?php

    include(APPPATH ."views/layouts/church_admin_header.phtml");

?>

<script type="text/javascript">

$(document).ready(function() {



    // for AJAX page-submission...

    var options = { 

        beforeSubmit:  showLoad,  // pre-submit callback 

        success:       validateFrm // post-submit callback 

    }; 

 

    // bind to the form's submit event 

    $('#importfrm').submit(function() {

        $(this).ajaxSubmit(options);

        return false;

        

    });



});



function showLoad()

{

 // $('#photo_album_btn').attr('disabled','disabled');

    showUIMsg();

  $('#product_create_btn').val('Creating...');

  

}





// validate ajax-submission...

function validateFrm(data)

{

    //alert( data);

    var data = JSON.parse(data);



    id=data.photo_id;



    if(data.success==false) 

    {

        $('.error-message').each(function(i){

            $(this).attr('style','display:none');

        });

        

        //$('#photo_album_btn').attr('disabled','');

        $('#product_create_btn').val('Create');

        $('#photo_loading').html('');



        for ( var id in data.arr_messages ){

            //alert(data.arr_messages[id]);

            if( $('#'+id) != null ) {

                $('#'+id).html(data.arr_messages[id]);

                $('#'+id).css('display', 'block');

            }

        }



        showUIMsg(data.msg);

    }

    else {

        

        showUIMsg(data.msg);        

        $('#csv').val('');

        

    }

    $('#sp_add_loading').html('');

    //hideLoading();

                

}








function searchWithMemberStatus(obj)
{
    $.ajax({
        type: 'post',
        url: base_url+'logged/church/search_church_member_pagination',
        dataType: 'json',
        data:'memberstatus='+obj.val(),
        success: function (data, status) {
            hideUILoader_nodialog();
            if(data.success) {
                
                    $('#table_content').html(data.html);
                }
               
     

            }   // end of success function...


    });
}

function approvedMember()
{
    //var mstatus = status;
	var id = $('#i_del_id').val();
	var mid = $('#i_mem_id').val();
	var mstatus = $('#i_mem_status').val();
	var approvedStatus = $('#i_mem_approved_status').val();
    $.ajax({
        type: 'post',
        url: base_url+'logged/church/approve_member/',
        dataType: 'json',
        data:'mid='+id+'&status='+mstatus+'&memberid='+mid,
        success: function (data, status) {
            hideUILoader_nodialog();
			hide_dialog();
            if(data.success) {
			//alert(mstatus);
                if(mstatus == 1)
                 {
						var mem_approved_status = 0;
						var mem_approved_status_label = 'Block';
						var dialog_box_class = 'block-group';
					if (approvedStatus == 0) {
						mem_approved_status = 1;
						mem_approved_status_label = 'Unblock';
						dialog_box_class = 'unblock-group';
					}
						$('#approve_'+id).html('<span>Approved</span><a onclick="show_dialog(\''+dialog_box_class+'\'); $(\'#i_del_id\').val(\''+id+'\'); $(\'#i_mem_unblock\').val(\''+mem_approved_status+'\');" href="javascript:void(0);">Block</a>');
						$('#approve_'+id).attr('class','approve');
					
					//window.location.reload();
                }
                else if(mstatus == 2)
                {
                    $('#approve_'+id).html('<span>Declined</span><a onclick="show_dialog(\'delete-group\'); $(\'#i_del_id\').val(\''+id+'\');" href="javascript:void(0);">Delete</a>');
                    $('#approve_'+id).attr('class','decline');
                }
     

            }   // end of success function...

        }

    });

}


</script>

<!-- CONTENT SECTION -->

<?php //pr($church_arr); ?>



<div class="container-body">

   <?php

    //include(APPPATH ."views/layouts/church_admin_left.phtml");

?>

    <div class="right-panel">
        <!--right-panel equal-height--->

    <h2>Members</h2>

    <!--<div class="vector-search">

        <label>Search :</label>

        <input type="text" >

    </div>-->

    <div class="vector-search">
		
        <span class="sample_csv">
            
            <a href="<?= base_url().'uploads/sample_csv/member_mailid.csv'?>" target="_blank"  >Download sample CSV</a>
        </span>
        
        <form style="width:412px;" name="importfrm" id="importfrm" action="<?=base_url().'logged/church/import_member_csv'?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">

        <label>Import CSV :</label>

        <input type="file" name="csv" id="csv">

        <input type="submit" value="Import" class="post-btn">

         <span id="err_csv" class="error-message"></span> 

        </form>
<div class="clear"></div>
    
    </div>

   

    <div class="right-box">

<div class="select-member"><form action="<?php echo base_url()?>church_member" method="POST" name="search">
            <label>Select  Member Status :</label>
            <select name="memberstatus" onchange="searchWithMemberStatus($(this))">
                <option value="">Select </option>
                <option value="1">Approved Members</option>
                <option value="0">Not Approved</option>
                <option value="2">Declined Members</option>
            </select>
        </form></div>
            <div class="clear"></div>
            <div align="right"><input type="submit" value="Add member" class="btn" onclick="invite_member();" style="font-weight:normal;"></div><br />

        <div class="church-time-table" style="margin-right:0;" id="table_content">
                        <?= $result_content ?>

        



        </div>

        

     



    </div>

    

     

    

    </div>

    

    </div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>

<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/church_footer.phtml");?>

<!-- /FOOTER SECTION -->




<script type="text/javascript">
function invite_member() {
	window.location.href = "<?php echo base_url(); ?>logged/church/church_add_member_form";
}

function sample_csv(){
   // alert('dd');
     $.ajax({

        type: 'post',

        url: base_url+'logged/church/download_sample_csv/',

        dataType: 'json',

        //data:'mid='+id,

        success: function (data, status) {



            hideUILoader_nodialog();

            if(data.success) {
window.open('<?php echo base_url();?>/church_member/?file=member_mailid.csv','_blank','width=200,height=100')
              //  $('#approve_'+id).html('Approved');  

               // $('#approve_'+id).removeAttr('onclick');

            }   // end of success function...

        }

    });
}

function deleteGroup()
    {
        hide_dialog();
        showBusyScreen();
        $.ajax({
            type: 'POST',
            url: base_url + 'logged/church/delete_member/',
            dataType: 'json',
            data: ({'gr_id': $('#i_del_id').val()}),
            success: function(data, status) {
                hideBusyScreen();
                showUIMsg(data.msg);
                $('#table_content').html(data.html);
				window.location.reload();
            }
        });
    }
	
function blockGroup()
    {
        hide_dialog();
        showBusyScreen();
		var id = $('#i_del_id').val();
        $.ajax({
            type: 'POST',
            url: base_url + 'logged/church/block_member/',
            dataType: 'json',
            data: ({'gr_id': $('#i_del_id').val()}),
            success: function(data, status) {
                hideBusyScreen();
                showUIMsg(data.msg);
				$('#approved_status_label_'+id).html('Block');
				$('#approved_status_label_'+id).attr('class','approve');
                $('#table_content').html(data.html);
				//window.location.reload();
            }
        });
    }

function unblockGroup()
    {
        hide_dialog();
        showBusyScreen();
		var id = $('#i_del_id').val();
        $.ajax({
            type: 'POST',
            url: base_url + 'logged/church/unblock_member/',
            dataType: 'json',
            data: ({'gr_id': $('#i_del_id').val()}),
            success: function(data, status) {
                hideBusyScreen();
                showUIMsg(data.msg);
				$('#approved_status_label_'+id).html('Unblock');
				$('#approved_status_label_'+id).attr('class','decline');
                $('#table_content').html(data.html);
				//window.location.reload();
            }
        });
    }	
$(document).ready(function(){
    $('.approve').children('a').mouseover(function(){
        var check = $('.approve a').val();
        alert(check);
    });
    
});
</script>
