<!-- CONTENT SECTION -->
<?php //pr($church_arr); ?>
<?php //pr($prayer_grp_info)?>
<?php 			if(!empty($prayer_grp_info)){	foreach($prayer_grp_info as $key=>$val)			{											?>

<div class="nw-prayer-wall-box no-right-mrgn" id="payer_member_<?=$val['rec_id']?>"> <!--<span class="prayermember-leble">							<a href="javascript:void(0)"> Join a Prayer</a>						</span>-->
  <ul class="prayermember-ul">
    <li> <span class="payer-member-name">
      <div style="background:url(<?=get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender'])?>) no-repeat center;width:30px; height:30px;" class="pro_photo3"></div>
      <div class="pra-member-content">
        <p>Group Name:<a href="<?=base_url()?>church-prayer-group/<?=$val['i_prayer_group_id']?>">
          <?=$val['s_group_name']?>
          </a> </p>
        <p>Invitee Name:<a href="<?=get_public_profile_url($val['i_user_id'], get_username_by_id($val['i_user_id']))?>">
          <?=get_username_by_id($val['i_user_id'])?>
          </a></p>
        <p> Requested On-
          <?=getShortDate($val['dt_created_on'],5)?>
        </p>
        <ul class="prayer-option">
          <li><a href="javascript:void(0)" onclick="acceptDecline_PrayerGroup_Invitation('<?=$val['i_prayer_group_id']?>','<?=$val['i_owner_id']?>','<?=$val['rec_id']?>','<?= $val['i_user_id'] ?>','decline');" class="icon-reject">Delete</a></li>
        </ul>
      </div>
      </span> </li>
  </ul>
</div>
<?php					  } ?>
<?php } else {?>
<p>No member found</p>
<?php } ?>
 <input type="hidden" id="current_page" name="current_page" value="<?= $current_page_1 ?>"  />  
