<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />

<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />

<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />

<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->

<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>

<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>

<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>

<script type="text/javascript">

$(function(){

		$("#friendSlct").multiselect().multiselectfilter();	

		$("#ringselect").multiselect().multiselectfilter();

		$("#netpalselect").multiselect().multiselectfilter();

		$("#ppselect").multiselect().multiselectfilter();	

		$("#pgselect").multiselect().multiselectfilter();

		$("#frndinv").multiselect().multiselectfilter();	

		$("#netpalinv").multiselect().multiselectfilter();

		$("#ppinv").multiselect().multiselectfilter();

		$("#pginv").multiselect().multiselectfilter();

	

	});

	

</script>

<script language="javascript">



var g_controller_url = base_url+"church-ring-list";



var photo_id = null;

$(document).ready(function() {



	// for AJAX page-submission...

    var options = { 

        beforeSubmit:  showLoad,  // pre-submit callback 

        success:       validateFrm // post-submit callback 

    }; 

 

    // bind to the form's submit event 

    $('#ring_frm').submit(function() {

        $(this).ajaxSubmit(options);

        return false;

		

    });



});



function showLoad()

{

 // $('#photo_album_btn').attr('disabled','disabled');

 	showUIMsg();

  $('#photo_album_btn').val('Updating...');

  

}





// validate ajax-submission...

function validateFrm(data)

{

	//alert( data);

	var data = JSON.parse(data);



	id=data.photo_id;



	if(data.success==false) 

	{

		$('.error-message').each(function(i){

			$(this).attr('style','display:none');

		});

		

		//$('#photo_album_btn').attr('disabled','');

		$('#photo_album_btn').val('Create');

		$('#photo_loading').html('');



		for ( var id in data.arr_messages ){

			//alert(data.arr_messages[id]);

			if( $('#err_'+id) != null ) {

				$('#err_'+id).html(data.arr_messages[id]);

				$('#err_'+id).css('display', 'block');

			}

		}



		

	}

	else {

		

		showUIMsg(data.msg);		

		//window.location.href= "<?$_SERVER['HTTP_REFERER']?>";///document.URL;

		window.location.href= "<?php echo base_url().'church-ring-list'?>";

		

	}

	$('#sp_add_loading').html('');

	//hideLoading();

				

}











$(function(){

	$('#ring_desc_span').textCounter({

		target: '#ring_desc', // required: string

		count: 500, // optional: integer [defaults 140]

		alertAt: 20, // optional: integer [defaults 20]

		warnAt: 10, // optional: integer [defaults 0]

		stopAtLimit: true // optional: defaults to false

	});

	

});





</script>

<script type="text/javascript">

$(document).ready(function() {



	$('.send-pro-message').click(function(){

		var index=$(this).index();

		$('.new-wl > .comments-number ').css('display','none');

		$(this).next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');

	});

	

	 $('.wal-minus').click(function(){

			$(this).parents('.comments-number').slideUp('fast');

	 });

});

</script>





<?php  include(APPPATH ."views/layouts/church_logged_header.phtml");?>

            <!-- NAVIGATION SECTION -->

      <?php //include(APPPATH."views/layouts/nav.phtml");?>

      <!-- /NAVIGATION SECTION -->

      </div>

</div>

<!-- /HEADER SECTION -->

<div class="clr"></div>



<!-- CONTENT SECTION -->

<div class="container">

      <div>

            <div class="main-page"> 

                  

                 <?php //include(APPPATH ."views/layouts/latest_news.phtml");?>

                   

                  <div class="clr"></div>

                  

                  <div id="main_container">

                  

                        

                        <?php //include(APPPATH."views/layouts/leftbar.phtml");?>

                        <?php //pr($ringdetail); ?>

                        <div id="mid_container">
                       	  
                          <h3 class="page-heading">Edit Ring</h3>

                             <form name="ring_frm" id="ring_frm" action="<?=base_url().'logged/church_ring/update_ring/'.$ringdetail['id']?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">

                             <div class="create-ring">

                                    <div class="lable01">Name: </div> 

                                    <div class="field03">

                                    <input name="ring_name" id="ring_name" type="text" value="<?php echo $ringdetail['s_ring_name']?>" />

                                    <span id="err_name" class="error-message"></span> 

                                    </div>  

                                    <div class="clr"></div>

                                    <div class="lable01">Description: </div>  

                                    <div class="field03">

<!--                                        <textarea name="ring_desc" id="ring_desc" cols="" rows="" style="width:300px; height:170px;"><?php // echo $ringdetail['s_description']?></textarea>-->

                                    <textarea name="ring_desc"  id="ring_desc" style="height:170px" onFocus="if(this.value=='Max 500 Char allowed') this.value='';" onBlur="if(this.value=='')this.value='Max 500 Char allowed'; " onkeypress="return restrict_carrige(event);"  ><?php 

									if($ringdetail['s_description']== '')

									{echo "Max 500 Char allowed";}

									else{

									echo $ringdetail['s_description'];

                                                                        }

									?></textarea>

                                    <div class="clr"></div>

                                     <span id="ring_desc_span" class="pad-80 tcWarn" style="display:none;">0</span>

                                     

                                     <span class="ch-count"></span>

                                     <p style="float:left" class="ch-count"><span id="text_count" >0</span> Characters left</p>

                                    <span id="err_desc" class="error-message"></span> 

                                    </div> 

                                    <div class="clr"></div>

                                    <div class="lable01">Category:</div>  

                                    <div class="field03">

                                    <select name="category" id="category" onchange="generateSubcat($(this).val())">

                                          <option value="">Please Select Category</option>

                                          <?php echo $category?>

                                    </select>

                 					<span id="err_category" class="error-message"></span> 

                                   <?php /*?> <script type="text/javascript">

                                        $(document).ready(function(arg) {

                                            $("#category").msDropDown();

                                            $("#category").hide();

                                        })

                                    </script><?php */?></div> 

                                    <div class="clr"></div>

                                    

                                    <div style="display:block;" id="sub_cat"><?=$sub_cat_html?></div>

                                    <div class="lable01"> Invite Members :</div>  

                                    <div class="field03">



                                      <?php echo get_churchinvitation('ring');?>

                                         <span id="err_invite_frnd" class="error-message"></span> 

                    

                                    </div>

                                    <div class="clr"></div>

                                     <div class="lable01">Logo:</div>  

                                    <div class="field03">

                                    <input name="ring_logo" type="file"  size="39" />

                                    

                                    <?php

									$LOGO	= base_url().'uploads/church_ring_logo/'.getThumbName($ringdetail['s_logo'],'thumb');

									?>

                                    <div style="background:URL('<?php echo $LOGO?>') no-repeat center; width:73px; height:72px; background-color:#fff"></div>

                                    <span id="err_logo" class="error-message"></span> 

                                    </div> 

                                    

                                    <div class="clr"></div>

                                     <div class="lable01">Privacy Settings:</div>  

                                    <div class="field03">

                                    <select name="privacy_settings" id="privacy_settings">

                                          

                                          <option value="2" <?php if($ringdetail['i_privacy']==2){echo 'selected';}?>>All User</option>

                                          <option value="1" <?php if($ringdetail['i_privacy']==1){echo 'selected';}?>>Only user invited by you can join  </option>

                                    </select>

                 					<span id="err_privacy_settings" class="error-message"></span> 

                                  <!--  <script type="text/javascript">

                                        $(document).ready(function(arg) {

                                            $("#privacy_settings").msDropDown();

                                            $("#privacy_settings").hide();

                                        })

                                    </script>--></div> 

                                     

                                    <div class="clr"></div>

<!--                                    <div class="lable01">	Invite Friends :</div>  -->

                                    <div class="field03" style="display: none;">

                                    

                                   	  <input type="text" id="invite_frnd" name="invite_frnd" autocomplete="off" placeholder ="Enter friend email id" />

                                      <input type="hidden" id="h_friend_id"  name="h_friend_id" />

                                      <?php //echo get_invitation('ring',$ringinvted);?>

                                         <span id="err_invite_frnd_email" class="error-message"></span> 

										

                                    </div>

                                  <?php /*?>  <div class="field03">  <p class="amber">A ring can not have more than 100 members.</p>

                                        <p class="blue_bold12"><a href="mailto:admin@admin.com?Subject=Please increase max member limit for my group">Request site admin to increase number</a></p></div>

                                        <?php */?>

                                        <div class="clr"></div>

                                     <div class="lable01">&nbsp;</div>  

                                    <div class="field03">

                                      

                                      <input name="photo_album_btn"  id="photo_album_btn" type="submit" value="Update"  class="btn"/> 

                                         <input name="" type="button" value="Cancel"  class="btn" onclick="location.href='<?php echo base_url()?>church-ring-list'" />

                               </div> 

                                    <div class="clr"></div>

                               </form>

                          

                            </div>

                        </div>

                         

                        

                         

                        <?php //include(APPPATH."views/layouts/rightbar.phtml");?>

                         

                  </div>

                   

                  <div class="clr"></div>

            </div> 

      </div>

      <div class="clr"></div>

</div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>











<?php //include(APPPATH."views/layouts/footer.phtml");?>

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<?php include(APPPATH."views/layouts/church_footer.phtml") ?>









<!-- /lightbox SECTION -->

<!-- confirm delete album popup-->

<!-- end of delete pop up -->

<script type="text/javascript">



 function generateSubcat(id) {

        showUILoader_nodialog();

        $.ajax({

            type: 'get',

            url: '<?= base_url() ?>logged/church_ring/generateSubCat_II' + '/' + id,

            dataType: 'json',

            success: function(data, status) {

                hideUILoader_nodialog();

                $('#sub_cat').html(base64_decode(data.html));

                $('#sub_cat').attr('style', 'display:block;');

            }	// end of success function...

        });

    }

</script>

<script type="text/javascript">

var carriage_count = 0;



$(document).ready(function () {

var count1=0;

//counting the left characters in comment

function limitChars(textid, limit, infodiv)

{

	

  var text = $('#'+textid).val(); 

 

  

  if(text == '' || text == 'Max 500 Char allowed'){

	 

	 var textlength = 0;

  }

 





else

{

	//alert(text);

 var textlength = text.length;
var textlength1 = (500 - textlength);
 //alert(textlength);

}

  $('#text_count').html(textlength1);

  if(textlength > limit)

  {

  $('#'+textid).val(text.substr(0,limit));

  return false;

  }

  else

  {

  return true;

  }

  

}





$(function(){

  $('#ring_desc').keyup(function(){

	  count1=1;

  limitChars('ring_desc', 500, '');

  });

  $('#ring_desc').keydown(function(){

	  count1=1;

  limitChars('ring_desc', 500, '');

  });

});





//// just to show correct no. of chracters left while the page is loaded...

limitChars('ring_desc',500, '');







});



function restrict_carrige(e)

{

	/*//if(e.keyCode == 13)

	{

		$.ajax({

			type: 'post',

			url: base_url+'logged/prayer_wall/getCarriageCount',

			data: {'str':$('#ta_desc').val()},

			dataType: 'json',

	

			success: function (data, status) {

				

					if(data.count > 1){

						return false;

					}

				

				}	// end of success function...

		});

	}*/

	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));



	if(e.keyCode == 13){

		carriage_count++;

		console.log(carriage_count);

	}

	/*if(e.keyCode == 8){

		carriage_count--;

	}*/

	if(e.keyCode == 13 && carriage_count >10){

		return false;

		//e.preventDefault();

	}

}

</script>

