<?php include(APPPATH ."views/layouts/church_logged_header.phtml");?>
<!-- NAVIGATION SECTION -->
<?php //include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->
</div>
</div>
<!-- /HEADER SECTION -->

<div class="clr"></div>
      <div class="container">

    <div class="main-page">
    <h3 class="page-heading">Ring</h3>
        <div id="mid_content">
            <!-- latest news -->
            <?php //include(APPPATH . "views/layouts/church_admin_left_ring.phtml"); ?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div>
                <?php include(APPPATH . "views/layouts/church_admin_left_ring.phtml") ?>
                <!-- left container -->
                <div class="activity-right">
                   
                    <div id="mid_container">
                        <div class="page_heading">

                            <div class="left" style="font-size:17px;"><!--<img src="images/icons/ring.png" alt="" /> Rings - --><div class="pro_photo_new" style="background:URL('<?=get_church_ring_logo_by_id($ring_detail_arr['0']['id'])?>') no-repeat center; width:73px; height:72px; background-color:#fff" onclick="location.href='<?=base_url()?>church_rings/<?=$ring_detail_arr['0']['id']?>/ring-home.html'"></div>  <?= $ring_detail_arr[0]['s_ring_name'] ?> </div>

                            <div class="right">

                              <input type="button" style="margin-top:0; margin-bottom:5px;" value="Back to My Rings" onclick="page_log()" class="back-btn" />

                            </div>

                            <div class="clear"></div>

                        </div>

                    </div>
                   
                    <div id="ring_members" class="div_content" style=" margin-top:0px;">
                      
                      <?=$ring_members?>
                    </div><!--div_container-->
                    <?php
                    //echo $current_page;
                    //echo "view more: ".$view_more;
                    //echo "current_page : ".$current_page;
                    if($view_more)
                    {
                    ?>
                          <div id="show_more_feeds_div" class="view_more">
                          <a id="show_more_feeds_link" onclick="show_more_members($(this).attr('page_value'))" page_value="<?php echo $current_page?>" href="javascript:void(0);">view more</a>
                          </div>
                    <?php
                    }
                    ?>
                    
              </div>
              <div class="clr"></div>

            </div>

            <div class="clr"></div>

        </div>

        <div id="bot_corner">&nbsp;</div>

    </div>

    <div class="clr"></div>

</div>

<!-- /CONTENT SECTION -->

<div class="clr"></div>

<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/church_footer.phtml");?> 

<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>




<?php include(APPPATH . "views/logged/ring/comments/my_ring_post_comment_lightbox.phtml"); ?>

<?php /* ?>VIEW COMMENTS<?php */ ?>

<div class="lightbox view_comments_div " style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/cmnt.png" alt="" width="30" height="30"/> View Comments </h4>
                  </div>
            </div>
            <div id="comment_html"></div>

            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<?php /*?>VIEW COMMENTS<?php */?>


<!-- confirm delete popup-->
<div class="lightbox delete-page-popup" style="width: 400px; left: 296px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Member</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to remove this member?</p>
               </div>
               <form method="post" enctype="multipart/form-data">
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                 <input name="" type="button" value="Yes" class="post-btn" style="margin-left:105px;" onClick="delete_member_()"/>
                    <input name="" type="button" value="No" class="cancel-btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!-- end of delete pop up -->


<script type="text/javascript">
function delete_confirm_(id)
{
    $('#i_del_id').val(id);
     
    show_dialog('delete-page-popup');
}


function delete_member_()
{
    id= $('#i_del_id').val();
    
    
    
    
    $.ajax({
        url : base_url+"logged/church_ring_home/delete_member",
        type : "post",
        data : ({'table_id':id}),
        dataType : 'json',
        success : function(data)
        {
            showUIMsg(data.msg);
            hide_dialog();
            window.location=document.URL;
        }
    });
}





var ajax_req_feeds = null;
function show_more_members(page) {
    
    if(ajax_req_feeds!=null) {
        ajax_req_feeds.abort();
    }
    
    showUILoader_nodialog();
    ajax_req_feeds = $.ajax({
        type: 'get',
        url: base_url+'logged/church_ring_home/ring_members_ajax_pagination/<?=$ring_id?>/'+page,
        dataType: 'json',

        success: function (data, status) {
//alert(data.current_page);
            hideUILoader_nodialog();
            if(data.html!='') {
                $('#ring_members').append(data.html);
                $('#show_more_feeds_link').attr('page_value', data.cur_page);
                $('#show_more_feeds_link').attr('onclick','');
                $('#show_more_feeds_link').attr('onclick','show_more_members('+data.cur_page+')');
            }
            else {
                $('#ring_members').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more member.</p></div>');
                $('#show_more_feeds_div').hide();
            }
            if(data.view_more==false)
            {
                $('#ring_members').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more member.</p></div>');
                $('#show_more_feeds_div').hide();
            }
            
           

        }    // end of success function...
    });
}



</script>