<?php
//pr($my_videos_album_content);
if(count($my_videos_album_content))
{
    foreach($my_videos_album_content as $album):
        $IMG = base_url()."uploads/user_videos_album/".getThumbName($album['s_video_album_image'],'thumb');
        $NO_IMG = base_url()."uploads/user_videos_album/no_image.gif";
        
?>
<div class="audio_div">
    <div class="photo-div">
        <a href="<?php echo get_video_album_url($album['id'], $album['s_name'])?>"><img src="<?php if($album['s_video_album_image']!='') echo $IMG; else echo $NO_IMG?>" alt="" style="width: 122px; height:82px"/></a>
    </div>
    <p class="blue_bold12"><a href="<?php echo get_video_album_url($album['id'], $album['s_name'])?>">
    <?php echo ucfirst(substr($album['s_name'],0,12))?><?if(strlen($album['s_name'])>12) echo "...";?></a></p>
        <?php
            if ($album['total_videos']>1)
                echo $album['total_videos']." Videos";
            else
                echo $album['total_videos']." Video";
        ?>
</div>


<?php
    endforeach;
}
else{
            echo  '<div class="section01" style="padding-top:5px;"><div  class="shade_norecords" style="width:280px;"><p class="blue_bold12">No Video Albums.</p></div></div>';
    }
?>
<div class="clr"></div>



<?php
 if($page_links){ ?>
<div class="pagination">

    <div class="left">Viewing Page <?=$current_loaded_page_no?> of <?=$total_pages?> </div>
    
    <div class="right">
           <ul class="small-paging">
            <?=$page_links?> 
            </ul>
    </div>
</div>
<?php  }
?>