<div class="div_content" style=" margin-top:0px;">

							<?php
							//pr($prod_data);
							if($prod_data)
							{
								$tmpid	= '';
								foreach($prod_data as $product)
								{
									
									$LOGO	= base_url().'uploads/e_trade_product/'.getThumbName($product['s_image'],'thumb');
							?>
									<div class="ne-etrade-product-category-list">
									<div class="thumb">
                                    	<div class="img_div" style="background:url(<?php echo $LOGO?>) no-repeat center #fff;" onclick="window.location='<?php echo base_url()?>efreebie/<?php echo $product['pid']?>/detail.html'"></div>
                                    </div>
									<div class="thumb-right">
                                    	
										<br class="clear"/>
									
										<div class="heading-etrade"><strong><?php echo $product['product_id']?></strong></div>
										<div class="heading-etrade" onclick="window.location='<?php echo base_url()?>efreebie/<?php echo $product['pid']?>/detail.html'" style="cursor:pointer;"><?php echo $product['s_name']?></div>
										<p class="attribute1">
											<?php echo substr($product['s_attribute1'],0,100)?>
										</p>
                                       
									</div>
									<?php /*?><ul class="ne-etrade-breadcrumb2">
                                            <li><a class="view-shipping-free" href="javascript:void(0);" onclick="showShippingFee('<?php echo $product['id']?>')">View Shipping Fee</a>
											<!--slide view shipping free-->
												<div class="slide-view-shipping-free attribute1" id="shippingfee_<?php echo $product['id']?>">
													<p><strong> Local Shipping Fee :</strong> <?php echo get_price($product['f_local_shipping_cost'])?></p>
													<p><strong> International Shipping Fee :</strong> <?php echo get_price($product['f_international_shipping_cost'])?></p>
												</div>
											<!--slide view shipping free-->
                                            </li><li>Posted On: <?php echo $product['dt_insert_time']?></li>
											<li>Seller From: <?php echo get_user_address_info($product['i_user_id'])?></li>
										
									</ul>
                                    <p class="attribute1">
                                      <strong> Details: </strong><?php echo substrws($product['s_description'],70)?>
                                    </p>
                                    
                                    
                                 <?php
								if($product['i_user_id']!=intval(decrypt($this->session->userdata('user_id'))))
								{
								?>
                                <br class="clr"/>
                                <a class="view_more" href="<?php echo base_url()?>efreebie/<?php echo $product['id']?>/detail.html">Read More</a>
                                <?php
								}
								?><?php */?>
                                
                                  <?php
                                         $arr_req	= $product['recv_req_arr'];
								  ?>
                                 <ul class="ne-etrade-breadcrumb2">
                                    	<li ><a href="javascript:void(0);" class="total-req-li"><strong>Total Request:</strong> <?php echo count($arr_req);?></a></li>
                                  </ul>
                                  
                                   <div id="req_rcv<?php echo $product['pid']?>" style="display:none;" class="total-req-div">
									  <?php
                                         $arr_req	= $product['recv_req_arr'];
                                          if(count($arr_req)){ 
										   foreach($arr_req as $k=>$reqval)
                                           {
                                      ?>
								               <div class="ne-etrade-quantity-section" id="rating_div_<?php echo $reqval['reqid']?>">
												<?php
                                                if($reqval['i_accept'] ==0)
                                                {
                                                ?>
                                                <div class="ne-etrade-product">
                                      
                                               <?php /*?> <p class="send-request-quantity">Product Offered</p>
                                                 <p>Requested From : <span><?php echo get_user_address_info($reqval['requid']);?></span></p>
                                                <ul class="ne-etrade-breadcrumb">
                                                 
                                                  <li><a href="javascript:void(0)">Requested On - <?php echo getShortDate($reqval['dt_req_date'],5)?></a></li>
                                                </ul>
                                                
                                                 <p class="send-request-quantity color-txt">Accept to see Customer details</p>
                                                <ul class="ne-etrade-breadcrumb">
                                                  <li><img class="acpt" src="images/icons/accept.png" alt="" />
                                                      <a href="javascript:void(0);" onclick="update_sent_request('<?php echo $reqval['reqid']?>','1','<?php echo ($reqval['pid'])?>');">Accept</a>
                                                  </li>
                                            
                                                  <li>I</li>
                                                  <li><img class="acpt" src="images/icons/band.png" alt="" />
                                                  <a href="javascript:void(0);" onclick="update_sent_request('<?php echo $reqval['reqid']?>','2','<?php echo ($reqval['pid'])?>');">Decline</a></li>
                                                </ul>
                                                <br class="clear" /><?php */?>
                                                
                                                 <h3>Request # <?=$k+1?></h3>
                                                   <!--personal information start-->
                                                  <p style="padding-top:5px;"><strong>Buyer's Details:</strong></p>
                                                  <p class="">Address : <span><?php echo get_user_address_info($reqval['requid']);?></span></p>
                                                   <!--personal information start-->
                                                  <p class="">Requested On - <?php echo getShortDate($reqval['dt_req_date'],5)?></p>
                                                  <p></p>
                                                 <p class="send-request-quantity color-txt">Accept to see Customer details</p>
                                                 <ul class="ne-etrade-breadcrumb">
                                                  <li><img class="acpt" src="images/icons/accept.png" alt="" />
                                                      <a href="javascript:void(0);" onclick="update_sent_request('<?php echo $reqval['reqid']?>','1','<?php echo ($reqval['pid'])?>');">Accept</a>
                                                  </li>
                                                  <li>I</li>
                                                  <li><img class="acpt" src="images/icons/band.png" alt="" />
                                                  <a href="javascript:void(0);" onclick="update_sent_request('<?php echo $reqval['reqid']?>','2','<?php echo ($reqval['pid'])?>');">Decline</a></li>
                                                </ul>
                                                <br class="clear" />
                                                
                                              </div>
                                                <?php
                                                }
                                                else if($reqval['i_accept']==1)
                                                {
                                                    ?>
                                                    <?php /*?><div class="ne-etrade-product">
                                                    <p class="send-request-quantity">Product Offered</p>
                                                     <p>Requested From : <span><?php echo get_user_address_info($reqval['requid']);?></span></p>
                                                    <ul class="ne-etrade-breadcrumb">
                                                     
                                                      <li><a href="javascript:void(0)">Accepted On - <?php echo getShortDate($reqval['dt_accept'],5)?></a></li>
                                                      <li>I</li>
                                                      <li><img class="acpt" src="images/icons/accept.png" alt="" /> <span>Request Accepted</span></li>
                                                    
                                                    </ul>
                                                   <br class="clear" />
                                                
                                                <!--personal information start-->
                                              
                                                  <ul class="Item-list-req">
                                                      <li>Name: <?php echo $reqval['s_first_name'].''.$reqval['s_last_name']?></li>
                                                      <li>Phone:  <?php echo ($reqval['s_phone']=='')?$reqval['s_moblie_no']:$reqval['s_phone']?></li>
                                                      <li>Email: <?php echo ($reqval['req_email']=='')?$reqval['s_email']:$reqval['req_email']?></li>
                                                  </ul>
                                                 <br class="clear" />
                                                  </div><?php */?>
                                                    
                                                    <div class="ne-etrade-product">
                                                
                                                       <h3>Request # <?=$k+1?></h3>
                                                       <p class=""><strong>Product Offered</strong></p>
                                                       <!--personal information start-->
                                                       <p style=""><strong>Buyer's Details:</strong></p>
                                                       <p>Name: <?php echo $reqval['s_first_name'].''.$reqval['s_last_name']?>, Address : <span><?php echo get_user_address_info($reqval['requid']);?></span></p>
                                                       <p>Email: <?php echo ($reqval['req_email']=='')?$reqval['s_email']:$reqval['req_email']?>
                                                       <?php 
                                                        if($reqval['s_phone']!=''){
                                                       ?>
                                                       , Phone:  <?php echo ($reqval['s_phone']=='')?$reqval['s_moblie_no']:$reqval['s_phone']?><?php }?> </p>
                                                        <!--personal information start-->
        
                                                   <p class="">Accepted On - <?php echo getShortDate($reqval['dt_accept'],5)?></p>
                                                   <p></p>
                                                   <ul class="ne-etrade-breadcrumb">
                                                   <li><img alt="" src="images/icons/accept.png" class="acpt" />Accepted</li>  
                                                   </ul>
                                                   
                                                   <!--personal information start-->
                                                
                                                  </div>
                                                    <?php
                                                }
                                                else if($reqval['i_accept']==2 || $reqval['i_accept']==3)
                                                {
                                                    ?>
                                                  <div class="ne-etrade-product">
                                                  <h3>Request # <?=$k+1?></h3>
                                                  <p style="padding-top:5px;"><strong>Buyer's Details:</strong></p>
                                                  <p>Address: <span><?php echo get_user_address_info($reqval['requid']);?></span></p>
                                                  <p>Declined On - <?php echo getShortDate($reqval['dt_accept'],5)?></p>
                                                         
                                                      <ul class="ne-etrade-breadcrumb">
                                                          <li><img class="acpt" src="images/icons/band.png" alt="" /> <span>Request Declined</span></li>
                                                      </ul>
                                                  </div>
                                                  <?php
                                                }
                                                ?>
                                  
                                          </div>
                                     <?php
										   }
										  }
									 ?>
                                	  
                                   </div>
                             
							   </div>
                            <?php
								}
							}
							?>
</div>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page_1?>"  />                     

                            
<script type="text/javascript">
$(function(){
		
		$('.disclaimer-link').click(function(){
			$(this).parent('p').next('.read-disclaimer').slideToggle('fast');
		});
		$('.total-req-li').click(function(){ 
			$(this).parent().parent('ul').next('.total-req-div').slideToggle('slow');
		});	
});


function giveRatingToBuyer(id)
{
	
	$.ajax({
			"type":'post',
			"data":'id='+id+'&rate='+$('#rating'+id).val(),
			"dataType":'json',
			"url":'<?php base_url()?>logged/e_trade/add_rate_for_buyer',
			"success": function(data)
						{
							if(data.success==false)
							{
								showUIMsg(data.msg);
							}
							else
							{
								if(data.html!='')
								{
									$('#rating_div_'+id).html(data.html);
								}
								showUIMsg(data.msg);
							}
						}
		
		});
}
function shipped(id)
{
	alert(id);
	$.ajax({
			"type":'post',
			"data":'id='+id,
			"dataType":'json',
			"url":'<?php base_url()?>logged/e_trade/shipped',
			"success": function(data)
						{
							if(data.success==false)
							{
								showUIMsg(data.msg);
							}
							else
							{
								if(data.html!='')
								{
									$('#rating_div_'+id).html(data.html);
								}
								showUIMsg(data.msg);
							}
						}
		
		});
}
</script>                          

