						<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                                          <tr>
                                            <th align="left" valign="middle" height="30" width="70">Date Posted</th>
                                            <th align="left" valign="middle" height="30" width="250">Donated By</th>
                                            <th align="left" valign="middle" height="30" width="120">Donated Through</th>
                                            <th align="left" valign="middle" height="30" width="200">Between Dates</th>
                                            <th align="left" valign="middle" height="30" width="100">Day of Week</th>
                                            <th align="left" valign="middle" height="30" width="80">Prayer Time</th>
                                            <th align="center" valign="middle" height="30" class="last">Actions</th>
                                          </tr>
                                          <?php
										  		if(count($info_arr)){
													foreach($info_arr as $key=> $info){
										  ?>
                                          <tr>
                                            <td align="left" valign="top">25/01/2013</td>
                                            <td align="left" valign="top">Allen Matt</td>
                                            <td align="left" valign="top">Cheque</td>
                                            <td align="left" valign="top">20-Jan-2013 to 26-Jan-2013</td>
                                            <td align="left" valign="top">Tuewday</td>
                                            <td align="left" valign="top">5:00 PM</td>
                                            <td align="center" valign="middle" class="last">
                                           <!-- <input name="" title="Edit" type="button" class="edit-button"  value=""/>-->
                            				<input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return show_dialog('delete-product')"/>
                                            </td>
                                          </tr>
                                          <?php
													}
												}
											else{
											?>
												 <tr>
													  <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
												 </tr>
											
											<?php
												}
											?>
                                        </table>
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>