<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" />Daily Bible Verse</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                            
                            <div>
                            
                            <?php 
								if(count($published_rand_bible_verse)){
							?>
                            <h1 style="color:#005CA8; font-size:15px;">Published Verse</h1>
                            <p class="green-title">Bible Verse : [ <a  href="read-bible-chapter-view.php"><?=$published_rand_bible_verse['s_book_name']?> <?=$published_rand_bible_verse['s_chapter'].':'.$published_rand_bible_verse['i_verses']?></a> ]</p>
                            <p><?=$published_rand_bible_verse['s_text']?></p>
                            <?php 
								}
							else {
							?>
                             <p class="green-title">No active verse, Please generate and publish.</p>
                            <?php } 
							?>
                            </div>
                            <div class="clr"></div>
                            
                            
                          
                            
                          
                            <div class="clr"></div>
                            
                      		<?php /*
								if(count($rand_bible_verse)){
							?>
                            <div style="margin-top:30px;">
                                                      
                            <h1 style="color:#005CA8; font-size:15px;">Suggested Verse</h1>
                            <p class="green-title">Bible Verse : [ <a  href="read-bible-chapter-view.php"><?=$rand_bible_verse['s_book_name']?> <?=$rand_bible_verse['s_chapter'].':'.$rand_bible_verse['i_verses']?></a> ]</p>
                            <p><?=$rand_bible_verse['s_text']?></p>
                            </div>
                            <?php 
								}*/
							?>
                            
                          
                            
                            <!-- <p style="padding-top:15px;"> <input class="blue_btn" type="button" onclick="window.location=admin_base_url+'holy-place/1/daily-bible-verse.html'" value="Generate New Verse" name="" />-->
                           <p style="padding-top:15px;"> <input class="blue_btn" type="button" onclick="javascript:add_verse_new()" value="Generate New Verse" name="" />
                           <?php 
						  /* if($show_publish == true) {
						   ?> 
                           <input class="blue_btn mrg-left" type="button" onclick="javascript:add_verse_new()" value="Publish Verse" name="" />
                           <?php }*/ ?>
						   
                           </p>
						   
                        </div>
						 <DIV id="table_content" style="width:985px;">
                            <?=$result_content?>
                            </DIV>
                  </div>
                  <div class="clr"></div>
                  
            </div><!--/mid_content-->
            
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>
<style>
.blue_btn {
  background-attachment:scroll;
  background-color:#005CA8;
  background-image:none;
  background-position:0 0;
  background-repeat:repeat repeat;
  color:#FFFFFF !important;
}
.mrg-left{
	margin-left:8px;
}
</style>

<!-- /CONTENT SECTION -->


<script type="text/javascript">

function add_verse_new()
{ 
	showBusyScreen();
    $.ajax({
        url : admin_base_url+'holy_place/daily_bible_verse/add/',
        type : 'post',
        data : ({'s_book_name':'<?=$rand_bible_verse['s_book_name']?>',
		 		 's_chapter': '<?=$rand_bible_verse['s_chapter']?>',
				 'i_verses': '<?=$rand_bible_verse['i_verses']?>',
				 's_text': '<?=$rand_bible_verse['s_text']?>'}),
        dataType : 'json',
        success : function(data)
        {
            window.location = admin_base_url+'holy-place/2/daily-bible-verse.html';
			//$('#table_content').html(data.response);
        }
    });
    
}


</script>



