                                <input type="hidden" id="h_current_page" value="<?=$current_page?>" />
                                <table width="80%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                                          
                                          
                                          <tr>
                                            <th align="left" valign="middle" height="30" width="100">Purchase Date</th>
                                            <th align="left" valign="middle" height="30" width="300">Purchased By</th>
                                            <th align="center" valign="middle" height="30" width="80">Amount ($)</th>
                                            <th align="left" valign="middle" height="30" width="280">Status</th>
                                            <th align="center" valign="middle" width="20" height="30" class="last">Actions</th>
                                          </tr>
                                          
                                          <?php
											//pr($info_arr);
												if(count($info_arr)){
												foreach($info_arr as $key=> $info){
													
											
																 
											?>
                                             <tr>
                                                <td align="left" valign="top"><?=getshortdate($info['dt_created_on'],5)?></td>
                                                <td align="left" valign="top"><?=$info['s_profile_name']?></td>
                                                <td align="center" valign="top"><?=round($info['f_amount'],2)?></td>
                                                <td align="left" valign="top"><?=($info['i_order_status'] == 1)?'Completed':'Pending'?></td>
                                                <td align="center" valign="middle" class="last">
                                                <!--<input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return show_dialog('history-popup')"/>-->
                                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return confirm_delete_(<?=$info['id']?>)"/>
                                                </td>
                                              </tr>
                                          
                                       
                                         <?php    }
												}
												else{
											?>
												 <tr>
													  <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
												 </tr>
											
											<?php
												}
											?>
										</table>
                                        
                                       <?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>  