<input type="hidden" id="current_page" value="<?=$current_page?>">

<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="150">Category</th>
                                <th align="center" valign="middle" height="30" class="last" style="width: 42px;">Actions</th>
                              </tr>
                              
<?php
//pr($categories,1);
if(count($categories)) {
    foreach($categories as $category)
    {
?>
                              <tr>
                                <td align="left" valign="top"><?=$category['cat_name']?></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="window.location='<?=admin_base_url()?><?=$current_page?><?=$category['id']?>/edit-help-center-category.html'"/>
                                
                                </td>
                              </tr>
<?php
    }
}
else
{
?>
                            <tr>
                                <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                             </tr>
<?php
}
?>
                       
                            
                            </table>

<?php

if($page_links) :
?>         
<div class="paging">
            <ul><?= $page_links ?></ul>
</div>        
<?php
endif;
?>                              