<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>

<!-- CONTENT SECTION -->
<? include "media_center_nav.phtml" ?>



<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input">
		  <form name="user_frms" id="user_frms" method="post" action="<?= base_url() . 'logged/christian_news/search_news' ?>"  onsubmit="return true;" >
		  <input type="text" name="search_keyword_val" value="<?php echo $search_keyword_val?>" placeholder="Type Keywords separated by comma">
		  <input name="" type="submit" value="Deactivate"  class="btn" style="display:none;"/>
		  </form>
		  </div>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                <h3 class="featured-heading">featured</h3>
                
                
                
                <div class="video-slide">
                    <?php if($video_featured)
                       // pr($video_featured);
                        $i=0;
			
                    { ?>
                            <?php  ?>          
                	<ul class="watchslide">
                            <?php
                            foreach($video_featured as $val)
						{
                                 if($i == 5){ break;}
                                 //$vidurl = $val['s_url'];
                              // $finalurl = end(explode('https:',$vidurl));
                                $this->load->library('embed_video');
			$config['zend_library_path'] = APPPATH ."libraries/Zend/";
			$config['video_url'] =  $val['s_url'];
			
			$this->embed_video->initialize($config);
			$this->embed_video->prepare();
			$html = $this->embed_video->get_player('728','360');
                       // echo $html['html'];      
                                ?>
  
  
                           
                                                <li>
                                                <?php /*?><h4 class="video-txt" title="<?=$video_featured['s_title']?>"><?php echo my_substr($video_featured['s_title'],80)?></h4><?php */?>
<h4 class="video-txt" title="<?= $val['s_title']; ?>"><?php echo my_substr($val['s_title'],80) ?></h4>
												<?php  echo $html['html']; ?></li><?php $i++; } ?>
 
                                              
          
          </ul>
                                        <?php
                                             
                                        }
                                        ?>
<?php if($video_featured)
					{?>
<div id="bx-pager">
<?php
                     
					//pr($video_featured);	
                                                     $i = 0;
                                             foreach($video_featured as $val)
						{
                                                 if($i == 5){ break;}
                                                  $this->load->library('embed_video');
			$config['zend_library_path'] = APPPATH ."libraries/Zend/";
			$config['video_url'] =  $val['s_url'];
			
			$this->embed_video->initialize($config);
			$this->embed_video->prepare();
			$html = $this->embed_video->get_player('127','102');
							//$is_img = BASEPATH.'../uploads/media_center_videos/' . getThumbName($val['s_image'], 'sliderthumb');
							//$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_image'], 'sliderthumb');
							//if(is_file($is_img))
							//{
							
							?>
    <a data-slide-index="<?= ($i); ?>" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
    	<?php  echo $html['html']; ?><span title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],40)?></span></a>
  <!--<img src="<?$IMG; ?>"  width="127" height="102"/>
  <a data-slide-index="1" href=""><img src="http://bxslider.com/images/thumbs/houses.jpg" /></a>
  <a data-slide-index="2" href=""><img src="http://bxslider.com/images/thumbs/hill_fence.jpg" /></a>
  <a data-slide-index="3" href=""><img src="http://bxslider.com/images/thumbs/houses.jpg" /></a>
  <a data-slide-index="4" href=""><img src="http://bxslider.com/images/thumbs/hill_fence.jpg" /></a>-->
  <?php 
							//}
  $i++;
  }
  
  ?>
</div>
     <?php
					}
	 ?>           
                </div>
                
                
               
                <?php
                         $query = $this->db->get_where('cg_mc_video_cat', array('id' => 1));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat1 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat1 == 0){ 
                
				if($video1)
				{
				?>
                <h3 class="minister-shout"><a class="article_category" href="<?php echo base_url().'watch/category/1' ?>"><?php echo $cat_name['1']?></a></h3>
                	<div class="shout-list">
                    	<ul>
						<?php
						$i  = 1;
						foreach($video1 as $val) 
						{	
							$class = '';
							if($i==3)
							{
								$class='last';
								$i=0;
							}
							$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'bigthumb');
							
						?>
                        	<li class="<?php echo $class?>"><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>"><img src="<?php echo $IMG?>" alt="Minister4 Shout" width="222" height="157"><span title="<?=$val['s_title']?>">
							
							<?php echo my_substr($val['s_title'],35)?></span></a>
                            	<ul>
                                	<li><a href="javascript:void(0);">Comments</a><span> (0)</span></li>
                                    <li>|</li>
                                    <li><a href="javascript:void(0);">Liked by</a><span> (0)</span></li>
                                </ul>
                            </li>
                        <?php
						$i++;
						}
						?>						
                        </ul>
                    </div>
                <div class="clear"></div>
                <?php
				}
                                  }
                                   $query = $this->db->get_where('cg_mc_video_cat', array('id' => 2));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat2 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat2 == 0){ 
				if(count($video2)>0)
				{
				
				?>
                  <h3 class="channel-icon"><a class="article_category" href="<?php echo base_url().'watch/category/2' ?>"><?php echo $cat_name['2']?></a><a href="<?php echo 'watch/category/2'?>">View all</a></h3>
                  
                <div class="thumb-slider"> 
					<div class="slider4">
					<?php
					
					foreach($video2 as $val) 
					{
					
					$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'midthumb');
					?>
						<div class="slide"><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>">
						<img src="<?php echo $IMG?>" width="164" height="114" alt="Cogtime Channel"><span title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],20)?></span></a></div>
					<?php
					}
					?>
 
					</div>
				</div>
				<?php
				}
                                  }
                                  $query = $this->db->get_where('cg_mc_video_cat', array('id' => 3));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat3 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat3 == 0){
                                  
				if($video3)
				{
				?>
                 
                     <h3 class="overcomers-icon"><a class="article_category" href="<?php echo base_url().'watch/category/3' ?>"><?php echo $cat_name['3']?></a></h3>
                     <div class="thumb-slider"> 
						<div class="slider4">
						<?php
						foreach($video3 as $val) 
						{
						$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'midthumb');
						?>
						<div class="slide"><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>"><img src="<?php echo $IMG?>" width="164" height="114" alt="Overcomers"><span title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],20)?></span></a></div>
						<?php
						}
						?>
						</div>
					</div>
				<?php
				}
                                  }
                                  $query = $this->db->get_where('cg_mc_video_cat', array('id' => 4));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat4 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat4 == 0){
				if($video4)
				{
				?>
                      <h3 class="inspired-icon"><a class="article_category" href="<?php echo base_url().'watch/category/4' ?>"><?php echo $cat_name['4']?></a><a href="<?php echo 'watch/category/'.$val['i_category_id']?>">View all</a></h3>
						<div class="thumb-slider"> 
						<div class="slider4">
						<?php
						foreach($video4 as $val) 
						{
						$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'midthumb');
						?>
						<div class="slide"><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>"><img src="<?php echo $IMG ?>" width="164" height="114" alt="Overcomers"><span title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],20)?></span></a></div>
						 
						<?php
						}
						?>
 						</div>
						</div>
				<?php
				}
                                  }
                                  $query = $this->db->get_where('cg_mc_video_cat', array('id' => 5));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat5 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat5 == 0){
				if($video5)
				{
				?>
				<h3 class="coaching-icon"><a class="article_category" href="<?php echo base_url().'watch/category/5' ?>"><?php echo $cat_name['5']?></a><a href="<?php echo 'watch/category/'.$val['i_category_id']?>">View all</a></h3>
					<div class="thumb-slider"> 
					<div class="slider4">
					<?php
					foreach($video5 as $val) 
					{
					$IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'midthumb');
					?>
					<div class="slide"><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>"><img src="<?php echo $IMG?>" width="164" height="114" alt="coaching"><span title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],20)?></span></a></div>
  
					<?php
					}
					?>	
 
					</div>
					</div>
				<?php
				}
                                  }
				?>				
                     
                     
                     
                     
                         
                     </div>
             <div class="media-center-right">
                 <div class="right-ad">
                     <!----------------------------->
                     <?php
                      if(count($advertisementmedia_detail)){ 
                          ?>
                
                    <?php 
  $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
  $name=getThumbName($advertisementmedia_detail[0]['s_image'],'main'); 
  $IMG_THUMB = $IMG_THUMB_PATH . $name; ;
?>
<img src="<?=$IMG_THUMB?>" alt="" width="250" height="250" onclick="window.open('<?=$advertisement_detail[0]['s_url']?>')"/>

                     
                      <?php    
                          
                      }
                     
                      ?>
                     <!------------------------------->
<!--                     <img src="images/left-ad1.png" alt="Advertisment" width="250" height="250">-->
                 </div>         
				 
              <div class="right-ad">
			  <?php
				$query = $this->db->get_where('cg_mc_video_cat', array('id' => 6));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_cat6 =  $row->is_hidden;
                                            }
                                  if($is_hidden_cat6 == 0){
				if($video6)
				{
				?>
                  <h3 class="prelibrary-icon"><a class="article_category" href="<?php echo base_url().'watch/category/6' ?>"><?php echo $cat_name['6']?></a></h3>
				  <?php
				  foreach($video6 as $val)
				  {
				  $IMG = base_url() . 'uploads/media_center_videos/' . getThumbName($val['s_video_thumb'], 'thumb');
				  ?>
                  <div class="dev-main">
                      <div class="pic-left"><img src="<?php echo $IMG?>" alt="Library" height="104px" width="104px"></div>
                      <div class="pic-right">
                          <h4><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>" title="<?=$val['s_title']?>"><?php echo my_substr($val['s_title'],30);?></a></h4>
                          <p><?php echo my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                         	 <ul class="green-comment">
                             	<li><a href="<?= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html"?>">Liked by</a><span> (0)</span></li>
                             </ul>
                      </div>
                      <div class="clr"></div>
                  </div>
                <?php 
				}
				}
                                  }
				?> 
                  
                      <!--<div class="pic-left"><img src="images/library7.png" alt="library"></div>
                      <div class="pic-right">
                          <h4>Donec sit amet turpis dui fringilla</h4>
                          <p>Faucibus orci luctus et ultrices posuere cubilia Curae..</p>
                          <ul class="green-comment">
                             	<li><a href="javascript:void(0);">Liked by</a><span> (0)</span></li>
                             </ul>
                      </div>-->
                      <div class="clr"></div>
                  </div>
                 <!---------------------------->
                 <?php
                      if(count($advertisementmedia_detail)){ 
                          //echo 'll';
                          $j = count($advertisementmedia_detail);
                          for($i=1;$i<$j;$i++){
                               $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
  $name=getThumbName($advertisementmedia_detail[$i]['s_image'],'main'); 
  $IMG_THUMB = $IMG_THUMB_PATH . $name; ;
                          ?>
                    <div class="right-ad"><img src="<?=$IMG_THUMB?>" alt="" width="250" height="250" onclick="window.open('<?=$advertisementmedia_detail[$i]['s_url']?>')"/></div>
<!--              <div class="advertisment"><img src="images/ad2.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad3.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad4.png" alt="Advertisment" width="250" height="250"></div>-->
                      <?php 
                          }
                      
                          } ?>
                    <!---------------------------------->
<!--                  <div class="right-ad"><img src="images/left-ad2.png" alt="Advertisment" width="250" height="250"></div>
              
              <div class="right-ad"><img src="images/left-ad3.png" alt="Advertisment" width="250" height="250"></div>-->
              </div>
              
              
              
                            
          </div>
          <div class="clr"></div>
          </div>
       
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>



 <script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '200px',
		orientation: 'vertical'
	});
});
</script>

<script type="text/javascript">
$('.watchslide').bxSlider({
  pagerCustom: '#bx-pager',
   auto: true
});
</script>


<script type="text/javascript">
$(document).ready(function(){
  $('.slider4').bxSlider({
    slideWidth: 164,
    minSlides: 4,
    maxSlides: 4,
    moveSlides: 1,
    slideMargin: 24
  });
});
</script>

