<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>
<? include "media_center_nav.phtml" ?>
<!-- CONTENT SECTION -->
<script>
function goBack() {
    window.history.back()
}
</script>
<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input">
		  <form name="user_frms" id="user_frms" method="post" action="<?= base_url() . 'logged/christian_news/search_news' ?>"  onsubmit="return true;" >
		  <input type="text" name="search_keyword_val" value="<?php echo $search_keyword_val?>" placeholder="Type Keywords separated by comma">
		  <input name="" type="submit" value="Deactivate"  class="btn" style="display:none;"/>
                  
		  </form>
             
		  </div>
           <a href="javascript:void(0)" class="media-back" onclick="goBack()">Back</a>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                <h3 class="music-channel-icon"><?=$detail_content['cat_name']?></h3>
                 <h4 class="sub-text"> <?=$detail_content['s_title']?></h4>
                
                
               
               	
            <div>
                <div>
                        <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<?= $detail_content['track_id'] ?>"></iframe>
                        <div class="clear"></div>
                    </div>
           	 <div class="clear"></div>
                    
              
                    <p class="music-description"><?=nl2br(get_unformatted_string_edit($detail_content['s_desc']))?></p>
                    <div class="music-bg">
         <div class="newscomment-panel">
                <h4 id="comment-box">COMMENT ON THIS AUDIO</h4>
                
                <div id="comment-pan">
                	<div class="post-box-panel">
                        <div class="postpic"><img src="images/no-profile-pic.jpg" alt="Profile" width="74" height="74"></div>
                        <div class="posttxt">
                        	
                            <form action="" id="comment_frm" onsubmit="return false;">
							 
									<textarea id="txtarea_comment<?=$detail_content['id']?>" name="" class="txtarea01" placeholder="Add a Comment..."></textarea>
							  
									<input class="postbtn" type="submit" value="Post" name="" onclick="return comment_(<?=$detail_content['id']?>,'logged/media_center/comment_videos')">
							  
							  </form>
                        </div>
                        <div class="clear"></div>
                    </div>
              		<div id="comentList">
					<?php echo $comments?>
				</div>
                    <!--<div class="show-more"><a href="javascript:void(0);">Show more</a></div>-->
                    </div>
                </div>
                  

              
                    </div>

                </div>
                
                     </div>
             <div class="media-center-right">
                 <?php $query = $this->db->get('cg_site_settings');
                            foreach ($query->result() as $row)
                                {
                                    $client_id = $row->client_id;
                                    $api_user_id = $row->api_user_id;
                                }
                            ?>
               
            <?php
				if($cat5_article)
				{
				?>  
                  <div>
                  <h3 class="daily-devotional-icon">Daily Devotional</h3>
                  
                  <div class="player-right">
                  	<?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == 'Daily Devotional' ){
     ?>
                            
  <iframe width="100%" height="250" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                    <table width="99%" border="0" cellspacing="0" cellpadding="0" class="music-layer-list">
 						 
                      <tr>
                        <td class="no-BorderBottom"></td>
                        <td class="no-BorderBottom"><a href="<?php echo base_url()."listen-detail/".$val['id'].'/'.my_url($val['s_title']).".html" ?>"><?=$val['s_title']?></a></td>
                        <td align="right" class="no-BorderBottom"></td>
                      </tr>
                    
                    </table>
                  </div>
                  
                 
              </div>
              <?php }?>
              <?
				if($cat6_article)
				{
				?>  
              <h3 class="audio-bible-icon">Audio Bible</h3>
              
                   <div class="player-right no-BorderBottom">
                  	<a href="<?php echo base_url()."listen-detail/".$cat6_article[0]['id'].'/'.my_url($cat6_article[0]['s_title']).".html" ?>"><?=$cat6_article[0]['s_url']?></a
                    	
                    ></div>
                    <div>
                    	<p><?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == 'Audio Bible'){
     ?>
                            
  <iframe width="100%" height="250" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?></p><br>
<br>

                    </div>
                    <? }?>
                    
                    <?php
                      if(count($advertisementmedia_detail)){ 
                          //echo 'll';
                          $j = count($advertisementmedia_detail);
                          for($i=0;$i<$j;$i++){
                               $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
  $name=getThumbName($advertisementmedia_detail[$i]['s_image'],'main'); 
  $IMG_THUMB = $IMG_THUMB_PATH . $name; ;
                          ?>
                    <div class="advertisment"><img src="<?=$IMG_THUMB?>" alt="" width="250" height="250" onclick="window.open('<?=$advertisementmedia_detail[$i]['s_url']?>')"/></div>
<!--              <div class="advertisment"><img src="images/ad2.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad3.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad4.png" alt="Advertisment" width="250" height="250"></div>-->
                      <?php 
                          }
                      
                          } ?>
                    
<!--                    <div class="advertisment"><img src="images/ad1.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad2.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad3.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad4.png" alt="Advertisment" width="250" height="250"></div>-->
              </div>
              
                            
          </div>
          <div class="clr"></div>
          </div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '200px',
		orientation: 'vertical'
	});
});
</script>

