<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>
<div class="left-menu">
    <div class="menu-icon"><img src="images/menu-icon.png" alt="Menu" width="45" height="50"></div>
<div id="navigation_vert">
                <ul>
                    <li class="read">
                        <a href="" class="navlink"><span>Read</span></a>
                        <div class="dropdown" id="dropdown_four">            
                            <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="devotionals-icon">Devotionals</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>  
                    </li>
                    <li class="watch">
                        <a href="" class="navlink"><span>Watch</span></a>
                        <div class="dropdown" id="dropdown_five">            
                              <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="devotionals-icon">Devotionals</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>
                    </li>
                    
                    <li class="listen">
                        <a href="" class="navlink"><span>Listen</span></a>
                        <div class="dropdown" id="dropdown_six">            
                         
                          <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="devotionals-icon">Devotionals</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>            
                	</li>
                </ul>
            </div>
    
</div>
<!-- CONTENT SECTION -->

<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input"><input type="text" name="" value="" placeholder="Search Keywords"></div>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                <h3 class="music-channel-icon">Cogtime channel</h3>
                 <h4 class="sub-text"> Cras condimentum scelerisque arcu. Phasellus tincidunt, mauris quis mollis gra vida.</h4>
                
                
               
               	
            <div>
           	  <p class="music-description">Nam sagittis nisl vel mauris auctor, in sagittis nunc volutpat. Donec a enim augue. Pellentesque dictum a felis id facilisis. Nam sagittis nisl vel mauris auctor, in sagittis nunc volutpat. Donec a enim augue.</p>
                    
              <div class="music-bg">
                    	<div>
                            <div class="pull-left"><img src="images/music-profile1.png" alt="Music Profile"></div>
                            <div class="pull-right"><img src="images/music-player.png" alt="Music Player"></div>
                            <div class="clear"></div>
                        </div>
                        <div class="newscomment-panel">
                <h4 id="comment-box">COMMENT ON THIS ARTICLE</h4>
                
                <div id="comment-pan">
                	<div class="post-box-panel">
                        <div class="postpic"><img src="images/no-profile-pic.jpg" alt="Profile" width="74" height="74"></div>
                        <div class="posttxt">
                        	<textarea name="" cols="" rows="" class="txtarea01" placeholder="Add a Comment..."></textarea>
                            <input name="" type="button" class="postbtn" value="post">
                        </div>
                        <div class="clear"></div>
                    </div>
                    
                    <div class="comment-pan">
                    	<div class="comment-pan-left"><img src="images/profile-pic1.jpg" alt="Profile Name" width="68" height="68"></div>
                        <div class="comment-pan-right">
                        	<h5>Jon Kole</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
                            <div class="update-time">Updated: 17-Jul-2014 14:00</div>
                            <ul class="comment-count">
                            	<li><a href="javascript:void(0);">Comment</a><span></span></li>
                                <li>|</li>
                                <li><a href="javascript:void(0);">Like</a><span></span></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>
                    
                    <div class="comment-pan">
                    	<div class="comment-pan-left"><img src="images/profile-pic2.jpg" alt="Profile Name" width="68" height="68"></div>
                        <div class="comment-pan-right">
                        	<h5>Richard Paul</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
                            <div class="update-time">Updated: 17-Jul-2014 14:00</div>
                            <ul class="comment-count">
                            	<li><a href="javascript:void(0);">Comment</a><span> (2)</span></li>
                                <li>|</li>
                                <li><a href="javascript:void(0);">Like</a><span> (1)</span></li>
                            </ul>
                            <div class="clear"></div>
                            
                            <div class="comment-pan comment-reply-pan">
                    	<div class="comment-pan-left"><img src="images/profile-pic3.jpg" alt="Profile Name" width="68" height="68"></div>
                        <div class="comment-pan-right">
                        	<h5>Mad warner</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
                            <div class="update-time">Updated: 17-Jul-2014 14:00</div>
                            <ul class="comment-count">
                            	<li><a href="javascript:void(0);">Comment</a><span> (2)</span></li>
                                <li>|</li>
                                <li><a href="javascript:void(0);">Like</a><span> (1)</span></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>
                    
                    <div class="comment-pan comment-reply-pan">
                    	<div class="comment-pan-left"><img src="images/profile-pic4.jpg" alt="Profile Name" width="68" height="68"></div>
                        <div class="comment-pan-right">
                        	<h5>Ketu Don</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
                            <div class="update-time">Updated: 17-Jul-2014 14:00</div>
                            <ul class="comment-count">
                            	<li><a href="javascript:void(0);">Comment</a><span> (2)</span></li>
                                <li>|</li>
                                <li><a href="javascript:void(0);">Like</a><span> (1)</span></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>
                        </div>
                    </div>
                    
               <div class="comment-pan">
                    	<div class="comment-pan-left"><img src="images/profile-pic1.jpg" alt="Profile Name" width="68" height="68"></div>
                        <div class="comment-pan-right">
                        	<h5>Parker</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
                            <div class="update-time">Updated: 17-Jul-2014 14:00</div>
                            <ul class="comment-count">
                            	<li><a href="javascript:void(0);">Comment</a><span></span></li>
                                <li>|</li>
                                <li><a href="javascript:void(0);">Like</a><span></span></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                    </div>     
                    
                    <div class="show-more"><a href="javascript:void(0);">Show more</a></div>
                    </div>
                </div>
                  

              
                    </div>

                </div>
                
                
                
                
                
                  
                  
                  
                     
                     
                     
                     
                     
                     

                     
                     
                         
                     </div>
             <div class="media-center-right">
               
              <div>
                  <h3 class="daily-devotional-icon">Daily Devotional</h3>
                  
                  <div class="player-right">
                  	<img src="images/tips-player2.png" alt="Player">
                    <table width="99%" border="0" cellspacing="0" cellpadding="0" class="music-layer-list">
  <tr>
    <td><img src="images/music-profile2.png" alt="Music Profile"></td>
    <td><a href="javascript:void(0);">Audio Byte- Interview By Ted Ex...</a></td>
    <td align="right"><a href="javascript:void(0);"><img src="images/play-music.png" alt="Play Music"><span> 6</span></a></td>
  </tr>
  <tr>
    <td><img src="images/music-profile2.png" alt="Music Profile"></td>
    <td><a href="javascript:void(0);">Audio Byte- Interview By Ted Ex...</a></td>
    <td align="right"><a href="javascript:void(0);"><img src="images/play-music.png" alt="Play Music"><span> 5</span></a></td>
  </tr>
  <tr>
    <td><img src="images/music-profile2.png" alt="Music Profile"></td>
    <td><a href="javascript:void(0);">Audio Byte- Interview By Ted Ex...</a></td>
    <td align="right"><a href="javascript:void(0);"><img src="images/play-music.png" alt="Play Music"><span> 4</span></a></td>
  </tr>
  <tr>
    <td><img src="images/music-profile2.png" alt="Music Profile"></td>
    <td><a href="javascript:void(0);">Audio Byte- Interview By Ted Ex...</a></td>
    <td align="right"><a href="javascript:void(0);"><img src="images/play-music.png" alt="Play Music"><span> 3</span></a></td>
  </tr>
  <tr>
    <td class="no-BorderBottom"><img src="images/music-profile2.png" alt="Music Profile"></td>
    <td class="no-BorderBottom"><a href="javascript:void(0);">Audio Byte- Interview By Ted Ex...</a></td>
    <td align="right" class="no-BorderBottom"><a href="javascript:void(0);"><img src="images/play-music.png" alt="Play Music"><span> 2</span></a></td>
  </tr>

</table>
                  </div>
                  
                  
                  
                  
                  
                  
              </div>
              
              
              <h3 class="audio-bible-icon">Audio Bible</h3>
              
                   <div class="player-right no-BorderBottom">
                  	<img src="images/tips-player2.png" alt="Player">
                    	
                    </div>
                    <div>
                    	<p>Mauris tristique libero at mattis lacinia. Nam sagittis nisl vel mauris auctor, in sagittis nunc volutpat. Donec a enim augue. Pellentesque dictum a felis id facilisis.</p>
                        <p>Nam sagittis nisl vel mauris auctor, in sagittis nunc volutpat. Donec a enim augue. Pellentesque dictum a felis id facilisis.Nam sagittis nisl vel mauris auctor, in sagittis nunc volutpat. Donec a enim augue.</p><br>
<br>

                    </div>
                    <div class="advertisment"><img src="images/ad1.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad2.png" alt="Advertisment" width="250" height="250"></div>
             
              </div>
              
                            
          </div>
          <div class="clr"></div>
          </div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '336px',
		orientation: 'vertical'
	});
});
</script>

