<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>

<!-- CONTENT SECTION -->

<?php $query = $this->db->get('cg_site_settings');
                            foreach ($query->result() as $row)
                                {
                                    $client_id = $row->client_id;
                                    $api_user_id = $row->api_user_id;
                                }
                            ?>


    <? include "media_center_nav.phtml" ?>

<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input">
		  <form name="user_frms" id="user_frms" method="post" action="<?= base_url() . 'logged/christian_news/search_news' ?>"  onsubmit="return true;" >
		  <input type="text" name="search_keyword_val" value="<?php echo $search_keyword_val?>" placeholder="Type Keywords separated by comma">
		  <input name="" type="submit" value="Deactivate"  class="btn" style="display:none;"/>
		  </form>
		  </div>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                
       
        	 <?
			if($featured)
			{
                       
			?>
			<h3 class="biblerap-icon">FEATURED</h3>
                <div class="video-slide">
                                                          
                	<ul class="watchslide">
                              <?php 
                                 $i = 0;
                              foreach($featured as $val) 
					{
                                   if($i==5){ break;}
                                   ?>
                           
                                                <li>
                                                <h4 class="video-txt" title="<?=my_substr(strip_tags(get_unformatted_string_edit( $val['s_title'])),50) ?>"><?=my_substr(strip_tags(get_unformatted_string_edit( $val['s_title'])),30) ?></h4>
                                                <iframe width="100%" height="175" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<?= $val['track_id'] ?>"></iframe>
												</li>  
                                        <?php 
                                        $i++;
                                        } ?>
                           
<!--                                                <li>
                                                <h4 class="video-txt" title="Pastor Joseph Prince">Pastor Joseph Prince</h4>
												<object  width="728" height="360" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/MES5ZDn4RIk&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/MES5ZDn4RIk&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="728" height="360"></embed></object></li>  
  
                           

                                                <li>
                                                <h4 class="video-txt" title="T D Jakes - Defying the Urge to Quit">T D Jakes - Defying the Urge to Quit</h4>
												<object  width="728" height="360" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/aDUrAOr0RCo&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/aDUrAOr0RCo&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="728" height="360"></embed></object></li>  
  
                           
                                                <li>
                                                <h4 class="video-txt" title="Joel Osteen - One More Time">Joel Osteen - One More Time</h4>
												<object  width="728" height="360" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/iJiu9q_1X8w&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/iJiu9q_1X8w&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="728" height="360"></embed></object></li>  
  
                           
                                                <li>
                                                <h4 class="video-txt" title="2014 Your Year of Gods Annointing - Benny Hinn">2014 Your Year of Gods Annointing - Benny Hinn</h4>
												<object  width="728" height="360" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/KQL7SwKxsIo&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/KQL7SwKxsIo&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="728" height="360"></embed></object></li> -->
                                              
          
          </ul>
                                        <div id="bx-pager">
                                            
                                             <?php 
                                             $i = 0;
                                             foreach($featured as $val) 
					{
                                                  if($i==5){ break;}
                                   ?>
    <a data-slide-index="<?=$i; ?>" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
<iframe width="100%" height="102" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<?= $val['track_id'] ?>"></iframe>
    	<span title="<?=my_substr(strip_tags(get_unformatted_string_edit( $val['s_title'])),45) ?>"><?=my_substr(strip_tags(get_unformatted_string_edit( $val['s_title'])),45) ?></span></a>
                                        <?php 
                                        
                                        $i++;
                                        } ?>
<!--      <a data-slide-index="1" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
    	<object  width="127" height="102" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/MES5ZDn4RIk&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/MES5ZDn4RIk&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="127" height="102"></embed></object><span title="Pastor Joseph Prince">Pastor Joseph Prince</span></a>

      <a data-slide-index="2" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
    	<object  width="127" height="102" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/aDUrAOr0RCo&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/aDUrAOr0RCo&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="127" height="102"></embed></object><span title="T D Jakes - Defying the Urge to Quit">T D Jakes - Defying the Urge to Quit</span></a>

      <a data-slide-index="3" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
    	<object  width="127" height="102" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/iJiu9q_1X8w&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/iJiu9q_1X8w&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="127" height="102"></embed></object><span title="Joel Osteen - One More Time">Joel Osteen - One More Time</span></a>

      <a data-slide-index="4" href="">
<div class="video-mask"><div class="video-top-arrow"></div></div>
    	<object  width="127" height="102" ><param name="wmode" value="opaque" /><param name="movie" value="http://www.youtube.com/v/KQL7SwKxsIo&hl=en_US&fs=1&showsearch=0&showinfo=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/KQL7SwKxsIo&hl=en_US&fs=1&showsearch=0&showinfo=0&rel=0" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" allowfullscreen="true" width="127" height="102"></embed></object><span title="2014 Your Year of Gods Annointing - Benny Hinn">2014 Your Year of Gods Annointing - Benn...</span></a>-->
 
  </div>
                
                </div>
                 <? 
				 }
                                  $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 1));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat1 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat1 == 0){ 
				 
				if($cat1_article)
				{
				?>
                <h3 class="music-channel-icon"><a class="article_category" href="<?php echo base_url().'listen/category/1' ?>"><?php echo $cat_name['1']?></a><!--<a href="<?php echo base_url().'christian_news/category/1' ?>">View all</a>--></h3>
               	
            <div>
           	  
                    
              <div class="music-bg">
                    	<div>
                            
                            <?php
                           // echo $cat_name['1'];
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['1'])){
     ?>
                            
  <iframe width="100%" height="360" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                            <div class="clear"></div>
                        </div>
                        
                

                  <!--<div><img src="images/bottom-pic.png" alt="Music"></div>-->
                    </div>

                </div>
                
                
                <? } 
                
                }
                ?>
                <!--cat1 end-->
                
             	
                
                <div class="audio-part-main">
                    <?
                    /**************************************/
                     $query1 = $this->db->get_where('cg_mc_audio_cat', array('id' => 3));
                                        foreach ($query1->result() as $row)
                                            {
                                               $is_hidden_audio_cat_3 =  $row->is_hidden;
                                            }
                    /**************************************/
                
                $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 2));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat2 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat2 == 0){ 
				
                
                
				if($cat2_article)
				{
				?>
                        <div class="pull-left <?php if($is_hidden_audio_cat_3 == 1){ echo ' view_full';} ?>">
                    	 <h3 class="audiobook-icon"><a class="article_category" href="<?php echo base_url().'listen/category/2' ?>"><?php echo $cat_name['2']?></a></h3>
                         <div class="player-book">
                         	<?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['2'])){
     ?>
                            
  <iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                         
                        
                         </div>
                         
                    </div>
  <? } 
  
  }
  ?>  
  <!--cat 2 end-->
  <?
				
  $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 3));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat3 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat3 == 0){ 
  
  
  
                          if($cat3_article)
				{
				?>                
                    <div class="pull-right <?php if($is_hidden_audio_cat2 == 1){ echo ' view_full';} ?>">
                    	<h3 class="musicplay-icon"><a class="article_category" href="<?php echo base_url().'listen/category/3' ?>"><?php echo $cat_name['3']?></a></h3>
                        
                        
                        <div class="player-book">
                         	 <?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['3'])){
     ?>
                            
  <iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                            
                         </div>
                    </div>
                                <? }
                
                }
                ?>
                	<div class="clear"></div>
                </div>
                
                <!--cat 3 end-->
                 <?
				
                 $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 4));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat4 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat4 == 0){ 
                 
                 
                       if($cat4_article)
				{
				?>  
                
                  <h3 class="buisnesstips-icon"><a class="article_category" href="<?php echo base_url().'listen/category/4' ?>"><?php echo $cat_name['4']?></a><a href="<?php echo base_url()?>'listen/category/4">View all</a></h3>
                  
                  <div>
           	  <p class="music-description"<?=my_substr(strip_tags(get_unformatted_string_edit($cat4_article[0]['s_desc'])),80)?></p>
                    
              <div class="music-bg">
                    	<div>
                        <?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['4'])){
     ?>
                            
  <iframe width="100%" height="235" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                     
                           
                            <div class="clear"></div>
                        </div>
                        
                

                 <!-- <div><img src="images/bottom-pic.png" alt="Music"></div>-->
				  
                    </div>

                </div>
                  <? }
                  
                  }
                  
                  ?> 
                  <!--cat 4 end-->
         </div> 
                     
              <div class="media-center-right">
               
            <?
                       $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 5));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat5 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat5 == 0){ 
            
            
            
				if($cat5_article)
				{
				?>  
                  <div>
                  <h3 class="daily-devotional-icon"><a class="article_category" href="<?php echo base_url().'listen/category/5' ?>"><?php echo $cat_name['5']?></a></h3>
                  
                  <div class="player-right">
                  	<?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['5'])){
     ?>
                            
  <iframe width="100%" height="250" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                   
                    
                  </div>
                  
                 
              </div>
              <? }
              }
              
              ?>
              <!--cat 5 end-->
              <?
                          $query = $this->db->get_where('cg_mc_audio_cat', array('id' => 6));
                                        foreach ($query->result() as $row)
                                            {
                                               $is_hidden_audio_cat6 =  $row->is_hidden;
                                            }
                                  if($is_hidden_audio_cat6 == 0){ 
              
              
              
				if($cat6_article)
				{
				?>  
              <h3 class="audio-bible-icon"><a class="article_category" href="<?php echo base_url().'listen/category/6' ?>"><?php echo $cat_name['6']?></a></h3>
              
                   <div class="player-right no-BorderBottom">
                  	<?php
                         	 $tracks_json = file_get_contents('http://api.soundcloud.com/users/'.$api_user_id.'/playlists.json?client_id='.$client_id.'');
$tracks = json_decode($tracks_json);
 //$playlist_id = $tracks->id;
// echo '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F50167193"></iframe>';

//print_r($tracks);

foreach ($tracks as $track){
  $trackID = $track->id;
  $title = $track->title;
 if($title == trim($cat_name['6'])){
     ?>
                            
  <iframe width="100%" height="250" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<?php echo $trackID;?>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>                           
                            <?php
      

 }

 }?>
                    	
                    </div>
                    <div>
                    	
<br>

                    </div>
                    <? }
                    
                    
                    }
                    ?>
                    <!-- cat 6 end-->
                    <?php
                      if(count($advertisementmedia_detail)){ 
                          //echo 'll';
                          $j = count($advertisementmedia_detail);
                          for($i=0;$i<$j;$i++){
                               $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
  $name=getThumbName($advertisementmedia_detail[$i]['s_image'],'main'); 
  $IMG_THUMB = $IMG_THUMB_PATH . $name; ;
                          ?>
                    <div class="advertisment"><img src="<?=$IMG_THUMB?>" alt="" width="250" height="250" onclick="window.open('<?=$advertisementmedia_detail[$i]['s_url']?>')"/></div>

                      <?php 
                          }
                      
                          } ?>
                   
<!--                    <div class="advertisment"><img src="images/ad1.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad2.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad3.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad4.png" alt="Advertisment" width="250" height="250"></div>-->
             
              </div>
                            
          
          <div class="clr"></div>
          </div>
       
      </div>
      <div class="clr"></div>
</div>


			  
			  
<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script>
$(window).load(function() {
 $('.blueberry').blueberry();
});
</script>
 <script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '200px',
		orientation: 'vertical'
	});
});
</script>

<script type="text/javascript">
$('.watchslide').bxSlider({
  pagerCustom: '#bx-pager',
   auto: true
});
</script>