<?php
	if( ($this->session->userdata('loggedin') !='' || $this->session->userdata('loggedin')!=false ) && $this->session->userdata('is_admin') != 1){
		
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
		
		
   <?php  }
     else{
         
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
  }?>
<div class="clr"></div>

<!-- CONTENT SECTION -->

<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input"><input type="text" name="" value="" placeholder="Search Keywords"></div>
	  <div class="clr"></div>
           </div>
          
          <div class="media-center-banner">
              <!-- Place somewhere in the <body> of your page -->
<div id="slider" class="flexslider">
  <ul class="slides">
  
	<?php 
        if(count($is_feature_home_news)){
	foreach($is_feature_home_news as $val) 
	{
		$IMG = base_url() . 'uploads/media_center_article_featured_home/' . getThumbName($val['s_image_featured'], 'main');
		
					
		//$detail_url	= base_url().$val['id']."/".$article[0]['cat_name']."/watch-detail/".my_url($val['s_title']).".html";
		$detail_url	= base_url().$val['id']."/".my_url($val['cat_name'])."/christian-news-details/".my_url($val['s_title']).".html";
		
	?>
    <li>
	<div style="background:url(<?=$IMG?>) center; width:999px; height:408px;">&nbsp;
   </div> 
	  <div class="caption-text">
          <h3>Featured Article </h3>
          <a href="<?php echo $detail_url;?>"><h4><?=$val['s_title']?></h4></a>
          <a href="<?php echo $detail_url;?>"><p><?=nl2br(get_unformatted_string_edit(substr($val['s_desc'],0,200)))?></p></a>
          
      </div>
    </li>
	<?php 
	} 
        }
	?>
	
	
	<?php 
        if(count($is_feature_home_video)){
	foreach($is_feature_home_video as $val) 
	{
		$IMG = base_url() . 'uploads/media_center_video_featured_home/' . getThumbName($val['s_image_featured'], 'main');
		$detail_url	= base_url().$val['id']."/".my_url($val['cat_name'])."/watch-detail/".my_url($val['s_title']).".html";
	
//                        $this->load->library('embed_video');
			$config['zend_library_path'] = APPPATH ."libraries/Zend/";
			$config['video_url'] =  $val['s_url'];
			$this->embed_video->initialize($config);
                        $this->embed_video->prepare();
			$html = $this->embed_video->get_player('999','408');
                //style="background:url(<?=$IMG?) center; width:999px; height:408px;"
			
                ?>
	
    <li>
      <div>&nbsp;
          <?php echo $html['html']; ?>
   	  </div> 
      <div class="caption-text">
         <h3>Featured Watch </h3>
          <a href="<?php echo $detail_url;?>"><h4><?=$val['s_title']?></h4></a>
          <a href="<?php echo $detail_url;?>"><p><?=nl2br(get_unformatted_string_edit(substr($val['s_desc'],0,200)))?></p></a>
          
      </div>
	  
    </li>
	
	<?php } 
        }?>
	
	<?php 
        if(count($is_feature_home_listen)){
	foreach($is_feature_home_listen as $val) 
	{
           // pr($is_feature_home_listen);
		//$IMG = base_url() . 'uploads/media_center_listen_featured_home/' . getThumbName($val['s_image_featured'], 'main');
		$detail_url = base_url()."listen-detail/".my_url($val['id']).'/'.my_url($val['s_title']).".html";
	?>
	
    <li>
      <div style="">&nbsp;
          <iframe width="100%" height="408" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<?= $val['track_id'] ?>"></iframe>
   	  </div> 
      <div class="caption-text">
          <h3>Featured Listen </h3>
          <a href="<?php echo $detail_url;?>"><h4><?=$val['s_title']?></h4></a>
          <a href="<?php echo $detail_url;?>"><p><?=nl2br(get_unformatted_string_edit(substr($val['s_desc'],0,200)))?></p></a>
	  </div>
    </li>
 
 	<?php
        }
        
        } ?>
 
    <!-- items mirrored twice, total of 12 -->
  </ul>
</div>
<div id="carousel-mdia" class="flexslider">
  <ul class="slides">
      <li id="rd">
        <span class="read-media">&nbsp;</span>
      <h5 onclick="window.location='<?=base_url().'christian-news/read.html'?>';" style="cursor:pointer;">Read</h5>
      <p><?php 
      $query = $this->db->get('cg_media_center_landing_page_text');
      foreach ($query->result() as $row)
        {
            echo $row->read;
        }
      ?></p>
    </li>
    <li id="vd">
      <span class="watch-media">&nbsp;</span>
      <h5 onclick="window.location='<?=base_url().'watch.html'?>';" style="cursor:pointer;">watch</h5>
      <p>
          <?php 
      $query = $this->db->get('cg_media_center_landing_page_text');
      foreach ($query->result() as $row)
        {
            echo $row->watch;
        }
      ?>
      </p>
    </li>
    <li id="ln" >
      <span class="listen-media">&nbsp;</span>
      <h5 onclick="window.location='<?=base_url().'listen.html'?>';" style="cursor:pointer;">listen</h5>
      <p>
           <?php 
      $query = $this->db->get('cg_media_center_landing_page_text');
      foreach ($query->result() as $row)
        {
            echo $row->listen;
        }
      ?>
          
      </p>
    </li>
    <!-- items mirrored twice, total of 12 -->
  </ul>
</div>
              
          </div>
          <div class="ad-list" align="center">
              <a href="javascript:void(0);"><?php
                      if(count($advertisementmedia_detail)){ 
                          ?>
                 
                    <?php 
  $IMG_THUMB_PATH = base_url() ."uploads/media_center_advertisement/";
  $name=getThumbName($advertisementmedia_detail[0]['s_image'],'main'); 
  $IMG_THUMB = $IMG_THUMB_PATH . $name; ;
?>
<img src="<?=$IMG_THUMB?>" alt="" width="970" height="250" onclick="window.open('<?=$advertisement_detail[0]['s_url']?>')"/>

                     
                      <?php    
                          
                      }
                     
                      ?></a>
              
          
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>



 <script type="text/javascript">
 $(window).load(function() {
  // The slider being synced must be initialized first
  $('#carousel-mdia').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 238,
    itemMargin: 0,
    asNavFor: '#slider'
  });
 
  $('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel-mdia"
  });
});
 </script>
 
 <?php
 if(count($is_feature_home_news) && count($is_feature_home_video) && count($is_feature_home_listen)){
 
 ?>
 <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#rd').addClass("flex-active-slide"); }, 3000);
    
   
 })
 
 </script>


<?php
 }  else if(count($is_feature_home_listen) && count($is_feature_home_video)){
     
 
?>
 <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#vd').addClass("flex-active-slide"); }, 3000);
    
    setTimeout(function(){ $('#rd').removeClass("flex-active-slide"); }, 3000);
 })
 
 </script>
 
 <?php
 } else if(count($is_feature_home_news) && count($is_feature_home_listen)){
     
 
 ?>
  <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#rd').addClass("flex-active-slide"); }, 3000);
    
   
 })
 
 </script>
 
 <?php } else if(count($is_feature_home_news)  && count($is_feature_home_video) ){ ?>
  <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#rd').addClass("flex-active-slide"); }, 3000);
     //setTimeout(function(){ $('#rd').removeClass("flex-active-slide"); }, 3000);
   
 })
 
 </script>
 <?php } else if(count($is_feature_home_listen)){?>
  <script type="text/javascript">
 $(document).ready(function(){
    // alert('ol')
    setTimeout(function(){ $('#ln').addClass("flex-active-slide"); }, 8000);
     setTimeout(function(){ $('#rd').removeClass("flex-active-slide"); }, 8000);
   
 })
 
 </script>
 
 <?php }else if(count($is_feature_home_video)){ ?>
 
  <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#vd').addClass("flex-active-slide"); }, 3000);
     setTimeout(function(){ $('#rd').removeClass("flex-active-slide"); }, 3000);
   
 })
 
 </script>
 
 <?php }else if(count($is_feature_home_news)){ ?>
  <script type="text/javascript">
 $(document).ready(function(){
    setTimeout(function(){ $('#rd').addClass("flex-active-slide"); }, 3000);
    
   
 })
 
 </script>
 <?php } ?>




 

