<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>
<div class="left-menu">
    <div class="menu-icon"><img src="images/menu-icon.png" alt="Menu" width="45" height="50"></div>

<div id="navigation_vert">
                <ul>
                    <li class="read">
                        <a href="" class="navlink"><span>Read</span></a>
                        <div class="dropdown" id="dropdown_four">            
                            <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="librarys-icon">librarys</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>  
                    </li>
                    <li class="watch">
                        <a href="" class="navlink"><span>Watch</span></a>
                        <div class="dropdown" id="dropdown_five">            
                              <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="librarys-icon">librarys</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>
                    </li>
                    
                    <li class="listen">
                        <a href="" class="navlink"><span>Listen</span></a>
                        <div class="dropdown" id="dropdown_six">            
                         
                          <ul class="menu-item">
                                <li><a href="javascript:void(0);" class="news-icon">News</a></li>
                                <li><a href="javascript:void(0);" class="life-icon">This Life</a></li>
                                <li><a href="javascript:void(0);" class="society-icon">Our Society</a></li>
                                <li><a href="javascript:void(0);" class="talk-icon">Let’s talk</a></li>
                                <li><a href="javascript:void(0);" class="shout-icon">Your Shout/The Voice</a></li>
                                <li><a href="javascript:void(0);" class="story-icon">Your Story</a></li>
                                <li><a href="javascript:void(0);" class="mission-icon">Mission Possible</a></li>
                                <li><a href="javascript:void(0);" class="faithbook-icon">Faithbook</a></li>
                                <li><a href="javascript:void(0);" class="book-icon">Book Reviews</a></li>
                                <li><a href="javascript:void(0);" class="blog-icon">Blogs</a></li>
                                <li><a href="javascript:void(0);" class="librarys-icon">librarys</a></li>
                                <li><a href="javascript:void(0);" class="grow-icon">G.R.O.W</a></li>
                            </ul>
                        </div>            
                	</li>
                </ul>
            </div>
    
</div>

<!-- CONTENT SECTION -->

<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input"><input type="text" name="" value="" placeholder="Search Keywords"></div>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                <h3 class="prelibrary-icon">preach libary</h3>
                
              <div class="textsearch-pan">
                    	<h4><a href="javavsript:void(0);">Curabitur libero purus, scelerisque vel arcu id, imperdiet blandit velit. Integer tempus neque.</a></h4>
                        <p>Praesent tempus, risus semper malesuada porta, purus velit mollis elit, a mollis odio odio et eros. Morbi nunc magna, laoreet a iaculis eget, pellentesque nec mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et lacus augue. Ut tortor augue, rutrum ac nibh ut, convallis molestie est. Etiam non posuere mauris, id elementum libero. Vivamus faucibus purus et elit porta, nec auctor risus sagittis.</p>
                        <div class="blog-links">
                        	<div class="blog-date">May 12, 2014 by Jon kol</div>
                            <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);">14 Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);">39 Views</a></li>
                            </ul>
                         </div>
                         <div class="clear"></div>
                        </div>
                        	<ul class="library-tag-list">
                <li>Tags</li>
                <li><a href="javascript:void(0);">Lorem,</a></li>
                <li><a href="javascript:void(0);">ipsum,</a></li>
                <li><a href="javascript:void(0);">Dolor,</a></li>
                <li><a href="javascript:void(0);">Sitamet,</a></li>
                <li><a href="javascript:void(0);">Consectetur,</a></li>
                <li><a href="javascript:void(0);">Adipiscing,</a></li>
                <li><a href="javascript:void(0);">Elit,</a></li>
                <li><a href="javascript:void(0);">Ultrices</a></li>
                </ul>
                <div class="clear"></div>
                    </div>
              
              
              <div class="textsearch-pan">
                    	<h4><a href="javavsript:void(0);">Interdum et malesuada fames ac ante ipsum primis in faucibus vestibulum et lacus augue</a></h4>
                        <p>Praesent tempus, risus semper malesuada porta, purus velit mollis elit, a mollis odio odio et eros. Morbi nunc magna, laoreet a iaculis eget, pellentesque nec mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et lacus augue. Ut tortor augue, rutrum ac nibh ut, convallis molestie est. Etiam non posuere mauris, id elementum libero. Vivamus faucibus purus et elit porta, nec auctor risus sagittis.</p>
                        <div class="blog-links">
                        	<div class="blog-date">May 12, 2014 by Jon kol</div>
                            <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);">14 Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);">39 Views</a></li>
                            </ul>
                         </div>
                         <div class="clear"></div>
                        </div>
                        	<ul class="library-tag-list">
                <li>Tags</li>
                <li><a href="javascript:void(0);">Lorem,</a></li>
                <li><a href="javascript:void(0);">ipsum,</a></li>
                <li><a href="javascript:void(0);">Dolor,</a></li>
                <li><a href="javascript:void(0);">Sitamet,</a></li>
                <li><a href="javascript:void(0);">Consectetur,</a></li>
                <li><a href="javascript:void(0);">Adipiscing,</a></li>
                <li><a href="javascript:void(0);">Elit,</a></li>
                <li><a href="javascript:void(0);">Ultrices</a></li>
                </ul>
                <div class="clear"></div>
                    </div>
                    
                    
                    <div class="textsearch-pan">
                    	<h4><a href="javavsript:void(0);">Morbi nunc magna, laoreet a iaculis eget, pellentesque nec mi. Interdum et malesuada fames ac ante ipsum primis in faucibus.</a></h4>
                        <p>Praesent tempus, risus semper malesuada porta, purus velit mollis elit, a mollis odio odio et eros. Morbi nunc magna, laoreet a iaculis eget, pellentesque nec mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et lacus augue. Ut tortor augue, rutrum ac nibh ut, convallis molestie est. Etiam non posuere mauris, id elementum libero. Vivamus faucibus purus et elit porta, nec auctor risus sagittis.</p>
                        <div class="blog-links">
                        	<div class="blog-date">May 12, 2014 by Jon kol</div>
                            <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);">14 Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);">39 Views</a></li>
                            </ul>
                         </div>
                         <div class="clear"></div>
                        </div>
                        	<ul class="library-tag-list">
                <li>Tags</li>
                <li><a href="javascript:void(0);">Lorem,</a></li>
                <li><a href="javascript:void(0);">ipsum,</a></li>
                <li><a href="javascript:void(0);">Dolor,</a></li>
                <li><a href="javascript:void(0);">Sitamet,</a></li>
                <li><a href="javascript:void(0);">Consectetur,</a></li>
                <li><a href="javascript:void(0);">Adipiscing,</a></li>
                <li><a href="javascript:void(0);">Elit,</a></li>
                <li><a href="javascript:void(0);">Ultrices</a></li>
                </ul>
                <div class="clear"></div>
                    </div>
                    
                    
                    <div class="textsearch-pan no-BorderBottom">
                    	<h4><a href="javavsript:void(0);">Curabitur libero purus, scelerisque vel arcu id, imperdiet blandit velit. Integer tempus neque.</a></h4>
                        <p>Praesent tempus, risus semper malesuada porta, purus velit mollis elit, a mollis odio odio et eros. Morbi nunc magna, laoreet a iaculis eget, pellentesque nec mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et lacus augue. Ut tortor augue, rutrum ac nibh ut, convallis molestie est. Etiam non posuere mauris, id elementum libero. Vivamus faucibus purus et elit porta, nec auctor risus sagittis.</p>
                        <div class="blog-links">
                        	<div class="blog-date">May 12, 2014 by Jon kol</div>
                            <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);">14 Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);">39 Views</a></li>
                            </ul>
                         </div>
                         <div class="clear"></div>
                        </div>
                        	<ul class="library-tag-list">
                <li>Tags</li>
                <li><a href="javascript:void(0);">Lorem,</a></li>
                <li><a href="javascript:void(0);">ipsum,</a></li>
                <li><a href="javascript:void(0);">Dolor,</a></li>
                <li><a href="javascript:void(0);">Sitamet,</a></li>
                <li><a href="javascript:void(0);">Consectetur,</a></li>
                <li><a href="javascript:void(0);">Adipiscing,</a></li>
                <li><a href="javascript:void(0);">Elit,</a></li>
                <li><a href="javascript:void(0);">Ultrices</a></li>
                </ul>
                <div class="clear"></div>
                    </div>
                    
                    
                    <div class="show-more"><a href="javascript:void(0);">Show More</a></div>
                
              	
                
                
              
              
              
              
                
                
				
                
                     
                     
                     
                         
                     </div>
             <div class="media-center-right">
              <div class="advertisment"><img src="images/ad5.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad6.png" alt="Advertisment" width="250" height="250"></div>
              <div class="advertisment"><img src="images/ad7.png" alt="Advertisment" width="250" height="250"></div>
          </div>
          <div class="clr"></div>
          </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '200px',
		orientation: 'vertical'
	});
});
</script>