<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>

<!-- CONTENT SECTION -->




    <? include "media_center_nav.phtml" ?>

<div id="content_section">
      <div id="container">
          <div class="top-page-heading">
          <h2 class="landing-title">Media center</h2>
          <div class="landing-input"><input type="text" name="" value="" placeholder="Search Keywords"></div>
	  <div class="clr"></div>
           </div>
          <div class="media-center-left">
               
                <h3 class="featured-heading">FEATURED</h3>
                <div class="read-slide">
                    <div id="ei-slider" class="ei-slider">
                    <?
                    if($featured)
					{
					?>
                    <ul class="ei-slider-large">
                    	<? foreach($featured as $val) 
						{
						$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'mid');
						?>
						<li>
                            <img src="<?=$IMG?>" alt="image06"/>
                            <div class="ei-title">
                                <h2><?=$val['s_title']?></h2>
                                
                            </div>
                        </li>
                        <? } ?>
                    </ul><!-- ei-slider-large -->
                    
                    <ul class="ei-slider-thumbs">
					<? 
						$i = 0;
						foreach($featured as $val) 
						{
					
					?>
                        <li class="<?php echo ($i==0)?'ei-slider-element':''?>"><a href="javascript:void(0)"></a></li>
					<? 
						$i++;
						} 
					?>	
                    </ul><!-- ei-slider-thumbs -->
					<? 
					
					} 
					?>
                </div><!-- ei-slider -->
                    
                </div>
                 <?
				if($cat1_article)
				{
				?>
                <h3 class="story-heading"><?php echo $cat_name['1']?><a href="<?php echo base_url().'christian_news/category/1' ?>">View all</a></h3>
                <div class="panel-main">
                    <div class="panel-left">
                    <? $IMG = base_url() . 'uploads/media_center_article/' . getThumbName($cat1_article[0]['s_image'], 'mid' )?>
                        <div><img src="<?=$IMG?>" alt="Story" ></div>
                        <h4><?=$cat1_article[0]['s_title']?></h4>
                        <p><?=my_substr(strip_tags(get_unformatted_string_edit($cat1_article[0]['s_desc'])),80)?></p>
                    
                    </div>
					
                    <div class="panel-right">
					
                    <? 
					$i=0;
					foreach($cat1_article as $val) 
					{	
						$i++;
						if($i == 1)
							continue;
						
							$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'mid');
							?>
							<div class="story-panel">
								<h4><?=$val['s_title']?></h4>
								<div class="story-thumb">
									<div class="pic"><img src="<?=$IMG?>" alt="Story" width="98" height="75"></div>
									<p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),120)?></p>
									<div class="clr"></div>
								</div>                           
							</div>
						<? 
						
					 }
					 ?>
					 </div>
                    <div class="clr"></div>
                </div>
                <? } ?>
				
                <?
				
				if($cat2_article)
				{
				$i=0;
				?>
                  <h3 class="blog-icon"><?php echo $cat_name['2']?><a href="<?php echo base_url().'christian_news/category/2' ?>">View all</a></h3>
                  
                  <div class="panel-main">
                    <div class="panel-left">
                    <? $IMG = base_url() . 'uploads/media_center_article/' . getThumbName($cat2_article[0]['s_image'], 'mid' )?>
                        <div><img src="<?=$IMG?>" alt="Story" width="348" height="195"></div>
                        <h4><?=$cat2_article[0]['s_title']?></h4>
                        <div class="blog-date">May 12, 2014 by Jon kol</div>         
                        <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);"><?=$total_comments?> Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);"><?=$i_view_count?> Views</a></li>
                            </ul>
                         </div>
                       <p><?=my_substr(strip_tags(get_unformatted_string_edit($cat2_article[0]['s_desc'])),80)?></p>
                    
                    </div>
                    <div class="panel-right">
                     <? foreach($cat2_article as $val) 
						{
						$i++;
						if($i == 1)
							continue;
						$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'thumb');
						?>
                        <div class="story-panel">
                            <h4><?=$val['s_title']?></h4>
                            <div class="story-thumb">
                                <div class="pic"><img src="<?=$IMG?>" alt="Story"></div>
                                <div class="blog-date">May 12, 2014 by Jon kol</div>
                       
                        <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);"><?=$total_comments?> Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);"><?=$i_view_count?> Views</a></li>
                            </ul>
                         </div>
                                <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                                <div class="clr"></div>
                            </div>                           
                        </div>
                       <? } ?>
                    </div>
                    <div class="clr"></div>
                </div>
               <? } ?>   
               
			   
			   
			   
                     <?
					if($cat3_article)
					{
					?>
					<h3 class="mission-icon"><?php echo $cat_name['3']?><a href="<?php echo base_url().'christian_news/category/3' ?>">View all</a></h3>
                     <? foreach($cat3_article as $val) 
						{
						$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'thumb_1');
						?>
                     <div class="mission-panel">
                         <div class="mission-left">
                             <img src="<?=$IMG?>" alt="Mission Possible">
                         </div>
                         <div class="mission-right">
                              <h4><?=$val['s_title']?></h4>
                                <div class="blog-date">May 12, 2014 by Jon kol</div>         
                        <div class="blog-quick-list">
                            <ul>
                                <li class="blog-comment"><a href="javascript:void(0);"><?=$val['total_comments']?> Comments</a></li>
                                <li class="blog-view"><a href="javascript:void(0);"><?=$val['i_view_count']?> Views</a></li>
                            </ul>
                         </div>
                                <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                         </div>
                         <div class="clr"></div>                         
                     </div>
                     <? }
					 } ?>
                      
                    <?
					if($cat4_article)
					{
					$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($cat4_article[0]['s_image'], 'smallthumb');
					$i=0;
					?>
                     <div class="faith-part">
                    
                         <div class="faith-left">
                             <h3 class="faithbook-icon"><?php echo $cat_name['4']?></h3>
                             <div class="part-pic">
                                 <img src="<?=$IMG?>" alt="Faithbook">
                                 <span><?=my_substr(strip_tags(get_unformatted_string_edit($cat4_article[0]['s_title'])),30)?></span>
                            </div>
                             <div class="clr"></div>
                             <ul class="faith-list">
                                <? 
								foreach($cat4_article as $val) 
								{
									$i++;
									if($i == 1)
										continue;
								?>
                                 <li><?=$val['s_title']?></li>
                                  <? 
								  } 
								  ?>                                  
                             </ul>
                         </div>
                      
                         
                     </div>
                     <? } 
					 
					if($cat5_article)
					{
					$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($cat5_article[0]['s_image'], 'smallthumb');
					$i=0;
					?>
					<div class="faith-part">
                         <div class="faith-left">
                             <h3 class="faithbook-icon"><?php echo $cat_name['5']?></h3>
                             <div class="part-pic">
                                 <img src="<?=$IMG?>" alt="Faithbook">
                                 <span><?=my_substr(strip_tags(get_unformatted_string_edit($cat5_article[0]['s_title'])),30)?></span>
                            </div>
                             <div class="clr"></div>
                             <ul class="faith-list">
                             <? 
								foreach($cat5_article as $val) 
								{
									$i++;
									if($i == 1)
										continue;
								?>
                                 <li><?=$val['s_title']?></li>
                                <? 
								  } 
								  ?>                            
                             </ul>
                         </div>
                         <? 
						}
						if($cat6_article)
						{ 
						$i=0;
						$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($cat6_article[0]['s_image'], 'smallthumb');
						?>
                         <div class="faith-right">
                              <h3 class="socaity-icon"><?php echo $cat_name['6']?></h3>
                             <div class="part-pic">
                                 <img src="<?=$IMG?>" alt="Faithbook">
                                 <span><?=my_substr(strip_tags(get_unformatted_string_edit($cat6_article[0]['s_title'])),30)?></span>
                            </div>
                             <div class="clr"></div>
                             <ul class="faith-list">
                                  <? 
								foreach($cat6_article as $val) 
								{
									$i++;
									if($i == 1)
										continue;
								?>
                                 <li><?=$val['s_title']?></li>
                                <? 
								  } 
								  ?>                           
                             </ul>
                             
                         </div>
                          <? 
						}
						?>
                         </div>					 
                     </div>
             <div class="media-center-right">
                 <div class="advertisment"><img src="images/left-ad1.png" alt="Advertisment" width="250" height="250" onclick="location.href='www.google.com'"></div>

              <div>
               <?
				if($cat6_article)
				{
				?>
				<h3 class="devotional"><?php echo $cat_name['6']?></h3>
                <?
					foreach($cat6_article as $val) 
					{
						$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'thumb');
						?>
						  
							
						  <div class="dev-main">
							  <div class="pic-left"><img src="<?=$IMG?>" alt="Devotional"></div>
							  <div class="pic-right">
								  <h4><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_title'])),20)?></h4>
								  <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
							  </div>
							  <div class="clr"></div>
						  </div>
                  
                  <? 
				 
				  }
				  ?>
                  
              </div>
              <? } ?>
              <?
			if($cat7_article)
			{
			
			?>
              <div>
               <h3 class="voice"><?php echo $cat_name['7']?></h3> 
               	<? foreach($cat7_article as $val) 
					{
					$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'thumb');
					?>   
               <div class="dev-main">
                      <div class="pic-left"><img src="<?=$IMG?>" alt="The Voices"></div>
                      <div class="pic-right">
                          <h4><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_title'])),20)?></h4>
                          <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                      </div>
                      <div class="clr"></div>
                  </div>
             
                <? } ?>   
              </div>
              <? } ?>
              
              <?
			if($cat8_article)
			{
			
			?>
              <div>
                  <h3 class="shout"><?php echo $cat_name['8']?></h3> 
                  	<? foreach($cat8_article as $val) 
					{
					$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'thumb');
					?>   
                  <div class="dev-main">
                      <div class="pic-left"><img src="<?=$IMG?>" alt="your shout"></div>
                      <div class="pic-right">
                          <h4><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_title'])),20)?></h4>
                          <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                      </div>
                      <div class="clr"></div>
                  </div> 
				  <? } ?>  
                  
              </div>
               <? } ?>  
               <?
			if($cat9_article)
			{
			
			?>
              <div>
                  <h3 class="review"><?php echo $cat_name['9']?></h3> 
                  	<? foreach($cat9_article as $val) 
					{
					$IMG = base_url() . 'uploads/media_center_article/' . getThumbName($val['s_image'], 'mid');
					?>
                  <div class="review-section">
                       <h4><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_title'])),20)?></h4>
                          <p><?=my_substr(strip_tags(get_unformatted_string_edit($val['s_desc'])),80)?></p>
                      
                  </div>
                 <? } ?>  
                 
              </div>              
          <? } ?>
          
          </div>
          <div class="clr"></div>
          </div>
       
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php include(APPPATH."views/layouts/footer.phtml");?>








<!--view comment div-->


<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script type="text/javascript">
            $(function() {
                $('#ei-slider').eislideshow({
					animation			: 'center',
					autoplay			: true,
					slideshow_interval	: 3000,
					titlesFactor		: 0
                });
            });
        </script>
 <script type="text/javascript">
$(function(){
	$('#navigation_vert').naviDropDown({
		dropDownWidth: '336px',
		orientation: 'vertical'
	});
});
</script>