<div class="link-div">
    <ul>
        <li><a href="<?php echo base_url()?>eswap/sent-request.html" <?=($swap_menu ==  1)?'class="current"':''?>><span class="nw-etrade">Swap Request Sent</span></a></li>
        <li><a href="<?php echo base_url()?>eswap/manage-my-product.html" <?=($swap_menu == 2)?'class="current"':''?>><span class="nw-etrade">My eSwap Products</span></a></li>
        <li><a href="<?php echo base_url()?>eswap/request-received.html" <?=($swap_menu == 3)?'class="current"':''?>><span class="nw-etrade">Swap Request Received</span></a></li>
    </ul>
    <div class="clr"></div>
</div>
