
<table width="70%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                          <tr>
                            <th align="left" valign="middle" height="30" width="500">Category</th>
                            <th align="center" valign="middle" height="30" width="100">No. of Sub-Category(s)</th>
                            <th align="center" valign="middle" height="30" class="last">Actions</th>
                          </tr>
                          
                         <?php
                         // pr($info_arr);
                            if(count($info_arr)){
                            foreach($info_arr as $key=> $info){
                            
                                                
                        ?>
                          <tr id="row_<?=$info['id']?>">
                            <td id="td_name_<?=$info['id']?>" align="left" valign="top"><a id="product_<?=$info['id']?>" href="<?= get_product_category_detail_url($info['id'],$info['s_category_name'])?>"><?=$info['s_category_name']?></a></td>
                            <td align="center" valign="top"><?=$info['total_sub_categories']?></td>
                            <td align="center" valign="middle" class="last">
                            <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return edit_cat(<?=$info['id']?>)"/>
                            <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return delete_confirm_(<?=$info['id']?>)"/>
                           
                  
                  
                  </td>
                </tr>
                
                <?php    }
                    }
                    else{
                ?>
                     <tr>
                          <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                     </tr>
                
                <?php
                    }
                ?>
                         
                        </table>

<div class="paging" style=" margin-right: 292px;" >
            <ul><?= $page_links ?></ul>
</div>    
