<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="80">Created On</th>
                                <th align="left" valign="middle" height="30" width="257">Chat Room Title</th>
                               <?php /*?> <th align="left" valign="middle" height="30" width="160">Category</th><?php */?>
                                <th align="left" valign="middle" height="30" width="420">Description</th>
                                <th align="center" valign="middle" height="30" width="80">Max Allowed Members</th>
                               <?php /*?> <th align="center" valign="middle" height="30" width="40">No. of Members joined till date</th><?php */?>
                                <th align="center" valign="middle" height="30" class="last">Actions</th>
                              </tr>
                              
                              
                              
                              <?php
								#pr($info_arr);
									if(count($info_arr)){
									foreach($info_arr as $key=> $info){
										
										$s_status = ($info['enable'] == 1)?'DISABLE':'ENABLE';	  
								?>
                              
                              
                              <tr>
                                <td align="left" valign="top"><?=getShortDate($info['create_time'],5)?></td>
                                <td align="left" valign="top"><?=$info['name']?></td>
                                <?php /*?><td align="left" valign="top">Contemporary</td><?php */?>
                                <td align="left" valign="top"><?=my_substr($info['des'], 200)?></td>
                                <td align="center" valign="top"><?=$info['max_user']?></td>
                               <?php /*?> <td align="center" valign="top">17</td><?php */?>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="return edit_chatRoom(<?=$info['room_id']?>); "/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="return delete_chatRoom(<?=$info['room_id']?>);"/>
                               
                               
                               <?php /*?> <input name="" title="Disable" type="button" class="btn-06"  value="Disable"/><?php */?>
                                
                                
                                 <?php if($info['enable'] == 1){ ?>
                            		<span id="<?=$info['room_id']?>_status">
                                    <input name="" title="Enable" type="button" class="btn-06"  onclick="javascript:changeStatus(<?php echo $info['room_id'] ?> , 0 , <?php echo $info['enable'] ?>)"  value="<?=$s_status?>"/>
                                    </span>
									<?php 
                                        } 
                                        else if($info['enable'] == 0){?>
                                            <span id="<?=$info['room_id']?>_status">
                                            <input name="" title="Disable" type="button" class="btn-06"  onclick="javascript:changeStatus(<?php echo $info['room_id'] ?> , 1 , <?php echo $info['enable'] ?>)"  value="<?=$s_status?>"/>
                                            </span>
                                    
                                    <?php }?>
                                
                                </td>
                              </tr>
                                 <?php	}
								  }
								  else{
							  ?>
								   <tr>
										<td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
								   </tr>
							  
							  <?php
								  }
							  ?>
                             
</table>

<div class="paging">
            <ul><?= $page_links ?></ul>
</div>	