
                  <?php  //pr($prayer_grp_info);
				  		if(count($prayer_grp_info)){
                          foreach($prayer_grp_info as $key=> $val):
                           
                           $IMG = ($val['is_owner'] == 'Y')?'<img src="'.base_url().'images/crown.png" alt="" />':'<img src="'.base_url().'images/man-24-16.png" alt="" />';
                           $detail_url = get_group_url($val['id'],$val['s_group_name']);
						   
						   $DATETEXT = ($val['is_owner'] == 'Y')?'Created on':'Joined on';
						   //$total_group_created = getTotalPrayerGroupCreated($val['i_user_id']);
                  ?>
                      <li>
                          <span class="payer-member-name"><?=$IMG?><a href="<?=$detail_url?>"> <?=$val['s_group_name']?></a>
                          <?php
						  if($val['is_owner'] == 'Y' && getTotalPrayerGroupCreated($val['i_user_id']) == $i_max_prayer_grp)
						  {
						  ?>
                          <a href="javascript:void(0)" title="Delete Group" onclick="show_dialog('delete-group');$('#i_del_id').val('<?php echo $val['id']?>');"><img src="<?php echo base_url()?>images/fe/cross-icon.gif" /></a>
                          <?php
						  }
						  ?>
                          </span>
                          <ul>
                              <li>No.of members-<?=$val['total_member']?></li>
                              <li>I</li>
                              <li>Denomination- <?=getDenominationNameById($val['i_denomination_id'])?></li>
                          </ul>
                          <br class="clr"/>
                          	<span><p style="font-size:13px;"><?=$DATETEXT?> : <?=getShortDate($val['creation_dt'],5)?></p></span>
                      </li>
                      
                   <?php  
                          endforeach;
                      }
                      else
                      {
                          echo '<li><span class="payer-member-name">No Groups.</span></li>';
                      }
                   ?>
                   
                   <div class="lightbox delete-group delete-post" style="width:245px;">
                          <div class="close"><a href="javascript:void(0)" onclick="hide_dialog();$('#i_del_id').val('');"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
                          <div class="top"><div>&nbsp;</div></div>
                          <div class="mid">
                                <div class="heading" style="margin-bottom:0px;">
                                      <div class="left">
                                            <h4>Delete Prayer Group</h4>
                                      </div>
                                </div>
                                   <div class="shade_box_white" style="padding:8px 0px;">
                                   <div style="padding-bottom:10px;">
                                   <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete these group?</p>
                                   </div>
                                   <form action="" method="post" enctype="multipart/form-data">
                                         <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                                        <input name="" type="button" value="Yes" class="popup-yes"  onClick="deleteGroup()"/>
                                        <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog();$('#i_del_id').val('');"/>
                                   </form>   
                                   <div class="clr"></div>
                                </div>
                                
                          </div>
                          <div class="bot"><div>&nbsp;</div></div>
                    </div>
              <script type="text/javascript">
			  function deleteGroup()
			  {
				 	hide_dialog();
					showBusyScreen();
			  		$.ajax({
							type: 'POST',
							url:base_url+'logged/prayer_group/delete_prayer_group/',
							dataType: 'json',
							data: ({'gr_id': $('#i_del_id').val() }),
							success: function (data, status) {
										hideBusyScreen();
										showUIMsg(data.msg);
										$('#grp_list').html(data.html);
										
										}
						});
			  }
			  </script>