<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="mid_content">
                 
                 
                  <!-- main container -->
                  <div class="main-prayer-group">
                      <!--buttons section start -->
                     <div class="arrow_btm"></div>
                      
                     <div class="page_heading_01 grey">
                            	<div class="left">My Prayer Group</div>
								 <a href="javascript:void(0);" class="create-group">Create Prayer Group</a>
                                 <a href="search-and-join-prayer-group.html" class="create-group2">Search And Join Prayer Group</a>
                                 <a href="request.html" class="create-group2" style="background-color:#7e7e7e;">Prayer Group Request</a> 

                     </div>
                      <!--Create Prayer Group section-->  
					  <div class="slid-Create-Prayer">
                      			<span id="err_grp_name"></span>
								<form id="add_prayer_grp"  action="" method="post" >
								<div class="prayer-group-name"> Prayer Group Name:</div>
								<input type="text" name="txt_group_name" id="txt_group_name" class="amount-input prayer-No-input" />
								 <div class="clr"></div>
                                 <div class="prayer-group-name">Denomination:</div>
                                  <select  name="sel_denomination" id="sel_denomination" class="amount-input prayer-No-input">
                                      <option value="-1">Select</option>
                                      <?=makeOptionDenomination()?>
                                  </select>
								 <div class="clr"></div>
								 <div class="prayer-group-name"></div>
								 <input type="button" class="yellow-btn" value="Create" id="create_bt" onclick="check_simlar_group()" />
                                 
                                 
                                 <div class="notification-list-box similar_prayer_grp" id="main_div" style="display:none;">
                                 <h1 style="color:#2B629C; padding-bottom:15px;">Prayer group with similar name and denomination already exists, are you sure want to create this group?</h1>
                                    <ul class="prayermember-ul">
                                     <DIV id="srchContent"></DIV>
                            		</ul>
                                  <p style="color:#2B629C; padding-top:15px;">Thanks, I will create my own Group</p>
                                 <input type="button" class="yellow-btn" value="Confirm" id="confirm_bt" onclick="add_group()" style="display:none;margin-top: 10px;" />
								 
                                 </div>
                                 </form>
                               </div>
					  </div>
					  <!--Create Prayer Group section-->   
                        
                      
                      <div class="clr"></div>
                      <!--buttons section end -->
					  
					  <!--payer notification start-->
					  <div class="main-payer-section">
                      <div class="payer-notification">
						<div class="nw-right-heading">
                           <div class="left"><h4>Notification</h4></div>
                        </div>
						
						<div class="notification-list-box">
                        	
                            <span style="float:right;">
                            <label class="short-by-prayer-selt" style="width:115px;">Filter by Group Name: </label>
                            <select onchange="get_Grouped_notificationlist()" id="notif_grp_by" class="prayer-selt " style="width:200px;">
                                <option value="-1">Select</option>
                               <?php
							   		if(count($all_grp_arr)){
										foreach($all_grp_arr as $k=> $val){
							   ?>
                                <option value="<?=$val['id']?>"><?=$val['s_group_name']?></option>
                              <?php
										}
									}
							  ?>
                            </select>
                            </span>
                        
							<ul class="notification-ul">
								
                                <DIV id="grp_post_list"><?=$notification_listing?></DIV>
								 <?php if($no_of_result == 0): ?>
                           			<div class="view_more" style="text-align:center;">No Notifications.</div>
                     			 <?php endif; ?>  
							</ul>
						</div>
					  
					  </div>
                      
                      
                      
                      
                      
                      
                      
                      <!--prayer wall eight start -->
					 <div class="main-notification-section">
                		<div class="nw-right-heading">
                     	 	<div class="left"><h4>Prayer Group i have joined/created</h4></div>
                 		</div>
                        <div class="nw-prayer-wall-box no-right-mrgn">
                         
                          <span class="prayermember-leble">
                              <img src="images/crown.png" alt="" width="12" /> Group Owner
                          </span>
                          <label class="short-by-prayer-selt">Sort by: </label>
                            <select class="prayer-selt " id="ordr_by" onchange="getSortedGrpList()">
                                <option value="-1">Select</option>
                                <option value="1" >Date</option>
                                <option value="2" >A-Z</option>
                            </select>
                           <br class="clr" />
                            <label class="short-by-prayer-selt">Group by: </label>
                            <select class="prayer-selt" id="grp_by" onchange="getSortedGrpList()">
                                <option value="all">All</option>
                                <option value="ownership" >Ownership</option>
                                <option value="members" >Members</option>
                            </select>
                         
                         
                         
                          <span class="prayermember-leble">
                              <img src="images/man-24-16.png" alt="" width="12" /> Member
                          </span>
                           <br class="clr"/>
                          
                          	<ul class="prayermember-ul">
                          	 	<DIV id="grp_list" style="margin-top: 10px;"><?=$group_listing?></DIV>
                            </ul>
          					</div> 
						</div>
                      <!--prayer wall eight end  -->
					  </div>
					  <?php if($no_of_result > $notification_per_page): ?>
                             
                           <div class="custom_show view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_records_link" page_value="<?=$current_page_1?>" onclick="show_more_records($(this).attr('page_value'))">[view more] </a> </div>
                     <?php endif; ?>  
					  <!--payer notification end-->
                      
                  	  <div class="clr"></div> 
                  </div>
                  <!-- /main container -->
                 
            </div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->


<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_records(page) {
	
	var group_id = '<?php echo $prayer_detail_arr['id']?>';
	var notif_grp_by = $('#notif_grp_by').val();
	
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/prayer_group/notifications_ajax_pagination/'+page+'/'+notif_grp_by,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				$('#grp_post_list').append(data.html);
				$('#show_more_records_link').attr('page_value', data.cur_page);
				$('#show_more_records_link').attr('onclick','');
				$('#show_more_records_link').attr('onclick','show_more_records('+data.cur_page+')');
			}
			else {
				$('#grp_post_list').append('<div class="view_more " style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Notifications.</p></div>');
				$('#show_more_div').remove();
			}
            
            if(data.view_more==false)
            {
                
                $('#grp_post_list').append('<div class="view_more " style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Notifications.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}


function getSortedGrpList(){
	
	var sort_val = $('#ordr_by').val();
	var grp_val = $('#grp_by').val();
	
	showUILoader_nodialog();
	 $.ajax({
		type: 'get',
		url: base_url+'logged/prayer_group/groups_ajax_listing/'+0+'/'+sort_val+'/'+grp_val,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			$('#grp_list').html(data.grp_html);
		}	// end of success function...
	});
	
}


function get_Grouped_notificationlist(){
	
	var notif_grp_by = $('#notif_grp_by').val();
	
	showUILoader_nodialog();
	 $.ajax({
		type: 'get',
		url: base_url+'logged/prayer_group/notifications_ajax_pagination/'+0+'/'+notif_grp_by,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			$('#grp_post_list').html('');
			$('#grp_post_list').html(data.html);
		}	// end of success function...
	});
	
}


</script>