<script type="text/javascript">
<!--
$(function(){
<?php
		//pr($arr_audio_detail[0]);
	
		//$ID = 'm1'. $audios[0]['id'];
		$audio_filename = base_url()."uploads/user_audio_files/".$arr_audio_detail[0]['s_audio_file_name'];
?>/*
	$(".audio").mb_miniPlayer({
		width:295,
		inLine:false
	});
*/
   jwplayer("myElement_<?=$val['id']?>").setup({
        file: "<?=$audio_filename?>",
        image: "<?=$audio_filename?>",
		height: 30,
        width: 440
    });
   
     
	
<?php
	
?>
});

//-->
</script>


  <div class="audio-block" style="border: 0 none;padding: 0;">
       <p class="blue_bold12"><img src="images/icons/audio_icon.png" alt="" /> <a href="javascript:void(0);"><?=$arr_audio_detail[0]['s_title']?></a></p>
       <p class="light_blue12"><?=$arr_audio_detail[0]['s_artist']?>, <?=get_genre_name_by_id($arr_audio_detail[0]['s_genre_id'])?>, <?=$arr_audio_detail[0]['s_sound_track_album']?></p>
       <p class="date-time">Uploaded on : <?=getShortDate($arr_audio_detail[0]['dt_created_on'],5)?></p>
       <p class="light-grey"><?= $arr_audio_detail[0]['s_desc']?></p>
        <div class="audio-player">
                
                 <div id="myElement_<?=$val['id']?>">Loading the player...</div>
       </div>
  </div>
                      
  <div class="comment-container" style="<?php if((count($arr_audio_detail[0]['comments_arr']))==0) echo 'display:none'?>">      
     <?/*     <div class="heading"><h4><img class="icon-img" src="images/icons/cmmnt.png" alt=""> View Comments</h4></div>
     */?>
          <DIV id="audio_comments_html">
          <?php 
		  		$comments_array = $arr_audio_detail[0]['comments_arr'];
		  		if(count($comments_array)){ 
		  			foreach($comments_array as $val){
                               $comment_user_img = get_profile_image($val['i_user_id'],'thumb',$val['s_profile_photo']);
		  ?>
          		     <div class="txt_content01"> 
                          <a href="javascript:void(0);"><img src="<?php echo $comment_user_img?>" height="60" width="60" alt="" class="pro_photo" /></a>
                          <div class="left_div01a">
                            <p class="blue_bold12"><a  href="javascript:void(0);"><?= $val['s_profile_name']?></a></p>
                            <p class="light-grey"><?= $val['s_contents']?></p>
                             <p class="date-time"><?php if(get_time_elapsed($val['dt_created_on'])) echo "Updated on : ".get_time_elapsed($val['dt_created_on']);?></p>
                            
                          </div>
                          <div class="clr"></div>
                      </div>
          
          
          <?php 	}
		  		}
                else{
          echo '<div class="shade_box_blue" style="padding-top:5px; min-height:255px;"><div  class="shade_norecords" style="width:250px; "><p class="blue_bold12" style="margin-top:80px;">No Comments.</p></div></div>';
                }
                
		  ?>
          </DIV>
          <!--<div class="view_more"><a  href="javascript:void(0);" class="blue_link">[view more] </a> </div>-->
  </div>
    
  <div class="div_content wall-comment">
        <div class="heading">
              <div class="left">
                    <h4><img alt="" class="icon-img" src="images/icons/coment.png" /> Post Comment</h4>
              </div>
        </div>
        <form action="" method="post" class="wall-comment-form">
            
                <!--text div start -->
                <div class="write-text write-text2">
                <textarea id="audio_comment_box<?=$arr_audio_detail[0]['id']?>" name="audio_comment_box<?=$arr_audio_detail[0]['id']?>" cols="" rows="" ></textarea>
                </div>
                <!--text div end -->
            
            <input name="" type="button" class="wall-comment-submit2" value="Post" onclick="post_audio_comment(<?=$arr_audio_detail[0]['id']?>)"/>
        </form>
  </div>