
<div class="div_content" style=" margin-top:0px;">

							<?php
							$logged_id=intval(decrypt($_SESSION['user_id']));

							//pr($ringdata);
							if($ringdata)
							{
								foreach($ringdata as $ringval)
								{
									$LOGO	= base_url().'uploads/user_ring_logos/'.getThumbName($ringval['s_logo'],'thumb');
									$ring_detail_link	= base_url().'rings/'.$ringval['ringid'].'/ring-home.html';
									
									$member_arr = getMembers_ring_bYID($ringval['ringid']); //pr($member_arr);
									
									#pr($arr_join_req_sent);
									#pr($arr_join_req_recv);
							?>
                            <?php if($ringval['s_type'] == 'ring'){
							?>
							<div class="blog" style="padding-top:5px;">
                            <h2 class="nw-blg-heading pull-left">
                            <a href="<?php echo $ring_detail_link?>" id="ring_name_<?php echo $ringval['ringid']?>" style="font-size: 16px; color: #096AA7;"><div class="pro_photo_new" style="background:URL('<?=get_ring_photo_by_id($ringval['ringid'])?>') no-repeat center; width:73px; height:72px; background-color:#fff"></div><?php echo $ringval['s_name']?></a>
                            </h2>
                            <div class="clear"></div>
                            
                           <?php /*?> <h3 class="category new-cat-ring"><?php echo $ringval['s_category_name']?></h3><?php */?>
                           <div class="new-cat-ring cat-name-adjust ">
                          
                         <div class="right-cat-list fnt-adj">  
                         	 <span class="left-cat-gap-one"><?php echo $ringval['s_category_name']?></span>
                          	 <span class="left-cat-gap"><?=get_ring_category_name_by_id($ringval['i_sub_category_id'])?></span>
                          </div>
                           <div class="right-cat-list"> <img src="images/category.png" class="cat_icons" alt="" width="18" height="31"/></div>
                           </div>
                           
                           </div>

                           <p class="time-posted">
                            created <?php echo getShortDate($ringval['dt_created_on'],5)?> by 
                            <?php
							if($ringval['if_already_friend'] == 'true' || $ringval['already_added_netpal'] == 'true'){
							  $profile_link = get_profile_url($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }else
							 {
							  $profile_link = get_profile_url_prayer_partner($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }										
							?>
                            <a style="color: #62C3BC;" href="<?php echo $profile_link?>"><?php echo $ringval['owner_name']?></a> 
                            </p>
                            
                            <p><?php echo my_substr($ringval['s_desc'],160)?></p>
                            <div class="clr"></div>
                            <ul class="article-comment-block article-comment-block2">
                            	<li class="first">Posts : <?php echo $ringval['post']?> </li> 
                                <li> <span>Comments : <?php echo $ringval['cmt']?></span></li>
                                <li> <span>Likes : <?php echo $ringval['lik']?></span></li>
                                <li> <span>Members : <?php echo count($member_arr)?></span></li>
                                <li class="right">
                                    <ul>
										<?php
                                    	if(!in_array($ringval['ringid'], $arr_join_req) && $this->i_profile_id != $ringval['post_owner_user_id'])
                                        {
                                        ?> 
                                        <li  class="first" id="join_req_p_<?php echo $ringval['ringid']?>"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  onclick="joinRequest('ring_name_<?php echo $ringval['ringid']?>','<?php echo encrypt($ringval['ringid'])?>','<?php echo count($member_arr)?>');">Join Ring</a></li>
                                        <?php 
                                        }
										else if($this->i_profile_id == $ringval['post_owner_user_id']){
                                        ?>
                                        <li  class="first"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  >Ring Owner</a></li>
                                        <?php
										}
										else if(in_array($this->i_profile_id, $member_arr) && $this->i_profile_id != $ringval['post_owner_user_id']){
										?>
                                         <li  class="first"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  >Already Member</a></li>
                                        <?php 
										}
										else if(!in_array($this->i_profile_id, $member_arr) && in_array($ringval['ringid'], $arr_join_req_sent) && $this->i_profile_id != $ringval['post_owner_user_id']){
										?>
                                         <li  class="first"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  onclick="acceptRingInvitation('<?php echo $this->session->userdata('user_id')?>','<?php echo encrypt($ringval['ringid'])?>','<?php echo encrypt($ringval['post_owner_user_id']);?>')">Accept invitation</a></li>
                                         
										<?php 
										}
										else if(!in_array($this->i_profile_id, $member_arr) && in_array($ringval['ringid'], $arr_join_req_recv) && $this->i_profile_id != $ringval['post_owner_user_id']){
										?>
                                         <li  class="first"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  >Join request sent</a></li>
                                         <?php }?>
                                    </ul>
                                </li>
                             </ul>
                            
                                  
                            </div>
                            <?php } else if($ringval['s_type'] == 'post'){
							$member=check_member_by_ring_id($ringval['ringid'],$logged_id);
							if($member == true)
							{
							?>
                            
                            <div class="blog" style="padding-top:5px;">
                            <h2 class="nw-blg-heading">
                            <a href="<?php echo $ring_detail_link.'#ring_post'.$ringval['ringPostid']?>" id="ring_name_<?php echo $ringval['ringid']?>" style="font-size: 16px; color: #096AA7;"><?php echo $ringval['s_name']?></a>
                            </h2>
                            <?php /*?><h3 class="category"><span>Category:</span><?php echo $ringval['s_category_name']?></h3><?php */?>
                            <div class="clr"></div>
                           <p class="time-posted">
                            posted <?php echo get_time_elapsed_blog($ringval['dt_created_on'])?> by 
                            <?php
							if($ringval['if_already_friend'] == 'true' || $ringval['already_added_netpal'] == 'true'){
							  $profile_link = get_profile_url($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }else
							 {
							  $profile_link = get_profile_url_prayer_partner($ringval['post_owner_user_id'],$ringval['s_profile_name']);
							 }										
							?>
                            <a style="color: #62C3BC;" href="<?php echo $profile_link?>"><?php echo $ringval['owner_name']?></a> 
                            </p>
                            
                            <p><?php echo my_substr($ringval['s_desc'],160)?></p>
                            <div class="clr"></div>
                            
                            <ul class="article-comment-block article-comment-block2">
                            	
                                <li class="first"> <span>Comments : <?php echo $ringval['post_cmt']?></span></li>
                                <li> <span>Likes : <?php echo $ringval['post_lik']?></span></li>
                                <li class="right">
                                    <ul>
										<?php
                                        if(!in_array($ringval['ringid'], $arr_join_req) && $this->i_profile_id != $ringval['post_owner_user_id'])
                                        {
                                        ?> 
                                        <li  class="first" id="join_req_p_<?php echo $ringval['ringid']?>"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  onclick="joinRequest('ring_name_<?php echo $ringval['ringid']?>','<?php echo encrypt($ringval['ringid'])?>','<?php echo count($member_arr)?>');">Join Ring</a></li>
                                        <?php 
                                        }
                                        ?>
                                    </ul>
                                </li>
                             </ul>
                            
                            <p>Posted on ring <a href="<?php echo $ring_detail_link?>" style="font-size: 15px; color: #096AA7;" ><?=get_ring_name_by_id($ringval['ringid'])?></a></p>
                            <?php /*?><ul class="article-comment-block article-comment-block2">
                            	<li class="first">Total Posts : <?php echo $ringval['post']?> </li> 
                                <li> <span>Total Comments : <?php echo $ringval['cmt']?></span></li>
                                <li> <span>Total Likes : <?php echo $ringval['lik']?></span></li>
                                <li class="right">
                                    <ul>
										<?php
                                        if(!in_array($ringval['ringid'], $arr_join_req) && $this->i_profile_id != $ringval['i_user_id'])
                                        {
                                        ?> 
                                        <li  class="first" id="join_req_p_<?php echo $ringval['ringid']?>"><img src="images/icons/ring2.png" alt="" class="icon-img" /> <a href="javascript:void(0);"  onclick="joinRequest('ring_name_<?php echo $ringval['ringid']?>','<?php echo encrypt($ringval['ringid'])?>');">Join Ring</a></li>
                                        <?php 
                                        }
                                        ?>
                                    </ul>
                                </li>
                             </ul><?php */?>
                            
                                  
                            </div>
                            
                            <?php }
							}
								}
							}

							?>
</div>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page_1?>"  />                     

                            
                            

