<?php pr(($arr_rings));
$logged_id=intval(decrypt($_SESSION['user_id']));
	if(count($arr_rings)){
		
		foreach($arr_rings as $key=> $val){
			
			  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
				  $profile_link = get_profile_url($val['post_owner_user_id'],$val['s_profile_name']);
			  }else
			  {
				  $profile_link = get_profile_url_prayer_partner($val['post_owner_user_id'],$val['s_profile_name']);
			  }
			
?>
  <!--my blog start -->
  <a name="<?='ring_post'.$val['id']?>"></a>
  <div class="blog">
      <h2 style="max-height:60px; overflow:hidden;"><?=$val['s_post_title']?></h2>
     <?php /* <p style="max-height:80px; overflow:hidden;"><?=my_substr(nl2br($val['s_post_description']) , 340)?></p> */?>
	 <p style=""><?=$val['s_post_description']?></p>
      <p class="time-posted">Posted  <?=get_time_elapsed_blog($val['dt_created_on'])?> by: <a href="<?=$profile_link?>"><?=$val['s_profile_name']?></a></p>
    
   		 <ul class="article-comment-block article-comment-block2">
           <li class="first left"><a  class="comments_div<?=$val['id']?>"  onclick="return show_comments(<?=$val['id']?>)" href="javascript:void(0);">Comments (<?=$val['total_comments']?>)</a><!--Comments (<span><a href="#">2</a></span>)--></li>
           <li class="left"><a onclick="return show_people_liked(<?=$val['id']?>); " class="liked_by_<?=$val['id']?>" href="javascript:void(0);">Liked By (<?=count_ring_post_like_link($val['id'])?>)</a></li> 
         
                  <?php if($logged_id !=$val['i_user_id']):?> <li class="left"><a href="javascript:void(0);" >Report Abuse </a>&nbsp;|</li><?php endif;?>
         
        <?php 
	#pr($ring_members_ajax);echo intval(decrypt($this->session->userdata('user_id')));exit;
    if(in_array(intval(decrypt($this->session->userdata('user_id'))),$ring_members_ajax) || $val['i_user_id'] == intval(decrypt($this->session->userdata('user_id'))))
    {
		
		if((show_ring_like_link($val['id']) == TRUE) ) { 
		?>
                           
           <li class="right">
              <ul>
			   <li class="first"><a href="javascript:void(0);" >Comment</a></li>
                  <li ><a  href="javascript:void(0);" id="like_count_<?=$val['id']?>" onClick="windowLike(<?=$val['id']?>,'Like')" >Like</a></li>
                 
				 
                 
				  
				 
              </ul>
          </li>
                               
       <?php } 
	   		else{ 
	   ?>
             <li class="right">
              <ul>
				<li class="first"><a href="javascript:void(0);" >Comment</a></li>
                  <li ><a  href="javascript:void(0);" id="like_count_<?=$val['id']?>"  >Like</a></li>
                  <li ><a  href="javascript:void(0);" id="edit<?=$val['id']?>"  >Edit</a></li>
                  <li ><a  href="javascript:void(0);" id="edit<?=$val['id']?>"  >Delete</a></li>
				 
                  
				

              </ul>
         	 </li>
          
       <?php 
	   }
	   }?>
         
         
          
      </ul>
	   			 <!-- slide section start -->
                          <div class="new-wl">
                          <!--comment section start-->
                              <div  class="comments-number content-width" id="comments_list_div<?=$val['id']?>">
                                <div class="comments-number-mid">
                                    <div class="heading">
                                          <div class="left">
                                                <h4><img class="cmnt" src="images/icons/cmnt2.png" alt="cmnt2s" height="20" width="20"/><span  class="comments_div<?=$val['id']?>"> Comments (<?=$val['total_comments']?>)</span> </h4>
                                                <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                                          </div>
                                    </div>
                                    
                                    <DIV id="ring_post_comment_div<?=$val['id']?>"></DIV>
                              </div>
                              </div>
                          <!--comment section end-->	
                          <!--like by section start-->
                              <div  class="comments-number content-width" >
                            
                                <div class="comments-number-mid">
                                    <div class="heading">
                                          <div class="left">
                                                <h4><img alt="" src="images/heart2.png" class="cmnt" /><span class="liked_by_<?=$val['id']?>"> Liked by (<?=count_ring_post_like_link($val['id'])?>) </span></h4>
                                                 <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                                          </div>
                                    </div>
                                    <DIV class="shade_box_white" id="ring_post_like_div<?=$val['id']?>"></DIV>
                              </div>
                           
                          </div>
                          <!--like by section end-->
                             <div class="comments-number content-width" id="text-section-<?=$val['id']?>" style="display:none">
								<form id="frm_report_abuse_<?=$val['id']?>" onSubmit="return false;">
								<textarea rows="5" cols="5" id="txt_abuse_profile_text_<?=$val['id']?>" style="width:461px;margin-bottom:10px;"></textarea>
								<input type="button" class="yellow-btn" value="Send" onclick="report_abuse_profile(<?=$val['id']?>)"/>
								</form>
							</div>	 
                          </div>
                          <div class="new-wl-right">
						  
						 <?/* <div class="comments-number content-width" id="text-section-<?=$val['id']?>" style="display:none">
								<form id="frm_report_abuse_<?=$val['id']?>" onSubmit="return false;">
								<textarea rows="5" cols="5" id="txt_abuse_profile_text_<?=$val['id']?>" style="width:461px;margin-bottom:10px;"></textarea>
								<input type="button" class="yellow-btn" value="Send" onclick="report_abuse_profile(<?=$val['id']?>)"/>
								</form>
							</div>	*/?>
                              <!--comment section start-->
                              <div  class="comments-number content-width" >
                            
                                <div class="comments-number-mid mid-adust-comment">
                                    <div class="heading">
                                          <div class="left">
                                                <h4><img alt="" src="images/no.png" class="cmnt" width="21" height="19" /> Comment  </h4>
                                                <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                                          </div>
                                    </div>
                                    
                                     <div class="txt_content01 comments-number-content"> 
                                      <textarea rows="" cols="" id="feed_comment_box_<?=$val['id']?>" name="feed_comment_box_<?=$val['id']?>" class="wal-comment-textarea" onkeyup="ringLimitText(feed_comment_box_<?=$val['id']?>,this.countdown,1000);" onkeydown="ringLimitText(feed_comment_box_<?=$val['id']?>,this.countdown,1000);"></textarea>
                                      <input type="button" onclick="post_comment(<?=$val['id']?>)" id="post_comment_button" class="yellow-btn" value="Post" />
                                      <br class="clr" />
                                      <p style="font-style:italic; font-size:11px;">Max Character 1000</p>
                                      </div>
                
                                    
                              </div>
                           
                          </div>
                              <!--comment section end-->
							
													  
                          </div>
                 <!-- slide section start -->
      
      
      <div class="clr"></div>
  </div>
  <!--my blog end -->
  
  <script type="text/javascript">
  $(function(){
	$('.article-comment-block .left').click(function(){
		$('.new-wl > .comments-number').css('display','none');
		$('.new-wl-right > .comments-number').css('display','none');
		var index= $(this).index();
		//alert(index);
		$(this).parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	})
	
	$('.article-comment-block .right .first').click(function(){ 
		$('.new-wl > .comments-number').css('display','none');
		$('.new-wl-right > .comments-number').css('display','none');
		var index= $(this).index();
		//console.log($(this).parent().parent().parent().next().next().children('.comments-number').filter(':eq('+ index +')'));
		$(this).parent().parent().parent().next().next().children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	})
	
	$('.wal-minus').click(function(){
		$(this).parents('.comments-number').slideUp('fast');
	})

	});
function report_abuse_profile(id)
{
	if($('#txt_abuse_profile_text_'+id).val() == ''){
	  showUIMsg('Please provide reason.');
	  return false;
  }
  showUILoader_nodialog();
  $.ajax({
	  type: 'post',
	  url: base_url + 'public_profile/abuseMedia/'+id+'/ring',
	  data: {'s_reason':$('#txt_abuse_profile_text_'+id).val(),'abuser':<?=$val['i_user_id']?>},
	  dataType: 'json',
	  success: function(data, status) {
		  
		  showUIMsg(data.msg);
		  $('#txt_abuse_profile_text_'+id).val('');
		  //$('.link-report').trigger('click');
		  $("#text-section-"+id).css("display","none");
		  hideUILoader_nodialog();
	  }	// end of success function...
  });
}
  </script>
<?php 
		}
	}
?>                 