<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />
<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->
<!--<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>
-->
 <script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>
<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div><?php /*?><?php */?>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <div id="mid_container">
                        	<!--sub page links -->
                              <div class="page_heading">
                            	<div class="left"><img src="images/icons/event.png" alt="" />Event</div>
                             </div>
                              <div class="link-div" style="margin-top:-2px;">
                              	<ul>
                                <li><a href="all-events.html" class="<?php echo ($page_name=='all-events')?'current':'';?>"><span>All Events</span></a> </li>	
                                    <li><a href="my-events.html" class="<?php echo ($page_name=='my-events')?'current':'';?>"><span>My Events</span> </a> </li>
                                	<li><a href="create-event.html" class="<?php echo ($page_name=='create-event')?'current':'';?>"><span>Create Event</span> </a> </li>
                                    <li><a href="event-invitations-received.html" class="<?php echo ($page_name=='event-invitations-received')?'current':'';?>"><span>Event Invitations Received</span></a> </li>
                                     <li><a href="archived-events.html" class="<?php echo ($page_name=='archived-events')?'current':'';?>"><span>Archive</span></a> </li>
                                      <li><a href="events-rsvp-recevied.html" class="<?php echo ($page_name=='events-rsvp-recevied')?'current':'';?>"><span>Event RSVPs Received</span></a> </li>
                                    
                                </ul>
                                <div class="clr"></div>
                              </div>
                            <!--/sub page links -->
                            
                            
                          
                            <form id="frmCreateEvent"  method="post" action="<?=base_url().'logged/create_event/add_event_ajax'?>" onsubmit="return false;" enctype="multipart/form-data"> 
                             <div class="frm_box blue_box" >
                                    <div class="lable01" style="width:60px;">Title : </div>  
                                    <div class="field03">
                                    <input name="txt_title" id="txt_title" type="text"  style="width:370px;" />
                                    <span id="err_title" class="error-message"></span>
                                    </div> 
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:60px;">Venue : </div>  
                                    <div class="field03">
                                    	 
                                       
                                        <div class="lable01" style="width:70px;">Street : </div>  
                                        <div class="field01" style=" width:325px;">
                                        <input name="txt_street" id="txt_street" type="text" style="width:285px;"/>
                                        <span id="err_street" class="error-message"></span>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01" style="width:70px;">City :</div>  
                                        <div class="field01" style=" width:325px;">
												  <input name="txt_city" id="txt_city" type="text" style="width:285px;" />                                        			<span id="err_city" class="error-message"></span>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01" style="width:70px;">State : </div>  
                                        <div class="field01" style=" width:325px;">
                                        
 												  <input name="txt_state" id="txt_state" type="text" style="width:285px;" />                                    				<span id="err_state" class="error-message"></span>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01" style="width:70px;">Postcode : </div>  
                                        <div class="field01" style=" width:325px;">
                                        
 												  <input name="txt_postcode" id="txt_postcode" type="text" style="width:285px;" />                                    				<span id="err_postcode" class="error-message"></span>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                       
                                        <div class="lable01" style="width:70px;">Country :</div>  
                                        <div class="field01" style=" width:325px;">
                                        	     <select name="country" id="country" style="width:297px; ">
                                                   <option value="-1">Select</option>
                                                   <?=makeOptionCountryNew();?>
                                                   
                                                </select>
                                               <span id="err_country" class="error-message"></span> 
                                        </div> 
                                        <div class="clr"></div>
                                        
                                    </div> 
                                    <div class="clr"></div>
                                    
                                    <div class="lable01" style="width:146px;">Date : </div>  
                                    <div class="field03">
                                    <input style="width:131px;" type="text"  value="" name="date_to" id="date_to"  readonly="readonly"/>
                                          <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                                          <script type="text/javascript">
                                           /* $(document).ready(function(arg) {
                                                $.datepicker.setDefaults($.datepicker.regional['']);
                                                //$("#date_to").datepicker($.datepicker.regional['en']);
													$("#date_to").datepicker({
															//beforeShow: changeYearButtons,
															//onChangeMonthYear: changeYearButtons,
															dateFormat : 'yy-mm-dd',
												  			minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?> ,  0, 00),
															regional:'en',
															//controlType: 'select',
															//stepMinute: 15
														 });
                
                                            });*/
											
											$(function(){
												 var inputDate = $("#date_to");
												 var changeYearButtons = function() {
													setTimeout(function() {
													   $('.NextYrClass').remove();
													   $('.PrevYrClass').remove();
													   var widgetHeader = inputDate.datepicker("widget").find(".ui-datepicker-header");
													   //you can opt to style up these simple buttons tho
													   var prevYrBtn = $('<button title="PrevYr" class="PrevYrClass"> </button>');
													   prevYrBtn.bind("click", function() {
														$.datepicker._adjustDate(inputDate, -1, 'Y');
													   });
													   var nextYrBtn = $('<button title="NextYr" class="NextYrClass"></button>');
													   nextYrBtn.bind("click", function() {
														$.datepicker._adjustDate(inputDate, +1, 'Y');
													 
													   });
													   prevYrBtn.appendTo(widgetHeader);
													   nextYrBtn.appendTo(widgetHeader);
											  
												  }, 0);
												 };
											  
											  	$("#date_to").datetimepicker({
															beforeShow: changeYearButtons,
															onChangeMonthYear: changeYearButtons,
															dateFormat : 'yy-mm-dd',
												  
															 minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?> ,  0, 00),
															 controlType: 'select',
																   stepMinute: 15
														   });
														
											  });
                                        </script>
                                        <span id="err_date_to" class="error-message"></span> 
                                    </div> 
                                    <div class="clr"></div>
                                    
                                    
                                   
                                    
                                 <?php /*  <div class="lable01" style="width:146px;">Start Time :</div>
                                     
                                       <div class="field03">
                                       <select class="select-box nw-select-box" name="todo_strt_frm" id="todo_strt_frm" onchange="generateEndtime($(this).val())">
                                       <option value="-1">Select</option>
                                        <?=makeOption_time()?>
                                    </select>
                                
                                   <span id="err_todo_strt_frm" class="error-message"></span> 							 
                                 
                                 </div>*/?>
                                 <div class="clr"></div>
                                 
                                
                                 
                                 <span id="add_to_do_end_time"> 
                                 
                                 <div class="lable01" style="width:146px;">End Date : </div>  
                                    <div class="field03">
                                    <input style="width:131px;" type="text"  value="" name="date_end" id="date_end"  readonly="readonly" onchange="check_lim()"/>
                                          <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
                                          <script type="text/javascript">
                                            /*$(document).ready(function(arg) {
                                                $.datepicker.setDefaults($.datepicker.regional['']);
												
                                               // $("#date_end").datepicker($.datepicker.regional['en']);
												$("#date_end").datepicker({
															//beforeShow: changeYearButtons,
															//onChangeMonthYear: changeYearButtons,
															dateFormat : 'yy-mm-dd',
												  			minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?> ,  0, 00),
															regional:'en',
															//controlType: 'select',
															//stepMinute: 15
														 });
                
                                            });*/
											$(function(){
												 var inputDate = $("#date_end");
												 var changeYearButtons = function() {
													setTimeout(function() {
													   $('.NextYrClass').remove();
													   $('.PrevYrClass').remove();
													   var widgetHeader = inputDate.datepicker("widget").find(".ui-datepicker-header");
													   //you can opt to style up these simple buttons tho
													   var prevYrBtn = $('<button title="PrevYr" class="PrevYrClass"> </button>');
													   prevYrBtn.bind("click", function() {
														$.datepicker._adjustDate(inputDate, -1, 'Y');
													   });
													   var nextYrBtn = $('<button title="NextYr" class="NextYrClass"></button>');
													   nextYrBtn.bind("click", function() {
														$.datepicker._adjustDate(inputDate, +1, 'Y');
													 
													   });
													   prevYrBtn.appendTo(widgetHeader);
													   nextYrBtn.appendTo(widgetHeader);
											  
												  }, 0);
												 };
											  
											  	$("#date_end").datetimepicker({
															beforeShow: changeYearButtons,
															onChangeMonthYear: changeYearButtons,
															dateFormat : 'yy-mm-dd',
												  
															 minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?> ,  0, 00),
															 controlType: 'select',
																   stepMinute: 15
														   });
														
											  });
											function check_lim()
											{
												var start_date=$('#date_to').val();
												var end_date=$('#date_end').val();
												//alert(end_date);
												if(start_date>end_date)
												{
													alert('Please enter a valid end date');
													$("#date_end").val('');
												}
											}
                                        </script>
                                        <span id="err_date_end" class="error-message"></span> 
                                    </div> 
                                    <div class="clr"></div>
                                 
                                 
                               <?php /*  <div class="lable01" style="width:146px;">End Time :</div>
                                  <div class="field03">
                                   <select name="todo_end_frm" id="todo_end_frm" class="select-box nw-select-box">
                                     <?php /*?><option value="-1">Select</option><?php ?>
                                     <?=makeOption_time()?>
                                    </select>
                                     <span id="err_todo_end_frm" class="error-message" ></span>

                                    </div>*/?>
                                     <div class="clr"></div>
                                </span>
                         
                                 
                                    
                                 <div class="lable01" style="width:146px;">Send reminder :</div>                                      
                                  <div class="field03">
                                   <select name="todo_rem_time" id="todo_rem_time" class="select-box nw-select-box">
                                   <option value="-1">Select</option>
                                   <option value="00:15">15 Minutes</option>
                                   <option value="00:30">30 Minutes</option>
                                   <option value="00:45">45 Minutes</option> 
                                   <option value="01:00">1 Hour</option>
                                   <option value="02:00">2 Hours</option>
                                   </select>
                                   <span class="blue12">Before the Start Time</span>
                                    
                                    <span id="err_todo_rem_time" class="error-message"></span>
                                    </div>
                                    
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:146px;">Privacy  :</div>  
                                    <div class="field03 smart-filter-wd">
                 						<?php echo get_privacy_setting('event');?>
                                        <a href="<?=base_url()?>/privacy-settings.html" style="text-decoration:underline">  [Change]</a>
                                     	<span class="error-message" id="err_privacy"></span> 
                                       
                 							<script type="text/javascript">
												$(document).ready(function(arg){
														$("#friendSlct").multiselect().multiselectfilter();	
														$("#ringselect").multiselect().multiselectfilter();
														$("#netpalselect").multiselect().multiselectfilter();
														$("#ppselect").multiselect().multiselectfilter();	
														$("#pgselect").multiselect().multiselectfilter();
														$("#pgselect").multiselect().multiselectfilter();
														$("#frndinv").multiselect().multiselectfilter();	
														$("#netpalinv").multiselect().multiselectfilter();
														$("#ppinv").multiselect().multiselectfilter();
													
													});
	
											</script>
                                    <?php /* <select name="privacy_settings" id="privacy_settings" style="width:144px;">
                                          <option>Only my friends</option>
                                    </select>?><script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#privacy_settings").msDropDown();
                                            $("#privacy_settings").hide();
                                        })
                                    </script><?php */?>
                                    </div> 
                                    <div class="clr"></div>
                                    
                                    
                                  <?php /*?>  <div class="lable01" style="width:60px;">	Start Time : </div>  
                                    <div class="field03">
                                    	 <div class="lbl01" style="width:165px;">
                                         
                                         <select name="strt_time" id="strt_time" style="width:160px;">
                                              <option>Select </option>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#strt_time").msDropDown();
                                                $("#strt_time").hide();
                                            })
                                        </script>  
                                        </div>  
                                        <div class="lbl01" style="width:70px;">
                                         
                                       Start Date :
                                        </div>  
                                        <div class="lbl01" style="width:160px;">
                						<input style="width:120px;"   type="text"  value=" " name="date_to" id="date_to"  readonly="readonly"/>
                                          <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
										<script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $.datepicker.setDefaults($.datepicker.regional['']);
                                                $("#date_to").datepicker($.datepicker.regional['en']);
                
                                            });
                                        </script>
                                        </div>  
                                         <div class="clr"></div>
                                    </div> 
                                    <div class="clr"></div>
                                    
                                     <div class="lable01" style="width:60px;">	End Time : </div>  
                                    <div class="field03">
                                    	 <div class="lbl01" style="width:165px;">
                                         
                                         <select name="end_time" id="end_time" style="width:160px;">
                                              <option>Select </option>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#end_time").msDropDown();
                                                $("#end_time").hide();
                                            })
                                        </script>  
                                        </div>  
                                        <div class="lbl01" style="width:70px;">
                                         
                                       End Date :
                                        </div>  
                                        <div class="lbl01" style="width:160px;">
                                       <input style="width:120px;"   type="text"  value=" " name="date_end" id="date_end"  readonly="readonly"/>
                                          <img src="images/icons/cal.png" alt="" onclick="$(this).prev().focus()" style="cursor:pointer; " />
										<script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $.datepicker.setDefaults($.datepicker.regional['']);
                                                $("#date_end").datepicker($.datepicker.regional['en']);
                
                                            });
                                        </script>
                                        </div>  
                                         <div class="clr"></div>
                                    </div> 
                                    <div class="clr"></div><?php */?>
                                    
                                    
                                    <div class="lable01" style="width:95px;">	Description: </div>  
                                    <div class="field03">
                                    <!--<textarea name="txt_event_desc"  id="txt_event_desc" cols="" rows="" style="width:335px; height:190px;"></textarea>-->
                                    <textarea name="txt_event_desc"  id="txt_event_desc" style="width:335px; height:190px" onFocus="if(this.value=='Max 500 Char allowed') this.value='';" onBlur="if(this.value=='')this.value='Max 500 Char allowed'; " onkeypress="return restrict_carrige(event);"  >Max 500 Char allowed</textarea>
                                     <span id="err_event_desc" class="error-message"></span>
                                    <p style=" clear:both; "> <span id="text_count">0</span> Characters</p>
                                    </div> 
                                    <div class="clr"></div>
                                    
                                  
                                  <div class="lable01" style="width:95px;">Main Image : </div>
                                  <div class="field03" style="width:365px; ">
                                    <input name="adv_image_1" id="adv_image_1" type="file" size="52"  style="width:340px;" /> 
                                    <div class="clr"></div>
                                  
                                  <span id="err_image_1" class="error-message"></span> 
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                  <div class="lable01" style="width:95px;">Image 2 : </div>
                                  <div class="field03" style="width:365px; ">
                                    <input name="adv_image_2" id="adv_image_2" type="file" size="52"  style="width:340px;" /> 
                                    <div class="clr"></div> 
                                    <span id="err_image_2" class="error-message"></span> 
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                  <div class="lable01" style="width:95px;">Image 3 : </div>
                                  <div class="field03" style="width:365px; ">
                                    <input name="adv_image_3" id="adv_image_3" type="file" size="52"  style="width:340px;" /> 
                                    <div class="clr"></div>
                                     <span id="err_image_3" class="error-message"></span> 
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01" style="width:95px;">Image 4 : </div>
                                  <div class="field03" style="width:365px; ">
                                    <input name="adv_image_4" id="adv_image_4" type="file" size="52"  style="width:340px;" /> 
                                    <div class="clr"></div>
                                     <span id="err_image_4" class="error-message"></span> 
                                  </div>
                                 
                                  <div class="clr"></div>
                                  
                                  <div class="lable01" style="width:95px;">Image 5 : </div>
                                  <div class="field03" style="width:365px; ">
                                    <input name="adv_image_5" id="adv_image_5" type="file" size="52"  style="width:340px;" /> 
                                    <div class="clr"></div>
                                     <span id="err_image_5" class="error-message"></span> 
                                  </div>
                                  
                                  <div class="clr"></div>
                                  
                                   
                                    <div class="labelnetwork">	Invite members from Your network:</div>  
                                    <div class="field03 field-network smart-filter-eventwd">
                                    
                                    	 <?php echo get_invitation('event');?>
										 <span id="err_invite_frnd" class="error-message"></span> 
                                    </div>
                                    <div class="clr"></div>
                                  <!--  <input type="hidden" id="h_friend_id"  name="h_friend_id" />
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:95px;">&nbsp;</div>  
                                    <div class="field03" style=" width:365px;">-->
                                      
                                         <!--<input name="" type="button" value="Contacts"  class="yellow-btn send-pro-message" /> -->
                                    
                                     <!-- <ul class="profile-msg-send">
                                        <li><a class="send-pro-message" href="javascript:void(0);" >Contacts</a></li>
                                      </ul>-->
                                      
                                     <!-- <div class="new-wl" style="margin-top:8px;">
                                        <div class="comments-number" style="width:97%;">
                                        <div class="heading">
                                            <div class="left">
                                                  <h4><img alt="" src="images/icons/cmnt2.png" class="cmnt" /> Contacts</h4>
                                                  <img src="images/minus-white.png" alt="" class="wal-minus" />
                                            </div>
                                        </div>
                                    	  <div class="shade_box_white" style="padding:8px 0px;">
                 						      <div id="contact_list" >
                                              <div class="selectRecipients" style=" min-height:120px; height:50px;">
												 <?php 
                                                    if(count($contact_arr)):
                                                       $count_total = 1;
                                                       //pr($contact_arr);
                                                        foreach($contact_arr as $key=>$val){
                                                            
                                                            $img = get_profile_image($val['user_id'], 'thumb');
                                                            
                                                            if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
                                                                  $profile_link = get_profile_url($val['user_id'],$val['s_displayname']);
                                                            }
                                                            else{
                                                                 $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
                                                            }
                                                            
                                                            $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
                                                                  
                                                   ?>
                                                   <div class="image-block <?=$CSS?>">
                                                       
                                                        <input type="checkbox"  value="<?=$val['user_id']?>_<?=$val['s_displayname']?>" name="<?=intval(decrypt($this->session->userdata('user_id')))?>" id="<?=$key+1?>" />
                                                        <div class="inside">
                                                            <?php /*?><img alt="Friend" class="pro_photo3" src="<?=$img?>" /><?php */?>
                                                            <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>                                                        </div>
                                                    </div>
                                                  
                                                   
                                                   <?php	$count_total++;	
                                                              }
                                                          endif; 
                                                   ?>
                                                     
                                                </div> 
                                              </div>
                                              <div class="clr"></div>
                                              <br />
                                              <input name="" type="button" value="Done" class="yellow-btn" onclick="javascript:get_selected_contacts();"/>
                                      		</div>
            							 </div>
            						   </div>
                                       </div>
                                     
                                    <div class="clr"></div>-->
                                     <div class="labelnetwork" >	Invite people outside cogtime: </div>  
                                    <div class="field03 field-network">
                                    <input name="txt_frnd_email" id="txt_frnd_email" type="text" style="width:335px;" />
                                    <span id="err_frnd_email" class="error-message"></span> 
                                   
                                    </div> 
                                   
                                    <div class="clr"></div>
                                     <div style="font-size:11px; font-style:italic; line-height:13px; margin-left:113px;" >(Please input comma seperated Email Ids.)</div>
                                    
                                    
                                    <div class="lable01" style="width:95px;">&nbsp;</div>  
                                    <div class="field03">
                                      
                                         <input name="" type="submit" value="Create"  class="btn"/> 
                                         <input name="" type="reset" value="Cancel"  class="btn" id="cenEvtBt"/>
                                     </div> 
                                    <div class="clr"></div>
                          	</div>
                            
                            </form>
                            <script>
                            $(document).ready(function(){
                                $('#cenEvtBt').click(function(){
                                    window.location = "<?= base_url(); ?>all-events.html";
                                });
                                
                            });
                            </script>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->

<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->

<div class="lightbox contact_div" style="width:500px; ">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Select from Contacts </h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
                 
                  <?php /*?> <div class="user_div"> 
                        <input name="" type="checkbox" value="" />  <a href="javascript:void(0);"><img src="images/man1.png" alt=""/></a>
                      <a href="javascript:void(0);" class="blue_link">George Swift</a>
                        
                  </div><?php */?>
                  <div id="contact_list" >          
                  		<div class="selectRecipients" style="background-color: #FFF; width:457px; border:none;">
                   <?php 
                      if(count($contact_arr)):
                         $count_total = 1;
                         //pr($contact_arr);
                          foreach($contact_arr as $key=>$val){
                              
                              $img = get_profile_image($val['user_id'], 'thumb');
                              
                              if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
                                    $profile_link = get_profile_url($val['user_id'],$val['s_displayname']);
                              }
                              else{
                                   $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
                              }
                              
                              $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
                                    
                     ?>
                     <div class="image-block <?=$CSS?>">
                         
                          <input type="checkbox"  value="<?=$val['user_id']?>_<?=$val['s_displayname']?>" name="<?=intval(decrypt($this->session->userdata('user_id')))?>" id="<?=$key+1?>" />
                          <div class="inside">
                              <?php /*?><div style="background:url('<?=$img?>') no-repeat center;width:60px; height:60px;" class="pro_photo2"></div><?php */?>
                              <img alt="Friend" src="<?=$img?>" /><br/><br/><br/>
                              <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>
                          </div>
                      </div>
                    
                     
                     <?php	$count_total++;	
                                }
                            endif; 
                     ?>
                       
                  </div> 
					</div>
                    <div class="clr"></div>
                    <br />
                    <div style="text-align:right;"><input name="" type="button" value="Done" onclick="javascript:get_selected_contacts();" class="btn"/></div>
            </div>
            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
      >
</div>

<script type="text/javascript">
 var carriage_count = 0;
$(document).ready(function() {

	$('.send-pro-message').click(function(){
		var index=$(this).index();
		$('.new-wl > .comments-number ').css('display','none');
		$(this).next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	});
	
	 $('.wal-minus').click(function(){
			$(this).parents('.comments-number').slideUp('fast');
	 });
	 $(function(){
  $('#txt_event_desc').keyup(function(){
	  count=1;
  limitChars('txt_event_desc', 500, '');
  });
  $('#txt_event_desc').keydown(function(){
	  count=1;
  limitChars('txt_event_desc', 500, '');
  });
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('txt_event_desc',500, '');

	
});
var count=0;
//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
	
  var text = $('#'+textid).val(); 
  
  if(text == ''){
	  count = 0;
  }
 


if( count == 0)
{
	//alert (carriage_count)
  var textlength = 0;
}
else
{
 var textlength = text.length;
}
  $('#text_count').html(textlength);
  if(textlength > limit)
  {
  $('#'+textid).val(text.substr(0,limit));
  return false;
  }
  else
  {
  return true;
  }
  
}




function restrict_carrige(e)
{
	/*//if(e.keyCode == 13)
	{
		$.ajax({
			type: 'post',
			url: base_url+'logged/prayer_wall/getCarriageCount',
			data: {'str':$('#ta_desc').val()},
			dataType: 'json',
	
			success: function (data, status) {
				
					if(data.count > 1){
						return false;
					}
				
				}	// end of success function...
		});
	}*/
	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));

	if(e.keyCode == 13){
		carriage_count++;
		console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >10){
		return false;
		//e.preventDefault();
	}
}

function generateEndtime(start_time)
{
	 var id = $('#i_list_id').val();
	
	 showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
  
		 $.ajax({
			 type: "get",
			 url: base_url+'logged/organizer_day_view/generate_end_time_list/'+start_time,
			 dataType:"json",
			 success: function(json_response){
				 
				  if(json_response.success == true) {
					   showUIMsg(json_response.msg);
						
						//hide_dialog('edit_list');
						
						$('#todo_end_frm').html('');
						$('#todo_end_frm').html(json_response.sel_html);
						$('#add_to_do_end_time').attr('style','display:block;');
						$('#add_to_do_end_time').show();
						//$('#end_time_select').show();
						hideUILoader_nodialog();
				  }
				  else {
					   
					  // alert(json_response.success +' al '+ 2+ ' id: '+ id);
					   $('#add_to_do_end_time').attr('style','display:none;');
					   hideUILoader_nodialog();
					  //showUIMsg('Some error occurred. Please try again.');
				  }
			  },
			  error: function(){
				 hideUILoader();
				 //hide_dialog('edit_list');
				  showUIMsg('Some error occurred. Please try again.');
			  }
		  });	 
}


function generateEndtime_edit(start_time , id)
{
	  showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
  
		 $.ajax({
			 type: "get",
			 url: base_url+'logged/organizer_day_view/generate_end_time_list/'+start_time,
			 dataType:"json",
			 success: function(json_response){
				 
				 
				  if(json_response.success == true) {
					   showUIMsg(json_response.msg);
						//alert(json_response.success+ 1);
						//hide_dialog('edit_list');
						
						$('#edit_todo_end_frm_'+id).html('');
						$('#edit_todo_end_frm_'+id).html(json_response.sel_html);
						$('#edit_end_time_div_'+id).attr('style','display:block;');
						hideUILoader_nodialog();
				  }
				  else if(json_response.success == false) {
					   //alert(json_response.success +' al '+ 2+ ' id: '+ id);
					   $('#edit_end_time_div_'+id).attr('style','display:none;');
					   hideUILoader_nodialog();
					   // showUIMsg('Some error occurred. Please try again.');
				  }
			  },
			  error: function(){
				 hideUILoader();
				 //hide_dialog('edit_list');
				  showUIMsg('Some error occurred. Please try again.');
			  }
		  });	 
}

</script>

