<?php
if (($this->session->userdata('loggedin') != '' || $this->session->userdata('loggedin') != false ) && $this->session->userdata('is_admin') != 1) {

    include(APPPATH . "views/layouts/logged_header.phtml");
    include(APPPATH . "views/layouts/nav.phtml");
    ?>
    <!-- /NAVIGATION SECTION -->
    </div>
    </div>


    <?php
} else {

    include(APPPATH . "views/layouts/header.phtml");
    include(APPPATH . "views/layouts/slider_nav.phtml");
}
?>

<!-- /HEADER SECTION -->
<div class="clr"></div><!-- CONTENT SECTION -->

<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
<?php /* ?><script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script><?php */ ?>
<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <!-- main container -->



        <!-- latest news -->
        <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
        <!-- /latest news -->
        <div class="clr"></div>
        <!-- main container -->
        <div id="main_container">
            <!-- left container -->
            <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
            <!-- /left container -->
            <div id="mid_container">
				 <div style="margin-left:412px; margin-bottom:5px;">
                     <input type="submit" class="sml_btn" name="reload_search" value="Back"  style=" background:none repeat scroll 0 0 #013D62;"  onclick="window.location='<?= $_SERVER['HTTP_REFERER'] ?>'"/>
                    </div>
  
                              
               

                <div class="page_heading">
                    <div class="left"><img alt="" src="images/icons/event.png" width="35" height="39"/> <?= $event_info['0']['s_title'] ?></div>
					
                    <ul class="pre-time-create-time">
                        <li class="name-pad"><strong>Created On:</strong> <?= getShortDate($event_info['0']['dt_created_on'], 5) ?></li>
                        <li  class="name-pad"><strong>Created By:</strong> <?= $event_info['0']['s_profile_name'] ?></li>
                    </ul>
                </div>
<!--sub page links -->
                              <?php include("event_home_menu.phtml")?>                               
                              <!--/sub page links -->
							   <?php
               //pr($event_info);

                $event_info = $event_info[0];
                $id = $event_info['id'];
                $title = $event_info['s_title'];
                $desc = html_entity_decode(htmlspecialchars_decode($event_info['s_desc']), ENT_QUOTES, 'utf-8');
                $country = get_country_name_by_id($event_info['i_country_id']);
                $address = $event_info['s_address'] . ', ' . $event_info['s_city'] . ', ' . $event_info['s_state'] . ', ' . $country;
                $IMG_THUMB_PATH = base_url() . "uploads/events_photo/";
                $main_name = getThumbName($event_info['s_image_1'], 'mid_FO');
                $MAIN_IMG_THUMB = $IMG_THUMB_PATH . $main_name;

                $name_5 = getThumbName($event_info['s_image_5'], 'thumb');
                $IMG_THUMB_5 = $IMG_THUMB_PATH . $name_5;

                $name_2 = getThumbName($event_info['s_image_2'], 'thumb');
                $IMG_THUMB_2 = $IMG_THUMB_PATH . $name_2;

                $name_3 = getThumbName($event_info['s_image_3'], 'thumb');
                $IMG_THUMB_3 = $IMG_THUMB_PATH . $name_3;

                $name_4 = getThumbName($event_info['s_image_4'], 'thumb');
                $IMG_THUMB_4 = $IMG_THUMB_PATH . $name_4;
                $logged_user_id = intval(decrypt($this->session->userdata('user_id')));
                ?>
                <ul class="pre-time">
                    <li><strong>Venue:</strong> <?= $address ?></li>
                    <li>I</li>
                    <li><strong>Time:</strong> <?= getShortDateWithTime($event_info['dt_start_time'], 6) ?></li>
                    <li>I</li>

                    <?php
                    if ($this->session->userdata('loggedin')):
                        ?>
                        <li><?php if ((show_event_rsvp($event_info['id']) == TRUE) && $event_info['event_owner_id'] != $logged_user_id) { ?><span id="send_rsvp_<?= $event_info['id'] ?>"> <a  href="javascript:void(0);" onclick="send_rsvp(<?= $event_info['id'] ?>)">Send RSVP</a></span><?php } ?></li>
                        <?php
                    else:
                        ?>
                        <li > <a onclick="show_login_popup('<?= base64_encode(my_current_url()) ?>')" href="javascript:void(0);">Send RSVP</a></li>
                    <?php
                    endif;
                    ?>  

                </ul>
                <br class="clear"/>

                <div class="arrow_btm"></div>
                <!--event start -->
                <div class="shade_box_01">

                    <!--content section start -->
                    <div class="pre-time-upcoming-content">
                        <div  style="background:url(<?= $MAIN_IMG_THUMB ?>) no-repeat center;" class="pre-time-upcoming-content-img" title="upcoming event"  ></div>
                        <p><?= nl2br($desc) ?></p>

                        <!--right part -->
                        <div class="pre-time-map">                               


                            <?php
                            # if map longitude-latitude data available...
                            if (strtolower($geodata['status']) == 'ok') :
                                ?>
                                <div class="map" id="map_canvas">
                                    <?php 
                                      echo $mapshow->printGMapsJS();
                                      echo $mapshow->showMap(false); 
                                    ?>
                                </div>
                                <?php
                            endif;
                            ?>

                        </div>
                        <!--/right part -->



                        <br class="clear" />
                        <a href="javascript:void(0);" class="pre-time-image-thumb" onclick="return open_zoom_lightbox(1,<?= $id ?>)">
                        	<img alt="upcoming event" src="<?= $MAIN_IMG_THUMB ?>" width="80" height="80" />
                        </a>
                        <?php if ($event_info['s_image_2'] != '') { ?>
                            <a href="javascript:void(0);" class="pre-time-image-thumb" onclick="return open_zoom_lightbox(2,<?= $id ?>)">
                            <img alt="upcoming event" src="<?= $IMG_THUMB_2 ?>"  width="80" height="80" /></a>
                        <?php } ?>

                        <?php if ($event_info['s_image_3'] != '') { ?>
                            <a href="javascript:void(0);" class="pre-time-image-thumb" onclick="return open_zoom_lightbox(3,<?= $id ?>)">
                            <img alt="upcoming event" src="<?= $IMG_THUMB_3 ?>"  width="80" height="80" /></a>
                        <?php } ?>

                        <?php if ($event_info['s_image_4'] != '') { ?>
                            <a href="javascript:void(0);" class="pre-time-image-thumb" onclick="return open_zoom_lightbox(4,<?= $id ?>)">
                            <img alt="upcoming event" src="<?= $IMG_THUMB_4 ?>"  width="80" height="80" /></a>
                        <?php } ?>

                        <?php if ($event_info['s_image_5'] != '') { ?>
                            <a href="javascript:void(0);" class="pre-time-image-thumb" onclick="return open_zoom_lightbox(5,<?= $id ?>)">
                            <img alt="upcoming event" src="<?= $IMG_THUMB_5 ?>"  width="80" height="80" /></a>
                        <?php } ?>
                        <br class="clear" />
                    </div> 
                    <!--content section end --> 

					<br class="clear"/>
                    <div class="report-abuse">
                          <a class="link-report" href="javascript:void(0);">Report abuse</a>
                          <div class="text-section" style="margin-left:1%; width:95%;">
                              <form id="frm_report_abuse" onSubmit="return false;">
                                  <textarea rows="5" cols="5" id="txt_abuse_profile_text"></textarea>
                                  <input type="button" class="yellow-btn" value="Send" onclick="report_abuse_profile()"/>
                              </form>
                          </div>
                      </div>
                                    
                                    
                    <!--comment section start -->
					
					
                    <div class="pre-time-upcoming-content">

                        <div class="div_content">
                            <div class="nwheading">
                                <div class="left">
                                    <h4>Comment  &amp;   Support</h4>
                                </div>
                            </div>

                        </div>


                        <form action="" method="post" enctype="multipart/form-data" class="comment-form">
                            <div class="textarea-div">
                                <textarea id="feed_comment_box_<?= $id ?>" class="pre-time-textarea" onFocus="if(this.value=='Max 500 Char allowed') this.value='';" onBlur="if(this.value=='')this.value='Max 500 Char allowed'; " onkeypress="return restrict_carrige(event);" >Max 500 Char allowed</textarea>
                                <span class="error-message"></span>
                                <p style=" clear:both; float:left"> <span id="text_count">0</span> Characters</p>
                            </div>
                            <div class="clr"></div>

                            <?php
                            if ($this->session->userdata('loggedin')):
                                ?>
                                <input name="" type="button" value="Post" class="pre-time-submit" onclick="post_events_comment_ajax(<?= $id ?>)" />
                                <?php
                            else:
                                ?>

                                <input name="" type="button" value="Post" class="pre-time-submit"   onclick="return show_login_popup('<?= base64_encode(my_current_url()) ?>')" />
                            <?php endif; ?>
                        </form>
                        <br class="clr" />



                        <div class="div_content">
                            <div class="nwheading">
                                <div class="left">
                                    <?php if ($comments_content != '') { ?>
                                        <h4 class="comment-support">View Comments</h4>

                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        
                        <DIV id="comment_div"><?= $comments_content ?></DIV>



                        <?php if ($no_comments > $pagination_per_page): ?>

                            <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?= $current_page ?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
                        <?php endif; ?>

                        <input type="hidden" id="i_curr_event_id" value="<?= $i_event_id ?>" />
                    </div>
                    <!--comment section end --> 
					
					<!-- feedback -->
					 <div class="pre-time-upcoming-content">
                        <div class="div_content">
                            <div class="nwheading">
                                <div class="left">
                                    <?php if ($feedback_content != '') { ?>
                                        <h4 class="comment-support">View Feedbacks</h4>

                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        
                        <DIV id="feedback_div"><?=$feedback_content ?></DIV>



                        <?php if ($no_feedback > $feedback_pagination_per_page): ?>

                            <div class="view_more" id="show_more_feedbacks_div"><a href="javascript:void(0);" id="show_more_feedbacks_link" page_value="<?= $current_page_feedback ?>" onclick="show_more_feedbacks($(this).attr('page_value'))">[view more] </a> </div>
                        <?php endif; ?>

                        
                    </div>
</div>
             
                <!--event end -->

                <div class="clr"></div>

            </div>
            <!-- /left container -->
            <!-- right container -->
            <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
            <!-- /right container -->
        </div>
        <!-- /main container -->
        <div class="clr"></div>

        <!--        <div id="bot_corner">&nbsp;</div>-->
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<?php
# include footer file...
include_once(APPPATH . "views/layouts/footer.phtml");
?>


<script type="text/javascript">

    var ajax_req_feeds = null;
	var ajax_req_feedbacks = null;
    function show_more_feeds(page) {

        var event_id = $('#i_curr_event_id').val();
        if (ajax_req_feeds != null) {
            ajax_req_feeds.abort();
        }
        showUILoader_nodialog();
        ajax_req_feeds = $.ajax({
            type: 'get',
            url: base_url + 'logged/events/comments_ajax_pagination/' + event_id + '/' + page,
            dataType: 'json',
            success: function(data, status) {


                hideUILoader_nodialog();
                if (data.html != '') {

                    //alert(data.cur_page+'dfdf');
                    $('#comment_div').append(data.html);
                    $('#show_more_feeds_link').attr('page_value', data.cur_page);
                    $('#show_more_feeds_link').attr('onclick', '');
                    $('#show_more_feeds_link').attr('onclick', 'show_more_feeds(' + data.cur_page + ')');
                }
                else {
                    $('#comment_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Comments.</p></div>');
                    $('#show_more_feeds_div').remove();
                }

                if (data.view_more == false)
                {

                    $('#comment_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Comments.</p></div>');
                    $('#show_more_feeds_div').remove();
                }


            }	// end of success function...
        });
    }
	
	function show_more_feedbacks(page) {

        var event_id = $('#i_curr_event_id').val();
        if (ajax_req_feedbacks != null) {
            ajax_req_feedbacks.abort();
        }
        showUILoader_nodialog();
        ajax_req_feedbacks = $.ajax({
            type: 'get',
            url: base_url + 'logged/events/feedback_ajax_pagination/' + event_id + '/' + page,
            dataType: 'json',
            success: function(data, status) {


                hideUILoader_nodialog();
                if (data.html != '') {

                    //alert(data.cur_page+'dfdf');
                    $('#feedback_div').append(data.html);
                    $('#show_more_feedbacks_link').attr('page_value', data.cur_fpage);
                    $('#show_more_feedbacks_link').attr('onclick', '');
                    $('#show_more_feedbacks_link').attr('onclick', 'show_more_feedbacks(' + data.cur_fpage + ')');
                }
                else {
                    $('#feedback_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More feedbacks.</p></div>');
                    $('#show_more_feedbacks_div').remove();
                }

                if (data.view_more_feedback == false)
                {

                    $('#feedback_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More feedbacks.</p></div>');
                    $('#show_more_feedbacks_div').remove();
                }


            }	// end of success function...
        });
    }
</script>



<script type="text/javascript">

    var ticker_holder = $('.bargaining').get(0);
    var ticker_text = $('.ticker').get(0);
    var ticker_pos = ticker_text.parentNode.offsetWidth;

    var ticker_data = $(ticker_holder).html();
    $(ticker_text).parent().html('<marquee scrollamount="3" scrolldelay="20">' + ticker_data + '</marquee>');

   /* $('#sub-nav').hover
            (
                    function() {
                        $('marquee', this).get(0).stop();
                    },
                    function() {
                        $('marquee', this).get(0).start();
                    }
            );*/

</script> 


<script type="text/javascript">

// show zoom window...
    function open_zoom_lightbox(image_no, id) {
        //alert(image_no);
        var url = base_url + 'events/zoom_photo/' + image_no + '/' + id + '?width=800&height=536';
        tb_show('zoom_img', url);
    }

 
 function report_abuse_profile(){
	
	  if($('#txt_abuse_profile_text').val() == ''){
		  showUIMsg('Please provide reason.');
		  return false;
	  }
	  showUILoader_nodialog();
	  $.ajax({
		  type: 'post',
		  url: base_url + 'public_profile/abuseMedia/'+<?= $event_info['id'] ?>+'/event',
		  data: {'s_reason':$('#txt_abuse_profile_text').val()},
		  dataType: 'json',
		  success: function(data, status) {
			  
			  showUIMsg(data.msg);
			  $('#txt_abuse_profile_text').val('');
			  $('.link-report').trigger('click');
			  hideUILoader_nodialog();
		  }	// end of success function...
	  });
  }
  
 var carriage_count = 0;
$(document).ready(function() {

 
  $('.link-report').click(function(){
	  //alert('hi');
	  $('.text-section').stop(true, true).slideToggle('slow');
  });
 $(function(){
  $('#feed_comment_box_<?= $id ?>').keyup(function(){
	  count=1;
  limitChars('feed_comment_box_<?= $id ?>', 500, '');
  });
  $('#feed_comment_box_<?= $id ?>').keydown(function(){
	  count=1;
  limitChars('feed_comment_box_<?= $id ?>', 500, '');
  });
});


//// just to show correct no. of chracters left while the page is loaded...
limitChars('feed_comment_box_<?= $id ?>',500, '');

});
var count=0;
//counting the left characters in comment
function limitChars(textid, limit, infodiv)
{
	
  var text = $('#'+textid).val(); 
  
  if(text == ''){
	  count = 0;
  }
 


if( count == 0)
{
	//alert (carriage_count)
  var textlength = 0;
}
else
{
 var textlength = text.length;
}
  $('#text_count').html(textlength);
  if(textlength > limit)
  {
  $('#'+textid).val(text.substr(0,limit));
  return false;
  }
  else
  {
  return true;
  }
  
}




function restrict_carrige(e)
{
	/*//if(e.keyCode == 13)
	{
		$.ajax({
			type: 'post',
			url: base_url+'logged/prayer_wall/getCarriageCount',
			data: {'str':$('#ta_desc').val()},
			dataType: 'json',
	
			success: function (data, status) {
				
					if(data.count > 1){
						return false;
					}
				
				}	// end of success function...
		});
	}*/
	//alert($('#ta_desc').val().replace(/\r/g,"\r").replace(/\n/g,"\n"));

	if(e.keyCode == 13){
		carriage_count++;
		console.log(carriage_count);
	}
	/*if(e.keyCode == 8){
		carriage_count--;
	}*/
	if(e.keyCode == 13 && carriage_count >10){
		return false;
		//e.preventDefault();
	}
}

</script>
<script type="text/javascript" src="<?= base_url() ?>js/switch.js"></script>