<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->
</div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script>
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
<div id="content_section">
    <div id="container">
        <div id="top_corner">&nbsp;</div>
        <div id="mid_content">
            <!-- latest news -->
            <?php include(APPPATH . "views/layouts/latest_news.phtml"); ?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div id="main_container">

                <!-- left container -->
                <?php include(APPPATH . "views/layouts/leftbar.phtml"); ?>
                <!-- /left container -->

                <!-- mid container -->
                <div id="mid_container">
                    <div class="link-div" style="margin-top:-2px;">
                        <ul>
                            <li><a href="all-events.html" class="<?php echo ($page_name == 'all-events') ? 'current' : ''; ?>"><span>All Events</span></a> </li>
                            <li><a href="find-events.html" class="<?php echo ($page_name == 'find-events') ? 'current' : ''; ?>"><span>Search Events</span></a> </li>	
                            <li><a href="my-events.html" class="<?php echo ($page_name == 'my-events') ? 'current' : ''; ?>"><span>My Events</span> </a> </li>
                            <li><a href="create-event.html" class="<?php echo ($page_name == 'create-event') ? 'current' : ''; ?>"><span>Create Event</span> </a> </li>
                            <li><a href="event-invitations-received.html" class="<?php echo ($page_name == 'event-invitations-received') ? 'current' : ''; ?>"><span>Event Invitations Received</span></a> </li>
                            <li><a href="archived-events.html" class="<?php echo ($page_name == 'archived-events') ? 'current' : ''; ?>"><span>Archive</span></a> </li>
                            <li><a href="events-rsvp-recevied.html" class="<?php echo ($page_name == 'events-rsvp-recevied') ? 'current' : ''; ?>"><span>Event RSVPs Received</span></a> </li>

                        </ul>
                        <div class="clr"></div>
                    </div>
                    <div class="clr"></div>
                    <div class="page_heading">
                        <div class="left">Find Events</div>                        
                    </div>

                    <div class="arrow_btm"></div>
                    <div class="find-church-mid">

                        <div class="register-your-church-form">
                            <form id="frm_srch" method="post" onsubmit=" return false;">
                                <div class="lable-form-nw"> Event Name:</div>
                                <input type="text"  name="txt_name" id="txt_name1" />
                                <div class="clr"></div>

                                <div class="lable-form-nw">Address:</div>
                                <input type="text"  name="txt_address" id="txt_address1"/>
                                <div class="clr"></div>

                                <div class="lable-form-nw"> Postcode:</div>
                                <input type="text" name="txt_postcode" id="txt_postcode1"/>
                                <div class="clr"></div>

                                <!--                                <label style="width:32px;" >Start Date :</label>-->
                                <div class="lable-form-nw"> Start Date :</div>
                                <input type="text"  value="" name="date_to1" id="date_to1"   class="date-field"/>
                                <!--<img src="<?= base_url(); ?>images/icons/cal.png" alt="" onclick="$(this).prev().focus()" class="calender" style="margin-right:35px;" />-->
                               
                                 <script type="text/javascript">
                $(document).ready(function(arg) {
                    $.datepicker.setDefaults($.datepicker.regional['']);
                    $("#date_to1").datepicker({
                                            regional: 'en',
                                            dateFormat: 'dd/mm/yy',
                                        });
                    //$("").datepicker($.datepicker.regional['en']);

                });
          </script>
                                <div class="lable-form-nw"> End Date :</div>
                                <input type="text"  value="" name="date_end1" id="date_end1"   class="date-field" style=""/>
                               <!-- <img src="<?= base_url(); ?>images/icons/cal.png" alt="" onclick="$(this).prev().focus()" class="calender" style="margin-right:35px;" />-->
                                <script type="text/javascript">
                                    $(document).ready(function(arg) {
                                        $.datepicker.setDefaults($.datepicker.regional['']);
                                        $("#date_end1").datepicker({
                                            regional: 'en',
                                            dateFormat: 'dd/mm/yy',
                                        });


                                    });
                                </script>
                                <!--                                <div class="clr"></div>
                                                                <div class="lable-form-nw">Location: </div>
                                                                <div class="field01">
                                                                    <input name="txt_location" id="txt_location" type="text" value="<?= $this->session->userdata('location') ?>" style="width:463px;"/>
                                                                </div>
                                                                <div class="clr"></div>
                                                                <div style="font-weight: normal;font-size: 11px;font-style: italic; ">(Note : Please use ',' (comma) between places.) </div> 
                                                                <div class="clr"></div>
                                
                                                                <div class="lable-form-nw"> Phone No.:</div>
                                                                <input type="text" name="txt_phone" />
                                                                <div class="clr"></div>-->

                                <div class="lable-form-nw"> 
                                    <input type="submit" class="yellow-btn register-your-float-right click-church" value="Search" name="" />
                                </div>
                                <input type="hidden" value="Y" name="search_basic" id="search_basic"  />
                                <div class="clr"></div>
                            </form>
                        </div>
                    </div>
                    <!--                    <a href="javascript:void(0)" class="ModifySearch">Modify Search</a>-->

                    <DIV ID="main_div" style="display:none;" >
                        <div class="nw-right-heading search-heading-section">
                            <?php
                            if (!empty($church_content)) {
                                ?>
                                <div class="left">
                                    <h4>Search Results</h4>
                                </div>
                            <?php } ?>
                        </div>

                        <ul class="search-list-display" id="church_content">
                            <?= $church_content ?>

                        </ul>




                    </DIV>
                    <?php if ($no_of_result > $pagination_per_page): ?>

                        <div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_records_link" page_value="<?= $current_page_1 ?>" onclick="show_more_records($(this).attr('page_value'))">[view more] </a> </div>
                                                            <!--<div class="view_more" id="show_more_feeds_div"><a href="<?= base_url() ?>events/ajax_pagination/<?= $current_page_1 ?>" id="show_more_feeds_link" page_value="<?= $current_page_1 ?>" >[view more] </a> </div>-->
                    <?php endif; ?>  


                </div>
                <!-- mid container -->
                <!-- right container -->
                <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
                <!-- /right container -->

                <div class="clr"></div>


            </div>
        </div>
        <!-- /main container -->
        <div class="clr"></div>
    </div>
    <div id="bot_corner">&nbsp;</div>
</div>
<div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>

<!-- FOOTER SECTION -->
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>
<!-- /FOOTER SECTION -->
<!--/map section-->

<div class="bot"><div>&nbsp;</div></div>
</div>
<!--map section end-->
<script type="text/javascript">
    $(document).ready(function(arg) {


        $('#frm_srch').submit(function() {
            var event_name = $('#txt_name1').val();
            var address = $('#txt_address1').val();
            var postcode = $('#txt_postcode1').val();
            var start_date = $('#date_to11').val();
            var end_date = $('#date_end11').val();
            var cnt = '';
            //alert(event_name);
            if (event_name == '' && address == '' && postcode == '' && start_date == '' && end_date == '') {
                cnt = 1;
            } else {
                cnt = 0;
            }
            //alert(cnt);
            if (cnt == 1) {
                showUIMsg("Please enter value for atleast one field");
                return false;
            }
            if (event_name != '' && event_name.length < 3) {
                showUIMsg("Please give atleast three letters text in church name field.");
                return false;
            }
            else {

//                $('.ModifySearch').css('display', 'block');
//                $('.register-your-church-form').slideUp('slow');

                var datatosend = $("#frm_srch").serialize();
                showBusyScreen();
                $.ajax({
                    type: "POST",
                    url: base_url + "logged/events/search_events_ajax_pagination/",
                    data: datatosend,
                    dataType: 'json',
                    success: function(data) {
                        hideBusyScreen();

                        $('#main_div').show();
                        $('#show_more_div').remove();
                        $('#church_content').html('');
                        if (data.html != '') {
                            //$('#no_project').hide();el
                            $('#church_content').html(data.html);
                        }
                        if (data.view_more == true)
                        {
                            cur_page = data.cur_page;
                            $('#main_div').append('<div class="custom_show view_more" id="show_more_div" style="width:475px;"><a href="javascript:void(0);" id="show_more_records_link" page_value="' + cur_page + '" onclick="show_more_records(' + cur_page + ')">[view more] </a> </div>');

                        }

                    }
                });
            }
        });


    });

    var ajax_req_feeds = null;
    function show_more_records(page) {

        if (ajax_req_feeds != null) {
            ajax_req_feeds.abort();
        }

        showUILoader_nodialog();
        ajax_req_feeds = $.ajax({
            type: 'get',
            url: base_url + 'logged/events/search_events_ajax_pagination/' + page,
            dataType: 'json',
            success: function(data, status) {
                $('#show_more_div').remove();
                hideUILoader_nodialog();
                if (data.html != '') {

                    $('#church_content').append(data.html);
                    $('#show_more_records_link').attr('page_value', data.cur_page);
                    $('#show_more_records_link').attr('onclick', '');
                    $('#show_more_records_link').attr('onclick', 'show_more_records(' + data.cur_page + ')');
                }
                else {
                    $('#church_content').append('<div class="view_more " style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Church.</p></div>');
                    $('#show_more_div').remove();
                }

                if (data.view_more == true)
                {
                    cur_page = data.cur_page;
                    $('#main_div').append('<div class="custom_show view_more" id="show_more_div" style="width:475px;"><a href="javascript:void(0);" id="show_more_records_link" page_value="' + cur_page + '" onclick="show_more_records(' + cur_page + ')">[view more] </a> </div>');

                }

                if (data.view_more == false)
                {

                    $('#church_content').append('<div class="view_more " style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No More Church.</p></div>');
                    $('#show_more_div').remove();
                }


            }	// end of success function...
        });
    }
</script>
<script>
    $(function() {
        /*var m= "2220 AUGY,2220 BAZOCHES-SUR-VESLES,2220 BRAINE,2220 BRENELLE";
         alert(m.replace(/[,]/g,"<br>"));*/

        $("#txt_location").autocomplete("<?php echo base_url(); ?>logged/prayer_wall/send_cities", {
            width: 473,
            selectFirst: true,
            minChars: 3,
            multiple: false,
            multipleSeparator: "\n",
            max: null,
            //matchContains: false,
            formatItem: formatItem
        });




    });

    function formatItem(row)
    {//console.log(row);
        //var n=row[0].replace(/[,]/g,"\n"); console.log(n);	
        if (row[0] != "No match found")
            return  "<span style='font-size:11px; font-weight:normal; margin:0px; padding: 3px 5px ;cursor: pointer; display:block;'>" + row[0] + "</span>";
        else
            return " (<span style='font-size:11px;'>" + row[0] + "</span>)";
    }


    function show_map(id)
    { //alert(id);

        if ($('#map_div' + id).css('display') == "none") {
            showBusyScreen();
            $.ajax({
                type: "POST",
                url: base_url + "logged/build_the_kingdom/view_map/" + id,
                dataType: 'json',
                success: function(data) {
                    hideBusyScreen();
                    if (data.success == true) {
                        $('#map_div' + id).html(data.html)
                        $('#map_div' + id).slideToggle('slow');
                        showmap();
                    }
                    else
                        showUIMsg("Please check address.");
                    //$('#map_container').contents().find('html').html(data.html);
                    //show_dialog('map-page-popup');
                }
            });
        }
        else {
            $('#map_div' + id).slideToggle('fast');
        }

    }


</script>

