<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- left container -->
                        <div id="mid_container">
                        	<div class="page_heading">
                            	<div class="left"><img src="images/icons/event.png" alt="" width="35" height="39"/> Event</div>
                             </div>
                            <!--sub page links -->
                               <div class="link-div" style="margin-top:-2px;">
                              	<ul>
                                <li><a href="all-events.html" class="<?php echo ($page_name=='all-events')?'current':'';?>"><span>All Events</span></a> </li>	
                                    <li><a href="my-events.html" class="<?php echo ($page_name=='my-events')?'current':'';?>"><span>My Events</span> </a> </li>
                                	<li><a href="create-event.html" class="<?php echo ($page_name=='create-event')?'current':'';?>"><span>Create Event</span> </a> </li>
                                    <li><a href="event-invitations-received.html" class="<?php echo ($page_name=='event-invitations-received')?'current':'';?>"><span>Event Invitations Received</span></a> </li>
                                     <li><a href="archived-events.html" class="<?php echo ($page_name=='archived-events')?'current':'';?>"><span>Archive</span></a> </li>
                                     <li><a href="events-rsvp-recevied.html" class="<?php echo ($page_name=='events-rsvp-recevied')?'current':'';?>"><span>Event RSVPs Received</span></a> </li>
                                
                                </ul>
                                <div class="clr"></div>
                              </div>
                            <!--/sub page links -->
                            
                            
                             <div class="arrow_btm"></div>
                            <DIV  id="invitaion_rec"><?=$events_ajax_content?></DIV>
                            
                            
                            <?php if($no_of_result  == 0):?>
                                <div class="shade_box_01" style="padding-top:5px;"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Event.</p></div></div>
                                <?php endif;?>	
                                <?php if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?=$current_page_1?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
                                 <?php endif; ?>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<!-- /lightbox SECTION -->

<div class="lightbox view_comments_div" style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="images/icons/cmnt.png" alt="" width="30" height="30"/> View Comments </h4>
                  </div>
            </div>
               <div id="comment_html"></div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<!--POST COMMENT LIGHTBOX -->
<div class="lightbox comment_div" style="width:540px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
     
            <div class="heading">
                  <div class="left">
                        <h4><img src="images/icons/coment.png" alt="" height="20" width="20"/> Post Comment </h4>
                  </div>
            </div>
            <div class="frm_box">
                  <p>
                    <textarea  class="feed_comment_box" cols="" rows="" style="width:486px; height:100px; margin-bottom:10px;"></textarea>
                  </p>
                  	<input type="hidden" name="i_event_id" id="i_event_id" value=""/>
                  <p>
                    <input class="submit-green" id="post_comment_button" type="button"  style="margin-top:15px;" value="Post" name="" onclick="post_comment();" />
                  </p>
                  
            </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div> 
<!--POST COMMENT LIGHTBOX -->


<div class="lightbox post_feedback_div" style="width:540px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading">
                  <div class="left">
                        <h4><img src="images/icons/feedback.png" alt="" width="18" height="17"/> Post Feedback </h4>
                  </div>
            </div>
            <div class="frm_box">
                 
               
                      <p>  <textarea name="" cols="" rows="" style="width:486px; height:100px; margin-bottom:10px;"></textarea></p>
             
                       <p> <input name="" type="button" value="Post"  class="btn"/></p>
             </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_feeds(page) {
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/my_events/events_rsvps_recieved_ajax_pagination/<?=$profile_id?>'+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#invitaion_rec').append(data.html);
				$('#show_more_feeds_link').attr('page_value', data.current_page);
			}
			else {
				$('#invitaion_rec').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Event.</p></div>');
				$('#show_more_feeds_div').hide();
			}
            
            if(data.view_more==false)
            {
                
                $('#invitaion_rec').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Event.</p></div>');
                $('#show_more_feeds_div').hide();
            }
			
			
		}	// end of success function...
	});
}
</script>
