 <div class="div_content" style=" margin-top:0px;">
   <?php //pr($arr_events);
		  if(count($arr_events) > 0){
			  foreach($arr_events as $val){
				  $title = $val['s_title'];
				  $desc = my_substr(html_entity_decode(htmlspecialchars_decode($val['s_desc']),ENT_QUOTES,'utf-8'), 285);
				  $country = get_country_name_by_id($val['i_country_id']);
				  $address = $val['s_address'].', '.$val['s_city'].', '.$val['s_state'].', '.$country;
				  $detail_url = get_events_detail_url($val['id']);
				 
				  $profile_img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);  
				  
				  $IMG_THUMB_PATH = base_url() ."uploads/events_photo/";
				  $main_name=getThumbName($val['s_image_1'],'mid_FO'); 
				  $MAIN_IMG_THUMB = $IMG_THUMB_PATH . $main_name;
				  
				  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
				  	$profile_link = get_profile_url($val['event_owner_id'],$val['s_profile_name']);
				  }else
				  {
					 $profile_link = get_public_profile_url($val['event_owner_id'],$val['s_profile_name']); 
				  }
				  
				  $IMG_THUMB_PATH = base_url() ."uploads/events_photo/";
				  $main_name=getThumbName($val['s_image_1'],'thumb'); 
				  $MAIN_IMG_THUMB = $IMG_THUMB_PATH . $main_name;
				  
				  
								
   ?>   				  
                         <div class="blog-container">
                            
                                 <div class="blog">
                                      <h2><a href="<?=$detail_url?>"><?=$title?></a></h2>
                                      <p class="time-posted">Created on <?=getShortDateWithTime($val['dt_created_on'],6)?> by: <a href="<?=$profile_link?>"><?=$val['s_profile_name']?></a></p>
                                      
                                      <!--event block highlighted start -->
                                      <div class="event-schidule">
                                      	<p style="font-weight: normal;"><span>Venue:</span> <?=$address?></p>
                                        <p style="font-weight: normal;"><span>Time:</span> <?=getShortDateWithTime($val['dt_start_time'], 6)?></p>
                                      </div>
                                      <!--event block highlighted end -->
                                      <div class="pro_photo2" style="background:url(<?=$MAIN_IMG_THUMB?>) no-repeat center;width:60px; height:60px;" ></div>
                                      <p><?=nl2br($desc)?></p> 
                                      
                                      
                                      <div class="clr"></div>
                                      <ul class="article-comment-block article-comment-block2">
                                          
                                      <li  class="first" id="send_rsvp_<?=$val['id']?>"><img src="images/icons/send.png" alt=""  width="16" height="13" class="icon-img" height="16" width="16"/> <a href="javascript:void(0);" class="blue_link" >RSVP Recieved (<?=$val['total_rsvp']?>) </a></li>
                                      
                                      </ul>
									  
									  
									  <div class="new-wl">
										
											<!--comment section start-->
											 <div  class="comments-number content-width" >
                                          
                                              <div class="comments-number-mid">
                                                  <div class="heading">
                                                        <div class="left">
                                                              <h4><img class="cmnt" src="images/icons/icon-14.png" alt="" style="margin-top:-2px;"/><span  class="comments_div<?=$val['id']?>">  RSVPs Recieved (<?=$val['total_rsvp']?>) </span></h4>
                                                              <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                                                        </div>
                                                  </div>
                                                  <?php 
												  
													 $rsvp_list_arr = $val['rsvp_list'];
												  	if(count($rsvp_list_arr)){
														foreach($rsvp_list_arr as $k=> $rval){
															
 														$RSVP_profile_img = get_profile_image_of_user('thumb',$rval['s_profile_photo'],$rval['e_gender']);  
												  ?>
                                                 <div class="txt_content01 comments-number-content"> 
                                                    <a href="javascript:void(0);"><div style="background:url('<?=$RSVP_profile_img?>') no-repeat center;width:60px; height:60px;" class="pro_photo" ></div></a>
                                                        <div class="left-nw-wal">
                                                              <p class="blue_bold12"><a href="javascript:void(0);"><?=$rval['s_profile_name']?></a></p>
                                                                 <p class="date-time">Sent on: <?=get_time_elapsed($rval['rsvp_dt'])?></p>
                                                        </div>
                                                        <div class="clr"></div>
                                                  </div>
                                                  
                                                  <?php }
													}
													else{
														echo '<div style="margin-top:5px;">No RSVPs received yet!</div>';
												   } ?>
                                                  
                                            </div>
                                         
                                        </div>
											<!--comment section end-->
									  </div>
									  									  
                                      <div class="clr"></div>
                                  </div>
                            
                            </div>
                                   
                          <script type="text/javascript">
							$(function(){
							$('.article-comment-block li').click(function(){
								$('.new-wl > .comments-number').css('display','none');
									var index= $(this).index();
									//alert(index);
									$(this).parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
								});
								$('.wal-minus').click(function(){
									$(this).parents('.comments-number').slideUp('fast');
								});
							
							});
						</script>
         
                                   
    <?php 
			 	 }
			 }
	?>       
 </div>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page_1?>"  />
