						<table width="100%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                              <tr>
                                <th align="left" valign="middle" height="30" width="80">Date Posted</th>
                                <th align="left" valign="middle" height="30" width="200">Church Name</th>
                                <th align="left" valign="middle" height="30" width="400">Location</th>
                                <th align="left" valign="middle" height="30" width="80">Post Code</th>
                                <th align="left" valign="middle" height="30" width="120">Phone No</th>
                                <th align="center" valign="middle" height="30" class="last">Actions</th>
                              </tr>
                              
                              <?php
							  //   pr($info_arr);
							  		if(count($info_arr)){
										foreach($info_arr as $key=> $info){
											$s_status = ($info['i_disabled'] == 1)?'Deny':'Approve';	 		
							  ?>
                              <?php if($info['i_disabled']==1){?>
							  
                              <tr id="req_row_<?=$info['id']?>">
                              <?php } else {?>
                              <tr id="req_row_<?=$info['id']?>" class="highlight" >
                              <?php }?>
                                <td align="left" valign="top"><?=getShortDate($info['dt_created_on'],5)?></td>
                                <td align="left" valign="top"><?=$info['s_name']?></td>
                                <td align="left" valign="top"><?=get_cityname($info['i_city_id'])?>, <?=get_statename($info['i_state_id'])?>, <?=get_countryname($info['i_country_id'])?></td>
                                <td align="left" valign="top"><?=$info['s_postcode']?></td>
                                <td align="left" valign="top"><?=$info['s_phone']?></td>
                                <td align="center" valign="middle" class="last">
                                <input name="" title="Edit" type="button" class="edit-button"  value="" onclick="show_edit(<?=$info['id']?>)"/>
                                <input name="" title="Delete" type="button" class="delete-button"  value="" onclick="delete_church(<?=$info['id']?>)"/>
                                 <?php if($info['i_disabled'] == 1){ ?>
                            		<span id="<?=$info['id']?>_status">
                                    <input name="" title="Approve" type="button" class="btn-06"  onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 2 , <?php echo $info['i_disabled'] ?>)"  value="<?=$s_status?>"/>
                                    </span>
									<?php 
                                        } 
                                        else if($info['i_disabled'] == 2){?>
                                            <span id="<?=$info['id']?>_status">
                                            <input name="" title="Deny" type="button" class="btn-06"  onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 1 , <?php echo $info['i_disabled'] ?>)"  value="<?=$s_status?>"/>
                                            </span>
                                    
                                    <?php }
                                    
                                    
                                    ?>
                                        <?php
                                   if($info['ch_space_enable'] == 1 && $info['ch_page_url'] != '' ){
                                        ?>
                                <img class="add-new-church" width="25" height="14" alt="crown" src="<?= base_url() ?>images/icons/crown.png" style="cursor: pointer" onclick="go_details(<?=$info['id']?>)">
                                            <?php
                                    }
                                    ?>
                                
                                </td>
                              </tr>
                              <?php
										}
									}
										else{
							?>
								<tr>
									<td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
								</tr>
							<?php
									}
							?>
 </table>


<div class="paging" >
            <ul><?= $page_links ?></ul>
</div>	
<script type="text/javascript">
$(document).ready(function()
{
	$(".highlight").children('td').css("background-color","#E5E5E5");
	
});
function go_details(id){
    //alert(id);
    window.location.href=admin_base_url+'admin/build_kingdom/churches/space_view/'+id
}
</script>