<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Salvation Prayer</div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area frm_box">
                        
                      
                        
                        <form id="salavtion_frm" action="" method="post" enctype="multipart/form-data" onsubmit="return form_post();">
                                  <div class="lable01">Welcome message : </div>
                                  <div class="field02">
                                        <textarea name="ta_welcome_msg" cols="" rows="" class="small"><?=$res['s_welcome_msg']?></textarea>
                                  </div>
                                  <div id="err_welcome_msg" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Being a Christian : </div>
                                  	  <div class="file-browse-container">
                                      <?php 
									  		if(count($photo_arr)){
												foreach($photo_arr as $key=>$p_val){
													
													$IMG = base_url()."uploads/salvation_prayer_photos/".getThumbName($p_val['s_photo_name'],'thumb');
									  ?>
                                     	
                                         <!--img upload section-->
                                             <div id="img_sec<?=$key+1?>">
                                                <div class="img-upload-section">
                                                    <input name="s_edit_photo_<?=$p_val['id']?>" type="file" size="48" class="file-browsing"/>
                                                    <?php if($key != 0){?>
                                                    <span onclick="removeExtraImageDiv(<?=$p_val['id']?>, <?=$key+1?>)"><img alt="" src="<?= base_url()?>images/icons/close.png" class="close-img" /></span>
                                                    <?php }?>
                                                  <div class="add-photo">
                                                      <img src="<?=$IMG?>" alt="" height="80" width="122"/>
                                                  </div>
                                                 </div>
                                                 <input type="hidden" name="db_photo_id[]" value="<?=$p_val['id']?>" />
                                                 <input type="hidden" name="db_photo_arr[]" value="<?=$p_val['s_photo_name']?>" />
                                                 <div class="clr"></div>
                                            </div>
										  <!--img upload section-->
                                          
                                            <?php 		}
											}
									 ?>
                                     
                                          <div id="add_more_images"></div>
                                          <div class="clr"></div>
                                          <a href="javascript:void(0);" class="add-more" onClick="return add_more_image()">Add More</a>
                                      </div>
                                     
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01">What does it mean to be a member : </div>
                                  <div class="field02">
                                        <textarea name="ta_mean_of_member" cols="" rows="" class="small"><?=$res['s_mean_of_member']?></textarea>
                                  </div>
                                  <div id="err_mean_of_member" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01">How do I become a member of the body ?</div>
                                  <div class="field02">
                                        <textarea name="ta_to_become_member" cols="" rows="" class="small"><?=$res['s_to_become_member']?></textarea>
                                  </div>
                                  <div id="err_to_become_member" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">Salvation Prayer</div>
                                  <div class="field02">
                                        <textarea name="ta_salvation_prayer" cols="" rows="" class="small"><?=$res['s_salvation_prayer']?></textarea>
                                  </div>
                                  <div id="err_salvation_prayer" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  
                                  <div class="lable01">What Next (Help Me Grow)</div>
                                  <div class="field02">
                                        <textarea name="ta_what_next" cols="" rows="" class="small"><?=$res['s_what_next']?></textarea>
                                  </div>
                                  <div id="err_what_next" class="error-message"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field02">
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="return clear_box()"/>
                                  </div>
                              </form>
                        
                            
                              
                              <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->


<script type="text/javascript">
$(document).ready(function(arg) {
    // for AJAX page-submission...
    optionsArr = {
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateFrm, // post-submit callback 
        url:        admin_base_url + "build_kingdom/salvation_prayer/edit_info"
    }; 
});
function form_post()
{
    $('#salavtion_frm').ajaxSubmit(optionsArr);
    return false;
}
// validate ajax-submission...
function validateFrm(data)
{
    
    var data = JSON.parse(data);
	hideBusyScreen();
	showUIMsg(data.msg);

     $('.error-message').each(function(i){
            $(this).attr('style','display:none');
        });
        
    if(data.result=='failure') 
    {
        for ( var id in data.arr_messages ){
            
            if( $('#err_'+id) != null ) {
                $('#err_'+id).html(data.arr_messages[id]);
                $('#err_'+id).css('display', 'block');
            }
        }
    }
    else {
         window.location.href = document.URL;
    }
}

function clear_box()
{     
   $('#salavtion_frm')[0].reset();
   $('.error-message').hide();
}

function add_more_image()
{

var no_of_divs= parseInt( $("div[class^=img-upload-section]:visible").length );

no_of_divs++;
//alert(no_of_divs);

var content = '<div id="img_sec'+no_of_divs+'"><div class="img-upload-section"><input name="s_photo[]" type="file" size="48" class="file-browsing"/><span onclick="removeExtraImageDiv(\'hide_only\','+no_of_divs+')"><img alt="" src="<?= base_url()?>images/icons/close.png" class="close-img" /></span></div><input type="hidden" name="db_photo_id" value=""/><div class="clr"></div></div>';

$(content).appendTo('#add_more_images');
}// end of add_extra_div


function removeExtraImageDiv(record_id, div_id)
{
	
	if(record_id != 'hide_only'){
		//alert(1);
		$.ajax({
			type: 'get',
			url: '<?=admin_base_url()?>build_kingdom/salvation_prayer/delete_photo/'+record_id,
			dataType: 'json',
	
			success: function (data, status) {
					$('#img_sec'+div_id).remove();
					showUIMsg('Photo removed successfully.');
				}	// end of success function...
		});
	}
	else{
			//alert(2);
		//alert('#img_sec'+div_id);
		$('#img_sec'+div_id).remove();
	}

}



</script>