<div class="div_content" style=" margin-top:0px;">

							<?php
							//pr($prod_data,1);
							if($prod_data)
							{
								foreach($prod_data as $product)
								{
									$LOGO	= base_url().'uploads/e_trade_product/'.getThumbName($product['s_image'],'thumb');
									$ring_detail_link	= base_url().'rings/'.$ringval['ringid'].'/ring-home.html';
									
									
									if($product['i_accept'] == 0 ){
										
										$status_name = "Requested On";
										$dt_type = 'dt_req_date';
										$status = '<li><img alt="" src="images/icons/pending.png" class="acpt" />Pending</li>
                                                <li>|</li>
                                                <li onclick="cancel_sent_request('.$product['request_id'].',3)" style=" cursor:pointer;" ><img alt="" src="images/icons/band.png" class="acpt" />Cancel</li>';
									}
									else if($product['i_accept'] == 1){
										$status_name = "Accepted On";
										$dt_type = 'dt_accept';
										$status = '<li><img alt="" src="images/icons/accept.png" class="acpt" />Accepted</li>';
									}
									else if($product['i_accept'] == 2){
										$status_name = "Requested On";
										$dt_type = 'dt_req_date';
										$status = '<li><img alt="" src="images/icons/band.png" class="acpt" />Request Declined</li>';
									}
									else if($product['i_accept'] == 3)
									{
										$status_name = "Requested On";
										$dt_type = 'dt_req_date';
										$status = '<li><img alt="" src="images/icons/band.png" class="acpt" />Request Cancelled</li>';
									}
							?>
									<div class="ne-etrade-product-category-list" >
									<div class="thumb">
                                    	<div class="img_div" style="background:url(<?php echo $LOGO?>) no-repeat center #fff;"  onclick="window.location='<?php echo base_url()?>eswap/<?php echo $product['id']?>/detail.html'"></div>
                                    </div>
									<div class="thumb-right">
										<div class="heading-etrade"><strong><?php echo $product['product_id']?></strong></div>
										<div class="heading-etrade" style=" cursor:pointer;" onclick="window.location='<?php echo base_url()?>eswap/<?php echo $product['id']?>/detail.html'"><?php echo $product['s_name']?></div>
										<p class="attribute1">
											<?php echo substr($product['s_attribute1'],0,100)?>
										</p>
                                       
									</div>
									<ul class="ne-etrade-breadcrumb2">
											<li>Brand: <?php echo $product['s_brand'];?></li>
											<li>Product Age: <?php echo $product['s_product_age']?></li>
											<li>Shipping Preference: <?php echo ($product['i_open_to_offer_for_local']==1)?'Local':(($product['i_open_to_offer_for_local']==2)?'International':'Local & International')?></li>
											<li>Posted On: <?php echo getShortDate($product['dt_insert_time'],5)?></li>
											<li>From: <?php echo get_user_address_info($product['i_user_id'])?></li>
											
									</ul>
                                    <div style="margin-bottom:10px; padding-bottom:10px;">
                                     <p class="attribute1">
                                      <strong> Details: </strong><?php echo substrws($product['s_description'],70)?>
                                    </p>
                                   <?php
                                    if($product['i_user_id']!=intval(decrypt($this->session->userdata('user_id'))))
                                    {
                                    ?>
                                    <br class="clr"/>
                                    <a class="view_more" href="<?php echo base_url()?>eswap/<?php echo $product['id']?>/detail.html">Read More</a>
                                    <?php
                                    }
                                    ?>
                                    </div>
								<div class="ne-etrade-quantity-section" id="rating_div_<?php echo $product['reqid']?>">
									 
										<div class="ne-etrade-product">
							
                                              <p class="send-request-quantity">Product : <?php echo $product['req_qty']?></p>
                                              <ul class="ne-etrade-breadcrumb">
                                                <li><a href="javascript:void(0)"><?=$status_name?> - <?php echo getShortDate($product[$dt_type],5)?></a></li>
                                              </ul>
                                              <p class="send-request-quantity">Request Status</p>
                                              <ul class="ne-etrade-breadcrumb">
                                                <?=$status?>
                                              </ul>
							  			</div>
									  <?php
									   /*?>}
									  else if($product['i_accept']==1)
									  {
										  ?>
                                          <div class="ne-etrade-product">
							
                                              <p class="send-request-quantity">Product Offered: <?php echo $product['req_qty']?></p>
                                              <ul class="ne-etrade-breadcrumb">
                                                <li><a href="javascript:void(0)">Accepted On - <?php echo getShortDate($product['dt_req_date'],5)?></a></li>
                                              </ul>
                                              <p class="send-request-quantity">Request Status</p>
                                              <ul class="ne-etrade-breadcrumb">
                                                <li>Request Accepted</li>
                                                <li>Name:</li>
                                                <li>Email:</li>
                                                <li>Phone:</li>
                                              </ul>
                                              
							  			</div>
                                          <?php
									  }
									  else if($product['i_accept']==2)
									  {
										  ?>
                                        <div class="ne-etrade-product">
                                            <ul class="ne-etrade-breadcrumb">
                                                 <li><img class="acpt" src="images/icons/band.png" alt="" /> <span>Request Declined</span></li>
                                            </ul>
                                        </div>
                                        <?php
									  }
									  ?><?php */?>
								</div>
                               
							   </div>
                            <?php
								}
							}
							?>
</div>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page_1?>"  />                     

                            
<script type="text/javascript">
$(function(){
		$('.view-shipping-free').click(function(){
			$(this).next('.slide-view-shipping-free').slideToggle('slow');
			})
		$('.disclaimer-link').click(function(){
			$(this).parent('p').next('.read-disclaimer').slideToggle('fast');
			});
	});
	
function editRequest(id,reqid,obj)
{
	var qty	= obj.prev().val();
	$.ajax({
			"type":'post',
			"data":'id='+id+'&qty='+qty+'&reqid='+reqid,
			"dataType":'json',
			"url":'<?php base_url()?>logged/e_trade/edit_request',
			"success": function(data)
						{
							if(data.success==false)
							{
								showUIMsg(data.msg);
							}
							else
							{
								$('#rating_div_'+data.id).html(data.html);
								showUIMsg(data.msg);
							}
						}
		
		});
}

function giveRatingToSeller(frmid)
{
	 var optionsrate = { 
       // beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateRateFrm // post-submit callback 
    }; 
    // bind to the form's submit event 
        $('#'+frmid).ajaxSubmit(optionsrate);
        return false;
}
function validateRateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	if(data.success==false) 
		showUIMsg(data.msg);
	else {
		$('#rating_div_'+data.id).html(data.html);
		showUIMsg(data.msg);
	}
	//hideBusyScreen()		;
}

</script>                          

