<div class="div_content" style=" margin-top:0px;">

							<?php
							
							if($ringdata)
							{
								//pr($ringdata);
								foreach($ringdata as $ring_inv_val)
								{
									$LOGO	= get_profile_image_of_user('thumb',$ring_inv_val['s_profile_photo'],$ring_inv_val['e_gender']);
									$ring_detail_link	= base_url().'rings/'.$ring_inv_val['ringid'].'/ring-home.html';
							?>
                              
                               <div class="shade_box_01" style="padding-top:5px;">
                                    <div class="txt_content"> <a href="javascript:void(0);"><div class="pro_photo2" style="background:URL('<?php echo $LOGO?>') no-repeat center; width:73px; height:72px; background-color:#fff"></div></a>
                                          <div class="left_div01" style="width:365px;">
                                                <p class="blue_bold12">
												<?php
													if($ring_inv_val['if_already_friend'] == 'true' || $ring_inv_val['already_added_netpal'] == 'true'){
													$profile_link = get_profile_url($ring_inv_val['post_owner_user_id'],$ring_inv_val['s_profile_name']);
													}else
													{
													$profile_link = get_profile_url_prayer_partner($ring_inv_val['post_owner_user_id'],$ring_inv_val['s_profile_name']);
													}										
												?>
												<a href="<?php echo $profile_link?>"><?php echo $ring_inv_val['s_profile_name']?></a></p>
                                                <p style="padding-bottom:8px;">Requested On: <?php echo getShortDate($ring_inv_val['dt_created_on'],5)?> </p>
                                                <p><?php echo my_substr($ring_inv_val['s_request_detail'],55)?></p>
												 <p style="padding-top:8px;"> 
                                                 <img src="images/icons/accept.png" alt="" /> 
                                                 <a href="javascript:void(0);" class="blue_link" onclick="acceptDeclineInvitation('<?php echo encrypt($ring_inv_val['ringid'])?>','<?php echo encrypt($ring_inv_val['invitedid'])?>','<?php echo encrypt($ring_inv_val['id'])?>','accept')"><strong>Accept</strong></a>  
                                                 &nbsp;  &nbsp; <img src="images/icons/decline.png" alt="" /> 
                                                 <a  href="javascript:void(0);" class="blue_link" onclick="acceptDeclineInvitation('<?php echo encrypt($ring_inv_val['ringid'])?>','<?php echo encrypt($ring_inv_val['invitedid'])?>','<?php echo encrypt($ring_inv_val['id'])?>','decline')"><strong>Decline</strong></a></p>
                                          </div>
                                          <div class="clr"></div>
                                    </div>
                              </div>
                              <?php
								}
							}
							?>
</div>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page_1?>"  />                     

                            
                            

