<?php 
	if($category)
	{
		?>
		<ul class="library-my-category">
                 
		
		<?php 
		#pr($readingplan);
		$i	= 0;
		foreach($category as $cat)
		{
			 /*?>$i++;
				if($i==1)
				{
				?>
				<tr>
        	<?php
			}
			?><?php */?>
            <li>
                 <p>
           <!-- <td align="left" valign="middle">-->
				<?php echo $cat['s_category']?>
                <span style="float:right;"><a href="javascript:void(0);" title="Edit"  onclick="showEditCategory('<?php echo encrypt($cat['id'])?>')"><img src="images/icons/edit.png" alt="edit" width="16" height="16"></a>
                        <a href="javascript:void(0);" title="Delete" onclick="show_dialog('delete_category');$('#deleteCatId').val('<?php echo encrypt($cat['id'])?>')"><img src="images/icons/close.png" alt="delete" width="12" height="12"></a>
                    </span></li>
                <!--<img src="<?php echo base_url()?>images/icons/edit.png" onclick="showEditCategory('<?php echo encrypt($cat['id'])?>')" />
                <img src="<?php echo base_url()?>images/icons/close.png" onclick="show_dialog('delete_category');$('#deleteCatId').val('<?php echo encrypt($cat['id'])?>')" />
            </td>-->
            
			
            <?php
			if($cat['s_category']=='' && $i<3)
			{
				
			}
			if($i==3)
			{
			?>
				<!--</tr>-->
			<?php
				$i	= 0;
			}
			
		}
	?>
	</ul>
<?php
}
?>