<div class="div_content" style=" margin-top:0px; padding:8px; position:relative;" id="versediv">
                            <?php
                            if($bible_data)
                            {
								$bookname	= '';
								$chapter	= '';
                                foreach($bible_data as $bibleval)
                                {
                                 	$replacetxt	= array();
                            ?>
                                <!--<div class="grey-container">-->
                                     
									  
									  <?php 
										if($bibleval['s_book_name']!=$bookname && $bibleval['s_chapter']!=$chapter)   
										{
											echo ' <h2 class="title booktitle" style="margin-bottom:0;">';
											echo $bibleval['s_book_name'];
											$bookname	= $bibleval['s_book_name'];
											
											echo '&nbsp;Chapter-'.$bibleval['s_chapter'];
											$chapter	= $bibleval['s_chapter'];
											
											echo '</h2>';
											$headingtxt[]	=  strtolower($bibleval['s_book_name']).':'.intval($bibleval['s_chapter']);
											$bookname_arr[]	=  strtolower($bibleval['s_book_name']);
											$verse_id_for_prev_book	= $bibleval['id'];
										}
										else if($bibleval['s_book_name']==$bookname && $bibleval['s_chapter']!=$chapter)
										{
											echo ' <h2 class="title booktitle" style="margin-bottom:0;">';
											echo $bibleval['s_book_name'];
											$bookname	= $bibleval['s_book_name'];
											
											echo '&nbsp;Chapter-'.$bibleval['s_chapter'];
											$chapter	= $bibleval['s_chapter'];
											
											echo '</h2>';
											$headingtxt[]	=  strtolower($bibleval['s_book_name']).':'.intval($bibleval['s_chapter']);
											$bookname_arr[]	=  strtolower($bibleval['s_book_name']);
											$verse_id_for_prev_book	= $bibleval['id'];
										}
										?>
                                        <div class="clr"></div>
                                        <div class="inside-grey-container" style="cursor:default;">
                                            <div class="contents">
                                            	<div class="spot-edit" >
                                                    	 <a href="javascript:void(0);" name="anchor_<?php echo $bibleval['id']?>" chapter="<?php echo $bibleval['i_chapter_id']?>" book="<?php echo $bibleval['i_book_id']?>" style="float:left;">
                                                                <sup onclick="spot_edit_click($(this));"><?php echo $bibleval['i_verses']?></sup>
                                                            </a>
                                                        <div class="spot-edit-box">
                                                        	<span class="bottom-arrow"></span>
                                                            <div class="spot-edit-container">
                                                                <ul class="main-buttons">
                                                                    <!--highlights start -->
                                                                    <li class="addHighlight"><a href="javascript:void(0);">Highlight</a></li>
                                                                    <!--highlights start -->
                                                                    <!--note start -->
                                                                    <li class="addNote"><a href="javascript:void(0);">Note</a></li>
                                                                    <!--note end -->
                                                                    <!--bookmark start -->
                                                                    <li class="addBookmark"><a href="javascript:void(0);">Bookmark</a></li>
                                                                    <!--bookmark end -->
                                                                </ul>
                                                                <!--highlights start -->
                                                                <div class="floating-popup add-highlight">
                                                                    <div class="title">
                                                                        <a title="Back" class="back" href="javascript:void(0);">&nbsp;</a>Add Highlight
                                                                        <a href="javascript:void(0);" class="close" title="Close"></a>
                                                                    </div>
                                                                    <form action="" id="frm_hilits<?php echo $bibleval['id']?>" method="post" enctype="multipart/form-data" class="quick-edit-form">
                                                                        <span class="verse-name"><?php echo $bibleval['s_book_name'].' '.$bibleval['s_chapter'].':'.$bibleval['i_verses']?></span>
                                                                        <label>Select Category:</label>
                                                                        <select name="bk_mark_category" class="select_shortcut_category">
                                                                            <option value="">select category</option>
                                                                            <?php echo $category_html?>
                                                                        </select>
                                                                        <span id="err_cat_hilits<?php echo $bibleval['id']?>" class="error-message" style="margin-left:119px;"></span>
                                                                        <br class="clr">
                                                                        <label class="small">or</label>
                                                                        <br class="clr">
                                                                        <label>Add New Category:</label>
                                                                        <input name="add_cat_h" type="text">
                                                                        <br class="clr">
                                                                        <label>Select Color:</label>
                                                                       		<?php echo get_highlights_color($bibleval['id']);?>
                                                                        <br class="clr">
                                                                        <input type="hidden" id="colorhidden_<?php echo $bibleval['id']?>" value="" name="colorhidden" />
                                                                        <input type="button" name="" value="Add" class="blue-small-button" onclick="addHighlights(<?php echo $bibleval['id']?>);">
                                                                        <br class="clr">
                                                                    </form>
                                                                </div>
                                                                <!--highlights end -->
                                                                <!--note start -->
                                                                <div class="floating-popup add-note">
                                                                    <div class="title">
                                                                        <a title="Back" class="back" href="javascript:void(0);">&nbsp;</a>Add Note
                                                                        <a href="javascript:void(0);" class="close" title="Close"></a>
                                                                    </div>
                                                                    <form action="" id="frmNote_<?php echo $bibleval['id']?>" method="post" enctype="multipart/form-data" class="quick-edit-form">
                                                                        <span class="verse-name"><?php echo $bibleval['s_book_name'].' '.$bibleval['s_chapter'].':'.$bibleval['i_verses']?></span>
                                                                        <label>Select Category:</label>
                                                                        <select name="category" class="select_shortcut_category">
                                                                        	<option value="">select category</option>
                                                                            <?php echo $category_html?>
                                                                        </select>
                                                                        <span id="err_cat_<?php echo $bibleval['id']?>" class="error-message" style="margin-left:119px;"></span>
                                                                        <br class="clr">
                                                                        <label class="small">or</label>
                                                                        <br class="clr">
                                                                        <label>Add New Category:</label>
                                                                        <input name="add_cat_n" type="text">
                                                                        <br class="clr">
                                                                        <label>Note:</label>
                                                                        <textarea name="note"></textarea>
                                                                        <span id="err_note_<?php echo $bibleval['id']?>" class="error-message" style="margin-left:119px;"></span>
                                                                        <br class="clr">
                                                                        <input type="button" name="" value="Add" class="blue-small-button" onclick="addNoteFromVerseNo('<?php echo $bibleval['id']?>');">
                                                                        <br class="clr">
                                                                    </form>
                                                                </div>
                                                                <!--note end -->
                                                                <!--bookmark start -->
                                                                <div class="floating-popup add-bookmark">
                                                                    <div class="title">
                                                                        <a title="Back" class="back" href="javascript:void(0);">&nbsp;</a>Add Bookmark
                                                                        <a href="javascript:void(0);" class="close" title="Close"></a>
                                                                    </div>
                                                                    <form action="" id="frmBkmark_<?php echo $bibleval['id']?>" method="post" enctype="multipart/form-data" class="quick-edit-form">
                                                                        <span class="verse-name"><?php echo $bibleval['s_book_name'].' '.$bibleval['s_chapter'].':'.$bibleval['i_verses']?> </span>
                                                                        <label>Select Category:</label>
                                                                        <select name="bk_mark_category" class="select_shortcut_category">
                                                                        	<option value="">select category</option>
                                                                            <?php echo $category_html?>
                                                                        </select>
                                                                        <span id="err_cat_bk_mark<?php echo $bibleval['id']?>" class="error-message" style="margin-left:119px;"></span>
                                                                        <br class="clr">
                                                                        <label class="small">or</label>
                                                                        <br class="clr">
                                                                        <label>Add New Category:</label>
                                                                        <input name="add_cat_b" type="text">
                                                                        <br class="clr">
                                                                        <input type="button" name="" value="Add" class="blue-small-button" onclick="addBookmarkFromVerseNo('<?php echo $bibleval['id']?>')">
                                                                        <br class="clr">
                                                                    </form>
                                                                </div>
                                                                <!--bookmark end -->
                                                            </div>
                                                            <div class="clr"></div>
                                                        </div>
                                                    </div>
                                           
                                            	<div class="hilitstest div_<?php echo $bibleval['id']?>" id="div_<?php echo $bibleval['id']?>" title="<?php echo $bookname.' Chapter-'.$chapter?>"><?php 
													$hilits_arr	= $hlts[$bibleval['id']];
													$vtxt		= $bibleval['s_text'];
													$replacetxtlength	= '';
													#pr($hilits_arr);
													foreach($hilits_arr as $hilits)
													{
														if(strpos($bibleval['s_text'],$hilits['txt']) !==FALSE)
														{
															$pos	= $replacetxtlength+$hilits['pos1'];
															$leng	= $hilits['pos2']-$hilits['pos1'];
															$replacetxt	= '<span style="background-color: '.$hilits['colocode'].'" id="'.$bibleval['id'].'">'.$hilits['txt'].'</span>'; 
															$replacetxtlength	+=	strlen($replacetxt)-strlen($hilits['txt']);
															$vtxt	= substr_replace($vtxt,$replacetxt,$pos,$leng);
															
														}													
													}
													echo $vtxt;
													$total_vernote	= count($note[$bibleval['id']]);
													for($vernote_count=0;$vernote_count<$total_vernote;$vernote_count++)
													{
														echo '&nbsp;<span title="Note" class="note-notify"></span>';
													}
													
													if($bkmark[$bibleval['id']]!='')
														echo '&nbsp;<span title="Bookmark" class="bookmark-notify"></span>';
												?>
												</div>
                                                	
                                            </div>
                                        </div>
                                        
                                        
                             <!--</div>-->
                            <?php
                                }
								//exit;
                            }
							
                            ?>
</div>
<div class="previous-next">
<ul><?= $page_links?></ul>
</div>
<div class="clr"></div>


  <div class="bible-controls">
  	<div class="left">
        <ul class="prev-next-control">
            <?php 
            //pr($headingtxt);
            //if(!in_array('genesis:1',$headingtxt))
			if($verse_id_for_prev_book >= 31)
            {
            ?>
            <li onclick="goToChapter('prev')" class="prev first" style="cursor:pointer;">Prev chapter</li><li>|</li>
            <?php
            }
            if(!in_array('revelation:22',$headingtxt))
            {
            ?> 
            <li onclick="goToChapter('next')" class="next" style="cursor:pointer;">Next chapter</li>
            <?php 
            }
            ?>
        </ul>
     </div>
     <div class="right">
        <ul class="prev-next-control">
        
        <?php 
            //pr($headingtxt);
            //if(!in_array('genesis',$bookname_arr))
			if($verse_id_for_prev_book >= 1526)
            {
            ?>
            <li onclick="goToBook('prev')" class="prev first" style="cursor:pointer;">Prev Book</li><li>|</li>
            <?php
            }
            if(!in_array('revelation',$headingtxt))
            {
            ?>
            <li onclick="goToBook('next')" class="next" style="cursor:pointer;">Next Book</li>
            <?php 
            }
            ?>
        </ul>
       </div>
</div>                  
<div class="clr"></div>
                            
<script type="text/javascript">
$(function(){

	if('<?php echo $pagebkmark[0]['i_page_bookmark']?>'=='<?php echo $bkmark?>')
	{	
		$("#bookmarkIcon").hide();
		$("#bookmarkIcon1").show();
	}
	else
	{
		$("#bookmarkIcon").show();
		$("#bookmarkIcon1").hide();
	}
	/*$('div .previous-next > ul > li:first').find('a').click(function()
	{
		if('<?php echo $pagebkmark[0]['i_page_bookmark']?>'=='<?php echo $bookmark_page_for_prev?>')
		{	
			$("#bookmarkIcon > a.bookmark").addClass('select');
		}
		else
			$("#bookmarkIcon > a .bookmark").removeClass('select');
		
	});
	$('div .previous-next > ul > li:last').find('a').click(function()
	{
		if('<?php echo $pagebkmark1[0]['i_page_bookmark']?>'=='<?php echo $bookmark_page_for_next?>')
		{
			
			$("#bookmarkIcon > a.bookmark").addClass('select');
		}
		else
			$("#bookmarkIcon > a .bookmark").removeClass('select');
		
	});*/
});

</script>                   


