<?php //pr($note_arr);
	if(count($note_arr)){
		foreach($note_arr as $k=> $val){
?>
<div class="nw-inside-grey-container">
        <span style="font-size:10px; float:right; color:#999999; font-style:italic;"><?=getShortDate($val['dt_created_on'],5)?></span>
        <div class="nw-contents" style="float:left;">
            <img class="icon-note" src="images/icons/note-personal.png" alt="">
            <?=$val['s_description']?>
        </div>
    	<br class="clr">
</div>

<?php
		}
	}
?>