<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
#table_content .paging .num_tag_link {display: none !important;}
</style>
<script>
	$(document).ready(function() {
		$('#searchtxt').autofill({'value':'Search by "<keywords>" or "<book name> <chapter no.>:<verse no.>"'});
	});
	
</script> 
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  
                  <div id="main_container">
                        <div class="page_heading">
                              <div class="left"><img src="images/icons/bible-icon.png" alt="" />The Bible</div>
                        </div>
						
						<div class="bible-left-part">
						  <!--bible toolbar start -->
							<div class="bible-toolbar">
                               <!-- <form action="<?php echo base_url()?>holy-place/read-bible" method="post" id="searchfrm1" class="keyword-search no-padding">
                                	<label>Keyword:</label>
                                    <input id="searchtxt" name="searchtxt" type="text" value="">
                                    <input name="btnsubmit1" id="btnsubmit1" type="button" class="search-btn" onclick="submitSearch();">
                                </form> -->
								<form class="keyword-search no-padding" action="<?php echo base_url()?>logged/holy_place/search" method="post" id="searchfrm" onsubmit="return false;">
                                	<label>Keyword:</label>
                                    <input id="searchtxt" name="searchtxt" type="text">
                                    <input name="btnsubmit" id="btnsubmit" type="submit" class="search-btn" value="">
                                </form>
                                <a href="<?php echo base_url()?>holy-place/bible/all-books" class="view-all-books">View All Books</a>
                                <div class="clr"></div>
                            </div>
							  <!--bible toolbar end -->
							  
							   <div class="shade_box_shade">
                             <div id="table_content" style="height: 1000px; overflow: hidden;" tabindex="5006">
                                   <?php echo $listingContent;?>
                            </div>
                            
                        </div>

						</div>
						
						
                          
                        
                        
                        <div class="bible-right-part bible-equalHeight" style="height:1064px;">
                       	<div class="right-floating">
                       		<div class="general-container">
                            	<div class="bible-text-container">
                                        <div class="title">Library</div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select  name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_note_bookmark_highilights','ajax_library')" id="library_categorylist">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_library" id="ajax_library">
                                            	<?php include(APPPATH."views/logged/holy_place/ajax_holy_place/ajax_listing_library.phtml");?>
                                        </div>
                                    </div>
                                   	 <div class="my-reading-options">
                                        <ul>
                                            <li>
                                                <a href="javascript:void(0);" id="readingPlan"><span class="reading-plan"></span>My Reading Plan</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myNoteBtn"><span class="notes"></span>My Notes</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myBookmarkBtn"><span class="bookmark"></span>My Bookmarks</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myHighlightBtn"><span class="highlights"></span>My Highlights</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myCategoryBtn"><span class="my-category"></span>My Category</a>
                                            </li>
                                        </ul>
                                    </div>
                                 </div>
                                 <!--reading plan start -->
                                 <?php include(APPPATH."views/logged/holy_place/reading_plan.phtml");?>
                                 <!--reading plan end -->
                              <div class="note-container">
                                        <div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Notes
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="mynotes_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_note/3','notediv')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_note" id="notediv">
                                        </div>
                                    </div>
                                    </div>
                                    
                                <div class="bookmark-container">
                                	<div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Bookmark
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="mybookmark_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_bookmark/3','bookmark_div')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_bookmark" id="bookmark_div">
                                        </div>
                                    </div>
                                </div>    
                                    
                                 <div class="highlight-container">
                                	<div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Highlights
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="myhighlights_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_highilights/3','hilits_div')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_highlights" id="hilits_div">
                                            
                                        </div>
                                    </div>
                                </div>   
                       </div>
                        
        			</div>
                        
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>

<?php /*?>LIGHT BOX <?php */?>
<?php include(APPPATH."views/logged/holy_place/lightbox.phtml");?>
<?php /*?>LIGHT BOX <?php */?>


<?php include(APPPATH."views/layouts/footer.phtml");?>

<script type="text/javascript">
$(function()
{
		showscroll();
	
});
function searchVerse()
{
	showBusyScreen(); 
	
	$.ajax({
		type: 'post',
		url: '<?php echo base_url()?>logged/holy_place/search/',
		dataType: 'json',
		data: 'searchtxt='+$('#searchtxt').val(),
		success: function (msg) {
			location.href = '<?php echo base_url()?>holy-place/read-bible/'+msg.slab+'/'+msg.dest_verse;
		
		}	// end of success function...
	});

}
$('#noteIcon').click(
		function(){
			$('.contents').css('cursor', 'pointer');
			$('.turn-on-btns a').removeClass('select');
			$('.inside-grey-container .contents div').unbind('mouseup');
			$(this).find('a').addClass('select');
			$('.inside-grey-container').click(
			function()
			{
				
				 var arrForId	= $(this).find("a").attr('name').split('_');
				 $("#verIdForNote").val(arrForId[1]);
				 $('#err_cat').html(''); 
				 $('#err_note').html('');
				 $('#add_cat_n').val('');
				 $('#category_N').val('');
				 $('#notetxt').val('');
				 show_dialog('comment_div');
			});
			
});


function addNote()
{
	$.ajax({
			type: 'post',
			url: '<?php echo base_url()?>logged/holy_place/add_note/',
			dataType: 'json',
			data: $("#frmnote").serialize(),
			success: function (msg) {

				if(msg.success==true)
				{	
					$.post(base_url+'logged/holy_place/generate_read_bible_AJAX/'+msg.slab, {'t' : 't'}, 
						function(data)
						{
							closeDialog('note')
							showUIMsg(msg.data);
							$('.inside-grey-container').unbind('click');
							$('.note-container').slideUp();
							$('.general-container').slideDown();
							$('#table_content').html(data);
							$('#ajax_library').html(msg.library);
							$('#library_categorylist').html('');
							$('#library_categorylist').html(msg.category_html);
							updateCategoryOptionInPopup(msg.category_html1);
							
						}
					); 
				}	
				else
				{
					if(msg.data.err_cat)
					{
						$('#err_cat').html(msg.data.err_cat);
					}
					if(msg.data.err_note)
					{
						$('#err_note').html(msg.data.err_note);
					}
				}
				
			}	// end of success function...
	});
}
$("#bookmarkIcon").click(function(){
	$('.turn-on-btns a').removeClass('select');
	$("#bkmarkAdd").unbind('click');
	$('.inside-grey-container').unbind('mouseup');
	
	$(this).find('a').addClass('select');
			
			
	var arrForId	= $('#versediv a:first').attr('name').split('_');
	$('#bk_mark_category').val('');
	$('#add_cat_b').val('');
	$('#err_cat_bk_mark').html('');
	show_dialog('bookmark_div');
	
	var thispage	= ($('div .previous-next > ul > li.current_tag_for_bible_paging').html());
	$("#bkmarkAdd").click(function(){
		$.ajax({
					type: 'post',
					url: '<?php echo base_url()?>logged/holy_place/add_bookmark/',
					dataType: 'json',
					data: 'versesid='+arrForId[1]+'&pagebookmark='+thispage+'&'+$('#frmbkmark').serialize(),
					success: function (msg) {
		
						if(msg.success==true)
						{	
							/*$.post(base_url+'logged/holy_place/generate_read_bible_AJAX/'+msg.slab, {'t' : 't'}, 
								function(data)
								{
									
									
								}
							); */
									closeDialog('bkmark')
									showUIMsg(msg.data);
									$("#bkmarkAdd").unbind('click');
									$('.bookmark-container').slideUp();
									$('.general-container').slideDown();
									//$('#table_content').html(data);
									$('#ajax_library').html(msg.library);
									$('#library_categorylist').html('');
									$('#library_categorylist').html(msg.category_html);
									$('#mynotes_cat').html(msg.category_html);
									$('#mybookmark_cat').html(msg.category_html);
									$('#myhighlights_cat').html(msg.category_html);
									updateCategoryOptionInPopup(msg.category_html1);
						}	
						
						else
						{
							if(msg.data.err_cat)
							{
								$('#err_cat_bk_mark').html(msg.data.err_cat);
							}
							else
							{
								showUIMsg(msg.data); 
								hide_dialog();
								
							}
							
						}
						
						
					}	// end of success function...
			  });
			  
	});
});


function addNoteFromVerseNo(id)
{
	$.ajax({
			type: 'post',
			url: '<?php echo base_url()?>logged/holy_place/add_note/',
			dataType: 'json',
			data: 'verIdForNote='+id+'&'+$("#frmNote_"+id).serialize(),
			success: function (msg) {
				showUIMsg(msg.data);
				if(msg.success==true)
				{	
					/*$.post(base_url+'logged/holy_place/generate_read_bible_AJAX/'+msg.slab, {'t' : 't'}, 
						function(data)
						{
							$('#table_content').html(data);*/
							$('#ajax_library').html(msg.library);
							$('.note-container').slideUp();
							$('.general-container').slideDown();
							$('.floating-popup').hide();
							$('.spot-edit-box').hide(); 
							$('.ghost-layer').remove();
							$('#library_categorylist').html('');
							$('#library_categorylist').html(msg.category_html);
							updateCategoryOptionInPopup(msg.category_html1);
							
							
						//}
					//); 
					
				}	
				else
				{
					if(msg.data.err_cat)
					{
						$('#err_cat_'+id).html(msg.data.err_cat);
					}
					if(msg.data.err_note)
					{
						$('#err_note_'+id).html(msg.data.err_note);//alert();
					}
				}
				
			}	// end of success function...
	});
}


function addBookmarkFromVerseNo(id)
{
	$.ajax({
					type: 'post',
					url: '<?php echo base_url()?>logged/holy_place/add_bookmark/',
					dataType: 'json',
					data: 'versesid='+id+'&'+$('#frmBkmark_'+id).serialize(),
					success: function (msg) {
		
						if(msg.success==true)
						{	
							/*$.post(base_url+'logged/holy_place/generate_read_bible_AJAX/'+msg.slab, {'t' : 't'}, 
								function(data)
								{
									
									
									
								}
							); */
									//$('#table_content').html(msg);
									$('#ajax_library').html(msg.library);
									$('.bookmark-container').slideUp();
									$('.general-container').slideDown();
									$('.floating-popup').hide();
									$('.spot-edit-box').hide(); 
									$('.ghost-layer').remove();
								$('#library_categorylist').html('');
									$('#library_categorylist').html(msg.category_html);
									updateCategoryOptionInPopup(msg.category_html1);
						}	
						else
						{
							if(msg.data.err_cat)
							{
								$('#err_cat_bk_mark'+id).html(msg.data.err_cat);
							}
							else
							{
								showUIMsg(msg.data); 
								hide_dialog();
								
							}
							
						}
						
						
					}	// end of success function...
			  });
}

function addHighlights(id)
{	
	var selectedtext	= $('#div_'+id).text();
	
	
	var selectedtextStart	= 0;	
	var selectedtextEnd	= selectedtext.length;	
	var selectedtext	= selectedtext;	
	
	$.ajax({
				type: 'post',
				url: '<?php echo base_url()?>logged/holy_place/add_highlights/',
				dataType: 'json',
				data: 'versesid='+id+'&text='+selectedtext+'&startpos='+selectedtextStart+'&endpos='+selectedtextEnd+'&'+$('#frm_hilits'+id).serialize(),
				success: function (msg) {
					if(msg.success==true)
					{
						showUIMsg(msg.data); 
						$('#div_'+id).html(msg.txt);
						
						$("#hilitsAdd").unbind('click');
						$('.highlight-container').slideUp();
						$('.general-container').slideDown();
						$('.floating-popup').hide();
						$('.spot-edit-box').hide(); 
						$('.ghost-layer').remove();
						$('#ajax_library').html(msg.library);
						//alert(msg.category_html);
						$('#library_categorylist').html('');
						$('#library_categorylist').html(msg.category_html);
						updateCategoryOptionInPopup(msg.category_html1);
					}	
					else
					{
						if(msg.data.err_cat)
						{
							$('#err_cat_hilits'+id).html(msg.data.err_cat);
						}
						else
						{
							showUIMsg(msg.data); 
							closeDialog('hilits')
							$("#hilitsAdd").unbind('click');
						}
					}
				
				}	// end of success function...
			});
}



function getColorCode(colorid,vid)
{
	if(vid=='')
		$('#colorhidden').val(colorid);
	else
		$('#colorhidden_'+vid).val(colorid);
}

function updateCategoryOptionInPopup(categoryOption)
{
	$('#library_categorylist').html(categoryOption);
	$('#bk_mark_category_h').html(categoryOption);
	$('#bk_mark_category_b').html(categoryOption);
	$('#category_N').html(categoryOption);
	$('#category').html(categoryOption);
	$('.select_shortcut_category').html(categoryOption);
}

</script>


