<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<style>
#table_content .paging .num_tag_link {display: none !important;}
</style>
<script>
	$(document).ready(function() {
		$('#searchtxt').autofill({'value':'Search by "<keywords>" or "<book name> <chapter no.>:<verse no.>"'});
	});
</script> 
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <div class="page_heading">
                              <div class="left"><img src="images/icons/bible-icon.png" alt="" />The Bible</div>
                        </div>
						
						<div class="bible-left-part bible-equalHeight" style="border-bottom: 1px solid #D9D9D9;background-color: #F2F2F2;">
							<!--bible toolbar start -->
                            <div class="bible-toolbar">
                                <form action="<?php echo base_url()?>holy-place/read-bible" method="post" id="searchfrm1" class="keyword-search no-padding">
                                	<label>Keyword:</label>
                                    <input id="searchtxt" name="searchtxt" type="text" value="">
                                    <input name="btnsubmit1" id="btnsubmit1" type="button" class="search-btn" onclick="submitSearch();">
                                </form>
                                <a href="<?php echo base_url()?>holy-place/bible/all-books" class="view-all-books">View All Books</a>
                                <div class="clr"></div>
                            </div>
                            
                         <div class="shade_box_shade" style="border-bottom:none;">
                          <div class="view-books-container" id="bibleContent_list">
                              <h2 class="title">
							  <?php echo $bookname.':'.$chapter?>
                              </h2>
                            
                            <?php
							#pr($versepointer);
							if($verse_data)
							{
								echo "<ul>";
								$counter	= 0;
								foreach($verse_data as $verse)
								{
								if($counter==0)
								{
								?>
									<li>
                                    <a href="<?php echo base_url().'holy-place/read-bible/'.$versepointer[$verse['id']]['slab_for_current_id'].'/'.$versepointer[$verse['id']]['verseid']?>">
										Start
                                        </a>
                                    </li>
								<?php
									$counter++;
								}
								?>
                                
									<li>
                                    <a href="<?php echo base_url().'holy-place/read-bible/'.$versepointer[$verse['id']]['slab_for_current_id'].'/'.$versepointer[$verse['id']]['verseid']?>">
										<?php echo $verse['i_verses']?>
                                        </a>
                                    </li>
								<?php
								}
								echo "</ul>";
							}
							?>
                            <div class="clr"></div>
                                
                            </div>
						
						</div>
						
                            
                        </div>
						
						
						<!--right panel-->
						<div class="bible-right-part bible-equalHeight">
                       	<div class="right-floating">
                       		<div class="general-container">
                            	<div class="bible-text-container">
                                        <div class="title">Library</div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_note_bookmark_highilights','ajax_library')" id="library_categorylist">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_library" id="ajax_library">
                                            	<?php include(APPPATH."views/logged/holy_place/ajax_holy_place/ajax_listing_library.phtml");?>
                                        </div>
                                    </div>
                                   	 <div class="my-reading-options">
                                        <ul>
                                            <li>
                                                <a href="javascript:void(0);" id="readingPlan"><span class="reading-plan"></span>My Reading Plan</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myNoteBtn"><span class="notes"></span>My Notes</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myBookmarkBtn"><span class="bookmark"></span>My Bookmarks</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myHighlightBtn"><span class="highlights"></span>My Highlights</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" id="myCategoryBtn"><span class="my-category"></span>My Category</a>
                                            </li>
                                        </ul>
                                    </div>
                                 </div>
                                 <!--reading plan start -->
                                 <?php include(APPPATH."views/logged/holy_place/reading_plan.phtml");?>
                                 <!--reading plan end -->
                              <div class="note-container">
                                        <div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Notes
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="mynotes_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_note/3','notediv')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_note" id="notediv">
                                        </div>
                                    </div>
                                    </div>
                                    
                                <div class="bookmark-container">
                                	<div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Bookmark
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="mybookmark_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_bookmark/3','bookmark_div')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_bookmark" id="bookmark_div">
                                        </div>
                                    </div>
                                </div>    
                                    
                                 <div class="highlight-container">
                                	<div class="bible-text-container">
                                        <div class="title">
                                        	<a href="javascript:void(0);" class="back" title="Back">&nbsp;</a>
                                        	My Highlights
                                        </div>
                                         <div class="filter-by">
                                        	<label>Filter By: </label>
                                            <select id="myhighlights_cat" name="" style="padding:0;" onchange="showAllByCategory(this.value,'<?php echo base_url()?>logged/holy_place/get_all_highilights/3','hilits_div')">
                                            	<option value="">View all</option>
                                                <?php echo $category_html?>
                                            </select>
                                        </div>
                                        <div class="scroll-container scroll_highlights" id="hilits_div">
                                            
                                        </div>
                                    </div>
                                </div>   
                       </div>
                        
        			</div>
						<!--right panel-->
                       
                        
                        
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php /*?>LIGHT BOX <?php */?>
<?php include(APPPATH."views/logged/holy_place/lightbox.phtml");?>
<?php /*?>LIGHT BOX <?php */?>

<?php include(APPPATH."views/layouts/footer.phtml");?>

<script type="text/javascript">




function gotoVersePointer(slab,id)
{
	window.location	= '<?php echo base_url()?>holy-place/read-bible/'+slab+'#'+id;

	/*$.ajax({
		type: 'post',
		url: '<?php echo base_url()?>logged/my_ring/add_join_request',
		dataType: 'json',
		data: 'ringid='+ringid,
		success: function (data) {
			
			if(data.msg=='success')
			{
				$('#join_req_p_'+data.removeid).remove();
				showUIMsg("Join request has been successfully send");
			}
			else if(data.msg=='error') 
			{
				$('#err_detail').html(data.err.err_detail);
			}
			
		}	// end of success function...
	});*/
}
function searchVerse()
{
	showBusyScreen(); 
	
	$.ajax({
		type: 'post',
		url: '<?php echo base_url()?>logged/holy_place/search/',
		dataType: 'json',
		data: 'searchtxt='+$('#searchtxt').val(),
		success: function (msg) {
			location.href = '<?php echo base_url()?>holy-place/read-bible/'+msg.slab+'/'+msg.dest_verse;
		
		}	// end of success function...
	});

}


function equalHeight(group) {
		var tallest = 0;
		group.each(function() {
			var thisHeight = $(this).height();
			if(thisHeight > tallest) {
				tallest = thisHeight;
			}
		});
		
		group.height(tallest);
		
	}	
	
	
$(function(){
	equalHeight($(".bible-equalHeight"));
});
</script>


