<script language="javascript">

var g_controller_url = base_url+"my-ring.html";

var photo_id = null;
$(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoad,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#ring_frm').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});

function showLoad()
{
 // $('#photo_album_btn').attr('disabled','disabled');
 	showUIMsg();
  $('#photo_album_btn').val('Creating...');
  
}


// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		//$('#photo_album_btn').attr('disabled','');
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		
	}
	else {
		
		showUIMsg(data.msg);		
		//window.location.href= "<?$_SERVER['HTTP_REFERER']?>";///document.URL;
		window.location.href= "<?php echo base_url().'my-ring.html'?>";
		
	}
	$('#sp_add_loading').html('');
	//hideLoading();
				
}





$(function(){
	$('#ring_desc_span').textCounter({
		target: '#ring_desc', // required: string
		count: 500, // optional: integer [defaults 140]
		alertAt: 20, // optional: integer [defaults 20]
		warnAt: 10, // optional: integer [defaults 0]
		stopAtLimit: true // optional: defaults to false
	});
	
});


</script>

<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                  
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        
                        <div id="mid_container">
                        
                            <!--sub page links -->
                              <div class="link-div" style="margin-top:-2px;">
                                  <ul>
                                    <li><a href="my-ring.html" class="<?php echo ($page_name=='my-ring')? 'current':'';?>"><span>My Ring</span> </a> </li>
                                    <li><a href="search-ring.html" class="<?php echo ($page_name=='search-ring')? 'current':'';?>"><span>Browse  &amp;  Search Ring</span> </a> </li>
                                    <li><a href="create-my-ring.html" class="<?php echo ($page_name=='create-my-ring')? 'current':'';?>"><span>Create Ring</span> </a> </li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                            <!--/sub page links -->
                            
                       	  <div class="page_heading">
                            	<div class="left"><img src="images/icons/ring.png" alt="" /> Create Ring</div>
                          </div>
                             
                             <div class="frm_box blue_box" style="width: 500px;">
                             <form name="ring_frm" id="ring_frm" action="<?=base_url().'logged/my_ring/add_ring'?>" method="post"  onsubmit="return false;" enctype="multipart/form-data">
                                    <div class="lable01" style="width:100px;">Name: </div> 
                                    <div class="field03" style="width: 350px;">
                                    <input name="ring_name" id="ring_name" type="text" style="width: 300px;" />
                                    <span id="err_name" class="error-message"></span> 
                                    </div>  
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">Description: </div>  
                                    <div class="field03" style="width: 350px;">
                                    <textarea name="ring_desc" id="ring_desc" cols="" rows="" style="width:300px; height:170px;"></textarea>
                                    <div class="clr"></div>
                                     <span id="ring_desc_span" class="pad-80 tcWarn" style="display:none;">0</span>
                                     
                                     <span>500 characters</span>
                                    <span id="err_desc" class="error-message"></span> 
                                    </div> 
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">Category:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <select name="category" id="category" style="width:300px;">
                                          <option value="">Please Select Category</option>
                                          <?php echo $category?>
                                    </select>
                 					<span id="err_category" class="error-message"></span> 
                                    <script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#category").msDropDown();
                                            $("#category").hide();
                                        })
                                    </script></div> 
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">Logo:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <input name="ring_logo" type="file"  size="39" style="width:300px"/>
                                    <span id="err_logo" class="error-message"></span> 
                                    </div> 
                                    
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">Privacy Settings:</div>  
                                    <div class="field03" style="width: 350px;">
                                    <select name="privacy_settings" id="privacy_settings" style="width:300px;">
                                          <option value="1">Only user invited by you can join  </option>
                                          <option value="2">All User</option>
                                    </select>
                 					<span id="err_privacy_settings" class="error-message"></span> 
                                    <script type="text/javascript">
                                        $(document).ready(function(arg) {
                                            $("#privacy_settings").msDropDown();
                                            $("#privacy_settings").hide();
                                        })
                                    </script></div> 
                                    <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">	Invite Friends :</div>  
                                    <div class="field03" style="width: 350px;">
                                    
                                   	  <input type="text" id="invite_frnd" name="invite_frnd" autocomplete="off" style="width:300px;" />
                                      <input type="hidden" id="h_friend_id"  name="h_friend_id" />
                                         <span id="err_invite_frnd" class="error-message"></span> 
										
                                    </div>
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">&nbsp;</div>  
                                    <div class="field03" style="width: 350px;">
                                      
                                         <input name="" type="button" value="Contacts"  class="sml_btn" onclick="return show_dialog('contact_div')"/> 
                                       
                                     </div> 
                                    <div class="clr"></div>
                                    <div class="lable01" style="width:100px;">&nbsp;</div>  
                                  <?/*?>  <div class="field03" style="width: 350px;">  <p class="amber">A ring can not have more than 100 members.</p>
                                        <p class="blue_bold12"><a href="mailto:admin@admin.com?Subject=Please increase max member limit for my group">Request site admin to increase number</a></p></div>
                                        <?*/?>
                                        <div class="clr"></div>
                                     <div class="lable01" style="width:100px;">&nbsp;</div>  
                                    <div class="field03" style="width: 350px;">
                                      
                                      <input name="photo_album_btn"  id="photo_album_btn" type="submit" value="Create"  class="btn"/> 
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="location.href='<?php base_url()?>my-ring.html'" />
                               </div> 
                                    <div class="clr"></div>
                               </form>
                          	</div>
                            
                        </div>
                    <!-- /left container -->
                        
            <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>





<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<div class="lightbox contact_div" style="width:500px; ">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" /></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Select from Contacts </h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
                 
                  <?php /*?> <div class="user_div"> 
                        <input name="" type="checkbox" value="" />  <a href="javascript:void(0);"><img src="images/man1.png" alt=""/></a>
                      <a href="javascript:void(0);" class="blue_link">George Swift</a>
                        
                  </div><?php */?>
                  <div id="contact_list" >
                                   
                                      <div class="selectRecipients" style="background-color: #FFF; width:457px; border:none;">
                                       <?php 
										  if(count($contact_arr)):
											 $count_total = 1;
											 //pr($contact_arr);
											  foreach($contact_arr as $key=>$val){
												  
												  $img = get_profile_image('thumb',$val['s_profile_photo'],$val['e_gender']);
												  
												  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
												   		$profile_link = get_profile_url($val['user_id'],$val['s_displayname']);
												  }
												  else{
													   $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
												  }
												  
												  $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';
														
										 ?>
                                         <div class="image-block <?=$CSS?>">
                                             
                                              <input type="checkbox"  value="<?=$val['user_id']?>_<?=$val['s_displayname']?>" name="<?=intval(decrypt($this->session->userdata('user_id')))?>" id="<?=$key+1?>" />
                                              <div class="inside">
                                                  <?php /*?><div style="background:url('<?=$img?>') no-repeat center;width:60px; height:60px;" class="pro_photo2"></div><?php */?>
                                                  <img alt="Friend" src="<?=$img?>"><br/><br/><br/>
                                                  <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>
                                              </div>
                                          </div>
                                        
                                       	 
										 <?php	$count_total++;	
										 			}
										 		endif; 
										 ?>
                                       	   
                                	  </div> 
								</div>
                    <div class="clr"></div>
                    <br />
                    <div style="text-align:right;"><input name="" type="button" value="Done" onclick="javascript:get_selected_contacts();" class="btn"/></div>
            </div>
            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>

<!-- /lightbox SECTION -->
<!-- confirm delete album popup-->
<!-- end of delete pop up -->
