<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">

            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                    <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                    
                        <!-- mid container -->
                        <div id="mid_container">
                        
                        <!--sub page links -->
                            <?php include("ring_home_menu.phtml")?>
                        <!--/sub page links -->
                        

                              <div class="page_heading">
                                    <div class="left"><img src="images/icons/ring.png" alt="" /> Invite Members</div>
                              </div>
                              <div class="arrow_btm"></div>
                   
                              <div class="frm_box inbox_div_blue" style=" margin-top:0px;">
                                
                              <input type="hidden" name="ring_id" id="ring_id" value="<?= $ring_id?>">
                                
                                
                                <div id="contact_list" >

                                      <div class="selectRecipients" style="width: 450px;">
                                       <?php 

            
                                          if(count($contacts)):
                                             $count_total = 1;
                                              foreach($contacts as $key=>$val){
                                                  
                                                  $img = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);
                                                  
                                                  if($val['if_already_friend'] == 'true' || $val['already_added_netpal'] == 'true'){
                                                           $profile_link = get_profile_url($val['user_id'],$val['user_profile_name']);
                                                  }
                                                  else{
                                                       $profile_link = get_public_profile_url($val['user_id'],$val['user_profile_name']);
                                                  }
                                                  
                                                  $CSS = ($count_total%4 == 0)?'no-right-mrgn':'';

                                           if(!in_array($val['user_id'],$arr_invited_id))             
                                           {
                                         ?>
                                         <div class="image-block <?=$CSS?>">
                                              <input  type="checkbox"  value="<?=encrypt($val['user_id'])?>" id="chkmember<?=$val['user_id']?>" name="chkmember<?=$val['user_id']?>">
                                              <div class="inside">
                                                  <?php /*?><div style="background:url('<?=$img?>') no-repeat center;width:60px; height:60px;" class="pro_photo2"></div><?php */?>
                                                  <img alt="Friend" src="<?=$img?>"><br/><br/><br/>
                                                  <a href="<?=$profile_link?>" ><span><p><?=$val['s_first_name']?></p></span></a>
                                              </div>
                                          </div>
                                        
                                            
                                         <?php    $count_total++;    
                                           }//end if in_array
                                                     }
                                                 endif; 
                                         ?>
                                              
                                      </div> 
                                      <div class="error_msg" id="err_send_recepients"></div>
                                      
                                      <div class="field03">
                                        <input id="btn_submit" class="btn" type="button" onclick="return invite_ring()" value="Invite" name="btn_submit">
                                        <!--<input id="btn_submit" class="btn" type="button" onclick="" value="Cancel" name="btn_submit">
                                        -->
                                      </div>
                                      
                                      
                                </div><!--/contact_list-->
                                
                                <div class="clr"></div>
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                              </div><!--inbox_div_blue-->
                              <?php
                              //echo $current_page;
                              //echo "view more: ".$view_more;
                              //echo "current_page : ".$current_page;
                              
                              ?>
                            
                              
                              
                              
                              
                        </div>
                        
                        
                        <!-- /mid container -->
                        <!-- right container -->
                          <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<!-- /FOOTER SECTION -->

<?php include(APPPATH."views/logged/ring/comments/my_ring_post_comment_lightbox.phtml");?>








<script type="text/javascript">

function invite_ring()
{
    //showBusyScreen();
    var ring_id = $('#ring_id').val();
    
    var csv_recipient_ids = '';
    i = 0;
    $(function() {
        $(':checkbox:checked').each(function(i){
            if($(this).attr('id').substr(0, 9) == 'chkmember') {
                csv_recipient_ids += $(this).val()+',';
            }
        });
    });
    csv_recipient_ids = csv_recipient_ids.substring(0, csv_recipient_ids.length-1);
    
   
    $('#err_send_recepients').hide();
    
    ajax_req = $.ajax({
        type: 'POST',
        url:base_url+'logged/ring_home/send_ring_invitation',
    
        dataType: 'json',
        data: ({'recipients': csv_recipient_ids, 'ring_id' : ring_id}),
        success: function (data)  
        {
            if(data.success==true)
            {
                showUIMsg(data.msg);
                window.location.href = base_url+'rings/'+ring_id+'/ring-home.html';
            }
            else
            {
                for ( var id in data.arr_message )
                {
                    
                    if( $('#err_'+id) != null ) 
                    {
                        $('#err_'+id).html(data.arr_message[id]);
                        $('#err_'+id).show();
                    }
                }
            }
        }
    
    });
   
}


</script>