function com_topcmm_ChatApplication(){var M='',lc='\n-',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',$b='"<script src=\\"',fb='"><\/script>',W='#',kc=');',cc='-\n',mc='-><\/scr',_b='.cache.js\\"><\/scr" + "ipt>"',Y='/',ib='//',Ob='0AA709084B7E39D2E56F594994D3C62B',Sb='1493C0D00CDAD424A17F506EEF6AF0F5',Tb='55301C1655C8F559420F783736548CEE',Ub='5D653EC967233ADF0EFBC4DEDD07D8B0',Vb='6B4AF0C1F267B2A6B64FC8E8ADCAFC6A',Xb=':',Pb=':1',Qb=':2',Rb=':3',mb='::',ac='<scr',eb='<script id="',pb='=',X='?',Wb='A54AFD7A971FE8BF470BFDF3183BB31C',rb='Bad handler "',Lb='Cross-site hosted mode not yet implemented. See issue ',Yb='DOMContentLoaded',gb='SCRIPT',db='__gwt_marker_com.topcmm.ChatApplication',xb='android',hb='base',_='baseUrl',Q='begin',P='bootstrap',$='clear.cache.gif',N='com.topcmm.ChatApplication',bb='com.topcmm.ChatApplication.nocache.js',lb='com.topcmm.ChatApplication::',ob='content',vb='device.type',jc='document.write(',V='end',fc='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',hc='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',Ib='gecko',Jb='gecko1_8',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',Mb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Hb='ie6',Gb='ie8',Fb='ie9',Z='img',wb='iphone',nc='ipt>',bc='ipt><!-',Zb='loadExternalRefs',jb='meta',ec='moduleName:"com.topcmm.ChatApplication", sessionId:window.__gwtStatsSessionId, subSystem:"startup",',U='moduleStartup',Eb='msie',yb='msiemobile',kb='name',Bb='opera',zb='pc',Db='safari',ab='script',Nb='selectingPermutation',O='startup',gc='type: "end"});',ic='type: "moduleRequested"});',cb='undefined',Kb='unknown',Ab='user.agent',Cb='webkit',dc='window.__gwtStatsEvent && window.__gwtStatsEvent({';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s=M,t={},u=[],v=[],w=[],x=0,y,z;o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Q});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=m.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}A=function(){return b};return b}
function B(){if(q&&r){q(y,N,s,x);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function C(){function e(a){var b=a.lastIndexOf(W);if(b==-1){b=a.length}var c=a.indexOf(X);if(c==-1){c=a.length}var d=a.lastIndexOf(Y,Math.min(c,b));return d>=0?a.substring(0,d+1):M}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(Z);b.src=a+$;a=e(b.src)}return a}
function g(){var a=E(_);if(a!=null){return a}return M}
function h(){var a=n.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(bb)!=-1){return e(a[b].src)}}return M}
function i(){var a;if(typeof isBodyLoaded==cb||!isBodyLoaded()){var b=db;var c;n.write(eb+b+fb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=gb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return M}
function j(){var a=n.getElementsByTagName(hb);if(a.length>0){return a[a.length-1].href}return M}
function k(){var a=n.location;return a.href==a.protocol+ib+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==M){l=h()}if(l==M){l=i()}if(l==M){l=j()}if(l==M&&k()){l=e(n.location.href)}l=f(l);s=l;return l}
function D(){var b=document.getElementsByTagName(jb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(kb),g;if(f){f=f.replace(lb,M);if(f.indexOf(mb)>=0){continue}if(f==nb){g=e.getAttribute(ob);if(g){var h,i=g.indexOf(pb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=M}t[f]=h}}else if(f==qb){g=e.getAttribute(ob);if(g){try{z=eval(g)}catch(a){alert(rb+g+sb)}}}else if(f==tb){g=e.getAttribute(ob);if(g){try{y=eval(g)}catch(a){alert(rb+g+ub)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
v[vb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(wb)!=-1){return wb}else if(b.indexOf(xb)!=-1){return xb}else if(b.indexOf(yb)!=-1){return yb}return zb};u[vb]={android:0,iphone:1,msiemobile:2,pc:3};v[Ab]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Bb)!=-1}())return Bb;if(function(){return b.indexOf(Cb)!=-1}())return Db;if(function(){return b.indexOf(Eb)!=-1&&n.documentMode>=9}())return Fb;if(function(){return b.indexOf(Eb)!=-1&&n.documentMode>=8}())return Gb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Hb;if(function(){return b.indexOf(Ib)!=-1}())return Jb;return Kb};u[Ab]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};com_topcmm_ChatApplication.onScriptLoad=function(a){com_topcmm_ChatApplication.onScriptLoad=null;q=a;B()};if(A()){alert(Lb+Mb);return}D();C();o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Nb});var H;try{F([xb,Db],Ob);F([wb,Db],Ob);F([yb,Db],Ob);F([zb,Db],Ob);F([xb,Db],Ob+Pb);F([wb,Db],Ob+Pb);F([yb,Db],Ob+Pb);F([zb,Db],Ob+Pb);F([xb,Db],Ob+Qb);F([wb,Db],Ob+Qb);F([yb,Db],Ob+Qb);F([zb,Db],Ob+Qb);F([xb,Db],Ob+Rb);F([wb,Db],Ob+Rb);F([yb,Db],Ob+Rb);F([zb,Db],Ob+Rb);F([xb,Hb],Sb);F([wb,Hb],Sb);F([yb,Hb],Sb);F([zb,Hb],Sb);F([xb,Hb],Sb+Pb);F([wb,Hb],Sb+Pb);F([yb,Hb],Sb+Pb);F([zb,Hb],Sb+Pb);F([xb,Hb],Sb+Qb);F([wb,Hb],Sb+Qb);F([yb,Hb],Sb+Qb);F([zb,Hb],Sb+Qb);F([xb,Hb],Sb+Rb);F([wb,Hb],Sb+Rb);F([yb,Hb],Sb+Rb);F([zb,Hb],Sb+Rb);F([xb,Gb],Tb);F([wb,Gb],Tb);F([yb,Gb],Tb);F([zb,Gb],Tb);F([xb,Gb],Tb+Pb);F([wb,Gb],Tb+Pb);F([yb,Gb],Tb+Pb);F([zb,Gb],Tb+Pb);F([xb,Gb],Tb+Qb);F([wb,Gb],Tb+Qb);F([yb,Gb],Tb+Qb);F([zb,Gb],Tb+Qb);F([xb,Gb],Tb+Rb);F([wb,Gb],Tb+Rb);F([yb,Gb],Tb+Rb);F([zb,Gb],Tb+Rb);F([xb,Bb],Ub);F([wb,Bb],Ub);F([yb,Bb],Ub);F([zb,Bb],Ub);F([xb,Bb],Ub+Pb);F([wb,Bb],Ub+Pb);F([yb,Bb],Ub+Pb);F([zb,Bb],Ub+Pb);F([xb,Bb],Ub+Qb);F([wb,Bb],Ub+Qb);F([yb,Bb],Ub+Qb);F([zb,Bb],Ub+Qb);F([xb,Bb],Ub+Rb);F([wb,Bb],Ub+Rb);F([yb,Bb],Ub+Rb);F([zb,Bb],Ub+Rb);F([xb,Jb],Vb);F([wb,Jb],Vb);F([yb,Jb],Vb);F([zb,Jb],Vb);F([xb,Jb],Vb+Pb);F([wb,Jb],Vb+Pb);F([yb,Jb],Vb+Pb);F([zb,Jb],Vb+Pb);F([xb,Jb],Vb+Qb);F([wb,Jb],Vb+Qb);F([yb,Jb],Vb+Qb);F([zb,Jb],Vb+Qb);F([xb,Jb],Vb+Rb);F([wb,Jb],Vb+Rb);F([yb,Jb],Vb+Rb);F([zb,Jb],Vb+Rb);F([xb,Fb],Wb);F([wb,Fb],Wb);F([yb,Fb],Wb);F([zb,Fb],Wb);F([xb,Fb],Wb+Pb);F([wb,Fb],Wb+Pb);F([yb,Fb],Wb+Pb);F([zb,Fb],Wb+Pb);F([xb,Fb],Wb+Qb);F([wb,Fb],Wb+Qb);F([yb,Fb],Wb+Qb);F([zb,Fb],Wb+Qb);F([xb,Fb],Wb+Rb);F([wb,Fb],Wb+Rb);F([yb,Fb],Wb+Rb);F([zb,Fb],Wb+Rb);H=w[G(vb)][G(Ab)];var I=H.indexOf(Xb);if(I!=-1){x=Number(H.substring(I+1));H=H.substring(0,I)}}catch(a){return}var J;function K(){if(!r){r=true;B();if(n.removeEventListener){n.removeEventListener(Yb,K,false)}if(J){clearInterval(J)}}}
if(n.addEventListener){n.addEventListener(Yb,function(){K()},false)}var J=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K()}},50);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:V});o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:Zb,millis:(new Date).getTime(),type:Q});var L=$b+s+H+_b;n.write(ac+bc+cc+dc+ec+fc+gc+dc+ec+hc+ic+jc+L+kc+lc+mc+nc)}
com_topcmm_ChatApplication();