<div class="link-div ps">
  <ul>
      <li>
          <a href="my-chat-rooms.html" <?=($page_name == 'my-chat-rooms')?'class="current" ':''?>>
              <span class="nw-etrade">My Rooms</span>
          </a>
      </li>
    
       <li>
          <a <?=($page_name == 'browse-chat-room')?'class="current" ':''?> href="browse-chat-room.html">
              <span class="nw-etrade">Public Room</span>
          </a>
      </li>
      <li>
          <a <?=($page_name == 'private-chat-room')?'class="current" ':''?> href="private-chat-room.html">
              <span class="nw-etrade">Private Room</span>
          </a>
      </li>
       <li>
          <a <?=($page_name == 'prayer-chat-room')?'class="current" ':''?> href="prayer-chat-room.html">
              <span class="nw-etrade">Prayer Room</span>
          </a>
      </li>
       <li>
          <a <?=($page_name == 'ring-chat-room')?'class="current" ':''?> href="ring-chat-room.html">
              <span class="nw-etrade">Rings</span>
          </a>
      </li>
  </ul>
    <div class="clr"></div>
</div>