<div class="clr"></div>
<!--navigation section start -->
<?php include(APPPATH."views/layouts/admin/admin_nav.phtml");?>
<!--navigation section end -->
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="top_corner">&nbsp;</div> -->
            <div id="mid_content">
                  <div class="page_heading left">
                        <div class="left"><img src="../images/icons/login.png" alt="" /> Chat Categories</div>
                        <div class="right"><input name="" type="button" value="Add a Category"  class="evnt_btn1" onclick="return show_dialog('add-product-category')"/></div>
                  </div>
                  <div class="clr"></div>
                  <div id="right_container">
                        <div class="arrow_btm"></div>
                        <div class="content_area">
                        
                         <DIV id="table_content">
							  <?=$result_content?>
                            </DIV>
                        <div class="clr"></div>
                        </div>
                  </div>
                  <div class="clr"></div>
            </div>
            <!--<div id="bot_corner">&nbsp;</div> -->
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->

<!--popup one start-->
<div class="lightbox delete-page-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Product Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <p class="center-text">If you delete this category all chat rooms under this category will be deleted from the system. Are you sure you want to delete this category anyway?</p>
                    <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->


<!--popup add category start-->
<div class="lightbox add-product-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="clear_box('add');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Add a Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_add_product_category" action="" method="post" onsubmit="return post_frm_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 105px;"><span class="red-mark">* </span> Category Name :</div>
                                  <div class="field01">
                                        <input name="txt_cat_name" id="txt_cat_name" type="text" />
                                  </div>
                                  <div id="err_cat_name" class="error-message" style="margin-left: 12px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01" style="margin-left: 10px;">
                                        <input name="" type="submit" class="btn"  value="Add"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('add');hide_dialog();"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup add category end-->



<!--popup edit product category start-->
<div class="lightbox edit-product-category" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="clear_box('edit');hide_dialog()"><img src="../images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Edit Chat Category</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div class="content_area frm_box2">
                        	  <form id="frm_edit_product_category" action="" method="post" onsubmit="return post_frm_edit_ajax();" enctype="multipart/form-data">
                                  <div class="lable01" style="width: 105px;"><span class="red-mark">* </span> Category Name :</div>
                                  <div class="field01">
                                        <input name="txt_edit_cat_name" id="txt_edit_cat_name" type="text" />
                                  </div>
                                  <div id="err_edit_cat_name" class="error-message" style="margin-left: 12px; padding-left: 116px;"></div>
                                  <div class="clr"></div>
                                  
                                  <div class="lable01">&nbsp;</div>
                                  <div class="field01" style="margin-left: 10px;">
                                  <input name="i_edit_id" id="i_edit_id" type="hidden" value=""/>
                                        <input name="" type="submit" class="btn"  value="Update"/>
                                        <input name="" type="reset" class="btn"  value="Cancel" onclick="clear_box('edit'); hide_dialog()"/>
                                  </div>
                              </form>
                              <div class="clr"></div>
                        </div>
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup edit product category end-->

