<?php
	if( ($this->session->userdata('loggedin') !='' || $this->session->userdata('loggedin')!=false ) && $this->session->userdata('is_admin') != 1){
		
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
		
		
   <?php  }
     else{
         
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
  }?>
<!-- CONTENT SECTION -->
<div class="clr"></div><!-- CONTENT SECTION -->

<!-- CONTENT SECTION -->
<div id="content_section" style="margin-top:8px;">
      <div id="container">
      		<!-- main container -->
            <div class="landing-page">
            	<div class="top-left">
                    <h2 class="landing-title">Build The Kingdom</h2>  
                    
                    <?php if(count($content_arr))
                        {
                            foreach($content_arr as $r)
                            {
                                if($r['s_keyword']=='buildkindom_main')
                                {
                                    $content['main_title']=$r['s_title'];
                                    $content['main_desc']=$r['s_desc'];
                                }
                                if($r['s_keyword']=='buildkindom_givin')
                                {
                                    $content['givin_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='buildkindom_prayer_partner')
                                {
                                    $content['pp_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='buildkindom_charity_project')
                                {
                                    $content['cp_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='buildkindom_salvation')
                                {
                                    $content['salvation_desc'] = $r['s_desc'];
                                }
                                if($r['s_keyword']=='buildkindom_bible_quiz')
                                {
                                    $content['bible_quiz'] = $r['s_desc'];
                                }
								if($r['s_keyword']=='buildkindom_find_church')
                                {
                                    $content['find_church'] = $r['s_desc'];
                                }
                        
                            }
                        }
                        
                        ?>
                    
                    
                    
                    
                    <p><?=nl2br($content['main_desc'])?></p>
                </div>
                <div class="top-right">
                <img src="images/build-the-kingdom.png" alt="build the kingdom" />
                </div>
                <div class="clr"></div>
                <!--bottom link section start -->
                <div class="link-section">
                    
                     
                
                	<?php //pr($contents,1);
                    if($this->session->userdata('loggedin')!='')
                    {
                        $destination = "window.location='giving.html'";
                    }
                    else
                    {
                        $url = base64_encode(base_url().'giving.html');
                        $destination = "return show_login_popup('".$url."')";
                    }
                    
                    ?>
                    
                	<!--box one start -->
                    <div class="link-box" onclick="<?=$destination?>">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img src="images/giving.png" alt="giving"/>
                            </div>
                            <h3>Giving</h3>
                            <p><?=nl2br($content['givin_desc'])?></p>
                        </div>
                    </div>
                    <!--box one end -->
                    
                    
                    <?php
                    if($this->session->userdata('loggedin')!='')
                    {
                        $destination = "window.location='my-prayer-partners.html'";
                        
                    }
                    else
                    {
                        $url = base64_encode(base_url().'my-prayer-partners.html');
                        $destination = "return show_login_popup('".$url."')";
                    }
                    
                    ?>
                    
                    <!--box two start -->
                    <div class="link-box" onclick="<?=$destination?>">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img src="images/prayer-partners-zone.png" alt="prayer partners zone"/>
                            </div>
                            <h3>Prayer Partners Zone</h3>
                            <p><?=nl2br($content['pp_desc'])?></p>
                        </div>
                    </div>
                    <!--box two end -->
                    
                    
                    <?php
                    if($this->session->userdata('loggedin')!='')
                    {
                        $destination = "window.location='suggest-projects/charity-project-home.html'";
                        
                    }
                    else
                    {
                        $url = base64_encode(base_url().'suggest-projects/charity-project-home.html');
                        $destination = "return show_login_popup('".$url."')";
                    }
                    
                    ?>
                    
                    
                    <!--box three start -->
                    <div class="link-box" onclick="<?=$destination?>">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img src="images/charity-projects.png" alt="Charity Projects"/>
                            </div>
                            <h3>Charity Projects</h3>
                           <p><?=nl2br($content['cp_desc'])?></p> 
                        </div>
                    </div>
                    <!--box three end -->
                    
                    
                    
                     <?php
                    if($this->session->userdata('loggedin')!='')
                    {
                        $destination = "return show_dialog('welcome')";
                        
                    }
                    else
                    {
                        $url = base64_encode(base_url().'build-the-kingdom.html');
                        $destination = "return show_login_popup('".$url."')";
                    }
                    
                    ?>
                    
                    <!--box four start -->
                    <div class="link-box " onclick="<?=$destination?>">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img src="images/salavation-prayer.png" alt="Salavation Prayer"/>
                            </div>
                            <h3>Salavation Prayer</h3>
                           <p><?=nl2br($content['salvation_desc'])?></p>
                        </div>
                    </div>
                    <!--box four end -->
                    
                    
                    
                    <?php
                    if($this->session->userdata('loggedin')!='')
                    {
                        $destination = "window.location='".base_url()."find-church.html'";
                        
                    }
                    else
                    {
                        $url = base64_encode(base_url().'find-church.html');
                        $destination = "return show_login_popup('".$url."')";
                    }
                    
                    ?>
                   <!--box five start -->
                   <div class="link-box no-bg" onclick="<?=$destination?>">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img alt="Find Church" src="images/find-church.png">
                            </div>
                            <h3>Find Church</h3>
                            <p><?=nl2br($content['find_church'])?></p>
                        </div>
                    </div>
                   
                  
                     <!--<div class="link-box no-bg" onclick="return show_dialog('login-box')">
                    	<div class="link-box-in">
                        	<div class="main-img">
                        		<img src="images/ministers-shout.png" alt="Ministers Shout" />
                            </div>
                            <h3>Ministers Shout</h3>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</p>
                        </div>
                    </div>-->
                    <!--box five end -->
                    <div class="clr"></div>
                </div>
                <!--bottom link section end -->
            </div>     
           <!-- /main container -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->  
  
<?php
	# include footer file...
	include_once(APPPATH ."views/layouts/footer.phtml");
?>
<!--login popup start -->

<!--login popup end -->