<?php
	if( ($this->session->userdata('loggedin') !='' || $this->session->userdata('loggedin')!=false ) && $this->session->userdata('is_admin') != 1){
		
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
		
		
   <?php  }
     else{
         
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
  }?>
<!-- CONTENT SECTION -->
<div class="clr"></div><!-- CONTENT SECTION -->
<style type="text/css">
.evnt li{ float:left; width:250px; margin-bottom:25px; }
</style>

<div id="content_section" style="margin-top:8px;">
    <div id="container">
        <div class="evnt">
            <?php 
            if(count($hp_events)){
                
                foreach ($hp_events as $val){
            $title = my_substr(html_entity_decode(htmlspecialchars_decode($val['s_title']),ENT_QUOTES,'utf-8'), 68);
								$desc = my_substr(html_entity_decode(htmlspecialchars_decode($val['s_desc']),ENT_QUOTES,'utf-8'), 100);
								$detail_url = get_events_detail_url($val['id']);
								
								$IMG_THUMB_PATH = base_url() ."uploads/events_photo/";
								$name=getThumbName($val['s_image_1'],'thumb'); 
								$IMG_THUMB = $IMG_THUMB_PATH . $name;
				?>
            <li><img src="<?=$IMG_THUMB?>" alt="prayer meeting" />
                    <div class="events-container-inside">
                        <p class="title"><a href="javascript:void(0);" onclick="show_dialog('event<?= $val['id']?>')"><?=$title?></a></p>
                        <p class="date" style="color:#000 !important; font-size:13px;"><?=getShortDate($val['dt_start_time'], 9)?></p>
                        <p><?=$desc?></p>
                        <p>Created On: <?=$val['dt_created_on'] ?></p>
                        <p>Venue: <?= $val['s_address']. ', ' . $val['s_city'] . ', ' . $val['s_state'] . ', ' . get_country_name_by_id($val['i_country_id']); ?></p>
                        <p>Details :<?= $desc; ?></p>
               
               

                        <p>Time: <?=$val['dt_start_time'] ?></p>
                    </div>
                </li>
            
            <?php
            
            
                }
            
                } ?>
            
        </div>
        
        
    </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->  
  
<?php
	# include footer file...
	include_once(APPPATH ."views/layouts/footer.phtml");
?>
<!--login popup start -->

<!--login popup end -->