<?php
	if( ($this->session->userdata('loggedin') !='' || $this->session->userdata('loggedin')!=false ) && $this->session->userdata('is_admin') != 1){
		
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
		
		
   <?php  }
     else{
         
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
  }?>
<!-- CONTENT SECTION -->
<div class="clr"></div><!-- CONTENT SECTION -->

<div id="content_section" style="margin-top:8px;">
    <div id="container"></div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->  
  
<?php
	# include footer file...
	include_once(APPPATH ."views/layouts/footer.phtml");
?>
<!--login popup start -->

<!--login popup end -->