<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
<div class="clr"></div>

<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <!--<div id="mid_content"> -->
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                               <div>
                                   <div id="1">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/profile.png" alt=" " />  Personal Information</h4> </div>
                                        <div class="right"><img src="<?php echo base_url();?>images/icons/edit.png" alt=" " width="16" height="16"/>  <a onclick="showDiv('1')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Title:</div>  
                                        <div class="field01"><?=$arr_profile_info['e_title']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">First Name:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_first_name']?> </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Last Name:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_last_name']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">City:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_city']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">State:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_state']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Country:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_country']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Gender:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_gender']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Date of Birth:</div>  
                                        <div class="field01">
										<?=($arr_profile_info['dt_dob'] != '')?getShortDate($arr_profile_info['dt_dob'],'1'):''?>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Profile Photo:</div>  
                                         <div class="field01"><a href="javascript:void(0);" class="blue_link"  onclick="showDiv('1')"><strong>[change]</strong></a></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Want to be Prayer Partner:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_want_prayer_partner']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Want to be Net Pal:</div>  
                                          <div class="field01"><?=$arr_profile_info['s_want_net_pal']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">My Website:</div>  
                                        <div class="field01"><a  href="javascript:void(0);" class="blue_link"><?=$arr_profile_info['s_website']?></a> </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">My Profile URL:</div>  
                                        <div class="field01"><a  href="javascript:void(0);" class="blue_link">www.xtiannetwork.com/<?=$arr_profile_info['s_profile_url_suffix']?></a> </div> 
                                        <div class="clr"></div>
                                       
                             
                                     </div>
                                   </div>
                                   <div id="jason1" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/profile.png" alt=" " />  Personal Information</h4> </div>
                                     </div>
                                     <!--FORM TO MODIFY Personal Information-->
                                     <form id="frmManageProfile" method="post" action="modify-my-profile-personal-info-ajax" onsubmit="return modify_my_profile_ajax()" enctype="multipart/form-data">
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        
                                        <div class="lable01">Title:</div>  
                                        <div class="field01">
                                         <select name="txt_title" id="txt_title" style="width:260px;">
                                              <option value="Mr" <?php echo $selected =($arr_profile_info["e_title"]=='Mr')?'selected':''?>>Mr.</option>
                                              <option value="Mrs" <?php echo $selected =($arr_profile_info["e_title"]=='Mrs')?'selected':''?>>Mrs.</option>
                                              <option value="Ms" <?php echo $selected =($arr_profile_info["e_title"]=='Ms')?'selected':''?>>Ms.</option>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#txt_title").msDropDown();
                                                $("#txt_title").hide();
                                            })
                                        </script>
                                        <?php echo form_error('txt_title'); ?>
                                       </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">First Name:</div>  
                                        <div class="field01">
                                        <input name="txt_fname" id="txt_fname" type="text" value="<?=isset($arr_profile_info["s_first_name"])? $arr_profile_info["s_first_name"]: '' ?>" />
                                        <?php echo form_error('txt_fname'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Last Name:</div>  
                                        <div class="field01">
                                        <input name="txt_lname" id="txt_lname" type="text" value="<?=isset($arr_profile_info["s_last_name"])? $arr_profile_info["s_last_name"]: '' ?>" />
                                        <?php echo form_error('txt_lname'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">City:</div>  
                                        <div class="field01">
                                        <input name="txt_city" id="txt_city" type="text" value="<?=isset($arr_profile_info["s_city"])? $arr_profile_info["s_city"]: '' ?>" />
                                        <?php echo form_error('txt_city'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">State:</div>  
                                        <div class="field01">
                                        <input name="txt_state" id="txt_state" type="text" value="<?=isset($arr_profile_info["s_state"])? $arr_profile_info["s_state"]: '' ?>" />
                                        <?php echo form_error('txt_state'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Country:</div>  
                                        <div class="field01">
                                        <input name="txt_country" id="txt_country" type="text" value="<?=isset($arr_profile_info["s_country"])? $arr_profile_info["s_country"]: '' ?>" />
                                        <?php echo form_error('txt_country'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Gender:</div>  
                                        <div class="field01">
                                        <input name="txt_gender" id="txt_gender" type="text" value="<?=isset($arr_profile_info["s_gender"])? $arr_profile_info["s_gender"]: '' ?>" />
                                        <?php echo form_error('txt_gender'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Date of Birth:</div>  
                                        <div class="field01">
                                       
                                       	<?php
										  # getting day-month-yr extracted from db DOB...
										  $DOB_TSTAMP = strtotime($arr_profile_info['dt_dob']);
										  $DOB_DAY = date( "j", $DOB_TSTAMP );
										  $DOB_MONTH = date( "n", $DOB_TSTAMP );
										  $DOB_YR = date( "Y", $DOB_TSTAMP );
									  ?>
									  
										  <select name="day" id="day"  style="width:70px; margin-right:2px;">
											<option value=""><?= "Day" ?></option>
											<?= makeOptionDay($DOB_DAY) ?>
										  </select>
										  
										  <select name="month" id="month"  style="width:85px; margin-right:2px;">
												<option value=""><?= "Month" ?></option>
												<?= makeOptionMonth($DOB_MONTH) ?>
										  </select>
										  
										  <select name="year" id="year"  style="width:70px;">
												<option value=""><?= "Year" ?></option>
												<?= makeOptionYear($DOB_YR) ?>
										  </select> 
                                          <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#day").msDropDown();
                                                $("#day").hide();
												$("#month").msDropDown();
                                                $("#month").hide();
												$("#year").msDropDown();
                                                $("#year").hide();
                                            })
                                        </script>
                                        <?php  if(form_error('day')!='' || form_error('month')!='' ||  form_error('year')!='' ) echo '<div class="error_massage" id="err_msg">Please provide Birth date</div>'; ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Profile Photo:</div>  
                                        <div class="field01">
                                        
                                        <?php
										 
											$IMG = base_url()."uploads/user_profile_image/".getThumbName($arr_profile_info['s_profile_photo'],'thumb');
											
										?>
                                        <input name="txt_profile_pic" id="txt_profile_pic" type="file" size="25" />
                                        
                                        
										<?php echo form_error('txt_profile_pic'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Want to be Prayer Partner:</div>  
                                        <div class="field01">
                                         <select name="txt_prayer_ptnr" id="txt_prayer_ptnr" style="width:260px;">
                                             <option value="Y" <?php echo $selected =($arr_profile_info["s_want_prayer_partner"]=='Yes')?'selected':''?>>Yes</option>
                                             <option value="N" <?php echo $selected =($arr_profile_info["s_want_prayer_partner"]=='No')?'selected':''?>>No</option>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#txt_prayer_ptnr").msDropDown();
                                                $("#txt_prayer_ptnr").hide();
                                            })
                                        </script>
                                       </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Want to be Net Pal:</div>  
                                          <div class="field01">
                                           <select name="txt_net_pal" id="txt_net_pal" style="width:260px;">
                                             <option value="Y" <?php echo $selected =($arr_profile_info["s_want_net_pal"]=='Yes')?'selected':''?>>Yes</option>
                                             <option value="N" <?php echo $selected =($arr_profile_info["s_want_net_pal"]=='No')?'selected':''?>>No</option>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#txt_net_pal").msDropDown();
                                                $("#txt_net_pal").hide();
                                            })
                                        </script></div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">My Website:</div>  
                                        <div class="field01">
                                        <input name="txt_website" id="txt_website" type="text"  value="<?=$arr_profile_info['s_website']?>"/>
                                        <?php echo form_error('txt_website'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">My Profile URL:</div>  
                                        <div class="field01">www.xtiannetwork.com/ &nbsp;  
                                        <input name="txt_profile_url" id="txt_profile_url" value="<?=$arr_profile_info['s_profile_url_suffix']?>" type="text"  style="width:113px;"/>
                                        <?php echo form_error('txt_profile_url'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                        <input type="hidden" name="is_submitted" id="is_submitted" value="Y" />
                                        <input name="btn_manage_profile" id="btn_manage_profile" type="submit" value="Save"  class="btn" /> 
                                        <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('1')"/>
                                        </div> 
                                        <div class="clr"></div>
                             
                                     </div>
                                     </form>
                                      <!--end FORM TO MODIFY Personal Information-->
                                  </div>
                              </div>
                              <div>
                                   <div id="2">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/info.png" alt=" " />  Basic Information</h4> </div>
                                        <div class="right"><img src="images/icons/edit.png" alt=" " width="16" height="16"/>  <a onclick="showDiv('2')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                    
                                   <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Languages I Speak:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_languages']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">About Me:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_about_me']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">My Church Name:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_name']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Church Location:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_location']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Church Phone:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_phone']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Denomination:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_name']?></div> 
                                        <div class="clr"></div>
                                        <!--<div class="lable01">Profile Photo:</div>  
                                        <div class="field01"><a href="javascript:void(0);" onclick="showDiv('2')" class="blue_link"><strong>[change]</strong></a></div> 
                                        <div class="clr"></div>-->
                                     </div>
                                  
                                     
                                   </div>
                                   <div id="jason2" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/info.png" alt=" " />  Basic Information</h4> </div>
                                     </div>
                                       <!--FORM TO MODIFY basic Information-->
                                     <form id="frmManageBasicProfile"  method="post" action="modify-my-profile-basic-info-ajax" onsubmit="return modify_my_basic_profile_ajax()" enctype="multipart/form-data">
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Languages I Speak:</div>  
                                        <div class="field01">
                                        <input name="txt_lang" id="txt_lang" type="text" value="<?=isset($arr_profile_info["s_languages"])? $arr_profile_info["s_languages"]: '' ?>" />
                                        <?php echo form_error('txt_lang'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">About Me:</div>  
                                        <div class="field01">
                                        <textarea rows="" cols="" name="txt_about" id="txt_about"><?=isset($arr_profile_info["s_about_me"])? $arr_profile_info["s_about_me"]: '' ?></textarea>
                                        <?php echo form_error('txt_about'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">My Church Name:</div>  
                                        <div class="field01">
                                        <input name="txt_cname" id="txt_cname" type="text" value="<?=isset($arr_profile_info["s_church_name"])? $arr_profile_info["s_church_name"]: '' ?>" />
                                        <?php echo form_error('txt_cname'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Address:</div>  
                                        <div class="field01">
                                        <textarea rows="" cols="" name="txt_caddress" id="txt_caddress"><?=isset($arr_profile_info["s_church_address"])? $arr_profile_info["s_church_address"]: '' ?></textarea>
                                        <?php echo form_error('txt_caddress'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church City:</div>  
                                        <div class="field01">
                                        <input name="txt_ccity" id="txt_ccity" type="text" value="<?=isset($arr_profile_info["s_church_city"])? $arr_profile_info["s_church_city"]: '' ?>" />
                                        <?php echo form_error('txt_ccity'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church State:</div>  
                                        <div class="field01">
                                        <input name="txt_cstate"  id="txt_cstate" type="text" value="<?=isset($arr_profile_info["s_church_state"])? $arr_profile_info["s_church_state"]: '' ?>" />
                                        <?php echo form_error('txt_cstate'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Country:</div>  
                                        <div class="field01">
                                        <input name="txt_ccountry" id="txt_ccountry" type="text" value="<?=isset($arr_profile_info["s_church_country"])? $arr_profile_info["s_church_country"]: '' ?>" />
                                        <?php echo form_error('txt_ccountry'); ?>
                                        </div> 
                                        <div class="clr"></div> 
                                        
                                        <div class="lable01">Church Postcode:</div>  
                                        <div class="field01">
                                        <input name="txt_cpostcode" id="txt_cpostcode" type="text" value="<?=isset($arr_profile_info["s_church_postcode"])? $arr_profile_info["s_church_postcode"]: '' ?>" />
                                        <?php echo form_error('txt_cpostcode'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Phone:</div>  
                                        <div class="field01">
                                        <input name="txt_cphone" id="txt_cphone" type="text"  value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>"/>
                                        <?php echo form_error('txt_cphone'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Denomination:</div>  
                                        <div class="field01">
                                         <select name="txt_denomination" id="txt_denomination" style="width:260px;">
                                             <option value="<?=encrypt(0)?>"><?="Denomination"?></option>
                                             <?=makeOptionDenomination(encrypt($arr_profile_info['i_id_denomination']));?>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                $("#txt_denomination").msDropDown();
                                                $("#txt_denomination").hide();
                                            })
                                        </script>
                                        <?php echo form_error('txt_denomination'.'===='); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <!--<div class="lable01">Profile Photo:</div>  
                                        <div class="field01"><input name="" type="file" size="25" /></div> 
                                        <div class="clr"></div>-->
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                          <input type="hidden" name="is_basic_submitted" id="is_basic_submitted" value="Y" />
                                          <input name="" type="submit" value="Save"  class="btn"/>
                                          <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('2')"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                     </form>
                                      <!--FORM TO MODIFY basic Information-->
                                  </div>
                              </div>
                              <div>
                                   <div id="3">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/education.png" alt=" " />  Education</h4> </div>
                                        <div class="right"><img src="<?php echo base_url();?>images/icons/edit.png" alt=" " width="16" height="16"/>  <a onclick="showDiv('3')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                     <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">School/College:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_school_name']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">School Location:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_school_loc']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Class Year:</div>  
                                        <div class="field01"><?=$arr_profile_info['i_class_year']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Degree:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_degree']?></div> 
                                        <div class="clr"></div>
                                      
                                     </div>
                                   </div>
                                   <div id="jason3" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/education.png" alt=" " />  Education</h4> </div>
                                     </div>
                                     <form id="frmManageEduProfile"  method="post" action="modify-my-profile-edu-info-ajax" onsubmit="return modify_my_edu_profile_ajax()" enctype="multipart/form-data">
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                       <div class="lable01">School/College:</div>  
                                        <div class="field01">
                                        <input name="txt_school_name"  id="txt_school_name" type="text" style="width:230px;" value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>" /> 
                                        <a href="javascript:void();" ><img src="images/icons/close.png" alt="" width="24" height="24"></a>
                                        </div> 
                                        <div class="clr"></div>
                                         <div class="lable01">School City:</div>  
                                        <div class="field01">
                                        <input name="" type="text" value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>" style="width:230px;" />
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">School State:</div>  
                                        <div class="field01">
                                        <input name="" type="text" value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>" style="width:230px;" />
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">School Country:</div>  
                                        <div class="field01">
                                        <input name="" type="text" value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>" style="width:230px;" />
                                        </div> 
                                        <div class="clr"></div> 
                                        
                                        <div class="lable01">Class Year:</div>  
                                        <div class="field01">
                                        <input name="" type="text"  value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>" style="width:230px;"/>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Degree:</div>  
                                        <div class="field01">
                                        <input name="" type="text" value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>"  style="width:230px;"/>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <?php /*?><DIV id="div_more_edu">
                                            <div class="fld01">
                                                <input name="article_photos[]" type="file"  size="51"/>
                                            </div>
                                        </DIV><?php */?>
                                        
                                        
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01" style="text-align:right; width:250px;"> 
                                             <a href="javascript:void(0);"  class="blue_link" id="add_mor_edu"><strong>Add More..</strong></a>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01">
                                         <input name="" type="submit" value="Save"  class="btn" onclick="closeDiv('3')"/>
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('3')"/>
                                         </div> 
                                        <div class="clr"></div>
                                     </div>
                                     </form>
                                  </div>
                              </div>
                              <div>
                                   <div id="4">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/job.png" alt=" " />  Work</h4> </div>
                                        <div class="right"><img src="images/icons/edit.png" alt=" " width="16" height="16"/>  <a onclick="showDiv('4')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                     <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Employer:</div>  
                                        <div class="field01">Company Name</div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work Place:</div>  
                                        <div class="field01">City, State, Country</div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Position:</div>  
                                        <div class="field01">Chief Technology Officier</div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Period:</div>  
                                        <div class="field01">2005 to till date</div> 
                                        <div class="clr"></div>
                                     </div>
                                   </div>
                                   <div id="jason4" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/job.png" alt=" " />  Work</h4> </div>
                                     </div>
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                      <div class="lable01">Employer:</div>  
                                        <div class="field01"><input name="" type="text" style="width:230px;" /> <a href="javascript:void();" ><img src="images/icons/close.png" alt=""width="24" height="24" ></a></div> 
                                        <div class="clr"></div>
                                       <div class="lable01">Work City:</div>  
                                        <div class="field01"><input name="" type="text" value="" style="width:230px;" /></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work State:</div>  
                                        <div class="field01"><input name="" type="text" value=""  style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Work Country:</div>  
                                        <div class="field01"><input name="" type="text" value="" style="width:230px;" /></div> 
                                        <div class="clr"></div> 
                                        <div class="lable01">Position:</div>  
                                        <div class="field01"><input name="" type="text"  value="" style="width:230px;"/></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Period:</div>  
                                         <div class="field01">
                                          <select name="mnth" id="mnth" style="width:60px;">
                                             <option>Jan</option>
                                            </select>
                         
                                            <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $("#mnth").msDropDown();
                                                    $("#mnth").hide();
                                                })
                                            </script>
                                         <input name="" type="text"  style="width:29px;" class="left" value="Year" />
                                         <span class="left"> &nbsp; To  &nbsp;</span>
                                         <select name="mnth1" id="mnth1" style="width:60px;">
                                             <option>Jan</option>
                                            </select>
                         
                                            <script type="text/javascript">
                                                $(document).ready(function(arg) {
                                                    $("#mnth1").msDropDown();
                                                    $("#mnth1").hide();
                                                })
                                            </script>
                                         <input name="" type="text"  style="width:29px;" class="left" value="Year" /> </div> 
                                        <div class="clr"></div>
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                            <input name="" type="checkbox" value="" /> Current Employer
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01" style="text-align:right;width:250px;"> 
                                             <a href="javascript:void();"  class="blue_link"><strong>Add More..</strong></a>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                        
                                        <input name="" type="button" value="Save"  class="btn" onclick="closeDiv('4')"/>
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('4')"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                  </div>
                              </div>
                              <div>
                                   <div id="5">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/man2.png" alt=" " />  Skills</h4> </div>
                                        <div class="right"><img src="images/icons/edit.png" alt=" " width="16" height="16" />  <a onclick="showDiv('5')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                       <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Skill 1:</div>  
                                        <div class="field01">Engineer</div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Skill 2:</div>  
                                        <div class="field01">Writer</div> 
                                        <div class="clr"></div>
                                       
                                     </div>
                                   </div>
                                   <div id="jason5" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="images/icons/man2.png" alt=" " />  Skills</h4> </div>
                                     </div>
                                   <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                    <div class="lable01">Skill 1:</div>  
                                        <div class="field01"><input name="" type="text" style="width:230px;" /> <a href="javascript:void();" ><img src="images/icons/close.png" alt=""width="24" height="24" ></a></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Skill 2:</div>  
                                        <div class="field01"><input name="" type="text" style="width:230px;" /> <a href="javascript:void();" ><img src="images/icons/close.png" alt=""width="24" height="24" ></a></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">&nbsp;</div>  
                                        <div class="field01" style="text-align:right;width:250px;"> 
                                             <a href="javascript:void();"  class="blue_link"><strong>Add More..</strong></a>
                                        </div> 
                                        <div class="clr"></div>
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01">
                                        
                                         <input name="" type="button" value="Save"  class="btn" onclick="closeDiv('5')"/>
                                         <input name="" type="button" value="Cancel"  class="btn" onclick="closeDiv('5')"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                  </div>
                              </div>
                        </div>                        
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            <!--</div> -->
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
