<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <div id="mid_container">
                              <div class="page_heading">
                                    <div class="left"><img src="images/icons/man2.png" alt="" width="20" height="23" />Change Password </div>
                              </div>
                              <div class="arrow_btm"></div>
                              <form name="user_frms" id="user_frms" method="post" action="<?=base_url().'logged/change_password/update_info'?>"  onsubmit="return false;" >  
                                <div class="frm_box shade_box_01 ">
                                     
                                    <div class="lable02" style="width:150px;">Password:</div>
                                    <div class="field01">
                                          <input name="txt_pwd" id="txt_pwd" type="password" value=""  style="width:258px;"/>
                                          <span id="err_pwd" class="error-message"></span>
                                    </div>  
                                    <div class="clr"></div>
                                    
                                    <div class="lable02" style="width:150px;">New Password:</div>
                                    <div class="field01">
                                         <input name="txt_new_pwd" id="txt_new_pwd" type="password" value=""  style="width:258px;"/>											
                                         <span id="err_new_pwd" class="error-message"></span>
                                    </div>  
                                    
                                    <div class="clr"></div>
                                    
                                    <div class="lable02" style="width:150px;">Confirm New Password:</div>
                                    <div class="field01">
                                       <input name="txt_new_cpwd" id="txt_new_cpwd" type="password" value=""  style="width:258px;"/>
                                       <span id="err_new_cpwd" class="error-message"></span>
                                    </div>  
                                      
                                    <div class="clr"></div>
                                    <div class="lable02"  style="width:150px;">&nbsp;</div>
                                    <div class="field01">
                                          <input name="" type="submit" value="Update"  class="btn"/>
                                    </div>
                                    <div class="clr"></div>
                                </div>
                              </form>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                       <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>


<script type="text/javascript">
$(document).ready(function() {
	
	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showBusyScreen,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#user_frms').submit(function() {
	
        $(this).ajaxSubmit(options);
		
        return false;
		
    });

});



// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);
	if(data.success==false) 
	{
		
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		for ( var id in data.arr_messages ){
			//alert(data.arr_messages[id]);
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}
		
	}
	else {
		
		  $('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		  $('#user_frms')[0].reset();
		  showUIMsg(data.msg);
		  //window.location.href= "<?=$_SERVER['HTTP_REFERER']?>";//document.URL;
	}
	
	hideBusyScreen();
				
}

</script>
