<?php
	if( $this->session->userdata('loggedin') =='' || $this->session->userdata('loggedin')==false){
		include(APPPATH ."views/layouts/header.phtml");
	   	include(APPPATH."views/layouts/slider_nav.phtml");
     }
     else{
         
		 include(APPPATH ."views/layouts/logged_header.phtml");
		 include(APPPATH."views/layouts/nav.phtml");?>
		  <!-- /NAVIGATION SECTION -->
      		</div>
		</div>
 <?php  }?>
<div class="clr"></div>
<style>
.match_fld{ float:right; margin-right:100px;}
</style>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <?php /*?><div id="top_corner">&nbsp;</div><?php */?>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- right container -->
                        <div class="single-block profile">
                        <div style="margin-left:664px; margin-bottom:5px;">
                        
                        <form name="frm_preserve_search" method="post" enctype="multipart/form-data" action="<?=$_SERVER['HTTP_REFERER']?>">
                        	<input type="hidden" name="IS_PRESERVE_SEARCH" id="IS_PRESERVE_SEARCH" value="Y" />
                            <input type="submit" class="sml_btn" name="reload_search"  style=" background:none repeat scroll 0 0 #013D62;" value="Back" />
                        </form>
                        </div>
                        <div class="heading"><h4>Profile</h4></div>
                        <div class="profile-content">
                          <div class="profile-tab first">
                              <div class="photo-section">
                                  <?php $img = get_profile_image_of_user('main',$profile_info['s_profile_photo'], $profile_info['e_gender']);?>
                                  <div style="background:url(<?=$img?>) no-repeat center;width:144px; height:144px;" title="member" ></div>
                                  
                              </div>
                                                          
                              
                              
                              <div class="content-section">
                                  <h2><?=$profile_info['s_profile_name']?> <?=(strtolower($this->session->userdata('s_lname')) == strtolower($profile_info['s_last_name']) && strtolower($this->session->userdata('s_fname')) == strtolower($profile_info['s_first_name']))?'<span class="match_fld"><img src="images/tick.png"></span>':''?> </h2>
<!--                                   <DIV id="rate_div"><?=show_profile_rating($profile_info['id'])?></DIV>-->
                                    <?php if(!isRated($profile_info['id'])){
									  ?>
                                   <script>
								    $( ".small-ratings li" ).mouseover(function() { 
									
										$(this).find('a').addClass('active');
										var prevAll = $(this).prevAll();
										 prevAll.each(function(index){
											  $(this).find('a').addClass('active');
										 });
										
									});
									
									$( ".small-ratings li" ).mouseleave(function() { 
										$(this).find('a').removeClass('active');
										var prevAll = $(this).prevAll();
										 prevAll.each(function(index){
											  $(this).find('a').removeClass('active');
										 });
									});
								   </script>
                                   <?php } ?>
                                  
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                      <td align="left" valign="top" class="first"><span>Gender</span> 
                                      </td>
                                      <td align="center" valign="top" class="second"><span>:</span></td>
                                      <td align="left" valign="top"><?=($profile_info['e_gender'] == 'F')?'Female':'Male';?> <?=($this->session->userdata('e_gender') == $profile_info['e_gender'])?'<span class="match_fld"><img src="images/tick.png"></span>':''?></td>
                                    </tr>
                                    
                                    <tr>
                                      <td align="left" valign="top" class="first"><span>Age</span></td>
                                      <td align="center" valign="top" class="second"><span>:</span></td>
                                      <td align="left" valign="top"><?=$profile_info['s_age'];?><?=($this->session->userdata('age') || $profile_info['s_age'] >= $this->session->userdata('s_age_from')  &&  $profile_info['s_age'] <= $this->session->userdata('s_age_to'))?'<span class="match_fld"><img src="images/tick.png"></span>':''?></td>
                                    </tr>
                                    <tr>
                                         <td align="left" valign="top" class="first"><span>Location</span> 
                                      </td>
                                      <td align="center" valign="top" class="second"><span>:</span></td>
                                     <td align="left" valign="top"><?=get_user_address_info($profile_info['id'])?> <?=$this->session->userdata('location')?'<span class="match_fld"><img src="images/tick.png"></span>':''?> </td>
                                  </tr>
                                    
                                    <tr>
                                      <td align="left" valign="top" class="first"><span>Website</span></td>
                                      <td align="center" valign="top" class="second"><span>:</span></td>
                                      <td align="left" valign="top"><a href="<?=$profile_info['s_website']?>" target="_blank"><?=$profile_info['s_website']?></a></td>
                                    </tr>
                                    <?php /*?><?php $p_url = get_profile_url($profile_info['id'], $profile_info['s_profile_name']); 
									?>
                                    <tr>
                                      <td align="left" valign="top" class="first"><span>Profile URL</span></td>
                                      <td align="center" valign="top" class="second"><span>:</span></td>
                                      <td align="left" valign="top"><a href="<?=$p_url?>" target="_blank"><?=$p_url?></a></td>
                                    </tr><?php */?>
                                  </table>
                                 
                              </div>
                              <div class="clr"></div>
                              
                                
                    
                   			  
                              
                              
                               <ul class="profile-msg-send">
                                  <?php if($prayer_partner['display_alreadyprayer_partner'] == 'true'):?>
                                      <li><a href="javascript:void(0);" class="send-pro-message">Send A Message</a></li>
                                   <?php endif;?>  
                                     
                                      <?php if($display_becomefriend == 'false'):?>
                                            	<li><a href="javascript:void(0);" id="invite_friend_<?=($profile_info['id'])?>" onclick="invite_friend_('<?=encrypt($profile_info['id'])?>')" class="addfriend">Re-send Friend Request</a></li>
                                      <?php else :?>
                                      			<li><a href="javascript:void(0);" id="invite_friend_<?=($profile_info['id'])?>" onclick="invite_friend_('<?=encrypt($profile_info['id'])?>')" class="addfriend">Send Friend Request</a></li>
                                      <?php endif; ?>
                                      
                                       <?php if($display_becomenetpals == 'false'):?>
                                       			<li><a href="javascript:void(0);" id="invite_netpal_<?= $profile_info['id']?>"  onclick="invite_netpals_(<?php echo $profile_info['id'];?>)" class="netpal">Reinvite As NetPal</a></li>
                                       <?php else :?>
                                      			<li><a href="javascript:void(0);" id="invite_netpal_<?= $profile_info['id']?>"  onclick="invite_netpals_(<?php echo $profile_info['id'];?>)" class="netpal">Send Netpals Request</a></li>
                                      <?php endif; ?>
                                      
                                      
                                         <?php  if($prayer_partner['display_becomeprayer_partner'] == 'false'): ?>
                                        	 <li> <a  href="javascript:void(0);" id="invite_prayer_partner_<?=($profile_info['id'])?>" onclick="invite_prayer_partner_('<?=encrypt($profile_info['id'])?>','<?=$prayer_partner['display_becomeprayer_partner']?>')" class="add-as-friend">Re-send Partner Request</a></li>
                                              
                                                                                            
                                          <?php elseif($prayer_partner['display_alreadyprayer_partner'] == 'true'):?>
                                          		<li><a href="javascript:void(0);" class="invite-partner"> Already Your Partner </a></li>
                                          
                                         
										 <?php elseif($prayer_partner['is_available']=='false') : ?>
                                         		<li><a href="javascript:void(0);" class="invite-partner">Not Available as Partner</a></li>
                                                 
                                          
										  <?php else: ?>
                                         <li> <a  href="javascript:void(0);" id="invite_prayer_partner_<?=($profile_info['id'])?>" onclick="invite_prayer_partner_('<?=encrypt($profile_info['id'])?>','<?=$prayer_partner['display_becomeprayer_partner']?>')" class="invite-partner">Invite As Partner</a></li>
                                          
                                          <?php endif; ?>
                                      
                                  </ul>
                                  
                        <div class="new-wl" >
                        <div class="comments-number" style="width:100%">
                                                          
                             <div class="comments-number-mid">
                              <div class="heading">
                                    <div class="left">
                                          <h4 style="line-height:24px;"><img alt="" src="images/icons/cmnt2.png" class="cmnt" height="20px" width="20px"/> Send A Message</h4>
                                          <img src="images/minus-white.png" alt="" class="wal-minus" width="13" height="10"/>
                                    </div>
                        		</div>
                              
                                
                              
                                <table width="100%" cellspacing="0" cellpadding="0" border="0" class="profile-msg-table" >
                                 <tr>
                                    <td valign="middle" align="left">To: </td>
                                    <td valign="top" align="left"><?=$profile_info['s_profile_name']?></td>
                                  </tr>
                                  <tr>
                                    <td valign="middle" align="left">Subject: </td>
                                    <td valign="top" align="left"><input type="text" class="profile-txt-width"  id="subject" name="subject" /></td>
                                  </tr>
                                  <tr>
                                    <td valign="top" align="left">body:</td>
                                    <td valign="top" align="left"><textarea class="profile-txt-width"  name="message" id="message"></textarea></td> 
                                    
                                  </tr>
                                  <tr style="">
                                  <td valign="top" align="left">&nbsp;&nbsp;</td>
                                  <td class="error_msg" id="err_send_message" style=" margin-left:138px;"></td>
                                  </tr>
                                 
                                  <tr>
                                    <td></td>
                                    <td><input type="button"  class="yellow-btn" value="Send" onclick="send_message_from_public_profile()" /></td>
                                  </tr>
                                  <input type="hidden" id="recipent_id" value="<?=($profile_info['id'])?>" />
                                </table>
                            </div>
                                                         
                        </div>
                    </div>
                          </div>
                        </div>
                        
                        <div class="heading"><h4>Basic Info</h4></div>
                        <div class="profile-content">
                          <div class="profile-tab first">
                              
                              <div class="content-section" style="float:left; width:710px;">
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>Languages I Speak</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"><?=$profile_info['s_languages']?> <?=(strtolower($this->session->userdata('language')) == strtolower($profile_info['s_languages']) && strtolower($this->session->userdata('language')) != '')? '<span class="match_fld"><img src="images/tick.png"></span>':''?></td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>About Me</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"><?=nl2br($profile_info['s_about_me'])?></td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>My Church Name</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"><?=$profile_info['s_church_name']?></td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>Church Location</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"><?=get_church_address_info($profile_info['id'])?></td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>Church Phone</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"><?=$profile_info['s_church_phone']?></td>
                                          </tr>
                                          <tr>
                                            <td align="left" valign="top" class="first"><span>Denomination</span></td>
                                            <td align="center" valign="top" class="second"><span>:</span></td>
                                            <td align="left" valign="top"> 	<?=$profile_info['s_name']?> <?=($this->session->userdata('s_denomination') == $profile_info['i_id_denomination'] && $this->session->userdata('s_denomination') != 0)? '<span class="match_fld"><img src="images/tick.png"></span>':''?></td>
                                          </tr>
                                        </table>
                              </div>
                          </div>
                        </div>
                        
                        </div>
                        <!-- /right container -->
                        
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<div class="lightbox send_message_div" style="width: 600px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="images/icons/msg.png" alt="" width="48" height="32"  />Write Message</h4>
                  </div>
            </div>
            <div class="frm_box">
             <div class="lable05">To:</div> 
             <div class="field03"><span style="color:#004084; font-size:14px;"><?=$profile_info['s_profile_name']?></span></div>
             <input type="hidden" id="recipent_id" value="<?=encrypt($profile_info['id'])?>" />
             <div class="clr"></div>
             
              <div class="lable05">Subject:</div> 
             <div class="field03"><input type="text" name="subject" id="subject" /></div>
             <div class="clr"></div>
             
             <div class="lable05">Body:</div> 
             <div class="field03"><textarea style="width:400px; height:100px;" rows="" cols="" name="message" id="message"></textarea></div>
             <div class="error_msg" id="err_send_message" style=" margin-left:138px;"></div>
             <div class="clr"></div>
              <div class="clr"></div>
             
             <div class="lable05">&nbsp;</div> 
             <div class="field01"><input type="button" class="btn" value="Send" name="" onclick="send_message_from_public_profile()" /></div>
             <div class="clr"></div>
           </div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>


<script type="text/javascript">
 $(document).ready(function() {
	  
	  $('.link-report').click(function(){
		  //alert('hi');
		  $('.text-section').stop(true, true).slideToggle('slow');
	  });

  });
  
  function rate_user(profile_id, rate){
	  showUILoader_nodialog();
	  $.ajax({
		  type: 'get',
		  url: base_url + 'public_profile/giveProfileRating/'+profile_id+'/'+rate+'/',
		  dataType: 'json',
		  success: function(data, status) {
			  $('#rate_div').html(data.html);
			  showUIMsg(data.msg);
			  hideUILoader_nodialog();
			
		  }	// end of success function...
	  });
  }
  
  
  function report_abuse_profile(){
	  showUILoader_nodialog();
	  $.ajax({
		  type: 'post',
		  url: base_url + 'public_profile/abuseProfile/'+<?= $profile_info['id'] ?>,
		  data: {'s_reason':$('#txt_abuse_profile_text').val()},
		  dataType: 'json',
		  success: function(data, status) {
			  
			  showUIMsg(data.msg);
			  $('#txt_abuse_profile_text').val('');
			  $('.link-report').trigger('click');
			  hideUILoader_nodialog();
		  }	// end of success function...
	  });
  }
</script>