<!-- HEADER SECTION -->

<div id="header_section">
  <div id="header">
    <div id="logo"><a href="<?=admin_base_url()?>"><img src="<?= base_url() ?>images/logo.png" alt="" /></a></div>
    <!-- section 01 -->
    
    <div class="right">
      <ul>
        <li style="background:none;"><a href="<?php echo admin_base_url()?>">Welcome Administrator</a></li>
        <li class="blue_link"><a href="<?php echo base_url()?>">Back to site</a></li>
        <li class="blue_link"><a href="<?php echo base_url()?>signout.html">Sign Out</a></li>
      </ul>
      <h4>BACK OFFICE D'ADMINISTRATION</h4>
    </div>
  </div>
</div>
<!-- /HEADER SECTION -->