<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<div class="clr"></div>

<!-- CONTENT SECTION -->

<div id="content_section">
      <div id="container">
      <!-- main container -->
      <!-- latest news -->
	 	<?php include(APPPATH ."views/layouts/latest_news.phtml");?>
      <!-- /latest news -->
      <div class="clr"></div>
      <div id="main_container">
      	<!-- left container -->
	     <?php include(APPPATH."views/layouts/leftbar.phtml");?>
        <!-- /left container -->
      	<div id="mid_container">
          <div class="christian-news-bg-1">
                <h2 class="white-title">Christian News</h2>  
          </div>
          <!--tabbed content start -->    
          <div class="dp-list-main-box">
                    <?php include(APPPATH."views/logged/media_center/christian_news/christian_news_left_panel.phtml");?>
                    <!--tab description  -->
                    <DIV id="parent_tab_container">
                        <div class="dp-list-content-box select-display">
                                <h2 id="heading"><?=$cat_name?></h2>
                            <div id="content"><?=$listingContent?></div>
                            
                        </div>
                        
                        <?php 
                        //echo "current : ".$current_page;
                        if($view_more)  :
                        ?>
                        <div id="view_more_div" class="tab_details menu-details" style="min-height: 50px;">
                            <div class="article-pagination inside-tab">
                                <a id="view_more_news" href="javascript:void(0)" style="float: right; color: #b2b2b2; margin-right: 5px; font-size: 15px;" onclick="return show_more_feeds(<?=$current_page?>)" page_value="<?=$current_page?>">[View More] </a>
                            </div>
                        </div>
                        <?php
                        endif;
                        ?>
                    </DIV>
                    
                    
                    
                    <!--tab description  end-->
              </div>
          <!--tabbed content end -->  
          </div>      
         <?php include(APPPATH."views/layouts/rightbar.phtml");?>
         </div>
      <!-- main container end-->       
      </div>
      <div class="clr"></div>
</div>


<!-- /CONTENT SECTION -->
<div class="clr"></div>

<input type="hidden" id="h_news_id" value="">
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>




<div class="lightbox liked_by_div" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/thumb_up.png" alt="" /> Liked by </h4>
                  </div>
            </div>
            <div id="liked_html"></div>
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>


<!--view comment div-->
<div class="lightbox view_comments_div " style="width:650px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24"/></a></div>
      <div class="top">
            <div>&nbsp;</div>
      </div>
      <div class="mid" >
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4><img src="<?=base_url()?>images/icons/cmnt.png" alt="" width="30" height="30"/> View Comments </h4>
                  </div>
            </div>
            <div id="comment_html"></div>

            
      </div>
      <div class="bot">
            <div>&nbsp;</div>
      </div>
</div>
<!--/view comment div-->
<!-- /lightbox SECTION -->

<?php //include(APPPATH."views/logged/blocks/common_popup.phtml");?>


