<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <?php /*?><div id="top_corner">&nbsp;</div><?php */?>
            <div id="mid_content">
                  <!-- latest news -->
                   <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        	<!--my tweeter profile start -->    
                            <div class="tweeter-profile">
                             	<div class="search-panel">
                                	<p class="title">Profile Summary</p>
                                    <div class="tweeter-search">
                                    <span>Search People:</span>
                                    <form action="" method="post" enctype="multipart/form-data" class="tweeter-search-form">
                                    	<input name="" type="text" id="searchTweeter">
                                        <input name="" type="submit" value="">
                                    </form>
                                    </div>
                                </div>
                                
                                <!--tweeter header start -->  
                                <div style="background:url(images/tweeter-profile-bg.jpg) no-repeat 0 0;" class="tweeter-profile-header">
                                	<?php /*?<div class="follow-section">
                                    	><span class="follow-btn"><input name="Follow" type="button" value="Follow"></span>
                                    </div><?php */?>
                                    <div class="clr"></div>
                                    
                                   <?php include(APPPATH ."views/logged/my_tweet/tweet_user_detail.phtml");?>
                                </div> 
                                <!--tweeter header end --> 
                                <!--tweeter page nav start --> 
                                 <?php include(APPPATH ."views/logged/my_tweet/my_twitter_menu.phtml");?>
                                <!--tweeter page nav end -->  
                                <!--write tweet section start -->
                                <div class="write-tweet">
                                	<form action="" method="post" enctype="multipart/form-data">
                                    	<span class="tweet-top-curve"></span>
                                        <div class="tweet-mid-curve"><textarea  class="tweet-comment-box" id="ta_post_tweet" 
                                        name="ta_post_tweet" onfocus="if(this.value=='Max 140 Characters')this.value='';" 
                                            onblur="if(this.value=='')this.value='Max 140 Characters';"  >Max 140 Characters</textarea></div>
                                        <span class="tweet-bot-curve"></span>
                                        <input name="Cancel" type="button" value="Cancel" class="tweetCancel">
                                        <input name="" type="button" value="Tweet" class="tweetSubmit" onclick="post_tweet_text('all_tweet')">
                                    </form>
                                    
                                    <input name="txt_ville" id="txt_ville"  type="text" style="margin-bottom: 5px;"   value="<?=$s_search_ville==''?t("Ville"):$s_search_ville?>" onclick="if(this.value=='<?=t("Ville")?>') this.value ='';" onblur="if(this.value=='') this.value ='<?=t("Ville")?>';"/>
                                    <div class="clr"></div>
                                </div>
                                <!--write tweet section end -->
                            	<div id="tweet_contents"><?=$tweets_ajax_content?></div>  
                            </div>
                            <!--my tweeter profile end -->  
                              <?php if($no_of_result  == 0):?>
                                <div class="shade_box_01" style="padding-top:5px;" id="no_tweets"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Tweets.</p></div></div>
                            <?php endif;?>	
                            <textarea id="test_ta" style="width:415px; resize:none;"></textarea>
                            
                            <?php if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="<?=$current_page_1?>" onclick="show_more_tweets($(this).attr('page_value'))">[view more] </a> </div>
                            <?php endif; ?>
                            <input type="hidden" id="i_user_id" value="<?=$profile_id?>" />
                        </div>
                        <!-- /mid container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>

<!-- /FOOTER SECTION -->
<!--popup one start-->
<div class="lightbox delete-popup" style="width:500px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Tweet</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete this Tweet?</p>
               </div>
               <form action="" method="post" enctype="multipart/form-data">
               		 <input type="hidden" name="i_del_id" id="i_del_id" value="" />
               		<input name="" type="button" value="Yes" class="btn" style="margin-left:146px;" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<!--popup one end-->

<!-- /lightbox SECTION -->
<script type="text/javascript">

$(function() {

   $('#txt_ville').live("keypress", function(e) {
	   //alert(e.which);
    	if(e.which == 35)
		  $("#txt_ville").autocomplete("<?php echo base_url();?>logged/tweet_home/show_trends",  {
		  width: 210,
		  selectFirst: true,
		  minChars: 2,
		  multiple: false,
		  multipleSeparator: "\n",
		  max: null,
		 // matchContains: true,
		 // formatItem: formatItem,
		  
		  highlight: highlight_text
		 });
   	
   });
   
   
});
	
function formatItem(row) 
{//console.log(row);
 //alert(row);
 //var n=row[0].replace(/[,]/g,"\n"); console.log(n);	
 if(row[0]!="No match found")
  return  "<span style='font-size:11px; font-weight:normal; margin:0px; padding: 3px 5px ;cursor: pointer; display:block;'>ddhgshdg" + row[0]+"</span>";
 else
  return " (<span style='font-size:11px;'>dddfs" +row[0]+"</span>)";
}

function highlight_text(value, term){
		return value.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)(" + term.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi, "\\$1") + ")(?![^<>]*>)(?![^&;]+;)", "gi"), "<strong>$1</strong>");
}

<?php /*?>
function changeText(event, ui) {
	
      var selectedElement = event.target.innerText;
      var text = $(this).val();
      text.replace(/#$/ , selectedElement);
	  text = text.replace(/#$/ , selectedElement);
      $(this).val(text);
}



function getSign(text){
  var indexOfAt = text.lastIndexOf('#');
  return indexOfAt;
};

function changeText(event, ui) {
      var selectedElement = event.target.innerText;
      var text = $(this).val();
      text.replace(/#$/ , selectedElement);
	  text = text.replace(/#$/ , selectedElement);
      $(this).val(text);
}

$(document).ready(function() {

$('#txt_ville').live("keypress", function(e) {
	   //alert(e.which);
    	if(e.which == 35)
  $("#txt_ville").autocomplete({
    source: function(request, response) {
		
      $.ajax({
        url: "/logged/tweet_home/show_trends",
        data: { 
          term: request.term.substr(getSign(request.term)+1,request.term.length-getSign(request.term)).trim() 
        },
        success: function(data){
          for(i=0; i<data.length; i++){
            data[i] = '#'+data[i];
          }
          return response(data);
        }
      });
    },
    minLength: 1,
    delay: 200,
    disabled: true,
    search: function() {
      if ( /\s$/.test($(this).val()) ) {
        $(this).autocomplete('disable');
      };
    },
    select: changeText
  });

});

  $("#txt_ville").keyup(function() {
    if ( /#$/.test($(this).val()) ) {
      $(this).autocomplete('enable');
    };
  });

});
<?php */?>

			
$(document).ready(function(){
		$("#searchTweeter").autofill({'value':"Type Keyword"}); 
		//$("#ta_post_tweet").autofill({'value':"Compose New Tweet"});
		
		$('.tweet-comment-box').focus(function(){
			$(this).animate({height:'50px'},500);
			$('.tweetSubmit, .tweetCancel').fadeIn('fast',function(){
					$('.tweetCancel').click(function(){
						$(this).parent('form').find('.tweet-comment-box').animate({height:'18px'},500);
						$('.tweetSubmit, .tweetCancel').stop(true,true).slideUp();
					});
					
					// added to slide p after tweeting
					$('.tweetSubmit').click(function(){
						$(this).parent('form').find('.tweet-comment-box').animate({height:'18px'},500);
						$('.tweetSubmit, .tweetCancel').stop(true,true).slideUp();
					});
			});
		});
		
	});

</script>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_tweets(page) {
	
	var i_user_id = $('#i_user_id').val();
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/tweet_home/all_tweets_ajax_pagination/'+i_user_id+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				
				//alert(data.cur_page+'dfdf');
				$('#tweet_contents').append(data.html);
				$('#show_more_tweets_link').attr('page_value', data.cur_page);
				$('#show_more_tweets_link').attr('onclick','');
				$('#show_more_tweets_link').attr('onclick','show_more_tweets('+data.cur_page+')');
			}
			else {
				$('#tweet_contents').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Tweets.</p></div>');
				$('#show_more_div').remove();
			}
            
            if(data.view_more==false)
            {
                
                $('#tweet_contents').append('<div class="view_more" style="text-align: center;" id="show_more_div"><p class="blue_bold12" style="font-size:14px;">No More Tweets.</p></div>');
                $('#show_more_div').remove();
            }
		

		}	// end of success function...
	});
}

$(document).ready(function(arg) {
	

 $('#frm_search').submit(function(){ 
			
		  var i_user_id = $('#i_user_id').val();			
		  var datatosend=$("#frm_search").serialize();
		   showUILoader_nodialog('<img src="'+base_url+'images/loading_big.gif" width="50"/> ');
			  $.ajax({
					 type: "POST",
					 url: base_url+'logged/tweets/all_tweets_ajax_pagination/'+i_user_id,
					 data: datatosend,
					 dataType : 'json',
					 success: function(data){
						$('#frm_search')[0].reset();
						
						if(data.html!='') {
							//alert( data.cur_page+' posting');
							$('#show_more_div').remove();
							$('#tweet_contents').html(data.html);
							$('#show_more_tweets_link').attr('page_value', data.cur_page);
							$('#show_more_tweets_link').attr('onclick','');
							$('#show_more_tweets_link').attr('onclick','show_more_tweets('+data.cur_page+')');
						}
						else {
							$('#tweet_contents').html('<div class="view_more" style="text-align: center;" ><p class="blue_bold12" style="font-size:14px;">No Tweets.</p></div>');
							$('#show_more_div').remove();
						}
						
						
						//alert(data.no_of_result- data.current_page);
						if(data.no_of_result == 0){
							$('#show_more_div').remove();
						}
						else if(data.view_more==false )
						{
							//alert(1);
							$('#tweet_contents').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Tweets.</p></div>');
							$('#show_more_div').remove();
						}
						else if((data.no_of_result - data.cur_page != 0)){
							//alert(2);
							
							$('#show_more_div').remove();
							$('#mid_container').append('<div class="view_more" id="show_more_div"><a href="javascript:void(0);" id="show_more_tweets_link" page_value="'+data.cur_page+'" onclick="show_more_tweets('+data.cur_page+')">[view more] </a> </div>');
						}
						
						hideUILoader_nodialog();
					 }
			   });	 
	
		});
 


});


</script>
<script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     {
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#ta_post_tweet').keyup(function(){
            limitChars('ta_post_tweet', 140, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('ta_post_tweet',140, '');
    
 
});
</script>