<?php  //pr($commit_arr);
	if(count($commit_arr)){
		foreach($commit_arr as $val){
			
			$profile_image_filename = get_profile_image_of_user('thumb',$val['s_profile_photo'],$val['e_gender']);
			$DESC = html_entity_decode(htmlspecialchars_decode($val['s_contents']),ENT_QUOTES,'utf-8');
?>
<div class="commitment-box"> 
        <a href="javascript:void(0);" class="profile-image"><div style="background:url('<?=$profile_image_filename?>') no-repeat center;width:60px; height:60px;" ></div></a>
        <div class="right-panel">
            <p class="quoted-text">
                <?=nl2br($DESC)?> 
                <span>Updated on: <?=get_time_elapsed($val['dt_created_on'])?></span>
            </p>
            <h2 class="name"><?=$val['s_profile_name']?></h2>
            <p class="place"><?=$val['s_country']?></p>
            <p class="date-time"><span style="margin-right: 2px;">From: </span><?=getShortDate($val['dt_start_time'], 5)?></p> 
            <p class="date-time"><span style="margin-right: 16px;">To: </span><?=getShortDate($val['dt_end_time'], 5)?></p>
        </div>
        <div class="clr"></div>
</div>
<?php
		}
	}
	
?>