<script type="text/javascript">
<!--
    function showPersonalEdit(obj) {
        $(obj).parents('.text-table').hide();
        if($(obj).parents('.sec-detail').find('.form-table').css('display')=='none'){
            $(obj).parents('.sec-detail').find('.form-table').show();
            $(obj).parents('.sec-detail').find('.dd').show();
        }
    }
    
    
    // when "cancel" button clicked...
    function hidePersonalEdit(obj) {
        
        //// remove those extra "add-more" divs...
       /* var actual_edu_rec_count = parseInt( $('#actual_personal_divs').val() );
        var max_no_of_tbls = 5;
        var start_loop = actual_edu_rec_count+1;
        for(i=start_loop; i<=max_no_of_tbls; i++) {
            tblID = "#edu_"+ i;
            $(obj).parents('.sec-detail').find(tblID).remove();
        }
        $('#h_edu').val( actual_edu_rec_count );    // resetting edu-count...
        $('#deleted_personal_divs').val('');        // resetting deleted record-count to 0 again...
        */
        
        $(obj).parents('.sec-detail').find('.form-table').hide(); 
        if($(obj).parents('.sec-detail').find('.text-table').css('display')=='none'){
            $(obj).parents('.sec-detail').find('.text-table').show();
            $(obj).parents('.sec-detail').find('.dd').hide();
            
        }
        
    }
//-->
</script>


<div class="show lavel-01" >
      <!--title section -->
      <div class="show sec-title">
          <span class="title-left"></span>
          <div class=" show title-body" id="first-title-body"><h2>Personal Information</h2></div>
          <span class="title-right"></span>
      </div>
      <!--/title section -->
      <!--detail section -->
      <?php
		  
          /*$address = (isset($result['s_city']))? $result['s_city']:"";
		  $address .= (isset($result['s_state']))? ', '.$result['s_state']:"";
		  $address .= (isset($result['s_country']))? ', '.$result['s_country']:"";
          */
         //echo get_country_name_by_id($result["i_country_id"]); 
            
         
         
         /*   $city     = $result["s_city"];
            $state    = $result["s_state"];
            $country  = get_country_name_by_id($result["i_country_id"]);  
            
            $personal_address=array();
           
            if(!empty($city))
                $personal_address['city']=$city;
            if(!empty($state))
                $personal_address['state']=$state;
            if(!empty($country))    
                $personal_address['country']=$country;
            
            
            $address= implode(', ',$personal_address);
		
		*/
		?>
      
      
      <div class="sec-detail" id="first-sec-detail">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table text-table" id="member_personal_info_details">
              
      <?php    $city     = $result["s_city"];
            $state    = $result["s_state"];
            $country  = get_country_name_by_id($result["i_country_id"]);  
            
            $personal_address=array();
           
            if(!empty($city))
                $personal_address['city']=$city;
            if(!empty($state))
                $personal_address['state']=$state;
            if(!empty($country))    
                $personal_address['country']=$country;
            
            
            $address= implode(', ',$personal_address);
             ?> 
              
              <tr>
                <td colspan="3" align="left" valign="top" height="30" ><h3><?php echo $result['s_title'].' '.$result['s_profile_name'];?></h3></td>
              </tr>
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">Location</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><?php echo $address;?></td>
              </tr>                                                    
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">Date of Birth</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><?php if($result['dt_dob'] != "0000-00-00") echo getShortDateWithTime($result['dt_dob'],4);?></td>
              </tr>
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">Want to be Prayer Partner</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><?php echo ($result['e_want_prayer_partner']=='N')? 'No':'Yes';?></td>
              </tr>                            
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">Want to be Net Pal</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><?php echo $result['s_want_net_pal'];?></td>
              </tr>
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">My Website</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><a href="javascript:void(0);"><?php echo $result['s_website'];?></a></td>
              </tr>
              <tr>
                <td align="left" valign="top" height="25" width="180" class="label">My Profile URL</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><a href="http://www.cogtime.com/<?php echo $result['s_profile_url_suffix'];?>" target="_blank">www.cogtime.com/<?php echo $result['s_profile_url_suffix'];?></a></td>
              </tr>
              <tr>
                <td align="left" valign="bottom" height="40" colspan="2">&nbsp;</td>
                <td align="left" valign="bottom"><a href="javascript:void(0);" class="edit-btn">Edit</a></td>
              </tr>
          </table>
          
          <form id="frmManageProfile" method="post" action="<?=admin_base_url().'members/member_details/modify_profile_personal_info_ajax/'.$result['id']?>" onsubmit="return modify_my_profile_ajax()" enctype="multipart/form-data">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" class="member-table form-table">
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Title</td>
                <td align="left" valign="top" width="20" class="label">:</td> 
                <td align="left" valign="top" >
                                           
              <select name="title" id="title"  style="width:70px; margin-right:2px;">
                <option value="-1"><?= "Select" ?></option>
                <option value="Mr" <?php echo $selected =($result["e_title"]=='Mr')?'selected':''?>>Mr.</option>
                <option value="Mrs" <?php echo $selected =($result["e_title"]=='Mrs')?'selected':''?>>Mrs.</option>
                <option value="Ms" <?php echo $selected =($result["e_title"]=='Ms')?'selected':''?>>Ms.</option>
              </select>
             
                </td>
                 
              </tr>
               <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_title"></div></td>
             </tr>
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">First name</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" name="txt_fname" id="txt_fname" value="<?php echo $result['s_first_name'];?>" /></td>
                
              </tr>
          	 <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_fname"></div></td>
             </tr>
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Last name</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" name="txt_lname" id="txt_lname" value="<?php echo $result['s_last_name'];?>" /></td>
              </tr>
               <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_lname"></div></td>
             </tr>
             
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Email</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" id="txt_email" name="txt_email"  value="<?=$result['s_email']?>"/></td>
              </tr>
              <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_email"></div></td>
             </tr>
              
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">City</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" name="txt_city" id="txt_city" value="<?php echo $result['s_city'];?>" /></td>
              </tr>
              
              
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">State</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" name="txt_state" id="txt_state" value="<?php echo $result['s_state'];?> "/></td> 
              </tr>
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Country</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                
                <td align="left" valign="top" >  <select name="txt_country" id="txt_country" style="width:238px; margin-bottom:6px;">
                     <option value="-1">Select</option>
                     <?=makeOptionCountry('',encrypt($result['i_country_id']));?>
                     
                  </select>
                  <script type="text/javascript">
                      $(document).ready(function(arg) {
                          $("#txt_country").msDropDown();
                          $("#txt_country").hide();
                          //$('#txt_country').css("width", "20px"); 
                      })
                  </script>
                <?php /*?><input type="text" name="txt_country" id="txt_country" value="<?php echo $result['s_country'];?> "/><?php */?></td> 
              </tr>
              
             <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_country"></div></td>
             </tr>
              
              <tr>
              <td align="left" valign="top" height="30" width="180" class="label">Time Zone</td>
              <td align="left" valign="top" width="20" class="label">:</td>
              <td align="left" valign="top" >
                <select  id="time-zone" name="time-zone" style="width:238px;">
                    <option value="-1">Select</option> 
                     <?= makeOptionTimezones($result['s_time']) ?>
                </select>
                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        $("#time-zone").msDropDown();
                        $("#time-zone").hide();
                    })
                </script>
              </td>
              
             
              
             
            <tr>
            <td align="left" valign="top" height="30" width="180" class="label">Date of birth</td>
            <td align="left" valign="top" width="20" class="label">:</td>
            <td>
              <?php
            # getting day-month-yr extracted from db DOB...
			if($result['dt_dob'] != "0000-00-00"){
			  $DOB_TSTAMP = strtotime($result['dt_dob']);
			  $DOB_DAY = date( "j", $DOB_TSTAMP );
			  $DOB_MONTH = date( "n", $DOB_TSTAMP );
			  $DOB_YR = date( "Y", $DOB_TSTAMP );
			}
        ?>
        
            <select name="day" id="day"  style="width:70px; margin-right:2px;">
              <option value="-1"><?= "---" ?></option>
              <?= makeOptionDay($DOB_DAY) ?>
            </select>
            
            <select name="month" id="month"  style="width:85px; margin-right:2px;">
                  <option value="-1"><?= "---" ?></option>
                  <?= makeOptionMonth($DOB_MONTH) ?>
            </select>
            
            <select name="year" id="year"  style="width:70px;">
                  <option value="-1"><?= "---" ?></option>
                  <?= makeOptionDobYear($DOB_YR) ?>
            </select> 
            
            <script type="text/javascript">
              $(document).ready(function(arg) {
                  $("#day").msDropDown();
                  $("#day").hide();
                  $("#month").msDropDown();
                  $("#month").hide();
                  $("#year").msDropDown();
                  $("#year").hide();
				  $("#title").msDropDown();
                  $("#title").hide();
              })
          </script>
                  
                </td>
              </tr>
             
             
             <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" style="margin-top: 0px;" id="err_month"></div></td>
             </tr>
             
              
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Want to be Prayer Partner</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top">
                  <select name="txt_prayer_ptnr" id="txt_prayer_ptnr" style="width:120px;">
                      <option value="Y" <?php echo ($result['e_want_net_pal']=='Y')? 'selected="selected"':'';?>>Yes</option> 
                      <option value="N" <?php echo ($result['e_want_net_pal']=='N')? 'selected="selected"':'';?>>No</option>
                  </select>
                  <script type="text/javascript">
                      $(document).ready(function(arg) {
                          $("#txt_prayer_ptnr").msDropDown();
                          $("#txt_prayer_ptnr").hide();
                      })
                  </script>
                </td>
              </tr>
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Want to be Net Pal</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" >
                  <select name="txt_net_pal" id="txt_net_pal" style="width:120px;">
                      <option value="Y" <?php echo ($result['e_want_prayer_partner']=='Y')? 'selected="selected"':'';?>>Yes</option> 
                      <option value="N" <?php echo ($result['e_want_prayer_partner']=='N')? 'selected="selected"':'';?>>No</option>
                  </select>
                  <script type="text/javascript">
                      $(document).ready(function(arg) {
                          $("#txt_net_pal").msDropDown();
                          $("#txt_net_pal").hide();
                      })
                  </script>
                </td>
              </tr>
               <tr>
                <td align="left" valign="top" height="30" width="180" class="label">Mobile</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" id="txt_phone" name="txt_phone" value="<?=$result['s_mobile']?>" /></td>
              </tr>
              
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">My Website</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" ><input type="text" name="txt_website" id="txt_website" value="<?php echo $result['s_website'];?>" /></td> 
              </tr>
                             
              
              <tr>
                <td align="left" valign="top" height="30" width="180" class="label">My Profile URL</td>
                <td align="left" valign="top" width="20" class="label">:</td>
                <td align="left" valign="top" >www.cogtime.com/ <input type="text" id="txt_profile_url" name="txt_profile_url" style="width:220px;" value="<?php echo $result['s_profile_url_suffix'];?> "/></td>
              </tr>
             
              <tr>
              <td align="left" valign="top" colspan="3" ><div class="error-message" id="err_profile_url"></div></td>
             </tr>
              <tr>
                <td align="left" valign="bottom" height="30" colspan="2">&nbsp;</td>             
                <td align="left" valign="bottom">
                <input name="" type="submit" class="btn"  value="Update"/>
                <input name="" type="reset" class="btn cancel_btn"  value="Cancel" onclick="hidePersonalEdit(this)" />
                <input type="hidden" name="is_submitted" id="is_submitted" value="Y" />
               </td>
              </tr>
          </table>
          </form>
      </div>
      <!--/detail section -->
</div>