<?php /*?> <?php
 if(count($info_arr)){ 
 ?>
	<script type="text/javascript">
    <!--
    function pausePlayers(playing_id) { 
      
       <?php
        foreach($info_arr as $val):
        ?>
            
               if(<?=$val['id']?> != playing_id) { jwplayer("myElement_"+<?=$val['id']?>).pause(true); }
        <?php
            endforeach;
        ?>
    };
    
    $(function(){
    <?php
        foreach($info_arr as $val):
		
		  if($val['e_type'] == 'audio'){
            //$ID = 'm1'. $val['id'];
          echo  $audio_filename = base_url()."uploads/user_audio_files/".get_audio_track_by_id($val['i_referenced_id']);
    ?>
        
         jwplayer("myElement_<?=$val['id']?>").setup({
            file: "<?=$audio_filename?>",
            image: "<?=$audio_filename?>",
            height: 30,
			width: 285,
    
            events:{
              onPlay: function() {
                    pausePlayers(<?=$val['id']?>);
                 //jwplayer('container3').stop();
              }
            }
    
         });
    <?php
		  }
        endforeach;
    ?>
    });
    //-->
    </script>
 <?php }
 ?><?php */?>
    
    
    <table width="80%" border="0" cellspacing="0" cellpadding="0" class="admin-table">
                                      <tr>
                                        <th align="left" valign="middle" height="30" width="300">Media</th>
                                        <th align="left" valign="middle" height="30" width="70">Posted By</th>
                                        <th align="left" valign="middle" height="30" width="100">Posting Date</th>
                                        <th align="center" valign="middle" height="30" width="80">Abuse Count</th>
                                        <th align="center" valign="middle" height="30" class="last" width="40">Actions</th>
                                      </tr>
                                     <?php
									 	
									 if(count($info_arr)){ 
											foreach($info_arr as $k=> $info){
												
												$type = $info['e_type'];
												$id = $info['i_referenced_id'];
												if($type == 'user'){
												  $stype = 'user profile'	;
												  $type_name = get_username_by_id($id);
												  $img = get_profile_image($id); 
												}
												else if($type == 'audio'){
												  $stype = 'user audio'	;
												  $type_name = get_audio_title($id);
												}
												else if($type == 'video'){
												  $stype = 'user video'	;
												  $type_name = get_video_title($id);
												}
												else if($type == 'photo'){
												  $stype = 'user photo'	;
												  $type_name = get_photo_title($id);
												  $img = get_photo_by_id($id); 
												}
												else if($type == 'event'){
												  $stype = 'event'	;
												  $type_name = get_event_title_by_id($id);
												}
									  
									  		$s_status = ($info['i_status'] == 1)?'Disable':'Enable';	  
									  ?>
                                   		  <tr>
                                        <td align="left" valign="top" class="banner-img">
                                        
                                       <?php
										if($type == 'photo'){ 
									   ?>
                                        <a href="javascript:void(0);" style="float:left;"><p style="background:url(<?=$img?>) no-repeat center; width:110px; height:60px;border: 3px solid #DCDCDC; " title="photo"></p></a>
                                        
                                        <p class="abuse-info">Uploaded by : <?=get_photo_owner_name_by_id($id)?></p>
                                        <?php
										 }
										 else if($type == 'video'){ 
										 	$img = get_video_snap_by_id($id);
										?>
                                        <a href="javascript:void(0);" style="float:left;"><p style="background:url(<?=$img?>) no-repeat center; width:110px; height:60px;border: 3px solid #DCDCDC; " title="banner"></p></a>
                                        
                                        
                                        <p class="abuse-info" style="margin-right:104px;">Uploaded by : <?=get_video_owner_name_by_id($id)?></p><br/>
                                        <p style="float:left; margin-left:17px;"><?=get_video_title($id)?></p>
                                        <?php
										 }
										 else if($type == 'audio'){ 
										?>
                                        <a href="javascript:void(0);" style="float:left;"><img alt="image" src="../images/audio-icon.jpg"></a>
                                        <p class="abuse-info" style="margin-right:154px;">Uploaded by : <?=get_audio_owner_name_by_id($id)?></p>
                                        <br/>
                                        <p style="float:left; margin-left:17px;"><?=get_audio_title($id)?></p>
                                        <!--<div id="myElement_<?=$info['id']?>" style="width:285px;">Loading the player...</div>
                                        -->
                                        
                                        <?php
										 }
										 else if($type == 'event'){ 
										 
										 		$event_info = get_event_detail_by_id($id);
												
												$user_name = ($event_info['i_user_type'] == 2)?get_admin_nameby_id($event_info['i_host_id']):get_username_by_id($event_info['i_host_id']);
												
												
												//pr($event_info);
										?>
                                        
                                        <p> <?=my_substr(html_entity_decode(htmlspecialchars_decode($event_info['s_title']),ENT_QUOTES,'utf-8'), 38)?></p><p >Uploaded by : <?=$user_name?></p>
                                        
                                        <?php
										 }
										 else if($type == 'user'){ 
										?>
                                        	 <a href="javascript:void(0);" style="float:left;"><p style="background:url(<?=$img?>) no-repeat center; width:60px; height:60px;border: 3px solid #DCDCDC; " title="banner"></p></a>
                                        
                                             <p class="abuse-info">Profile Name: <?=get_username_by_id($info['i_referenced_id'])?></p>
                                        
                                        <?php
										 }
										?>
                                        </td>
                                        <td align="left" valign="top"><?=get_username_by_id($info['i_given_by_user_id'])?></td>
                                        <td align="left" valign="top"><?=getShortDate($info['dt_created_on'], 5)?></td>
                                        <td align="center" valign="top"><?=$info['abuse_count']?></td>
                                        <td align="center" valign="middle" class="last">
                                        <?php /*?>  <input name="" title="Delete" type="button" class="btn-02"  value="Confirm Abuse & Disable"/>
                                      <input name="" title="Delete" type="button" class="btn-02"  value="Not an Abuse"/><?php */?>
                                       <?php
									   
							  if($info['i_status'] == 1){ ?>
                            		<span id="<?=$info['id']?>_status"><input  title="Show" type="button" class="btn-03" onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 2 , <?php echo $info['i_status'] ?>, <?=$info['i_referenced_id']?>, '<?=$type?>')"  value="<?=$s_status?>"/></span>
                            <?php 
							    } 
								else if($info['i_status'] == 2){?>
                                	<span id="<?=$info['id']?>_status"><input title="Show" type="button" class="btn-03" onclick="javascript:changeStatus(<?php echo $info['id'] ?> , 1 , <?php echo $info['i_status'] ?>, <?=$info['i_referenced_id']?>, '<?=$type?>')"  value="<?=$s_status?>"/></span>
                            
                            <?php }?>
                                        </td>
                                      </tr>
                                     <?php }
										}
										else{
									 ?>
                                      <tr>
                                          <td style="text-align:center;" height="80" colspan="20">No data available!!!</td>
                                      </tr>
                                    <?php }
									?>
 </table>
 <div class="paging_box" >
            <ul><?= $page_links ?></ul>
</div>	
