<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery.multiselect.filter.css" />
<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/prettify.css" />
<!--<link rel="stylesheet" type="text/css" href="<?php echo  base_url()?>css/jquery-ui.css" />-->
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/jquery.multiselect.filter.js"></script>
<script type="text/javascript" src="<?php echo  base_url()?>js/prettify.js"></script>
<script type="text/javascript">
$(function(){
		$("#friendSlct").multiselect().multiselectfilter();	
		$("#ringselect").multiselect().multiselectfilter();
		$("#netpalselect").multiselect().multiselectfilter();
		$("#ppselect").multiselect().multiselectfilter();	
		$("#pgselect").multiselect().multiselectfilter();
	
	});
	
</script>
<script language="javascript">
<!--
var g_controller_url = base_url+"logged/create_audio_album.html";

var photo_id = null;
$(document).ready(function() {

	// for AJAX page-submission...
    var options = { 
        beforeSubmit:  showLoad,  // pre-submit callback 
        success:       validateFrm // post-submit callback 
    }; 
 
    // bind to the form's submit event 
    $('#frmPhotoAlbum').submit(function() {
        $(this).ajaxSubmit(options);
        return false;
		
    });

});

function showLoad()
{
 // $('#photo_album_btn').attr('disabled','disabled');
  $('#photo_album_btn').val('Creating...');
  
}


// validate ajax-submission...
function validateFrm(data)
{
	//alert( data);
	var data = JSON.parse(data);

	id=data.photo_id;

	if(data.success==false) 
	{
		
		$('.error-message').each(function(i){
			$(this).attr('style','display:none');
		});
		
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');

		for ( var id in data.arr_messages ){
			if( $('#err_'+id) != null ) {
				$('#err_'+id).html(data.arr_messages[id]);
				$('#err_'+id).css('display', 'block');
			}
		}

		
	}
	else {
		$('#photo_album_btn').val('Create');
		$('#photo_loading').html('');
		 $('#frmPhotoAlbum')[0].reset();

		showUIMsg(data.msg);		
		window.location.href="<?=$_SERVER['HTTP_REFERER']?>";
		
		
	}
	$('#sp_add_loading').html('');
				
}


-->
</script>
<script type="text/javascript">
$(document).ready(function () {

 //counting the left characters in comment
     function limitChars(textid, limit, infodiv)
     { //alert(1);
      var text = $('#'+textid).val(); 
      var textlength = text.length;
      if(textlength > limit)
      {
      $('#'+textid).val(text.substr(0,limit));
       return false;
      }
      else
      {
      
       return true;
      }
     }
    
    
    $(function(){
        $('#txt_desc').keyup(function(){
            limitChars('txt_desc', 500, '');
        });
    });
    
    
    //// just to show correct no. of chracters left while the page is loaded...
    limitChars('txt_desc',500, '');
    
 
});
</script>
<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>

<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                      <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- left container -->
                        <div id="mid_container">
                       <div class="page_heading">
                                <div class="left"><img src="images/icons/audio.png" alt="" /> Audios</div>
                              
                            </div>
                         <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                                  <ul>
                                    <li><a href="my-audios.html"><span>My Audios</span></a> </li>
                                    <li><a href="manage-my-audio.html"><span>Manage My Audio Albums</span></a> </li>
                                    <li><a href="javascript:void(0);" onclick="return show_dialog('upload_audio')"><span>Upload Audio</span></a></li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                              <!--/sub page links -->
                        
                        
                        	
                            <form id="frmPhotoAlbum"  method="post" action="<?=base_url().'logged/create_audio_album/add_audio_album'?>" onsubmit="return false;" enctype="multipart/form-data" class="form-manage">
                             <div class="frm_box blue_box" style="background:url(images/music.png) no-repeat 20px 90% #f0f7fa; width:452px;">
                                    <div class="lable01">Name:</div>  
                                    <div class="field01">
                                    <input name="txt_name" id="txt_name" type="text" />
                                    <span id="err_name" class="error-message"></span>  
                                    </div> 
                                    <div class="clr"></div>
                                    
                                   <?php /*?> <div class="lable01">Privacy:</div>  
                                    <div class="field01">
                                    <select name="privacy" id="privacy" style="width:262px;">
                                    	  <option value="-1">Select</option>
                                          <option value="friend">My friends only</option>
                                          <option value="everyone">Every One</option>
                                    </select>
                 
                                   
                                    <span id="err_privacy" class="error-message"></span> 
                                    </div> 
                                    <div class="clr"></div><?php */?>
                                    
                                    <div class="lable01">Description:</div>  
                                    <div class="field01">
                                    <textarea name="txt_desc"  id="txt_desc" cols="" rows="" style="height:125px;" maxlength="500"></textarea>
                                    <span id="err_desc" class="error-message"></span> 
                                    <span style="font-size: 11px;font-style: italic;line-height: 13px;">(Max 500 characters.)</span> 
                                    </div> 
                                    <div class="clr"></div>
                                    
                                     <div class="lable01">Cover Image:</div> 
                                     <div class="field01">
                                     <input name="s_photo" id="s_photo" type="file" />
                                     <span id="err_photo" class="error-message"></span>  
                                     </div>
                                     <div class="clr"></div>
                                    
                                    <div class="lable01-privacy">Privacy</div> 
                                    
                                    <div class="lable01"><?php echo get_privacy_setting('audio');?>:</div>
                                    <div class="field01">
                                     <a href="<?=base_url()?>/privacy-settings.html" class="change-btn">  [Change]</a>
                                    </div> 
                                    <div class="clr"></div>
                                     
                                    <div class="lable01">&nbsp;</div>  
                                    <div class="field01"> 
                                    <input name="photo_album_btn"  id="photo_album_btn" type="submit" value="Create"  class="btn"/></div> 
                                    <div class="clr"></div>
                          	</div>
                            </form>
                        </div>
                        <!-- /left container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<?php include(APPPATH."views/logged/audios/blocks/upload_audios_popup_manage.phtml");?>

