<?php //pr($arr_photos)?>

<?php //pr($arr_photos);
	if(count($arr_photos)>0){
?>
<script type="text/javascript">
<!--
function pausePlayers(playing_id) { 
  
   <?php
	foreach($arr_photos as $val):
	?>
		
		   if(<?=$val['id']?> != playing_id) { jwplayer("myElement_"+<?=$val['id']?>).pause(true); }
	<?php
 		endforeach;
	?>
};

$(function(){
<?php
	foreach($arr_photos as $val):
		//$ID = 'm1'. $val['id'];
		$audio_filename = base_url()."uploads/user_audio_files/".$val['s_audio_file_name'];
?>
	
	 jwplayer("myElement_<?=$val['id']?>").setup({
        file: "<?=$audio_filename?>",
        image: "<?=$audio_filename?>",
		height: 30,

        events:{
		  onPlay: function() {
		    	pausePlayers(<?=$val['id']?>);
			 //jwplayer('container3').stop();
		  }
		}

     });
<?php
	endforeach;
?>
});
//-->
</script>
	
<?php		
		//pr($arr_photos);
		foreach($arr_photos as $val):
				
		 $audio_filename = base_url()."uploads/user_audio_files/".$val['s_audio_file_name'];
?>

        <div class="shade_box_01">
         <div class="checkbox-div"><?php /*?><input name="chk_photo<?=$val['id']?>" id="chk_photo<?=$val['id']?>" type="checkbox" value="<?=$val['id']?>" class="check-box" /><?php */?></div>
        <div class="nw-wal-aud"> 
        <p class="blue_bold12"><img src="images/icons/audio_icon.png" alt="" /> <a href="javascript:void(0);"><?=my_substr($val['s_title'], 35);?></a></p>
           <p class="light_blue12"><?=$val['s_artist']?> , <?=$val['genre']?> </p>
           <p class="date-time" >Uploaded on : <?=getShortDate($val['dt_created_on'], 5)?></p>
           <p ><?=my_substr($val['s_desc'] , 160)?></p>
           
           <div class="audio-player">
                <div id="myElement_<?=$val['id']?>">Loading the player...</div>
           </div>
           	
        </div>
        
        
        <div class="light_heading"> 
             <div class="left"><a href="javascript:void(0);" class="comments_div<?=$val['id']?>" onclick="return show_comments(<?=$val['id']?>)" >Comments (<?=$val['total_comments']?>)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);"   onclick="return show_people_liked(<?=$val['id']?>); " class="liked_by_<?=$val['id']?>">Liked by (<?=count_photo_like_link($val['id'],'audio')?>)</a></div>
             
        <?php if((show_photo_like_link($val['id'],'audio') == TRUE) ) { 
		?>
                <div class="right"><a href="javascript:void(0);"  >Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$val['id']?>" onClick="windowLike(<?=$val['id']?>,'Like')">Like</a>  </div>                
       <?php } 
	   		else{ 
	   ?>
         		<div class="right"><a href="javascript:void(0);"  >Comment</a> &nbsp; |   &nbsp; <a href="javascript:void(0);" id="like_count_<?=$val['id']?>" >Like</a> </div>
          
       <?php }?>
             
              
         </div> 
			
          <!-- slide section start -->
            <div class="new-wl">
            <!--comment section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid">
                      <div class="heading">
                            <div class="left">
                                  <h4><img class="cmnt" src="images/icons/cmnt2.png" height="20px" width="20px" alt="" /> <span class="comments_div<?=$val['id']?>">Comments (<?=$val['total_comments']?>)</span> </h4>
                                  <img class="wal-minus" alt="" src="images/minus-white.png" />
                            </div>
                       </div>
                       <DIV id="audio_comment_div<?=$val['id']?>"></DIV>
                    </div>
                </div>
            <!--comment section end-->	
            <!--like by section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid">
                      <div class="heading">
                            <div class="left">
                                  <h4><img alt="" src="images/heart2.png" height="19px" width="20px" class="cmnt" /> <span class="liked_by_<?=$val['id']?>">Liked by (<?=count_photo_like_link($val['id'],'audio')?>)</span> </h4>
                                   <img class="wal-minus" alt="" src="images/minus-white.png" />
                            </div>
                      </div>
                      
                        <div class="shade_box_white" id="audio_like_div<?=$val['id']?>">
                        </div>
                   </div>
            	</div>
            <!--like by section end-->
                
            </div>
            <div class="new-wl-right">
                <!--comment section start-->
                <div  class="comments-number content-width" >
                  <div class="comments-number-mid comment-box-manage">
                      <div class="heading">
                            <div class="left">
                                  <h4><img alt="" src="images/no.png" class="cmnt" />  Comment  </h4>
                                  <img class="wal-minus" alt="" src="images/minus-white.png" />
                            </div>
                      </div>
                      
                      <div class="txt_content01 comments-number-content"> 
                      <textarea class="wal-comment-textarea" id="feed_comment_box_<?=$val['id']?>"  cols="" rows=""></textarea>
                      <input type="button" value="Post" class="yellow-btn" id="post_comment_button" onclick="post_comment(<?=$val['id']?>)" />
                      <br class="clr" />
                      </div>
                </div>
                </div>
                <!--comment section end-->	
            </div>
          <!-- slide section end --> 
				 
        </div>
        <script type="text/javascript">
			$(function(){
				$('.left a').click(function(){
				var index=$(this).index();
				
				$('.new-wl > .comments-number').css('display','none');
				$('.new-wl-right > .comments-number').css('display','none');
				$(this).parent().parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
				})
				
				$('.right a').click(function(){
				var index=$(this).index();
				$('.new-wl > .comments-number').css('display','none');
				$('.new-wl-right > .comments-number').css('display','none');
				$(this).parent().parent().next().next('.new-wl-right').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
				})
				
				$('.wal-minus').click(function(){
					$(this).parents('.comments-number').slideUp('fast');
				
				})
			})
		</script>
     
<?php                                
		endforeach;?>
		        
<?php	}
	
?>
<input type="hidden" id="current_page" name="current_page" value="<?=$current_page?>"  />

<?php if($page_links){ ?>
<div class="pagination">
<div class="left">Viewing Page <?=$current_loaded_page_no?> of <?=$total_pages?> </div>
<div class="right">
       <ul class="small-paging">
        <?=$page_links?> 
        </ul>
</div>
</div>
<?php } ?>





  