<script type="text/javascript">
$(function(){
		
	$('.left a').click(function(){
	var index=$(this).index();
	
	$('.new-wl > .comments-number').css('display','none');
	$('.new-wl-right > .comments-number').css('display','none');
	$(this).parent().parent().next('.new-wl').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	})
	
	$('.right a').click(function(){
	var index=$(this).index();
	$('.new-wl > .comments-number').css('display','none');
	$('.new-wl-right > .comments-number').css('display','none');
	$(this).parent().parent().next().next('.new-wl-right').children('.comments-number').filter(':eq('+ index +')').slideDown('slow');
	})
	
	$('.wal-minus').click(function(){
		$(this).parents('.comments-number').slideUp('fast');
	})
});
			
var ajax_req_feeds = null;
function show_more_album_comments(page) {
	
	var current_media_id = $('#current_media_id').val();
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/my_audio_album_details/albums_comments_ajax_pagination/'+current_media_id+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#comment_result_div').append(data.html);
				$('#show_more_feeds_link').attr('page_value', data.current_page);
			}
			else {
				$('#comment_result_div').append('<div class="view_more" style="text-align: center; background-color:#F2F2F2;"><p class="blue_bold12" style="font-size:14px;">No more comments.</p></div>');
				$('#show_more_feeds_div').hide();
			}

		}	// end of success function...
	});
}


var ajax_req_tracks = null;
function show_more_tracks(page) {
	
	var current_media_id = $('#current_media_id').val();
	if(ajax_req_tracks!=null) {
		ajax_req_tracks.abort();
	}
	showUILoader_nodialog(); 
	ajax_req_tracks = $.ajax({
		type: 'get',
		url: base_url+'logged/my_audio_album_details/audio_tracks_ajax_pagination/'+current_media_id+'/'+page,
		dataType: 'json',

		success: function (data, status) {

			hideUILoader_nodialog();
			if(data.html!='') {
				$('#audio_tracks_html').append(data.html);
				$('#show_more_track_link').attr('page_value', data.current_page);
			}
			else {
				$('#audio_tracks_html').append('<div class="view_more" style="text-align: center; background-color:#ECECEC;"><p class="blue_bold12" style="font-size:14px;">No more Audio.</p></div>');
				$('#show_more_track_div').hide();
			}
			
		}	// end of success function...
	});
}
</script>
<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <?php /*?><div id="top_corner">&nbsp;</div><?php */?>
            <div id="mid_content">
                  <!-- latest news -->
                  <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                        <!-- left container -->
                        <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- /left container -->
                        <!-- mid container -->
                        <div id="mid_container">
                        <div class="page_heading">
                                <div class="left"><img src="images/icons/audio.png" alt="" /> Audios</div>
                              
                            </div>
                        	 <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                                  <ul>
                                    <li><a href="my-audios.html"><span>My Audios</span></a> </li>
                                    <li><a href="manage-my-audio.html"><span>Manage My Audio Albums</span></a> </li>
                                    <li><a href="create-audio-album.html"><span>Create Audio Album</span></a></li>
                                    <li><a href="javascript:void(0);" onclick="return show_dialog('upload_audio')"><span>Upload Audio</span></a></li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                              <!--/sub page links -->
                        
                        	<div class="page_heading">
                            	<div class="left"><img src="images/icons/audio.png" alt="" /> <?=$arr_albums['s_name']?></div>
                            </div>
                             
                            <div class="arrow_btm"></div>
                            
                            <div class="shade_box_01">
                            	<div class="new-albumtxt-testing">
                                <?php //pr($arr_albums);
								 $IMG = base_url()."uploads/user_audio_album_photos/".getThumbName($arr_albums['s_image_name'],'thumb'); ?> 
                                   <div class="new-alm-thmb">
                                        <div title="Album" style="background:url(<?=$IMG?>) no-repeat 50% 50%; width:122px; height:82px; cursor:pointer; ">
                                        </div>
                                    </div>
                            	
                                   <div class="album-info-section">
                                   <p class="date-time">Created On: <?=getShortDate($arr_albums['dt_created_on'],5)?></p>
                                   <p><?=$arr_albums['s_desc']?></p>
                                    
                                    <div class="album-info">
                                        <p class="light_blue12">Total Tracks: <?=$arr_albums['total_audio']?></p>
                                    </div>
                                  </div>
                                </div>
                                
                                <!--like block start -->
                                <div class="clr"></div>
								
								<div class="light_heading">
									<div class="left">
										<a href="javascript:void(0);" onclick="return show_album_people_liked(<?=$arr_albums['id']?>); " class="album_liked_by_<?=$arr_albums['id']?>" >Liked by (<?=count_photo_like_link($arr_albums['id'],'audio_album')?>)</a>
									</div>
									<div class="right">
									<?php if((show_photo_like_link($arr_albums['id'],'audio_album') == TRUE) ) { 
                                     ?>
                                          <a href="javascript:void(0);" id="like_count_<?=$arr_albums['id']?>" onClick="album_windowLike(<?=$arr_albums['id']?>,'Like')" >Like</a>             
                                    <?php } 
                                      else{ 
                                     ?>
                                          <a href="javascript:void(0);" id="like_count_<?=$arr_albums['id']?>" >Like</a>
                                    <?php }?>
									</div>
								</div>
								
								<div class="new-wl">
                                    <!--like by section start-->
                                        <div  class="comments-number content-width" >
                                          <div class="comments-number-mid">
                                              <div class="heading">
                                                    <div class="left">
                                                          <h4><img alt="" src="images/heart2.png" height="19" width="20" class="heart2" /> <span class="album_liked_by_<?=$arr_albums['id']?>">Liked by (<?=count_photo_like_link($arr_albums['id'],'audio_album')?>)</span> </h4>
                                                           <img class="wal-minus" alt="" src="images/minus-white.png" width="13" height="10"/>
                                                    </div>
                                              </div>
                                                <div class="shade_box_white" id="audio_album_like_div<?=$arr_albums['id']?>">
                                                </div>
                                           </div>
                                        </div>
                                    <!--like by section end-->
            					</div>
							</div>
                            
                            <div class="shade_box_01" style="margin-top:10px;">	
                                <!--like block end -->
                                 <DIV id="audio_tracks_html">
                                 	<?=$audio_track_content?>
                                 </DIV>
                                 
                                   <?php if($no_of_tracks == 0): ?>
                                    	<div id="no_audio_div" class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No comments.</p></div>
                                     <?php endif; ?>

                                    
                                    <?php  if($no_of_tracks > 2): ?>
                                    <div class="view_more" id="show_more_track_div" style="background-color:#ECECEC;"><a href="javascript:void(0);" id="show_more_track_link" page_value="<?=$tracks_current_page_1?>" onclick="show_more_tracks($(this).attr('page_value'))">[view more] </a> </div>
                                    <?php endif; ?>
                                
                             </div>
                            
                              <div class="div_content aud-wall-comment">
                                    <div class="postheading">
                                          <div class="left">
                                                <h4>Post Comment</h4>
                                          </div>
                                    </div>
                                    <form method="post" class="wall-comment-form">
                                        
                                        	<!--text div start -->
                                            <div class="">
                                          		<textarea   id="feed_album_comment_box<?=$arr_albums['id']?>" name="" class="aud-wall-comment-textarea"></textarea>
            									<input type="hidden" name="i_audio_album_id" id="i_audio_album_id" value="<?=$arr_albums['id']?>"/>
                                        	</div>
                                            <!--text div end -->
                                       <input name="" id="post_comment_button" type="button" value="Post"  class="wall-comment-submit-nw " onclick="post_album_comment();"/>
                                    </form>
                              </div>
                              
                               <div class="div_content">
                                    <div class="heading">
                                          <div class="left">
                                                <h4><img class="icon-img" src="images/icons/cmmnt.png" alt="" /> View Comments</h4>
                                          </div>
                                    </div>
                                    <div id="comment_result_div"><?=$comments_list_html?></div>
                                    <?php if($no_of_albums_comments == 0): ?>
                                    	<div id="no_comments_div" class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No comments.</p></div>
                                     <?php endif; ?>

                                    
                                    <?php  if($no_of_albums_comments > 2): ?>
                                    <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?=$comment_current_page_1?>" onclick="show_more_album_comments($(this).attr('page_value'))">[view more] </a> </div>
                                    <?php endif; ?>
                                    
                              </div>
                              
                              <input type="hidden" name="current_media_id" id="current_media_id" value="<?=$i_media_id?>" />
                            
                             
                            
                            
                            
                        </div>
                        <!-- /mid container -->
                         <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<?php include(APPPATH."views/logged/audios/blocks/upload_audios_popup_album_detail.phtml");?>
<?php include(APPPATH."views/logged/audios/comments/my_audios_post_comment_lightbox.phtml");?>

