
<?php include(APPPATH."views/layouts/logged_header.phtml");?>
<!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
<!-- /NAVIGATION SECTION -->
<div class="clr"></div>
<!-- CONTENT SECTION -->
<div id="content_section">
      <div id="container">
            <div id="top_corner">&nbsp;</div>
            <div id="mid_content">
                  <!-- latest news -->
                 <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
                  <!-- /latest news -->
                  <div class="clr"></div>
                  <!-- main container -->
                  <div id="main_container">
                      <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                        <!-- left container -->
                        <div id="mid_container">
                        <div class="page_heading">
                                <div class="left"><img src="images/icons/audio.png" alt="" /> Audios</div>
                              
                            </div>
                         <!--sub page links -->
                              <div class="link-div" style="margin-top:0px;">
                                  <ul>
                                    <li><a href="my-audios.html"><span>My Audios</span></a> </li>
                                    <li><a href="manage-my-audio.html"><span>Manage My Audio Albums</span></a> </li>
                                    <li><a href="create-audio-album.html"><span>Create Audio Album</span></a></li>
                                    <li><a href="javascript:void(0);" onclick="return show_dialog('upload_audio')"><span>Upload Audio</span></a></li>
                                </ul>
                                <div class="clr"></div>
                              </div>
                              <!--/sub page links -->
                        	<!--<div class="page_heading">
                            	<div class="left"><img src="images/icons/photo.png" alt="" /> <?=$arr_albums['s_name']?></div>
                             </div>-->
                             <div class="arrow_btm"></div>
                                  <div class="section01" style="padding:17px 10px;">
                                  <?php 
                                  
								  $IMG = base_url()."uploads/user_audio_album_photos/".getThumbName($arr_albums['s_image_name'],'thumb'); 
								  $ALBUM_URL = get_audio_album_detail_url($arr_albums['id'], $arr_albums['s_name']);
								  ?>
                                  <div class="photo-div" style="float:left; "><div style="background:url(<?=$IMG?>) no-repeat center;width:122px; height:82px; cursor:pointer; "  title="Album" ></div></div>
                                  <p style=" font-size:12px;margin-left:155px;"><?=$arr_albums['s_desc']?></p></div>
                          	 <div class="page_heading">
                                    <div class="left"><img src="images/icons/organize.png" alt="" /> Organize Audios</div>
                                    <div class="right">
                                       
                                        <input type="button" class="upload_btn"  value="Upload Audio" onclick="return show_dialog('upload_audio')"/>
                                    </div>
                              </div>
                              <div class="arrow_btm"></div>
                              <DIV ID ="album_div">
                              <?=$result_album_content?>
                              </DIV>
                              
                              <?php
                              if($total == 0) :
                              ?>
                              <div class="section01" style="padding-top:5px;" id="no_audio_box"><div  class="shade_norecords" style="width:260px;"><p class="blue_bold12">No Audios.</p></div></div>
                              <?php
                              endif;
                              ?>
                              
                              
                              <?php 
                              //echo "no_of result : ".$no_of_result;
                              if($no_of_result > $pagination_per_page): ?>
                                    
                                    <div class="view_more" id="show_more_feeds_div"><a href="javascript:void(0);" id="show_more_feeds_link" page_value="<?=$current_page?>" onclick="show_more_feeds($(this).attr('page_value'))">[view more] </a> </div>
                              <?php endif; ?>
                              
                              <input type="hidden" id="audio_media_id" name="audio_media_id" value="<?=$current_album_id?>" />
                              
                              
                        </div>
                          
                        <!-- /left container -->
                        <!-- right container -->
                        <?php include(APPPATH."views/layouts/rightbar.phtml");?>
                        <!-- /right container -->
                  </div>
                  <!-- /main container -->
                  <div class="clr"></div>
            </div>
            <div id="bot_corner">&nbsp;</div>
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH."views/layouts/footer.phtml");?>
<!-- /FOOTER SECTION -->
<?php include(APPPATH."views/logged/blocks/common_popup.phtml");?>
<?php include(APPPATH."views/logged/audios/blocks/upload_audios_popup_no_redirect.phtml");?>
<?php include(APPPATH."views/logged/audios/blocks/edit_audio_popup-no-redirect.phtml");?>

<?php /*?>delete confirm box for wall post <?php */?>
<div class="lightbox delete-photo" style="width:auto;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png" alt="" width="24" height="24" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Audio</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">Do you really want to delete this Audio?</p>
               </div>
               <form method="post" enctype="multipart/form-data">
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                  <input type="hidden" name="i_album_id" id="i_album_id" value="" />
                 <input name="" type="button" value="Yes" class="popup-yes" onClick="delete_()"/>
                    <input name="" type="button" value="No" class="popup-no" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<script type="text/javascript">

var ajax_req_feeds = null;
function show_more_feeds(page) {
	
	var i_media_id = $('#audio_media_id').val();
	if(ajax_req_feeds!=null) {
		ajax_req_feeds.abort();
	}
	showUILoader_nodialog();
	ajax_req_feeds = $.ajax({
		type: 'get',
		url: base_url+'logged/organize_audio/album_wise_audio_ajax_pagination/'+i_media_id+'/'+page,
		dataType: 'json',

		success: function (data, status) {
		//	$('div[id ^= "mp_m1"]').css('display','none');
			hideUILoader_nodialog();
			if(data.html!='') {
				$('#album_div').append((data.html));
				$('#show_more_feeds_link').attr('page_value', data.current_page);
			}
			else {
				$('#album_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No more audios.</p></div>');
				$('#show_more_feeds_div').hide();
			}
			if(data.view_more==false)
            {
                $('#album_div').append('<div class="view_more" style="text-align: center;"><p class="blue_bold12" style="font-size:14px;">No More Audio.</p></div>');
                $('#show_more_feeds_div').hide();
            }
			
			
		}	// end of success function...
	});
}
</script>