<?php 
$count= count($result['skill_arr']);

$skill_no=0; 
if($count==0)
	$count=2;
	
	for($i=0;$i<$count;$i++)    :
	
	
	$skill_no++;
?>

<tr>
  <td align="left" valign="top" height="25" width="180" class="label">Skill <?php echo $skill_no;?></td>
  <td align="left" valign="top" width="20" class="label">:</td>
  <td align="left" valign="top" ><?php echo $result['skill_arr'][$i]['s_name'];?></td>
</tr>

<?php
endfor;
?>

<tr>
  <td align="left" valign="bottom" height="40" colspan="2">&nbsp;</td>
  <td align="left" valign="bottom"><a href="javascript:void(0);" class="edit-btn-other" onclick="showSkillEdit(this)">Edit</a></td>
</tr>