
                                   <div id="2">
                                     <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/info.png" alt=" " />  Basic Information</h4> </div>
                                        <div class="right"><img src="images/icons/edit.png" alt=" " />  <a onclick="showDiv('2')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
                                     </div>
                                      
                                   <div id="basic_info_div" class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Languages I Speak:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_languages']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">About Me:</div>  
                                        <div class="field01"><?=nl2br($arr_profile_info['s_about_me'])?></div> 
                                        <div class="clr"></div>
                                        
                                        <p class="lable01" style="font-weight: bold; font-size: 12px;">Church Details</p>
                                        <div class="clr"></div>
                                        <div class="lable01">Church Name:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_name']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Location:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_location'] ?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Phone:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_church_phone']?></div> 
                                        <div class="clr"></div>
                                        <div class="lable01">Denomination:</div>  
                                        <div class="field01"><?=$arr_profile_info['s_name']?></div> 
                                        <div class="clr"></div>
                                        <!--<div class="lable01">Profile Photo:</div>  
                                        <div class="field01"><a href="javascript:void(0);" onclick="showDiv('2')" class="blue_link"><strong>[change]</strong></a></div> 
                                        <div class="clr"></div>-->
                                     </div>
                                  
                                     
                                   </div>
                                   <div id="jason2" style="display:none;"> 
                                   <div class="heading01"> 
                                         <div class="left"><h4><img src="<?php echo base_url();?>images/icons/info.png" alt=" " />  Basic Information</h4> </div>
                                     </div>
                                       <!--FORM TO MODIFY basic Information-->
                                     <form id="frmManageBasicProfile"  method="post" action="modify-my-profile-basic-info-ajax" onsubmit="return modify_my_basic_profile_ajax()" enctype="multipart/form-data">
                                    <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
                                        <div class="lable01">Languages I Speak:</div>  
                                        <div class="field01">
                                        <?php /*<input name="txt_lang" id="txt_lang" type="text" value="<?=isset($arr_profile_info["s_languages"])? $arr_profile_info["s_languages"]: '' ?>" />*/?>
										<select name="txt_lang" id="txt_lang" style="width:212px;">
                                          	<option value="">---</option>
											<?php
										if($arr_profile_info['s_languages'] == '')
										{
										?>
											<?php echo makeNetpalLanguage();
											}
											else{
											echo makeNetpalLanguage($arr_profile_info['s_languages']);
											
											}?>
                                          </select>
                                        <?php echo form_error('txt_lang'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <div class="lable01">About Me:</div>  
                                        <div class="field01">
                                        <textarea style="height: 60px;" rows="" cols="" name="txt_about" id="txt_about"><?=isset($arr_profile_info["s_about_me"])? get_unformatted_string_edit(br2nl($arr_profile_info["s_about_me"])): '' ?></textarea>
                                        <?php echo form_error('txt_about'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <p class="lable01" style="font-weight: bold; font-size: 12px;">Church Details</p>
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Name:</div>  
                                        <div class="field01">
                                        <input name="txt_cname" id="txt_cname" type="text" value="<?=isset($arr_profile_info["s_church_name"])? $arr_profile_info["s_church_name"]: '' ?>" />
                                        <?php echo form_error('txt_cname'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Address:</div>  
                                        <div class="field01">
                                         <input name="txt_caddress" id="txt_caddress" type="text" value="<?=isset($arr_profile_info["s_church_address"])? $arr_profile_info["s_church_address"]: '' ?>" />
                                        
                                        <?php echo form_error('txt_caddress'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                       <?php /*?> <div class="lable01">City:</div>  
                                        <div class="field01">
                                        <input name="txt_ccity" id="txt_ccity" type="text" value="<?=isset($arr_profile_info["s_church_city"])? $arr_profile_info["s_church_city"]: '' ?>" />
                                        <?php echo form_error('txt_ccity'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">State:</div>  
                                        <div class="field01">
                                        <input name="txt_cstate"  id="txt_cstate" type="text" value="<?=isset($arr_profile_info["s_church_state"])? $arr_profile_info["s_church_state"]: '' ?>" />
                                        <?php echo form_error('txt_cstate'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Church Country:</div>  
                                        <div class="field01">
                                        
                                        <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;">
                                            <option value="-1">---</option>
                                            <?=makeOptionCountry('',encrypt($arr_profile_info["i_church_country_id"]));?>

                                        </select>
                                        <?php echo form_error('txt_ccountry'); ?>
                                        </div> 
                                        <div class="clr"></div> <?php */?>
                                        
                                        <div class="lable01">Country:</div>  
                                        <div class="field01">
                                        
                                        <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;" onchange="showChurchState(this.value);">
                                            <option value="-1">---</option>
                                            <?=makeOptionCountryNew('',encrypt($arr_profile_info["i_church_country_id"]));?>

                                        </select>
                                        <?php echo form_error('txt_ccountry'); ?>
             
                                        </div> 
                                        <div class="clr"></div> 
                                        
                                        <div class="lable01">State:</div>  
                                        <div class="field01">
                                        <select name="txt_cstate" id="txt_cstate" onchange="showChurchCity(this.value)">
                                        	<option value="-1">---</option>
											<?=$cstate;?>
                                        </select>
                                        
                                        <?php echo form_error('txt_cstate'); ?>
                                         <div class="error-message" id="err_cstate"></div>
                                        </div> 
										<div class="clr"></div> 
                                        <div class="lable01">City:</div>  
                                        <div class="field01">
                                        <select name="txt_ccity" id="txt_ccity">
                                        	<option value="-1">---</option>
											<?=$ccity;?>
                                        </select>
                                        
                                        <?php echo form_error('txt_ccity'); ?>
                                         <div class="error-message" id="err_ccity"></div>
                                         </div>
                                       
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Postcode:</div>  
                                        <div class="field01">
                                        <input name="txt_cpostcode" id="txt_cpostcode" type="text" value="<?=isset($arr_profile_info["s_church_postcode"])? $arr_profile_info["s_church_postcode"]: '' ?>" />
                                        <?php echo form_error('txt_cpostcode'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Phone:</div>  
                                        <div class="field01">
                                        <input name="txt_cphone" id="txt_cphone" type="text"  value="<?=isset($arr_profile_info["s_church_phone"])? $arr_profile_info["s_church_phone"]: '' ?>"/>
                                        <?php echo form_error('txt_cphone'); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        
                                        <div class="lable01">Denomination:</div>  
                                        <div class="field01">
                                         <select name="txt_denomination" id="txt_denomination" style="width:260px;">
                                             <option value="<?=encrypt(0)?>">---</option>
                                             <?=makeOptionDenomination(encrypt($arr_profile_info['i_id_denomination']));?>
                                        </select>
                     
                                        <script type="text/javascript">
                                            $(document).ready(function(arg) {
                                                //$("#txt_denomination").msDropDown();
                                                //$("#txt_denomination").hide();
                                            })
                                        </script>
                                        <?php echo form_error('txt_denomination'.'===='); ?>
                                        </div> 
                                        <div class="clr"></div>
                                        <!--<div class="lable01">Profile Photo:</div>  
                                        <div class="field01"><input name="" type="file" size="25" /></div> 
                                        <div class="clr"></div>-->
                                         <div class="lable01">&nbsp;</div>  
                                        <div class="field01"> 
                                          <input type="hidden" name="is_basic_submitted" id="is_basic_submitted" value="Y" />
                                          <input name="" type="submit" value="Save"  class="btn" />
                                          <input name="" type="button" value="Cancel"  class="btn" onclick="closeBasicInfoDiv()"/>
                                        </div> 
                                        <div class="clr"></div>
                                     </div>
                                     </form>
                                      <!--FORM TO MODIFY basic Information-->
                                  </div>
