
<div id="1">
    <div class="heading01"> 
        <div class="left"><h4><img src="<?php echo base_url(); ?>images/icons/profile.png" alt=" " width="25" height="26" />  Basic Information</h4> </div>
        <div class="right"><img src="<?php echo base_url(); ?>images/icons/edit.png" alt=" " width="16" height="16" />  <a onclick="showDiv('1')" href="javascript:void(0);" class="white-link"><strong>Edit</strong></a></div>
    </div>
    <div id="profile_info_div" class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
        <div class="lable01">Title:</div>  
        <div class="field01"><?= $arr_profile_info['e_title'] ?></div> 
        <div class="clr"></div>
        <div class="lable01">First Name:</div>  
        <div class="field01"><?= $arr_profile_info['s_first_name'] ?> </div> 
        <div class="clr"></div>
        <div class="lable01">Last Name:</div>  
        <div class="field01"><?= $arr_profile_info['s_last_name'] ?></div> 
        <div class="clr"></div>
        <div class="lable01">Country:</div>  
        <div class="field01"><?= get_countryname($arr_profile_info['i_country_id']) ?></div> 
        <div class="clr"></div>
        <div class="lable01">State:</div>  
        <div class="field01"><?= get_statename($arr_profile_info['i_state_id']) ?></div> 
        <div class="clr"></div>
        <div class="lable01">City:</div>  
        <div class="field01"><?= get_cityname($arr_profile_info['i_city_id']) ?></div> 
        <div class="clr"></div>
        <div class="lable01">Gender:</div>  
        <div class="field01"><?= $arr_profile_info['s_gender'] ?></div> 
        <div class="clr"></div>
        <div class="lable01">Timezone:</div>  
        <div class="field01">
		<?php if($arr_profile_info['s_timezone_text'] == '')
			{
			echo get_time_zone_by_value($arr_profile_info['s_time']);
			}							 
			else
			{
			echo $arr_profile_info['s_timezone_text'];
			}
?>
		</div> 
        <div class="clr"></div>
        <div class="lable01">Date of Birth:</div>  
        <div class="field01">
            <?php
            //echo $arr_profile_info['dt_dob'] ;
            if ($arr_profile_info['dt_dob'] == '0000-00-00') {
                echo "";
            } else {
                echo getShortDate($arr_profile_info['dt_dob'], '1');
            }
            ?>
        </div> 
        <div class="clr"></div>
        <? /* <div class="lable01">Profile Photo:</div>  
          <div class="field01"><a href="javascript:void(0);" class="blue_link"  onclick="showDiv('1')"><strong>[change]</strong></a></div>
          <div class="clr"></div>
         */ ?>
        <div class="lable01">Want to be Prayer Partner:</div>  
        <div class="field01"><?= $arr_profile_info['s_want_prayer_partner'] ?></div> 
        <div class="clr"></div>
        <div class="lable01">Want to be Net Pal:</div>  
        <div class="field01"><?= $arr_profile_info['s_want_net_pal'] ?></div> 
        <div class="clr"></div>
        <div class="lable01">My Website:</div>  
        <div class="field01"><a  href="javascript:void(0);" class="blue_link"><?= $arr_profile_info['s_website'] ?></a> </div> 
        <div class="clr"></div>
        <div class="lable01">My Profile URL:</div>  
        <div class="field01"><a  href="javascript:void(0);" class="blue_link">www.xtiannetwork.com/<?= $arr_profile_info['s_profile_url_suffix'] ?></a> </div> 
        <div class="clr"></div>
        <!----------------------->
        <div id="basic_info_div" class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
            <div class="lable01">Languages I Speak:</div>  
            <div class="field01"><?= $arr_profile_info['s_languages'] ?></div> 
            <div class="clr"></div>
            <div class="lable01">About Me:</div>  
            <div class="field01"><?= nl2br($arr_profile_info['s_about_me']) ?></div> 
            <div class="clr"></div>

            <p class="lable01" style="font-weight: bold; font-size: 12px;">Church Details</p>
            <div class="clr"></div>
            <div class="lable01">Church Name:</div>  
            <div class="field01"><?= $arr_profile_info['s_church_name'] ?></div> 
            <div class="clr"></div>
            <div class="lable01">Location:</div>  
            <div class="field01"><?= $arr_profile_info['s_church_location'] ?></div> 
            <div class="clr"></div>
            <div class="lable01">Phone:</div>  
            <div class="field01"><?= $arr_profile_info['s_church_phone'] ?></div> 
            <div class="clr"></div>
            <div class="lable01">Denomination:</div>  
            <div class="field01"><?= $arr_profile_info['s_name'] ?></div> 
            <div class="clr"></div>
            <!--<div class="lable01">Profile Photo:</div>  
            <div class="field01"><a href="javascript:void(0);" onclick="showDiv('2')" class="blue_link"><strong>[change]</strong></a></div> 
            <div class="clr"></div>-->
            <!--                                     </div>-->


        </div>
        <!----------------------------------->

    </div>
</div>
<div id="jason1" style="display:none;"> 
    <div class="heading01"> 
        <div class="left"><h4><img src="<?php echo base_url(); ?>images/icons/profile.png" alt=" " width="25" height="26" />  Basic Information</h4> </div>
    </div>
    <!--FORM TO MODIFY Personal Information-->
    <form id="frmManageProfile" method="post" action="modify-my-profile-personal-info-ajax" onsubmit="return modify_my_profile_ajax()" enctype="multipart/form-data">
        <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">

            <div class="lable01">Title:</div>  
            <div class="field01">
                <select name="txt_title" id="txt_title" style="width:60px;">
                    <option value="-1" >---</option>
                    <option value="Mr" <?php echo $selected = ($arr_profile_info["e_title"] == 'Mr') ? 'selected' : '' ?>>Mr.</option>
                    <option value="Mrs" <?php echo $selected = ($arr_profile_info["e_title"] == 'Mrs') ? 'selected' : '' ?>>Mrs.</option>
                    <option value="Ms" <?php echo $selected = ($arr_profile_info["e_title"] == 'Ms') ? 'selected' : '' ?>>Ms.</option>
                </select>

                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        //$("#txt_title").msDropDown();
                        //$("#txt_title").hide();
                    })
                </script>
                <?php echo form_error('txt_title'); ?>
                <div class="error-message" id="err_title"></div>
            </div> 
            <div class="clr"></div>

            <div class="lable01">First Name:</div>  
            <div class="field01">
                <input name="txt_fname" id="txt_fname" type="text" value="<?= isset($arr_profile_info["s_first_name"]) ? $arr_profile_info["s_first_name"] : '' ?>" />
                <?php /* ?><?php echo form_error('txt_fname'); ?><?php */ ?>
                <div class="error-message" id="err_fname"></div>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Last Name:</div>  
            <div class="field01">
                <input name="txt_lname" id="txt_lname" type="text" value="<?= isset($arr_profile_info["s_last_name"]) ? $arr_profile_info["s_last_name"] : '' ?>" />
                <?php echo form_error('txt_lname'); ?>
                <div class="error-message" id="err_lname"></div>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Country:</div>  
            <div class="field01">

                <select name="txt_country" id="txt_country" style="width:150px; margin-bottom:6px;" onchange="showState(this.value);">
                    <option value="-1">---</option>
                    <?= makeOptionCountryNew('', encrypt($arr_profile_info["i_country_id"])); ?>
                </select>
                <?php echo form_error('txt_country'); ?>
                <div class="error-message" id="err_country"></div>
            </div> 
            <div class="clr"></div>
            <div class="lable01">State:</div>  
            <div class="field01">
                <select name="txt_state" id="txt_state" onchange="showCity(this.value)">
                    <option value="-1">---</option>
                    <?= $state; ?>
                </select>

                <?php echo form_error('txt_state'); ?>
                <div class="error-message" id="err_state"></div>
            </div> 
            <div class="clr"></div>
            <div class="lable01">City:</div>  
            <div class="field01">
                <select name="txt_city" id="txt_city">
                    <option value="-1">---</option>
                    <?= $city; ?>
                </select>

                <?php echo form_error('txt_city'); ?>
                <div class="error-message" id="err_city"></div>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Gender:</div>  
            <div class="field01">

                <select name="txt_gender" id="txt_gender" style="width: 70px;">
                    <option value="-1">---</option>
                    <option value="M" <?php echo $selected = ($arr_profile_info["s_gender"] == 'Male') ? 'Selected' : ''; ?>>Male</option>
                    <option value="F" <?php echo $selected = ($arr_profile_info["s_gender"] == 'Female') ? 'Selected' : ''; ?>>Female</option>
                </select>
                <?php echo form_error('txt_gender'); ?>
                <div class="error-message" id="err_gender"></div>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Date of Birth:</div>  
            <div class="field01">

                <?php
                # getting day-month-yr extracted from db DOB...
                if ($arr_profile_info['dt_dob'] != '0000-00-00') {
                    $DOB_TSTAMP = strtotime($arr_profile_info['dt_dob']);
                    $DOB_DAY = date("j", $DOB_TSTAMP);
                    $DOB_MONTH = date("n", $DOB_TSTAMP);
                    $DOB_YR = date("Y", $DOB_TSTAMP);
                }
                ?>

                <select name="day" id="day"  style="width:50px; margin-right:2px;" autocomplete="off">
                    <option value="">---</option>
                    <?= makeOptionDay($DOB_DAY) ?>

                </select>

                <select name="month" id="month"  style="width:90px; margin-right:2px;">
                    <option value="">---</option>
                    <?= makeOptionMonth($DOB_MONTH) ?>
                </select>

                <select name="year" id="year"  style="width:70px;">
                    <option value="">---</option>
                    <?= makeOptionDobYear($DOB_YR) ?>
                </select> 
                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        //$("#day").msDropDown();
                        //$("#day").hide();
                        //$("#month").msDropDown();
                        //$("#month").hide();
                        //$("#year").msDropDown();
                        //$("#year").hide();
                    })
                </script>
                <?php // if(form_error('day')!='' || form_error('month')!='' ||  form_error('year')!='' ) echo '<div class="error_massage" id="err_msg">Please provide Birth date</div>';  ?>
                <div class="error-message" id="err_dob"></div>

            </div> 
            <div class="clr"></div>

            <div class="lable01">Profile Photo:</div>  
            <div class="field01">

                <?php
                $IMG = base_url() . "uploads/user_profile_image/" . getThumbName($arr_profile_info['s_profile_photo'], 'thumb');
                ?>
                <input name="txt_profile_pic" id="txt_profile_pic" type="file" size="25" />


                <?php echo form_error('profile_pic'); ?>
        <div class="error-message" id="err_profile_pic"></div>
            </div> 
             <!------------------------------------------>
                                <div class="prvimg">
                                    <input type="hidden" value="<?= $arr_profile_info['id'] ?>" id="prf_id">
                                        <div style="background:url(<?= get_profile_image_of_user( 'thumb',$arr_profile_info['s_profile_photo'],$arr_profile_info['e_gender']) ?>) no-repeat center;width:60px; height:60px;" title="member" class="pro_photo4 user_pro_image" ></div>
                                    
                                     <?php
                                      if($arr_profile_info['s_profile_photo'] != ''){
                                     ?>
                                      <a href="javascript:void(0)" onclick="show_dialog('image-delete');">Remove</a><?php } ?>
                                    
                                </div>
                                <!---------------------------------------------->
            
            <div class="clr"></div>
            <div class="lable01">Time Zone:</div>
            <div class="field01">
                <select name="time_zone" id="time_zone" style="width:312px;" onchange="get_time_text()">
                    <option value="-1">Select</option>

                    <?= makeOptionTimezones($arr_profile_info['s_time'],$arr_profile_info['s_timezone_text']) ?>

                </select>

                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        $("#time_zone").msDropDown();
                        $("#time_zone").hide();
                    });
					function  get_time_text()
					{
					var text=$('#time_zone option:selected').text();
					$('#time_text').val(text);
					}
                </script>

                <?php echo form_error('s_time'); ?>
            </div>
				<input type="hidden" value="" id="time_text" name="time_text">
            <div class="clr"></div>
            <div class="lable01">Want to be Prayer Partner:</div>  
            <div class="field01">
                <select name="txt_prayer_ptnr" id="txt_prayer_ptnr" style="width:55px;">
                    <option value="Y" <?php echo $selected = ($arr_profile_info["s_want_prayer_partner"] == 'Yes') ? 'selected' : '' ?>>Yes</option>
                    <option value="N" <?php echo $selected = ($arr_profile_info["s_want_prayer_partner"] == 'No') ? 'selected' : '' ?>>No</option>
                </select>

                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        //$("#txt_prayer_ptnr").msDropDown();
                        //$("#txt_prayer_ptnr").hide();
                    })
                </script>
            </div> 
            <div class="clr"></div>
            <div class="lable01">Want to be Net Pal:</div>  
            <div class="field01">
                <select name="txt_net_pal" id="txt_net_pal" style="width:55px;">
                    <option value="Y" <?php echo $selected = ($arr_profile_info["s_want_net_pal"] == 'Yes') ? 'selected' : '' ?>>Yes</option>
                    <option value="N" <?php echo $selected = ($arr_profile_info["s_want_net_pal"] == 'No') ? 'selected' : '' ?>>No</option>
                </select>

                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        //$("#txt_net_pal").msDropDown();
                        //$("#txt_net_pal").hide();
                    })
                </script></div>
            <div class="clr"></div>

            <div class="lable01">My Website:</div>  
            <div class="field01">
                <input name="txt_website" id="txt_website" type="text"  value="<?= $arr_profile_info['s_website'] ?>"/>
                <?php echo form_error('txt_website'); ?>
                <div class="error-message" id="err_website"></div >
            </div> 
            <div class="clr"></div>

            <div class="lable01">My Profile URL:</div>  
            <div class="field01">www.xtiannetwork.com/ &nbsp;  
                <input name="txt_profile_url" id="txt_profile_url" value="<?= $arr_profile_info['s_profile_url_suffix'] ?>" type="text"  style="width:113px;"/>
                <?php echo form_error('txt_profile_url'); ?>
                <div class="error-message" id="err_profile_url"></div >
            </div> 
            <div class="clr"></div>

            <div class="lable01">&nbsp;</div>  
            <!--                                        <div class="field01"> 
                                                    <input type="hidden" name="is_submitted" id="is_submitted" value="Y" />
                                                    <input name="btn_manage_profile" id="btn_manage_profile" type="submit" value="Save"  class="btn"  /> 
                                                    <input name="" type="button" value="Cancel"  class="btn" onclick="closePersonalInfoDiv()"/>
                                                    </div> -->
            <div class="clr"></div>

        </div>
        <div class="shade_box_01 frm_box shade_box_blue" style="padding-bottom:17px;">
            <div class="lable01">Languages I Speak:</div>  
            <div class="field01">
                <?php /* <input name="txt_lang" id="txt_lang" type="text" value="<?=isset($arr_profile_info["s_languages"])? $arr_profile_info["s_languages"]: '' ?>" /> */ ?>
                <select name="txt_lang" id="txt_lang" style="width:212px;">
                    <option value="">---</option>
                    <?php
                    if ($arr_profile_info['s_languages'] == '') {
                        ?>
                        <?php
                        echo makeNetpalLanguage();
                    } else {
                        echo makeNetpalLanguage($arr_profile_info['s_languages']);
                    }
                    ?>
                </select>
                <?php echo form_error('txt_lang'); ?>
            </div> 
            <div class="clr"></div>
            <div class="lable01">About Me:</div>  
            <div class="field01">
                <textarea style="height: 60px;" rows="" cols="" name="txt_about" id="txt_about"><?= isset($arr_profile_info["s_about_me"]) ? get_unformatted_string_edit(br2nl($arr_profile_info["s_about_me"])) : '' ?></textarea>
                <?php echo form_error('txt_about'); ?>
            </div> 
            <div class="clr"></div>

            <p class="lable01" style="font-weight: bold; font-size: 12px;">Church Details</p>
            <div class="clr"></div>

            <div class="lable01">Church Name:</div>  
            <div class="field01">
                <input name="txt_cname" id="txt_cname" type="text" value="<?= isset($arr_profile_info["s_church_name"]) ? $arr_profile_info["s_church_name"] : '' ?>" />
                <?php echo form_error('txt_cname'); ?>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Address:</div>  
            <div class="field01">
                <input name="txt_caddress" id="txt_caddress" type="text" value="<?= isset($arr_profile_info["s_church_address"]) ? $arr_profile_info["s_church_address"] : '' ?>" />

                <?php echo form_error('txt_caddress'); ?>
            </div> 
            <div class="clr"></div>

            <?php /* ?> <div class="lable01">City:</div>  
              <div class="field01">
              <input name="txt_ccity" id="txt_ccity" type="text" value="<?=isset($arr_profile_info["s_church_city"])? $arr_profile_info["s_church_city"]: '' ?>" />
              <?php echo form_error('txt_ccity'); ?>
              </div>
              <div class="clr"></div>

              <div class="lable01">State:</div>
              <div class="field01">
              <input name="txt_cstate"  id="txt_cstate" type="text" value="<?=isset($arr_profile_info["s_church_state"])? $arr_profile_info["s_church_state"]: '' ?>" />
              <?php echo form_error('txt_cstate'); ?>
              </div>
              <div class="clr"></div>

              <div class="lable01">Church Country:</div>
              <div class="field01">

              <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;">
              <option value="-1">---</option>
              <?=makeOptionCountry('',encrypt($arr_profile_info["i_church_country_id"]));?>

              </select>
              <?php echo form_error('txt_ccountry'); ?>
              </div>
              <div class="clr"></div> <?php */ ?>

            <div class="lable01">Country:</div>  
            <div class="field01">

                <select name="txt_ccountry" id="txt_ccountry" style="width:238px; margin-bottom:6px;" onchange="showChurchState(this.value);">
                    <option value="-1">---</option>
                    <?= makeOptionCountryNew('', encrypt($arr_profile_info["i_church_country_id"])); ?>

                </select>
                <?php echo form_error('txt_ccountry'); ?>

            </div> 
            <div class="clr"></div> 

            <div class="lable01">State:</div>  
            <div class="field01">
                <select name="txt_cstate" id="txt_cstate" onchange="showChurchCity(this.value)">
                    <option value="-1">---</option>

                    <?php echo $cstate; ?>
                </select>

                <?php echo form_error('txt_cstate'); ?>
                <div class="error-message" id="err_cstate"></div>
            </div> 
            <div class="clr"></div> 
            <div class="lable01">City:</div>  
            <div class="field01">
                <select name="txt_ccity" id="txt_ccity">
                    <option value="-1">---</option>
                    <?= $ccity; ?>
                </select>

                <?php echo form_error('txt_ccity'); ?>
                <div class="error-message" id="err_ccity"></div>
            </div>


            <div class="clr"></div>

            <div class="lable01">Postcode:</div>  
            <div class="field01">
                <input name="txt_cpostcode" id="txt_cpostcode" type="text" value="<?= isset($arr_profile_info["s_church_postcode"]) ? $arr_profile_info["s_church_postcode"] : '' ?>" />
                <?php echo form_error('txt_cpostcode'); ?>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Phone:</div>  
            <div class="field01">
                <input name="txt_cphone" id="txt_cphone" type="text"  value="<?= isset($arr_profile_info["s_church_phone"]) ? $arr_profile_info["s_church_phone"] : '' ?>"/>
                <?php echo form_error('txt_cphone'); ?>
            </div> 
            <div class="clr"></div>

            <div class="lable01">Denomination:</div>  
            <div class="field01">
                <select name="txt_denomination" id="txt_denomination" style="width:260px;">
                    <option value="<?= encrypt(0) ?>">---</option>
                    <?= makeOptionDenomination(encrypt($arr_profile_info['i_id_denomination'])); ?>
                </select>

                <script type="text/javascript">
                    $(document).ready(function(arg) {
                        //$("#txt_denomination").msDropDown();
                        //$("#txt_denomination").hide();
                    })
                </script>
                <?php echo form_error('txt_denomination' . '===='); ?>
            </div> 
            <div class="clr"></div>
            <!--<div class="lable01">Profile Photo:</div>  
            <div class="field01"><input name="" type="file" size="25" /></div> 
            <div class="clr"></div>-->
            <div class="lable01">&nbsp;</div>  
            <div class="field01"> 
                <input type="hidden" name="is_submitted" id="is_basic_submitted" value="Y" />
                <input name="" type="submit" value="Save"  class="btn" />
                <input name="" type="button" value="Cancel"  class="btn" onclick="closePersonalInfoDiv()"/>
            </div> 
            <div class="clr"></div>
        </div>
    </form>
    <!--end FORM TO MODIFY Personal Information-->
</div>
<!----------------------light box-------------------------------->
                                 <div class="lightbox image-delete" style="width: 400px; left: 100px;">
      <div class="close"><a href="javascript:void(0)" onclick="hide_dialog()"><img src="<?=base_url()?>images/close.png"  height="24px" width="24px" alt="" /></a></div>
      <div class="top"><div>&nbsp;</div></div>
      <div class="mid">
            <div class="heading" style="margin-bottom:0px;">
                  <div class="left">
                        <h4>Delete Profile Image</h4>
                  </div>
            </div>
               <div class="shade_box_white" style="padding:8px 0px;">
               <div style="padding-bottom:10px;">
               <p class="center-text" style="line-height:23px; color:#494949;">
                  Do you want to delete profile image ?
               </p>
               </div>
               <form action="" method="post" id="delfrm">
                  <input type="hidden" name="i_del_id" id="i_del_id" value="" />
                 <input name="" type="button" value="Yes" class="btn" style="margin-left:105px;" onClick="delete_profile_image()"/>
                 <input name="" type="button" value="No" class="btn" onclick="hide_dialog()"/>
               </form>   
               <div class="clr"></div>
            </div>
            
      </div>
      <div class="bot"><div>&nbsp;</div></div>
</div>
<script type="text/javascript">
function delete_profile_image(){
   // alert('ok')
   var id = $('#prf_id').val();
   //alert(id)
   showBusyScreen();
   $.ajax({
       
       type: 'post',
       url :'<?= base_url() ?>logged/my_profile/del_prf_img',
       dataType: 'json',
       data : {id:id},
       success: function (msg) {

				if(msg.success==true)
				{	
				showUIMsg('loading...');
					location.reload(); 
				}	
				else
				{
					showUIMsg("something went wrong. Please try again.");
				}
				
			}
       
   });
}



$(document).ready(function(){
  $("#txt_profile_pic").change(function() {

    var val = $(this).val();
    alert(val);

    switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase()){
        case 'gif': case 'jpg': case 'png':  case 'jpeg':
            alert("an image");
             $('#err_profile_pic').html('');
            break;
        default:
            $(this).val('');
            // error message here
            $('#err_profile_pic').html('Please enter valid image (jpg,jpeg,png,gif)');
            alert("not an image");
            break;
    }
});
})


</script>