<?php include(APPPATH . "views/layouts/logged_header.phtml"); ?>
<!-- NAVIGATION SECTION -->
<?php include(APPPATH . "views/layouts/nav.phtml"); ?>
<!-- /NAVIGATION SECTION -->
</div>
</div>


<!-- /HEADER SECTION -->
<div class="clr"></div>
<?php //pr($category_details,1); ?>
<!-- CONTENT SECTION -->
<div id="content_section" style="margin-top:8px;">
      <div id="container">
      		 
             
             <!-- Help Center Start-->
             <div class="help-center-main">
             
            
        <h2 class="page-title pull-left">Help Center </h2>
        <a onclick="goBack()" class="media-back" href="javascript:void(0)">Back</a>
        <br class="clr">
          <div class="search-main">
                 <form method="POST" id="help_search" name="help_search" action="<?= base_url() ?>logged/help_center/help_center_search" onsubmit="return true;">
                     <input type="text" placeholder="Find answers" class="search-box" name="help_key" value="<?= $help_tag ?>">
              <input type="button" value="Search" name="search" id="help_sub">
                 </form>
              
            </div>
        <script>
            $(document).ready(function(){
                $('#help_sub').click(function(){
                    $('#help_search').submit();
                })
                
            });
function goBack() {
    window.history.back()
}
</script>
        <div class="clear"></div>
		<div class="media-center-left">
                    <?php //pr($cat_name); ?>
        <h3><?php if($help_tag != NULL ){ echo 'Searching For '.$help_tag.''; }else{ echo 'All Result';}?></h3>
                    <?php 
                     if($Search_result != NULL){
                    foreach($Search_result as $val){
                    ?>
              <div class="textsearch-pan">                                
            <h4><a href="<?= base_url() ?><?= $val['id'] ?>/help_center_question_details"><?= $val['h_title']; ?></a></h4>
                        <p><?= nl2br(get_unformatted_string_edit(my_substr($val['h_des'],200))) ?> </p>
                    </div>
                    <?php }
                     }else{
                         ?><h3>No Result Found</h3>
                         <?php } ?>
<!--                
                    <div class="textsearch-pan">                                
            <h4><a href="javascript:void(0);">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></h4>
                        <p>Sed lacinia nisi et lacinia hendrerit. Nam eu molestie neque. Maecenas eget quam vitae augue pretium accumsan vitae et nisl. Vestibulum eget bibendum diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
                    </div>


                    <div class="textsearch-pan">
            <h4><a href="javascript:void(0);">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></h4>
                        <p>Sed lacinia nisi et lacinia hendrerit. Nam eu molestie neque. Maecenas eget quam vitae augue pretium accumsan vitae et nisl. Vestibulum eget bibendum diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
                    </div>

                    <div class="textsearch-pan">                                
            <h4><a href="javascript:void(0);">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></h4>
                        <p>Sed lacinia nisi et lacinia hendrerit. Nam eu molestie neque. Maecenas eget quam vitae augue pretium accumsan vitae et nisl. Vestibulum eget bibendum diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
                    </div>


                    <div class="textsearch-pan">
            <h4><a href="javascript:void(0);">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></h4>
                        <p>Sed lacinia nisi et lacinia hendrerit. Nam eu molestie neque. Maecenas eget quam vitae augue pretium accumsan vitae et nisl. Vestibulum eget bibendum diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
                    </div>-->
             </div>
             <div class="media-center-right">
                 <?php //pr($all_cat_name); ?>
             	<h3><a href="javascript:void(0);">Troubleshooting</a></h3>
                <div class="help-list"><ul>
                        <?php foreach ($all_cat_name as $val){ ?>
                	<li><a href="<?= base_url() ?><?= $val['id'] ?>/help_center_details"><?= $val['cat_name']; ?></a></li>
                        <?php } ?>
<!--                    <li><a href="javascript:void(0);">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="javascript:void(0);">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="javascript:void(0);">Lorem ipsum dolor sit amet</a></li>-->
                </ul></div>
             </div>
             
             <div class="clear"></div>

             </div>
      		
            <!-- Help Center End-->
                       
      </div>
      <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>


<?php include(APPPATH . "views/layouts/footer.phtml"); ?>

<?php /* ?>POPUPS AND SCRIPTS<?php */ ?>

<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>

