<div class="vid_com">
<?php
//pr($info_arr);
foreach($info_arr as $info){
    echo"<h1>".$info['s_title']."</h1>";
	$url = $info['s_video_file_name'];
preg_match(
        '/[\\?\\&]v=([^\\?\\&]+)/',
        $url,
        $matches
    );
$id = $matches[1];
 
$width = '320';
$height = '240';
echo '<object width="' . $width . '" height="' . $height . '"><param name="movie" value="http://www.youtube.com/v/' . $id . '&amp;hl=en_US&amp;fs=1?rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/' . $id . '&amp;hl=en_US&amp;fs=1?rel=0" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="' . $width . '" height="' . $height . '"></embed></object>';

}?>
</div>
<style>
    .vid_com{ margin: 15px 0 0 121px;}
</style>