<div id="myjquerymenu" class="jquerycssmenu">
            <ul>
			<?php
            $full_name = $_SERVER['PHP_SELF'];
            $name_array = explode('/',$full_name);
            $count = count($name_array);
            $page_name = $name_array[$count-1];
            ?>
                  <li><a href="my-wall.html" class="first <?php echo ($page_name=='my-wall' || $page_name=='my-profile' || $page_name=='my-friends' || $page_name=='friend-request' || $page_name=='search-invite-friends' || $page_name=='my-net-pals' || $page_name=='net-pal-request' || $page_name=='search-invite-net-pals' || $page_name=='my-photos' || $page_name=='manage-my-photo' || $page_name=='my-audios' || $page_name=='manage-my-audio' || $page_name=='my-videos' || $page_name=='manage-video-album' || $page_name=='my-msg-inbox' || $page_name=='my-msg-outbox' || $page_name=='my-msg-deleted-items' || $page_name=='buy-credit' || $page_name=='privacy-settings' || $page_name=='email-notification-settings' || $page_name=='sms-notification-settings' || $page_name=='my-account' || $page_name=='organize-calender-view')?'current':'';?> <?php if( isset($MAIN_MENU_SELECTED) && $MAIN_MENU_SELECTED==1 ) echo('current'); ?>"><span>Home</span></a>
                        <ul>
                              <!--<li><a href="my-wall.php">My Wall</a></li>-->
                              <li><a href="my-profile.html">My Profile</a> </li>
                              <li><a href="my-friends.html">My Friends Zone</a>
                                    <!--<ul>
                                          <li><a href="my-friends.php">My Friends</a> </li>
                                          <li><a href="friend-request.php">Friend Request</a> </li>
                                          <li><a href="search-invite-friends.php">Search  &amp;  Invite Friends</a> </li>
                                    </ul>-->
                              </li>
                              <li><a href="my-net-pals.html">My Net Pals Zone</a>
                                    <!--<ul>
                                          <li><a href="my-net-pals.php">My Net Pals</a> </li>
                                          <li><a href="net-pal-request.php">Net Pal Request</a> </li>
                                          <li><a href="search-invite-net-pals.php">Search  &amp;  Invite Net Pals</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-photos.html">My Photos</a>
                                    <!--<ul>
                                          <li><a href="my-photos.php">View My Photos</a> </li>
                                          <li><a href="manage-my-photo.php">Manage My Photo Albums </a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-audios.html">My Audios</a>
                                    <!--<ul>
                                          <li><a href="my-audios.php">View My Audios </a> </li>
                                          <li><a href="manage-my-audio.php">Manage My Audio Albums</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-videos.html">My Videos</a>
                                    <!--<ul>
                                          <li><a href="my-videos.php">View My Videos </a> </li>
                                          <li><a href="manage-video-album.php">Manage My Video Albums</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-msg-inbox.html">My Messages</a>
                                    <!--<ul>
                                          <li><a href="my-msg-inbox.php">Inbox </a> </li>
                                          <li><a href="my-msg-outbox.php">Sent Items</a> </li>
                                          <li><a href="my-msg-deleted-items.php">Deleted Items</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="buy-credit.html">Purchase SMS Credit</a> </li>
                              <li><a href="privacy-settings.html">My Privacy Settings</a> </li>
                              <li><a href="email-notification-settings.html">My Email Notification Settings</a> </li>
                              <li><a href="sms-notification-settings.html">My SMS Notification Settings</a> </li>
                              <li><a href="my-account.html">My Account</a> </li>
                              <li><a href="organize-calender-view.html">Organizer</a> </li>
                        </ul>
                  </li>
                  <li><a href="social-hub.html" class="<?php echo ($page_name=='social-hub' ||$page_name=='my-tweet' || $page_name=='search-follow-tweet' || $page_name=='my-blog' || $page_name=='search-blog' || $page_name=='browse-ring' || $page_name=='create-ring' || $page_name=='my-rings' || $page_name=='create-event' || $page_name=='my-events' || $page_name=='event-invitations-received' || $page_name=='browse-chat-room')?'current':'';?>"><span>Social&nbsp;Hub</span></a>
                        <ul>
                              <li><a href="my-tweet.html">Tweet</a>
                                    <!--<ul>
                                          <li><a href="my-tweet.php">View My Tweet </a> </li>
                                          <li><a href="search-follow-tweet.php">Search  &amp; Follow Tweet</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-blog.html">Blogs</a>
                                    <!--<ul>
                                          <li><a href="my-blog.php">My Blog </a> </li>
                                          <li><a href="search-blog.php">Search All Blogs</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-rings.html">Rings</a>
                                    <!--<ul>
                                          <li><a href="browse-ring.php">Browse  &amp;  Search Ring </a> </li>
                                          <li><a href="create-ring.php">Create New Ring</a> </li>
                                          <li><a href="my-rings.php">My Rings</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="my-events.html">Events</a>
                                    <!--<ul>
                                          <li><a href="create-event.php">Create Event </a> </li>
                                          <li><a href="my-events.php">My Events</a> </li>
                                          <li><a href="event-invitations-received.php">Event Invitations Received</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="browse-chat-room.html">Chat Rooms</a>
                                    <!--<ul>
                                          <li><a href="browse-chat-room.php">Browse Chat Rooms </a> </li>
                                    </ul> -->
                              </li>
                        </ul>
                  </li>
                  <li><a href="trade-center.html" class="<?php echo ($page_name=='trade-center' ||$page_name=='etrade-home' || $page_name=='buy-sent-request' || $page_name=='manage-product-listing' || $page_name=='buy-request-received' || $page_name=='eswap-home' || $page_name=='manage-swap-request-sent' || $page_name=='eswap-product-wishlist' || $page_name=='manage-swap-request-received' || $page_name=='efreebie-home' || $page_name=='efreebies-offered' || $page_name=='manage-freebie-request-received' || $page_name=='manage-freebie-request-sent' || $page_name=='trade-center-activities' || $page_name=='buy-product-listing-credit')?'current':'';?>"><span>Trade&nbsp;Center</span></a>
                        <ul>
                              <li><a href="etrade-home.html">eTrade</a>
                                    <!--<ul>
                                          <li><a href="etrade-home.php">eTrade Home</a> </li>
                                          <li><a href="buy-sent-request.php">Manage Buy Request Sent</a> </li>
                                          <li><a href="manage-product-listing.php">Manage My Products Listing</a> </li>
                                          <li><a href="buy-request-received.php">Manage Buy Request Received </a> </li>
                                    </ul>-->
                              </li>
                              <li><a href="eswap-home.html">eSwap</a>
                                    <!--<ul>
                                          <li><a href="eswap-home.php">eSwap Home</a> </li>
                                          <li><a href="manage-swap-request-sent.php">Manage Swap Request Sent</a> </li>
                                          <li><a href="eswap-product-wishlist.php">My eSwap Products and Wish List </a> </li>
                                          <li><a href="manage-swap-request-received.php">Manage Swap Request Received</a> </li>
                                    </ul>-->
                              </li>
                              <li><a href="efreebie-home.html">eFreebie</a>
                                    <!--<ul>
                                          <li><a href="efreebie-home.php">eFreebie Home</a> </li>
                                          <li><a href="efreebies-offered.php">eFreebies Offered</a> </li>
                                          <li><a href="manage-freebie-request-received.php">Manage Freebie Request Received</a> </li>
                                          <li><a href="manage-freebie-request-sent.php">Manage Freebie Request Sent</a> </li>
                                    </ul> -->
                              </li>
                              <li><a href="trade-center-activities.html">My Trade Center Activities</a> </li>
                              <li><a href="buy-product-listing-credit.html">Purchase Product Listing Credit</a> </li>
                        </ul>
                  </li>
                  <li><a href="media-center.html" class="<?php echo ($page_name=='media-center' || $page_name=='christian-news'|| $page_name=='christian-news-details' || $page_name=='gospel-magazine' || $page_name=='gospel-magazine-details' || $page_name=='christian-project-highlight' || $page_name=='christian-project-highlight-details')?'current':'';?>"><span>Media&nbsp;Center</span></a></li>
                  <li><a href="build-the-kingdom.html" class="<?php echo ($page_name=='build-the-kingdom' || $page_name=='giving.php' || $page_name=='my-prayer-partners.php' || $page_name=='prayer-partner-request.php' || $page_name=='search-invite-prayer-partner' || $page_name=='charity-project-home' || $page_name=='view-manage-projects' || $page_name=='minister-shout')?'current':'';?>"><span>Build&nbsp;The&nbsp;Kingdom</span></a>
                        <ul>
                              <li><a href="giving.html">Giving </a></li>
                              <li><a href="my-prayer-partners.html">Prayer Partners Zone</a>
                                    <!--<ul>
                                          <li><a href="my-prayer-partners.php">My Prayer Partners </a></li>
                                          <li><a href="prayer-partner-request.php">Prayer Partner Requests</a></li>
                                          <li><a href="search-invite-prayer-partner.php">Search  &amp;  Invite Prayer Partners</a></li>
                                    </ul> -->
                              </li>
                              <li><a href="charity-project-home.html">Charity Projects</a>
                                    <!--<ul>
                                          <li><a href="charity-project-home.php">Charity Project Home </a></li>
                                          <li><a href="view-manage-projects.php">View  &amp;  Manage My Projects</a></li>
                                    </ul> -->
                              </li>
                              <li><a href="javascript:void(0);">Salvation Prayer</a></li>
                              <li><a href="minister-shout.html">Ministers Shout</a></li>
                        </ul>
                  </li>
                  <li><a href="holy-place.html" class="<?php echo ($page_name=='holy-place' || $page_name=='read-bible-testament-view' || $page_name=='bible-quiz' || $page_name=='my-daily-bible-reading-plan' || $page_name=='library' || $page_name=='prayer-wall-home' || $page_name=='view-search-prayer-wall' || $page_name=='view-manage-prayer-posts-commitment' || $page_name=='view-search-eintercession' || $page_name=='view-manage-eintercession-commitments'  || $page_name=='view-manage-eintercession-commitments' || $page_name=='tesimony'  || $page_name=='find-church')?'current':'';?>"><span>Holy&nbsp;Place</span></a>
                        <ul>
                              <li><a href="javascript:void(0);">5 a Day</a></li>
                              <li><a href="read-bible-testament-view.html">Read Bible</a></li>
                              <li><a href="bible-quiz.html">Bible Quiz</a></li>
                              <li><a href="my-daily-bible-reading-plan.html">My Daily Bible Reading Plan</a></li>
                              <li><a href="library.html">Library</a></li>
                              <li><a href="prayer-wall-home.html">Prayer Wall</a>
                                    <!--<ul>
                                          <li><a href="prayer-wall-home.php">Prayer Wall Home</a></li>
                                          <li><a href="view-search-prayer-wall.php">View  &amp;  Search Prayer Wall</a></li>
                                          <li><a href="view-manage-prayer-posts-commitment.php">View  &amp;  Manage My Prayer Posts  &amp;  Commitments</a></li>
                                    </ul> -->
                              </li>
                              <li><a href="view-search-eintercession.html">E-Intercession</a>
                                    <!--<ul>
                                          <li><a href="view-search-eintercession.php">View  &amp;  Search E-Intercession</a></li>
                                          <li><a href="view-manage-eintercession-commitments.php">View  &amp;  Manage My E-Intercession Commitments</a></li>
                                    </ul> -->
                              </li>
                              <li><a href="tesimony.html">Testimony</a></li>
                              <li><a href="find-church.html">Find a Church </a></li>
                        </ul>
                  </li>
            </ul>
      </div>