<div class="timeline-part pull-left">
        	<div class="post-profile-pic"><img src="images/richard-pic.jpg" alt="Image" width="49" height="49">
            <span><a href="javavscript:void(0);">Richard</a>Updated on: 2:40</span></div>
            <figure><img src="images/prayer-post.jpg" alt="Prayer" width="477" height="244"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>  
        
      <div class="timeline-part pull-right">
        	<div class="post-profile-pic"><img src="images/sam-pic.jpg" alt="Image" width="49" height="49">
          <span><a href="javavscript:void(0);">Sam</a>Updated on: 2:40</span></div>
            <p>Hear from heaven, even from your dwelling-place, their prayer request, and maintain their cause, and forgive those who have sinned against you. Now, O my God, let, I urge you, your eyes be open, and let your ears be attentive, to the prayer request that is made in this place. Please grant it according to your will.</p>
        <figure><img src="images/church-pic.jpg" alt="Prayer" width="478" height="370"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>
        
        <div class="timeline-part pull-left">
        	<div class="post-profile-pic"><img src="images/sam-pic.jpg" alt="Image" width="49" height="49">
          <span><a href="javavscript:void(0);">Sam</a>Updated on: 2:40</span></div>
            <p>A Haitian man prays during an outdoor Mass in front of the destroyed presidential palace in downtown Port-au-Prince.</p>
        <figure><img src="images/hand.jpg" alt="Prayer" width="477" height="403"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>
        
        <div class="timeline-part pull-right">
        	<div class="post-profile-pic"><img src="images/sam-pic.jpg" alt="Image" width="49" height="49">
          <span><a href="javavscript:void(0);">Sam</a>Updated on: 2:40</span></div>
            <p>A new survey conducted by a Christian-based retailer finds that one-quarter of praying Americans believe all their prayers will be answered.</p>
        <figure><img src="images/baby.jpg" alt="Prayer" width="478" height="370"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>        
        <div class="timeline-part pull-left">
        	<div class="post-profile-pic"><img src="images/sam-pic.jpg" alt="Image" width="49" height="49">
          <span><a href="javavscript:void(0);">Sam</a>Updated on: 2:40</span></div>
            <p>A new survey conducted by a Christian-based retailer finds that one-quarter of praying Americans believe all their prayers will be answered.</p>
        <figure><img src="images/baby.jpg" alt="Prayer" width="478" height="370"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>
        
        <div class="timeline-part pull-right">
        	<div class="post-profile-pic"><img src="images/sam-pic.jpg" alt="Image" width="49" height="49">
          <span><a href="javavscript:void(0);">Sam</a>Updated on: 2:40</span></div>
            
        <figure><img src="images/quote.jpg" alt="Prayer" width="479" height="244"></figure>
            <div class="light_heading">
  <div class="left"> <a>Comment (0)</a> &nbsp; |   &nbsp; <a href="javascript:void(0);">Like (0)</a></div>
  
</div>
        </div>