 <img src="images/icons/calender-right.png" class="calender-left-arrow" alt="" onclick="show_cal_contents(<?=$selected_year?>,<?=$selected_month?>  ,<?=$selected_day?> , 'next')"/>
                            
 <img src="images/icons/calender-left.png" class="calender-left-arrow" alt="" onclick="show_cal_contents(<?=$selected_year?>,<?=$selected_month?>  ,<?=$selected_day?>,'prev')"/>
                          