<style>
.select-box{ width:105px !important;}
.right-gap{ float:right;margin-right:30px;}
.del_img{ cursor:pointer;}
.day-event{ cursor:pointer;}
.edit-list-label-nw{ width:33px;}
.nw-edit-select-box { width:90px !important;}
</style>
<?php include(APPPATH."views/layouts/logged_header.phtml");?>
            <!-- NAVIGATION SECTION -->
      <?php include(APPPATH."views/layouts/nav.phtml");?>
      <!-- /NAVIGATION SECTION -->
      </div>
</div>
<!-- /HEADER SECTION -->
<!-- CONTENT SECTION -->
<div id="content_section">
    <div id="container">
        <div id="top_corner">&nbsp;</div>
        <div id="mid_content">
            <!-- latest news -->
           <?php include(APPPATH ."views/layouts/latest_news.phtml");?>
            <!-- /latest news -->
            <div class="clr"></div>
            <!-- main container -->
            <div id="main_container">

                <!-- left container -->
                <?php include(APPPATH."views/layouts/leftbar.phtml");?>
                <!-- /left container -->




                <!-- mid container -->
                <div id="mid_container">
                    <div class="page_heading">
                        <div class="left"><img src="images/icons/calender2.png" alt=""  /> Organizer - </div>
                        <ul class="organizer-timer">
                            <li><a href="organizer-day-view.html" >Day</a></li> 
                            <li><a href="organizer-week-view.html" >Week</a></li> 
                            <li class="no-bg select"><a href="organizer-month-view.html" class="select">Month</a></li>
                        </ul>
                    </div>
                    <!--todays entry section start -->
                    <div class="todays-entry-block">


                        <div class="organize-calender-section">

                            <script type="text/javascript">
                                $(function() {
                                    $('#current-month').datepicker({
                                        numberOfMonths: 2,
										minDate: new Date(<?=(date('Y'))?>, <?=(date('m')-1)?>, <?=(date('d'))?> ,  0, 00),
									    onChangeMonthYear: function(y, m, i){                                
											show_cal_contents_by_month(y, m, '');
										},
										onSelect: function(selectedDate) { //alert(selectedDate);
											var day_arr = selectedDate.split('/');
											var val_date = day_arr[2]+'-'+day_arr[1]+'-'+day_arr[0];
											gotoDay(val_date);
										}
									});
									
                                });
							</script>

                            <div class="current-month" id="current-month"></div>

                        </div>

                            <div class="page_heading">
                             <?php
								$d_year = date('Y', mktime(0, 0, 0, $selected_month, $selected_day, $selected_year));
								$d_month = date('m', mktime(0, 0, 0, $selected_month, $selected_day, $selected_year));
	
								$PreviousMonth = date('m',mktime(0, 0, 0, $selected_month - 1, 1, $selected_year));
								$CurrentMonth = date('m',mktime(0, 0, 0, $selected_month, 1, $selected_year));
								$NextMonth = date('m',mktime(0, 0, 0, $selected_month + 1, 1, $selected_year));
								
								$PreviousYear = date('Y',mktime(0, 0, 0, $selected_month - 1, 1, $selected_year));
								$NextYear = date('Y',mktime(0, 0, 0, $selected_month + 1, 1, $selected_year)); 
								
								$display_date = date('F, Y',mktime(0, 0, 0, $selected_month, $selected_day, $selected_year));
								?>
								<div class="left line-height" id="displayDateDIV"><?php echo $display_date ?> </div>
	
								<span id="slider-span">
									<img src="images/icons/calender-right.png" class="calender-left-arrow" alt="" onclick="show_cal_contents_by_month(<?= $NextYear ?>, <?= $NextMonth ?>, 'next')"/>
	
									<img src="images/icons/calender-left.png" class="calender-left-arrow" alt="" onclick="show_cal_contents_by_month(<?=$PreviousYear?>,<?=$PreviousMonth?>,'prev')"/>
								</span>
                            <br class="clear"/>

                        </div>
                        
                         <ul class="calender-add-todolist">
                            <li><a href="javascript:void(0);">Add New Note</a></li>
                            <li><a href="javascript:void(0);">Add New ToDo List</a></li>
                        </ul>
                        <br class="clear"/>

                        <div class="add-cal-list">

                            <div class="shade_box_01 cal-list cal-list-1">
                                <form id="frmAddNote"  method="post" action="<?= base_url() . 'logged/organizer_day_view/add_note_ajax' ?>" onsubmit="return false;"  enctype="multipart/form-data" class="note-todo-form">

                                    <div class="lable-txt-nw">Add Note : </div>
                                    <textarea rows="" cols="" name="txt_desc" id="txt_desc" onKeyDown="limitText(this.form.txt_desc, this.form.countdown, 250);" onKeyUp="limitText(this.form.txt_desc, this.form.countdown, 250);"></textarea>
                                    <span id="err_desc" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span> 
                                    <br class="clear"/>
                                    
                                    
                                    <div class="lable-txt-nw">Date : </div>
                                    <div style="margin-top: 2px;">
                                    <input type="text"  value="" name="start_to2" id="start_to2"  readonly="readonly" style="width:93px;"/>
                                     <img src="images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" class="calender" />
                                     <script type="text/javascript">
										  var  dateToday = new Date();	
										  $(document).ready(function(arg) {
											  var inputDate = $("#start_to2");
												
											  $("#start_to2").datepicker({
											  minDate: dateToday,
											  dateFormat : 'dd/mm/yy',
											  altField: "#hd_date",
											  altFormat: "yy-mm-dd",
											  onClose: function (selectedDate) {
														var myDate = $(this).datepicker('getDate'); 
														$('#start_to2').datepicker('setDate', myDate);
														var formatted_dt = $.datepicker.formatDate('yy-mm-dd', myDate);
														$('#hd_date').val(formatted_dt);
														
													}
											  });
											  $('#start_to2').datepicker('setDate', dateToday);
										  });
									  </script>
                                    </div>
                                    <br class="clear"/>
                                  <?php /*?>  <span id="err_time" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span> 
                                    <?php */?>
                                    <div class="lable-txt-nw"> Remind Me At : </div>
                                    <select name="s_time" id="s_time" class="select-box nw-select-box rem_sel_box" >
                                        <option value="-1">Do not remind</option>
                                        <?= makeOption_time() ?>
                                    </select>
                                    <span id="err_time" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span> 									
                                    <input type="hidden" id="hd_date" name="hd_date" value="<?= getShortDate($selected_date, '8') ?>"/>
                                    <input type="hidden" id="hd_note_ajax_method" name="hd_note_ajax_method" value="week_slider_ajax_list" />

                                    <br class="clear"/>
                                    <div class="lable-txt-nw"></div>
                                    <div class="calader-lable-txt">
                                        <input name="Add" type="submit" value="Add" class="yellow-btn calader-float-left"/>
                                        <input name="cancel" type="button" value="Cancel" class="yellow-btn calader-float-left" onclick="$('.cal-list-1').slideToggle();
                                                clearFrmAdd('frmAddNote')" />
                                                <input type="hidden" id="frmnote" value="month_view" />
                                    </div>
                                    <br class="clear"/>
                                </form>

                            </div>



                            <div class="shade_box_01 cal-list cal-list-2">

                                <form id="frmAddTodolist"  method="post" action="<?= base_url() . 'logged/organizer_day_view/add_todo_ajax' ?>" onsubmit="return false;" enctype="multipart/form-data" class="note-todo-form">
                                    <div class="lable-txt-nw">Add Todo List : </div>
                                    <textarea name="ta_todo_desc" id="ta_todo_desc" onKeyDown="limitText(this.form.ta_todo_desc, this.form.countdown, 250);" 
                          onKeyUp="limitText(this.form.ta_todo_desc, this.form.countdown, 250);"></textarea>	
                                    <span id="err_todo_desc" class="error-message" style="margin-left: 130px;
                                          margin-top: -9px;"></span>
                                    <br class="clear"/>

                                    <div class="lable-txt-nw">Start Time :</div>
                                    <select class="select-box nw-select-box" name="todo_strt_frm" id="todo_strt_frm" onchange="generateEndtime($(this).val())">
                                        <option value="-1">Select</option>
                                        <?= makeOption_time() ?>
                                    </select>


                                    <span id="add_to_do_end_time"  class="right-gap">
                                        <div class="lable-txt-nw left-gap" style="text-align:none; ">End Time :</div>
                                        <select name="todo_end_frm" id="todo_end_frm" class="select-box nw-select-box">
                                            <?php /* ?><option value="-1">Select</option><?php */ ?>
                                            <?= makeOption_time() ?>
                                        </select>
                                    </span>

                                    <span id="err_todo_strt_frm" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span> 														
                                    <span id="err_todo_end_frm" class="error-message" style="margin-left: 374px;margin-top: -19px;"></span>
                                    <br class="clear"/>

                                    <div class="lable-txt-nw">Remind Me :</div>                                      
                                    <select name="todo_rem_time" id="todo_rem_time" class="select-box nw-select-box rem_sel_box">
                                        <option value="-1">Do not remind</option>
                                        <option value="00:15">15 Minutes</option>
                                        <option value="00:30">30 Minutes</option>
                                        <option value="00:45">45 Minutes</option> 
                                        <option value="01:00">1 Hour</option>
                                        <option value="02:00">2 Hours</option>
                                    </select>
                                    <span class="blue12"><strong>Back</strong></span>

                                    <span id="err_todo_rem_time" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span>
                                     <br class="clear"/>
                                    
                                    <div class="lable-txt-nw">Date : </div>
                                    <div style="margin-top: 2px;">
                                    <input type="text"  value="" name="start_to" id="start_to"  readonly="readonly" style="width:93px;"/>
                                     <img src="images/icons/cal.png" alt="" width="15" height="16" onclick="$(this).prev().focus()" class="calender" />
                                     <script type="text/javascript">
										var  dateToday = new Date();	
									
											 $(document).ready(function(arg) {
											  var inputDate = $("#start_to");
												
											  $("#start_to").datepicker({
											  minDate: dateToday,
											  dateFormat : 'dd/mm/yy',
											  altField: "#hd_tododate",
											  altFormat: "yy-mm-dd",
											  onClose: function (selectedDate) {
														var myDate = $(this).datepicker('getDate'); 
														$('#start_to').datepicker('setDate', myDate);
														var formatted_dt = $.datepicker.formatDate('yy-mm-dd', myDate);
														$('#hd_tododate').val(formatted_dt);
														
													}
											  });
											  
											  $('#start_to').datepicker('setDate', dateToday);
											  
										  });
									</script>
                                    </div>
                                    <span id="err_time" class="error-message" style="margin-left: 130px;margin-top: -8px;"></span> 
                                    
                                    <input type="hidden" id="hd_tododate" name="hd_tododate" value="<?= getShortDate($selected_date, '8') ?>"/>
                                    <input type="hidden" id="hd_list_ajax_method" name="hd_list_ajax_method" value="week_slider_ajax_list" />
                                    <br class="clear"/>
                                    <div class="lable-txt-nw"></div>
                                    <div class="calader-lable-txt">
                                        <input type="submit" class="yellow-btn calader-float-left" value="Add" name="Add" />
                                        <input type="button"  class="yellow-btn calader-float-left" value="Cancel" name="cancel" onclick="$('.cal-list-2').slideToggle('slow');
                                                clearFrmAdd('frmAddTodolist')" />
                                         <input type="hidden" id="frmlist" value="month_view" />
                                    </div>
                                </form>
                                <br class="clear"/>
                            </div>
                        </div>
                        

                        <!--calender start -->
                        <?php include( APPPATH . 'views/logged/organize/right_event_calendar.phtml' );?>
                       <!--calender end -->
						<div style="display:none;">
                        <form id="gotoFrm" action="<?=base_url().'organizer-day-view.html'?>" method="post"><input type="hidden" name="goto_date" id="goto_date" value="" /></form>
                        </div>


                    </div>
                    <!--todays entry section end -->
                </div>

                <!-- /left container -->
                <!-- right container -->
                <?php include(APPPATH . "views/layouts/rightbar.phtml"); ?>
                <!-- /right container -->
            </div>
            <!-- /main container -->
            <div class="clr"></div>
        </div>
        <div id="bot_corner">&nbsp;</div>
    </div>
    <div class="clr"></div>
</div>
<!-- /CONTENT SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php include(APPPATH . "views/layouts/footer.phtml"); ?>
<?php include(APPPATH . "views/logged/blocks/common_popup.phtml"); ?>
<!-- /FOOTER SECTION -->


<script type="text/javascript">

  $(document).ready(function() {
	  $('#month-select').jcarousel({
		  wrap: 'circular'
	  });
	  $('#year-select').jcarousel({
		  wrap: 'circular'
	  });
	  $('.ui-datepicker').show();
  });
	  
	
function show_cal_contents_by_month(year, month, type){
	
	var user_id = <?php echo intval(decrypt($this->session->userdata('user_id')));?> ;
	
	showBusyScreen();
	
		$.ajax({
			   type: "POST",
			   url: base_url+'base_controller/show_event_calendar/'+user_id+'/'+year+'/'+month+'/'+1+'/'+1,
			   dataType: 'json',
			   success: function(data,status){
				   $('#slider-span').html(data.sliderContent);
				   $('#calender').html(data.html);
				   $('#displayDateDIV').html(data.display_date);
				   hideBusyScreen();
				   
				  }
		 });	 
	
}
</script>
<style>
.nw-select-box{ text-transform:capitalize !important;}
.rem_sel_box{width:120px !important;}

</style>